### ISSUE TITLE
[Bug]: PyTorch 2.5.x vLLM 1.0.0 dev issue with tensor parallel size > 1

### ISSUE THREAD

**Issue by CortexEdgeUser** [vllm-project/vllm#10039]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

Hello, the latest version of vLLM with the wheels 1.0.0dev (pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl) causes issues with tensor parallel size when set above 1.

Task exception was never retrieved
future: <Task finished name='Task-2' coro=<MQLLMEngineClient.run_output_handler_loop() done, defined at /root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/engine/multiprocessing/client.py:175> exception=ZMQError('Operation not supported')>
Traceback (most recent call last):
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/engine/multiprocessing/client.py", line 181, in run_output_handler_loop
    while await self.output_socket.poll(timeout=VLLM_RPC_TIMEOUT
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/zmq/_future.py", line 400, in poll
    raise _zmq.ZMQError(_zmq.ENOTSUP)
zmq.error.ZMQError: Operation not supported
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<MQLLMEngineClient.run_output_handler_loop() done, defined at /root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/engine/multiprocessing/client.py:175> exception=ZMQError('Operation not supported')>
Traceback (most recent call last):
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/engine/multiprocessing/client.py", line 181, in run_output_handler_loop
    while await self.output_socket.poll(timeout=VLLM_RPC_TIMEOUT
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/zmq/_future.py", line 400, in poll
    raise _zmq.ZMQError(_zmq.ENOTSUP)
zmq.error.ZMQError: Operation not supported
Traceback (most recent call last):
  File "/root/miniconda3/envs/vlm3/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/scripts.py", line 195, in main
    args.dispatch_function(args)
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/scripts.py", line 41, in serve
    uvloop.run(run_server(args))
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/uvloop/init.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/uvloop/init.py", line 61, in wrapper
    return await main
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 580, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/root/miniconda3/envs/vlm3/lib/python3.10/contextlib.py", line 199, in aenter
    return await anext(self.gen)
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 107, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/root/miniconda3/envs/vlm3/lib/python3.10/contextlib.py", line 199, in aenter
    return await anext(self.gen)
  File "/root/miniconda3/envs/vlm3/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 201, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
/root/miniconda3/envs/vlm3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 24 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @robertgshaw2-neuralmagic

**Comment by BrennanCode1** [comment]
Any update on this ?

**Comment by JohnConnor123** [comment]
Same problem

**Comment by youkaichao** [comment]
please follow the issue template to report detailed information.

**Comment by JohnConnor123** [comment]
> please follow the issue template to report detailed information.

Okey, I will create new issue with all info
