### ISSUE TITLE
[Usage]: disable pydantic request validation

### ISSUE THREAD

**Issue by matbee-eth** [vllm-project/vllm#10093]
### Your current environment

How do I ignore request validation through the openai compatible api? I want to pass in custom roles.

### How would you like to use vllm

```
Error processing publish message
Traceback (most recent call last):
  File "/home/acidhax/dev/autogen/python/packages/autogen-core/src/autogen_core/application/_single_threaded_agent_runtime.py", line 385, in _process_publish
    await asyncio.gather(*responses)
  File "/home/acidhax/dev/autogen/python/packages/autogen-core/src/autogen_core/application/_single_threaded_agent_runtime.py", line 377, in _on_message
    return await agent.on_message(
  File "/home/acidhax/dev/autogen/python/packages/autogen-core/src/autogen_core/components/_routed_agent.py", line 468, in on_message
    return await h(self, message, ctx)
  File "/home/acidhax/dev/autogen/python/packages/autogen-core/src/autogen_core/components/_routed_agent.py", line 148, in wrapper
    return_value = await func(self, message, ctx)
  File "/home/acidhax/dev/autogen/python/packages/autogen-magentic-one/src/autogen_magentic_one/agents/base_agent.py", line 83, in handle_incoming_message
    await future
  File "/home/acidhax/dev/autogen/python/packages/autogen-magentic-one/src/autogen_magentic_one/agents/base_agent.py", line 49, in _process
    await self._handle_broadcast(message, ctx)
  File "/home/acidhax/dev/autogen/python/packages/autogen-magentic-one/src/autogen_magentic_one/agents/orchestrator.py", line 280, in _handle_broadcast
    await super()._handle_broadcast(message, ctx)
  File "/home/acidhax/dev/autogen/python/packages/autogen-magentic-one/src/autogen_magentic_one/agents/base_orchestrator.py", line 76, in _handle_broadcast
    next_agent = await self._select_next_agent(message.content)
  File "/home/acidhax/dev/autogen/python/packages/autogen-magentic-one/src/autogen_magentic_one/agents/orchestrator.py", line 288, in _select_next_agent
    await self._initialize_task(self._get_message_str(message), cancellation_token)
  File "/home/acidhax/dev/autogen/python/packages/autogen-magentic-one/src/autogen_magentic_one/agents/orchestrator.py", line 153, in _initialize_task
    response = await self._model_client.create(
  File "/home/acidhax/dev/autogen/python/packages/autogen-ext/src/autogen_ext/models/_openai/_openai_client.py", line 479, in create
    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future
  File "/home/acidhax/dev/autogen/python/.venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1633, in create
    return await self._post(
  File "/home/acidhax/dev/autogen/python/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/acidhax/dev/autogen/python/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
    return await self._request(
  File "/home/acidhax/dev/autogen/python/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1633, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "2 validation errors for ChatCompletionRequest\nmessages.1.user.name\n  Extra inputs are not permitted [type=extra_forbidden, input_value='UserProxy', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden\nmessages.2.user.name\n  Extra inputs are not permitted [type=extra_forbidden, input_value='Orchestrator', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden", 'type': 'BadRequestError', 'param': None, 'code': 400}

```

**Comment by DarkLight1337** [comment]
We do allow custom roles, as shown here: https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/chat_utils.py#L84

**Comment by DarkLight1337** [comment]
To better debug the issue, can you show your input?

**Comment by matbee-eth** [comment]
It's a project from autogen, and I figured out the issue, they attach a "name" property to each of the ChatCompletion request entries

**Comment by DarkLight1337** [comment]
This should be supported as shown here: https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/chat_utils.py#L112

**Comment by DarkLight1337** [comment]
This code passes for me

```py
from vllm.entrypoints.chat_utils import ChatCompletionMessageParam
from pydantic import TypeAdapter

TypeAdapter(ChatCompletionMessageParam).validate_python({"role": "user", "content": "My name is Bob", "name": "Bob"})
```

Can you try this on your end?
