### ISSUE TITLE
[Usage]: [XPU] offline_inference.py - RuntimeError: oneCCL: exec.cpp:122 start_workers: EXCEPTION: failed to start worker # 0 

### ISSUE THREAD

**Issue by rskasturi** [vllm-project/vllm#10109]
### Your current environment

```text
Collecting environment information...
[WARNING] Failed to create Level Zero tracer: 2013265921
WARNING 11-07 06:41:13 _logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 11-07 06:41:13 importing.py:15] Triton not installed or not compatible; certain GPU-related functions will not be available.
PyTorch version: 2.3.1+cxx11.abi
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.5
Libc version: glibc-2.35

Python version: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:24:24) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8468V
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
Stepping:                        8
Frequency boost:                 enabled
CPU max MHz:                     2401.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4800.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       4.5 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        192 MiB (96 instances)
L3 cache:                        195 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-47,96-143
NUMA node1 CPU(s):               48-95,144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] clip-anytorch==2.6.0
[pip3] intel_extension_for_pytorch==2.3.110+xpu
[pip3] numpy==1.26.4
[pip3] open-clip-torch==2.7.0
[pip3] pyzmq==26.2.0
[pip3] sentence-transformers==3.0.1
[pip3] torch==2.3.1+cxx11.abi
[pip3] torchaudio==2.3.1+cxx11.abi
[pip3] torchdiffeq==0.2.4
[pip3] torchsde==0.2.6
[pip3] torchvision==0.18.1+cxx11.abi
[pip3] transformers==4.46.2
[pip3] triton-xpu==3.0.0b1
[conda] intel-extension-for-pytorch 2.3.110+xpu              pypi_0    pypi
[conda] mkl                       2024.2.1                 pypi_0    pypi
[conda] mkl-dpcpp                 2024.2.1                 pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] onemkl-sycl-blas          2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-datafitting   2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-dft           2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-lapack        2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-rng           2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-sparse        2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-stats         2024.2.1                 pypi_0    pypi
[conda] onemkl-sycl-vm            2024.2.1                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.3.1+cxx11.abi          pypi_0    pypi
[conda] torchaudio                2.3.1+cxx11.abi          pypi_0    pypi
[conda] torchvision               0.18.1+cxx11.abi          pypi_0    pypi
[conda] transformers              4.46.2                   pypi_0    pypi
[conda] triton-xpu                3.0.0b1                  pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.3.post2.dev272+g29862b88.d20241107
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

```bash
oneccl-bind-pt                    2.3.100+xpu
```

Hardware:

```bash
(vllm-xpu-tp) ue5c01becfd98f8b9e769a8179f45cdf@idc-training-gpu-compute-04:~/dev/tp/vllm$ clinfo -l
Platform #0: Intel(R) OpenCL
 `-- Device #0: Intel(R) Xeon(R) Platinum 8468V
Platform #1: Intel(R) OpenCL Graphics
 +-- Device #0: Intel(R) Data Center GPU Max 1100
 +-- Device #1: Intel(R) Data Center GPU Max 1100
 +-- Device #2: Intel(R) Data Center GPU Max 1100
 +-- Device #3: Intel(R) Data Center GPU Max 1100
 +-- Device #4: Intel(R) Data Center GPU Max 1100
 +-- Device #5: Intel(R) Data Center GPU Max 1100
 +-- Device #6: Intel(R) Data Center GPU Max 1100
 `-- Device #7: Intel(R) Data Center GPU Max 1100
```

### How would you like to use vllm

While I'm running [examples/offline_inference.py](https://github.com/vllm-project/vllm/blob/main/examples/offline_inference.py) ending up on the error. I guess this issue is observed after adding support of https://github.com/vllm-project/vllm/pull/8884.

Do let me know If I'm missing any steps/add any relevant flags in the environment.

```bash
(vllm-xpu-tp) ue5c01becfd98f8b9e769a8179f45cdf@idc-training-gpu-compute-04:~/dev/tp/vllm$ python examples/offline_inference.py
[WARNING] Failed to create Level Zero tracer: 2013265921
WARNING 11-07 06:28:48 _logger.py:68] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 11-07 06:28:48 importing.py:15] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 11-07 06:28:55 llm_engine.py:247] Initializing an LLM engine (v0.6.3.post2.dev272+g29862b88.d20241107) with config: model='facebook/opt-125m', speculative_config=None, tokenizer='facebook/opt-125m', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=xpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=facebook/opt-125m, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=None)
WARNING 11-07 06:28:55 _logger.py:68] CUDA graph is not supported on XPU, fallback to the eager mode.
INFO 11-07 06:28:55 selector.py:231] Cannot use _Backend.FLASH_ATTN backend on XPU.
INFO 11-07 06:28:55 selector.py:166] Using IPEX attention backend.
2024:11:07-06:28:55:(3157777) |CCL_WARN| value of CCL_ATL_TRANSPORT changed to be ofi (default:mpi)
2024:11:07-06:28:55:(3157777) |CCL_WARN| value of CCL_LOCAL_RANK changed to be 0 (default:-1)
2024:11:07-06:28:55:(3157777) |CCL_WARN| value of CCL_LOCAL_SIZE changed to be 1 (default:-1)
2024:11:07-06:28:55:(3157777) |CCL_WARN| value of CCL_PROCESS_LAUNCHER changed to be none (default:hydra)
2024:11:07-06:28:56:(3157777) |CCL_ERROR| base_thread.cpp:22 start: error while creating worker thread #0 pthread_create returns 22
2024:11:07-06:28:56:(3157777) |CCL_ERROR| exec.cpp:122 start_workers: condition workers.back()->start(cpu_affinity, mem_affinity) == ccl::status::success failed
failed to start worker # 0
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/dev/tp/vllm/examples/offline_inference.py", line 14, in <module>
[rank0]:     llm = LLM(model="facebook/opt-125m")
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/utils.py", line 1028, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/entrypoints/llm.py", line 208, in __init__
[rank0]:     self.llm_engine = self.engine_class.from_engine_args(
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/engine/llm_engine.py", line 585, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/engine/llm_engine.py", line 347, in __init__
[rank0]:     self.model_executor = executor_class(vllm_config=vllm_config, )
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/executor/executor_base.py", line 36, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/executor/xpu_executor.py", line 27, in _init_executor
[rank0]:     GPUExecutor._init_executor(self)
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/executor/gpu_executor.py", line 39, in _init_executor
[rank0]:     self.driver_worker.init_device()
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/worker/xpu_worker.py", line 80, in init_device
[rank0]:     self.init_worker_distributed_environment()
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/vllm-0.6.3.post2.dev272+g29862b88.d20241107.xpu-py3.10.egg/vllm/worker/xpu_worker.py", line 178, in init_worker_distributed_environment
[rank0]:     torch.distributed.all_reduce(torch.zeros(1).xpu())
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/ue5c01becfd98f8b9e769a8179f45cdf/.conda/envs/vllm-xpu-tp/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2219, in all_reduce
[rank0]:     work = group.allreduce([tensor], opts)
[rank0]: RuntimeError: oneCCL: exec.cpp:122 start_workers: EXCEPTION: failed to start worker # 0
```

cc: @yma11 @zhouy

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by yma11** [comment]
@rskasturi There should be some problems with underlying oneCCL communication. You need to assure network works before try tp.

**Comment by rskasturi** [comment]
The offline example doesn't use any TP/PP even then I'm facing the issue. I'll give your suggestions a try!
Thank you!

**Comment by rskasturi** [comment]
Following suggestion from @yma11 helped me to bypass the checks, had to [comment](https://github.com/vllm-project/vllm/blob/main/vllm/worker/xpu_worker.py#L180).
Thank you!
