### ISSUE TITLE
[Bug]: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12

### ISSUE THREAD

**Issue by yananchen1989** [vllm-project/vllm#10300]
### Your current environment

i cannot execute collect_env.py  because of this error.

in my another environment: torch is 2.4.0 and the version of vllm is `0.6.3.post1` which works fine.

### 🐛 Describe the bug

following installation guide: [](https://docs.vllm.ai/en/stable/getting_started/installation.html#install-the-latest-code)

`vllm version: 0.6.3.post2.dev386+g0b8bb86b`

however, it forces the installation of torch to be `2.5.1`

which causes the error :

> Traceback (most recent call last):
>   File "/home/ubuntu/vllm/collect_env.py", line 15, in <module>
>     from vllm.envs import environment_variables
>   File "/home/ubuntu/vllm/vllm/__init__.py", line 3, in <module>
>     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
>   File "/home/ubuntu/vllm/vllm/engine/arg_utils.py", line 8, in <module>
>     import torch
>   File "/opt/conda/envs/vllmsource/lib/python3.11/site-packages/torch/__init__.py", line 367, in <module>
>     from torch._C import *  # noqa: F403
>     ^^^^^^^^^^^^^^^^^^^^^^
> ImportError: /opt/conda/envs/vllmsource/lib/python3.11/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by yananchen1989** [comment]
related issue: https://github.com/pytorch/pytorch/issues/111469

**Comment by yananchen1989** [comment]
`python -c "import torch"`

error:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/opt/conda/envs/vllmsource/lib/python3.11/site-packages/torch/__init__.py", line 367, in <module>
>     from torch._C import *  # noqa: F403
>     ^^^^^^^^^^^^^^^^^^^^^^
> ImportError: /opt/conda/envs/vllmsource/lib/python3.11/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12

**Comment by mbertrait** [comment]
I just encountered this issue, seems like the new torch 2.5.1 revive https://github.com/pytorch/pytorch/issues/111469

**Comment by Ecocytus** [comment]
Same issue for vllm==v0.6.4.post1 and torch==2.5.1. Cuda version 12.1.

**Comment by GallonDeng** [comment]
same issue, vllm==0.6.4.post1, torch==2.5.1

**Comment by piamo** [comment]
same issue, vllm==0.6.4.post1, torch==2.5.1

**Comment by chintan-ushur** [comment]
The fix is in progress, meanwhile here is a quick workaround:

```patchelf --add-rpath '$ORIGIN/../../nvidia/nvjitlink/lib' /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so```

Ref - [https://github.com/pytorch/pytorch/issues/140797](url)

**Comment by iseesaw** [comment]
> The fix is in progress, meanwhile here is a quick workaround:
> 
> `patchelf --add-rpath '$ORIGIN/../../nvidia/nvjitlink/lib' /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so ` Ref - [https://github.com/pytorch/pytorch/issues/140797](url)

This is very useful.

**Comment by fanfanaaaa** [comment]
it can solve the bug:
export LD_LIBRARY_PATH=/data/home/user/anaconda3/envs/vllm/lib/python3.10
/site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH

**Comment by Hambaobao** [comment]
> it can solve the bug: export LD_LIBRARY_PATH=/data/home/user/anaconda3/envs/vllm/lib/python3.10 /site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH

Very helpful.

**Comment by Cap-rgb** [comment]
> it can solve the bug: export LD_LIBRARY_PATH=/data/home/user/anaconda3/envs/vllm/lib/python3.10 /site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH

在2025年2月8日，测试这个解决方案成功。我的情况与vllm无关，单纯使用 `python -m venv test01` 创建虚拟环境，然后报上面的错。使用miniconda无误。

**Comment by tchaton** [comment]
Any updates ?

**Comment by neils2019** [comment]
> Any updates ?

Setting the LD_LIBRARY_PATH to search in the virtual environment directory first for the library works well,  update LD_LIBRARY_PATH=<path to /nvidia/nvjitlink/lib in virtual enviroment>:$LD_LIBRARY_PATH

**Comment by wfloveiu** [comment]
`unset LD_LIBRARY_PATH` works for me!

**Comment by kuailehaha** [comment]
A very useful method. For docker users (v0.7.3), the nvidia path at `/usr/local/lib/python3.12/dist-packages/nvidia/nvjitlink/lib`
so, 
```export LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH```

**Comment by kcxain** [comment]
> `unset LD_LIBRARY_PATH` works for me!

It works, thanks!

**Comment by leslie2046** [comment]
> it can solve the bug: export LD_LIBRARY_PATH=/data/home/user/anaconda3/envs/vllm/lib/python3.10 /site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH

works for me

**Comment by CauchyFanUpdate** [comment]
> it can solve the bug: export LD_LIBRARY_PATH=/data/home/user/anaconda3/envs/vllm/lib/python3.10 /site-packages/nvidia/nvjitlink/lib:$LD_LIBRARY_PATH

It is very useful !

**Comment by BiNLP** [comment]
> `unset LD_LIBRARY_PATH` works for me!

It works for me too! tks!
