### ISSUE TITLE
[Bug]: Unable to run Qwen2.5-0.5B-Instruct model in v0.6.4.post1 version, Error: No available memory for the cache blocks

### ISSUE THREAD

**Issue by Valdanitooooo** [vllm-project/vllm#10439]
### Your current environment

<details>
<summary>The commands in my Docker(vllm/vllm-openai:v0.6.4.post1)</summary>

```text
VLLM_ARGS=--trust-remote-code  --served-model-name=Qwen2.5-0.5B-Instruct --model=/storage-800GB/models/Qwen2.5-0.5B-Instruct --gpu-memory-utilization=0.4 --max-model-len=512 --enable-auto-tool-choice --tool-call-parser hermes --uvicorn-log-level debug --chat-template /storage-800GB/models/templates/template.jinja

python3 -m vllm.entrypoints.openai.api_server --port=5000 --host=0.0.0.0 ${VLLM_ARGS}
```

</details>

### Unique variable

When I revert back to the v0.6.3 version image, this model can run successfully.

### GPU info
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H800 PCIe               Off |   00000000:93:00.0 Off |                    0 |
| N/A   86C    P0            128W /  350W |   37789MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   1690103      C   /usr/bin/python3.10                         37760MiB |
+-----------------------------------------------------------------------------------------+
```

### Error
```
vllm-1  | INFO 11-18 18:07:17 api_server.py:585] vLLM API server version 0.6.4.post1
vllm-1  | INFO 11-18 18:07:17 api_server.py:586] args: Namespace(host='0.0.0.0', port=5000, uvicorn_log_level='debug', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template='/storage-800GB/models/templates/template.jinja', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=True, tool_call_parser='hermes', tool_parser_plugin='', model='/storage-800GB/models/Qwen2.5-0.5B-Instruct', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', chat_template_text_format='string', trust_remote_code=True, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=512, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.4, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['Qwen2.5-0.5B-Instruct'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
vllm-1  | INFO 11-18 18:07:17 api_server.py:175] Multiprocessing frontend to use ipc:///tmp/b0076790-edae-427c-8435-140c057908d8 for IPC Path.
vllm-1  | INFO 11-18 18:07:17 api_server.py:194] Started engine process with PID 76
vllm-1  | INFO 11-18 18:07:21 config.py:350] This model supports multiple tasks: {'embedding', 'generate'}. Defaulting to 'generate'.
vllm-1  | WARNING 11-18 18:07:21 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
vllm-1  | INFO 11-18 18:07:26 config.py:350] This model supports multiple tasks: {'generate', 'embedding'}. Defaulting to 'generate'.
vllm-1  | WARNING 11-18 18:07:26 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
vllm-1  | INFO 11-18 18:07:26 llm_engine.py:249] Initializing an LLM engine (v0.6.4.post1) with config: model='/storage-800GB/models/Qwen2.5-0.5B-Instruct', speculative_config=None, tokenizer='/storage-800GB/models/Qwen2.5-0.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=512, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen2.5-0.5B-Instruct, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=None)
vllm-1  | INFO 11-18 18:07:26 selector.py:135] Using Flash Attention backend.
vllm-1  | INFO 11-18 18:07:27 model_runner.py:1072] Starting to load model /storage-800GB/models/Qwen2.5-0.5B-Instruct...
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.32it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.32it/s]
vllm-1  |
vllm-1  | INFO 11-18 18:07:28 model_runner.py:1077] Loading model weights took 0.9276 GB
vllm-1  | INFO 11-18 18:07:28 worker.py:232] Memory profiling results: total_gpu_memory=79.10GiB initial_memory_usage=38.40GiB peak_torch_memory=2.34GiB memory_usage_post_profile=38.49GiB non_torch_memory=37.54GiB kv_cache_size=-8.24GiB gpu_memory_utilization=0.40
vllm-1  | INFO 11-18 18:07:28 gpu_executor.py:113] # GPU blocks: 0, # CPU blocks: 21845
vllm-1  | INFO 11-18 18:07:28 gpu_executor.py:117] Maximum concurrency for 512 tokens per request: 0.00x
vllm-1  | ERROR 11-18 18:07:28 engine.py:366] No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
vllm-1  | ERROR 11-18 18:07:28 engine.py:366] Traceback (most recent call last):
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     return cls(ipc_path=ipc_path,
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
vllm-1  | Process SpawnProcess-1:
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 350, in __init__
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     self._initialize_kv_caches()
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 500, in _initialize_kv_caches
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/gpu_executor.py", line 120, in initialize_cache
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 268, in initialize_cache
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     raise_if_cache_size_invalid(num_gpu_blocks,
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 493, in raise_if_cache_size_invalid
vllm-1  | ERROR 11-18 18:07:28 engine.py:366]     raise ValueError("No available memory for the cache blocks. "
vllm-1  | ERROR 11-18 18:07:28 engine.py:366] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
You can try reducing the `gpu_memory_utilization` . For more details, please refer to: https://github.com/vllm-project/vllm/issues/10357#issuecomment-2478421215

**Comment by Valdanitooooo** [comment]
> gpu_memory_utilization

I have tried many numbers between 0.03 and 0.4, but they all have the same error
```
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```

**Comment by jeejeelee** [comment]
> > gpu_memory_utilization
> 
> I have tried many numbers between 0.03 and 0.4, but they all have the same error
> 
> ```
> ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
> ```

plz try increasing  gpu_memory_utilization,e.g. 0.5,0.6

**Comment by DarkLight1337** [comment]
`--gpu-memory-utilization` refers to the final capacity taken up by vLLM + other processes, not just vLLM itself. So if your GPU is already 40% used up for example, you should set a larger value (e.g. 95%) so vLLM can use 55% of the GPU.

**Comment by Valdanitooooo** [comment]
> plz try increasing gpu_memory_utilization,e.g. 0.5,0.6

@jeejeelee @DarkLight1337 My GPU has 80GB VRAM, and it's hard for me to imagine allocating more than 40GB VRAM to a 0.5B model

**Comment by DarkLight1337** [comment]
> `--gpu-memory-utilization` refers to the final capacity taken up by vLLM + other processes, not just vLLM itself. So if your GPU is already 40% used up for example, you should set a larger value (e.g. 95%) so vLLM can use 55% of the GPU.

See this. Since 40% of your GPU is already used, setting it to 0.5 will only leave 10% for vLLM.

**Comment by Valdanitooooo** [comment]
@jeejeelee @DarkLight1337 Thank you, I successfully ran the model when I changed it to 0.9, which consumed 27.5GB 
 VRAM 🥲
