### ISSUE TITLE
[Feature]: LoRA fine-tuning model for DeepSeek V2

### ISSUE THREAD

**Issue by Z-Diviner** [vllm-project/vllm#10446]
### 🚀 The feature, motivation and pitch

I'm glad to use the vLLM framework to accelerate LLM inference. Could you provide support for the LoRA fine-tuned model of DeepSeek V2?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Could you plz provibe your lora config, I am glad to add lora for this model

**Comment by AlexanderZhk** [comment]
> ig

not original poster, but my `adapter_config.json`

```
{
  "alpha_pattern": {},
  "auto_mapping": null,
  "base_model_name_or_path": "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layer_replication": null,
  "layers_pattern": null,
  "layers_to_transform": null,
  "loftq_config": {},
  "lora_alpha": 50,
  "lora_dropout": 0.01,
  "megatron_config": null,
  "megatron_core": "megatron.core",
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 50,
  "rank_pattern": {},
  "revision": null,
  "target_modules": [
    "kv_a_proj_with_mqa",
    "o_proj",
    "down_proj",
    "kv_b_proj",
    "q_proj",
    "gate_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM",
  "use_dora": false,
  "use_rslora": false
}```

With VLLM 0.7.2:
`AssertionError: DeepseekV2ForCausalLM does not support LoRA yet.`

**Comment by bi1101** [comment]
@jeejeelee is this not yet supported because `Fused MoE` as well?

**Comment by jeejeelee** [comment]
> [@jeejeelee](https://github.com/jeejeelee) is this not yet supported because `Fused MoE` as well?

Yeah, Fused MoE is the root reason

**Comment by josephrocca** [comment]
Could this be re-opened? IIUC, it is still not supported as of latest vLLM version. Now that together.ai [supports lora finetuning of DeepSeek](https://www.together.ai/blog/fine-tuning-updates-sept-2025) for a few dollars, I excitedly gave it a shot, but their own endpoints don't allow controlling lora scale/strength, and vLLM gives this message:

> (Worker_TP1 pid=12939) WARNING 11-13 01:16:18 [models.py:66] For MoE models, vLLM currently does not support fused MoE LoRA inference. Please ensure that the loaded LoRA model does not contain expert weights

<details>
<summary>Click for logs</summary>
```
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706] WorkerProc hit an exception.                                                                                                                                                         
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706] Traceback (most recent call last):                                                                                                                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 701, in worker_busy_loop                                                               
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     output = func(*args, **kwargs)                                                                                                                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]              ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context                                                                           
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     return func(*args, **kwargs)                                                                                                                                                     
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                     
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 279, in determine_available_memory                                                               
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self.model_runner.profile_run()                                                                                                                                                  
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3683, in profile_run                                                                       
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     hidden_states, last_hidden_states = self._dummy_run(                                                                                                                             
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]                                         ^^^^^^^^^^^^^^^^                                                                                                                             
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context                                                                           
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     return func(*args, **kwargs)                                                                                                                                                     
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                     
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3351, in _dummy_run                                                                        
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     with self.maybe_dummy_run_with_lora(                                                                                                                                             
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__                                                                                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     return next(self.gen)                                                                                                                                                            
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]            ^^^^^^^^^^^^^^                                                                                                                                                            
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/worker/lora_model_runner_mixin.py", line 165, in maybe_dummy_run_with_lora                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     with (                                            
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__                                                                                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     return next(self.gen)                                                                                                                                                            
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]            ^^^^^^^^^^^^^^                                                                                                                                                            
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/worker/lora_model_runner_mixin.py", line 152, in maybe_select_dummy_loras                                                    
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self._set_active_loras(                                                                                                                                                          
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/v1/worker/lora_model_runner_mixin.py", line 67, in _set_active_loras                                                            
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self.lora_manager.set_active_adapters(lora_requests, lora_mapping)                                                                                                               
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/lora/worker_manager.py", line 170, in set_active_adapters                                                                       
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self._apply_adapters(requests)                                                                                                                                                   
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/lora/worker_manager.py", line 249, in _apply_adapters                                                                           
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self.add_adapter(lora)                                                                                                                                                           
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/lora/worker_manager.py", line 277, in add_adapter                                                                               
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self._adapter_manager.activate_adapter(lora_request.lora_int_id)                                                                                                                 
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/lora/models.py", line 816, in activate_adapter                                                                                  
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     result = super().activate_adapter(lora_id)                                                                                                                                       
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                       
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/lora/models.py", line 453, in activate_adapter                                                                                  
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     module.set_lora(                                                                                                                                                                 
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]   File "/root/venv/lib/python3.12/site-packages/vllm/lora/layers/base_linear.py", line 137, in set_lora                                                                              
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]     self.lora_a_stacked[0][index, 0, : lora_a.shape[0], : lora_a.shape[1]].copy_(                                                                                                    
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706]                                        ^^^^^^^^^^^^                                                                                                                                  
(Worker_TP3 pid=12941) ERROR 11-13 01:16:19 [multiproc_executor.py:706] AttributeError: 'NoneType' object has no attribute 'shape'
```

</details>

Here's the (very undertrained) lora I was testing, in case it's helpful for debugging/implementing:

* https://drive.google.com/file/d/1AtGXJwo47fhuTPEkMFII1pJAbqMjzN5G/view?usp=sharing
