### ISSUE TITLE
[Usage]: What's the relationship between KV cache and MAX_SEQUENCE_LENGTH.

### ISSUE THREAD

**Issue by GRuuuuu** [vllm-project/vllm#10517]
### Your current environment

GPU : H100 80G *2
Model : Llama 3.1 70B

Model Params:
~~~
      env:
        - name: MODEL_NAME
          value: /mnt/models/models--meta-llama--llama-3-1-70b-instruct
        - name: DTYPE_STR
          value: float16
        - name: MAX_SEQUENCE_LENGTH
          value: '20000'
        - name: MAX_BATCH_SIZE
          value: '4'
        - name: MAX_NEW_TOKENS
          value: '4096'
        - name: MAX_LOG_LEN
          value: '100'
        - name: DEFAULT_INCLUDE_STOP_SEQS
          value: 'false'
        - name: NUM_GPUS
          value: '2'
        - name: CUDA_VISIBLE_DEVICES
          value: '0,1'
        - name: HUGGINGFACE_HUB_CACHE
          value: /mnt/models/
        - name: HF_MODULES_CACHE
          value: /tmp/huggingface/modules
        - name: PORT
          value: '3000'
~~~

Initializing an LLM engine (v0.5.4) with config
~~~
model='/mnt/models/models--meta-llama--llama-3-1-70b-instruct', speculative_config=None, tokenizer='/mnt/models/models--meta-llama--llama-3-1-70b-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/mnt/models/models--meta-llama--llama-3-1-70b-instruct, use_v2_block_manager=False, enable_prefix_caching=False)
~~~

### How would you like to use vllm

Hello, I'm trying to serve `Llama 3.1 70B` on 2*H100 80G. **I know This might cause an error because of lack of GPU memory.**  

and actually I got this error message:  
~~~
INFO 11-20 08:34:06 distributed_gpu_executor.py:56] # GPU blocks: 1498, # CPU blocks: 1638
Process SpawnProcess-1:
ERROR 11-20 08:34:06 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 118 died, exit code: -15
INFO 11-20 08:34:06 multiproc_worker_utils.py:123] Killing local vLLM worker processes
Traceback (most recent call last):
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/entrypoints/openai/rpc/server.py", line 222, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/entrypoints/openai/rpc/server.py", line 26, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(async_engine_args,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 735, in from_engine_args
    engine = cls(
             ^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 631, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 830, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 267, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/llm_engine.py", line 282, in __init__
    self._initialize_kv_caches()
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/llm_engine.py", line 401, in _initialize_kv_caches
    self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py", line 62, in initialize_cache
    self._run_workers("initialize_cache",
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 192, in _run_workers
    driver_worker_output = driver_worker_method(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/worker/worker.py", line 226, in initialize_cache
    raise_if_cache_size_invalid(num_gpu_blocks,
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/worker/worker.py", line 445, in raise_if_cache_size_invalid
    raise ValueError(
ValueError: The model's max seq len (131072) is larger than the maximum number of tokens that can be stored in KV cache (23968). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
~~~

Error message said KV cache is not enough to store model's max seq length. So I decreased `MAX_SEQUENCE_LENGTH` 131072 to 24000 and got same error message :  
~~~
ValueError: The model's max seq len (24000) is larger than the maximum number of tokens that can be stored in KV cache (6592). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
~~~

and then I decreased `MAX_SEQUENCE_LENGTH`  again. 24000 -> 20000 
~~~
ValueError: The model's max seq len (20000) is larger than the maximum number of tokens that can be stored in KV cache (10944). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
~~~

So I tested few cases: 
max_seq_len|kv_cache||
---|---|---
131072|23968|# GPU blocks: 1498, # CPU blocks: 1638
120000|23968|
24000|6592 | # GPU blocks: 412, # CPU blocks: 1638
20000|10944 |# GPU blocks: 684, # CPU blocks: 1638
16000 |15328|

### My question is:   
Why doesn’t the kv_cache consistently increase or decrease as the `MAX_SEQUENCE_LENGTH` decreases?
**What is the relationship between `MAX_SEQUENCE_LENGTH` and KV_Cache?**   
I also dig into source code, and find some calculation logic (it might be wrong... Please correct me)

![image](https://github.com/user-attachments/assets/8d2dae3f-f1ff-427b-b45d-1876b8273180)

I can't understand how `MAX_SEQUENCE_LENGTH` effect KV_cache... 
Please share the knowledge and give me an advise! 

Thank you!!!

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by kaspersiminski** [comment]
+1, It is strange that in my case I can run 20k,  35k, or 45k, but if I set --max-model-len to 29k it throws an error
GPU: RTX 3090
MODEL: meta-llama/Llama-3.1-8B-Instruct

20k - OK
```
Loading model weights took 14.9888 GB
Memory profiling results: total_gpu_memory=23.58GiB initial_memory_usage=15.34GiB peak_torch_memory=17.06GiB memory_usage_post_profile=15.35GiB non_torch_memory=0.35GiB kv_cache_size=3.81GiB gpu_memory_utilization=0.90
GPU blocks: 1952, # CPU blocks: 2048
Maximum concurrency for 20000 tokens per request: 1.56x
```

**29k - BAD**
```
Loading model weights took 14.9888 GB
Memory profiling results: total_gpu_memory=23.58GiB initial_memory_usage=15.34GiB peak_torch_memory=17.98GiB memory_usage_post_profile=15.35GiB non_torch_memory=0.35GiB kv_cache_size=2.89GiB gpu_memory_utilization=0.90
# GPU blocks: 1478, # CPU blocks: 2048
Maximum concurrency for 29000 tokens per request: 0.82x
The model's max seq len (29000) is larger than the maximum number of tokens that can be stored in KV cache (23648). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
```

35k - OK
```
Loading model weights took 14.9888 GB
Memory profiling results: total_gpu_memory=23.58GiB initial_memory_usage=15.34GiB peak_torch_memory=15.05GiB memory_usage_post_profile=15.37GiB non_torch_memory=0.37GiB kv_cache_size=5.80GiB gpu_memory_utilization=0.90
# GPU blocks: 2971, # CPU blocks: 2048
Maximum concurrency for 35000 tokens per request: 1.36x
```

45k - OK
```
Loading model weights took 14.9888 GB
Memory profiling results: total_gpu_memory=23.58GiB initial_memory_usage=15.34GiB peak_torch_memory=15.05GiB memory_usage_post_profile=15.37GiB non_torch_memory=0.37GiB kv_cache_size=5.80GiB gpu_memory_utilization=0.90
# GPU blocks: 2971, # CPU blocks: 2048
Maximum concurrency for 45000 tokens per request: 1.06x
```

If this is expected, I think there should be a link or more detailed information explaining why the KV cache behaves this way.
