### ISSUE TITLE
RuntimeError: CUDA error: OS call failed or operation not supported on this OS 

### ISSUE THREAD

**Issue by kchanLuo** [vllm-project/vllm#1054]
I get an error when I use Vllm to speed up model inference:

When I first use 4 A100*40G graphics cards, I can reason normally, but when I use 8 3090 * 24G graphics cards, I get an error. The specific error information is as follows:
```
(base) root@I1516380d0c001014e6:/hy-tmp/vllm_test# python test.py
2023-09-15 12:33:58,024 INFO worker.py:1621 -- Started a local Ray instance.
INFO 09-15 12:33:59 llm_engine.py:72] Initializing an LLM engine with config: model='/hy-tmp/openbuddy-llama2-70b-v10.1-bf16', tokenizer='/hy-tmp/openbuddy-llama2-70b-v10.1-bf16', tokenizer_mode=auto, revision=None, trust_remote_code=True, dtype=torch.bfloat16, download_dir=None, load_format=auto, tensor_parallel_size=8, seed=0)
INFO 09-15 12:33:59 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 09-15 12:35:28 llm_engine.py:201] # GPU blocks: 7384, # CPU blocks: 6553
Traceback (most recent call last):
  File "test3.py", line 22, in <module>
    llm = LLM(model="/hy-tmp/openbuddy-llama2-70b-v10.1-bf16", tensor_parallel_size=8, trust_remote_code=True)
  File "/hy-tmp/vllm/vllm/entrypoints/llm.py", line 68, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/hy-tmp/vllm/vllm/engine/llm_engine.py", line 225, in from_engine_args
    engine = cls(*engine_configs,
  File "/hy-tmp/vllm/vllm/engine/llm_engine.py", line 107, in __init__
    self._init_cache()
  File "/hy-tmp/vllm/vllm/engine/llm_engine.py", line 213, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/hy-tmp/vllm/vllm/engine/llm_engine.py", line 691, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::RayWorker.execute_method() (pid=22585, ip=172.17.0.3, actor_id=bbbdc3cd7dbfc07f3ed46f7d01000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f7fa5f155e0>)
  File "/hy-tmp/vllm/vllm/engine/ray_utils.py", line 29, in execute_method
    return executor(*args, **kwargs)
  File "/hy-tmp/vllm/vllm/worker/worker.py", line 139, in init_cache_engine
    self.cache_engine = CacheEngine(self.cache_config, self.model_config,
  File "/hy-tmp/vllm/vllm/worker/cache_engine.py", line 45, in __init__
    self.cpu_cache = self.allocate_cpu_cache()
  File "/hy-tmp/vllm/vllm/worker/cache_engine.py", line 99, in allocate_cpu_cache
    key_blocks = torch.empty(
RuntimeError: CUDA error: OS call failed or operation not supported on this OS
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

Here's the code I ran:

```

import torch
from vllm import LLM, SamplingParams

# Set the number of GPUs you want to use
num_gpus = 8 # Change this to the number of GPUs you have

# Define your prompts and sampling parameters
prompts = """You are a helpful, respectful and honest INTP-T AI Assistant named Buddy. You are talking to a human User.
Always answer as helpfully and logically as possible, while being safe. Your answers should not include any harmful, political, religious, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.
You are trained by OpenBuddy team, (https://openbuddy.ai, https://github.com/OpenBuddy/OpenBuddy), you are based on LLaMA and Falcon transformers model, not related to GPT or OpenAI.

User: What to do with insomnia?
Assistant:"""
sampling_params = SamplingParams(temperature=1, top_p=0.6, top_k=50, max_tokens=256, stop="</s>")

# Initialize the VLLM model
llm = LLM(model="/hy-tmp/openbuddy-llama2-70b-v10.1-bf16", tensor_parallel_size=8, trust_remote_code=True)

# Move the model to GPUs
llm = torch.nn.DataParallel(llm, device_ids=list(range(num_gpus)))

# Generate outputs
outputs = llm.module.generate(prompts, sampling_params)

# Print the outputs
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

```

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by hzhx7707** [comment]
if this issue has been resolved?
