### ISSUE TITLE
[Doc]: Docker+vllm+fastchat deploys multimodal large model Qwen2-vl-7b-instruct(docker+vllm+fastchat部署多模态大模型Qwen2-vl-7b-instruct)

### ISSUE THREAD

**Issue by Aanlifire** [vllm-project/vllm#10566]
### 📚 The doc issue

When testing using the following method, an error is reported, and the terminal log results are shown as follows:

curl -X POST http:(base) root@lxing:~# curl -X POST http://127.0.0.1:8000/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
  "model": "Qwen2-VL-7B-Instruct",
  "messages": [{"role": "user", "content": "你好！"}],
  "temperature": 1.0,
  "max_tokens": 100
}'
{"object":"error","message":"Internal Server Error","code":50001}

2024-11-22 02:50:27 | INFO | stdout | INFO:     127.0.0.1:55822 - "POST /model_details HTTP/1.1" 200 OK 
2024-11-22 02:50:27 | INFO | stdout | INFO:     127.0.0.1:55838 - "POST /count_token HTTP/1.1" 200 OK
2024-11-22 02:50:27 | INFO | stdout | INFO:     127.0.0.1:55844 - "POST /worker_generate HTTP/1.1" 500 Internal Server Error
2024-11-22 02:50:27 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-11-22 02:50:27 | ERROR | stderr | Traceback (most recent call last):
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
2024-11-22 02:50:27 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-11-22 02:50:27 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     raise exc
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-11-22 02:50:27 | ERROR | stderr |     raise exc
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-11-22 02:50:27 | ERROR | stderr |     await app(scope, receive, sender)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
2024-11-22 02:50:27 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
2024-11-22 02:50:27 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
2024-11-22 02:50:27 | ERROR | stderr |     await self.app(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
2024-11-22 02:50:27 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-11-22 02:50:27 | ERROR | stderr |     raise exc
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2024-11-22 02:50:27 | ERROR | stderr |     await app(scope, receive, sender)
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
2024-11-22 02:50:27 | ERROR | stderr |     response = await f(request)
2024-11-22 02:50:27 | ERROR | stderr |                ^^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
2024-11-22 02:50:27 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-11-22 02:50:27 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
2024-11-22 02:50:27 | ERROR | stderr |     return await dependant.call(**values)
2024-11-22 02:50:27 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastchat/serve/vllm_worker.py", line 217, in api_generate
2024-11-22 02:50:27 | ERROR | stderr |     output = await worker.generate(params)
2024-11-22 02:50:27 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastchat/serve/vllm_worker.py", line 173, in generate
2024-11-22 02:50:27 | ERROR | stderr |     async for x in self.generate_stream(params):
2024-11-22 02:50:27 | ERROR | stderr |   File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastchat/serve/vllm_worker.py", line 106, in generate_stream
2024-11-22 02:50:27 | ERROR | stderr |     sampling_params = SamplingParams(
2024-11-22 02:50:27 | ERROR | stderr |                       ^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
```
2024-11-22 02:50:27 | ERROR | stderr | File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastchat/serve/vllm_worker.py", line 106, in generate_stream
2024-11-22 02:50:27 | ERROR | stderr | sampling_params = SamplingParams(
2024-11-22 02:50:27 | ERROR | stderr | ^^^^^^^^^^^^^^^
2024-11-22 02:50:27 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'
```

This looks like an incompatibility between FastChat and vLLM versions.

**Comment by DarkLight1337** [comment]
If FastChat doesn't correctly specify vLLM dependency, please open an issue on their repo instead.

**Comment by Aanlifire** [comment]
> ```
> 2024-11-22 02:50:27 | ERROR | stderr | File "/app/miniconda3/envs/vllm/lib/python3.12/site-packages/fastchat/serve/vllm_worker.py", line 106, in generate_stream
> 2024-11-22 02:50:27 | ERROR | stderr | sampling_params = SamplingParams(
> 2024-11-22 02:50:27 | ERROR | stderr | ^^^^^^^^^^^^^^^
> 2024-11-22 02:50:27 | ERROR | stderr | TypeError: Unexpected keyword argument 'use_beam_search'
> ```
> 
> This looks like an incompatibility between FastChat and vLLM versions.这看起来像是 FastChat 和 vLLM 版本之间的不兼容。

How should this problem be solved? Which versions are compatible between fastchat and vllm?

**Comment by DarkLight1337** [comment]
Since fastchat uses vLLM (rather than the other way around), I suggest looking at the dependencies defined on their repo and install the exact version they use.

**Comment by Aanlifire** [comment]
> Since fastchat uses vLLM (rather than the other way around), I suggest looking at the dependencies defined on their repo and install the exact version they use.由于 fastchat 使用 vLLM（而不是相反），我建议查看其存储库上定义的依赖项并安装他们使用的确切版本。

Thank you very much. I will give it a try
