### ISSUE TITLE
[Bug]: about NCCL error：unhandled system error

### ISSUE THREAD

**Issue by wlll123456** [vllm-project/vllm#10626]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.12.2
Libc version: glibc-2.27

Python version: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 12.6.77
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40
GPU 4: NVIDIA A40
GPU 5: NVIDIA A40
GPU 6: NVIDIA A40
GPU 7: NVIDIA A40

Nvidia driver version: 560.28.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              86
On-line CPU(s) list: 0-85
Thread(s) per core:  2
Core(s) per socket:  43
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:            6
CPU MHz:             2593.902
BogoMIPS:            5187.80
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-85
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid md_clear

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.46.2
[pip3] transformers-stream-generator==0.0.4
[pip3] triton==3.1.0
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2023.1.0         h213fc3f_46344    defaults
[conda] mkl-service               2.4.0           py310h5eee18b_1    defaults
[conda] mkl_fft                   1.3.10          py310h5eee18b_0    defaults
[conda] mkl_random                1.2.7           py310h1128e8f_0    defaults
[conda] numpy                     1.26.4          py310h5f9d8c6_0    defaults
[conda] numpy-base                1.26.4          py310hb5e798b_0    defaults
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.46.2                   pypi_0    pypi
[conda] transformers-stream-generator 0.0.4                    pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     PHB     PHB     PHB     PHB     PHB     PHB     0-85    0               N/A
GPU1    PHB      X      PHB     PHB     PHB     PHB     PHB     PHB     0-85    0               N/A
GPU2    PHB     PHB      X      PHB     PHB     PHB     PHB     PHB     0-85    0               N/A
GPU3    PHB     PHB     PHB      X      PHB     PHB     PHB     PHB     0-85    0               N/A
GPU4    PHB     PHB     PHB     PHB      X      PHB     PHB     PHB     0-85    0               N/A
GPU5    PHB     PHB     PHB     PHB     PHB      X      PHB     PHB     0-85    0               N/A
GPU6    PHB     PHB     PHB     PHB     PHB     PHB      X      PHB     0-85    0               N/A
GPU7    PHB     PHB     PHB     PHB     PHB     PHB     PHB      X      0-85    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

CUDNN_VERSION=7.6.4.38
LD_LIBRARY_PATH=/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/cuda/lib64:
VLLM_WORKER_MULTIPROC_METHOD=spawn
NVIDIA_VISIBLE_DEVICES=all
NCCL_VERSION=2.4.8-1
MAX_JOBS=20
NCCL_P2P_DISABLE=0
CUDA_VERSION=9.2.148
NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,compat32,utility
CUDA_VISIBLE_DEVICES=0,1,2,3
CUDA_VISIBLE_DEVICES=0,1,2,3
NVIDIA_REQUIRE_CUDA=cuda>=9.2
NCCL_IGNORE_DISABLED_P2P=1
NCCL_DEBUG=INFO
NCCL_SOCKET_IFNAME=eth0
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

tensor_parallel_size = 1  no nccl error
tensor_parallel_size > 1 will get nccl error
```
            self.llm = LLM(
                model=model_name,
                tensor_parallel_size=tensor_parallel_size,
                limit_mm_per_prompt={"image": 25, "video": 1},
                max_model_len=32700
            )
```

```
use_vllm: True
tensor_parallel_size: 2
use_vllm2 True
vllm
INFO 11-25 08:17:27 config.py:350] This model supports multiple tasks: {'generate', 'embedding'}. Defaulting to 'generate'.
INFO 11-25 08:17:27 config.py:1020] Defaulting to use mp for distributed inference
INFO 11-25 08:17:27 llm_engine.py:249] Initializing an LLM engine (v0.6.4.post1) with config: model='../models/Qwen2-VL-7B-Instruct', speculative_config=None, tokenizer='../models/Qwen2-VL-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32700, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=../models/Qwen2-VL-7B-Instruct, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=None)
WARNING 11-25 08:17:28 multiproc_gpu_executor.py:56] Reducing Torch parallelism from 43 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 11-25 08:17:28 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 11-25 08:17:28 selector.py:135] Using Flash Attention backend.
[1;36m(VllmWorkerProcess pid=55933)[0;0m INFO 11-25 08:17:33 selector.py:135] Using Flash Attention backend.
[1;36m(VllmWorkerProcess pid=55933)[0;0m INFO 11-25 08:17:33 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 11-25 08:17:33 utils.py:961] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=55933)[0;0m INFO 11-25 08:17:33 utils.py:961] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=55933)[0;0m INFO 11-25 08:17:33 pynccl.py:69] vLLM is using nccl==2.21.5
INFO 11-25 08:17:33 pynccl.py:69] vLLM is using nccl==2.21.5
ae05277d311f:55583:55583 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
ae05277d311f:55583:55583 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.3<0>
ae05277d311f:55583:55583 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
ae05277d311f:55583:55583 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
ae05277d311f:55583:55583 [0] NCCL INFO NET/Plugin: Using internal network plugin.
ae05277d311f:55583:55583 [0] NCCL INFO cudaDriverVersion 12060
NCCL version 2.21.5+cuda12.4
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229] Exception in worker VllmWorkerProcess while processing method init_device.
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     output = executor(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/worker/worker.py", line 145, in init_device
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     init_worker_distributed_environment(self.parallel_config, self.rank,
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/worker/worker.py", line 462, in init_worker_distributed_environment
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 1105, in ensure_model_parallel_initialized
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     initialize_model_parallel(tensor_model_parallel_size,
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 1069, in initialize_model_parallel
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     _TP = init_model_parallel_group(group_ranks,
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 908, in init_model_parallel_group
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     return GroupCoordinator(
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 228, in __init__
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     self.pynccl_comm = PyNcclCommunicator(
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 244, in ncclCommInitRank
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]   File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 223, in NCCL_CHECK
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229]     raise RuntimeError(f"NCCL error: {error_str}")
[1;36m(VllmWorkerProcess pid=55933)[0;0m ERROR 11-25 08:17:34 multiproc_worker_utils.py:229] RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
Error in rollout: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
Stack trace: Traceback (most recent call last):
  File "/root/mount/Matterport3DSimulator/MapGPT/vln/gpt_agent.py", line 289, in rollout
    self.qwen_model = QwenVisionInference(model_name="../models/Qwen2-VL-7B-Instruct", use_vllm=use_vllm, tensor_parallel_size=tensor_parallel_size)
  File "/root/mount/Matterport3DSimulator/MapGPT/vln/Qwen_inference.py", line 87, in __init__
    self.llm = LLM(
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/utils.py", line 1028, in inner
    return fn(*args, **kwargs)
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 210, in __init__
    self.llm_engine = self.engine_class.from_engine_args(
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 585, in from_engine_args
    engine = cls(
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 347, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 36, in __init__
    self._init_executor()
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 113, in _init_executor
    self._run_workers("init_device")
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 195, in _run_workers
    driver_worker_output = driver_worker_method(*args, **kwargs)
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/worker/worker.py", line 145, in init_device
    init_worker_distributed_environment(self.parallel_config, self.rank,
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/worker/worker.py", line 462, in init_worker_distributed_environment
    ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 1105, in ensure_model_parallel_initialized
    initialize_model_parallel(tensor_model_parallel_size,
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 1069, in initialize_model_parallel
    _TP = init_model_parallel_group(group_ranks,
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 908, in init_model_parallel_group
    return GroupCoordinator(
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 228, in __init__
    self.pynccl_comm = PyNcclCommunicator(
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 244, in ncclCommInitRank
    self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
  File "/root/miniconda/envs/MapGPT/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 223, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)

INFO 11-25 08:17:34 multiproc_worker_utils.py:133] Terminating local vLLM worker processes
[1;36m(VllmWorkerProcess pid=55933)[0;0m INFO 11-25 08:17:34 multiproc_worker_utils.py:240] Worker exiting
ae05277d311f:55933:55933 [1] NCCL INFO cudaDriverVersion 12060
ae05277d311f:55933:55933 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
ae05277d311f:55933:55933 [1] NCCL INFO Bootstrap : Using eth0:172.17.0.3<0>
ae05277d311f:55933:55933 [1] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
ae05277d311f:55933:55933 [1] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : when loading libnccl-net.so
ae05277d311f:55933:55933 [1] NCCL INFO NET/Plugin: Using internal network plugin.
ae05277d311f:55933:55933 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
ae05277d311f:55933:55933 [1] NCCL INFO NET/IB : No device found.
ae05277d311f:55933:55933 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
ae05277d311f:55933:55933 [1] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.3<0>
ae05277d311f:55933:55933 [1] NCCL INFO Using non-device net plugin version 0
ae05277d311f:55933:55933 [1] NCCL INFO Using network Socket
ae05277d311f:55933:55933 [1] NCCL INFO ncclCommInitRank comm 0xbde4170 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 80 commId 0x7fc852296fe0f6fb - Init START
ae05277d311f:55933:55933 [1] NCCL INFO comm 0xbde4170 rank 1 nRanks 2 nNodes 1 localRanks 2 localRank 1 MNNVL 0
ae05277d311f:55933:55933 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
ae05277d311f:55933:55933 [1] NCCL INFO P2P Chunksize set to 131072
ae05277d311f:55933:55933 [1] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.

ae05277d311f:55933:55933 [1] misc/shmutils.cc:72 NCCL WARN Error: failed to extend /dev/shm/nccl-RH5XJd to 9637892 bytes

ae05277d311f:55933:55933 [1] misc/shmutils.cc:113 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-RH5XJd (size 9637888)
ae05277d311f:55933:55933 [1] NCCL INFO transport/shm.cc:114 -> 2
ae05277d311f:55933:55933 [1] NCCL INFO transport.cc:33 -> 2
ae05277d311f:55933:55933 [1] NCCL INFO transport.cc:113 -> 2
ae05277d311f:55933:55933 [1] NCCL INFO init.cc:1263 -> 2
ae05277d311f:55933:55933 [1] NCCL INFO init.cc:1548 -> 2
ae05277d311f:55933:55933 [1] NCCL INFO init.cc:1799 -> 2
ae05277d311f:55933:55933 [1] NCCL INFO init.cc:1837 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
ae05277d311f:55583:55583 [0] NCCL INFO NET/IB : No device found.
ae05277d311f:55583:55583 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
ae05277d311f:55583:55583 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.3<0>
ae05277d311f:55583:55583 [0] NCCL INFO Using non-device net plugin version 0
ae05277d311f:55583:55583 [0] NCCL INFO Using network Socket
ae05277d311f:55583:55583 [0] NCCL INFO ncclCommInitRank comm 0x13f6c490 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 70 commId 0x7fc852296fe0f6fb - Init START
ae05277d311f:55583:55583 [0] NCCL INFO comm 0x13f6c490 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
ae05277d311f:55583:55583 [0] NCCL INFO Channel 00/02 :    0   1
ae05277d311f:55583:55583 [0] NCCL INFO Channel 01/02 :    0   1
ae05277d311f:55583:55583 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
ae05277d311f:55583:55583 [0] NCCL INFO P2P Chunksize set to 131072
ae05277d311f:55583:55583 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.

ae05277d311f:55583:55583 [0] misc/shmutils.cc:72 NCCL WARN Error: failed to extend /dev/shm/nccl-JwB54o to 9637892 bytes

ae05277d311f:55583:55583 [0] misc/shmutils.cc:113 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-JwB54o (size 9637888)
ae05277d311f:55583:55583 [0] NCCL INFO transport/shm.cc:114 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO transport.cc:33 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO transport.cc:113 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO init.cc:1263 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO init.cc:1548 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO init.cc:1799 -> 2
ae05277d311f:55583:55583 [0] NCCL INFO init.cc:1837 -> 2

```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by wlll123456** [comment]
https://docs.vllm.ai/en/latest/getting_started/debugging.html. this give the current bug info

my docker share_memory is small, and i add this to solve 

https://docs.vllm.ai/en/latest/getting_started/debugging.html.这里的脚本他会给我nccl报错的原因，我送到了GPT里，主要原因是我这个docker的共享内存太小了，所以我无法启动nccl
