### ISSUE TITLE
[Bug]: vllm infer for Qwen2-VL-72B-Instruct-GPTQ-Int8 

### ISSUE THREAD

**Issue by DoctorTar** [vllm-project/vllm#10650]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
$python collect_env.py
WARNING 11-26 09:49:49 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Alibaba Group Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 9.2.1 20200522 (Alibaba 9.2.1-3 2.17)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.30

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-13.al8.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB

Nvidia driver version: 470.161.03
cuDNN version: Probably one of the following:
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:              6
CPU MHz:               3499.987
CPU max MHz:           3500.0000
CPU min MHz:           800.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] atorch==1.2.1
[pip3] flake8==6.1.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pynvml==11.4.1
[pip3] pyzmq==25.1.2
[pip3] sentence-transformers==3.2.0
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchpippy==0.1.1+cecc4fc
[pip3] torchvision==0.19.0
[pip3] transformers==4.46.2
[pip3] transformers-stream-generator==0.0.5
[pip3] triton==3.0.0
[conda] atorch                    1.2.1                    pypi_0    pypi
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pynvml                    11.4.1                   pypi_0    pypi
[conda] pyzmq                     25.1.2                   pypi_0    pypi
[conda] sentence-transformers     3.2.0                    pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchaudio                2.4.0                    pypi_0    pypi
[conda] torchpippy                0.1.1+cecc4fc            pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.46.2                   pypi_0    pypi
[conda] transformers-stream-generator 0.0.5                    pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.3.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

NVIDIA_VISIBLE_DEVICES=GPU-8146fa97-b89e-8d8a-006e-a33b4db5f764,GPU-640d8674-21b7-6141-a8a4-bd4c619c05d4
LD_LIBRARY_PATH=/opt/conda/lib/python3.8/site-packages/cv2/../../lib64::/opt/conda/lib/python3.8/site-packages/aistudio_common/reader/libs/:/opt/taobao/java/jre/lib/amd64/server/:/usr/local/cuda/lib64:/opt/conda/lib/python3.8/site-packages/aistudio_common/reader/libs/:/opt/taobao/java/jre/lib/amd64/server/:/usr/local/cuda/lib64:/opt/conda/lib/python3.8/site-packages/aistudio_common/reader/libs/:/opt/taobao/java/jre/lib/amd64/server/:/usr/local/cuda/lib64:/opt/conda/lib/python3.8/site-packages/aistudio_common/reader/libs/:/opt/taobao/java/jre/lib/amd64/server/:/usr/local/cuda/lib64:/opt/conda/lib/python3.8/site-packages/aistudio_common/reader/libs/:/opt/taobao/java/jre/lib/amd64/server/:/usr/local/cuda/lib64
NVIDIA_DRIVER_CAPABILITIES=all
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

running the following code for Qwen2-VL-72B-Instruct-GPTQ-Int8 in vllm:

```
import torch, os
from transformers import AutoProcessor
from transformers import Qwen2VLForConditionalGeneration # adding this line could leads to error
from vllm import LLM, SamplingParams
from qwen_vl_utils import process_vision_info

MODEL_PATH = "local/models/Qwen2-VL-72B-Instruct-GPTQ-Int8"
llm = LLM(
    model=MODEL_PATH,
    limit_mm_per_prompt={"image": 10, "video": 10},
    tensor_parallel_size=2
)
```

Adding the line "from transformers import Qwen2VLForConditionalGeneration" will leads to error:

> WARNING 11-26 09:52:54 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
> INFO 11-26 09:53:03 gptq_marlin.py:107] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
> INFO 11-26 09:53:03 config.py:905] Defaulting to use mp for distributed inference
> INFO 11-26 09:53:03 llm_engine.py:237] Initializing an LLM engine (v0.6.3.post1) with config: model='/mnt/282062/pretrained_models/Qwen2-VL-72B-Instruct-GPTQ-Int8', speculative_config=None, tokenizer='/mnt/282062/pretrained_models/Qwen2-VL-72B-Instruct-GPTQ-Int8', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq_marlin, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/mnt/282062/pretrained_models/Qwen2-VL-72B-Instruct-GPTQ-Int8, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
> WARNING 11-26 09:53:03 multiproc_gpu_executor.py:53] Reducing Torch parallelism from 128 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
> INFO 11-26 09:53:03 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
> (VllmWorkerProcess pid=8387) INFO 11-26 09:53:04 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229] Exception in worker VllmWorkerProcess while processing method init_device.
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229] Traceback (most recent call last):
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.8/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]     output = executor(*args, **kwargs)
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.8/site-packages/vllm/worker/worker.py", line 166, in init_device
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]     torch.cuda.set_device(self.device)
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 420, in set_device
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]     torch._C._cuda_setDevice(device)
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 300, in _lazy_init
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229]     raise RuntimeError(
> (VllmWorkerProcess pid=8387) ERROR 11-26 09:53:04 multiproc_worker_utils.py:229] RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

I've tried uninstall pynvml, add "multiprocessing.set_start_method('spawn')" or "torch.multiprocessing.set_start_method('spawn')", it didn't work as well.
I'm using

NOTE:
1. I know the import line is unnecessarily, but it's really weird that an import line could leads to this error (at least to me)
2. I am not sure whether this issue is supposed to be raised in vllm project or qwen,or in transformers project, sorry if I am wrong but it is the llm=.... line that raise error and that's why I choose here. 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
In most cases, this issue occurs because CUDA has already been initialized before the LLM initialization. You can debug it by checking if there's GPU usage after running `from transformers import Qwen2VLForConditionalGeneration `
