### ISSUE TITLE
[Bug]: v0.6.4.post1 Qwen2-VL-7B-Instruct-AWQ crash：shape mismatch

### ISSUE THREAD

**Issue by wciq1208** [vllm-project/vllm#10686]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.5
Libc version: glibc-2.35

Python version: 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:27:36) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.71.1.el7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6140M CPU @ 2.30GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       4
Stepping:                        4
BogoMIPS:                        4599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat umip pku ospke md_clear spec_ctrl intel_stibp arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        64 MiB (16 instances)
L3 cache:                        64 MiB (4 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; Load fences, usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS (kernel), IBPB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] optree==0.13.0
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1+cu124
[pip3] torchaudio==2.5.1+cu124
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.20.1+cu124
[pip3] transformers==4.46.2
[pip3] triton==3.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] optree                    0.13.0                   pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.5.1+cu124              pypi_0    pypi
[conda] torchaudio                2.5.1+cu124              pypi_0    pypi
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchvision               0.20.1+cu124             pypi_0    pypi
[conda] transformers              4.46.2                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     0-15    0               N/A
GPU1    PHB      X      0-15    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute,utility
PYTORCH_VERSION=2.5.1
LD_LIBRARY_PATH=/opt/conda/lib/python3.11/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
CUDA_MODULE_LOADING=LAZY
```

</details>

### Model Input Dumps

[err_execute_model_input_20241126-132009.pkl.zip](https://github.com/user-attachments/files/17927878/err_execute_model_input_20241126-132009.pkl.zip)

### 🐛 Describe the bug

command
```bash
vllm serve /hestia/model/Qwen2-VL-7B-Instruct-AWQ --quantization awq --num-gpu-blocks-override 4096 --max-num-seqs 32 --port 8002 --swap-space 4 --served-model-name qwenvl --disable-log-requests --enable-prefix-caching --enable-chunked-prefill --max-num-batched-tokens 2048
```

```bash
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
WARNING 11-26 13:17:29 utils.py:603] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:11<00:11, 11.35s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:20<00:00,  9.89s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:20<00:00, 10.11s/it]

INFO 11-26 13:17:49 model_runner.py:1077] Loading model weights took 6.4639 GB
WARNING 11-26 13:17:49 model_runner.py:1257] Computed max_num_seqs (min(32, 2048 // 2450)) to be less than 1. Setting it to the minimum value of 1.
INFO 11-26 13:17:52 worker.py:232] Memory profiling results: total_gpu_memory=23.69GiB initial_memory_usage=7.34GiB peak_torch_memory=6.96GiB memory_usage_post_profile=7.40GiB non_torch_memory=0.92GiB kv_cache_size=13.44GiB gpu_memory_utilization=0.90
INFO 11-26 13:17:52 llm_engine.py:491] Overriding num_gpu_blocks=15723 with num_gpu_blocks_override=4096
INFO 11-26 13:17:52 gpu_executor.py:113] # GPU blocks: 4096, # CPU blocks: 4681
INFO 11-26 13:17:52 gpu_executor.py:117] Maximum concurrency for 32768 tokens per request: 2.00x
INFO 11-26 13:17:56 model_runner.py:1400] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 11-26 13:17:56 model_runner.py:1404] If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 11-26 13:17:59 model_runner.py:1518] Graph capturing finished in 3 secs, took 0.47 GiB
INFO 11-26 13:17:59 api_server.py:249] vLLM to use /tmp/tmp3t3map8n as PROMETHEUS_MULTIPROC_DIR
INFO 11-26 13:17:59 launcher.py:19] Available routes are:
INFO 11-26 13:17:59 launcher.py:27] Route: /openapi.json, Methods: GET, HEAD
INFO 11-26 13:17:59 launcher.py:27] Route: /docs, Methods: GET, HEAD
INFO 11-26 13:17:59 launcher.py:27] Route: /docs/oauth2-redirect, Methods: GET, HEAD
INFO 11-26 13:17:59 launcher.py:27] Route: /redoc, Methods: GET, HEAD
INFO 11-26 13:17:59 launcher.py:27] Route: /health, Methods: GET
INFO 11-26 13:17:59 launcher.py:27] Route: /tokenize, Methods: POST
INFO 11-26 13:17:59 launcher.py:27] Route: /detokenize, Methods: POST
INFO 11-26 13:17:59 launcher.py:27] Route: /v1/models, Methods: GET
INFO 11-26 13:17:59 launcher.py:27] Route: /version, Methods: GET
INFO 11-26 13:17:59 launcher.py:27] Route: /v1/chat/completions, Methods: POST
INFO 11-26 13:17:59 launcher.py:27] Route: /v1/completions, Methods: POST
INFO 11-26 13:17:59 launcher.py:27] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [5209]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
INFO 11-26 13:18:09 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:18:19 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:18:29 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:18:39 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:18:49 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:18:59 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:19:09 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:19:19 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:19:29 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:19:39 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:19:49 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 11-26 13:19:59 metrics.py:449] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
Compiling FSM index for all state transitions: 100%|██████████| 12/12 [00:00<00:00, 18.10it/s]
INFO 11-26 13:20:06 preprocess.py:215] Your model uses the legacy input pipeline instead of the new multi-modal processor. Please note that the legacy pipeline will be removed in a future release. For more details, see: https://github.com/vllm-project/vllm/issues/10114
INFO 11-26 13:20:09 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241126-132009.pkl...
INFO 11-26 13:20:09 model_runner_base.py:149] Completed writing input of failed execution to /tmp/err_execute_model_input_20241126-132009.pkl.
CRITICAL 11-26 13:20:09 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     192.168.96.11:61988 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR 11-26 13:20:09 engine.py:135] RuntimeError('Error in model execution (input dumped to /tmp/err_execute_model_input_20241126-132009.pkl): shape mismatch: value tensor of shape [4956, 3584] cannot be broadcast to indexing result of shape [2033, 3584]')
ERROR 11-26 13:20:09 engine.py:135] Traceback (most recent call last):
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
ERROR 11-26 13:20:09 engine.py:135]     return func(*args, **kwargs)
ERROR 11-26 13:20:09 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1654, in execute_model
ERROR 11-26 13:20:09 engine.py:135]     hidden_or_intermediate_states = model_executable(
ERROR 11-26 13:20:09 engine.py:135]                                     ^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 11-26 13:20:09 engine.py:135]     return self._call_impl(*args, **kwargs)
ERROR 11-26 13:20:09 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 11-26 13:20:09 engine.py:135]     return forward_call(*args, **kwargs)
ERROR 11-26 13:20:09 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2_vl.py", line 1287, in forward
ERROR 11-26 13:20:09 engine.py:135]     inputs_embeds = self._merge_multimodal_embeddings(
ERROR 11-26 13:20:09 engine.py:135]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2_vl.py", line 1237, in _merge_multimodal_embeddings
ERROR 11-26 13:20:09 engine.py:135]     inputs_embeds[mask, :] = multimodal_embeddings
ERROR 11-26 13:20:09 engine.py:135]     ~~~~~~~~~~~~~^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135] RuntimeError: shape mismatch: value tensor of shape [4956, 3584] cannot be broadcast to indexing result of shape [2033, 3584]
ERROR 11-26 13:20:09 engine.py:135] 
ERROR 11-26 13:20:09 engine.py:135] The above exception was the direct cause of the following exception:
ERROR 11-26 13:20:09 engine.py:135] 
ERROR 11-26 13:20:09 engine.py:135] Traceback (most recent call last):
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 133, in start
ERROR 11-26 13:20:09 engine.py:135]     self.run_engine_loop()
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 196, in run_engine_loop
ERROR 11-26 13:20:09 engine.py:135]     request_outputs = self.engine_step()
ERROR 11-26 13:20:09 engine.py:135]                       ^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 214, in engine_step
ERROR 11-26 13:20:09 engine.py:135]     raise e
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 205, in engine_step
ERROR 11-26 13:20:09 engine.py:135]     return self.engine.step()
ERROR 11-26 13:20:09 engine.py:135]            ^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 1454, in step
ERROR 11-26 13:20:09 engine.py:135]     outputs = self.model_executor.execute_model(
ERROR 11-26 13:20:09 engine.py:135]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 125, in execute_model
ERROR 11-26 13:20:09 engine.py:135]     output = self.driver_worker.execute_model(execute_model_req)
ERROR 11-26 13:20:09 engine.py:135]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 343, in execute_model
ERROR 11-26 13:20:09 engine.py:135]     output = self.model_runner.execute_model(
ERROR 11-26 13:20:09 engine.py:135]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 11-26 13:20:09 engine.py:135]     return func(*args, **kwargs)
ERROR 11-26 13:20:09 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-26 13:20:09 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
ERROR 11-26 13:20:09 engine.py:135]     raise type(err)(
ERROR 11-26 13:20:09 engine.py:135] RuntimeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20241126-132009.pkl): shape mismatch: value tensor of shape [4956, 3584] cannot be broadcast to indexing result of shape [2033, 3584]
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [5209]
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by wciq1208** [comment]
> I ran into the same thing with Molmo. I think prefix caching is broken on vision models. I have a suspicion it's related to images of different sizes, but I haven't tested that theory at all.

I tried disabling prefix-caching, but the same error still occurred.

**Comment by sihamouda** [comment]
Me too same issue

**Comment by DarkLight1337** [comment]
This shouldn't happen on the latest version anymore since this model was updated to use merged multi-modal processor. Feel free to reopen if you still encounter this problem.

**Comment by DarkLight1337** [comment]
Also, prefix caching / chunked prefill aren't supported for non-V1 vision models yet.
