### ISSUE TITLE
[Installation]: on docker swarm in VPS say: RuntimeError: Failed to infer device type

### ISSUE THREAD

**Issue by devMls** [vllm-project/vllm#10717]
### Your current environment

INFO 11-27 07:19:27 api_server.py:194] Started engine process with PID 16

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 643, in <module>

    uvloop.run(run_server(args))

  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run

    return __asyncio.run(

           ^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run

    return runner.run(main)

           ^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run

    return self._loop.run_until_complete(task)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete

  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper

    return await main

           ^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 609, in run_server

    async with build_async_engine_client(args) as engine_client:

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 113, in build_async_engine_client

    async with build_async_engine_client_from_engine_args(

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 197, in build_async_engine_client_from_engine_args

    engine_config = engine_args.create_engine_config()

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 958, in create_engine_config

    device_config = DeviceConfig(device=self.device)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 1208, in __init__

    raise RuntimeError("Failed to infer device type")

RuntimeError: Failed to infer device type

Process SpawnProcess-1:

ERROR 11-27 07:19:31 engine.py:366] Failed to infer device type

ERROR 11-27 07:19:31 engine.py:366] Traceback (most recent call last):

ERROR 11-27 07:19:31 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine

ERROR 11-27 07:19:31 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,

ERROR 11-27 07:19:31 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ERROR 11-27 07:19:31 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 114, in from_engine_args

ERROR 11-27 07:19:31 engine.py:366]     engine_config = engine_args.create_engine_config()

ERROR 11-27 07:19:31 engine.py:366]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ERROR 11-27 07:19:31 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 958, in create_engine_config

Traceback (most recent call last):

  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap

    self.run()

  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine

    raise e

ERROR 11-27 07:19:31 engine.py:366]     device_config = DeviceConfig(device=self.device)

ERROR 11-27 07:19:31 engine.py:366]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ERROR 11-27 07:19:31 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 1208, in __init__

ERROR 11-27 07:19:31 engine.py:366]     raise RuntimeError("Failed to infer device type")

ERROR 11-27 07:19:31 engine.py:366] RuntimeError: Failed to infer device type

  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine

    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 114, in from_engine_args

    engine_config = engine_args.create_engine_config()

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 958, in create_engine_config

    device_config = DeviceConfig(device=self.device)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 1208, in __init__

    raise RuntimeError("Failed to infer device type")

RuntimeError: Failed to infer device type

### How you are installing vllm

I install using docker swarm on dedicated cloud vps on hetzner, I want run a lightweight model "jinaai/jina-embeddings-v3", I assume that the cpu and ram i sufficient in a 16gb ram and 4 dedicated cpu.

My docker compose file

services:
  jinna:
    hostname: jinaai
    image: vllm/vllm-openai:latest
    command: "--model jinaai/jina-embeddings-v3 "
    volumes:
      - jinaai:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${secret}
    networks:
      - ragflow
      - bridge

volumes:
  jinaai:
    driver: local

networks:
  ragflow:
    external: true
  bridge:
    name: bridge
    external: true      

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by devMls** [comment]
My fault --device="cpu"  fix the problem

now i dealing with "ValueError: Only 'absolute' position_embedding_type is supported

Traceback (most recent call last):"
