### ISSUE TITLE
[Usage]: ValueError: Model architectures ['Qwen2ForCausalLM'] failed to be inspected. Please check the logs for more details.

### ISSUE THREAD

**Issue by despzcm** [vllm-project/vllm#10759]
### Your current environment

```text
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 530.41.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD Ryzen Threadripper 3970X 32-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2589.433
CPU max MHz:                     3700.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7400.62
Virtualization:                  AMD-V
L1d cache:                       1 MiB
L1i cache:                       1 MiB
L2 cache:                        16 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.46.1
[pip3] triton==3.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.10          py311h5eee18b_0  
[conda] mkl_random                1.2.7           py311ha02d727_0  
[conda] numpy                     1.26.4          py311h08b1b3b_0  
[conda] numpy-base                1.26.4          py311hf175353_0  
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.46.1                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity
GPU0     X      SYS     0-63            N/A
GPU1    SYS      X      0-63            N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### How would you like to use vllm

```python
# Initialize the tokenizer
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-7B-Instruct")

# Pass the default decoding hyperparameters of Qwen2.5-7B-Instruct
# max_tokens is for the maximum length for generation.
sampling_params = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.05, max_tokens=512)

# Input the model name or path. Can be GPTQ or AWQ models.
llm = LLM(model="Qwen/Qwen2.5-7B-Instruct")
```
When I want to load the Qwen2.5-7B-Instruct, it seems fail. And get error: `ValueError: Model architectures ['Qwen2ForCausalLM'] failed to be inspected. Please check the logs for more details.`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Can you show the full logs?

**Comment by Wang-YLi** [comment]
export VLLM_USE_MODELSCOPE=True

**Comment by despzcm** [comment]
Thx for reply.
The full logs are as following:
```text
ERROR 11-29 06:51:24 registry.py:297] Error in inspecting model architecture 'Qwen2ForCausalLM'
ERROR 11-29 06:51:24 registry.py:297] Traceback (most recent call last):
ERROR 11-29 06:51:24 registry.py:297]   File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 468, in _run_in_subprocess
ERROR 11-29 06:51:24 registry.py:297]     returned.check_returncode()
ERROR 11-29 06:51:24 registry.py:297]   File "/envs/Anaconda3/envs/PRM/lib/python3.11/subprocess.py", line 502, in check_returncode
ERROR 11-29 06:51:24 registry.py:297]     raise CalledProcessError(self.returncode, self.args, self.stdout,
ERROR 11-29 06:51:24 registry.py:297] subprocess.CalledProcessError: Command '['/envs/Anaconda3/envs/PRM/bin/python', '-m', 'vllm.model_executor.models.registry']' returned non-zero exit status 1.
ERROR 11-29 06:51:24 registry.py:297] 
ERROR 11-29 06:51:24 registry.py:297] The above exception was the direct cause of the following exception:
ERROR 11-29 06:51:24 registry.py:297] 
ERROR 11-29 06:51:24 registry.py:297] Traceback (most recent call last):
ERROR 11-29 06:51:24 registry.py:297]   File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 295, in _try_inspect_model_cls
ERROR 11-29 06:51:24 registry.py:297]     return model.inspect_model_cls()
ERROR 11-29 06:51:24 registry.py:297]            ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-29 06:51:24 registry.py:297]   File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 257, in inspect_model_cls
ERROR 11-29 06:51:24 registry.py:297]     return _run_in_subprocess(
ERROR 11-29 06:51:24 registry.py:297]            ^^^^^^^^^^^^^^^^^^^
ERROR 11-29 06:51:24 registry.py:297]   File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 471, in _run_in_subprocess
ERROR 11-29 06:51:24 registry.py:297]     raise RuntimeError(f"Error raised in subprocess:\n"
ERROR 11-29 06:51:24 registry.py:297] RuntimeError: Error raised in subprocess:
ERROR 11-29 06:51:24 registry.py:297] Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-a34b3233.so.1 library.
ERROR 11-29 06:51:24 registry.py:297]   Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
ERROR 11-29 06:51:24 registry.py:297] 
Traceback (most recent call last):
  File "/test111.py", line 13, in <module>
    llm = LLM(model="/model/Qwen2.5-Math-7B-Instruct")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/utils.py", line 1028, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 210, in __init__
    self.llm_engine = self.engine_class.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 582, in from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 959, in create_engine_config
    model_config = self.create_model_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 891, in create_model_config
    return ModelConfig(
           ^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/config.py", line 251, in __init__
    self.multimodal_config = self._init_multimodal_config(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/config.py", line 277, in _init_multimodal_config
    if ModelRegistry.is_multimodal_model(architectures):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 422, in is_multimodal_model
    return self.inspect_model_cls(architectures).supports_multimodal
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 391, in inspect_model_cls
    return self._raise_for_unsupported(architectures)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/Anaconda3/envs/PRM/lib/python3.11/site-packages/vllm/model_executor/models/registry.py", line 348, in _raise_for_unsupported
    raise ValueError(
ValueError: Model architectures ['Qwen2ForCausalLM'] failed to be inspected. Please check the logs for more details.
```

And I use `export VLLM_USE_MODELSCOPE=True` but It doesn't seem to be working.

**Comment by DarkLight1337** [comment]
```
ERROR 11-29 06:51:24 registry.py:297] RuntimeError: Error raised in subprocess:
ERROR 11-29 06:51:24 registry.py:297] Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-a34b3233.so.1 library.
ERROR 11-29 06:51:24 registry.py:297]   Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
```

This shows that you need to update your numpy version.

**Comment by despzcm** [comment]
It works! Thanks @DarkLight1337 !
But after I update my numpy to the newest version(2.1.3), it get some conflicts, which is
```text
vllm 0.6.4.post1 requires numpy<2.0.0, but you have numpy 2.1.3 which is incompatible.
```
Though my code can run properly, Will this become a problem for the future? Do I need to downgrade the numpy version？

**Comment by surak** [comment]
vllm-0.6.6.post2.dev4+g7af553ea does this with ALL models

**Comment by DarkLight1337** [comment]
Please open a new issue and provide more information.

**Comment by tginart** [comment]
Hi @DarkLight1337 ,

I think this issue should be re-opened

I am currently getting this issue with both 0.6.6 and 0.6.4.

Thanks.

**Comment by DarkLight1337** [comment]
Have you tried this?

> You can try downgrading back to numpy v1, maybe re-installing numpy can also fix the issue.

**Comment by cainiaoup** [comment]
> It works! Thanks [@DarkLight1337](https://github.com/DarkLight1337) ! But after I update my numpy to the newest version(2.1.3), it get some conflicts, which is
> 
> ```
> vllm 0.6.4.post1 requires numpy<2.0.0, but you have numpy 2.1.3 which is incompatible.
> ```
> 
> Though my code can run properly, Will this become a problem for the future? Do I need to downgrade the numpy version？

use pip install numpy==1.25.2, it' work..

**Comment by qiulang** [comment]
同样问题 https://github.com/xorbitsai/inference/issues/3327
确实把numpy 降到1.x 就可以，可问题是 如果直接用vllm 启动 numpy 1.x 或 2.x 都是可以的

**Comment by qiulang** [comment]
@DarkLight1337 and all I found my reason, 

my numpy installed through conda and  the conda-built NumPy with MKL assumes it will use Intel's own threading layer by default.

So set MKL_THREADING_LAYER=GNU and start xinference fixing my problem

**Comment by qiulang** [comment]
@DarkLight1337  ”Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp-a34b3233.so.1 library... This shows that you need to update your numpy version."

That is **incorrect**!

That means his NumPy is probably installed by conda (mine too), and is built with Intel MKL optimizationsThis optimization can sometimes cause the threading conflicts.

Setting MKL_THREADING_LAYER=GNU, forces Intel's Math Kernel Library to use GNU's OpenMP implementation instead of Intel's own implementation

**Comment by DarkLight1337** [comment]
Thanks for the explanation. I think if you re-install numpy using `pip` then it should use NumPy compiled with the correct library though?

**Comment by qiulang** [comment]
@DarkLight1337 if you re-install numpy using pip, pip will use its numpy implementation

You may also check this SO discussion about conda's numpy with Intel's MKL

https://stackoverflow.com/questions/68965495/how-to-change-numpy-and-conda-mkl-version

**Comment by qiulang** [comment]
Another issue with conda that worths to mention is do not use conda's pytorch as vllm document mentioned here https://docs.vllm.ai/en/latest/getting_started/installation/gpu.html

> In order to be performant, vLLM has to compile many cuda kernels. The compilation unfortunately introduces binary incompatibility with other CUDA versions and PyTorch versions, even for the same PyTorch version with different building configurations.
