### ISSUE TITLE
[Usage]: How to use llava-hf/llava-1.5-7b-hf with bitsandbytes quantization in vllm serve? 

### ISSUE THREAD

**Issue by Wxy-24** [vllm-project/vllm#10813]
### Your current environment

```
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-051900-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True


Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.46.3
[pip3] triton==3.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.46.3                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-11            N/A             N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

CUDA_VISIBLE_DEVICES=0
CUDA_VISIBLE_DEVICES=0
LD_LIBRARY_PATH=/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/cv2/../../lib64:/usr/local/cuda-11.7/lib64:/usr/local/cuda-11.7/lib64
CUDA_HOME=:/usr/local/cuda:/usr/local/cuda
CUDA_HOME=:/usr/local/cuda:/usr/local/cuda
CUDA_MODULE_LOADING=LAZY
```

### How would you like to use vllm

I want to run inference of a [unsloth/llava-1.5-7b-hf-bnb-4bit](https://huggingface.co/unsloth/llava-1.5-7b-hf-bnb-4bit) (4 bit quantized llava using bitsandbytes). I don't know how to integrate it with vllm.

If I don't use bitsandbytes to load llava, my GPU(RTX 3060 6GB) can't load the model. I hope to reduce memory consumption through 4bit quantization of bitsandbytes, but vllm does not seem to support llava.

I have the issue when loading the model as follow:
```
llm = LLM(model="unsloth/llava-1.5-7b-hf-bnb-4bit", dtype=torch.bfloat16, quantization="bitsandbytes", load_format="bitsandbytes")
```

Then I find errors as follow:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/wxy/download/llava.py", line 44, in <module>
[rank0]:     run_llava_pixel_values()
[rank0]:   File "/home/wxy/download/llava.py", line 16, in run_llava_pixel_values
[rank0]:     llm = LLM(model="unsloth/llava-1.5-7b-hf-bnb-4bit", dtype=torch.bfloat16, quantization="bitsandbytes", load_format="bitsandbytes")
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/utils.py", line 1028, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 210, in __init__
[rank0]:     self.llm_engine = self.engine_class.from_engine_args(
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 585, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 347, in __init__
[rank0]:     self.model_executor = executor_class(vllm_config=vllm_config, )
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 36, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/worker/worker.py", line 152, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 1074, in load_model
[rank0]:     self.model = get_model(vllm_config=self.vllm_config)
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
[rank0]:     return loader.load_model(vllm_config=vllm_config)
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/model_executor/model_loader/loader.py", line 1091, in load_model
[rank0]:     self._load_weights(model_config, model)
[rank0]:   File "/home/wxy/anaconda3/envs/llama/lib/python3.9/site-packages/vllm/model_executor/model_loader/loader.py", line 963, in _load_weights
[rank0]:     raise AttributeError(
[rank0]: AttributeError: Model LlavaForConditionalGeneration does not support BitsAndBytes quantization yet.
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
This #10795  has just been merged. You can either build vllm yourself or wait for the next version release.
