### ISSUE TITLE
[Bug]: vllm  v1/chat/completions  Internal Server Error

### ISSUE THREAD

**Issue by tangliangwu** [vllm-project/vllm#10925]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

INFO 12-05 09:57:05 async_llm_engine.py:173] Added request chat-4656e70d011f4049913ba3b1ab64a702.
ERROR 12-05 09:57:05 async_llm_engine.py:56] Engine background task failed
ERROR 12-05 09:57:05 async_llm_engine.py:56] Traceback (most recent call last):
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 46, in _log_task_completion
ERROR 12-05 09:57:05 async_llm_engine.py:56]     return_value = task.result()
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 637, in run_engine_loop
ERROR 12-05 09:57:05 async_llm_engine.py:56]     result = task.result()
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 580, in engine_step
ERROR 12-05 09:57:05 async_llm_engine.py:56]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 253, in step_async
ERROR 12-05 09:57:05 async_llm_engine.py:56]     output = await self.model_executor.execute_model_async(
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/executor/cpu_executor.py", line 121, in execute_model_async
ERROR 12-05 09:57:05 async_llm_engine.py:56]     output = await make_async(self.driver_worker.execute_model
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 12-05 09:57:05 async_llm_engine.py:56]     result = self.fn(*self.args, **self.kwargs)
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 236, in execute_model
ERROR 12-05 09:57:05 async_llm_engine.py:56]     self.model_runner.prepare_model_input(
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/cpu_model_runner.py", line 326, in prepare_model_input
ERROR 12-05 09:57:05 async_llm_engine.py:56]     ) = self._prepare_prompt(seq_group_metadata_list)
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/cpu_model_runner.py", line 204, in _prepare_prompt
ERROR 12-05 09:57:05 async_llm_engine.py:56]     attn_metadata = self.attn_backend.make_metadata(
ERROR 12-05 09:57:05 async_llm_engine.py:56]   File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/attention/backends/abstract.py", line 39, in make_metadata
ERROR 12-05 09:57:05 async_llm_engine.py:56]     return cls.get_metadata_cls()(*args, **kwargs)
ERROR 12-05 09:57:05 async_llm_engine.py:56] TypeError: FlashAttentionMetadata.__init__() got an unexpected keyword argument 'is_prompt'
Exception in callback functools.partial(<function _log_task_completion at 0x7f769feda950>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f7687a7bfd0>>)
handle: <Handle functools.partial(<function _log_task_completion at 0x7f769feda950>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f7687a7bfd0>>)>
Traceback (most recent call last):
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 46, in _log_task_completion
    return_value = task.result()
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 637, in run_engine_loop
    result = task.result()
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 580, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 253, in step_async
    output = await self.model_executor.execute_model_async(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/executor/cpu_executor.py", line 121, in execute_model_async
    output = await make_async(self.driver_worker.execute_model
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 236, in execute_model
    self.model_runner.prepare_model_input(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/cpu_model_runner.py", line 326, in prepare_model_input
    ) = self._prepare_prompt(seq_group_metadata_list)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/cpu_model_runner.py", line 204, in _prepare_prompt
    attn_metadata = self.attn_backend.make_metadata(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/attention/backends/abstract.py", line 39, in make_metadata
    return cls.get_metadata_cls()(*args, **kwargs)
TypeError: FlashAttentionMetadata.__init__() got an unexpected keyword argument 'is_prompt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 58, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause.
INFO 12-05 09:57:05 async_llm_engine.py:180] Aborted request chat-4656e70d011f4049913ba3b1ab64a702.
INFO:     172.16.80.73:61206 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 129, in create_chat_completion
    generator = await openai_serving_chat.create_chat_completion(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 195, in create_chat_completion
    return await self.chat_completion_full_generator(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 404, in chat_completion_full_generator
    async for res in result_generator:
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 772, in generate
    async for output in self._process_request(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 888, in _process_request
    raise e
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 884, in _process_request
    async for request_output in stream:
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 93, in __anext__
    raise result
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 46, in _log_task_completion
    return_value = task.result()
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 637, in run_engine_loop
    result = task.result()
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 580, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 253, in step_async
    output = await self.model_executor.execute_model_async(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/executor/cpu_executor.py", line 121, in execute_model_async
    output = await make_async(self.driver_worker.execute_model
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 236, in execute_model
    self.model_runner.prepare_model_input(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/cpu_model_runner.py", line 326, in prepare_model_input
    ) = self._prepare_prompt(seq_group_metadata_list)
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/worker/cpu_model_runner.py", line 204, in _prepare_prompt
    attn_metadata = self.attn_backend.make_metadata(
  File "/home/spfx/miniconda3/envs/vllm4/lib/python3.10/site-packages/vllm/attention/backends/abstract.py", line 39, in make_metadata
    return cls.get_metadata_cls()(*args, **kwargs)
TypeError: FlashAttentionMetadata.__init__() got an unexpected keyword argument 'is_prompt'

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Which version of vLLM are you using? Please show the output of `collect_env.py`.

**Comment by tangliangwu** [comment]
vllm version 0.5.3 

vllm serve  ~/Qwen2-VL/models/Qwen2.5-7B-Instruct --tensor-parallel-size 1 --host 172.16.102.154 --port 6006 --served-model-name gpt-4 --device cpu

curl --location --request POST 'http://172.16.102.154:6006/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "Qwen2.5-1.5B-Instruct",
    "messages": [
        {"role": "system", "content": "You are an assistant that answers using the language of the given prompt."},
        {"role": "user", "content": "Hello, how are you?"}
    ]
}'

**Comment by DarkLight1337** [comment]
I think flash attention isn't supported on CPU. You should use SDPA backend instead.

**Comment by tangliangwu** [comment]
export VLLM_ATTENTION_BACKEND=TORCH_SDPA

vllm serve  ~/Qwen2-VL/models/Qwen2.5-7B-Instruct --tensor-parallel-size 1 --host 172.16.102.154 --port 6006 --served-model-name gpt-4 --device cpu

AssertionError: Torch SDPA backend is only used for the CPU device.

**Comment by Isotr0py** [comment]
If you want to serve model with CPU backend, you need to use CPU installation: https://docs.vllm.ai/en/latest/getting_started/cpu-installation.html#installation-with-cpu. Otherwise, CPU kernel won't be compiled by default.
