### ISSUE TITLE
[Bug]: Qwen2VL doesn't work with TPU backend

### ISSUE THREAD

**Issue by carlesoctav** [vllm-project/vllm#10987]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.6.0.dev20241126+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.31.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.19.0-1022-gcp-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          240
On-line CPU(s) list:             0-239
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7B12
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              60
Socket(s):                       2
Stepping:                        0
BogoMIPS:                        4499.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3.8 MiB (120 instances)
L1i cache:                       3.8 MiB (120 instances)
L2 cache:                        60 MiB (120 instances)
L3 cache:                        480 MiB (30 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-59,120-179
NUMA node1 CPU(s):               60-119,180-239
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==26.2.0
[pip3] torch==2.6.0.dev20241126+cpu
[pip3] torch-xla==2.6.0+git39e67b5
[pip3] torchvision==0.20.0.dev20241126+cpu
[pip3] transformers==4.47.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post2.dev266+g7be15d93
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

LD_LIBRARY_PATH=/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/cv2/../../lib64:

```

</details>

### 🐛 Describe the bug

What I did was simply run vllm serve Qwen/Qwen2-VL-7B-Instruct. Previously, I tested the pure LLM (Qwen2.5-7B), and it worked.

I think this error code is relevant for debugging:
```
(RayWorkerWrapper pid=22778) INFO 12-08 10:38:29 importing.py:15] Triton not installed or not compatible; certain GPU-related functions will not be available. [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) INFO 12-08 10:38:30 weight_utils.py:243] Using model weights format ['*.safetensors'] [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution. [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] Traceback (most recent call last): [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/worker/worker_base.py", line 459, in execute_method [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return executor(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/worker/tpu_worker.py", line 111, in determine_num_available_blocks [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.model_runner._dummy_run( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/worker/tpu_model_runner.py", line 266, in _dummy_run [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.model(token_ids, position_ids, attn_metadata, input_lens, t, p, [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return self._call_impl(*args, **kwargs) [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return forward_call(*args, **kwargs) [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 231, in _fn [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return fn(*args, **kwargs) [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 547, in __call__ [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return self._torchdynamo_orig_callable( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return _compile( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 986, in _compile [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     guarded_code = compile_inner(code, one_graph, hooks, transform) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 715, in compile_inner [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return _compile_inner(code, one_graph, hooks, transform) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_utils_internal.py", line 95, in wrapper_function [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return function(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 750, in _compile_inner [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     out_code = transform_code_object(code, transform) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1349, in transform_code_object [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     transformations(instructions, code_options) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 662, in transform [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     tracer.run() [repeated 16x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1054, in run [repeated 18x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     super().run() [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     while self.step(): [repeated 16x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 964, in step [repeated 16x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.dispatch_table[inst.opcode](self, inst) [repeated 16x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 661, in wrapper [repeated 16x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return inner_fn(self, inst) [repeated 16x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1660, in CALL_FUNCTION [repeated 8x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.call_function(fn, args, {}) [repeated 8x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 1004, in call_function [repeated 54x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type] [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/variables/lazy.py", line 170, in realize_and_forward [repeated 8x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return getattr(self.realize(), name)(*args, **kwargs) [repeated 8x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return variables.UserFunctionVariable(fn, source=source).call_function( [repeated 10x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return super().call_function(tx, args, kwargs) [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs) [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 905, in inline_user_function_return [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return InliningInstructionTranslator.inline_call(self, fn, args, kwargs) [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3069, in inline_call [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return cls.inline_call_(parent, func, args, kwargs) [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 3195, in inline_call_ [repeated 14x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1750, in CALL_FUNCTION_KW [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.call_function(fn, args, kwargs) [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1738, in CALL_FUNCTION_EX [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.call_function(fn, argsvars.items, kwargsvars) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 315, in impl [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     self.push(fn_var.call_function(self, self.popn(nargs), {})) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return handler(tx, args, kwargs) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 980, in _handle_insert_op_in_graph [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return wrap_fx_proxy(tx, proxy) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 2123, in wrap_fx_proxy [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 2189, in wrap_fx_proxy_cls [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return _wrap_fx_proxy( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 2285, in _wrap_fx_proxy [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2411, in get_fake_value [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     ret_val = wrap_fake_exception( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1957, in wrap_fake_exception [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return fn() [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2412, in <lambda> [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     lambda: run_node(tx.output, node, args, kwargs, nnmodule) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/.venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 2526, in run_node [repeated 4x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     raise RuntimeError(make_error_message(e)).with_traceback( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return node.target(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., device='xla:0', size=(1, s1, 24)), 1), **{}): [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] index 1 is out of bounds for dimension 0 with size 1 [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]  [repeated 10x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] from user code: [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]    File "/home/carlesoctav/vllm/vllm/worker/tpu_model_runner.py", line 816, in forward [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     hidden_states = self.model( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/model_executor/models/qwen2.py", line 175, in forward [repeated 8x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     hidden_states = self.language_model.model( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/compilation/decorators.py", line 170, in __call__ [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     return self.forward(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     hidden_states, residual = layer( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     hidden_states = self.self_attn( [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     q, k = self.rotary_emb(positions, q, k) [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/model_executor/layers/rotary_embedding.py", line 813, in forward [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     cos = torch.cat([ [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]   File "/home/carlesoctav/vllm/vllm/model_executor/layers/rotary_embedding.py", line 814, in <listcomp> [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     m[i] [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467] You can suppress this exception and fall back to eager by setting: [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     import torch._dynamo [repeated 2x across cluster]
(RayWorkerWrapper pid=22792) ERROR 12-08 10:40:08 worker_base.py:467]     torch._dynamo.config.suppress_errors = True [repeated 2x across cluster]
(RayWorkerWrapper pid=22778) WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU. [repeated 2x across cluster]
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by carlesoctav** [comment]
this output is maybe more informative for debugging:
```
[rank0]: torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., device='xla:0', size=(1, s1, 24)), 1), **{}):
[rank0]: index 1 is out of bounds for dimension 0 with size 1

```

**Comment by bvrockwell** [comment]
Hey @carlesoctav ! Thanks very much for this bug, we're landing multimodal model support for TPU in a month or so, so we'll check back on this bug when it's ready!!
