### ISSUE TITLE
gptq  Qwen-7B-Chat-Int4 load_error

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [vllm-project/vllm#1100]
qwen.py", line 303, in load_weights
    param = state_dict[name]
KeyError: 'transformer.h.0.attn.c_attn.g_idx'

**Comment by hhxx2015** [comment]
```shell
CUDA_VISIBLE_DEVICES=3 python3 -m vllm.entrypoints.openai.api_server --model "/data/transformers/Qwen/Qwen-7B-Chat-Int4" --trust-remote-code --host 0.0.0.0 --port 50111
```

```
INFO 09-21 11:09:41 llm_engine.py:72] Initializing an LLM engine with config: model='/data/transformers/Qwen/Qwen-7B-Chat-Int4', tokenizer='/data/transformers/Qwen/Qwen-7B-Chat-Int4', tokenizer_mode=auto, revision=None, trust_remote_code=True, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
WARNING 09-21 11:09:42 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/server/vllm/vllm/entrypoints/openai/api_server.py", line 624, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/server/vllm/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/workspace/server/vllm/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/server/vllm/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/server/vllm/vllm/engine/llm_engine.py", line 105, in __init__
    self._init_workers(distributed_init_method)
  File "/workspace/server/vllm/vllm/engine/llm_engine.py", line 137, in _init_workers
    self._run_workers(
  File "/workspace/server/vllm/vllm/engine/llm_engine.py", line 685, in _run_workers
    output = executor(*args, **kwargs)
  File "/workspace/server/vllm/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "/workspace/server/vllm/vllm/model_executor/model_loader.py", line 100, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/workspace/server/vllm/vllm/model_executor/models/qwen.py", line 312, in load_weights
    param = state_dict[name]
KeyError: 'transformer.h.0.attn.c_attn.g_idx'

```

**Comment by TitanWhoo** [comment]
same issue

**Comment by shujun1992** [comment]
Qwen-14B-Chat-Int4   same issue

**Comment by allendred** [comment]
Qwen-14B-Chat-Int4 same issue

**Comment by wangschang** [comment]
same issue . is it not supprot gptq?

**Comment by allendred** [comment]
The error occurs only in the quantized version, not in FP16. However, FP16 consumes a significant amount of memory. How can I perform model quantization?

**Comment by pjpan** [comment]
same issue, is anybody solved?

**Comment by DanteYuan** [comment]
Mark

**Comment by Johnny-xyz** [comment]
same issue, is anybody solved?

**Comment by Johnny-xyz** [comment]
same issue
KeyError: transformer.h.27.mlp.gate_up_proj.bias
![Uploading image.png…]()

**Comment by Johnny-xyz** [comment]
same issue
KeyError: transformer.h.27.mlp.gate_up_proj.bias
![image](https://github.com/vllm-project/vllm/assets/56420183/75ba3f97-6975-4731-93a3-9b9e2df7fb86)

**Comment by YuRong-Lin** [comment]
Qwen-14B-Chat-Int4 same issue

**Comment by Dinghow** [comment]
This works for me, I quantized a Qwen-72B model by myself, and I edited the config.json with an addition seems like the [official repo](https://huggingface.co/Qwen/Qwen-72B-Chat-Int4/blob/main/config.json)
```yaml
  "quantization_config": {
    "bits": 4,
    "group_size": 128,
    "damp_percent": 0.01,
    "desc_act": false,
    "static_groups": false,
    "sym": true,
    "true_sequential": true,
    "model_name_or_path": null,
    "model_file_base_name": "model",
    "quant_method": "gptq"
  },
```
