### ISSUE TITLE
[Bug]: unsloth/Llama-3.3-70B-Instruct-bnb-4bit can't work on vllm 0.6.4.post1

### ISSUE THREAD

**Issue by tonyaw** [vllm-project/vllm#11010]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

I'm using following command to load Llama3.3 on one GPU:
```
CUDA_VISIBLE_DEVICES=1  python3 -m vllm.entrypoints.openai.api_server --model unsloth/Llama-3.3-70B-Instruct-bnb-4bit            --host 0.0.0.0 --port 8081  --seed 42 --trust-remote-code --enable-chunked-prefill            --tensor-parallel-size 1 --max-model-len 1024
```

Got error:
```
Loading safetensors checkpoint shards:   0% Completed | 0/8 [00:00<?, ?it/s]
ERROR 12-09 00:49:29 engine.py:366] 'layers.0.mlp.down_proj.weight.absmax'
ERROR 12-09 00:49:29 engine.py:366] Traceback (most recent call last):
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-09 00:49:29 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-09 00:49:29 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-09 00:49:29 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-09 00:49:29 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-09 00:49:29 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-09 00:49:29 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 12-09 00:49:29 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-09 00:49:29 engine.py:366]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-09 00:49:29 engine.py:366]     self._init_executor()
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
ERROR 12-09 00:49:29 engine.py:366]     self.driver_worker.load_model()
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 152, in load_model
ERROR 12-09 00:49:29 engine.py:366]     self.model_runner.load_model()
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1074, in load_model
ERROR 12-09 00:49:29 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 12-09 00:49:29 engine.py:366]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 12-09 00:49:29 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 12-09 00:49:29 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
ERROR 12-09 00:49:29 engine.py:366]     model.load_weights(self._get_all_weights(model_config, model))
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 586, in load_weights
ERROR 12-09 00:49:29 engine.py:366]     loader.load_weights(
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 229, in load_weights
ERROR 12-09 00:49:29 engine.py:366]     autoloaded_weights = list(self._load_module("", self.module, weights))
ERROR 12-09 00:49:29 engine.py:366]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 190, in _load_module
ERROR 12-09 00:49:29 engine.py:366]     yield from self._load_module(prefix,
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 175, in _load_module
ERROR 12-09 00:49:29 engine.py:366]     module_load_weights(weights)
ERROR 12-09 00:49:29 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 407, in load_weights
ERROR 12-09 00:49:29 engine.py:366]     param = params_dict[name]
ERROR 12-09 00:49:29 engine.py:366]             ~~~~~~~~~~~^^^^^^
ERROR 12-09 00:49:29 engine.py:366] KeyError: 'layers.0.mlp.down_proj.weight.absmax'
```

Could you please advice what is going on and how to fix it? 
Thanks in advance!

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by lebronjamesking** [comment]
Any updates so far, as I cannot infer on Llama-3___3-70B-Instruct-bnb-4bit. I got something weired like KeyError: 'layers.74.mlp.down_proj.weight.absmax'

**Comment by nikhilcms** [comment]
with unsloth/Llama-3.3-70B-Instruct-bnb-4bit I am getting "KeyError: 'layers.0.mlp.down_proj.weight.absmax'" error,


also I tried casperhansen/llama-3.3-70b-instruct-awq weights  this also we are getting "ValueError: Converting from Tiktoken failed, if a converter for SentencePiece is available, provide a model path with a SentencePiece tokenizer.model file.Currently available slow->fast convertors" error.

for both experiment, I used latest vllm image: vllm/vllm-openai:v0.6.6.post1

please have solution to support quantized version of llama3.3 model

**Comment by cpwan** [comment]
Same here

bitsandbytes                      0.44.0
transformers                      4.46.3
vllm                              0.6.3.post1

```
  File "/usr/local/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 414, in load_weights
    param = params_dict[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'layers.62.mlp.down_proj.weight'
```

**Comment by cpwan** [comment]
Similar issue in the comment field.
https://github.com/vllm-project/vllm/issues/10964#issuecomment-2541519931

**Comment by chaostracker** [comment]
I too have a similar issue with unsloth/Llama-3.3-70B-Instruct-bnb-4bit on a single L40s:
`ERROR 02-07 11:38:50 engine.py:389]     param = params_dict[name]
ERROR 02-07 11:38:50 engine.py:389]             ~~~~~~~~~~~^^^^^^
ERROR 02-07 11:38:50 engine.py:389] KeyError: 'layers.40.mlp.down_proj.weight.absmax'`

**Comment by JulienVig** [comment]
Same error with `llm = LLM(model="unsloth/Llama-3.3-70B-Instruct-bnb-4bit")`:
```
KeyError: 'layers.0.mlp.down_proj.weight.absmax'
```
