### ISSUE TITLE
[Bug]: Docker deployment model encountered an exception

### ISSUE THREAD

**Issue by kerry-weic** [vllm-project/vllm#11084]
### Your current environment

docker vllm imags version:
```
vllm/vllm-openai                                latest                               698668586297   3 weeks ago     10.6GB
```

nvidia-smi:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.78                 Driver Version: 550.78         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:4B:00.0 Off |                  Off |
| 30%   33C    P8             22W /  450W |    7981MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:65:00.0 Off |                  Off |
| 30%   28C    P8             13W /  450W |    7981MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
```

### 🐛 Describe the bug

docker run:
```
docker run --gpus all --ipc=host -p 8000:8000 -e VLLM_USE_MODELSCOPE=True vllm/vllm-openai --model=Qwen/Qwen2.5-7B-Instruct --tensor-parallel-size=2
```

docker logs:
```
INFO 12-10 19:40:18 api_server.py:585] vLLM API server version 0.6.4.post1
INFO 12-10 19:40:18 api_server.py:586] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-7B-Instruct', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', chat_template_text_format='string', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
INFO 12-10 19:40:18 api_server.py:175] Multiprocessing frontend to use ipc:///tmp/9be31d2f-b4e8-4e21-977d-9a92df855d16 for IPC Path.
INFO 12-10 19:40:18 api_server.py:194] Started engine process with PID 76
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
Downloading [config.json]: 100%|██████████| 663/663 [00:00<00:00, 1.21kB/s]
Downloading [configuration.json]: 100%|██████████| 2.00/2.00 [00:00<00:00, 5.40B/s]
Downloading [generation_config.json]: 100%|██████████| 243/243 [00:00<00:00, 678B/s]
Downloading [LICENSE]: 100%|██████████| 11.1k/11.1k [00:00<00:00, 26.2kB/s]
Downloading [merges.txt]: 100%|██████████| 1.59M/1.59M [00:00<00:00, 2.33MB/s]
Downloading [README.md]: 100%|██████████| 5.85k/5.85k [00:00<00:00, 15.0kB/s]
Downloading [tokenizer.json]: 100%|██████████| 6.71M/6.71M [00:00<00:00, 8.06MB/s]
Downloading [tokenizer_config.json]: 100%|██████████| 7.13k/7.13k [00:00<00:00, 20.8kB/s]
Downloading [vocab.json]: 100%|██████████| 2.65M/2.65M [00:00<00:00, 3.78MB/s]
2024-12-10 19:40:25,042 - modelscope - INFO - Creating symbolic link [/root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct].
2024-12-10 19:40:25,768 - modelscope - INFO - Target directory already exists, skipping creation.
2024-12-10 19:40:28,523 - modelscope - INFO - Target directory already exists, skipping creation.
2024-12-10 19:40:29,235 - modelscope - INFO - Target directory already exists, skipping creation.
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
INFO 12-10 19:40:37 config.py:350] This model supports multiple tasks: {'generate', 'embedding'}. Defaulting to 'generate'.
INFO 12-10 19:40:39 config.py:1020] Defaulting to use mp for distributed inference
WARNING 12-10 19:40:39 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
2024-12-10 19:40:40,338 - modelscope - INFO - Target directory already exists, skipping creation.
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
INFO 12-10 19:40:40 config.py:350] This model supports multiple tasks: {'generate', 'embedding'}. Defaulting to 'generate'.
INFO 12-10 19:40:40 config.py:1020] Defaulting to use mp for distributed inference
WARNING 12-10 19:40:40 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
INFO 12-10 19:40:40 llm_engine.py:249] Initializing an LLM engine (v0.6.4.post1) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=None)
2024-12-10 19:40:41,400 - modelscope - INFO - Target directory already exists, skipping creation.
2024-12-10 19:40:53,045 - modelscope - INFO - Target directory already exists, skipping creation.
2024-12-10 19:40:53,739 - modelscope - INFO - Target directory already exists, skipping creation.
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
WARNING 12-10 19:40:53 multiproc_gpu_executor.py:56] Reducing Torch parallelism from 48 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 12-10 19:40:53 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 12-10 19:40:53 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=349) INFO 12-10 19:40:53 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=349) INFO 12-10 19:40:53 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 12-10 19:40:54 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=349) INFO 12-10 19:40:54 utils.py:961] Found nccl from library libnccl.so.2
INFO 12-10 19:40:54 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=349) INFO 12-10 19:40:54 pynccl.py:69] vLLM is using nccl==2.21.5
INFO 12-10 19:40:54 custom_all_reduce_utils.py:204] generating GPU P2P access cache in /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=349) INFO 12-10 19:41:05 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 12-10 19:41:05 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=349) WARNING 12-10 19:41:05 custom_all_reduce.py:143] Custom allreduce is disabled because your platform lacks GPU P2P capability or P2P test failed. To silence this warning, specify disable_custom_all_reduce=True explicitly.
WARNING 12-10 19:41:05 custom_all_reduce.py:143] Custom allreduce is disabled because your platform lacks GPU P2P capability or P2P test failed. To silence this warning, specify disable_custom_all_reduce=True explicitly.
INFO 12-10 19:41:05 shm_broadcast.py:236] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x7f0c07dc8830>, local_subscribe_port=34496, remote_subscribe_port=None)
INFO 12-10 19:41:05 model_runner.py:1072] Starting to load model Qwen/Qwen2.5-7B-Instruct...
(VllmWorkerProcess pid=349) INFO 12-10 19:41:05 model_runner.py:1072] Starting to load model Qwen/Qwen2.5-7B-Instruct...
(VllmWorkerProcess pid=349) Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
Downloading [model-00001-of-00004.safetensors]:   0%|          | 0.00/3.67G [00:00<?, ?B/s]Downloading Model to directory: /root/.cache/modelscope/hub/Qwen/Qwen2.5-7B-Instruct
Downloading [model-00001-of-00004.safetensors]: 100%|██████████| 3.67G/3.67G [02:10<00:00, 30.3MB/s]
Downloading [model-00001-of-00004.safetensors]: 100%|██████████| 3.67G/3.67G [02:16<00:00, 28.8MB/s]
(VllmWorkerProcess pid=349) 2024-12-10 19:43:24,080 - modelscope - ERROR - File /root/.cache/modelscope/hub/._____temp/Qwen/Qwen2.5-7B-Instruct/model-00001-of-00004.safetensors integrity check failed, expected sha256 signature is a1333e6293854747c481288ea83b348226af178dd565c49b6f9495ba1966aba7, actual is e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, the download may be incomplete, please try again.
ERROR 12-10 19:43:24 engine.py:366] [Errno 2] No such file or directory: '/root/.cache/modelscope/hub/._____temp/Qwen/Qwen2.5-7B-Instruct/model-00001-of-00004.safetensors_0_167772159'
ERROR 12-10 19:43:24 engine.py:366] Traceback (most recent call last):
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-10 19:43:24 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-10 19:43:24 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-10 19:43:24 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-10 19:43:24 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-10 19:43:24 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-10 19:43:24 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 12-10 19:43:24 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-10 19:43:24 engine.py:366]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
ERROR 12-10 19:43:24 engine.py:366]     super().__init__(*args, **kwargs)
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-10 19:43:24 engine.py:366]     self._init_executor()
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 114, in _init_executor
ERROR 12-10 19:43:24 engine.py:366]     self._run_workers("load_model",
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 195, in _run_workers
ERROR 12-10 19:43:24 engine.py:366]     driver_worker_output = driver_worker_method(*args, **kwargs)
ERROR 12-10 19:43:24 engine.py:366]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 152, in load_model
ERROR 12-10 19:43:24 engine.py:366]     self.model_runner.load_model()
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1074, in load_model
ERROR 12-10 19:43:24 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 12-10 19:43:24 engine.py:366]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 12-10 19:43:24 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 12-10 19:43:24 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
ERROR 12-10 19:43:24 engine.py:366]     model.load_weights(self._get_all_weights(model_config, model))
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 503, in load_weights
ERROR 12-10 19:43:24 engine.py:366]     loader.load_weights(weights)
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 229, in load_weights
ERROR 12-10 19:43:24 engine.py:366]     autoloaded_weights = list(self._load_module("", self.module, weights))
ERROR 12-10 19:43:24 engine.py:366]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 181, in _load_module
ERROR 12-10 19:43:24 engine.py:366]     for child_prefix, child_weights in self._groupby_prefix(weights):
ERROR 12-10 19:43:24 engine.py:366]                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 103, in _groupby_prefix
ERROR 12-10 19:43:24 engine.py:366]     for prefix, group in itertools.groupby(weights_by_parts,
ERROR 12-10 19:43:24 engine.py:366]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 101, in <genexpr>
ERROR 12-10 19:43:24 engine.py:366]     for weight_name, weight_data in weights)
ERROR 12-10 19:43:24 engine.py:366]                                     ^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 313, in _get_all_weights
ERROR 12-10 19:43:24 engine.py:366]     yield from self._get_weights_iterator(primary_weights)
ERROR 12-10 19:43:24 engine.py:366]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 272, in _get_weights_iterator
ERROR 12-10 19:43:24 engine.py:366]     hf_folder, hf_weights_files, use_safetensors = self._prepare_weights(
ERROR 12-10 19:43:24 engine.py:366]                                                    ^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 200, in _prepare_weights
ERROR 12-10 19:43:24 engine.py:366]     model_name_or_path = self._maybe_download_from_modelscope(
ERROR 12-10 19:43:24 engine.py:366]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 182, in _maybe_download_from_modelscope
ERROR 12-10 19:43:24 engine.py:366]     model_path = snapshot_download(
ERROR 12-10 19:43:24 engine.py:366]                  ^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/modelscope/hub/snapshot_download.py", line 85, in snapshot_download
ERROR 12-10 19:43:24 engine.py:366]     return _snapshot_download(
ERROR 12-10 19:43:24 engine.py:366]            ^^^^^^^^^^^^^^^^^^^
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/modelscope/hub/snapshot_download.py", line 249, in _snapshot_download
ERROR 12-10 19:43:24 engine.py:366]     _download_file_lists(
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/modelscope/hub/snapshot_download.py", line 445, in _download_file_lists
ERROR 12-10 19:43:24 engine.py:366]     download_file(url, repo_file, temporary_cache_dir, cache, headers,
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/modelscope/hub/file_download.py", line 593, in download_file
ERROR 12-10 19:43:24 engine.py:366]     parallel_download(
ERROR 12-10 19:43:24 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/modelscope/hub/file_download.py", line 415, in parallel_download
ERROR 12-10 19:43:24 engine.py:366]     with open(part_file_name, 'rb') as part_file:
ERROR 12-10 19:43:24 engine.py:366]          ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by kerry-weic** [comment]
I tried multiple times, but when I removed the **tensor-parallel-size** parameter setting, the model was able to download normally
