### ISSUE TITLE
[Bug]: vllm 0.6.4 部署 MiniCPM-V_2_6_awq_int4 报错

### ISSUE THREAD

**Issue by fengqiliang93** [vllm-project/vllm#11128]
### Your current environment

<details>
<summary>python3 -m vllm.entrypoints.openai.api_server --model MiniCPM-V_2_6_awq_int4/ --trust-remote-code 报错</summary>

```text
INFO 12-12 01:40:53 model_runner.py:1072] Starting to load model MiniCPM-V_2_6_awq_int4/...
ERROR 12-12 01:40:53 engine.py:366] Weight output_size_per_partition = 4304 is not divisible by  min_thread_n = 64. Consider reducing tensor_parallel_size or running with --quantization gptq.
ERROR 12-12 01:40:53 engine.py:366] Traceback (most recent call last):
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-12 01:40:53 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-12 01:40:53 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-12 01:40:53 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-12 01:40:53 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-12 01:40:53 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-12 01:40:53 engine.py:366]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self._init_executor()
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
ERROR 12-12 01:40:53 engine.py:366]     self.driver_worker.load_model()
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 152, in load_model
ERROR 12-12 01:40:53 engine.py:366]     self.model_runner.load_model()
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1074, in load_model
ERROR 12-12 01:40:53 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 12-12 01:40:53 engine.py:366]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 12-12 01:40:53 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 12-12 01:40:53 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 316, in load_model
ERROR 12-12 01:40:53 engine.py:366]     model = _initialize_model(vllm_config=vllm_config)
ERROR 12-12 01:40:53 engine.py:366]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 108, in _initialize_model
ERROR 12-12 01:40:53 engine.py:366]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 12-12 01:40:53 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/minicpmv.py", line 1119, in __new__
ERROR 12-12 01:40:53 engine.py:366]     return instance_class(vllm_config=vllm_config, prefix=prefix)
ERROR 12-12 01:40:53 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/minicpmv.py", line 991, in __init__
ERROR 12-12 01:40:53 engine.py:366]     super().__init__(vllm_config=vllm_config, prefix=prefix)
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/minicpmv.py", line 400, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self.vpm = self.init_vision_module(config,
ERROR 12-12 01:40:53 engine.py:366]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/minicpmv.py", line 1008, in init_vision_module
ERROR 12-12 01:40:53 engine.py:366]     model = Idefics2VisionTransformer(config.vision_config,
ERROR 12-12 01:40:53 engine.py:366]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/idefics2_vision_model.py", line 311, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self.encoder = Idefics2Encoder(config,
ERROR 12-12 01:40:53 engine.py:366]                    ^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/idefics2_vision_model.py", line 272, in __init__
ERROR 12-12 01:40:53 engine.py:366]     Idefics2EncoderLayer(config,
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/idefics2_vision_model.py", line 225, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self.mlp = Idefics2VisionMLP(config,
ERROR 12-12 01:40:53 engine.py:366]                ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/idefics2_vision_model.py", line 188, in __init__
ERROR 12-12 01:40:53 engine.py:366]     self.fc1 = ColumnParallelLinear(
ERROR 12-12 01:40:53 engine.py:366]                ^^^^^^^^^^^^^^^^^^^^^
ERROR 12-12 01:40:53 engine.py:366]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 304, in __init_
```

</details>

### 🐛 Describe the bug

vllm 0.6.4 部署 [MiniCPM-V_2_6_awq_int4](https://www.modelscope.cn/models/linglingdan/MiniCPM-V_2_6_awq_int4) 报错。错误信息如上。另外，也尝试用vllm0.6.4 部署 MiniCPM-V_2_6 的 bnb、gptq  int4量化版本，均未成功。
但vllm 0.5.4 部署 [MiniCPM-V_2_6_awq_int4](https://www.modelscope.cn/models/linglingdan/MiniCPM-V_2_6_awq_int4) 可以成功。

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
## For AWQ

 - try modifying the [configuration](https://www.modelscope.cn/models/linglingdan/MiniCPM-V_2_6_awq_int4/file/view/master?fileName=config.json&status=1#L31)  with:

```shell
"modules_to_not_convert": ["vpm", "resampler"]
```
- In version 0.5.4, the `vpm` and `resampler` parts of this model don't support quantization yet, so it doesn't matter if you don't set `modules_to_not_convert` because they will be automatically skipped anyway.
 
## For BNB  int4

This needs further investigation. But the BNB in-flight quantization is ok.

## For GPTQ

Could you please provide the model info or link? Maybe it's a similar issue with AWQ

**Comment by fengqiliang93** [comment]
Thank you for your reply. I will try again. @jeejeelee

**Comment by franklyd** [comment]
Thanks @jeejeelee ! I tried to add this line and it works!
I used this awq version: https://huggingface.co/jfiekdjdk/MiniCPM-V-2_6-awq
