### ISSUE TITLE
[Bug]: vllm.core.block.interfaces.BlockAllocator.NoFreeBlocksError to old Mistral Model

### ISSUE THREAD

**Issue by fahadh4ilyas** [vllm-project/vllm#11168]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.35

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.25-051525-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      13th Gen Intel(R) Core(TM) i5-13400
CPU family:                      6
Model:                           191
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       1
Stepping:                        2
CPU max MHz:                     3425.8350
CPU min MHz:                     800.0000
BogoMIPS:                        4992.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx
pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx
 est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb
 invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap
 clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke wa
itpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       416 KiB (10 instances)
L1i cache:                       448 KiB (10 instances)
L2 cache:                        9.5 MiB (7 instances)
L3 cache:                        20 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-ml-py==12.560.30
[pip3] optree==0.12.1
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.19.0
[pip3] transformers==4.46.0
[pip3] triton==3.0.0
[conda] blas                      1.0                         mkl
[conda] cuda-cudart               12.1.105                      0    nvidia
[conda] cuda-cupti                12.1.105                      0    nvidia
[conda] cuda-libraries            12.1.0                        0    nvidia
[conda] cuda-nvrtc                12.1.105                      0    nvidia
[conda] cuda-nvtx                 12.1.105                      0    nvidia
[conda] cuda-opencl               12.5.39                       0    nvidia
[conda] cuda-runtime              12.1.0                        0    nvidia
[conda] cuda-version              12.5                          3    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libcublas                 12.1.0.26                     0    nvidia
[conda] libcufft                  11.0.2.4                      0    nvidia
[conda] libcufile                 1.10.1.7                      0    nvidia
[conda] libcurand                 10.3.6.82                     0    nvidia
[conda] libcusolver               11.4.4.55                     0    nvidia
[conda] libcusparse               12.0.2.55                     0    nvidia
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] libnpp                    12.0.2.50                     0    nvidia
[conda] libnvjitlink              12.1.105                      0    nvidia
[conda] libnvjpeg                 12.1.1.14                     0    nvidia
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0           py311h5eee18b_1
[conda] mkl_fft                   1.3.8           py311h5eee18b_0
[conda] mkl_random                1.2.4           py311hdb19cb5_0
[conda] numpy                     1.26.4          py311h08b1b3b_0
[conda] numpy-base                1.26.4          py311hf175353_0
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] pytorch                   2.4.0           py3.11_cuda12.1_cudnn9.1.0_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.4.0               py311_cu121    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtriton               3.0.0                     py311    pytorch
[conda] torchvision               0.19.0              py311_cu121    pytorch
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.1.dev3151+g31c7178 (git sha: 31c7178
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

NVIDIA_VISIBLE_DEVICES=GPU-bce6a93f-3c2e-5454-a4e9-ab8b98b80cae
NVIDIA_DRIVER_CAPABILITIES=compute,utility
PYTORCH_VERSION=2.4.0
LD_LIBRARY_PATH=/workspace-lib/lib/python3.11/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

</details>

### 🐛 Describe the bug

Here is what is logged from `vllm serve`

```
ERROR 12-13 08:58:11 engine.py:165] NoFreeBlocksError()
ERROR 12-13 08:58:11 engine.py:165] Traceback (most recent call last):
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 163, in start
ERROR 12-13 08:58:11 engine.py:165] self.run_engine_loop()
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 226, in run_engine_loop
ERROR 12-13 08:58:11 engine.py:165] request_outputs = self.engine_step()
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 244, in engine_step
ERROR 12-13 08:58:11 engine.py:165] raise e
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 235, in engine_step
ERROR 12-13 08:58:11 engine.py:165] return self.engine.step()
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 1374, in step
ERROR 12-13 08:58:11 engine.py:165] ) = self.scheduler[virtual_engine].schedule()
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1219, in schedule
ERROR 12-13 08:58:11 engine.py:165] scheduler_outputs: SchedulerOutputs = self._schedule()
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1178, in _schedule
ERROR 12-13 08:58:11 engine.py:165] return self._schedule_default()
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1013, in _schedule_default
ERROR 12-13 08:58:11 engine.py:165] prefills = self._schedule_prefills(budget,
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/scheduler.py", line 949, in _schedule_prefills
ERROR 12-13 08:58:11 engine.py:165] self._allocate_and_set_running(seq_group)
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1413, in _allocate_and_set_running
ERROR 12-13 08:58:11 engine.py:165] self.block_manager.allocate(seq_group)
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block_manager.py", line 169, in allocate
ERROR 12-13 08:58:11 engine.py:165] block_table: BlockTable = self._allocate_sequence(seq)
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block_manager.py", line 155, in _allocate_sequence
ERROR 12-13 08:58:11 engine.py:165] block_table.allocate(seq.get_token_ids())
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block/block_table.py", line 96, in allocate
ERROR 12-13 08:58:11 engine.py:165] blocks = self._allocate_blocks_for_token_ids(prev_block=None,
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block/block_table.py", line 277, in _allocate_blocks_for_token_ids
ERROR 12-13 08:58:11 engine.py:165] self._allocator.allocate_immutable_blocks(
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block/cpu_gpu_block_allocator.py", line 150, in allocate_immutable_blocks
ERROR 12-13 08:58:11 engine.py:165] return self._allocators[device].allocate_immutable_blocks(
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block/naive_block.py", line 94, in allocate_immutable_blocks
ERROR 12-13 08:58:11 engine.py:165] block_ids.append(self._allocate_block_id())
ERROR 12-13 08:58:11 engine.py:165] ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 12-13 08:58:11 engine.py:165] File "/workspace-lib/lib/python3.11/site-packages/vllm/core/block/naive_block.py", line 130, in _allocate_block_id
ERROR 12-13 08:58:11 engine.py:165] raise BlockAllocator.NoFreeBlocksError()
ERROR 12-13 08:58:11 engine.py:165] vllm.core.block.interfaces.BlockAllocator.NoFreeBlocksError
```

Here is the config file of the model I serve

```json
{
  "_name_or_path": "mistral-7B",
  "architectures": [
    "MistralForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 32000,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 8192,
  "model_type": "mistral",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "rms_norm_eps": 1e-05,
  "rope_theta": 10000.0,
  "sliding_window": 4096,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32019
}
```

I suspect there is problem because of the model. I'm using mistral as base model.

Here is how I serve the model

```bash
vllm serve my-model --host 0.0.0.0 --served-model-name my-model --port 8000 --enforce-eager
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by fahadh4ilyas** [comment]
So, there is no solution to this?

**Comment by Abineshik** [comment]
Hello, I faced the same issue on running bulk prompts.  Is there any solution?

**Comment by Kagam11** [comment]
Same issue while running starcoder2 with long input. Tried adjust enforce_eager, or increase block_size, or decrease max_num_seqs, this will sometimes fix the problem, but not completely.
