### ISSUE TITLE
Stuck when running benchmarks/benchmark_throughput.py

### ISSUE THREAD

**Issue by simple86** [vllm-project/vllm#1118]
I was trying vllm with [benchmarks/benchmark_throughput.py](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py). It got stuck, while everything works well with hf backend. So, what seems to be the problem?

environment:
```
nvcr.io/nvidia/pytorch:22.12-py3
GPU: T4
```
vllm version: 
```
vllm-0.1.7
```
cmd:
```
python benchmark_throughput.py \
	--backend vllm \
	--dataset /workspace/tests/llama/ShareGPT_V3_unfiltered_cleaned_split.json \
	--model /workspace/tests/llama/open_llama_7b_v2 \
	--num-prompts 1
```
log:
```
Namespace(backend='vllm', dataset='/workspace/tests/llama/ShareGPT_V3_unfiltered_cleaned_split.json', hf_max_batch_size=None, model='/workspace/tests/llama/open_llama_7b_v2', n=1, num_prompts=1, seed=0, tensor_parallel_size=1, tokenizer='/workspace/tests/llama/open_llama_7b_v2', trust_remote_code=False, use_beam_search=False)
INFO 09-21 03:44:48 tokenizer.py:30] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Token indices sequence length is longer than the specified maximum sequence length for this model (2862 > 2048). Running this sequence through the model will result in indexing errors
INFO 09-21 03:45:22 llm_engine.py:72] Initializing an LLM engine with config: model='/workspace/tests/llama/open_llama_7b_v2', tokenizer='/workspace/tests/llama/open_llama_7b_v2', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, download_dir=None, load_format=auto, tensor_parallel_size=1, seed=0)
INFO 09-21 03:45:22 tokenizer.py:30] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:55559 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:55559 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:55559 (errno: 97 - Address family not supported by protocol).
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
INFO 09-21 03:45:39 llm_engine.py:199] # GPU blocks: 24, # CPU blocks: 512
Processed prompts:   0%|                                         | 0/1 [00:00<?, ?it/s]
```
It's stuck for a long time here, and CPU util is full at this moment.
backtrace:
```
^CTraceback (most recent call last):
  File "benchmark_throughput.py", line 221, in <module>
    main(args)
  File "benchmark_throughput.py", line 172, in main
    elapsed_time = run_vllm(
  File "benchmark_throughput.py", line 99, in run_vllm
    llm._run_engine(use_tqdm=True)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/llm.py", line 149, in _run_engine
    while self.llm_engine.has_unfinished_requests():
KeyboardInterrupt
```

**Comment by WoosukKwon** [comment]
@simple86 Thanks for trying out vLLM and reporting the issue.

> # GPU blocks: 24

It seems you initialized 7B model (i.e., 14GB parameters) on T4 which has 16GB memory. Therefore, you have very limited memory space; so small that it cannot hold a single request. In such a case, currently vLLM might hang. We will fix this bug and raise an error when the memory is too limited. Thanks again for letting us know the issue.
