### ISSUE TITLE
[Installation]: System missing some CUDA libraries/not linked properly?

### ISSUE THREAD

**Issue by james-hx-song** [vllm-project/vllm#11215]
### Your current environment

```text
The output of `python collect_env.py`

Traceback (most recent call last):
  File "/home/shxjames/llm-eval/collect_env.py", line 15, in <module>
    from vllm.envs import environment_variables
  File "/home/shxjames/.conda/envs/inference/lib/python3.10/site-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/home/shxjames/.conda/envs/inference/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 8, in <module>
    import torch
  File "/home/shxjames/.conda/envs/inference/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/shxjames/.conda/envs/inference/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

### How you are installing vllm

```sh
conda create -n inference python=3.10 -y
conda activate inference
pip install vllm
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by james-hx-song** [comment]
Same exact error when importing vllm library.

**Comment by robertgshaw2-neuralmagic** [comment]
Your machine has cuda runtime < 12.4 and torch 2.5 uses 12.4 bindings by default. Just run the following to install vllm with the 12.1 torch wheels:

```bash
pip install vllm --extra-index-url https://download.pytorch.org/whl/cu121
```

**Comment by flaviussn** [comment]
@robertgshaw2-redhat The solution you provided worked perfectly for my case. Thank you!
