### ISSUE TITLE
[Bug]: Failed to run docker vllm-cpu-env arm docker on MacOS

### ISSUE THREAD

**Issue by MoSedkyy** [vllm-project/vllm#11266]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

After building Docker Images with [Dockerfile.arm](https://docs.vllm.ai/en/latest/getting_started/arm-installation.html), it built successfully but when attempts to run `docker run -it \
             --rm \
             --network=host \
             vllm-cpu-env --device="cpu" --disable_async_output_proc --enforce-eager --model=Qwen/Qwen2.5-1.5B-Instruct --dtype=float16`. it gets error in :
`File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 1639, in resolve_obj_by_qualname
    module_name, obj_name = qualname.rsplit(".", 1)
`
I am running on MacStudio Ultra and env is collected by building `Dockerfile.arm` file by executing `docker build -f Dockerfile.arm -t vllm-cpu-env --shm-size=4g .`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by sanketkaleoss** [comment]
Can you confirm if this error is only for this particular model? Also can you provide the error SC

**Comment by MoSedkyy** [comment]
@sanketkaleoss Thanks for your quick reply. No, I have tried it with the default Model `facebook/opt-125m`,`meta-llama/Llama-Guard-3-1B` and `Qwen/Qwen2.5-1.5B-Instruct`, it gives the same failure. Please find below error SC:


```ERROR 12-17 18:40:37 engine.py:366] not enough values to unpack (expected 2, got 1)
ERROR 12-17 18:40:37 engine.py:366] Traceback (most recent call last):
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-17 18:40:37 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-17 18:40:37 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-17 18:40:37 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 288, in __init__
ERROR 12-17 18:40:37 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-17 18:40:37 engine.py:366]     self._init_executor()
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 81, in _init_executor
ERROR 12-17 18:40:37 engine.py:366]     self.driver_worker = self._create_worker()
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 127, in _create_worker
ERROR 12-17 18:40:37 engine.py:366]     wrapper.init_worker(**kwargs)
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 450, in init_worker
ERROR 12-17 18:40:37 engine.py:366]     worker_class = resolve_obj_by_qualname(
ERROR 12-17 18:40:37 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 1639, in resolve_obj_by_qualname
ERROR 12-17 18:40:37 engine.py:366]     module_name, obj_name = qualname.rsplit(".", 1)
ERROR 12-17 18:40:37 engine.py:366] ValueError: not enough values to unpack (expected 2, got 1)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
    return cls(ipc_path=ipc_path,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 288, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 81, in _init_executor
    self.driver_worker = self._create_worker()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 127, in _create_worker
    wrapper.init_worker(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 450, in init_worker
    worker_class = resolve_obj_by_qualname(
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 1639, in resolve_obj_by_qualname
    module_name, obj_name = qualname.rsplit(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 706, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 672, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 117, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 222, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.```

**Comment by MoSedkyy** [comment]
I have tried to get latest from yesterday's version and it's working properly now. Not sure if yesterday's release included this fix or it's my lucky day 🪄  😄

**Comment by sanketkaleoss** [comment]
> I have tried to get latest from yesterday's version and it's working properly now. Not sure if yesterday's release included this fix or it's my lucky day 🪄 😄

Oh, that's good to know.
