### ISSUE TITLE
[Bug]: AttributeError: 'CachedPreTrainedTokenizerFast' object has no attribute 'default_chat_template'. Did you mean: 'get_chat_template'?

### ISSUE THREAD

**Issue by ziyang-arch** [vllm-project/vllm#11271]
### Your current environment

<details>
I installed vllm 0.6.4 in conda environment, but when I run `python collect_env.py` it gives me
<summary>The output of `python collect_env.py`</summary>

```text
ModuleNotFoundError: No module named 'vllm._C'
```

</details>

### 🐛 Describe the bug

when i run `python benchmarks/benchmark_serving.py --backend vllm --model meta-llama/Meta-Llama-3-70B --dataset-name sonnet --dataset-path benchmarks/sonnet.txt --num-prompts 2`, 
it gives me
```
AttributeError: 'CachedPreTrainedTokenizerFast' object has no attribute 'default_chat_template'. Did you mean: 'get_chat_template'?
```
So I tried to check the environment with `python collect_env.py`, then I got vllm is not complete.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ziyang-arch** [comment]
I found when I try to import vllm when there is vllm repo cloned in my directory it will show error 
```
ModuleNotFoundError: No module named 'vllm._C'
```
but when I remove the vllm repository, I can import vllm and run `python collect_env.py` and that's the results
```
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.102.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4
GPU 5: Tesla T4
GPU 6: Tesla T4
GPU 7: Tesla T4

Nvidia driver version: 545.23.06
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.7.6.5
/usr/lib64/libcudnn.so.8.9.6
/usr/lib64/libcudnn_adv_infer.so.8.9.6
/usr/lib64/libcudnn_adv_train.so.8.9.6
/usr/lib64/libcudnn_cnn_infer.so.8.9.6
/usr/lib64/libcudnn_cnn_train.so.8.9.6
/usr/lib64/libcudnn_ops_infer.so.8.9.6
/usr/lib64/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
Stepping:              7
CPU MHz:               2100.000
CPU max MHz:           3200.0000
CPU min MHz:           800.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-15,32-47
NUMA node1 CPU(s):     16-31,48-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-ml-py==12.560.30
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.46.3
[pip3] triton==3.1.0
[conda] blas                      1.0                         mkl  
[conda] cuda-cudart               12.1.105                      0    nvidia
[conda] cuda-cupti                12.1.105                      0    nvidia
[conda] cuda-libraries            12.1.0                        0    nvidia
[conda] cuda-nvrtc                12.1.105                      0    nvidia
[conda] cuda-nvtx                 12.1.105                      0    nvidia
[conda] cuda-opencl               12.6.77                       0    nvidia
[conda] cuda-runtime              12.1.0                        0    nvidia
[conda] cuda-version              12.6                          3    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libcublas                 12.1.0.26                     0    nvidia
[conda] libcufft                  11.0.2.4                      0    nvidia
[conda] libcufile                 1.11.1.6                      0    nvidia
[conda] libcurand                 10.3.7.77                     0    nvidia
[conda] libcusolver               11.4.4.55                     0    nvidia
[conda] libcusparse               12.0.2.55                     0    nvidia
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] libnpp                    12.0.2.50                     0    nvidia
[conda] libnvjitlink              12.1.105                      0    nvidia
[conda] libnvjpeg                 12.1.1.14                     0    nvidia
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.11          py310h5eee18b_0  
[conda] mkl_random                1.2.8           py310h1128e8f_0  
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] numpy-base                2.0.1           py310hb5e798b_1  
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] pytorch                   2.5.1           py3.10_cuda12.1_cudnn9.1.0_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_6    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torchaudio                2.5.1               py310_cu121    pytorch
[conda] torchtriton               3.1.0                     py310    pytorch
[conda] torchvision               0.20.1              py310_cu121    pytorch
[conda] transformers              4.46.3                   pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     SYS     SYS     SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU1    PIX      X      SYS     SYS     SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU2    SYS     SYS      X      PIX     SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU3    SYS     SYS     PIX      X      SYS     SYS     SYS     SYS     0-15,32-47      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      PIX     SYS     SYS     16-31,48-63     1               N/A
GPU5    SYS     SYS     SYS     SYS     PIX      X      SYS     SYS     16-31,48-63     1               N/A
GPU6    SYS     SYS     SYS     SYS     SYS     SYS      X      PIX     16-31,48-63     1               N/A
GPU7    SYS     SYS     SYS     SYS     SYS     SYS     PIX      X      16-31,48-63     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

CUDA_HOME=/usr/local/cuda-12.3
CUDA_HOME=/usr/local/cuda-12.3
LD_LIBRARY_PATH=/data3/zjia016/Miniconda/envs/vllm_inf/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/lib64:
TORCH_HUB=/data3/zjia016/.cache/torch_hub
TORCH_EXTENSIONS_DIR=/data3/zjia016/.cache/torch_extensions
TORCH_HOME=/data3/zjia016/.cache/torch
CUDA_MODULE_LOADING=LAZY

```

**Comment by DarkLight1337** [comment]
How did you install vLLM? Can you show the commands used?

**Comment by ziyang-arch** [comment]
I installed with `pip install vllm`. Then according to #1814, I cannot clone the vllm project if I want to use the vllm installed with pip. 
So I tried to build the vllm from source with `pip install -e .`, but then it gives me 
```

Obtaining file:///data3/***/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/data3/***/Miniconda/envs/vllm_src/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data3/***/Miniconda/envs/vllm_src/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data3/***/Miniconda/envs/vllm_src/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-8w5e3dbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-8w5e3dbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-8w5e3dbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8w5e3dbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "/tmp/pip-build-env-8w5e3dbn/overlay/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-8w5e3dbn/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: symbol __nvJitLinkComplete_12_4, version libnvJitLink.so.12 not defined in file libnvJitLink.so.12 with link time reference
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by DarkLight1337** [comment]
@dtrifiro can you look into this?

**Comment by Yang-x-Zhao** [comment]
Similar issue here when I was benchmarking Meta Llama 3.1 8B. But with Meta Llama 3.1 8B Instruct, I have no issue, so maybe this is a error only in non-instruct model?

**Comment by NickLucche** [comment]
Hey, have you double-checked that you set the cuda env vars correctly? `CUDA_HOME=/usr/local/cuda PATH="${CUDA_HOME}/bin:$PATH" pip install -v -e .`

**Comment by dtrifiro** [comment]
@ziyang-arch If you don't need to rebuild the cuda kernels, can you try with `VLLM_USE_PRECOMPILED=1 pip install -e .` ?

**Comment by ziyang-arch** [comment]
Hi @NickLucche and @dtrifiro , thank you for the suggestion, I tried both install commands and see the same error.

**Comment by Yang-x-Zhao** [comment]
I think the issue is that benchmark_serving.py use `tokenizer.chat_template` when using sonnet as input. However, the foundation model does not have a `chat_template`, so error occur. Try to use `Instruct` model or remove the `chat-template` check will help.

**Comment by dtrifiro** [comment]
Can you try this in a fresh virtualenv?

```bash

python -m venv .venv
source .venv/bin/activate

pip install uv
uv pip install -r requirements-build.txt -r requirements-cuda.txt
pip install --no-build-isolation --editable . 
```

**Comment by ziyang-arch** [comment]
Thank you for the reply! 
Hi, @Yang-x-Zhao, I tried the `Instruct` models and I can start the server successfully, and when I run the client it gives me 
```
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.
```
The dataset `sonet` and `ShareGPT_V3_unfiltered_cleaned_split.json` both show this error. May I know which dataset you are using? Thanks.

**Comment by ziyang-arch** [comment]
Thanks @dtrifiro, when I run the `uv pip install -r requirements-build.txt -r requirements-cuda.txt`, it gives me
```
 × No solution found when resolving dependencies:
   Because only the following versions of xgrammar{platform_machine == 'x86_64'} are available:
          xgrammar{platform_machine == 'x86_64'}<=0.1.6
          xgrammar{platform_machine == 'x86_64'}==0.1.7
          xgrammar{platform_machine == 'x86_64'}==0.1.8
      and xgrammar{platform_machine == 'x86_64'}>=0.1.6 has no wheels with a matching platform tag, we can conclude that xgrammar{platform_machine == 'x86_64'}>=0.1.6 cannot be used.
      And because you require xgrammar{platform_machine == 'x86_64'}>=0.1.6, we can conclude that your requirements are unsatisfiable.
```
Th

**Comment by dtrifiro** [comment]
@ziyang-arch I recommend updating to python>=3.12, we're testing vLLM on 3.12. The error your're seeing probably means that `xgrammar` does not have a wheel available for 3.10.
