### ISSUE TITLE
[Usage]: How to serve my custom model?

### ISSUE THREAD

**Issue by zhaocaibei123** [vllm-project/vllm#11282]
### How would you like to use vllm

I have a custom model, and here is my serve code:

```
from vllm import ModelRegistry
from transformers import AutoConfig
from qwen2_rvs_fast import Qwen2TransConfig, Qwen2TransForCausalLM

AutoConfig.register("qwen2trans", Qwen2TransConfig)
ModelRegistry.register_model("Qwen2TransForCausalLM", Qwen2TransForCausalLM)

import runpy
runpy.run_module('vllm.entrypoints.openai.api_server', run_name='__main__')
```

When I run `python my_serve.py --model my_model_path` I got this:
INFO 12-18 12:08:19 api_server.py:175] Multiprocessing frontend to use ipc:///tmp/bb074f99-9633-4cf0-a3e2-3043001a3c67 for IPC Path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/zhaocaibei/git/rvs_fast/rvs_fast_models/vllm/serve.py", line 10, in <module>
    runpy.run_module('vllm.entrypoints.openai.api_server', run_name='__main__')
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 643, in <module>
    uvloop.run(run_server(args))
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 609, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 113, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 191, in build_async_engine_client_from_engine_args
    engine_process.start()
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/data/zhaocaibei/git/rvs_fast/rvs_fast_models/vllm/serve.py", line 10, in <module>
    runpy.run_module('vllm.entrypoints.openai.api_server', run_name='__main__')
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 643, in <module>
    uvloop.run(run_server(args))
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 609, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 113, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/data/zhaocaibei/setup/anaconda3/envs/sf_llm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 210, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.

So how should I serve my model?
Others: `vllm serve Qwen/Qwen2.5-7B-Instruct` can work correctly.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should create a plugin and register your model inside the plugin, as outlined [here](https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration).

**Comment by zhaocaibei123** [comment]
> You should create a plugin and register your model inside the plugin, as outlined [here](https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration).

I have registered referencing your link, but got an error. There's something wrong with multiprocessing?

**Comment by DarkLight1337** [comment]
How did you setup your plugin? It should be something like [`tests/plugins/vllm_add_dummy_model`](https://github.com/vllm-project/vllm/tree/main/tests/plugins/vllm_add_dummy_model)

**Comment by zhaocaibei123** [comment]
![image](https://github.com/user-attachments/assets/4a2e3b51-f83e-4c5a-9a85-88bbc91640ee)

**Comment by zhaocaibei123** [comment]
https://docs.vllm.ai/en/v0.6.3/models/adding_model.html
![image](https://github.com/user-attachments/assets/761d5075-ab92-41de-b5ca-7e9d870beece)
I wrote code following this doc.

**Comment by DarkLight1337** [comment]
> https://docs.vllm.ai/en/v0.6.3/models/adding_model.html ![image](https://private-user-images.githubusercontent.com/48509226/396779815-761d5075-ab92-41de-b5ca-7e9d870beece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDI4OTIsIm5iZiI6MTczNDUwMjU5MiwicGF0aCI6Ii80ODUwOTIyNi8zOTY3Nzk4MTUtNzYxZDUwNzUtYWI5Mi00MWRlLWI1Y2EtN2U5ZDg3MGJlZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA2MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOWRhMTMyMTlmNTBmZDA1NGNlMGZmZThhOWY4ZWFlODc5OGRiOGY4MzU1ZDJkN2RjZjFjZmYyMjRlODM2NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-syCm8v3xVHfvwBjE1_FOz_Uc6EUtYGjXd_SP2KKIUg) I wrote code following this doc. my vllm version: 0.6.4.post1

This doc is for v0.6.3. You should use the newer version.

**Comment by zhaocaibei123** [comment]
> How did you setup your plugin? It should be something like [`tests/plugins/vllm_add_dummy_model`](https://github.com/vllm-project/vllm/tree/main/tests/plugins/vllm_add_dummy_model)

It works! Thank you! I think it's better to update the doc : )

**Comment by DarkLight1337** [comment]
We have already updated the doc, you just have to browse the latest version of it.

**Comment by zhaocaibei123** [comment]
![image](https://github.com/user-attachments/assets/8b34b2f3-34a5-4f8d-b838-b118d8848f71)
I got error above. And this doc doesn't mention setup plugin?

**Comment by DarkLight1337** [comment]
It is in the latest version: https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration

**Comment by DarkLight1337** [comment]
We can't retroactively update older docs since that would break the version semantics.

**Comment by zhaocaibei123** [comment]
> It is in the latest version: https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration

This doc doesn't mention how to run api server with `vllm serve` and the plugin. I think someone may meet the same question as me.

**Comment by DarkLight1337** [comment]
The plugin is loaded automatically, so you just have to install your plugin via `pip install`. I agree that the docs can use some more work though. cc @youkaichao

**Comment by zhaocaibei123** [comment]
Got it! Thank you : )
