### ISSUE TITLE
[Bug]: [RuntimeError: CUDA error: unspecified launch failure  ]int8 w8a8 quantization data set to generate model data, an error occurred when changing the specified data set

### ISSUE THREAD

**Issue by bunengshuo1** [vllm-project/vllm#11281]
### Your current environment

PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA L40S
GPU 1: NVIDIA L40S
GPU 2: NVIDIA L40S
GPU 3: NVIDIA L40S
GPU 4: NVIDIA L40S
GPU 5: NVIDIA L40S
GPU 6: NVIDIA L40S
GPU 7: NVIDIA L40S

Nvidia driver version: 550.54.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       GenuineIntel
BIOS Vendor ID:                  Intel(R) Corporation
Model name:                      Intel(R) Xeon(R) Platinum 8468V
BIOS Model name:                 Intel(R) Xeon(R) Platinum 8468V
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
Stepping:                        8
CPU max MHz:                     3800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4800.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_pt cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq cldemote movdiri movdir64b md_clear pconfig spec_ctrl intel_stibp flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       4.5 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        192 MiB (96 instances)
L3 cache:                        195 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-47,96-143
NUMA node1 CPU(s):               48-95,144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; Load fences, usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-modelopt==0.15.1
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] onnx==1.16.2
[pip3] optree==0.11.0
[pip3] pynvml==11.5.3
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.45.2
[pip3] triton==3.1.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     PXB     0-47,96-143     0               N/A
GPU1    PIX      X      PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     PXB     0-47,96-143     0               N/A
GPU2    PXB     PXB      X      PXB     SYS     SYS     SYS     SYS     SYS     SYS     PXB     0-47,96-143     0               N/A
GPU3    PXB     PXB     PXB      X      SYS     SYS     SYS     SYS     SYS     SYS     PIX     0-47,96-143     0               N/A
GPU4    SYS     SYS     SYS     SYS      X      PIX     PXB     PXB     PXB     PXB     SYS     48-95,144-191   1               N/A
GPU5    SYS     SYS     SYS     SYS     PIX      X      PXB     PXB     PXB     PXB     SYS     48-95,144-191   1               N/A
GPU6    SYS     SYS     SYS     SYS     PXB     PXB      X      PXB     PXB     PXB     SYS     48-95,144-191   1               N/A
GPU7    SYS     SYS     SYS     SYS     PXB     PXB     PXB      X      PIX     PIX     SYS     48-95,144-191   1               N/A
NIC0    SYS     SYS     SYS     SYS     PXB     PXB     PXB     PIX      X      PIX     SYS
NIC1    SYS     SYS     SYS     SYS     PXB     PXB     PXB     PIX     PIX      X      SYS
NIC2    PXB     PXB     PXB     PIX     SYS     SYS     SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_2
  NIC1: mlx5_3
  NIC2: mlx5_bond_0

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=12.4 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526 brand=tesla,driver>=535,driver<536 brand=unknown,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=geforce,driver>=535,driver<536 brand=geforcertx,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=titan,driver>=535,driver<536 brand=titanrtx,driver>=535,driver<536
NCCL_VERSION=2.21.5-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
CUDA_VERSION=12.4.1
LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
CUDA_MODULE_LOADING=LAZY

### 🐛 Describe the bug

Refer to the official documentation ”[https://docs.vllm.ai/en/latest/quantization/int8.html“](https://docs.vllm.ai/en/latest/quantization/int8.html%E2%80%9C), perform int8 w8a8 quantization and change the calibration data set to mit-han-lab/pile-val-backup for weight conversion, and an error occurs

code：
# Load and preprocess the dataset                                                                                                                                                   
 15 ds = load_dataset("mit-han-lab/pile-val-backup",split="validation")                                                                                                                 
 16 ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))                                                                                                                     
 17 def preprocess(example):                                                                                                                                                           
 18     return {"Texta": tokenizer.apply_chat_template(example["text"], tokenize=False)}                                                                                                
 19 ds = ds.map(preprocess)                                                                                                                                                            
 20                                                                                                                                                                                     
 21 def tokenize(sample):                                                                                                                                                               
 22     return tokenizer(sample["Texta"], padding=False, max_length=MAX_SEQUENCE_LENGTH, truncation=True, add_special_tokens=False)                                                      
 23 ds = ds.map(tokenize, remove_columns=ds.column_names)                                                                                                                               
 24 from llmcompressor.transformers import oneshot                                                                                                                                      
 25 from llmcompressor.modifiers.quantization import GPTQModifier                                                                                                                       
 26 from llmcompressor.modifiers.smoothquant import SmoothQuantModifier                                                                                                                 
 27                                                                                                                                                                                     
 28 # Configure the quantization algorithms                                                                                                                                             
 29 recipe = [                                                                                                                                                                          
 30     SmoothQuantModifier(smoothing_strength=0.5),                                                                                                                                    
 31     GPTQModifier(targets="Linear", scheme="W8A8", ignore=["lm_head"]),                                                                                                              
 32 ]                                                                                                                                                                                   
 33                                                                                                                                                                                     
 34 # Apply quantization                                                                                                                                                                
 35 oneshot(                                                                                                                                                                            
 36         model=model,                                                                                                                                                                
 37         dataset=ds,                                                                                                                                                                 
 38         recipe=recipe,                                                                                                                                                              
 39         max_seq_length=MAX_SEQUENCE_LENGTH,                                                                                                                                         
 40         num_calibration_samples=NUM_CALIBRATION_SAMPLES,                                                                                                                            
 41 )                                                                                                                                                                                   
 42                                                                                                                                                                                     
 43 # Save the compressed model                                                                                                                                                         
 44 SAVE_DIR = MODEL_ID.split("/")[1] + "-W8A8-Dynamic-Per-Token"                                                                                                                       
 45 model.save_pretrained(SAVE_DIR, save_compressed=True)                                                                                                                               
 46 tokenizer.save_pretrained(SAVE_DIR)           

error results：
024-12-16T09:44:59.912924+0000 | _calibrate | INFO - Running SmoothQuantModifier calibration with 128 samples...                                                                       
  0%|                                                                                                                                                           | 0/128 [00:00
Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)                                                
  9%|█████████████▋                                                                                                                                    | 12/128 [00:08<01:23,  1.39it/s]
Traceback (most recent call last):                                                                                                                                                      
  File "/data/weight_transpose/run2.py", line 35, in                                                                                                                            
    oneshot(                                                                                                                                                                            
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/text_generation.py", line 76, in oneshot                                                            
    main(model_args, data_args, training_args)                                                                                                                                          
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/text_generation.py", line 364, in main                                                              
    stage_runner.one_shot()                                                                                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/runner.py", line 171, in one_shot                                                                   
    self.trainer.one_shot(calibration_data=calib_data, stage=stage)                                                                                                                     
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/session_mixin.py", line 401, in one_shot                                                            
    apply(                                                                                                                                                                              
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/core/session_functions.py", line 184, in apply                                                                            
    return active_session().apply(                                                                                                                                                      
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/core/session.py", line 210, in apply                                                                                      
    self.initialize(**kwargs)                                                                                                                                                           
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/core/session.py", line 156, in initialize                                                                                 
    mod_data = self._lifecycle.initialize(                                                                                                                                              
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/core/lifecycle.py", line 126, in initialize                                                                               
    data = mod.initialize(state=self.state, **extras)                                                                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/modifiers/stage.py", line 124, in initialize                                                                              
    modifier.initialize(state, **kwargs)                                                                                                                                                
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/modifiers/modifier.py", line 118, in initialize                                                                           
    initialized = self.on_initialize(state=state, **kwargs)                                                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/modifiers/smoothquant/base.py", line 134, in on_initialize                                                                
    self._calibrate(state.model, calibration_dataloader)                                                                                                                                
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context                                                                              
    return func(*args, **kwargs)                                                                                                                                                        
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/modifiers/smoothquant/base.py", line 250, in _calibrate                                                                   
    run_calibration_forward(                                                                                                                                                            
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/modifiers/utils/pytorch_helpers.py", line 105, in run_calibration_forward                                                 
    torch.cuda.empty_cache()                                                                                                                                                            
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py", line 192, in empty_cache                                                                                         
    torch._C._cuda_emptyCache()                                                                                                                                                         
RuntimeError: CUDA error: unspecified launch failure                                                                                                                                    
Compile with `TORCH_USE_CUDA_DSA` to enable device-sid

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by bunengshuo1** [comment]
Refer to the official documentation ”https://docs.vllm.ai/en/latest/quantization/int8.html“, perform int8 w8a8 quantization and change the calibration data set to mit-han-lab/pile-val-backup for weight conversion, and an error occurs

**Comment by siddartha-RE** [comment]
I am hitting the same issue when I test different calibration data. I have checked the samples and it is not because one of them is longer. However, with a given dataset it seems to fail repeatably at the same record. Memory usage seems very reasonable throughout.
