### ISSUE TITLE
[Bug]: Multi-Node CPU Inference on MacOS calling `intel_extension_for_pytorch` 

### ISSUE THREAD

**Issue by MoSedkyy** [vllm-project/vllm#11342]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

While attempting to execute `NCCL_DEBUG=TRACE docker run -it --rm -p 8000:8000 --shm-size=4g --env "HUGGING_FACE_HUB_TOKEN=<token>" --env "VLLM_CPU_KVCACHE_SPACE=40" --privileged -e NCCL_IB_HCA=mlx5 vllm-cpu-env-latest --device="cpu" --disable_async_output_proc --enforce-eager --model=meta-llama/Llama-Guard-3-1B --dtype=float16 --tensor-parallel-size 16 --pipeline-parallel-size 2 --distributed-executor-backend="ray" --swap-space=1` for Multi-Node inference; It raise an error in `/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py` in `line 338` as it needs `intel_extension_for_pytorch` Module. 

The error disappeared after commenting lines 338 and 339, would be great for a quick fixing. 

Moreover, just want to confirm that Ray is supported for CPU Inference on Multi-Node as described in [documentation](https://docs.vllm.ai/en/latest/serving/distributed_serving.html#details-for-distributed-inference-and-serving)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ruisearch42** [comment]
Hi @MoSedkyy , can you post the full stack trace for the error?

**Comment by varad-ahirwadkar** [comment]
Hi, 
I am facing the same issue while trying to set `--tensor-parallel-size` more than 1 on `ppc64le` machine. 

logs:
```
# vllm serve meta-llama/Meta-Llama-3.1-8B-Instruct  --tensor-parallel-size 2 --max-model-len 2048

INFO 01-16 09:13:50 api_server.py:712] vLLM API server version 0.6.6.post2.dev29+g6036d4db.d20250103
INFO 01-16 09:13:50 api_server.py:713] args: Namespace(subparser='serve', model_tag='meta-llama/Meta-Llama-3.1-8B-Instruct', config='', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='meta-llama/Meta-Llama-3.1-8B-Instruct', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=2048, guided_decoding_backend='xgrammar', logits_processor_pattern=None, distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7ff799f74ea0>)
INFO 01-16 09:13:50 api_server.py:199] Started engine process with PID 361
INFO 01-16 09:14:02 config.py:516] This model supports multiple tasks: {'embed', 'classify', 'reward', 'score', 'generate'}. Defaulting to 'generate'.
INFO 01-16 09:14:02 config.py:1316] Defaulting to use mp for distributed inference
WARNING 01-16 09:14:02 config.py:648] Async output processing is not supported on the current platform type cpu.
WARNING 01-16 09:14:02 cpu.py:56] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 01-16 09:14:02 cpu.py:71] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
INFO 01-16 09:14:06 config.py:516] This model supports multiple tasks: {'score', 'generate', 'embed', 'reward', 'classify'}. Defaulting to 'generate'.
INFO 01-16 09:14:06 config.py:1316] Defaulting to use mp for distributed inference
WARNING 01-16 09:14:06 config.py:648] Async output processing is not supported on the current platform type cpu.
WARNING 01-16 09:14:06 cpu.py:56] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 01-16 09:14:06 cpu.py:71] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
INFO 01-16 09:14:06 importing.py:14] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 01-16 09:14:06 llm_engine.py:234] Initializing an LLM engine (v0.6.6.post2.dev29+g6036d4db.d20250103) with config: model='meta-llama/Meta-Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=meta-llama/Meta-Llama-3.1-8B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"candidate_compile_sizes":[],"compile_sizes":[],"capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
INFO 01-16 09:14:07 cpu.py:33] Cannot use _Backend.FLASH_ATTN backend on CPU.
INFO 01-16 09:14:07 selector.py:141] Using Torch SDPA backend.
(VllmWorkerProcess pid=386) WARNING 01-16 09:14:07 registry.py:270] `mm_limits` has already been set for model=meta-llama/Meta-Llama-3.1-8B-Instruct, and will be overwritten by the new values.
(VllmWorkerProcess pid=386) INFO 01-16 09:14:07 multiproc_worker_utils.py:220] Worker ready; awaiting tasks
INFO 01-16 09:14:07 shm_broadcast.py:255] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_fec3c65f'), local_subscribe_port=41913, remote_subscribe_port=None)
INFO 01-16 09:14:08 weight_utils.py:251] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=386) INFO 01-16 09:14:08 weight_utils.py:251] Using model weights format ['*.safetensors']
INFO 01-16 09:14:09 cpu_executor.py:186] # CPU blocks: 4096
INFO 01-16 09:14:09 llm_engine.py:431] init engine (profile, create kv cache, warmup model) took 0.19 seconds
INFO 01-16 09:14:09 api_server.py:640] Using supplied chat template:
INFO 01-16 09:14:09 api_server.py:640] None
INFO 01-16 09:14:09 launcher.py:19] Available routes are:
INFO 01-16 09:14:09 launcher.py:27] Route: /openapi.json, Methods: GET, HEAD
INFO 01-16 09:14:09 launcher.py:27] Route: /docs, Methods: GET, HEAD
INFO 01-16 09:14:09 launcher.py:27] Route: /docs/oauth2-redirect, Methods: GET, HEAD
INFO 01-16 09:14:09 launcher.py:27] Route: /redoc, Methods: GET, HEAD
INFO 01-16 09:14:09 launcher.py:27] Route: /health, Methods: GET
INFO 01-16 09:14:09 launcher.py:27] Route: /tokenize, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /detokenize, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /v1/models, Methods: GET
INFO 01-16 09:14:09 launcher.py:27] Route: /version, Methods: GET
INFO 01-16 09:14:09 launcher.py:27] Route: /v1/chat/completions, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /v1/completions, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /v1/embeddings, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /pooling, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /score, Methods: POST
INFO 01-16 09:14:09 launcher.py:27] Route: /v1/score, Methods: POST
INFO 01-16 09:14:12 logger.py:37] Received request cmpl-c9781df2331a4a7e8dcd2f589bc4be89-0: prompt: 'San Francisco is a', params: SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=7, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None), prompt_token_ids: [128000, 24661, 13175, 374, 264], lora_request: None, prompt_adapter_request: None.
INFO 01-16 09:14:12 engine.py:267] Added request cmpl-c9781df2331a4a7e8dcd2f589bc4be89-0.
CRITICAL 01-16 09:14:13 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:55778 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR 01-16 09:14:13 engine.py:135] ModuleNotFoundError("No module named 'intel_extension_for_pytorch'")
ERROR 01-16 09:14:13 engine.py:135] Traceback (most recent call last):
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/engine/multiprocessing/engine.py", line 133, in start
ERROR 01-16 09:14:13 engine.py:135]     self.run_engine_loop()
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/engine/multiprocessing/engine.py", line 196, in run_engine_loop
ERROR 01-16 09:14:13 engine.py:135]     request_outputs = self.engine_step()
ERROR 01-16 09:14:13 engine.py:135]                       ^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/engine/multiprocessing/engine.py", line 214, in engine_step
ERROR 01-16 09:14:13 engine.py:135]     raise e
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/engine/multiprocessing/engine.py", line 205, in engine_step
ERROR 01-16 09:14:13 engine.py:135]     return self.engine.step()
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/engine/llm_engine.py", line 1394, in step
ERROR 01-16 09:14:13 engine.py:135]     outputs = self.model_executor.execute_model(
ERROR 01-16 09:14:13 engine.py:135]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/executor/cpu_executor.py", line 201, in execute_model
ERROR 01-16 09:14:13 engine.py:135]     output = self.driver_method_invoker(self.driver_worker,
ERROR 01-16 09:14:13 engine.py:135]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/executor/cpu_executor.py", line 298, in _driver_method_invoker
ERROR 01-16 09:14:13 engine.py:135]     return getattr(driver, method)(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/worker/worker_base.py", line 343, in execute_model
ERROR 01-16 09:14:13 engine.py:135]     output = self.model_runner.execute_model(
ERROR 01-16 09:14:13 engine.py:135]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 01-16 09:14:13 engine.py:135]     return func(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/worker/cpu_model_runner.py", line 530, in execute_model
ERROR 01-16 09:14:13 engine.py:135]     hidden_states = model_executable(
ERROR 01-16 09:14:13 engine.py:135]                     ^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-16 09:14:13 engine.py:135]     return self._call_impl(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-16 09:14:13 engine.py:135]     return forward_call(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/model_executor/models/llama.py", line 568, in forward
ERROR 01-16 09:14:13 engine.py:135]     model_output = self.model(input_ids, positions, kv_caches,
ERROR 01-16 09:14:13 engine.py:135]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/compilation/decorators.py", line 168, in __call__
ERROR 01-16 09:14:13 engine.py:135]     return self.forward(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/model_executor/models/llama.py", line 351, in forward
ERROR 01-16 09:14:13 engine.py:135]     hidden_states = self.get_input_embeddings(input_ids)
ERROR 01-16 09:14:13 engine.py:135]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/model_executor/models/llama.py", line 336, in get_input_embeddings
ERROR 01-16 09:14:13 engine.py:135]     return self.embed_tokens(input_ids)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-16 09:14:13 engine.py:135]     return self._call_impl(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-16 09:14:13 engine.py:135]     return forward_call(*args, **kwargs)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/model_executor/layers/vocab_parallel_embedding.py", line 419, in forward
ERROR 01-16 09:14:13 engine.py:135]     output = tensor_model_parallel_all_reduce(output_parallel)
ERROR 01-16 09:14:13 engine.py:135]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/distributed/communication_op.py", line 11, in tensor_model_parallel_all_reduce
ERROR 01-16 09:14:13 engine.py:135]     return get_tp_group().all_reduce(input_)
ERROR 01-16 09:14:13 engine.py:135]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 01-16 09:14:13 engine.py:135]   File "/opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg/vllm/distributed/parallel_state.py", line 338, in all_reduce
ERROR 01-16 09:14:13 engine.py:135]     import intel_extension_for_pytorch as ipex
ERROR 01-16 09:14:13 engine.py:135] ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
INFO 01-16 09:14:13 multiproc_worker_utils.py:125] Killing local vLLM worker processes
```

**Comment by ruisearch42** [comment]
Hi @varad-ahirwadkar @MoSedkyy , have you pip installed intel_extension_for_pytorch?

**Comment by varad-ahirwadkar** [comment]
> Hi [@varad-ahirwadkar](https://github.com/varad-ahirwadkar) [@MoSedkyy](https://github.com/MoSedkyy) , have you pip installed intel_extension_for_pytorch?

Hi @ruisearch42,  
Unable to install it on `ppc64le`.
```
# pip install intel_extension_for_pytorch
DEPRECATION: Loading egg at /opt/conda/lib/python3.11/site-packages/vllm-0.6.6.post2.dev29+g6036d4db.d20250103.cpu-py3.11-linux-ppc64le.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
ERROR: Could not find a version that satisfies the requirement intel_extension_for_pytorch (from versions: none)
ERROR: No matching distribution found for intel_extension_for_pytorch
```

**Comment by MoSedkyy** [comment]
@ruisearch42 No I am using MacOs with CPU Inference. I am using [Dockerfile.arm](https://docs.vllm.ai/en/latest/getting_started/installation/cpu/index.html) image for installation , it shouldn't call `intel_extension_for_pytorch` at all
