### ISSUE TITLE
[Bug]: vllm 0.6.3.post1 crash when deploy qwen2vl 72b 

### ISSUE THREAD

**Issue by xxlight** [vllm-project/vllm#11356]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

```
python -m vllm.entrypoints.openai.api_server --model "path_to_qwen2_vl_72b_instruct" \
                                            --tensor-parallel-size 8 \
                                            --max-model-len 32768 \
```
```
from openai import OpenAI
from vllm.assets.image import ImageAsset
import os
import base64

openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)

models = client.models.list()
model = models.data[0].id
question="What is the text in the illustrate?"
image_path = "path_to_image"
with open(image_path, "rb") as file:
    image_base64 = base64.b64encode(file.read()).decode('utf-8')

stream = True
response = client.chat.completions.create(
    model=model,
    messages=[{
        'role': 'user',
        'content': [{
            'type': 'text',
            'text': question,
        }, {
            'type': 'image_url',
            'image_url': {
                'url': f"data:image/jpeg;base64,{image_base64}",,
            },
        }],
    }],
    temperature=0.1,
    top_p=0.001,
    stream = stream,
)

if stream:
    for iter in response:
        print(iter.choices[0].delta.content, end = "", flush=True)
    print("")
else:
    print(response.choices[0].message.content)
```

launch server success, but while send a request, vllm server crash, I have tried increasing CUDA_VISIBLE_DEVICES, export VLLM_RPC_TIMEOUT=10000000, but it don't work,the image size is 500*500

(VllmWorkerProcess pid=162247) WARNING 12-18 17:55:29 shm_broadcast.py:396] No available block found in 60 second. 
ERROR 12-13 11:09:50 client.py:250] RuntimeError('Engine loop has died')
ERROR 12-13 11:09:50 client.py:250] Traceback (most recent call last):
ERROR 12-13 11:09:50 client.py:250]   File "/usr/local/lib/python3.10/site-packages/vllm/engine/multiprocessing/client.py", line 150, in run_heartbeat_loop
ERROR 12-13 11:09:50 client.py:250]     await self._check_success(
ERROR 12-13 11:09:50 client.py:250]   File "/usr/local/lib/python3.10/site-packages/vllm/engine/multiprocessing/client.py", line 314, in _check_success
ERROR 12-13 11:09:50 client.py:250]     raise response
ERROR 12-13 11:09:50 client.py:250] RuntimeError: Engine loop has died
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 568, in receive
    await self.message_event.wait()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f7b70b2b190

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 258, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
    raise BaseExceptionGroup(
exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by CodeFrontWang** [comment]
Same problem

**Comment by DarkLight1337** [comment]
My first guess would be that there is something wrong with your distributed GPU setup (e.g. NCCL). Can you show the results of `collect_env.py`? cc @youkaichao

**Comment by youkaichao** [comment]
I don't see enough information from the issue :(

**Comment by xxlight** [comment]
Solved this problem by using --disable-custom-all-reduce
