### ISSUE TITLE
[Usage]: how to use prefill-decode disaggregation ??

### ISSUE THREAD

**Issue by chenchunhui97** [vllm-project/vllm#11490]
### Your current environment

vllm official images: v0.6.5
device: RTX4090
cuda driver: 550.78
cuda toolkit: 12.4

### How would you like to use vllm

I  want to know how to use prefilling-decoding disaggregation, i use it in the following command but failed:

```shell
# prefilling instance
docker run --runtime nvidia --rm -itd --gpus '"device=3"'  -v /storage/nfs2/ModelHub/QwenLM/Qwen2.5:/models -p 24050:24050 --ipc=host --name pds-prefill vllm/vllm-openai:v0.6.5 --model /models/Qwen2.5-1.5B-Instruct --port 24050  --max-model-len 100 --gpu-memory-utilization 0.8 --kv-transfer-config '{"kv_connector":"PyNcclConnector","kv_role":"kv_producer","kv_rank":0,"kv_parallel_size":2,"kv_ip":"127.0.0.1", "kv_port":24050}'
```

```shell
# decoding instance
docker run --runtime nvidia --rm -itd --gpus '"device=4"'  -v /storage/nfs2/ModelHub/QwenLM/Qwen2.5:/models -p 24051:24051 --ipc=host --name pds-decode vllm/vllm-openai:v0.6.5 --model /models/Qwen2.5-1.5B-Instruct --port 24051 --max-model-len 100 --gpu-memory-utilization 0.8 --kv-transfer-config  '{"kv_connector":"PyNcclConnector","kv_role":"kv_producer","kv_rank":0,"kv_parallel_size":2,"kv_ip":"127.0.0.1","kv_port":24051}' 
```

then I  run the `python3 ../benchmarks/disagg_benchmarks/disagg_prefill_proxy_server.py` after modified the port. 

but the model deployment failed, so I want to inquire the command of PD-disaggregation.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by chenchunhui97** [comment]
docker logs:
![image](https://github.com/user-attachments/assets/77784dad-cbb3-4ebe-b7b1-12353c6db0c5)

**Comment by chenchunhui97** [comment]
@zhouyuan could you please help me to fix this bug?

**Comment by forearrow** [comment]
+1

**Comment by surajssd** [comment]
Fails for me in the same way as well:

```bash
# export MODEL="microsoft/Phi-4-mini-instruct"
CUDA_VISIBLE_DEVICES=0 python3 \
    -m vllm.entrypoints.openai.api_server \
    --model $MODEL \
    --port 8100 \
    --max-model-len 8192 \
    --gpu-memory-utilization 0.6 \
    --kv-transfer-config \
    '{"kv_connector":"PyNcclConnector","kv_role":"kv_producer","kv_rank":0,"kv_parallel_size":2,"kv_buffer_size":5e9}' &
[1] 846
root@phi4-mini-6bdff6b448-lflt7:/vllm-workspace# INFO 06-02 14:09:55 [__init__.py:243] Automatically detected platform cuda.
INFO 06-02 14:09:57 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 06-02 14:09:57 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 06-02 14:09:57 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 06-02 14:09:57 [api_server.py:1289] vLLM API server version 0.9.0
INFO 06-02 14:09:58 [cli_args.py:300] non-default args: {'port': 8100, 'model': 'microsoft/Phi-4-mini-instruct', 'max_model_len': 8192, 'gpu_memory_utilization': 0.6, 'kv_transfer_config': KVTransferConfig(kv_connector='PyNcclConnector', engine_id='f76a2a7b-bf2b-47a4-ad76-14d15b3e6f52', kv_buffer_device='cuda', kv_buffer_size=5000000000.0, kv_role='kv_producer', kv_rank=0, kv_parallel_size=2, kv_ip='127.0.0.1', kv_port=14579, kv_connector_extra_config={}, kv_connector_module_path=None)}
INFO 06-02 14:09:58 [config.py:213] Replacing legacy 'type' key with 'rope_type'
INFO 06-02 14:10:05 [config.py:793] This model supports multiple tasks: {'generate', 'embed', 'classify', 'reward', 'score'}. Defaulting to 'generate'.
INFO 06-02 14:10:05 [config.py:2118] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 06-02 14:10:10 [__init__.py:243] Automatically detected platform cuda.
INFO 06-02 14:10:12 [core.py:438] Waiting for init message from front-end.
INFO 06-02 14:10:12 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 06-02 14:10:12 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 06-02 14:10:12 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 06-02 14:10:12 [core.py:65] Initializing a V1 LLM engine (v0.9.0) with config: model='microsoft/Phi-4-mini-instruct', speculative_config=None, tokenizer='microsoft/Phi-4-mini-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=microsoft/Phi-4-mini-instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level": 3, "custom_ops": ["none"], "splitting_ops": ["vllm.unified_attention", "vllm.unified_attention_with_output"], "compile_sizes": [], "inductor_compile_config": {"enable_auto_functionalized_v2": false}, "use_cudagraph": true, "cudagraph_num_of_warmups": 1, "cudagraph_capture_sizes": [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], "max_capture_size": 512}
WARNING 06-02 14:10:13 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f6293508d40>
INFO 06-02 14:10:13 [parallel_state.py:1064] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
ERROR 06-02 14:10:13 [core.py:500] EngineCore failed to start.
ERROR 06-02 14:10:13 [core.py:500] Traceback (most recent call last):
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 491, in run_engine_core
ERROR 06-02 14:10:13 [core.py:500]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 06-02 14:10:13 [core.py:500]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 390, in __init__
ERROR 06-02 14:10:13 [core.py:500]     super().__init__(vllm_config, executor_class, log_stats,
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 71, in __init__
ERROR 06-02 14:10:13 [core.py:500]     self.model_executor = executor_class(vllm_config)
ERROR 06-02 14:10:13 [core.py:500]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 52, in __init__
ERROR 06-02 14:10:13 [core.py:500]     self._init_executor()
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 46, in _init_executor
ERROR 06-02 14:10:13 [core.py:500]     self.collective_rpc("init_device")
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
ERROR 06-02 14:10:13 [core.py:500]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 06-02 14:10:13 [core.py:500]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2605, in run_method
ERROR 06-02 14:10:13 [core.py:500]     return func(*args, **kwargs)
ERROR 06-02 14:10:13 [core.py:500]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 604, in init_device
ERROR 06-02 14:10:13 [core.py:500]     self.worker.init_device()  # type: ignore
ERROR 06-02 14:10:13 [core.py:500]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 137, in init_device
ERROR 06-02 14:10:13 [core.py:500]     init_worker_distributed_environment(self.vllm_config, self.rank,
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 353, in init_worker_distributed_environment
ERROR 06-02 14:10:13 [core.py:500]     ensure_kv_transfer_initialized(vllm_config)
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/kv_transfer/kv_transfer_state.py", line 63, in ensure_kv_transfer_initialized
ERROR 06-02 14:10:13 [core.py:500]     _KV_CONNECTOR_AGENT = KVConnectorFactory.create_connector_v1(
ERROR 06-02 14:10:13 [core.py:500]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/kv_transfer/kv_connector/factory.py", line 72, in create_connector_v1
ERROR 06-02 14:10:13 [core.py:500]     assert issubclass(connector_cls, KVConnectorBase_V1)
ERROR 06-02 14:10:13 [core.py:500]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 14:10:13 [core.py:500] AssertionError
Process EngineCore_0:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 504, in run_engine_core
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 491, in run_engine_core
    engine_core = EngineCoreProc(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 390, in __init__
    super().__init__(vllm_config, executor_class, log_stats,
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 71, in __init__
    self.model_executor = executor_class(vllm_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 52, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 46, in _init_executor
    self.collective_rpc("init_device")
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2605, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 604, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 137, in init_device
    init_worker_distributed_environment(self.vllm_config, self.rank,
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 353, in init_worker_distributed_environment
    ensure_kv_transfer_initialized(vllm_config)
  File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/kv_transfer/kv_transfer_state.py", line 63, in ensure_kv_transfer_initialized
    _KV_CONNECTOR_AGENT = KVConnectorFactory.create_connector_v1(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/kv_transfer/kv_connector/factory.py", line 72, in create_connector_v1
    assert issubclass(connector_cls, KVConnectorBase_V1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
[rank0]:[W602 14:10:14.438886419 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 1376, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 1324, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 153, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 185, in build_async_engine_client_from_engine_args
    async_llm = AsyncLLM.from_vllm_config(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 157, in from_vllm_config
    return cls(
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 123, in __init__
    self.engine_core = core_client_class(
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 734, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 418, in __init__
    self._wait_for_engine_startup(output_address, parallel_config)
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 484, in _wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

[1]+  Exit 1                  CUDA_VISIBLE_DEVICES=0 python3 -m vllm.entrypoints.openai.api_server --model $MODEL --port 8100 --max-model-len 8192 --gpu-memory-utilization 0.6 --kv-transfer-config '{"kv_connector":"PyNcclConnector","kv_role":"kv_producer","kv_rank":0,"kv_parallel_size":2,"kv_buffer_size":5e9}'
```

**Comment by XiaobinZhao** [comment]
@surajssd same error. maybe version vllm0.9.0.1  bug

**Comment by surajssd** [comment]
> [@surajssd](https://github.com/surajssd) same error. maybe version vllm0.9.0.1 bug

I used the 0.9.0 version, I am not sure if 0.8.5 works ok!

**Comment by chaunceyjiang** [comment]
It seems that `PyNcclConnector` has not been implemented in v1 yet and is only available in v0.

**Comment by ziruiliu** [comment]
> > [@surajssd](https://github.com/surajssd) same error. maybe version vllm0.9.0.1 bug
> 
> I used the 0.9.0 version, I am not sure if 0.8.5 works ok!

PyNcclConnector is only for v0 engine. you can try 
1. force to use v0 engine with env VLLM_USE_V1=0
2. switch to use v1 connectors, see examples/offline_inference/disaggregated-prefill-v1
Wish these would help

**Comment by valepipi** [comment]
+1

**Comment by pratgaur03** [comment]
Did it work with v1 connectors from examples/offline_inference/disaggregated-prefill-v1?

**Comment by yexiangd** [comment]
Yes `examples/offline_inference/disaggregated-prefill-v1`  works for me

**Comment by pratgaur03** [comment]
> Yes `examples/offline_inference/disaggregated-prefill-v1` works for me
Online?
