### ISSUE TITLE
[Bug]:  ModuleNotFoundError: No module named 'vllm.transformers_utils.configs.dbrx'       

### ISSUE THREAD

**Issue by someoneexistsontheinternet** [vllm-project/vllm#11644]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
(vllm) user@dell-h100-nj5-1:~/vllm$ python collect_env.py
Traceback (most recent call last):
  File "/mnt/weka/home/ggb/vllm/collect_env.py", line 15, in <module>
    from vllm.envs import environment_variables
  File "/mnt/weka/home/ggb/vllm/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/mnt/weka/home/ggb/vllm/vllm/engine/arg_utils.py", line 11, in <module>
    from vllm.config import (CacheConfig, CompilationConfig, ConfigFormat,
  File "/mnt/weka/home/ggb/vllm/vllm/config.py", line 27, in <module>
    from vllm.transformers_utils.config import (
  File "/mnt/weka/home/ggb/vllm/vllm/transformers_utils/config.py", line 25, in <module>
    from vllm.transformers_utils.configs import (ChatGLMConfig, Cohere2Config,
  File "/mnt/weka/home/ggb/vllm/vllm/transformers_utils/configs/__init__.py", line 3, in <module>
    from vllm.transformers_utils.configs.dbrx import DbrxConfig
ModuleNotFoundError: No module named 'vllm.transformers_utils.configs.dbrx'```
```
</details>

### 🐛 Describe the bug

When running 
```
(vllm) user@dell-h100-nj5-1:~/vllm$ vllm serve deepseek-ai/DeepSeek-V3 --max-model-len 8192 -q fp8 -tp 8 --trust-remote-code                                                                                                                     
```
On latest 

```
((vllm) user@dell-h100-nj5-1:~/vllm$ pip install -U vllm                                                                  
Requirement already satisfied: vllm in /mnt/weka/home/ggb/micromamba/envs/vllm/lib/python3.10/site-packages (0.6.6.post1)                                                                                                                       )
```

It fails due to some missing imports? Specifically `ModuleNotFoundError: No module named 'vllm.transformers_utils.configs.dbrx`. Not sure what could be causing this. 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Can you run `pip list` to check which version of vLLM you are actually using?

**Comment by DarkLight1337** [comment]
Also, if you are running vLLM from a local clone of the repository, it may be conflicting with the one you've `pip install`ed.

**Comment by someoneexistsontheinternet** [comment]
`pip list` does 
```
vllm                              0.6.6.post1
```

going to try running it outside 

seems like it works after moving it out... thanks!
