### ISSUE TITLE
[Usage]: multinode inference: assert value == world_size, f"Expected {world_size}, got {value}" AssertionError: Expected 16, got 1.0

### ISSUE THREAD

**Issue by mangomatrix** [vllm-project/vllm#11651]
### Your current environment

```text
The output of `python collect_env.py`
```text
The output of `python collect_env.py`
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.12.8 (main, Dec  4 2024, 08:54:12) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-192-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 535.183.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      43 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             256
On-line CPU(s) list:                0-255
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 7742 64-Core Processor
CPU family:                         23
Model:                              49
Thread(s) per core:                 2
Core(s) per socket:                 64
Socket(s):                          2
Stepping:                           0
Frequency boost:                    enabled
CPU max MHz:                        2250.0000
CPU min MHz:                        1500.0000
BogoMIPS:                           4491.42
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                     AMD-V
L1d cache:                          4 MiB (128 instances)
L1i cache:                          4 MiB (128 instances)
L2 cache:                           64 MiB (128 instances)
L3 cache:                           512 MiB (32 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-15,128-143
NUMA node1 CPU(s):                  16-31,144-159
NUMA node2 CPU(s):                  32-47,160-175
NUMA node3 CPU(s):                  48-63,176-191
NUMA node4 CPU(s):                  64-79,192-207
NUMA node5 CPU(s):                  80-95,208-223
NUMA node6 CPU(s):                  96-111,224-239
NUMA node7 CPU(s):                  112-127,240-255
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] flashinfer==0.1.6+cu121torch2.4
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.47.1
[pip3] triton==3.1.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.6
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    NIC9    NIC10   NIC11   CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV8     NV8     NV8     NV8     NV8     NV8     NV8     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     48-63,176-191   3               N/A
GPU1    NV8      X      NV8     NV8     NV8     NV8     NV8     NV8     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     48-63,176-191   3               N/A
GPU2    NV8     NV8      X      NV8     NV8     NV8     NV8     NV8     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     16-31,144-159   1               N/A
GPU3    NV8     NV8     NV8      X      NV8     NV8     NV8     NV8     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     16-31,144-159   1               N/A
GPU4    NV8     NV8     NV8     NV8      X      NV8     NV8     NV8     SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     112-127,240-255 7               N/A
GPU5    NV8     NV8     NV8     NV8     NV8      X      NV8     NV8     SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     112-127,240-255 7               N/A
GPU6    NV8     NV8     NV8     NV8     NV8     NV8      X      NV8     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     80-95,208-223   5               N/A
GPU7    NV8     NV8     NV8     NV8     NV8     NV8     NV8      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     80-95,208-223   5               N/A
NIC0    PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS      X      PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC1    PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     PXB      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC2    SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS      X      PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC3    SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     PXB      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      PIX     SYS     SYS     SYS     SYS     SYS     SYS
NIC5    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX      X      SYS     SYS     SYS     SYS     SYS     SYS
NIC6    SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      PXB     SYS     SYS     SYS     SYS
NIC7    SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PXB      X      SYS     SYS     SYS     SYS
NIC8    SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      PXB     SYS     SYS
NIC9    SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PXB      X      SYS     SYS
NIC10   SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      PIX
NIC11   SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=12.1 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NCCL_IB_HCA=mlx5
VLLM_USAGE_SOURCE=production-docker-image
CUDA_VERSION=12.1.0
CUDA_LAUNCH_BLOCKING=1
TORCH_USE_CUDA_DSA=1
LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
CUDA_MODULE_LOADING=LAZY

```

```


### How would you like to use vllm

I have 2 nodes, 8 * A800 per node.I want to inference a model on the 2 nodes. 
deploying with docker, multinode inference,  use test.py from https://docs.vllm.ai/en/latest/getting_started/debugging.html.

**docker run**:
* on the master node 
```shell
bash vllm.sh \
    docker.m.daocloud.io/vllm/vllm-openai:v0.6.6 \
    100.150.22.107 \
    --head \
    /mnt/models \
    --privileged -e NCCL_IB_HCA=mlx5
```

* on the other node 

```shell
bash vllm.sh \
    docker.m.daocloud.io/vllm/vllm-openai:v0.6.6 \
    100.150.22.107 \
    --worker \
    /mnt/models \
    --privileged -e NCCL_IB_HCA=mlx5
```

**on the master node**:

```shell
GLOO_SOCKET_IFNAME=enp97s0f1 NCCL_DEBUG=TRACE torchrun --nnodes 2 --nproc-per-node=8 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1 test.py
```

**on the other node**:

```shell
GLOO_SOCKET_IFNAME=enp97s0f1 NCCL_DEBUG=TRACE torchrun --nnodes 2 --nproc-per-node=8 --node-rank 1 --master_addr 100.150.22.107 test.py
```
but error occured:

```shell
.....
DG-DGX6:1453:1453 [1] NCCL INFO ncclCommInitRank comm 0xc3c6de0 rank 9 nranks 16 cudaDev 1 nvmlDev 1 busId f000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1456:1456 [4] NCCL INFO ncclCommInitRank comm 0xb6d5480 rank 12 nranks 16 cudaDev 4 nvmlDev 4 busId 87000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1452:1452 [0] NCCL INFO ncclCommInitRank comm 0xbeb57a0 rank 8 nranks 16 cudaDev 0 nvmlDev 0 busId 7000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1457:1457 [5] NCCL INFO ncclCommInitRank comm 0xb187e60 rank 13 nranks 16 cudaDev 5 nvmlDev 5 busId 90000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1454:1454 [2] NCCL INFO ncclCommInitRank comm 0xc5ea5a0 rank 10 nranks 16 cudaDev 2 nvmlDev 2 busId 47000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1455:1455 [3] NCCL INFO ncclCommInitRank comm 0xc29a730 rank 11 nranks 16 cudaDev 3 nvmlDev 3 busId 4e000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1458:1458 [6] NCCL INFO ncclCommInitRank comm 0xc08ca30 rank 14 nranks 16 cudaDev 6 nvmlDev 6 busId b7000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
DG-DGX6:1459:1459 [7] NCCL INFO ncclCommInitRank comm 0xbc84730 rank 15 nranks 16 cudaDev 7 nvmlDev 7 busId bd000 commId 0xdbc0fae1f524efb3 - Init COMPLETE
[rank9]: Traceback (most recent call last):
[rank9]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank9]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank9]:            ^^^^^^^^^^^^^^^^^^^
[rank9]: AssertionError: Expected 16, got 1.0
[rank11]: Traceback (most recent call last):
[rank11]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank11]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank11]:            ^^^^^^^^^^^^^^^^^^^
[rank11]: AssertionError: Expected 16, got 1.0
[rank13]: Traceback (most recent call last):
[rank13]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank13]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank13]:            ^^^^^^^^^^^^^^^^^^^
[rank13]: AssertionError: Expected 16, got 1.0
[rank10]: Traceback (most recent call last):
[rank10]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank10]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank10]:            ^^^^^^^^^^^^^^^^^^^
[rank10]: AssertionError: Expected 16, got 1.0
[rank8]: Traceback (most recent call last):
[rank8]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank8]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank8]:            ^^^^^^^^^^^^^^^^^^^
[rank8]: AssertionError: Expected 16, got 1.0
[rank12]: Traceback (most recent call last):
[rank12]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank12]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank12]:            ^^^^^^^^^^^^^^^^^^^
[rank12]: AssertionError: Expected 16, got 1.0
[rank15]: Traceback (most recent call last):
[rank15]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank15]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank15]:            ^^^^^^^^^^^^^^^^^^^
[rank15]: AssertionError: Expected 16, got 1.0
[rank14]: Traceback (most recent call last):
[rank14]:   File "/vllm-workspace/test.py", line 43, in <module>
[rank14]:     assert value == world_size, f"Expected {world_size}, got {value}"
[rank14]:            ^^^^^^^^^^^^^^^^^^^
[rank14]: AssertionError: Expected 16, got 1.0
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 3
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 3
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 3
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 3
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 4
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 4
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 4
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 4
DG-DGX6:1456:1560 [4] NCCL INFO [Service thread] Connection closed by localRank 4
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 2
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 2
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 2
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 2
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 6
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 6
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 6
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 6
DG-DGX6:1458:1553 [6] NCCL INFO [Service thread] Connection closed by localRank 6
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 5
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 5
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 5
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 5
DG-DGX6:1457:1552 [5] NCCL INFO [Service thread] Connection closed by localRank 5
[rank8]:[W1230 23:19:23.970692304 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 0
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 0
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 0
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 0
DG-DGX6:1452:1554 [0] NCCL INFO [Service thread] Connection closed by localRank 7
DG-DGX6:1453:1555 [1] NCCL INFO [Service thread] Connection closed by localRank 7
DG-DGX6:1454:1549 [2] NCCL INFO [Service thread] Connection closed by localRank 7
DG-DGX6:1455:1548 [3] NCCL INFO [Service thread] Connection closed by localRank 7
DG-DGX6:1459:1561 [7] NCCL INFO [Service thread] Connection closed by localRank 7
DG-DGX6:1453:1661 [1] NCCL INFO comm 0x8e90b50 rank 9 nranks 16 cudaDev 1 busId f000 - Abort COMPLETE
DG-DGX6:1455:1640 [3] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1454:1641 [2] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1452:1639 [0] NCCL INFO [Service thread] Connection closed by localRank 1
DG-DGX6:1455:1662 [3] NCCL INFO comm 0x8d69e20 rank 11 nranks 16 cudaDev 3 busId 4e000 - Abort COMPLETE
DG-DGX6:1452:1667 [0] NCCL INFO comm 0x897f660 rank 8 nranks 16 cudaDev 0 busId 7000 - Abort COMPLETE
DG-DGX6:1454:1664 [2] NCCL INFO comm 0x90b3290 rank 10 nranks 16 cudaDev 2 busId 47000 - Abort COMPLETE
DG-DGX6:1458:1665 [6] NCCL INFO comm 0x8b56e20 rank 14 nranks 16 cudaDev 6 busId b7000 - Abort COMPLETE
DG-DGX6:1456:1663 [4] NCCL INFO comm 0x8197e20 rank 12 nranks 16 cudaDev 4 busId 87000 - Abort COMPLETE
DG-DGX6:1457:1666 [5] NCCL INFO comm 0x7c50070 rank 13 nranks 16 cudaDev 5 busId 90000 - Abort COMPLETE
W1230 23:19:24.129000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1452 closing signal SIGTERM
W1230 23:19:24.130000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1454 closing signal SIGTERM
W1230 23:19:24.131000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1455 closing signal SIGTERM
W1230 23:19:24.131000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1456 closing signal SIGTERM
W1230 23:19:24.132000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1457 closing signal SIGTERM
W1230 23:19:24.133000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1458 closing signal SIGTERM
W1230 23:19:24.134000 1388 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1459 closing signal SIGTERM
E1230 23:19:24.575000 1388 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 1453) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-30_23:19:24
  host      : DG-DGX6
  rank      : 9 (local_rank: 1)
  exitcode  : 1 (pid: 1453)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

how can I solve it? thanks

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
there is a comment in the test code:

```python
# pynccl is enabled by default for 0.6.5+,
# but for 0.6.4 and below, we need to enable it manually.
# keep the code for backward compatibility when because people
# prefer to read the latest documentation.
pynccl.disabled = False
```

make sure you are reading the latest doc from https://docs.vllm.ai/en/latest/getting_started/troubleshooting.html

**Comment by mangomatrix** [comment]
Thanks, I've abandoned this deployment plan because the A800 doesn't support FP8.

**Comment by youkaichao** [comment]
sorry, I think you need to use the updated script at https://github.com/vllm-project/vllm/pull/13487

**Comment by mangomatrix** [comment]
Thank you, when I later used VLLM I skipped the testing script and went straight to inference without any problems, so I didn't raise any further related questions.
