### ISSUE TITLE
How to inference model that is larger than single GPU?

### ISSUE THREAD

**Issue by teknium1** [vllm-project/vllm#1174]
I am using:
```python
    # load model and inference
    llm = vllm.LLM(
        MODEL_NAME,
        seed=SEED,
    )
    params = vllm.SamplingParams(
        temperature=TEMPERATURE,
        top_p=TOP_P,
        max_tokens=MAX_TOKENS,
        presence_penalty=PRESENCE_PENALTY,
        frequency_penalty=FREQUENCY_PENALTY,
    )

    results: List[InferenceResult] = []

    for batch in batches:
        generated = llm.generate(batch, params)
        for output in generated:
            results.append(
                InferenceResult(
                    prompt=output.prompt, response=output.outputs[0].text
                )
            )
```  

but when I chose a 13b on my 4090, it does not seem to split the model across both gpus?

**Comment by teknium1** [comment]
I tried setting tensor_parallel_size=2 but it says I need to have Ray installed. I pip installed Ray and it tells me its already installed?

```~/vllm$ pip install ray
Requirement already satisfied: ray in ./venv/lib/python3.10/site-packages (2.7.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in ./venv/lib/python3.10/site-packages (from ray) (4.24.3)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in ./venv/lib/python3.10/site-packages (from ray) (1.0.6)
Requirement already satisfied: aiosignal in ./venv/lib/python3.10/site-packages (from ray) (1.3.1)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from ray) (3.12.4)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from ray) (2.31.0)
Requirement already satisfied: click>=7.0 in ./venv/lib/python3.10/site-packages (from ray) (8.1.7)
Requirement already satisfied: numpy>=1.19.3 in ./venv/lib/python3.10/site-packages (from ray) (1.26.0)
Requirement already satisfied: pyyaml in ./venv/lib/python3.10/site-packages (from ray) (6.0.1)
Requirement already satisfied: jsonschema in ./venv/lib/python3.10/site-packages (from ray) (4.19.1)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from ray) (23.1)
Requirement already satisfied: frozenlist in ./venv/lib/python3.10/site-packages (from ray) (1.4.0)
Requirement already satisfied: rpds-py>=0.7.1 in ./venv/lib/python3.10/site-packages (from jsonschema->ray) (0.10.3)
Requirement already satisfied: referencing>=0.28.4 in ./venv/lib/python3.10/site-packages (from jsonschema->ray) (0.30.2)
Requirement already satisfied: attrs>=22.2.0 in ./venv/lib/python3.10/site-packages (from jsonschema->ray) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./venv/lib/python3.10/site-packages (from jsonschema->ray) (2023.7.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->ray) (2.0.5)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->ray) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->ray) (2023.7.22)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->ray) (3.2.0)
```

**Comment by teknium1** [comment]
After installing from git like someone told me to try, now it says:
```Traceback (most recent call last):
  File "/home/teknium/vllm/inference-report-vllm.py", line 213, in <module>
    llm = vllm.LLM(
  File "/home/teknium/vllm/venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 66, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/teknium/vllm/venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 220, in from_engine_args
    distributed_init_method, placement_group = initialize_cluster(
  File "/home/teknium/vllm/venv/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 102, in initialize_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
```  

But I have two gpus (2x 4090s). 
My code used is:
```    llm = vllm.LLM(
        MODEL_NAME,
        seed=SEED,
        tensor_parallel_size=2
    )
```

**Comment by teknium1** [comment]
It worked. Closing.
