### ISSUE TITLE
Serving Qwen/Qwen-14B-Chat-Int4  error

### ISSUE THREAD

**Issue by ZPerling** [vllm-project/vllm#1178]
```
INFO 09-26 11:50:12 api_server.py:650] args: Namespace(host='0.0.0.0', port=8082, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, model='Qwen/Qwen-14B-Chat-Int4', tokenizer=None, tokenizer_mode='auto', trust_remote_code=True, download_dir='/home/models/qwen/Qwen-14B-Chat-Int4', load_format='auto', dtype='auto', worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=2560, max_num_seqs=256, disable_log_stats=False, engine_use_ray=False, disable_log_requests=False)
INFO 09-26 11:50:13 llm_engine.py:72] Initializing an LLM engine with config: model='Qwen/Qwen-14B-Chat-Int4', tokenizer='Qwen/Qwen-14B-Chat-Int4', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, download_dir='/home/models/qwen/Qwen-14B-Chat-Int4', load_format=auto, tensor_parallel_size=1, seed=0)
WARNING 09-26 11:50:14 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 09-26 11:50:14 distributed_c10d.py:442] Added key: store_based_barrier_key:1 to store for rank: 0
INFO 09-26 11:50:14 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
INFO 09-26 11:50:15 distributed_c10d.py:442] Added key: store_based_barrier_key:2 to store for rank: 0
INFO 09-26 11:50:15 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 1 nodes.
INFO 09-26 11:50:15 distributed_c10d.py:442] Added key: store_based_barrier_key:3 to store for rank: 0
INFO 09-26 11:50:15 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:3 with 1 nodes.
INFO 09-26 11:50:15 distributed_c10d.py:442] Added key: store_based_barrier_key:4 to store for rank: 0
INFO 09-26 11:50:15 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:4 with 1 nodes.
INFO 09-26 11:50:15 distributed_c10d.py:442] Added key: store_based_barrier_key:5 to store for rank: 0
INFO 09-26 11:50:15 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:5 with 1 nodes.
INFO 09-26 11:50:15 distributed_c10d.py:442] Added key: store_based_barrier_key:6 to store for rank: 0
INFO 09-26 11:50:15 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:6 with 1 nodes.
INFO 09-26 11:50:15 distributed_c10d.py:442] Added key: store_based_barrier_key:7 to store for rank: 0
INFO 09-26 11:50:15 distributed_c10d.py:476] Rank 0: Completed store-based barrier for key:store_based_barrier_key:7 with 1 nodes.
Traceback (most recent call last):
  File "/home/apps/qwen/api_server.py", line 658, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 250, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_workers(distributed_init_method)
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 134, in _init_workers
    self._run_workers(
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 678, in _run_workers
    output = executor(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/model_executor/model_loader.py", line 66, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/root/miniconda3/envs/codellama/lib/python3.11/site-packages/vllm/model_executor/models/qwen.py", line 280, in load_weights
    loaded_weight = loaded_weight.view(3, total_num_heads,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[3, 32, 128]' is invalid for input of size 15360
```

**Comment by xcpuma** [comment]
貌似不支持量化后的模型

**Comment by White-Friday** [comment]
> 貌似不支持量化后的模型

没量化的也一样，float版本

**Comment by shuai-dian** [comment]
这个问题去看一下qwen14B的config文件https://huggingface.co/Qwen/Qwen-14B-Chat/blob/main/config.json
![image](https://github.com/vllm-project/vllm/assets/83287167/041b8b8c-e8d1-4caf-b2a2-671f8a71424c)
14B的参数变了
Hyperparameter | Value
n_layers | 40
n_heads | 40
d_model | 5120
7B的是32

**Comment by ye7love7** [comment]
一样的问题，哪位大佬能否PR支持一下14b模型。

**Comment by ye7love7** [comment]
支持的。



---Original---
From: "Lionel ***@***.***&gt;
Date: Wed, Nov 22, 2023 18:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] Serving Qwen/Qwen-14B-Chat-Int4  error (Issue#1178)




 
题主解决了吗，目前qwen-14b或14b-chat是否被支持？

**Comment by Wangqi12138** [comment]
请问题主解决了吗？遇到了一样的问题

**Comment by Yang-QW** [comment]
遇到了同样的问题，有没有解决的？

**Comment by Yang-QW** [comment]
解决了，vllm版本的问题，升级到最新版解决了
