### ISSUE TITLE
Quantization is not supported for <class 'vllm.model_executor.models.mistral.MistralForCausalLM'>

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [vllm-project/vllm#1247]
Hi,

Thanks for this great repo!

I tried to run inference on AWQ `casperhansen/mistral-7b-instruct-v0.1-awq` model:
```
from vllm import LLM, SamplingParams

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="casperhansen/mistral-7b-instruct-v0.1-awq", quantization="awq", dtype="half")

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```
And got the following error:
```
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 716/716 [00:00<00:00, 175kB/s]
INFO 10-02 16:43:47 llm_engine.py:72] Initializing an LLM engine with config: model='casperhansen/mistral-7b-instruct-v0.1-awq', tokenizer='casperhansen/mistral-7b-instruct-v0.1-awq', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 915/915 [00:00<00:00, 258kB/s]
Downloading tokenizer.model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 493k/493k [00:00<00:00, 1.33MB/s]
Downloading (…)/main/tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.80M/1.80M [00:00<00:00, 4.07MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72.0/72.0 [00:00<00:00, 93.3kB/s]
Traceback (most recent call last):
  File "/home/matthieu/Code/Python/vLLM/mistral-7b-instruct-v0.1-awq.py", line 11, in <module>
    llm = LLM(model="casperhansen/mistral-7b-instruct-v0.1-awq", quantization="awq", dtype="half")
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 89, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers(distributed_init_method)
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 140, in _init_workers
    self._run_workers(
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 692, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/home/matthieu/anaconda3/envs/vllm_gpu118/lib/python3.8/site-packages/vllm/model_executor/model_loader.py", line 67, in get_model
    raise ValueError(
ValueError: Quantization is not supported for <class 'vllm.model_executor.models.mistral.MistralForCausalLM'>.
```

Could you provide quantization support for `mistral-7b-instruct-v0.1` model?

**Comment by aliozts** [comment]
I have not checked for `awq` yet but for `mistral`, current version of `vllm` works. I'll edit this response if I check for `mistral-awq` as well.

**Comment by rhamnett** [comment]
@Matthieu-Tinycoaching  You just need to fork this repo and add MistralForCausalLM to _MODEL_CLASSES_SUPPORT_QUANTIZATION around line 37 here https://github.com/vllm-project/vllm/blob/acbed3ef40f015fcf64460e629813922fab90380/vllm/model_executor/model_loader.py#L4

This needs a proper fix gong forward, I'd help but not sure what the desired approach is.

**Comment by darrenangle** [comment]
you don't have to fork, you can just do something that shouldn't be possible in python but somehow is


```python

model_class = model_loader._MODEL_REGISTRY["MistralForCausalLM"]

model_loader._MODEL_CLASSES_SUPPORT_QUANTIZATION.append(model_class)

llm = LLM(model="TheBloke/Mistral-7B-Instruct-v0.1-AWQ")
```

**Comment by WoosukKwon** [comment]
Addressed by #1278

**Comment by SalomonKisters** [comment]
Hi, when will this PR be included in pip? Because building from source does not work for me inside docker, always showing a requirements issue.

**Comment by pvtoan** [comment]
Hi,

I got the same problem for AquilaChat2-34B-AWQ and I do the same way as @rhamnett  said by adding 
AquilaForCausalLM,
in model_loader.py 

However, I still got the error "TypeError: __init__() takes 2 positional arguments but 3 were given (type=type_error.raytask(type); cause=__init__() takes 2 positional arguments but 3 were given)"

At present, is AquilaForCausalLM (awq format) not supported by VLLM? If yes, pls let me know how to fix this problem?
