### ISSUE TITLE
v0.2.0 KeyError: 'base_lrs' 

### ISSUE THREAD

**Issue by Careiner** [vllm-project/vllm#1308]
Hi, 
when switching from 0.1.7. to 0.2.0 I encountered this error seen below. When switching back to 0.1.7 it works again. 
I run a Llama 13B model inside a Docker container. 
Any idea how to fix this error? 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/project/vllm_app/run.py", line 33, in <module>
    vllm_single()
  File "/project/vllm_app/run.py", line 14, in vllm_single
    single_test.run_vllm_single()
  File "/project/vllm_app/vllm_samples/single_test.py", line 12, in run_vllm_single
    llm = LLM(model="data/models/llama/")
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 89, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 140, in _init_workers
    self._run_workers(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 692, in _run_workers
    output = executor(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llama.py", line 399, in load_weights
    param = state_dict[name]
KeyError: 'base_lrs'
```
Thank you all and have a nice day!

**Comment by jerrytunin** [comment]
Seeing the same when trying to run samantha-mistral-instruct-7b.

**Comment by WoosukKwon** [comment]
I think this is because the model directory includes `scheduler.pt` or any `*.pt` file not for model weights. For now, please remove (or rename) the `*.pt` files from the model directory.

**Comment by Careiner** [comment]
Thank you for your answer. Indeed removing/renaming all *.pt files from the model folder fixed my issue.
