### ISSUE TITLE
Transitive dependency issues causes pip install to hang

### ISSUE THREAD

**Issue by jonnyli1125** [vllm-project/vllm#1324]
## Problem description

If you try to `pip install vllm` from a blank system or the docker image `nvcr.io/nvidia/pytorch:22.12-py3` (as recommended in the docs), it will take a very long time to install, and the command appears to hang forever. I think it might be the same issue as in https://github.com/vllm-project/vllm/issues/445.

## Quick solution

In the meanwhile, if anyone else is struggling with this issue, I found that the following command fixed the install for me:
```bash
pip install typing-extensions==4.5.0 transformers==4.33.1 vllm==0.2.0
```

## Potential reasons and fixes

In `requirements.txt`, there is:
```
pydantic<2
fastapi
```

They both specify dependency on `typing-extensions`, but there is no compatible version for both of them, i.e. [`pydantic<2` only specifies `typing-extensions==4.3.0`](https://github.com/pydantic/pydantic/blob/v1.10.13/requirements.txt#L7), and [`fastapi` latest version specifies `typing-extensions>=4.5.0`](https://github.com/tiangolo/fastapi/blob/0.103.2/pyproject.toml#L46).

I also found that `vllm.entrypoints.openai.api_server` only works with `typing-extensions==4.5.0`, otherwise you run into some error like this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 21, in <module>
    from vllm.entrypoints.openai.protocol import (
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/protocol.py", line 111, in <module>
    class CompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

Furthermore, if you don't have `transformers` pre-installed, it also may take a long time to resolve the dependencies on some libraries like `regex`.

To the authors, is it possible to specify exact versions in `requirements.txt` like `transformers==4.33.1` to help fix the dependency issues for new installations, instead of a wide version range like `pydantic<2`, `transformers>=4.33.1`, etc?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by I-I-IT** [comment]
This is helpful and should be recommended, the fix above helped me.
