### ISSUE TITLE
baichuan13b vllm upgrade to 0.2.0 load model error

### ISSUE THREAD

**Issue by AltenLi** [vllm-project/vllm#1330]
Traceback (most recent call last):
  File "/user/dddd/vllm_infer_baichuan_full.py", line 193, in <module>
    vllm_model, sampling_params = __init_vllm(parser_paras)
  File "/user/dddd/vllm_infer_baichuan_full.py", line 148, in __init_vllm
    llm = LLM(model=args.state_dict_path,
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 89, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 106, in __init__
    self._init_workers_ray(placement_group)
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 179, in _init_workers_ray
    self._run_workers(
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 696, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/user/dpoenv/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/user/dpoenv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/user/dpoenv/lib/python3.9/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::RayWorker.execute_method() (pid=149364, ip=10.212.201.50, actor_id=42c0b6d1b91018e9ef8e485001000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f2db03c9340>)
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/model_executor/models/baichuan.py", line 329, in load_weights
    loaded_weight = convert_pyslice_to_tensor(loaded_weight)
  File "/user/dpoenv/lib/python3.9/site-packages/vllm/model_executor/weight_utils.py", line 251, in convert_pyslice_to_tensor
    x = x[:]
TypeError: 'int' object is not subscriptable

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
