### ISSUE TITLE
running benchmark OOM

### ISSUE THREAD

**Issue by nuoma** [vllm-project/vllm#1332]
Hi, I'm using 2*3090, the start command is CUDA_VISIBLE_DEVICES=0 python -m vllm.entrypoints.api_server --model Llama-2-7b-chat-hf/ --swap-space 16 --disable-log-requests --port 9009 

Then I use python benchmark_serving.py --backend vllm --tokenizer ../../Llama-2-7b-chat-hf/ --dataset ../../ShareGPT_V3_unfiltered_cleaned_split.json --request-rate 200 --host 127.0.0.1 --port 9009

It was able to finish the benchmark. However for the other two benchmarks, python benchmark_latency.py  --model ../../Llama-2-7b-chat-hf/ --batch-size 10 --input-len 500 and python benchmark_throughput.py --backend vllm --model ../../Llama-2-7b-chat-hf/ --dataset ../../ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 1, I get OOM:

(fastchat) nlp@nlp-1:~/Desktop/20231012_deploy/vllm-main/benchmarks$ python benchmark_throughput.py --backend vllm --model ../../Llama-2-7b-chat-hf/ --dataset ../../ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 1
Namespace(backend='vllm', dataset='../../ShareGPT_V3_unfiltered_cleaned_split.json', model='../../Llama-2-7b-chat-hf/', tokenizer='../../Llama-2-7b-chat-hf/', quantization=None, tensor_parallel_size=1, n=1, use_beam_search=False, num_prompts=1, seed=0, hf_max_batch_size=None, trust_remote_code=False, dtype='auto')
INFO 10-12 20:32:34 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 10-12 20:32:57 llm_engine.py:72] Initializing an LLM engine with config: model='../../Llama-2-7b-chat-hf/', tokenizer='../../Llama-2-7b-chat-hf/', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
INFO 10-12 20:32:57 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "/home/nlp/Desktop/20231012_deploy/vllm-main/benchmarks/benchmark_throughput.py", line 246, in <module>
    main(args)
  File "/home/nlp/Desktop/20231012_deploy/vllm-main/benchmarks/benchmark_throughput.py", line 173, in main
    elapsed_time = run_vllm(requests, args.model, args.tokenizer,
  File "/home/nlp/Desktop/20231012_deploy/vllm-main/benchmarks/benchmark_throughput.py", line 69, in run_vllm
    llm = LLM(
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 89, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers(distributed_init_method)
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 140, in _init_workers
    self._run_workers(
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 692, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/worker/worker.py", line 63, in init_model
    _init_distributed_environment(self.parallel_config, self.rank,
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/vllm/worker/worker.py", line 357, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/nlp/anaconda3/envs/fastchat/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:121, unhandled cuda error, NCCL version 2.14.3
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'out of memory'

**Comment by nuoma** [comment]
Oh, I figured that for these two benchmarks, I don't need vllm workers running. For example, 
python benchmark_latency.py --model ../../Llama-2-7b-chat-hf/ --batch-size 10 --input-len 500
python benchmark_throughput.py --model ../../Llama-2-7b-chat-hf/ --dataset ../../ShareGPT_V3_unfiltered_cleaned_split.json

**Comment by nuoma** [comment]
Oh, I figured that for these two benchmarks, I don't need vllm workers running. For example,
python benchmark_latency.py --model ../../Llama-2-7b-chat-hf/ --batch-size 10 --input-len 500
python benchmark_throughput.py --model ../../Llama-2-7b-chat-hf/ --dataset ../../ShareGPT_V3_unfiltered_cleaned_split.json
