### ISSUE TITLE
openai.error.APIError: Invalid response object from API

### ISSUE THREAD

**Issue by lonngxiang** [vllm-project/vllm#1352]
Traceback (most recent call last):
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_requestor.py", line 403, in handle_error_response
error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\llm\NLP\aquila_openai_api_vllm.py", line 54, in
test_embedding()
File "D:\llm\NLP\aquila_openai_api_vllm.py", line 25, in test_embedding
embedding = openai.Embedding.create(model =model,input="你好")
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
response = super().create(*args, **kwargs)
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
response, _, api_key = requestor.request(
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_requestor.py", line 298, in request
resp, got_stream = self._interpret_response(result, stream)
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_requestor.py", line 707, in _interpret_response
self._interpret_response_line(
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_requestor.py", line 772, in _interpret_response_line
raise self.handle_error_response(
File "C:\Users\loong.conda\envs\nlp\lib\site-packages\openai\api_requestor.py", line 405, in handle_error_response
raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404)
```
openai.api_key = "EMPTY"
model = "/mnt/data/loong/AquilaChat2-7B"
openai.api_base = "http://localhost:10860/v1"

def test_embedding():
    embedding = openai.Embedding.create(model =model,input="hello")
    print(embedding)
    print(embedding["data"][0]["embedding"].shape)
    print(embedding["data"][0]["embedding"])
```

**Comment by lonngxiang** [comment]
anyone？

**Comment by lonngxiang** [comment]
INFO:     192.1**:51306 - "POST /v1/embeddings HTTP/1.1" 404 Not Found

**Comment by satyajitghana** [comment]
I don't think there's an embeddings api with vllm, let me know if you find an implementation!

**Comment by iFe1er** [comment]
same question here, but it is not /v1/embeddings url, but using /v1/chat
