### ISSUE TITLE
Vicuna-7b-v1.3 OOM with vLLM but working with Fastchat

### ISSUE THREAD

**Issue by Katerunner** [vllm-project/vllm#1354]
I am using WSL2 and trying to start OpenAI server with `lmsys/vicuna-7b-v1.3` model using the following command:
```{shell}
python -m vllm.entrypoints.openai.api_server --model lmsys/vicuna-7b-v1.3 --gpu-memory-utilization 0.98 --dtype half
```
After loading the model it takes ~5-6 min of waiting until I get the **ValueError: No available memory for the cache blocks**:
```
$ python -m vllm.entrypoints.openai.api_server --model lmsys/vicuna-7b-v1.3 --gpu-memory-utilization 0.98 --dtype half
INFO 10-14 21:32:44 llm_engine.py:72] Initializing an LLM engine with config: model='lmsys/vicuna-7b-v1.3', tokenizer='lmsys/vicuna-7b-v1.3', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

INFO 10-14 21:40:24 llm_engine.py:205] # GPU blocks: 0, # CPU blocks: 512
Traceback (most recent call last):
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 616, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_cache()
  File "/home/dev/anaconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 209, in _init_cache
    raise ValueError("No available memory for the cache blocks. "
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```

I also tried different combinations of `--gpu-memory-utilization`, `--dtype`, and `--block-size` parameters and got same result.

However when using the `fastchat` platform, I am able to run the model successfully on GPU:
```
$ python3 -m fastchat.serve.cli --model-path lmsys/vicuna-7b-v1.3  --device cuda
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Downloading (…)model.bin.index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.8k/26.8k [00:00<00:00, 12.0MB/s]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.79s/it]
Downloading (…)neration_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [00:00<00:00, 103kB/s]
USER: Hi! How are you?
ASSISTANT: Hello! As an artificial intelligence language model, I don't have...
```
Same with staring the OpenAI server with Fastchat, everything works correctly.

I am using NVIDIA GeForce RTX 3080 Ti 12 Gb GPU. Here is how the `nvidia-smi` result looks like before starting the server:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.112                Driver Version: 537.42       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti     On  | 00000000:01:00.0  On |                  N/A |
|  0%   35C    P8              18W / 350W |    664MiB / 12288MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        23      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

Why am I getting an OOM error in vLLM and how can I fix this if possible?

Thanks for help

**Comment by WoosukKwon** [comment]
The weights of `lmsys/vicuna-7b-v1.3` model take 14GB when using the `half` or `bfloat16` data types. Therefore, it dose not fit into your 12GB GPU. Instead, you can use quantized models by running:
```
python -m vllm.entrypoints.openai.api_server --model casperhansen/vicuna-7b-v1.5-awq --dtype half -q awq
```

I don't know what FastChat does in this case.

**Comment by 1973sir** [comment]
> The weights of `lmsys/vicuna-7b-v1.3` model take 14GB when using the `half` or `bfloat16` data types. Therefore, it dose not fit into your 12GB GPU. Instead, you can use quantized models by running:
> 
> ```
> python -m vllm.entrypoints.openai.api_server --model casperhansen/vicuna-7b-v1.5-awq --dtype half -q awq
> ```
> 
> I don't know what FastChat does in this case.

Got same error with 3090,tried dtype half and float16 with no luck.
However fastchat can run the same model just fine.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
