### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by archeradvanture** [vllm-project/vllm#1382]
Hello team, i am trying to use vllm to inference Llama2-70b-chat-hf on 8 *v100 (32G, 4 nodes ,each node with 2 gpu) . The model was manually downloaded from huggingface , and saved to /mnt/share_dir/models/Llama-2-70b-chat-hf which is a shared directory across 4 nodes 

`vllm: 0.2.0`

And i encountered the error 

Here are the code 

```python

from vllm import LLM,SamplingParams

num_gpus=8
llm = LLM("/mnt/share_dir/models/Llama-2-70b-chat-hf", tensor_parallel_size=num_gpus,load_format="pt")

sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
system_prompt="You are a helpful assistant. "
query= "Hello"
template1 = f"""<<SYS>>{system_prompt}<<SYS>>\n\n
[INST] {query} [INST]
"""
outputs = llm.generate([template1],sampling_params)
# Print the outputs.
print(outputs)

```

```
2023-10-16 21:31:12,187	INFO worker.py:1458 -- Connecting to existing Ray cluster at address: xxx.xxx.xxx.xxx:6379...
2023-10-16 21:31:12,195	INFO worker.py:1642 -- Connected to Ray cluster.
INFO 10-16 21:31:12 llm_engine.py:72] Initializing an LLM engine with config: model='/mnt/share_dir/models/Llama-2-70b-chat-hf', tokenizer='/mnt/share_dir/models/Llama-2-70b-chat-hf', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=8, quantization=None, seed=0)
INFO 10-16 21:31:12 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
Traceback (most recent call last):
  File "/mnt/share_dir/code/inference/distributed/vllm/multiple_node_multiple_gpus_inference.py", line 10, in <module>
    llm = LLM("/mnt/share_dir/models/Llama-2-70b-chat-hf", tensor_parallel_size=num_gpus)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 89, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 106, in __init__
    self._init_workers_ray(placement_group)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 179, in _init_workers_ray
    self._run_workers(
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 696, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(UnpicklingError): ray::RayWorker.execute_method() (pid=125680, ip=10.11.18.25, actor_id=b6da6dd117bc064e660943bf07000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f75f85bcf40>)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 340, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/model_executor/weight_utils.py", line 233, in hf_model_weights_iterator
    state = torch.load(bin_file, map_location="cpu")
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

The previous code loads models in pt , and if load models in safetensors, it raised another error 

```
ray.exceptions.RayTaskError(SafetensorError): ray::RayWorker.execute_method() (pid=157843, ip=xxx, actor_id=530ca09d7391aab6bb3303430b000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7fa027eaafd0>)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 340, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/nfsdir/miniconda3/envs/bx-update-template/lib/python3.9/site-packages/vllm/model_executor/weight_utils.py", line 227, in hf_model_weights_iterator
    with safe_open(st_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by kocmitom** [comment]
If you have the same issue, you probably forget to run `git lfs install` before getting the model from huggingface.

**Comment by KLL535** [comment]
> If you have the same issue, you probably forget to run `git lfs install` before getting the model from huggingface.

(venv) C:\python2\JoyCaption>git lfs install
git: 'lfs' is not a git command. See 'git --help'.
