### ISSUE TITLE
 Could not build wheels for vllm, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ABooth01** [vllm-project/vllm#1391]
This appears to be an issue with CUDA version requiring 11.7. However, there are security concerns with this version of CUDA requiring me to use version 12.2 is there any intention of updating vLLM to work with the latest version of CUDA?

**Comment by latishab** [comment]
Building wheels for collected packages: vllm
  Building wheel for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [157 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\vllm
      copying vllm\block.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\config.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\logger.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\outputs.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\sampling_params.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\sequence.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\utils.py -> build\lib.win-amd64-cpython-311\vllm
      copying vllm\__init__.py -> build\lib.win-amd64-cpython-311\vllm
      creating build\lib.win-amd64-cpython-311\vllm\core
      copying vllm\core\block_manager.py -> build\lib.win-amd64-cpython-311\vllm\core
      copying vllm\core\policy.py -> build\lib.win-amd64-cpython-311\vllm\core
      copying vllm\core\scheduler.py -> build\lib.win-amd64-cpython-311\vllm\core
      copying vllm\core\__init__.py -> build\lib.win-amd64-cpython-311\vllm\core
      creating build\lib.win-amd64-cpython-311\vllm\engine
      copying vllm\engine\arg_utils.py -> build\lib.win-amd64-cpython-311\vllm\engine
      copying vllm\engine\async_llm_engine.py -> build\lib.win-amd64-cpython-311\vllm\engine
      copying vllm\engine\llm_engine.py -> build\lib.win-amd64-cpython-311\vllm\engine
      copying vllm\engine\ray_utils.py -> build\lib.win-amd64-cpython-311\vllm\engine
      copying vllm\engine\__init__.py -> build\lib.win-amd64-cpython-311\vllm\engine
      creating build\lib.win-amd64-cpython-311\vllm\entrypoints
      copying vllm\entrypoints\api_server.py -> build\lib.win-amd64-cpython-311\vllm\entrypoints
      copying vllm\entrypoints\llm.py -> build\lib.win-amd64-cpython-311\vllm\entrypoints
      copying vllm\entrypoints\__init__.py -> build\lib.win-amd64-cpython-311\vllm\entrypoints
      creating build\lib.win-amd64-cpython-311\vllm\model_executor
      copying vllm\model_executor\input_metadata.py -> build\lib.win-amd64-cpython-311\vllm\model_executor
      copying vllm\model_executor\model_loader.py -> build\lib.win-amd64-cpython-311\vllm\model_executor
      copying vllm\model_executor\utils.py -> build\lib.win-amd64-cpython-311\vllm\model_executor
      copying vllm\model_executor\weight_utils.py -> build\lib.win-amd64-cpython-311\vllm\model_executor
      copying vllm\model_executor\__init__.py -> build\lib.win-amd64-cpython-311\vllm\model_executor
      creating build\lib.win-amd64-cpython-311\vllm\transformers_utils
      copying vllm\transformers_utils\config.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils
      copying vllm\transformers_utils\tokenizer.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils
      copying vllm\transformers_utils\__init__.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils
      creating build\lib.win-amd64-cpython-311\vllm\worker
      copying vllm\worker\cache_engine.py -> build\lib.win-amd64-cpython-311\vllm\worker
      copying vllm\worker\worker.py -> build\lib.win-amd64-cpython-311\vllm\worker
      copying vllm\worker\__init__.py -> build\lib.win-amd64-cpython-311\vllm\worker
      creating build\lib.win-amd64-cpython-311\vllm\entrypoints\openai
      copying vllm\entrypoints\openai\api_server.py -> build\lib.win-amd64-cpython-311\vllm\entrypoints\openai
      copying vllm\entrypoints\openai\protocol.py -> build\lib.win-amd64-cpython-311\vllm\entrypoints\openai
      copying vllm\entrypoints\openai\__init__.py -> build\lib.win-amd64-cpython-311\vllm\entrypoints\openai
      creating build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      copying vllm\model_executor\layers\activation.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      copying vllm\model_executor\layers\attention.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      copying vllm\model_executor\layers\layernorm.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      copying vllm\model_executor\layers\rotary_embedding.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      copying vllm\model_executor\layers\sampler.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      copying vllm\model_executor\layers\__init__.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers
      creating build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\aquila.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\baichuan.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\bloom.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\falcon.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\gpt2.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\gpt_bigcode.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\gpt_j.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\gpt_neox.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\internlm.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\llama.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\mistral.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\mpt.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\opt.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\qwen.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      copying vllm\model_executor\models\__init__.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\models
      creating build\lib.win-amd64-cpython-311\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\communication_op.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\layers.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\parallel_state.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\utils.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\__init__.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\parallel_utils
      creating build\lib.win-amd64-cpython-311\vllm\model_executor\quantization_utils
      copying vllm\model_executor\quantization_utils\awq.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\quantization_utils
      copying vllm\model_executor\quantization_utils\base.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\quantization_utils
      copying vllm\model_executor\quantization_utils\__init__.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\quantization_utils
      creating build\lib.win-amd64-cpython-311\vllm\model_executor\layers\quantized_linear
      copying vllm\model_executor\layers\quantized_linear\awq.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers\quantized_linear
      copying vllm\model_executor\layers\quantized_linear\__init__.py -> build\lib.win-amd64-cpython-311\vllm\model_executor\layers\quantized_linear
      creating build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\aquila.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\baichuan.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\falcon.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\mpt.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\qwen.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\__init__.py -> build\lib.win-amd64-cpython-311\vllm\transformers_utils\configs
      running build_ext
      C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "C:\Users\SNS\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\SNS\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 252, in <module>
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\SNS\AppData\Local\Temp\pip-build-env-5_6jbzx7\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'NoneType'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects

(base) C:\Users\SNS>

**Comment by adityamiskin** [comment]
Facing the same issue but for cuda version = 11.8

**Comment by gstarwd** [comment]
same error

**Comment by bacoco** [comment]
Same problem

**Comment by ugref** [comment]
Same error with cuda v12.3

**Comment by latishab** [comment]
> Same error with cuda v12.3

Same, I have an error with cuda v12.3

**Comment by ugref** [comment]
Retried with changed CUDA version to 11.7.1, same problem occurs

**Comment by DoodleBears** [comment]
Same when I try it on Windows. But, it works fine in WSL

**Comment by Siegi96** [comment]
any fix for that?

**Comment by xiexq2019** [comment]
any fix for that?

**Comment by raygeAI** [comment]
any fix for that?

**Comment by evolu8** [comment]
Still failing. Thoughts?

**Comment by darkbloodevil** [comment]
waiting for fix

**Comment by WaddleKing** [comment]
i am still waiting for fix, it is new years please i beg

**Comment by SuperMalinge** [comment]
same issues here
![Uploading vllm.png…]()

**Comment by SuperMalinge** [comment]
![cudaversiont](https://github.com/vllm-project/vllm/assets/64928345/1a41eeae-fd3d-402f-b358-8f42844a5af6)
Ive solved this issue for myself in the setup.py of the vllm-0.2.7.tar.gz. The Version that is hardcoded in there shows 12.1. Changed it to 12.3. and it works fine now

**Comment by Arcmoon-Hu** [comment]
Same error. And I can''t believe no one fix it  for serveal months...

**Comment by chongqingwei** [comment]
> ![cudaversiont](https://private-user-images.githubusercontent.com/64928345/296383171-1a41eeae-fd3d-402f-b358-8f42844a5af6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTA4NDMsIm5iZiI6MTcwOTA5MDU0MywicGF0aCI6Ii82NDkyODM0NS8yOTYzODMxNzEtMWE0MWVlYWUtZmQzZC00MDJmLWIzNTgtOGY0Mjg0NGE1YWY2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAzMjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjA4N2FiMmI2OGExYjUzODNmMGVhMmM1N2Y0NTczMWE5NDY5M2E1NDFlMTUzMzUxNWM2MzIwNjRkN2M4NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j05J66ZTVr8zH3NjoABlijpdTZmGIGhkWVLjfxXeicU) Ive solved this issue for myself in the setup.py of the vllm-0.2.7.tar.gz. The Version that is hardcoded in there shows 12.1. Changed it to 12.3. and it works fine now

which files?

**Comment by minhyuk** [comment]
if you get some error like:
```
        Failed to detect a default CUDA architecture.
```

you have to add PATH for `nvcc` which cmake will use check proper version, try this:
```
> export PATH=/usr/local/cuda/bin:$PATH
> pip install .
```

It works for me :)

**Comment by gstarwd** [comment]
您好 您的邮件我已经收到~
----
王迪

**Comment by Howe-Young** [comment]
> Same error with cuda v12.3

Same error with cuda v12.1

**Comment by gstarwd** [comment]
您好 您的邮件我已经收到~
----
王迪

**Comment by ZhoraZhang** [comment]
Hello! No one solved this issue? I meet the same error in env. python = 3.10, CUDA=11.7

**Comment by inquisitor731** [comment]
> same issues here ![vllm](https://private-user-images.githubusercontent.com/64928345/296383317-7887cf71-7057-47bc-8185-7c08d571fee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjM5NDUsIm5iZiI6MTcyOTAyMzY0NSwicGF0aCI6Ii82NDkyODM0NS8yOTYzODMzMTctNzg4N2NmNzEtNzA1Ny00N2JjLTgxODUtN2MwOGQ1NzFmZWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIwMjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZmQ2MzM3MzRmZDhlZDMxNzY5ZjAwZGY5ZDJmZTI3YjkyMTI2MjMxOTAzYWZlODIzMzgxNmQ3YThlZmQwOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D4fvuBrYQn_YDYVVTDJwy82LFFSS0PLxC-hOJy9siXA)

![root@v2631866_ ~_bot 15 10 2024 14_21_44](https://github.com/user-attachments/assets/22e882ff-dc5b-41ec-a362-129ec5db3c76)

**Comment by inquisitor731** [comment]
you found the solution because I can't find it

**Comment by BoDevOps** [comment]
pip install "vllm>=0.4.3,<0.6.4" => it works fine for me

**Comment by Sameer-13** [comment]
> pip install "vllm>=0.4.3,<0.6.4" => it works fine for me

Which Python version were you using?

**Comment by gstarwd** [comment]
您好 您的邮件我已经收到~
----
王迪
