### ISSUE TITLE
Error when use multiple GPUs

### ISSUE THREAD

**Issue by bugzyz** [vllm-project/vllm#1393]
Hi team,
I am working on inference with codellama/CodeLlama-7b-Instruct-hf on vllm. I am using 2 T4 GPU for this. 
At the first place, I was trying with `engine_args.tensor_parallel_size = 1`. And it shows OOM. So after that, I tried `engine_args.tensor_parallel_size = 2`. But new error pop up.  

FYI, when I tried with 1 A100, the result looks good as the memory is enough.

Could you help check on this? Thanks!

**GPU**
```
(base) [root@ac4da495a32a vllm]# nvidia-smi
Tue Oct 17 10:00:36 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    10W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:00:05.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**version**
```
python==3.8.16

vllm                         0.2.0
transformers                 4.35.0.dev0
torch                        2.0.1
torchvision                  0.15.2
```

**reproduce code**
```
import argparse
import asyncio
from typing import Iterable, Optional, Dict
from vllm import EngineArgs, LLMEngine, RequestOutput, SamplingParams, AsyncLLMEngine, AsyncEngineArgs
from mlserver.logging import logger
import uuid


def get_engine(model_path):
    logger.info("ready to load vllm AsyncLLMEngine")

    engine_args = AsyncEngineArgs(model_path)
    # engine_args.tensor_parallel_size = 1
    engine_args.tensor_parallel_size = 2
    engine_args.dtype = 'float16'
    print(f"engine_args: {engine_args}")
    """
    AsyncEngineArgs(model='facebook/opt-13b', tokenizer='facebook/opt-13b', tokenizer_mode='auto',
                    trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', seed=0,
                    max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2,
                    block_size=16, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None,
                    max_num_seqs=256, disable_log_stats=False, revision=None, quantization=None, engine_use_ray=False,
                    disable_log_requests=False, max_log_len=None)
    """
    engine = AsyncLLMEngine.from_engine_args(engine_args)

    logger.info(f"loaded vllm AsyncLLMEngine with model_path: {model_path}")
    return engine


async def generate_stream_vllm(engine,
                               tokenizer,
                               prompt,
                               temperature,
                               presence_penalty,
                               frequency_penalty,
                               max_tokens,
                               stream_interval: int = 2
                               ):
    assert stream_interval > 0, f'stream_interval assertion failed, expect > 0 but got {stream_interval}'
    logger.info("generate_stream_vllm with vllm AsyncLLMEngine")

    sampling_params = SamplingParams(
        temperature=temperature,
        presence_penalty=presence_penalty,
        # frequency_penalty=frequency_penalty,
        max_tokens=max_tokens,
    )

    logger.info(f"sampling_params: {sampling_params}")

    request_id = uuid.uuid4()

    cur_step = 0
    async for request_output in engine.generate(prompt, sampling_params, request_id):
        cur_step = cur_step + 1

        if request_output.finished or cur_step % stream_interval == 0:
            yield {
                "text": request_output.outputs[0].text,
                "usage": {
                    "prompt_tokens": len(request_output.prompt_token_ids),
                    "completion_tokens": len(request_output.outputs[0].token_ids),
                    "total_tokens": len(request_output.prompt_token_ids) + len(request_output.outputs[0].token_ids),
                },
                "finish_reason": None if not request_output.finished else "stop",
            }


async def generate_vllm(engine,
                        tokenizer,
                        prompt,
                        temperature,
                        presence_penalty,
                        frequency_penalty,
                        max_tokens,
                        ):
    logger.info("generate_vllm with vllm AsyncLLMEngine")
    result = None
    async for result in generate_stream_vllm(engine,
                                             tokenizer,
                                             prompt,
                                             temperature,
                                             presence_penalty,
                                             frequency_penalty,
                                             max_tokens,
                                             50
                                             ):
        pass
    return result


def non_streaming_main():
    # model_path = "codellama/CodeLlama-13b-Instruct-hf"
    model_path = "codellama/CodeLlama-7b-Instruct-hf"
    params = {
        "prompt": "A robot may not injure a human being",
        "temperature": 0.0,
        "repetition_penalty": 1.0,
        "max_new_tokens": 30,
    }

    engine = get_engine(model_path)
    print(asyncio.run(generate_vllm(engine,
                                    None,
                                    prompt=params["prompt"],
                                    temperature=params["temperature"],
                                    presence_penalty=params["repetition_penalty"],
                                    frequency_penalty=None,
                                    max_tokens=params["max_new_tokens"],
                                    )))


if __name__ == '__main__':
    non_streaming_main()
```

**engine_args.tensor_parallel_size = 1**
```
(base) [root@ac4da495a32a vllm]# python vllm_wrapper_async.py
engine_args: AsyncEngineArgs(model='codellama/CodeLlama-7b-Instruct-hf', tokenizer='codellama/CodeLlama-7b-Instruct-hf', tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='float16', seed=0, max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, block_size=16, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, disable_log_stats=False, revision=None, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████| 646/646 [00:00<00:00, 68.4kB/s]
WARNING 10-17 09:53:40 config.py:341] Casting torch.bfloat16 to torch.float16.
INFO 10-17 09:53:40 llm_engine.py:72] Initializing an LLM engine with config: model='codellama/CodeLlama-7b-Instruct-hf', tokenizer='codellama/CodeLlama-7b-Instruct-hf', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
INFO 10-17 09:53:40 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████| 749/749 [00:00<00:00, 94.7kB/s]
Downloading tokenizer.model: 100%|████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 2.33MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 24.1MB/s]
Downloading (…)cial_tokens_map.json: 100%|███████████████████████████████████████████████| 411/411 [00:00<00:00, 218kB/s]
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:34617 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:34617 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:34617 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:34617 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:34617 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:34617 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:34617 (errno: 97 - Address family not supported by protocol).
Downloading (…)of-00002.safetensors: 100%|██████████████████████████████████████████| 3.50G/3.50G [01:03<00:00, 55.0MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████████████████████████████████████| 9.98G/9.98G [03:00<00:00, 55.4MB/s]
Traceback (most recent call last):
  File "vllm_wrapper_async.py", line 115, in <module>
    non_streaming_main()
  File "vllm_wrapper_async.py", line 103, in non_streaming_main
    engine = get_engine(model_path)
  File "vllm_wrapper_async.py", line 25, in get_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_cache()
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 191, in _init_cache
    num_blocks = self._run_workers(
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 692, in _run_workers
    output = executor(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/worker/worker.py", line 109, in profile_num_available_blocks
    self.model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/llama.py", line 297, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/llama.py", line 257, in forward
    hidden_states = layer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/llama.py", line 216, in forward
    hidden_states = self.mlp(hidden_states)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/llama.py", line 81, in forward
    gate_up, _ = self.gate_up_proj(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 238, in forward
    output_parallel = self.apply_weights(input_parallel, bias)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 222, in apply_weights
    return F.linear(x, self.weight, bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 688.00 MiB (GPU 0; 14.58 GiB total capacity; 13.06 GiB already allocated; 678.38 MiB free; 13.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**engine_args.tensor_parallel_size = 2**
```
(base) [root@ac4da495a32a vllm]# python vllm_wrapper_async.py
engine_args: AsyncEngineArgs(model='codellama/CodeLlama-7b-Instruct-hf', tokenizer='codellama/CodeLlama-7b-Instruct-hf', tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='float16', seed=0, max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, block_size=16, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, disable_log_stats=False, revision=None, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 10-17 09:57:35 config.py:341] Casting torch.bfloat16 to torch.float16.
2023-10-17 09:57:37,236	WARNING services.py:1889 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 46964736 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=7.67gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-10-17 09:57:37,378	INFO worker.py:1642 -- Started a local Ray instance.
INFO 10-17 09:57:38 llm_engine.py:72] Initializing an LLM engine with config: model='codellama/CodeLlama-7b-Instruct-hf', tokenizer='codellama/CodeLlama-7b-Instruct-hf', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, seed=0)
INFO 10-17 09:57:38 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
(RayWorker pid=6679) [W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:172.17.0.3]:36763 (errno: 97 - Address family not supported by protocol).
(RayWorker pid=6678) [W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:36763 (errno: 97 - Address family not supported by protocol).
(RayWorker pid=6679) *** SIGBUS received at time=1697536689 on cpu 7 ***
(RayWorker pid=6679) PC: @     0x7f600974f18a  (unknown)  __memset_avx2_unaligned_erms
(RayWorker pid=6679)     @     0x7f60096e9df0       1536  (unknown)
(RayWorker pid=6679)     @ 0x54392d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=6679) [2023-10-17 09:58:09,995 E 6679 6879] logging.cc:361: *** SIGBUS received at time=1697536689 on cpu 7 ***
(RayWorker pid=6679) [2023-10-17 09:58:09,996 E 6679 6879] logging.cc:361: PC: @     0x7f600974f18a  (unknown)  __memset_avx2_unaligned_erms
(RayWorker pid=6679) [2023-10-17 09:58:09,999 E 6679 6879] logging.cc:361:     @     0x7f60096e9df0       1536  (unknown)
(RayWorker pid=6679) [2023-10-17 09:58:10,003 E 6679 6879] logging.cc:361:     @ 0x54392d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=6679) Fatal Python error: Bus error
(RayWorker pid=6679)
(RayWorker pid=6678) [W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [::ffff:172.17.0.3]:36763 (errno: 97 - Address family not supported by protocol). [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
2023-10-17 09:58:10,214	WARNING worker.py:2058 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff5612a023179f9dd66427c42101000000 Worker ID: 751fef21f9b691422fcf0a276b2e0cd19b3c3eb807a3dcf7eb0f240a Node ID: 52ba7341d9a6a03d304c25c56050eb18dbde025686633d9b3a2afdf2 Worker IP address: 172.17.0.3 Worker port: 35173 Worker PID: 6679 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "vllm_wrapper_async.py", line 115, in <module>
    non_streaming_main()
  File "vllm_wrapper_async.py", line 103, in non_streaming_main
    engine = get_engine(model_path)
  File "vllm_wrapper_async.py", line 25, in get_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_cache()
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 191, in _init_cache
    num_blocks = self._run_workers(
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 696, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/opt/conda/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ray/_private/worker.py", line 2549, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: RayWorker
	actor_id: 5612a023179f9dd66427c42101000000
	pid: 6679
	namespace: 4b5e0964-74c2-4739-bd27-961c79067b12
	ip: 172.17.0.3
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(RayWorker pid=6678) *** SIGBUS received at time=1697536689 on cpu 4 ***
(RayWorker pid=6678) PC: @     0x7f3c580e518a  (unknown)  __memset_avx2_unaligned_erms
(RayWorker pid=6678)     @     0x7f3c5807fdf0       1536  (unknown)
(RayWorker pid=6678)     @ 0x43422d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=6678) [2023-10-17 09:58:09,995 E 6678 6878] logging.cc:361: *** SIGBUS received at time=1697536689 on cpu 4 ***
(RayWorker pid=6678) [2023-10-17 09:58:09,996 E 6678 6878] logging.cc:361: PC: @     0x7f3c580e518a  (unknown)  __memset_avx2_unaligned_erms
(RayWorker pid=6678) [2023-10-17 09:58:09,999 E 6678 6878] logging.cc:361:     @     0x7f3c5807fdf0       1536  (unknown)
(RayWorker pid=6678) [2023-10-17 09:58:10,003 E 6678 6878] logging.cc:361:     @ 0x43422d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=6678) Fatal Python error: Bus error
(RayWorker pid=6678)
```

**Comment by 10xsai** [comment]
Facing same issue when trying with llama 7b on single and two v100s instances

**Comment by lish-baidu** [comment]
me too，the bug occur when set --tensor-parallel-size=4.

**Comment by yeshenyong** [comment]
the same issue

**Comment by yeshenyong** [comment]
解法：`docker run --shm-size=10.24gb -d your_image_name` 即可（chatgpt4 说的，实测可以，附上chatgpt4 解释 这个警告信息是来自于 Ray（一种用于分布式计算的库），它在告诉你对象存储正在使用 /tmp 目录而不是 /dev/shm 目录。这通常是由于 /dev/shm 的可用空间不足导致的。/dev/shm 是一个临时文件存储区，也被称为共享内存，通常用于高性能计算场景，因为它比普通的磁盘存储有更快的访问速度。

默认情况下，Docker 容器的 /dev/shm 分区大小可能相对较小，这可能限制了性能，尤其是在需要大量内存的应用程序中。为了解决这个问题，你可以在启动 Docker 容器时，设置更大的共享内存大小。

根据警告信息提供的建议，你可以通过以下步骤来增加 Docker 容器的 /dev/shm 大小：）

**Comment by francescov1** [comment]
Using `--ipc=host` fixed the issue for me. See vLLM docs here: https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html

**Comment by yeshenyong** [comment]
您好，我是叶燊泳，已收到你的邮件。

**Comment by qdm12** [comment]
FYI for anyone using `podman-compose`, the `ipc` instruction is still unsupported for whatever obscure reason, and no error is given for unknown fields in your docker-compose.yml, so watch out for this.
