### ISSUE TITLE
Division/modulo by 0 error in Falcon when using >8 gpu cluster

### ISSUE THREAD

**Issue by lroberts7** [vllm-project/vllm#1412]
Hi vllm, 

We're  doing some benchmarking for various configurations.
Our cluster setup is a 2-node, 16 gpu L40 running ray. 

For the 40B Falcon model I'm not able to run this using 16 gpus (2 nodes) but we are able to run this same workload using 2,4,8 gpus and the 40B Falcon model). 

The error is a division by 0 on the 16 gpu but not on the 8 gpu. Here is a brief stack trace/logs for both scenarios

Here is `tensor_parallel_size=8`

```bash

INFO 2023-10-18 16:22:35,133 run.py:137 unknown_model_name:unknown_model_version
Hello! logging initialized, starting up... 
INFO 2023-10-18 16:22:35,133 run.py:138 unknown_model_name:unknown_model_version
Git commit of model: unknown_git_commit 
INFO 2023-10-18 16:22:35,133 run.py:139 unknown_model_name:unknown_model_version
Git commit of cuda torch base: unknown_git_commit 
INFO 2023-10-18 16:22:35,653 run.py:143 unknown_model_name:unknown_model_version
Compute device available: cuda 
2023-10-18 16:22:35,930	INFO worker.py:1458 -- Connecting to existing Ray cluster at address: 172.18.220.54:6379...
2023-10-18 16:22:35,936	INFO worker.py:1642 -- Connected to Ray cluster.
INFO 2023-10-18 16:23:50,962 run.py:166 unknown_model_name:unknown_model_version
Startup completed! 
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.23s/it]
```
Here is `tensor_parallel_size=16`
```bash
chat with 16 and 1...
INFO 2023-10-18 16:23:56,644 run.py:137 unknown_model_name:unknown_model_version
Hello! logging initialized, starting up... 
INFO 2023-10-18 16:23:56,645 run.py:138 unknown_model_name:unknown_model_version
Git commit of model: unknown_git_commit 
INFO 2023-10-18 16:23:56,645 run.py:139 unknown_model_name:unknown_model_version
Git commit of cuda torch base: unknown_git_commit 
INFO 2023-10-18 16:23:57,102 run.py:143 unknown_model_name:unknown_model_version
Compute device available: cuda 
2023-10-18 16:23:57,384	INFO worker.py:1458 -- Connecting to existing Ray cluster at address: 172.18.220.54:6379...
2023-10-18 16:23:57,389	INFO worker.py:1642 -- Connected to Ray cluster.
Traceback (most recent call last):
  File "/home/cirrascale/run.py", line 246, in <module>
    chat_en = ChatEn(ngpu=args.ngpu)
  File "/home/cirrascale/run.py", line 162, in __init__
    self.model = LLM(model=self.model_path, tensor_parallel_size=self.n_gpu)
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 89, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 106, in __init__
    self._init_workers_ray(placement_group)
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 179, in _init_workers_ray
    self._run_workers(
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 696, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/cirrascale/.local/share/virtualenvs/bert-dock-hsoAEOOS/lib/python3.10/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ZeroDivisionError): ray::RayWorker.execute_method() (pid=850118, ip=172.18.220.54, actor_id=ae7d063dad05cbc64258f53066000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7fc4f82631c0>)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/worker/worker.py", line 68, in init_model
    self.model = get_model(self.model_config)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 93, in get_model
    model = model_class(model_config.hf_config)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/models/falcon.py", line 391, in __init__
    self.transformer = FalconModel(config)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/models/falcon.py", line 353, in __init__
    self.h = nn.ModuleList([
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/models/falcon.py", line 354, in <listcomp>
    FalconDecoderLayer(config) for _ in range(config.num_hidden_layers)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/models/falcon.py", line 264, in __init__
    self.self_attention = FalconAttention(config)
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/models/falcon.py", line 167, in __init__
    self.attn = PagedAttentionWithRoPE(
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 279, in __init__
    super().__init__(num_heads,
  File "/home/cirrascale/.local/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 70, in __init__
    assert self.num_heads % self.num_kv_heads == 0
ZeroDivisionError: integer division or modulo by zero
```

I suspect what is happening here is the integer division is returning a 0 which is propagated further in the code path, creating the division by 0. 

The config.json for falcon we have in the cluster:

```bash
{
  "alibi": false,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "FalconForCausalLM"
  ],
  "attention_dropout": 0.0,
  "auto_map": {
    "AutoConfig": "configuration_falcon.FalconConfig",
    "AutoModel": "modeling_falcon.FalconModel",
    "AutoModelForSequenceClassification": "modeling_falcon.FalconForSequenceClassification",
    "AutoModelForTokenClassification": "modeling_falcon.FalconForTokenClassification",
    "AutoModelForQuestionAnswering": "modeling_falcon.FalconForQuestionAnswering",
    "AutoModelForCausalLM": "modeling_falcon.FalconForCausalLM"
  },
  "bias": false,
  "bos_token_id": 11,
  "eos_token_id": 11,
  "hidden_dropout": 0.0,
  "hidden_size": 8192,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "falcon",
  "new_decoder_architecture": true,
  "num_attention_heads": 128,
  "num_hidden_layers": 60,
  "num_kv_heads": 8,
  "parallel_attn": true,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.27.4",
  "use_cache": true,
  "vocab_size": 65024
}
```
 I suspect that the integer division of `num_kv_heads` by 16 gets converted to 0 and propagated in the code. 

Is this a bug or should this setup for falcon-40b fail? (and perhaps a more informative error message could be returned?) 

Thanks for all the work so far on vllm project, kind regards.

**Comment by lroberts7** [comment]
Just in case you want these: 
```bash
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vllm, ray 
>>> vllm.__version__
'0.2.0'
>>> ray.__version__
'2.7.1'
>>> 

```

**Comment by lroberts7** [comment]
I had missed these before but it looks like these might be related issues for llama2 model that are in `0.2.1` so including link s here, in the llama2 model it seems that the kv == 8 issue was ameliorated when # gpus > 8, perhaps it is a similar issue here with falcon-40b? 

https://github.com/vllm-project/vllm/pull/1122 
https://github.com/vllm-project/vllm/pull/1209
