### ISSUE TITLE
Llama-2 13B run on 2 RTX4090 GPU error

### ISSUE THREAD

**Issue by zhuyy1168** [vllm-project/vllm#1421]
hi, when i run Llama-2-13b-chat-hf on 2 RTX4090 GPUs, someting wrong.
pytorch 2.0.1 cuda11.8 vllm0.2.1

python -m vllm.entrypoints.api_server --model llama2/Llama-2-13b-chat-hf/ --tensor-parallel-size 2

error:
param[:loaded_weight.shape[0]].copy_(loaded_weight)
RuntimeError: The size of tensor a (5120) must match the size of tensor b (4096) at non-singleton dimension 1

log:
2023-10-19 17:44:09,548	INFO worker.py:1642 -- Started a local Ray instance.
INFO 10-19 17:44:12 llm_engine.py:72] Initializing an LLM engine with config: model='llama2/Llama-2-13b-chat-hf/', tokenizer='llama2/Llama-2-13b-chat-hf/', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, seed=0)
INFO 10-19 17:44:12 tokenizer.py:31] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/entrypoints/api_server.py", line 74, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 487, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers_ray(placement_group)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/llm_engine.py", line 181, in _init_workers_ray
    self._run_workers(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/llm_engine.py", line 704, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::RayWorker.execute_method() (pid=62632, ip=192.168.1.143, actor_id=d044915b9ecd845ef01b482501000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7ef3583d5c70>)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/worker/worker.py", line 70, in init_model
    self.model = get_model(self.model_config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/model_executor/model_loader.py", line 103, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/model_executor/models/llama.py", line 416, in load_weights
    load_padded_tensor_parallel_vocab(param, loaded_weight,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/vllm-0.2.1-py3.8-linux-x86_64.egg/vllm/model_executor/weight_utils.py", line 275, in load_padded_tensor_parallel_vocab
    param[:loaded_weight.shape[0]].copy_(loaded_weight)
RuntimeError: The size of tensor a (5120) must match the size of tensor b (4096) at non-singleton dimension 1

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
