### ISSUE TITLE
Exception while running fine-tuned Mistral

### ISSUE THREAD

**Issue by DHOFM** [vllm-project/vllm#1430]
Running vllm as a service I often get a 500 Error Response. This happens, if I run a fine-tuned Version of mistral. I did the Finetuning using Transformers Trainer and QLORA. The Model itself runs. I run the base model with the same prompt, I don't get this error. Here is the full stack trace:
```

`
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f09ff3c21f0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f0858f385e0>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f09ff3c21f0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f0858f385e0>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 351, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 330, in engine_step
    request_outputs = await self.engine.step_async()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 522, in _process_model_outputs
    self._process_sequence_group_samples(seq_group, samples)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 393, in _process_sequence_group_samples
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 631, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/usr/local/lib/python3.8/dist-packages/vllm/transformers_utils/tokenizer.py", line 140, in detokenize_incrementally
    new_text = _convert_tokens_to_string_with_added_encoders(
  File "/usr/local/lib/python3.8/dist-packages/vllm/transformers_utils/tokenizer.py", line 94, in _convert_tokens_to_string_with_added_encoders
    sub_text = tokenizer.convert_tokens_to_string(current_sub_text)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_fast.py", line 580, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO 10-20 12:46:25 async_llm_engine.py:134] Aborted request cmpl-87bfd8b4a28c44238cfcd5e39c76c0bd.
INFO:     127.0.0.1:34826 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 351, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 330, in engine_step
    request_outputs = await self.engine.step_async()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 522, in _process_model_outputs
    self._process_sequence_group_samples(seq_group, samples)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 393, in _process_sequence_group_samples
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 631, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/usr/local/lib/python3.8/dist-packages/vllm/transformers_utils/tokenizer.py", line 140, in detokenize_incrementally
    new_text = _convert_tokens_to_string_with_added_encoders(
  File "/usr/local/lib/python3.8/dist-packages/vllm/transformers_utils/tokenizer.py", line 94, in _convert_tokens_to_string_with_added_encoders
    sub_text = tokenizer.convert_tokens_to_string(current_sub_text)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_fast.py", line 580, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 514, in create_completion
    async for res in result_generator:
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 435, in generate
    raise e
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 429, in generate
    async for request_output in stream:
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 70, in __anext__
    raise result
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
`
```

**Comment by sumsam-ali-sac** [comment]
I want to know how u did the finetuning can we connect?

**Comment by DHOFM** [comment]
@sumsam-ali-sac Sure, what do you need to know? I did a QLoRa Tuning without using peft (only for helper methods) - because I got OOPs with peft after updating my docker container. So it is a native Transformer based Training

**Comment by zysNLP** [comment]
> @sumsam-ali-sac Sure, what do you need to know? I did a QLoRa Tuning without using peft (only for helper methods) - because I got OOPs with peft after updating my docker container. So it is a native Transformer based Training

Can you send me something to my email zys158am@126.com? I want to known how you use vllm with finetuned models, thank you very much!

**Comment by DoctorSlimm** [comment]
@DHOFM did you succeed in running fine tuned mistral with vllm?
