### ISSUE TITLE
AssertionError   assert output == other_output

### ISSUE THREAD

**Issue by shujun1992** [vllm-project/vllm#1476]
model:  Qwen-7B-Chat
cuda: 12.2
vllm: 0.2.1
GPU:  2   T4

async_llm_engine.py:134] Aborted request 2f0244c5636145e8bf9a59e7b4063657.
2023-10-26 18:11:35 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-10-26 18:11:35 | ERROR | stderr | Traceback (most recent call last):
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
2023-10-26 18:11:35 | ERROR | stderr |     task.result()
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 351, in run_engine_loop
2023-10-26 18:11:35 | ERROR | stderr |     has_requests_in_progress = await self.engine_step()
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 330, in engine_step
2023-10-26 18:11:35 | ERROR | stderr |     request_outputs = await self.engine.step_async()
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 191, in step_async
2023-10-26 18:11:35 | ERROR | stderr |     output = await self._run_workers_async(
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 228, in _run_workers_async
2023-10-26 18:11:35 | ERROR | stderr |     assert output == other_output
2023-10-26 18:11:35 | ERROR | stderr | AssertionError
2023-10-26 18:11:35 | ERROR | stderr | 
2023-10-26 18:11:35 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-10-26 18:11:35 | ERROR | stderr | 
2023-10-26 18:11:35 | ERROR | stderr | Traceback (most recent call last):
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-10-26 18:11:35 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/fastapi/applications.py", line 1115, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     raise exc
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     raise exc
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     raise e
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     await self.app(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-10-26 18:11:35 | ERROR | stderr |     await self.app(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2023-10-26 18:11:35 | ERROR | stderr |     await response(scope, receive, send)
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-10-26 18:11:35 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-10-26 18:11:35 | ERROR | stderr |     raise exceptions[0]
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-10-26 18:11:35 | ERROR | stderr |     await func()
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2023-10-26 18:11:35 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/fastchat/serve/vllm_worker.py", line 103, in generate_stream
2023-10-26 18:11:35 | ERROR | stderr |     async for request_output in results_generator:
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 436, in generate
2023-10-26 18:11:35 | ERROR | stderr |     raise e
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 430, in generate
2023-10-26 18:11:35 | ERROR | stderr |     async for request_output in stream:
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 70, in __anext__
2023-10-26 18:11:35 | ERROR | stderr |     raise result
2023-10-26 18:11:35 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
2023-10-26 18:11:35 | ERROR | stderr |     raise exc
2023-10-26 18:11:35 | ERROR | stderr |   File "/opt/jiuyindanao/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
2023-10-26 18:11:35 | ERROR | stderr |     raise AsyncEngineDeadError(
2023-10-26 18:11:35 | ERROR | stderr | vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

**Comment by vishal09vns** [comment]
Faced same issue while using [LINK](https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-AWQ)

`llm = LLM("model_weights/TheBloke_Mistral-7B-OpenOrca-AWQ", tensor_parallel_size=1, quantization = "awq", dtype ="half" )`

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
