### ISSUE TITLE
New Dockerfile build error

### ISSUE THREAD

**Issue by Extremys** [vllm-project/vllm#1539]
Hello trying to build the new pushed Dockerfile I get the following error:
Command executed with docker 20.10.23 version (under Windows 10), the processes are progressively Killed.
`
set DOCKER_BUILDKIT=1
docker build . --target vllm --tag vllm --build-arg max_jobs=8
`

``` log
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(277): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(291): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
606.0
606.0 Killed
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(40): warning #177-D: variable "scaling_factors_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(41): warning #177-D: variable "zeros_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(44): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(58): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(272): warning #177-D: variable "scaling_factors_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(273): warning #177-D: variable "zeros_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(277): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(291): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(24): warning #177-D: function "vllm::awq::__pack_half2" was declared but never referenced
606.0
606.0 Killed
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(24): warning #177-D: function "vllm::awq::__pack_half2" was declared but never referenced
606.0
606.0 Killed
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(40): warning #177-D: variable "scaling_factors_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(41): warning #177-D: variable "zeros_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(44): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(58): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(272): warning #177-D: variable "scaling_factors_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(273): warning #177-D: variable "zeros_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(277): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(291): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(24): warning #177-D: function "vllm::awq::__pack_half2" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(40): warning #177-D: variable "scaling_factors_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(41): warning #177-D: variable "zeros_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(44): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(58): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(272): warning #177-D: variable "scaling_factors_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(273): warning #177-D: variable "zeros_shared" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(277): warning #177-D: variable "blockIdx_x" was declared but never referenced
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(291): warning #177-D: variable "ld_zero_flag" was declared but never referenced
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
606.0
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
606.0           detected during:
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 (61): here
606.0             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
606.0 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
606.0
606.0 /workspace/csrc/quantization/awq/gemm_kernels.cu(24): warning #177-D: function "vllm::awq::__pack_half2" was declared but never referenced
606.0
625.3 [3/3] /usr/local/cuda/bin/nvcc  -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c -c /workspace/csrc/quantization/squeezellm/quant_cuda_kernel.cu -o /workspace/build/temp.linux-x86_64-3.10/csrc/quantization/squeezellm/quant_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_86,code=sm_86 --threads 8 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quantization_ops -D_GLIBCXX_USE_CXX11_ABI=0
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/core/TensorImpl.h(77): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
625.3           detected during:
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 (61): here
625.3             instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/qualified_name.h(73): here
625.3
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/cuda/CUDATensorMethods.cuh: In member function ‘T* at::Tensor::data() const [with T = __half]’:
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/cuda/CUDATensorMethods.cuh:13:59: warning: ‘T* at::Tensor::data() const [with T = c10::Half]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
625.3    13 |   return reinterpret_cast<__half*>(data<Half>());
625.3       |                                    ~~~~~~~~~~~~~~         ^
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/TensorBody.h:244:1: note: declared here
625.3   244 |   T * data() const {
625.3       | ^ ~~
625.3 /workspace/csrc/quantization/squeezellm/quant_cuda_kernel.cu: In function ‘void squeezellm_gemm(at::Tensor, at::Tensor, at::Tensor, at::Tensor)’:
625.3 /workspace/csrc/quantization/squeezellm/quant_cuda_kernel.cu:138:125: warning: ‘T* at::Tensor::data() const [with T = c10::Half]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
625.3   138 |   vllm::squeezellm::NUQ4MatMulKernel<<<blocks, threads>>>(
625.3       |                                                                                                                             ^
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/TensorBody.h:244:1: note: declared here
625.3   244 |   T * data() const {
625.3       | ^ ~~
625.3 /workspace/csrc/quantization/squeezellm/quant_cuda_kernel.cu:138:182: warning: ‘T* at::Tensor::data() const [with T = c10::Half]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
625.3   138 |   vllm::squeezellm::NUQ4MatMulKernel<<<blocks, threads>>>(
625.3       |
                ^
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/TensorBody.h:244:1: note: declared here
625.3   244 |   T * data() const {
625.3       | ^ ~~
625.3 /workspace/csrc/quantization/squeezellm/quant_cuda_kernel.cu:138:226: warning: ‘T* at::Tensor::data() const [with T = c10::Half]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
625.3   138 |   vllm::squeezellm::NUQ4MatMulKernel<<<blocks, threads>>>(
625.3       |
                                                            ^
625.3 /usr/local/lib/python3.10/dist-packages/torch/include/ATen/core/TensorBody.h:244:1: note: declared here
625.3   244 |   T * data() const {
625.3       | ^ ~~
625.3 ninja: build stopped: subcommand failed.
625.5 Traceback (most recent call last):
625.5   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
625.5     subprocess.run(
625.5   File "/usr/lib/python3.10/subprocess.py", line 526, in run
625.5     raise CalledProcessError(retcode, process.args,
625.5 subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
625.5
625.5 The above exception was the direct cause of the following exception:
625.5
625.5 Traceback (most recent call last):
625.5   File "/workspace/setup.py", line 257, in <module>
625.5     setuptools.setup(
625.5   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
625.5     return distutils.core.setup(**attrs)
625.5   File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
625.5     dist.run_commands()
625.5   File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
625.5     self.run_command(cmd)
625.5   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
625.5     cmd_obj.run()
625.5   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
625.5     _build_ext.run(self)
625.5   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
625.5     self.build_extensions()
625.5   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
625.5     build_ext.build_extensions(self)
625.5   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
625.5     self._build_extensions_serial()
625.5   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
625.5     self.build_extension(ext)
625.5   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
625.5     _build_ext.build_extension(self, ext)
625.5   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 529, in build_extension
625.5     objects = self.compiler.compile(sources,
625.5   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
625.5     _write_ninja_file_and_compile_objects(
625.5   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
625.5     _run_ninja_build(
625.5   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
625.5     raise RuntimeError(message) from e
625.5 RuntimeError: Error compiling objects for extension
------
Dockerfile:30
--------------------
  28 |     # max jobs used by Ninja to build extensions
  29 |     ENV MAX_JOBS=$max_jobs
  30 | >>> RUN python3 setup.py build_ext --inplace
  31 |
  32 |     # image to run unit testing suite
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 setup.py build_ext --inplace" did not complete successfully: exit code: 1
```

**Comment by Extremys** [comment]
> Ah I think this is because the build requires GPU VM to compile vLLM from scratch. We might need a Dockerfile with just `pip` installing pre-built binary. Thoughts? @skrider

This is what I was mentioning in the Dockerfile PR thread but I hadn't an anwser around the topic :)  by the way my setup has the nvidia container runtime enabled + RTX 3090 but probably the architecture is too old or doesn't support all stuff compared to the A10G I presume.

**Comment by samos123** [comment]
I created a vLLM docker image for the openai endpoint that can be used as a reference example: https://github.com/substratusai/vllm-docker

It's been tested with K8s as well

**Comment by skrider** [comment]
This is very strange. Potentially try building under WSL? If I had to guess, docker is pulling the windows base image for cuda-devel, which is probably different from the x86 linux base image this dockerfile is tested on, causing the torch extensions to be built with a different compiler. Regardless, docker does not expose the GPU during the build process, so it shouldn't be because of that.

**Comment by Extremys** [comment]
> This is very strange. Potentially try building under WSL? If I had to guess, docker is pulling the windows base image for cuda-devel, which is probably different from the x86 linux base image this dockerfile is tested on, causing the torch extensions to be built with a different compiler. Regardless, docker does not expose the GPU during the build process, so it shouldn't be because of that.

I agree with your analysis, I'm not sure to have the possibility to build under WSL without messing up my current docker installation. If you have resources to share it's welcome.
