### ISSUE TITLE
Docker build fails due to CUDA version mismatch

### ISSUE THREAD

**Issue by ekg** [vllm-project/vllm#1597]
I attempted to build vllm with docker, using this command:

```
docker build -t vllm-v0.2.1-8efe23f .
```

But it fails like this:

```
------
 > [build 6/6] RUN python3 setup.py build_ext --inplace:
2.168 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
2.192 running build_ext
2.229 Traceback (most recent call last):
2.229   File "/workspace/setup.py", line 257, in <module>
2.229     setuptools.setup(
2.229   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
2.229     return distutils.core.setup(**attrs)
2.229   File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
2.229     dist.run_commands()
2.229   File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands 
2.229     self.run_command(cmd)
2.229   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
2.229     cmd_obj.run()
2.229   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
2.230     _build_ext.run(self)
2.230   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
2.230     self.build_extensions()
2.230   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 525, in build_extensions
2.230     _check_cuda_version(compiler_name, compiler_version)
2.230   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
2.230     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
2.230 RuntimeError: 
2.230 The detected CUDA version (11.8) mismatches the version that was used to compile
2.230 PyTorch (12.1). Please make sure to use the same CUDA versions.
2.230 
```

Am I correctly understanding that this means there is a CUDA version mismatch within the system being built by docker? I notice that 12.1 support has just landed. Could there be a mismatch with the current dockerfile? Is this build being tested with CI?

**Comment by jaesuny** [comment]
https://github.com/vllm-project/vllm/issues/129#issuecomment-1805088950
> Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
