### ISSUE TITLE
RuntimeError: CUDA error: out of memory with llama-2-13b-chat-hf model on A100 with vllm 0.2.1.post1 version

### ISSUE THREAD

**Issue by yaliqin** [vllm-project/vllm#1614]
Hi team, I tried below code on vm with A100 which fastchat and DeepSpeed can both server  the same model 
```
from vllm import LLM, SamplingParams
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
prompts = [
    "What's the advantage of DeepSpeed",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
llm = LLM(model="llama-2-13b-chat-hf")
outputs = llm.generate(prompts, sampling_params)

```
I met the error below,

```
Traceback (most recent call last):
  File "/home/yalqin/deepspeed_mii/test-vllm.py", line 11, in <module>
    llm = LLM(model="llama-2-13b-chat-hf")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 231, in from_engine_args
    engine = cls(*engine_configs,
             ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 142, in _init_workers
    self._run_workers(
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
    output = executor(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/worker.py", line 65, in init_model
    _init_distributed_environment(self.parallel_config, self.rank,
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/worker.py", line 359, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
                                 ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Can anyone help?

**Comment by WoosukKwon** [comment]
Hi @yaliqin, do you mean you are trying to set up both vLLM and DeepSpeed servers on a single GPU? If so, you should configure `gpu_memory_utilization` (by default 0.9) to a lower value like 0.5. This means the vLLM instance will occupy 50% of the GPU memory. However, if the model size itself exceeds the 50% of the GPU memory, you will see errors.

**Comment by SafeyahShemali** [comment]
Hello, 
I am having a similar problem regarding CUDA out of Memory with lama2-13b-hf in GCP. Can anybody help me with it ?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
