### ISSUE TITLE
[Bug] CUBLAS_STATUS_EXECUTION_FAILED when generating bunch of long responses

### ISSUE THREAD

**Issue by wangruohui** [vllm-project/vllm#1672]
I am using vLLM to generate response from ChatGLM2 model. I found that when there are lots of queries and some of them cause the model to output very long responses. The program will raise CUDA error.

In below example, the vLLM model is asked to handle 2000 quries with long response. 

Please note when using the default `max_len` of ChatGLM2 which is 8192, CUDA error are raised. But if we limit the `max_len` to 2048, or decrease the number of prompts, everything works fine.

My env and env variable:
- main branch of vLLM
- torch 2.0.1
- huggingface 4.35
- cuda 12.2
- A100 GPUs
- set CUDA_LAUNCH_BLOCKING to 1

```python
PATH_TO_CHATGLM2_6B = "THUDM/chatglm2-6b"
PATH_TO_CHATGLM2_6B = "chatglm2-6b"  # if model repo are cloned or linked here

def test_vllm(prompts, max_tokens):
    from vllm import LLM, SamplingParams

    llm = LLM(
        model=PATH_TO_CHATGLM2_6B,
        tokenizer=PATH_TO_CHATGLM2_6B,
        trust_remote_code=True,
        tensor_parallel_size=1,
    )
    sampling_params = SamplingParams(n=1, temperature=0.0, max_tokens=max_tokens)

    for i, p in enumerate(prompts):
        p = llm.get_tokenizer().build_prompt(p)
        prompts[i] = p

    responses = llm.generate(prompts, sampling_params=sampling_params)

    def process_response(response):
        response = response.strip()
        response = response.replace("[[训练时间]]", "2023年")
        return response

    # print(responses)
    for i, response in enumerate(responses):
        response = process_response(response.outputs[0].text)
        # print(repr(response))

if __name__ == "__main__":
    # Since the tensor parallel group can be initialized only once, one has to comment out other tests and run only a single test. 
    print("Test 1")
    test_vllm(prompts[:100], max_tokens=8192)  # works fine, prompts[-100:] works fine too
    print("Test 2")
    test_vllm(prompts, max_tokens=2048)  # works fine
    print("Test 3")
    test_vllm(prompts, max_tokens=8192)  # CUDA Error as below
```

Outputs from terminal (some paths are hidden):
```
$ python models/test_vllm.py 
INFO 11-15 15:37:54 llm_engine.py:72] Initializing an LLM engine with config: model='chatglm2-6b', tokenizer='chatglm2-6b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
WARNING 11-15 15:37:54 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 11-15 15:38:10 llm_engine.py:207] # GPU blocks: 130569, # CPU blocks: 9362
Processed prompts:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 1978/2000 [08:38<07:06, 19.39s/it]Traceback (most recent call last):
  File "$HOME/$PROJECT/test_vllm.py", line 65, in <module>
    test_vllm(prompts)  #
  File "$HOME/$PROJECT/test_vllm.py", line 40, in test_vllm
    
  File "$HOME/vllm/vllm/entrypoints/llm.py", line 157, in generate
    return self._run_engine(use_tqdm)
  File "$HOME/vllm/vllm/entrypoints/llm.py", line 177, in _run_engine
    step_outputs = self.llm_engine.step()
  File "$HOME/vllm/vllm/engine/llm_engine.py", line 562, in step
    output = self._run_workers(
  File "$HOME/vllm/vllm/engine/llm_engine.py", line 700, in _run_workers
    output = executor(*args, **kwargs)
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "$HOME/vllm/vllm/worker/worker.py", line 370, in execute_model
    output = self.model(
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "$HOME/vllm/vllm/model_executor/models/chatglm.py", line 335, in forward
    hidden_states = self.transformer(input_ids, positions, kv_caches,
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "$HOME/vllm/vllm/model_executor/models/chatglm.py", line 307, in forward
    hidden_states = self.encoder(
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "$HOME/vllm/vllm/model_executor/models/chatglm.py", line 261, in forward
    hidden_states = layer(
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "$HOME/vllm/vllm/model_executor/models/chatglm.py", line 197, in forward
    attention_output = self.self_attention(
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "$HOME/vllm/vllm/model_executor/models/chatglm.py", line 107, in forward
    attn_output, _ = self.dense(context_layer)
  File "$HOME/miniconda3/envs/pt2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "$HOME/vllm/vllm/model_executor/parallel_utils/layers.py", line 291, in forward
    output_parallel = self.apply_weights(input_parallel)
  File "$HOME/vllm/vllm/model_executor/parallel_utils/layers.py", line 266, in apply_weights
    return F.linear(x, self.weight)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
Processed prompts:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 1978/2000 [09:01<00:06,  3.66it/s]
```

**Comment by simon-mo** [comment]
This looks like the `dense` layer's forward call run out of memory. vLLM performs memory profiling ahead of time but it seems the max_len is misconfigured by default.
