### ISSUE TITLE
Crash with `--tensor-parallel-size` in the docker container

### ISSUE THREAD

**Issue by tanliboy** [vllm-project/vllm#1710]
I build the docker image from the master and ran into this error while serving 13B model in the docker container.

```
(base) ubuntu@ip-10-217-30-221:~$ docker run --runtime nvidia --gpus all \
>    -p 8000:8000 \
>    -v <my_local_model_path>:/mnt/model/ \
>     vllm:latest \
>    --host 0.0.0.0 \
>    --model="/mnt/model/" \
>    --tensor-parallel-size 2
WARNING 11-18 03:39:14 config.py:128] None quantization is not fully optimized yet. The speed can be slower than non-quantized models.
2023-11-18 03:39:16,283 WARNING services.py:1996 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-11-18 03:39:16,440 INFO worker.py:1673 -- Started a local Ray instance.
INFO 11-18 03:39:17 llm_engine.py:72] Initializing an LLM engine with config: model='/mnt/model/', tokenizer='/mnt/model/', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, seed=0)
(RayWorker pid=1916) *** SIGBUS received at time=1700278768 on cpu 2 ***
(RayWorker pid=1916) PC: @     0x7fb50a96c200  (unknown)  (unknown)
(RayWorker pid=1916)     @     0x7fb50a80d520       1600  (unknown)
(RayWorker pid=1916)     @ 0x38752d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=1916) [2023-11-18 03:39:28,956 E 1916 2236] logging.cc:361: *** SIGBUS received at time=1700278768 on cpu 2 ***
(RayWorker pid=1916) [2023-11-18 03:39:28,959 E 1916 2236] logging.cc:361: PC: @     0x7fb50a96c200  (unknown)  (unknown)
(RayWorker pid=1916) [2023-11-18 03:39:28,959 E 1916 2236] logging.cc:361:     @     0x7fb50a80d520       1600  (unknown)
(RayWorker pid=1916) [2023-11-18 03:39:28,962 E 1916 2236] logging.cc:361:     @ 0x38752d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=1916) Fatal Python error: Bus error
(RayWorker pid=1916)
(RayWorker pid=1916)
(RayWorker pid=1916) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, uvloop.loop, ray._raylet, charset_normalizer.md, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, sentencepiece._sentencepiece, pyarrow.lib, pyarrow._hdfsio, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, pyarrow._parquet, pyarrow._json (total: 101)
(RayWorker pid=1915) PC: @     0x7fd2faa87a37  (unknown)  ncclShmOpen()
(RayWorker pid=1915) [2023-11-18 03:39:29,019 E 1915 2235] logging.cc:361: PC: @     0x7fd2faa87a37  (unknown)  ncclShmOpen()
2023-11-18 03:39:59,250 WARNING worker.py:2074 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff148befecb0ef8c406444c96301000000 Worker ID: 612005cedeef0e14edcfce010ff1f26c025499a83cf5976034fcea8c Node ID: bde02f7526cc02e79b95007ee82adb5047efa8852a955a6d4d5bc114 Worker IP address: 172.17.0.2 Worker port: 38745 Worker PID: 1915 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/api_server.py", line 80, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 269, in __init__
  ```

On the other hand, the below works well with the released vllm lib.
```
python -m vllm.entrypoints.api_server  --model /home/ubuntu/models/tanliboy/CodeLlama-13b-Instruct-call-graph-v1 --tensor-parallel-size 2
```

**Comment by simon-mo** [comment]
Try `--shm-size=10gb` or smaller? The `ncclShmOpen` error indicates that torch wasn't able allocate shared memory for nccl.

**Comment by tanliboy** [comment]
Thanks for the suggestion, @simon-mo !
