### ISSUE TITLE
ChatGLM3-6B  AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'

### ISSUE THREAD

**Issue by ilas-zzk** [vllm-project/vllm#1713]
Traceback (most recent call last):
  File "/home/imcp/ChatGlm3/vllm_test.py", line 11, in <module>
    llm = LLM(model="./model", trust_remote_code=True)
  File "/home/imcp/anaconda3/envs/glm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/imcp/anaconda3/envs/glm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 231, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/imcp/anaconda3/envs/glm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 96, in __init__
    self._verify_args()
  File "/home/imcp/anaconda3/envs/glm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 187, in _verify_args
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/home/imcp/anaconda3/envs/glm/lib/python3.10/site-packages/vllm/config.py", line 128, in verify_with_parallel_config
    total_num_hidden_layers = self.hf_config.num_hidden_layers
  File "/home/imcp/anaconda3/envs/glm/lib/python3.10/site-packages/transformers/configuration_utils.py", line 262, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'

**Comment by WoosukKwon** [comment]
Hi @ilas-zzk, I believe this error is fixed in the new version of vLLM (v0.2.2), which was just released. Please try it again with the new version and re-open the issue if the error persists.

**Comment by zhaozhaoxia** [comment]
> Hi @ilas-zzk, I believe this error is fixed in the new version of vLLM (v0.2.2), which was just released. Please try it again with the new version and re-open the issue if the error persists.

v 0.2.2 需要的CUDA版本最低是多少？哪里可以看到不同版本需要的基本CUDA配置信息
安装　v 0.2.2以后，torch版本也会升级到2.1.2+cu121，不太支持．　有支持11.1版本的吗？
