### ISSUE TITLE
How to install vllm in NVIDIA offcial images correctly?

### ISSUE THREAD

**Issue by unsw-luopan** [vllm-project/vllm#1781]
I am using the offical images built by NVIDIA: nvcr.io/nvidia/pytorch:23.10-py3. This image has pre-build torch 2.1.0a0+32f93b1.
Then I run the contrainer and use  "pip install vllm", but this command will uninstall the pre-build pytorch 2.1.0a0+32f93b1 and re-install  torch 2.1.0 which lead to the following error when I use vllm in fschat:
 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/vllm_worker.py", line 21, in <module>
    from fastchat.serve.model_worker import (
  File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 18, in <module>
    from fastchat.model.model_adapter import (
  File "/usr/local/lib/python3.10/dist-packages/fastchat/model/__init__.py", line 1, in <module>
    from fastchat.model.model_adapter import (
  File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 15, in <module>
    import accelerate
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 36, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.10/dist-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py", line 139, in <module>
    from .launch import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/launch.py", line 32, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/other.py", line 32, in <module>
    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/__init__.py", line 6, in <module>
    from .layernorm_linear import LayerNormLinear
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/module/layernorm_linear.py", line 15, in <module>
    from .. import cpp_extensions as tex
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/cpp_extensions/__init__.py", line 6, in <module>
    from transformer_engine_extensions import *
ImportError: /usr/local/lib/python3.10/dist-packages/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

 I also try to install vllm by  source, I remove pyproject.toml and run "pip install -e .", but the pre-build torch still uninstalled.
Attempting uninstall: torch
    Found existing installation: torch 2.1.0a0+32f93b1
    Uninstalling torch-2.1.0a0+32f93b1:
      Successfully uninstalled torch-2.1.0a0+32f93b1

So how to install vllm in Nvidia offical images? By the way, the machine is offline and can only use "pip install" from limited pypi source. So I cant rebuild torch in the container.

**Comment by unsw-luopan** [comment]
@Juelianqvq Thank you for your advice, the error message change to:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/vllm_worker.py", line 21, in <module>
    from fastchat.serve.model_worker import (
  File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 18, in <module>
    from fastchat.model.model_adapter import (
  File "/usr/local/lib/python3.10/dist-packages/fastchat/model/__init__.py", line 1, in <module>
    from fastchat.model.model_adapter import (
  File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 18, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1273, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Does this error come from the re-installed torch?

**Comment by frankxyy** [comment]
@Juelianqvq may be use 23.09?
