### ISSUE TITLE
Install vLLM with CUDA 11.8 run api_server failed

### ISSUE THREAD

**Issue by candowu** [vllm-project/vllm#1813]
install vLLM with CUDA 11.8 by running:
# Install vLLM with CUDA 11.8.
# Replace `cp310` with your Python version (e.g., `cp38`, `cp39`, `cp311`).
pip install https://github.com/vllm-project/vllm/releases/download/v0.2.2/vllm-0.2.2+cu118-cp310-cp310-manylinux1_x86_64.whl

# Re-install PyTorch with CUDA 11.8.
pip uninstall torch -y
pip install torch --upgrade --index-url https://download.pytorch.org/whl/cu118

pip list:
Package                   Version
------------------------- ------------
aiosignal                 1.3.1
anyio                     3.7.1
argcomplete               3.1.6
attrs                     23.1.0
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
einops                    0.7.0
exceptiongroup            1.2.0
fastapi                   0.104.1
filelock                  3.13.1
frozenlist                1.4.0
fsspec                    2023.10.0
h11                       0.14.0
httptools                 0.6.1
huggingface-hub           0.19.4
idna                      3.6
Jinja2                    3.1.2
jsonschema                4.20.0
jsonschema-specifications 2023.11.1
MarkupSafe                2.1.3
mpmath                    1.3.0
msgpack                   1.0.7
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.2
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
packaging                 23.2
pandas                    2.1.3
pip                       23.3.1
pipx                      1.2.1
protobuf                  4.25.1
psutil                    5.9.6
pyarrow                   14.0.1
pydantic                  1.10.13
python-dateutil           2.8.2
python-dotenv             1.0.0
pytz                      2023.3.post1
PyYAML                    6.0.1
ray                       2.8.0
referencing               0.31.0
regex                     2023.10.3
requests                  2.31.0
rpds-py                   0.13.1
safetensors               0.4.1
sentencepiece             0.1.99
setuptools                68.0.0
six                       1.16.0
sniffio                   1.3.0
starlette                 0.27.0
sympy                     1.12
tokenizers                0.15.0
torch                     2.1.0+cu118
tqdm                      4.66.1
transformers              4.35.2
triton                    2.1.0
typing_extensions         4.8.0
tzdata                    2023.3
urllib3                   2.1.0
userpath                  1.9.1
uvicorn                   0.24.0.post1
uvloop                    0.19.0
vllm                      0.2.2+cu118
watchfiles                0.21.0
websockets                12.0
wheel                     0.41.2
xformers                  0.0.22.post7

run api_server：
python -m vllm.entrypoints.api_server \
   --model="01ai/Yi-34B-Chat-4bits" \
   --revision="v1.1.8" \
   --trust-remote-code

WARNING 11-28 21:04:20 config.py:140] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 11-28 21:04:20 llm_engine.py:72] Initializing an LLM engine with config: model='candowu/modelscope/01ai/Yi-34B-Chat-4bits', tokenizer='candowu/modelscope/01ai/Yi-34B-Chat-4bits', tokenizer_mode=auto, revision=v1.1.8, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Traceback (most recent call last):
  File "miniconda3/envs/vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "miniconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/api_server.py", line 80, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 305, in _init_engine
    return engine_class(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 113, in __init__
    self._init_cache()
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 193, in _init_cache
    num_blocks = self._run_workers(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
    output = executor(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 111, in profile_num_available_blocks
    self.model(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 295, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 261, in forward
    hidden_states, residual = layer(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 209, in forward
    hidden_states = self.self_attn(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 154, in forward
    attn_output = self.attn(positions, q, k, v, k_cache, v_cache,
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 355, in forward
    return super().forward(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 250, in forward
    self.multi_query_kv_attention(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 105, in multi_query_kv_attention
    out = xops.memory_efficient_attention_forward(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 244, in memory_efficient_attention_forward
    return _memory_efficient_attention_forward(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 341, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/flash.py", line 400, in apply
    out, softmax_lse, rng_state = cls.OPERATOR(
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
  File "miniconda3/envs/vllm/lib/python3.10/site-packages/xformers/ops/fmha/flash.py", line 117, in _flash_fwd
    ) = _C_flashattention.varlen_fwd(
RuntimeError: CUDA error: CUDA driver version is insufficient for CUDA runtime version
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by WoosukKwon** [comment]
Hi @candowu, as shown in the error message, it seems your NVIDIA driver is too old. Please consider upgrading the driver.

**Comment by candowu** [comment]
> Hi @candowu, as shown in the error message, it seems your NVIDIA driver is too old. Please consider upgrading the driver.

 NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8  

i think, NVIDIA driver is not too old.

**Comment by Pzeyang** [comment]
Hi @candowu, 
I also encountered the same error,  have you solved it now

**Comment by Serenagirl** [comment]
same error，and my vllm0.3.2 on arm，cuda11.8+520.61.05，torch2.1.2，Tesla t4 now get：
no openator found for memory_efficient_attention_forward
[rank0]:     xFormers wasn't build with CUDA support
[rank0]:     requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
