### ISSUE TITLE
when use awq for qwen and tensor_parallel_size is 2, input size got error.

### ISSUE THREAD

**Issue by enbacoo** [vllm-project/vllm#1816]
File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 70, in init_model
    self.model = get_model(self.model_config)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 90, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 243, in __init__
    self.transformer = QWenModel(config, linear_method)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 199, in __init__
    self.h = nn.ModuleList([
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 200, in <listcomp>
    QWenBlock(config, linear_method)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 151, in __init__
    self.mlp = QWenMLP(config.hidden_size,
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 51, in __init__
    self.c_proj = RowParallelLinear(intermediate_size,
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 485, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/awq.py", line 84, in create_weights
    raise ValueError(
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.

maybe qwen model  is "intermediate_size": 27392，get input size is 6848 and AWQConfig(weight_bits=4, group_size=128, zero_point=True)
 

<br class="Apple-interchange-newline">

**Comment by WoosukKwon** [comment]
Hi @enbacoo, we found this bug after releasing v0.2.2. The bug was fixed by #1731. Please [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source) until the next release. Sorry for the inconvenience.

**Comment by enbacoo** [comment]
> Hi @enbacoo, we found this bug after releasing v0.2.2. The bug was fixed by #1731. Please [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source) until the next release. Sorry for the inconvenience.

I use newest vllm source code and pip install from source，this bug still exist. Please use https://huggingface.co/TheBloke/Qwen-14B-Chat-AWQ this model for test.

ERROR:    Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/home/minfeng.mf/model_server/model_server_workers.py", line 28, in startup_event
    model = QwenVLLM(model_path,
  File "/home/minfeng.mf/model_server/qwen.py", line 53, in __init__
    super().__init__(model_path, model_name, **kwargs)
  File "/home/minfeng.mf/model_server/inference.py", line 194, in __init__
    self.model = LLM(model=model_path, **model_args)
  File "/home/minfeng.mf/tools/vllm/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/minfeng.mf/tools/vllm/vllm/engine/llm_engine.py", line 243, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/minfeng.mf/tools/vllm/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers_ray(placement_group)
  File "/home/minfeng.mf/tools/vllm/vllm/engine/llm_engine.py", line 191, in _init_workers_ray
    self._run_workers(
  File "/home/minfeng.mf/tools/vllm/vllm/engine/llm_engine.py", line 737, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/home/minfeng.mf/tools/vllm/vllm/engine/llm_engine.py", line 714, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/vllm/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::RayWorker.execute_method() (pid=81299, ip=172.22.43.105, actor_id=a80afdd5a05834e353b03aa801000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7fab7d9a2650>)
  File "/home/minfeng.mf/tools/vllm/vllm/engine/ray_utils.py", line 31, in execute_method
    return executor(*args, **kwargs)
  File "/home/minfeng.mf/tools/vllm/vllm/worker/worker.py", line 72, in load_model
    self.model = get_model(self.model_config)
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/model_loader.py", line 91, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/models/qwen.py", line 236, in __init__
    self.transformer = QWenModel(config, linear_method)
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/models/qwen.py", line 195, in __init__
    self.h = nn.ModuleList([
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/models/qwen.py", line 196, in <listcomp>
    QWenBlock(config, linear_method)
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/models/qwen.py", line 147, in __init__
    self.mlp = QWenMLP(config.hidden_size,
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/models/qwen.py", line 47, in __init__
    self.c_proj = RowParallelLinear(intermediate_size,
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/layers/linear.py", line 483, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "/home/minfeng.mf/tools/vllm/vllm/model_executor/layers/quantization/awq.py", line 84, in create_weights
    raise ValueError(
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.

**Comment by enbacoo** [comment]
> Hi @enbacoo, we found this bug after releasing v0.2.2. The bug was fixed by #1731. Please [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source) until the next release. Sorry for the inconvenience.

intermediate_size//quant.gourp_size is not integer， 27392/2/2= 6848 and 6848/128 is not integer，when I use groupsize 64 to quantize，it workers well. I don`t konw how to fix it .

**Comment by tonystz** [comment]
the bug still exists when I build from master  souce code. Any one could suggest me?
