### ISSUE TITLE
Local models cannot be used when the network is not accessible.

### ISSUE THREAD

**Issue by hello-web** [vllm-project/vllm#1824]
2023-11-29 11:34:19 Traceback (most recent call last):
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
2023-11-29 11:34:19     self._validate_conn(conn)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
2023-11-29 11:34:19     conn.connect()
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 642, in connect
2023-11-29 11:34:19     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
2023-11-29 11:34:19     ssl_sock = ssl_wrap_socket(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 470, in ssl_wrap_socket
2023-11-29 11:34:19     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 514, in _ssl_wrap_socket_impl
2023-11-29 11:34:19     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2023-11-29 11:34:19   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
2023-11-29 11:34:19     return self.sslsocket_class._create(
2023-11-29 11:34:19   File "/usr/lib/python3.10/ssl.py", line 1071, in _create
2023-11-29 11:34:19     self.do_handshake()
2023-11-29 11:34:19   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
2023-11-29 11:34:19     self._sslobj.do_handshake()
2023-11-29 11:34:19 ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)
2023-11-29 11:34:19 
2023-11-29 11:34:19 During handling of the above exception, another exception occurred:
2023-11-29 11:34:19 
2023-11-29 11:34:19 Traceback (most recent call last):
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
2023-11-29 11:34:19     response = self._make_request(
2023-11-29 11:34:19 INFO 11-29 03:34:19 api_server.py:638] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, model='TheBloke/Yi-34B-Chat-AWQ', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.95, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
2023-11-29 11:34:19     raise new_e
2023-11-29 11:34:19 urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)
2023-11-29 11:34:19 
2023-11-29 11:34:19 The above exception was the direct cause of the following exception:
2023-11-29 11:34:19 
2023-11-29 11:34:19 Traceback (most recent call last):
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
2023-11-29 11:34:19     resp = conn.urlopen(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
2023-11-29 11:34:19     retries = retries.increment(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
2023-11-29 11:34:19     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2023-11-29 11:34:19 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /TheBloke/Yi-34B-Chat-AWQ/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-11-29 11:34:19 
2023-11-29 11:34:19 During handling of the above exception, another exception occurred:
2023-11-29 11:34:19 
2023-11-29 11:34:19 Traceback (most recent call last):
2023-11-29 11:34:19   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-11-29 11:34:19     return _run_code(code, main_globals, None,
2023-11-29 11:34:19   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2023-11-29 11:34:19     exec(code, run_globals)
2023-11-29 11:34:19   File "/workspace/vllm/entrypoints/openai/api_server.py", line 646, in <module>
2023-11-29 11:34:19     engine = AsyncLLMEngine.from_engine_args(engine_args)
2023-11-29 11:34:19   File "/workspace/vllm/engine/async_llm_engine.py", line 480, in from_engine_args
2023-11-29 11:34:19     engine_configs = engine_args.create_engine_configs()
2023-11-29 11:34:19   File "/workspace/vllm/engine/arg_utils.py", line 187, in create_engine_configs
2023-11-29 11:34:19     model_config = ModelConfig(self.model, self.tokenizer,
2023-11-29 11:34:19   File "/workspace/vllm/config.py", line 91, in __init__
2023-11-29 11:34:19     self.hf_config = get_config(self.model, trust_remote_code, revision)
2023-11-29 11:34:19   File "/workspace/vllm/transformers_utils/config.py", line 23, in get_config
2023-11-29 11:34:19     config = AutoConfig.from_pretrained(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1048, in from_pretrained
2023-11-29 11:34:19     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 622, in get_config_dict
2023-11-29 11:34:19     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 677, in _get_config_dict
2023-11-29 11:34:19     resolved_config_file = cached_file(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 430, in cached_file
2023-11-29 11:34:19     resolved_file = hf_hub_download(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2023-11-29 11:34:19     return fn(*args, **kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
2023-11-29 11:34:19     metadata = get_hf_file_metadata(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2023-11-29 11:34:19     return fn(*args, **kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
2023-11-29 11:34:19     r = _request_wrapper(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
2023-11-29 11:34:19     response = _request_wrapper(
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 425, in _request_wrapper
2023-11-29 11:34:19     response = get_session().request(method=method, url=url, **params)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
2023-11-29 11:34:19     resp = self.send(prep, **send_kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
2023-11-29 11:34:19     r = adapter.send(request, **kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 63, in send
2023-11-29 11:34:19     return super().send(request, *args, **kwargs)
2023-11-29 11:34:19   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 517, in send
2023-11-29 11:34:19     raise SSLError(e, request=request)
2023-11-29 11:34:19 requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /TheBloke/Yi-34B-Chat-AWQ/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))"), '(Request ID: 91b68885-d0ae-4e19-bb51-63855c72ce75)')

**Comment by simon-mo** [comment]
Looks like it can't find config file locally so opt to download?

**Comment by hello-web** [comment]
> Looks like it can't find config file locally so opt to download?

The local model and configuration files already exist. The parameter local_files_only is missing when calling AutoConfig.from_pretrained() in the vllm code, and the local_files_only parameter may also be missing in other code.

**Comment by simon-mo** [comment]
@hello-web great point! Can you help adding this parameter to vLLM?

**Comment by hello-web** [comment]
> @hello-web great point! Can you help adding this parameter to vLLM?

Try adding the local_files_only parameter to all configurations, and find that all configurations of models do not have options related to the Config of transformers aligned. It will be very tricky to fix the normal operation of local models that have been automatically downloaded when the network is inaccessible.

After tracing, it was found that vllm implemented its own local model logic, and configured the --mode parameter of vllm to the path where the model is located to run normally.

**Comment by simon-mo** [comment]
Correct! `--model` parameter dictate which model to use, an argument `--local-files-only` could be useful for EngineArgs neighboring to `--download-dir` https://docs.vllm.ai/en/latest/models/engine_args.html

**Comment by hello-web** [comment]
> Correct! `--model` parameter dictate which model to use, an argument `--local-files-only` could be useful for EngineArgs neighboring to `--download-dir` https://docs.vllm.ai/en/latest/models/engine_args.html

Specifying --download-dir cannot eliminate the error that the local model cannot run when the network is inaccessible.
The correct method is to specify the --model parameter as the full file path of the local model. The internal full name of --model is model_name_or_path. Substituting the path for the model name will work normally. In addition, specifying --model as a path will potentially change the expected name of the model, and the name also needs to be changed to the complete path name when the client accesses it.

**Comment by AIApprentice101** [comment]
Same issue here. It leads to downtime of services when Huggingface Hub is down.

**Comment by hmellor** [comment]
You can use locally downloaded models if you pass the absolute path to the model snapshot to `--model`
