### ISSUE TITLE
awq CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by cdj0311** [vllm-project/vllm#1830]
hi, 

I get an "an illegal memory access was encountered" error when inference [deepseek-coder-33B-base-AWQ](https://huggingface.co/TheBloke/deepseek-coder-33B-base-AWQ),  which is a Llama2 (GQA) architecture model, but the smaller model is fine([deepseek-coder-6.7B-base-AWQ](https://huggingface.co/TheBloke/deepseek-coder-6.7B-base-AWQ)), the relevant information as follows:

## Environment
python==3.8
torch==2.0.1+cu118
transformers==4.34.1
vllm==0.2.2

## Code
````
from vllm import LLM, SamplingParams
import torch

model_path = "deepseek-coder-33b-base-awq"

sampling_params = SamplingParams(temperature=0.0, 
                                      n=1,
                                      use_beam_search=False,
                                      top_p=1, top_k=-1, max_tokens=200, 
                                      skip_special_tokens=False, 
                                      stop_token_ids=stop_token_ids)

llm = LLM(model=model_path, quantization="awq", dtype="auto", gpu_memory_utilization=0.9, swap_space=32)

text = "def quick_sort("
outputs = llm.generate([text], sampling_params)
print(outputs)
````

## Error
````
INFO 11-29 16:37:53 llm_engine.py:72] Initializing an LLM engine with config: model='deepseek-coder-33b-base-awq', tokenizer='deepseek-coder-33b-base-awq', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=65536, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "infer_vllm.py", line 26, in <module>
    llm = LLM(model=ckpt, quantization="awq", dtype="auto", gpu_memory_utilization=0.9, swap_space=32)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/engine/llm_engine.py", line 243, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/engine/llm_engine.py", line 113, in __init__
    self._init_cache()
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/engine/llm_engine.py", line 205, in _init_cache
    num_blocks = self._run_workers(
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/engine/llm_engine.py", line 737, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/engine/llm_engine.py", line 711, in _run_workers_in_batch
    output = executor(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/worker/worker.py", line 113, in profile_num_available_blocks
    self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/model_executor/models/llama.py", line 288, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/model_executor/models/llama.py", line 254, in forward
    hidden_states, residual = layer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/model_executor/models/llama.py", line 216, in forward
    hidden_states = self.mlp(hidden_states)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/model_executor/models/llama.py", line 74, in forward
    gate_up, _ = self.gate_up_proj(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/model_executor/layers/linear.py", line 203, in forward
    output_parallel = self.linear_method.apply_weights(
  File "/home/vllm/build/lib.linux-x86_64-cpython-38/vllm/model_executor/layers/quantization/awq.py", line 154, in apply_weights
    out = ops.awq_gemm(reshaped_x, qweight, scales, qzeros, pack_factor)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
````

**Comment by esmeetu** [comment]
Have you tested other 34b or 33b model?
