### ISSUE TITLE
[Error] "IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes"  when logprobs > 0

### ISSUE THREAD

**Issue by tongyx361** [vllm-project/vllm#1847]
When I use `logprobs > 0`, the `IndexError` occurs after 500~1000 iters.

## Trace

```
Traceback (most recent call last):
  File "/path/to/repo/src/vllm-generate.py", line 179, in <module>
    outputs = llm.generate(
              ^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 157, in generate
    return self._run_engine(use_tqdm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 177, in _run_engine
    step_outputs = self.llm_engine.step()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 562, in step
    output = self._run_workers(
             ^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
    output = executor(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/worker/worker.py", line 370, in execute_model
    output = self.model(
             ^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 297, in forward
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/model_executor/layers/sampler.py", line 96, in forward
    prompt_logprobs, sample_logprobs = _get_logprobs(
                                       ^^^^^^^^^^^^^^
  File "/path/to/conda/env/lib/python3.11/site-packages/vllm/model_executor/layers/sampler.py", line 534, in _get_logprobs
    batched_logprobs_query_result = logprobs[[
                                    ^^^^^^^^^^
IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes [2199], [2171]
```

### `vllm` version

`vllm` version: `0.2.2`

### SamplingParams

```
sampling_params = SamplingParams(n=5, best_of=5, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.3, top_p=0.95, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['Question:', 'Question', 'USER:', 'USER', 'ASSISTANT:', 'ASSISTANT', 'Instruction:', 'Instruction', 'Response:', 'Response', '### Instruction'], ignore_eos=False, max_tokens=4096, logprobs=1, prompt_logprobs=0, skip_special_tokens=True, spaces_between_special_tokens=True)
```

### model

```
model='EleutherAI/llemma_7b', tokenizer='EleutherAI/llemma_7b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=42)
```

**Comment by richardzhuang0412** [comment]
I am having a same issue here but with prompt_logprob > 0 (in fact even when it is 0). Could the team resolve this issue please?

**Comment by thefirebanks** [comment]
Just ran into the same issue with `prompt_logprobs=1`
