### ISSUE TITLE
use cmd : python -m vllm.entrypoints.openai.api_server --model /home/centific/hua-project/models/01ai/Yi-34B-Chat-4bits , RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by hxujal** [vllm-project/vllm#1911]
(vllm) centific@centific-System-Product-Name:~/hua-project/vllm$ python -m vllm.entrypoints.openai.api_server     --model /home/centific/hua-project/models/01ai/Yi-34B-Chat-4bits
INFO 12-04 10:05:22 api_server.py:704] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', model='/home/centific/hua-project/models/01ai/Yi-34B-Chat-4bits', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 12-04 10:05:22 config.py:140] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 12-04 10:05:22 llm_engine.py:72] Initializing an LLM engine with config: model='/home/centific/hua-project/models/01ai/Yi-34B-Chat-4bits', tokenizer='/home/centific/hua-project/models/01ai/Yi-34B-Chat-4bits', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Traceback (most recent call last):
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/centific/hua-project/vllm/vllm/entrypoints/openai/api_server.py", line 714, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/centific/hua-project/vllm/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/centific/hua-project/vllm/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/centific/hua-project/vllm/vllm/engine/async_llm_engine.py", line 305, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/centific/hua-project/vllm/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_cache()
  File "/home/centific/hua-project/vllm/vllm/engine/llm_engine.py", line 203, in _init_cache
    num_blocks = self._run_workers(
  File "/home/centific/hua-project/vllm/vllm/engine/llm_engine.py", line 735, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/home/centific/hua-project/vllm/vllm/engine/llm_engine.py", line 709, in _run_workers_in_batch
    output = executor(*args, **kwargs)
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/centific/hua-project/vllm/vllm/worker/worker.py", line 88, in profile_num_available_blocks
    self.model_runner.profile_run()
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/centific/hua-project/vllm/vllm/worker/model_runner.py", line 318, in profile_run
    self.execute_model(seqs, kv_caches)
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/centific/hua-project/vllm/vllm/worker/model_runner.py", line 285, in execute_model
    output = self.model.sample(
  File "/home/centific/hua-project/vllm/vllm/model_executor/models/llama.py", line 303, in sample
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/centific/hua-project/vllm/vllm/model_executor/layers/sampler.py", line 47, in forward
    logits = _get_logits(hidden_states, embedding, embedding_bias,
  File "/home/centific/hua-project/vllm/vllm/model_executor/layers/sampler.py", line 105, in _get_logits
    logits = torch.matmul(hidden_states, embedding.t())
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by sunshineyg2018** [comment]
Did that work out

**Comment by fml-2020** [comment]
make max-model-len lower or use multiple gpu
