### ISSUE TITLE
ValueError: Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm'].

### ISSUE THREAD

**Issue by EchoShoot** [vllm-project/vllm#1919]
```
Traceback (most recent call last):
  File "/workspace/api/server.py", line 2, in <module>
    from api.models import app, EMBEDDED_MODEL, GENERATE_ENGINE
  File "/workspace/api/models.py", line 144, in <module>
    GENERATE_ENGINE = create_vllm_engine()
  File "/workspace/api/models.py", line 89, in create_vllm_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 480, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/workspace/vllm/engine/arg_utils.py", line 187, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/workspace/vllm/config.py", line 97, in __init__
    self._verify_quantization()
  File "/workspace/vllm/config.py", line 137, in _verify_quantization
    raise ValueError(
ValueError: Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm'].
```

**Comment by RithvikKolla** [comment]
Upgrading vLLM with `pip install vllm -U` worked for me.

**Comment by esmeetu** [comment]
@EchoShoot @nuo-o  GPTQ quantization method has been support from v0.2.6 to latest version (0.3.3).

**Comment by lxohi** [comment]
Just passing by to say, I also encountered this problem. 

In my environment, the issue was due to the vllm version being downgraded by other packages, so I noticed that initially a higher version of vllm was downloaded, but eventually, pip installed a lower version. 

The problem is not with vllm itself.

**Comment by Harryalways317** [comment]
Yes, came here to say, happend the same with lm-eval
