### ISSUE TITLE
Can't load `vllm-openai/v0.2.3` image

### ISSUE THREAD

**Issue by harryjulian** [vllm-project/vllm#1936]
As the title reads, upgraded from v0.2.2 and now getting this error:

```
vllm_1   | RuntimeError: CUDA error: no kernel image is available for execution on the device
vllm_1   | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
vllm_1   | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
vllm_1   | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by simon-mo** [comment]
Can you tell us more about the machine you are running on? What's the output of `nvidia-smi`?

**Comment by zhaofangtao** [comment]
me too.  same version，  same issue.  OS: linux. GPU: P100,   
![f2196975f017def67ff96b3a9a299f1](https://github.com/vllm-project/vllm/assets/117793219/177119f4-23f8-400d-9c87-2f8b35444983)

**Comment by goncalogiga** [comment]
I run into the same problem with Ubuntu 20.04 and A100 GPUs, after upgrading the image to v0.2.3. Here is the full traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 721, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 495, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 112, in __init__
    self._init_cache()
  File "/workspace/vllm/engine/llm_engine.py", line 208, in _init_cache
    num_blocks = self._run_workers(
  File "/workspace/vllm/engine/llm_engine.py", line 750, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/workspace/vllm/engine/llm_engine.py", line 724, in _run_workers_in_batch
    output = executor(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/vllm/worker/worker.py", line 88, in profile_num_available_blocks
    self.model_runner.profile_run()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/vllm/worker/model_runner.py", line 321, in profile_run
    self.execute_model(seqs, kv_caches)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/vllm/worker/model_runner.py", line 279, in execute_model
    hidden_states = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/model_executor/models/mistral.py", line 290, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/model_executor/models/mistral.py", line 256, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/model_executor/models/mistral.py", line 206, in forward
    hidden_states = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/model_executor/models/mistral.py", line 150, in forward
    qkv, _ = self.qkv_proj(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/model_executor/layers/linear.py", line 203, in forward
    output_parallel = self.linear_method.apply_weights(
  File "/workspace/vllm/model_executor/layers/linear.py", line 68, in apply_weights
    return F.linear(x, weight, bias)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

And `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   36C    P0    30W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   38C    P0    33W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by harryjulian** [comment]
@simon-mo it was on a g5.2xlarge EC2 instance (1x A10G).

**Comment by EnnoAi** [comment]
Same issue with v0.2.3 and works with v0.2.2

**Comment by simon-mo** [comment]
I think I know the issue, now, fixing soon.

**Comment by goncalogiga** [comment]
Thanks @simon-mo; unfortunately I am still facing the same issue with the A100s

**Comment by simon-mo** [comment]
Please check again. New version pushed. The compiled library should include the latest change:

<details><summary>cuobjdump</summary>
<p>

```
(base) xmo@simon-devbox:~$ cuobjdump _C.cpython-310-x86_64-linux-gnu.so --list-ptx
PTX file    1: _C.cpython-310-x86_64-linux-gnu.1.sm_90.ptx
PTX file    2: _C.cpython-310-x86_64-linux-gnu.2.sm_90.ptx
PTX file    3: _C.cpython-310-x86_64-linux-gnu.3.sm_90.ptx
PTX file    4: _C.cpython-310-x86_64-linux-gnu.4.sm_90.ptx
PTX file    5: _C.cpython-310-x86_64-linux-gnu.5.sm_90.ptx
PTX file    6: _C.cpython-310-x86_64-linux-gnu.6.sm_90.ptx
PTX file    7: _C.cpython-310-x86_64-linux-gnu.7.sm_90.ptx
PTX file    8: _C.cpython-310-x86_64-linux-gnu.8.sm_90.ptx
(base) xmo@simon-devbox:~$ cuobjdump _C.cpython-310-x86_64-linux-gnu.so --list-elf
ELF file    1: _C.cpython-310-x86_64-linux-gnu.1.sm_70.cubin
ELF file    2: _C.cpython-310-x86_64-linux-gnu.2.sm_89.cubin
ELF file    3: _C.cpython-310-x86_64-linux-gnu.3.sm_75.cubin
ELF file    4: _C.cpython-310-x86_64-linux-gnu.4.sm_80.cubin
ELF file    5: _C.cpython-310-x86_64-linux-gnu.5.sm_90.cubin
ELF file    6: _C.cpython-310-x86_64-linux-gnu.6.sm_86.cubin
ELF file    7: _C.cpython-310-x86_64-linux-gnu.7.sm_70.cubin
ELF file    8: _C.cpython-310-x86_64-linux-gnu.8.sm_89.cubin
ELF file    9: _C.cpython-310-x86_64-linux-gnu.9.sm_75.cubin
ELF file   10: _C.cpython-310-x86_64-linux-gnu.10.sm_80.cubin
ELF file   11: _C.cpython-310-x86_64-linux-gnu.11.sm_90.cubin
ELF file   12: _C.cpython-310-x86_64-linux-gnu.12.sm_86.cubin
ELF file   13: _C.cpython-310-x86_64-linux-gnu.13.sm_70.cubin
ELF file   14: _C.cpython-310-x86_64-linux-gnu.14.sm_89.cubin
ELF file   15: _C.cpython-310-x86_64-linux-gnu.15.sm_75.cubin
ELF file   16: _C.cpython-310-x86_64-linux-gnu.16.sm_80.cubin
ELF file   17: _C.cpython-310-x86_64-linux-gnu.17.sm_90.cubin
ELF file   18: _C.cpython-310-x86_64-linux-gnu.18.sm_86.cubin
ELF file   19: _C.cpython-310-x86_64-linux-gnu.19.sm_70.cubin
ELF file   20: _C.cpython-310-x86_64-linux-gnu.20.sm_89.cubin
ELF file   21: _C.cpython-310-x86_64-linux-gnu.21.sm_75.cubin
ELF file   22: _C.cpython-310-x86_64-linux-gnu.22.sm_80.cubin
ELF file   23: _C.cpython-310-x86_64-linux-gnu.23.sm_90.cubin
ELF file   24: _C.cpython-310-x86_64-linux-gnu.24.sm_86.cubin
ELF file   25: _C.cpython-310-x86_64-linux-gnu.25.sm_70.cubin
ELF file   26: _C.cpython-310-x86_64-linux-gnu.26.sm_89.cubin
ELF file   27: _C.cpython-310-x86_64-linux-gnu.27.sm_75.cubin
ELF file   28: _C.cpython-310-x86_64-linux-gnu.28.sm_80.cubin
ELF file   29: _C.cpython-310-x86_64-linux-gnu.29.sm_90.cubin
ELF file   30: _C.cpython-310-x86_64-linux-gnu.30.sm_86.cubin
ELF file   31: _C.cpython-310-x86_64-linux-gnu.31.sm_70.cubin
ELF file   32: _C.cpython-310-x86_64-linux-gnu.32.sm_89.cubin
ELF file   33: _C.cpython-310-x86_64-linux-gnu.33.sm_75.cubin
ELF file   34: _C.cpython-310-x86_64-linux-gnu.34.sm_80.cubin
ELF file   35: _C.cpython-310-x86_64-linux-gnu.35.sm_90.cubin
ELF file   36: _C.cpython-310-x86_64-linux-gnu.36.sm_86.cubin
ELF file   37: _C.cpython-310-x86_64-linux-gnu.37.sm_70.cubin
ELF file   38: _C.cpython-310-x86_64-linux-gnu.38.sm_89.cubin
ELF file   39: _C.cpython-310-x86_64-linux-gnu.39.sm_75.cubin
ELF file   40: _C.cpython-310-x86_64-linux-gnu.40.sm_80.cubin
ELF file   41: _C.cpython-310-x86_64-linux-gnu.41.sm_90.cubin
ELF file   42: _C.cpython-310-x86_64-linux-gnu.42.sm_86.cubin
ELF file   43: _C.cpython-310-x86_64-linux-gnu.43.sm_70.cubin
ELF file   44: _C.cpython-310-x86_64-linux-gnu.44.sm_89.cubin
ELF file   45: _C.cpython-310-x86_64-linux-gnu.45.sm_75.cubin
ELF file   46: _C.cpython-310-x86_64-linux-gnu.46.sm_80.cubin
ELF file   47: _C.cpython-310-x86_64-linux-gnu.47.sm_90.cubin
ELF file   48: _C.cpython-310-x86_64-linux-gnu.48.sm_86.cubin
```


</p>
</details> 

<details><summary>T4 Log</summary>
<p>

```
(base) xmo@instance-2:~$ nvidia-smi
Thu Dec  7 19:30:11 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P0              27W /  70W |  13061MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     25900      C   python3                                   13044MiB |
+---------------------------------------------------------------------------------------+
(base) xmo@instance-2:~$ curl http://localhost:8000/v1/completions  -H "Content-Type: application/json"      -d '{
         "model": "facebook/opt-125m",
         "prompt":"Who won the world series in 2020?",
         "max_tokens": 20,
         "ignore_eos": true
     }'
{"id":"cmpl-f449a17d5fca40c39b807af4c845c19d","object":"text_completion","created":7475,"model":"facebook/opt-125m","choices":[{"index":0,"text":" The chelsea football title\nIt's almost football time again, and now fans have finally got","logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":9,"total_tokens":29,"completion_tokens":20}}

(base) xmo@instance-2:~$ docker run --runtime nvidia --gpus all     -v ~/.cache/huggingface:/root/.cache/huggingface     -p 8000:8000     --env "HUGGING_FACE_HUB_TOKEN=<secret>"     vllm/vllm-openai
INFO 12-07 19:29:45 api_server.py:715] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', model='facebook/opt-125m', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 12-07 19:29:45 llm_engine.py:73] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
INFO 12-07 19:29:51 llm_engine.py:222] # GPU blocks: 22167, # CPU blocks: 7281
WARNING 12-07 19:29:54 api_server.py:115] No chat template provided. Chat API will not work.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO 12-07 19:30:01 async_llm_engine.py:379] Received request cmpl-e35de7de98a04e07974f9fc81974c74a: prompt: 'Who won the world series in 2020?', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], ignore_eos=True, max_tokens=2000, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [2, 12375, 351, 5, 232, 651, 11, 2760, 116].
INFO 12-07 19:30:01 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 12-07 19:30:06 async_llm_engine.py:134] Aborted request cmpl-e35de7de98a04e07974f9fc81974c74a.
INFO 12-07 19:30:19 async_llm_engine.py:379] Received request cmpl-f449a17d5fca40c39b807af4c845c19d: prompt: 'Who won the world series in 2020?', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], ignore_eos=True, max_tokens=20, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [2, 12375, 351, 5, 232, 651, 11, 2760, 116].
INFO 12-07 19:30:19 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 12-07 19:30:19 async_llm_engine.py:111] Finished request cmpl-f449a17d5fca40c39b807af4c845c19d.
INFO:     172.17.0.1:42530 - "POST /v1/completions HTTP/1.1" 200 OK



</p>
</details>

**Comment by simon-mo** [comment]
We will also add the step into our release pipeline so it won't happen again 🙇
