### ISSUE TITLE
Issue with building Docker image

### ISSUE THREAD

**Issue by bengoodenough-ec** [vllm-project/vllm#1989]
```DOCKER_BUILDKIT=1 docker build . --target vllm-openai --tag vllm/vllm-openai --build-arg max_jobs=8```

Outputs: 

```
[+] Building 44.7s (27/29)                                                                                                           docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                                 0.0s
 => => transferring dockerfile: 2.21kB                                                                                                               0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:12.1.0-base-ubuntu22.04                                                                       1.4s
 => [internal] load metadata for docker.io/nvidia/cuda:12.1.0-devel-ubuntu22.04                                                                      1.4s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                                                           0.0s
 => [dev 1/7] FROM docker.io/nvidia/cuda:12.1.0-devel-ubuntu22.04@sha256:e3a8f7b933e77ecee74731198a2a5483e965b585cea2660675cf4bb152237e9b            0.0s
 => [internal] load build context                                                                                                                    0.0s
 => => transferring context: 785.55kB                                                                                                                0.0s
 => [vllm-base 1/5] FROM docker.io/nvidia/cuda:12.1.0-base-ubuntu22.04@sha256:40042016a816cbbe0504dd0a396e7cfc036a8aa43f5694af60dd6f8f87d24e52       0.0s
 => CACHED [dev 2/7] RUN apt-get update -y     && apt-get install -y python3-pip                                                                     0.0s
 => CACHED [dev 3/7] WORKDIR /workspace                                                                                                              0.0s
 => [dev 4/7] COPY requirements.txt requirements.txt                                                                                                 0.0s
 => CACHED [vllm-base 2/5] RUN apt-get update -y     && apt-get install -y python3-pip                                                               0.0s
 => CACHED [vllm-base 3/5] WORKDIR /workspace                                                                                                        0.0s
 => [vllm-base 4/5] COPY requirements.txt requirements.txt                                                                                           0.0s
 => [dev 5/7] RUN --mount=type=cache,target=/root/.cache/pip     pip install -r requirements.txt                                                    37.3s
 => [vllm-base 5/5] RUN --mount=type=cache,target=/root/.cache/pip     pip install -r requirements.txt                                              37.3s
 => [dev 6/7] COPY requirements-dev.txt requirements-dev.txt                                                                                         0.0s
 => [vllm-openai 1/3] RUN --mount=type=cache,target=/root/.cache/pip     pip install accelerate fschat                                               5.4s
 => [dev 7/7] RUN --mount=type=cache,target=/root/.cache/pip     pip install -r requirements-dev.txt                                                 3.6s
 => [build 1/8] COPY requirements-build.txt requirements-build.txt                                                                                   0.2s
 => [build 2/8] RUN --mount=type=cache,target=/root/.cache/pip     pip install -r requirements-build.txt                                             0.8s
 => [build 3/8] COPY csrc csrc                                                                                                                       0.0s
 => [build 4/8] COPY setup.py setup.py                                                                                                               0.0s
 => [build 5/8] COPY requirements.txt requirements.txt                                                                                               0.0s
 => [build 6/8] COPY pyproject.toml pyproject.toml                                                                                                   0.0s
 => [build 7/8] COPY vllm/__init__.py vllm/__init__.py                                                                                               0.0s
 => ERROR [build 8/8] RUN python3 setup.py build_ext --inplace                                                                                       1.3s
------
 > [build 8/8] RUN python3 setup.py build_ext --inplace:
1.043 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
1.062 running build_ext
1.087 Traceback (most recent call last):
1.087   File "/workspace/setup.py", line 208, in <module>
1.087     setuptools.setup(
1.087   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
1.087     return distutils.core.setup(**attrs)
1.087   File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
1.087     dist.run_commands()
1.087   File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
1.088     self.run_command(cmd)
1.088   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
1.088     cmd_obj.run()
1.088   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
1.089     _build_ext.run(self)
1.089   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
1.089     self.build_extensions()
1.089   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 525, in build_extensions
1.089     _check_cuda_version(compiler_name, compiler_version)
1.089   File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 407, in _check_cuda_version
1.089     torch_cuda_version = packaging.version.parse(torch.version.cuda)
1.089   File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
1.089     return Version(version)
1.089   File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
1.089     match = self._regex.search(version)
1.089 TypeError: expected string or bytes-like object
------
Dockerfile:35
--------------------
  33 |     # max jobs used by Ninja to build extensions
  34 |     ENV MAX_JOBS=$max_jobs
  35 | >>> RUN python3 setup.py build_ext --inplace
  36 |     
  37 |     # image to run unit testing suite
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 setup.py build_ext --inplace" did not complete successfully: exit code: 1
```

**Comment by simon-mo** [comment]
Are you running this on a GPU device with NVIDIA docker enabled?

**Comment by bengoodenough-ec** [comment]
I was not aware this was a requirement. Could you point to this requirement in the documentation?
