### ISSUE TITLE
TypeError: PaddedGatherOp.forward() takes 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2017]
I installed from latest main, installed stk, megablocks, latest flash_attn, transformers etc...
And got following error: 
```llm.engine.ray_utils.RayWorkerVllm object at 0x7f1657fe5bd0>)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/worker/worker.py", line 88, in profile_num_available_blocks
    self.model_runner.profile_run()
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 321, in profile_run
    self.execute_model(seqs, kv_caches)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 279, in execute_model
    hidden_states = self.model(
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 488, in forward
    hidden_states = layer(
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 439, in forward
    r = self.block_sparse_moe(self.ffn_norm(h))
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/vllm/model_executor/models/mixtral.py", line 353, in forward
    x = ops.padded_gather(x, indices, bin_ids, bins, padded_bins,
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/stk/backend/autocast.py", line 28, in decorate_fwd
    return fwd(*args, **kwargs)
TypeError: PaddedGatherOp.forward() takes 6 positional arguments but 7 were given
```

_Originally posted by @draganjovanovich in https://github.com/vllm-project/vllm/issues/2011#issuecomment-1849769275_

**Comment by WoosukKwon** [comment]
This issue is because `pip install megabucks` installs `megablocks==0.2.0` which is outdated. Please install the latest megabucks by `pip install git+https://github.com/stanford-futuredata/megablocks.git@v0.5.0`

**Comment by draganjovanovich** [comment]
Ok, thanks, will try now. btw, I also would love to get some bucks("megabucks") via pip install lol

**Comment by WoosukKwon** [comment]
@draganjovanovich Please note that you should use python 3.10 to install megablocks (because of one of its dependencies).

**Comment by draganjovanovich** [comment]
Yes, I am on: Python 3.10.12

**Comment by draganjovanovich** [comment]
Can't install megablocks@0.5.0, I tracked down to that this package is failing to build/install https://github.com/tgale96/grouped_gemm

**Comment by AlpinDale** [comment]
Looks like megablocks 0.5.0 expects `mosaicml-turbo`, but that package doesn't exist. I've submitted an issue for now at [stanford-futuredata/megablocks#51](https://github.com/stanford-futuredata/megablocks/issues/51)

**Comment by tgale96** [comment]
Hi all, we'll fix the original error :) We've been stuck on a non-PyPi version of Triton for the last 6 months which has blocked us from uploading new packages.

I'll respond about the turbo dep on our repo, thanks for filing the issue!

I'm not sure what the grouped GEMM build error is. Could you give us more details on your environment?

**Comment by tgale96** [comment]
The build error you posted [here](https://github.com/vllm-project/vllm/pull/2011#issuecomment-1849809890) is a missing cuTENSOR API that is required for the CUTLASS dependency. I'm not sure why it's missing, I'll have to find a CUDA 12 machine to test on.

In the meantime, grouped GEMM is only needed if you use the `GroupedMLP`. MegaBlocks will work fine without it (using `SparseMLP` for the dMoE layer, which is the default). Same with `turbo` - you can skip the install and as long as you don't enable the quantization features in your `Arguments` object everything should work.

**Comment by draganjovanovich** [comment]
Ok, but I am unable to install the latest megablocks, because it fails with that error.
btw, do you know some easy way of installing it?

**Comment by tgale96** [comment]
You can install with `--ignore-dependencies`. The only packages MegaBlocks needs to run Mixtral is `stanford-stk` and `triton`. If you give me 10m this will be fixed and `pip install megablocks` will be all you need for Mixtral :)

**Comment by draganjovanovich** [comment]
ofc, great!

**Comment by draganjovanovich** [comment]
For anyone trying mixtral with current state of the repo vllm and megablocks:
pip install --no-deps git+https://github.com/stanford-futuredata/megablocks.git 
and use load_format="pt" as with default safetensors it fails with keyerror.

**Comment by vibhuagrawal14** [comment]
I'm installing megablocks while building my docker image, but it fails with the following error:

`Step 7/11 : RUN python3 -m pip install git+https://github.com/stanford-futuredata/megablocks.git@v0.5.0
 ---> Running in 4a566820a3a2
Collecting git+https://github.com/stanford-futuredata/megablocks.git@v0.5.0
  Cloning https://github.com/stanford-futuredata/megablocks.git (to revision v0.5.0) to /tmp/pip-req-build-6zcfn01r
  Running command git clone --filter=blob:none --quiet https://github.com/stanford-futuredata/megablocks.git /tmp/pip-req-build-6zcfn01r
  Running command git checkout -q 04601813b499f4d68a5c9f7f866fbcbb59e44208
  Resolved https://github.com/stanford-futuredata/megablocks.git to commit 04601813b499f4d68a5c9f7f866fbcbb59e44208
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-6zcfn01r/setup.py", line 6, in <module>
          _dc = torch.cuda.get_device_capability()
        File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 435, in get_device_capability
          prop = get_device_properties(device)
        File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 449, in get_device_properties
          _lazy_init()  # will define _get_device_properties
        File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
          torch._C._cuda_init()
      RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c python3 -m pip install git+https://github.com/stanford-futuredata/megablocks.git@v0.5.0' returned a non-zero code: 1`

Would be very helpful if someone can point me to the right way to install this!

**Comment by tgale96** [comment]
Re: https://github.com/vllm-project/vllm/issues/2017#issuecomment-1850441060

Ok, I've updated our PyPi packages so you should be able to just `pip install megablocks` to run Mixtral with vLLM.

Re: https://github.com/vllm-project/vllm/issues/2017#issuecomment-1850448385

Are you on a GPU machine? Looks like you don't have a GPU available and its failing trying to build our custom kernels.
