### ISSUE TITLE
vLLM Docker container fails with Mixtral 8x7b

### ISSUE THREAD

**Issue by abatilo** [vllm-project/vllm#2026]
I built the `Dockerfile` in the root of the repo, on commit `https://github.com/vllm-project/vllm/commit/4ff0203987ff100eaaad69f0a8abf7ed821e3a0a`, then pushed the container and tried to run it using the following args:

```
    - --host
    - 0.0.0.0
    - --model
    - mistralai/Mixtral-8x7B-Instruct-v0.1
    - --tensor-parallel-size
    - "2"
```

When I run the container, this is what I see
```
INFO 12-11 17:57:51 api_server.py:719] args: Namespace(host='0.0.0.0', port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', model='mistralai/Mixtral-8x7B-Instruct-v0.1', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
config.json: 100%|██████████| 720/720 [00:00<00:00, 4.57MB/s]
2023-12-11 17:57:53,085 WARNING services.py:1996 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67104768 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-12-11 17:57:54,229 INFO worker.py:1673 -- Started a local Ray instance.
INFO 12-11 17:57:55 llm_engine.py:73] Initializing an LLM engine with config: model='mistralai/Mixtral-8x7B-Instruct-v0.1', tokenizer='mistralai/Mixtral-8x7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, seed=0)
tokenizer_config.json: 100%|██████████| 1.46k/1.46k [00:00<00:00, 8.47MB/s]
tokenizer.model: 100%|██████████| 493k/493k [00:00<00:00, 10.2MB/s]
tokenizer.json: 100%|██████████| 1.80M/1.80M [00:00<00:00, 22.7MB/s]
special_tokens_map.json: 100%|██████████| 72.0/72.0 [00:00<00:00, 442kB/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 729, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 495, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 107, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/engine/llm_engine.py", line 156, in _init_workers_ray
    from vllm.worker.worker import Worker
  File "/workspace/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import set_random_seed
  File "/workspace/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/workspace/vllm/model_executor/model_loader.py", line 10, in <module>
    from vllm.model_executor.models import *
  File "/workspace/vllm/model_executor/models/__init__.py", line 13, in <module>
    from vllm.model_executor.models.mixtral import MixtralForCausalLM
  File "/workspace/vllm/model_executor/models/mixtral.py", line 151, in <module>
    class BlockSparseMoE(nn.Module):
  File "/workspace/vllm/model_executor/models/mixtral.py", line 254, in BlockSparseMoE
    padded_bins: torch.Tensor) -> stk.Matrix:
NameError: name 'stk' is not defined. Did you mean: 'str'?
MegaBlocks not found, please see https://github.com/stanford-futuredata/megablocks/. Note that MegaBlocks depends on mosaicml-turbo, which only supports python 3.10.
STK not found: please see https://github.com/stanford-futuredata/stk
```

**Comment by 0-hero** [comment]
Can you please check now. It should be fixed. requirements.txt is updated

**Comment by abatilo** [comment]
@0-hero I saw that the change got reverted. It looks like I should wait for #2027?

**Comment by 0-hero** [comment]
As a temporary fix you can add megablocks to the requirements.txt file, while #2027 is merged
