### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by yixuantt** [vllm-project/vllm#2053]
Hi, thanks for this impressive project.
I use vllm, which works well for llama quantized by awq. However, when I changed to falcon-40b (awq), it did not work. 
The version is the newest, and I serve this model online. I tried to use the hf transformer to generate a response, which performed normally without any error.

```
2023-12-12 19:38:39 | ERROR | stderr | Traceback (most recent call last):
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-12-12 19:38:39 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/runpy.py", line 87, in _run_code
2023-12-12 19:38:39 | ERROR | stderr |     exec(code, run_globals)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/fastchat/serve/vllm_worker.py", line 243, in <module>
2023-12-12 19:38:39 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 495, in from_engine_args
2023-12-12 19:38:39 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
2023-12-12 19:38:39 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
2023-12-12 19:38:39 | ERROR | stderr |     return engine_class(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 112, in __init__
2023-12-12 19:38:39 | ERROR | stderr |     self._init_cache()
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 208, in _init_cache
2023-12-12 19:38:39 | ERROR | stderr |     num_blocks = self._run_workers(
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 750, in _run_workers
2023-12-12 19:38:39 | ERROR | stderr |     self._run_workers_in_batch(workers, method, *args, **kwargs))
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 724, in _run_workers_in_batch
2023-12-12 19:38:39 | ERROR | stderr |     output = executor(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-12 19:38:39 | ERROR | stderr |     return func(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/worker/worker.py", line 88, in profile_num_available_blocks
2023-12-12 19:38:39 | ERROR | stderr |     self.model_runner.profile_run()
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-12 19:38:39 | ERROR | stderr |     return func(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 321, in profile_run
2023-12-12 19:38:39 | ERROR | stderr |     self.execute_model(seqs, kv_caches)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-12 19:38:39 | ERROR | stderr |     return func(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 288, in execute_model
2023-12-12 19:38:39 | ERROR | stderr |     output = self.model.sample(
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/model_executor/models/falcon.py", line 408, in sample
2023-12-12 19:38:39 | ERROR | stderr |     next_tokens = self.sampler(self.lm_head.weight, hidden_states,
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-12-12 19:38:39 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-12-12 19:38:39 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 93, in forward
2023-12-12 19:38:39 | ERROR | stderr |     sample_results = _sample(probs, logprobs, sampling_metadata)
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 501, in _sample
2023-12-12 19:38:39 | ERROR | stderr |     sample_results = _random_sample(seq_groups, is_prompts,
2023-12-12 19:38:39 | ERROR | stderr |   File "/root/miniconda3/envs/fastchat/lib/python3.9/site-packages/vllm/model_executor/layers/sampler.py", line 396, in _random_sample
2023-12-12 19:38:39 | ERROR | stderr |     random_samples = torch.multinomial(probs,
2023-12-12 19:38:39 | ERROR | stderr | RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by zhaotyer** [comment]
I meet this error, when I use Qwen-7b-chat
Error log is:
Traceback (most recent call last):
  File "/workspace/QwenChat-7b/./atom/1/model_copy.py", line 920, in vllm_response_thread
    async for request_output in results_generator:
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 151, in generate
    raise e
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 148, in generate
    await self.engine_step(request_id)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 74, in engine_step
    request_outputs = self.engine.step()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 313, in step
    output = self._run_workers(
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 470, in _run_workers
    output = executor(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 293, in execute_model
    output = self.model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/qwen.py", line 240, in forward
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/sampler.py", line 89, in forward
    return _sample(probs, logprobs, input_metadata)
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/sampler.py", line 391, in _sample
    next_token_ids = _sample_from_prompt(prob, sampling_params)
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/sampler.py", line 305, in _sample_from_prompt
    next_token_ids = torch.multinomial(prob,
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

vllm==0.23

**Comment by shiqingzhangCSU** [comment]
use beamserch
