### ISSUE TITLE
Runtime AsyncEngineDeadError: "This should never happen! Please open an issue on Github."

### ISSUE THREAD

**Issue by tanliboy** [vllm-project/vllm#2067]
Report this per the request in the error message.

I got this error on A100 without distributed inference.  I can consistently repro with this query, and other queries work fine.

```
INFO 12-12 20:00:59 async_llm_engine.py:379] Received request cmpl-e044ab19e61a4b0ba256c262c7975267: prompt: 'How to make Sushi?', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], ignore_eos=False, max_tokens=1024, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [1, 1602, 298, 1038, 318, 1426, 28710, 28804].
INFO 12-12 20:00:59 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 12-12 20:01:00 async_llm_engine.py:134] Aborted request cmpl-e044ab19e61a4b0ba256c262c7975267.
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7fde9c3c1c60>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7fde9033d690>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7fde9c3c1c60>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7fde9033d690>)>
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 338, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/workspace/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 663, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 158, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/workspace/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/workspace/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO:     172.17.0.1:59150 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 338, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/workspace/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 663, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 158, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 633, in create_completion
    async for res in result_generator:
  File "/workspace/vllm/engine/async_llm_engine.py", line 444, in generate
    raise e
  File "/workspace/vllm/engine/async_llm_engine.py", line 438, in generate
    async for request_output in stream:
  File "/workspace/vllm/engine/async_llm_engine.py", line 70, in __anext__
    raise result
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/workspace/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/workspace/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO 12-12 20:01:49 async_llm_engine.py:379] Received request cmpl-3d50fdb26fd04317bd02e381a4d46ab9: prompt: 'How to make Sushi?', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], ignore_eos=False, max_tokens=100, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [1, 1602, 298, 1038, 318, 1426, 28710, 28804].
Future exception was never retrieved
future: <Future finished exception=TypeError("argument 'tokens': 'NoneType' object cannot be converted to 'PyString'")>
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 338, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/workspace/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 663, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 158, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'
INFO 12-12 20:01:49 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
```

**Comment by godefroi** [comment]
I see a very similar error:

```
myuser@myhostname:~$ sudo docker run --rm --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=my_hf_token" -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model ericzzz/falcon-rw-1b-chat
INFO 12-13 17:44:04 api_server.py:719] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', model='ericzzz/falcon-rw-1b-chat', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
config.json: 100%|██████████| 754/754 [00:00<00:00, 5.99MB/s]
INFO 12-13 17:44:04 llm_engine.py:73] Initializing an LLM engine with config: model='ericzzz/falcon-rw-1b-chat', tokenizer='ericzzz/falcon-rw-1b-chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
tokenizer_config.json: 100%|██████████| 910/910 [00:00<00:00, 7.73MB/s]
vocab.json: 100%|██████████| 798k/798k [00:00<00:00, 6.23MB/s]
merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 31.7MB/s]
tokenizer.json: 100%|██████████| 2.11M/2.11M [00:00<00:00, 26.0MB/s]
special_tokens_map.json: 100%|██████████| 441/441 [00:00<00:00, 1.13MB/s]
model.safetensors: 100%|██████████| 2.62G/2.62G [01:05<00:00, 40.3MB/s]
INFO 12-13 17:45:39 llm_engine.py:222] # GPU blocks: 699, # CPU blocks: 1365
WARNING 12-13 17:45:39 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 12-13 17:45:39 api_server.py:113] Using default chat template:
INFO 12-13 17:45:39 api_server.py:113] {% for message in messages %}{% if loop.index > 1 and loop.previtem['role'] != 'assistant' %}{{ ' ' }}{% endif %}{% if message['role'] == 'system' %}{{ '[SYS] ' + message['content'].strip() }}{% elif message['role'] == 'user' %}{{ '[INST] ' + message['content'].strip() }}{% elif message['role'] == 'assistant' %}{{ '[RESP] '  + message['content'] + eos_token }}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ ' [RESP] ' }}{% endif %}
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.17.0.1:56062 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
^[[AINFO 12-13 17:47:16 async_llm_engine.py:379] Received request cmpl-050cc5ddb0424413896a8cf2edf1403b: prompt: '[SYS] You are a friendly assistant. [INST] What is san francisco? [RESP] ', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.2, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], ignore_eos=False, max_tokens=2024, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [58, 50, 16309, 60, 921, 389, 257, 8030, 8796, 13, 685, 38604, 60, 1867, 318, 5336, 46754, 4861, 30, 685, 19535, 47, 60, 220].
INFO 12-13 17:47:16 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 12-13 17:47:21 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 51.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 12-13 17:47:26 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 50.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.9%, CPU KV cache usage: 0.0%
INFO 12-13 17:47:31 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 49.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 7.2%, CPU KV cache usage: 0.0%
INFO 12-13 17:47:36 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 48.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 9.3%, CPU KV cache usage: 0.0%
INFO 12-13 17:47:41 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 47.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 11.3%, CPU KV cache usage: 0.0%
INFO 12-13 17:47:43 async_llm_engine.py:134] Aborted request cmpl-050cc5ddb0424413896a8cf2edf1403b.
INFO:     172.17.0.1:36150 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7efe9adc9c60>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7eff3e3c5e10>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7efe9adc9c60>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7eff3e3c5e10>)>
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 338, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/workspace/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 663, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 158, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/workspace/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/workspace/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/workspace/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/workspace/vllm/engine/async_llm_engine.py", line 338, in engine_step
    request_outputs = await self.engine.step_async()
  File "/workspace/vllm/engine/async_llm_engine.py", line 199, in step_async
    return self._process_model_outputs(output, scheduler_outputs) + ignored
  File "/workspace/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
    self._process_sequence_group_outputs(seq_group, outputs)
  File "/workspace/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
    self._decode_sequence(seq, seq_group.sampling_params)
  File "/workspace/vllm/engine/llm_engine.py", line 663, in _decode_sequence
    read_offset) = detokenize_incrementally(
  File "/workspace/vllm/transformers_utils/tokenizer.py", line 158, in detokenize_incrementally
    new_text = tokenizer.convert_tokens_to_string(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
    return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 430, in create_chat_completion
    return await completion_full_generator()
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 376, in completion_full_generator
    async for res in result_generator:
  File "/workspace/vllm/engine/async_llm_engine.py", line 444, in generate
    raise e
  File "/workspace/vllm/engine/async_llm_engine.py", line 438, in generate
    async for request_output in stream:
  File "/workspace/vllm/engine/async_llm_engine.py", line 70, in __anext__
    raise result
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/workspace/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/workspace/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
```
