### ISSUE TITLE
How to install from source with CUDA 11.8 instead of 12.1?

### ISSUE THREAD

**Issue by alpayariyak** [vllm-project/vllm#2072]

**Comment by hirovi** [comment]
1. After cloning this repo, remove the `.toml` file
2. Go to `setup.py` file and set cuda version to 11.8, like;
`MAIN_CUDA_VERSION = "11.8"`
3. Then install `xformers` for cuda 11.8, with `pip install -U xformers --index-url https://download.pytorch.org/whl/cu118`
4. Comment out or remove, torch and xformers from the `requirements.txt`
5. You might get an error of `packaging` module not found, install with `pip install packaging`
6. Now you can install vLLM from source with CUDA 11.8 by simply running `pip install -e .`

**Comment by bjoernpl** [comment]
Does it have to be this difficult? It was fine to install before the latest update.

Also, for me since I'm on `torch==2.0.1` using `pip install xformers==0.0.22` was necessary.

**Comment by janelu9** [comment]
> 6\. pip install -e .

vllm==0.2.6 build error

```
      Traceback (most recent call last):
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/e/nlp/vllm/setup.py", line 296, in <module>
          setuptools.setup(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run          _build_ext.run(self)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
  Running setup.py clean for vllm
Failed to build vllm
ERROR: Failed to build one or more wheels
```

**Comment by janelu9** [comment]
> 1. After cloning this repo, remove the `.toml` file
> 2. Go to `setup.py` file and set cuda version to 11.8, like;
>    `MAIN_CUDA_VERSION = "11.8"`
> 3. Then install `xformers` for cuda 11.8, with;
>    `pip install -U xformers --index-url https://download.pytorch.org/whl/cu118`
> 4. Comment out or remove, torch and xformers from the `requirements.txt`
> 5. You might get an error of `packaging` module not found, install with `pip install packaging`
> 6. Now you can install vLLM from source with CUDA 11.8 by simply running `pip install -e .`

vllm==0.2.6 build error

```
      Traceback (most recent call last):
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/e/nlp/vllm/setup.py", line 296, in <module>
          setuptools.setup(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run          _build_ext.run(self)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
  Running setup.py clean for vllm
Failed to build vllm
ERROR: Failed to build one or more wheels
```

**Comment by janelu9** [comment]
> > 1. After cloning this repo, remove the `.toml` file
> > 2. Go to `setup.py` file and set cuda version to 11.8, like;
> >    `MAIN_CUDA_VERSION = "11.8"`
> > 3. Then install `xformers` for cuda 11.8, with;
> >    `pip install -U xformers --index-url https://download.pytorch.org/whl/cu118`
> > 4. Comment out or remove, torch and xformers from the `requirements.txt`
> > 5. You might get an error of `packaging` module not found, install with `pip install packaging`
> > 6. Now you can install vLLM from source with CUDA 11.8 by simply running `pip install -e .`
> 
> vllm==0.2.6 build error
> 
> ```
>       Traceback (most recent call last):
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
>           subprocess.run(
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/subprocess.py", line 571, in run
>           raise CalledProcessError(retcode, process.args,
>       subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
>       The above exception was the direct cause of the following exception:
> 
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/mnt/e/nlp/vllm/setup.py", line 296, in <module>
>           setuptools.setup(
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
>           return distutils.core.setup(**attrs)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
>           return run_commands(dist)
>                  ^^^^^^^^^^^^^^^^^^
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
>           dist.run_commands()
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
>           super().run_command(command)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
>           self.run_command("build")
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
>           super().run_command(command)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
>           super().run_command(command)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 88, in run          _build_ext.run(self)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
>           self.build_extensions()
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
>           build_ext.build_extensions(self)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
>           self._build_extensions_serial()
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
>           self.build_extension(ext)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
>           _build_ext.build_extension(self, ext)
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
>           objects = self.compiler.compile(
>                     ^^^^^^^^^^^^^^^^^^^^^^
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
>           _write_ninja_file_and_compile_objects(
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
>           _run_ninja_build(
>         File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
>           raise RuntimeError(message) from e
>       RuntimeError: Error compiling objects for extension
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for vllm
>   Running setup.py clean for vllm
> Failed to build vllm
> ERROR: Failed to build one or more wheels
> ```

it's OK when I uninstall vllm at first

**Comment by skt7** [comment]
> 1. After cloning this repo, remove the `.toml` file
> 2. Go to `setup.py` file and set cuda version to 11.8, like;
>    `MAIN_CUDA_VERSION = "11.8"`
> 3. Then install `xformers` for cuda 11.8, with;
>    `pip install -U xformers --index-url https://download.pytorch.org/whl/cu118`
> 4. Comment out or remove, torch and xformers from the `requirements.txt`
> 5. You might get an error of `packaging` module not found, install with `pip install packaging`
> 6. Now you can install vLLM from source with CUDA 11.8 by simply running `pip install -e .`

@hirovi thanks, this helps. Following what is on the official docs, doesn't work, this should be updated there.
