### ISSUE TITLE
命令行启动vllm服务，openai调用报错；vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly

### ISSUE THREAD

**Issue by xxm1668** [vllm-project/vllm#2099]
Traceback (most recent call last):
File "/home/house365ai/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "/home/house365ai/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
return await self.app(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
await super().__call__(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
await self.middleware_stack(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
raise exc
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
await self.app(scope, receive, _send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
await self.app(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
await self.asgi_callable(scope, receive, wrapped_send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
raise exc
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
await self.app(scope, receive, sender)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
raise e
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
await self.app(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
await route.handle(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
await self.app(scope, receive, send)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
response = await func(request)
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
raw_response = await run_endpoint_function(
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
return await dependant.call(**values)
File "/home/house365ai/xxm/new/vllm4/vllm/entrypoints/openai/api_server.py", line 430, in create_chat_completion
return await completion_full_generator()
File "/home/house365ai/xxm/new/vllm4/vllm/entrypoints/openai/api_server.py", line 376, in completion_full_generator
async for res in result_generator:
File "/home/house365ai/xxm/new/vllm4/vllm/engine/async_llm_engine.py", line 444, in generate
raise e
File "/home/house365ai/xxm/new/vllm4/vllm/engine/async_llm_engine.py", line 438, in generate
async for request_output in stream:
File "/home/house365ai/xxm/new/vllm4/vllm/engine/async_llm_engine.py", line 70, in __anext__
raise result
File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
File "/home/house365ai/xxm/new/vllm4/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
raise exc
File "/home/house365ai/xxm/new/vllm4/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

**Comment by houhailun** [comment]
+1

**Comment by xxm1668** [comment]
@houhailun 我的主要是没有结束符，而且会产生None，然后报错；换了模型就可以了
