### ISSUE TITLE
argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

### ISSUE THREAD

**Issue by xxm1668** [vllm-project/vllm#2104]
sampling_params = SamplingParams(temperature=0.2)
正常运行
sampling_params = SamplingParams(temperature=0.2, frequency_penalty=1.2, presence_penalty=1.2, top_p=0.95,
top_k=1, stop=["</s>", '<|im_end|>', '<|endoftext|>'], max_tokens=4096)
报错信息：
Traceback (most recent call last):
File "/home/house365ai/xxm/new/vllm4/demo.py", line 33, in <module>
outputs = llm.generate(prompts, sampling_params)
File "/home/house365ai/xxm/new/vllm4/vllm/entrypoints/llm.py", line 153, in generate
return self._run_engine(use_tqdm)
File "/home/house365ai/xxm/new/vllm4/vllm/entrypoints/llm.py", line 173, in _run_engine
step_outputs = self.llm_engine.step()
File "/home/house365ai/xxm/new/vllm4/vllm/engine/llm_engine.py", line 585, in step
return self._process_model_outputs(output, scheduler_outputs)
File "/home/house365ai/xxm/new/vllm4/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
self._process_sequence_group_outputs(seq_group, outputs)
File "/home/house365ai/xxm/new/vllm4/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
self._decode_sequence(seq, seq_group.sampling_params)
File "/home/house365ai/xxm/new/vllm4/vllm/engine/llm_engine.py", line 663, in _decode_sequence
read_offset) = detokenize_incrementally(
File "/home/house365ai/xxm/new/vllm4/vllm/transformers_utils/tokenizer.py", line 158, in detokenize_incrementally
new_text = tokenizer.convert_tokens_to_string(
File "/home/house365ai/.conda/envs/vllm11/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 612, in convert_tokens_to_string
return self.backend_tokenizer.decoder.decode(tokens)
TypeError: argument 'tokens': 'NoneType' object cannot be converted to 'PyString'

**Comment by chenxuantt** [comment]
请问解决了吗

**Comment by xxm1668** [comment]
应该降低transformer的版本就可以了
