### ISSUE TITLE
paged_attention_v1(): incompatible function arguments.

### ISSUE THREAD

**Issue by d0lphin** [vllm-project/vllm#2106]
I start the server with the following command:

`python -m vllm.entrypoints.api_server`

output:

```
python -m vllm.entrypoints.api_server
INFO 12-14 11:38:07 llm_engine.py:73] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
INFO 12-14 11:38:11 llm_engine.py:222] # GPU blocks: 22817, # CPU blocks: 7281
INFO:     Started server process [142586]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

Then i query it with:

```
curl http://localhost:8000/generate \
    -d '{
        "prompt": "San Francisco is a",
        "use_beam_search": true,
        "n": 4,
        "temperature": 0
    }'

```
Error on the server:

```
INFO 12-14 11:30:02 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f116cf1ae80>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f115d4a2f90>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f116cf1ae80>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f115d4a2f90>)>
Traceback (most recent call last):
  File "/home/abalogh/work/contrib/vllm/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish

```

```
TypeError: paged_attention_v1(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: float, arg6: torch.Tensor, arg7: torch.Tensor, arg8: int, arg9: int, arg10: Optional[torch.Tensor]) -> None

Invoked with: tensor([[[-4.7109, -1.9668, -5.9336,  ..., -6.3086, -1.2490, -4.9648],

```
```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/abalogh/work/contrib/vllm/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/home/abalogh/work/contrib/vllm/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO 12-14 11:30:02 async_llm_engine.py:134] Aborted request 67b26f1bed07420eb247b3119b810d1e.
```

list of installed packages:
```

pip list
Package                   Version
------------------------- ------------
aioprometheus             23.3.0
aiosignal                 1.3.1
anyio                     3.7.1
attrs                     23.1.0
brotlipy                  0.7.0
certifi                   2023.11.17
cffi                      1.15.1
charset-normalizer        2.0.4
click                     8.1.7
cryptography              41.0.3
einops                    0.7.0
fastapi                   0.103.1
filelock                  3.9.0
frozenlist                1.4.0
fsspec                    2023.9.1
gmpy2                     2.1.2
h11                       0.14.0
httptools                 0.6.1
huggingface-hub           0.19.4
idna                      3.4
Jinja2                    3.1.2
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
MarkupSafe                2.1.1
megablocks                0.5.0
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mpmath                    1.3.0
msgpack                   1.0.6
networkx                  3.1
ninja                     1.11.1
numpy                     1.25.2
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
orjson                    3.9.10
packaging                 23.1
pandas                    2.1.3
Pillow                    9.4.0
pip                       23.2.1
protobuf                  4.24.3
psutil                    5.9.5
pyarrow                   14.0.1
pycparser                 2.21
pydantic                  1.10.13
pyOpenSSL                 23.2.0
PySocks                   1.7.1
python-dateutil           2.8.2
python-dotenv             1.0.0
pytz                      2023.3.post1
PyYAML                    6.0.1
quantile-python           1.1
ray                       2.7.0
referencing               0.30.2
regex                     2023.8.8
requests                  2.31.0
rpds-py                   0.10.3
safetensors               0.3.3
sentencepiece             0.1.99
setuptools                68.0.0
six                       1.16.0
sniffio                   1.3.0
stanford-stk              0.0.6
starlette                 0.27.0
sympy                     1.11.1
tokenizers                0.15.0
torch                     2.1.1
torchaudio                2.0.2
torchvision               0.15.2
tqdm                      4.66.1
transformers              4.36.1
triton                    2.1.0
typing_extensions         4.7.1
tzdata                    2023.3
urllib3                   1.26.16
uvicorn                   0.23.2
uvloop                    0.19.0
vllm                      0.2.5
watchfiles                0.21.0
websockets                12.0
wheel                     0.38.4
xformers                  0.0.23
```

**Comment by michaelfeil** [comment]
This is because of the use of `paged_attention_v1`, with its newly introduced `num_key_value_heads: int` as `arg4`. Before it was the head_mapping, a list / tensor.

This can be closed, installing the most recent version should fix it.
