### ISSUE TITLE
AMD MI210 successfully installed vllm but undefined symbol _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

### ISSUE THREAD

**Issue by Jackyan1999** [vllm-project/vllm#2156]
`(vllm_rocm) [yys@v100 examples]$ python offline_inference.py 
/home/yys/anaconda_install/envs/vllm_rocm/lib/python3.8/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "offline_inference.py", line 1, in <module>
    from vllm import LLM, SamplingParams
  File "/home/yys/anaconda_install/envs/vllm_rocm/lib/python3.8/site-packages/vllm-0.2.4+rocm573-py3.8-linux-x86_64.egg/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/home/yys/anaconda_install/envs/vllm_rocm/lib/python3.8/site-packages/vllm-0.2.4+rocm573-py3.8-linux-x86_64.egg/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
  File "/home/yys/anaconda_install/envs/vllm_rocm/lib/python3.8/site-packages/vllm-0.2.4+rocm573-py3.8-linux-x86_64.egg/vllm/config.py", line 9, in <module>
    from vllm.utils import get_cpu_memory, is_hip
  File "/home/yys/anaconda_install/envs/vllm_rocm/lib/python3.8/site-packages/vllm-0.2.4+rocm573-py3.8-linux-x86_64.egg/vllm/utils.py", line 8, in <module>
    from vllm._C import cuda_utils
ImportError: /home/yys/anaconda_install/envs/vllm_rocm/lib/python3.8/site-packages/vllm-0.2.4+rocm573-py3.8-linux-x86_64.egg/vllm/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv`

following the amd_installation guide....... dont know why

**Comment by Jackyan1999** [comment]
gcc 11 has this problem..... gcc 10.4 is OK

**Comment by Jackyan1999** [comment]
down....
