### ISSUE TITLE
Error running Mixtral in tensor-parallel 2

### ISSUE THREAD

**Issue by jbohnslav** [vllm-project/vllm#2181]
AWQ mixtral-instruct downloaded from here: https://huggingface.co/ybelkada/Mixtral-8x7B-Instruct-v0.1-AWQ

Command: 

```bash
 docker run --gpus all \
   -p 8000:8000  \
   --shm-size=12gb \
   vllm/vllm-openai \
   --model /models/Mixtral-8x7B-Instruct-v0.1-AWQ  \
   -tp 2 
```

Result:
```bash
INFO 12-18 19:16:27 api_server.py:727] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', 
ssl_keyfile=None, ssl_certfile=None, model='/models/Mixtral-8x7B-Instruct-v0.1-AWQ', tokenizer=None, revision=None, 
tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', 
max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, 
block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, 
max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, 
engine_use_ray=False, disable_log_requests=False, max_log_len=None)                     
WARNING 12-18 19:16:27 config.py:175] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.                                 
                                                     
2023-12-18 19:16:28,984 INFO worker.py:1673 -- Started a local Ray instance.      
                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                           File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main                    
return _run_code(code, main_globals, None,                                                                                                                                                                               File "/usr/lib/python3.10/runpy.py", line 86, in _run_code                                                                                                                                                                   exec(code, run_globals)                                                                                                                                                                                                  File "/workspace/vllm/entrypoints/openai/api_server.py", line 737, in <module>                                                                                                                                               engine = AsyncLLMEngine.from_engine_args(engine_args)                           
File "/workspace/vllm/engine/async_llm_engine.py", line 493, in from_engine_args    
distributed_init_method, placement_group = initialize_cluster(                                                                                                                                                           File "/workspace/vllm/engine/ray_utils.py", line 105, in initialize_cluster            
raise ValueError(                                                                                                                                                                                                      
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
```

**Comment by miko7879** [comment]
How many GPUs are on your device?

**Comment by jbohnslav** [comment]
2 GPUs, both visible in `nvidia-smi`.

**Comment by miko7879** [comment]
@jbohnslav are you using CUDA 12.1 or 11.8? We are having no issues with vLLM 0.2.5 and CUDA 11.8

**Comment by miko7879** [comment]
Oh one thing is we are not running thr quantized model so not sure if my suggestion is applicable, my apologies

**Comment by jbohnslav** [comment]
Cuda 12.1 for the record

**Comment by WoosukKwon** [comment]
I think this should be Ray issue. It seems Ray did not detect 2 GPUs on you machine for some reason.

**Comment by jbohnslav** [comment]
Hmm, I added a debug statement-- looks like ray finds zero GPUs. 

This leads me to think it might be due to running in Windows with WSL2. Here's a long ray issue: https://github.com/ray-project/ray/issues/33798

**Comment by mlinmg** [comment]
I ubuntu 22.04, cuda 12.1 torch 1.2.1 same issue

**Comment by francescov1** [comment]
Seeing this as well with Mixtral. Tried downgrading CUDA to 11.8 but still running into it.

**Comment by epolewski** [comment]
I'm hitting this with both CUDA 11.8 and 12.1. Documented more in[ this thread](https://github.com/vllm-project/vllm/issues/1116). Spent days on it. Ended up [writing my own batching API to load models across GPUs](https://github.com/epolewski/EricLLM) out of frustration. I dug through the code and I was not able to find the issue. I'm also running WSL2. Tried a Docker image with the same issue (using WSL2 back-end though I suspect, I selected the option to use WSL in Docker for Windows).

**Comment by sam-h-bean** [comment]
@hmellor why did you close this? people want to run tensor parallel models with vLLM on top of Ray data for processing batches. Why are you not planning to support this?

**Comment by hmellor** [comment]
If you close an issue as duplicate/stale/not planned it will always appear as not planned in the fred. This issue was closed as stale.

Also, the issue was opened because tensor parallel was not working correctly with Mixtral AWQ, I have tested this use case myself and it does work now.

**Comment by sam-h-bean** [comment]
I thought possibly related to https://github.com/vllm-project/vllm/issues/3190
