### ISSUE TITLE
vllm.engine.async_llm_engine.AsyncEngineDeadError

### ISSUE THREAD

**Issue by joindn** [vllm-project/vllm#2197]
2023-12-19 18:11:16 | ERROR | stderr | 
2023-12-19 18:11:16 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-12-19 18:11:16 | ERROR | stderr | 
2023-12-19 18:11:16 | ERROR | stderr | Traceback (most recent call last):
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-12-19 18:11:16 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     raise exc
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     raise exc
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     raise e
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-12-19 18:11:16 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
2023-12-19 18:11:16 | ERROR | stderr |     await response(scope, receive, send)
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
2023-12-19 18:11:16 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-12-19 18:11:16 | ERROR | stderr |     raise exceptions[0]
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
2023-12-19 18:11:16 | ERROR | stderr |     await func()
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
2023-12-19 18:11:16 | ERROR | stderr |     async for chunk in self.body_iterator:
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/miniconda3/envs/pytorch21/lib/python3.10/site-packages/fastchat/serve/vllm_worker.py", line 113, in generate_stream
2023-12-19 18:11:16 | ERROR | stderr |     async for request_output in results_generator:
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/vllm-gptq/vllm/engine/async_llm_engine.py", line 435, in generate
2023-12-19 18:11:16 | ERROR | stderr |     raise e
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/vllm-gptq/vllm/engine/async_llm_engine.py", line 429, in generate
2023-12-19 18:11:16 | ERROR | stderr |     async for request_output in stream:
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/vllm-gptq/vllm/engine/async_llm_engine.py", line 70, in __anext__
2023-12-19 18:11:16 | ERROR | stderr |     raise result
2023-12-19 18:11:16 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/vllm-gptq/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
2023-12-19 18:11:16 | ERROR | stderr |     raise exc
2023-12-19 18:11:16 | ERROR | stderr |   File "/root/vllm-gptq/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
2023-12-19 18:11:16 | ERROR | stderr |     raise AsyncEngineDeadError(
2023-12-19 18:11:16 | ERROR | stderr | vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

**Comment by yhyu13** [comment]
https://github.com/vllm-project/vllm/issues/2239 duplicated
