### ISSUE TITLE
CUDA11.6 not support?

### ISSUE THREAD

**Issue by Arsmart1** [vllm-project/vllm#220]
(base) C:\Users\a>pip install vllm
Collecting vllm
  Using cached vllm-0.1.1.tar.gz (83 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'
      Traceback (most recent call last):
        File "D:\software_loc\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\software_loc\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\software_loc\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\hzy\AppData\Local\Temp\pip-build-env-67chdc7b\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\hzy\AppData\Local\Temp\pip-build-env-67chdc7b\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\hzy\AppData\Local\Temp\pip-build-env-67chdc7b\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
      RuntimeError: Cannot find CUDA at CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6. CUDA must be available in order to build the package.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Aswesome** [comment]
Vllm does not support windows, if you want to use windows, please use WSL.
