### ISSUE TITLE
Mixtral weight loading with manually loaded weights does not work

### ISSUE THREAD

**Issue by jbohnslav** [vllm-project/vllm#2211]
Hi, I downloaded this model manually with `git lfs`. https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ

I tried to start an OpenAI server pointing to this directory
```bash
python3 -m vllm.entrypoints.openai.api_server \                                                                                                                                                  --model /models/Mixtral-8x7B-Instruct-v0.1-GPTQ -tp 2 --dtype float16 
```

Error:
```bash
INFO 12-20 03:39:53 api_server.py:727] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, model='/models/Mixtral-8x7B-Instruct-v0.1-GPTQ', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='float16', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 12-20 03:39:53 config.py:463] Casting torch.bfloat16 to torch.float16.
WARNING 12-20 03:39:53 config.py:175] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
WARNING 12-20 03:39:53 config.py:187] gptq does not support CUDA graph yet. Disabling CUDA graph.
2023-12-20 03:39:54,822 INFO worker.py:1673 -- Started a local Ray instance.
INFO 12-20 03:39:55 llm_engine.py:73] Initializing an LLM engine with config: model='/models/Mixtral-8x7B-Instruct-v0.1-GPTQ', tokenizer='/models/Mixtral-8x7B-Instruct-v0.1-GPTQ', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=gptq, enforce_eager=True, seed=0)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 737, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 496, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/engine/llm_engine.py", line 195, in _init_workers_ray
    self._run_workers(
  File "/workspace/vllm/engine/llm_engine.py", line 763, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/workspace/vllm/engine/llm_engine.py", line 740, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::RayWorkerVllm.execute_method() (pid=1334, ip=172.17.0.3, actor_id=be6ee56f722fcf13a3803e5c01000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7ff197109a80>)
  File "/workspace/vllm/engine/ray_utils.py", line 31, in execute_method
    return executor(*args, **kwargs)
  File "/workspace/vllm/worker/worker.py", line 79, in load_model
    self.model_runner.load_model()
  File "/workspace/vllm/worker/model_runner.py", line 60, in load_model
    self.model = get_model(self.model_config)
  File "/workspace/vllm/model_executor/model_loader.py", line 72, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/workspace/vllm/model_executor/models/mixtral.py", line 412, in load_weights
    weight_loader(param, loaded_weight)
  File "/workspace/vllm/model_executor/weight_utils.py", line 270, in default_weight_loader
    assert param.size() == loaded_weight.size()
AssertionError
```

However, when I run specifying a name, and let vLLM do the downloading, it works. 
```bash
python3 -m vllm.entrypoints.openai.api_server \                                                                                                                                                 
--model TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ -tp 2 --dtype float16 --download-dir /models 
```

I have a working version, so it's not that big a deal, but I don't want to re-download all of my models.

**Comment by hmellor** [comment]
You must specify the snapshot `/models/Mixtral-8x7B-Instruct-v0.1-GPTQ/snapshots/123456789...`

**Comment by airedwin** [comment]
did you fix this? i have the same error with the same model downloaded with huggingface-cli
