### ISSUE TITLE
when deploy wizardcoder-34b-gptq in vllm 0.2.6,  I encounter "500 Internal Server Error" ,details are as follows：

### ISSUE THREAD

**Issue by meichangsu1** [vllm-project/vllm#2234]
Traceback (most recent call last):  File "/workspace/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish  task.result()  File "/workspace/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop  has_requests_in_progress = await self.engine_step()  File "/workspace/vllm/engine/async_llm_engine.py", line 338, in engine_step  request_outputs = await self.engine.step_async()  File "/workspace/vllm/engine/async_llm_engine.py", line 191, in step_async  output = await self._run_workers_async(  File "/workspace/vllm/engine/async_llm_engine.py", line 227, in _run_workers_async  assert output == other_output  AssertionError

**Comment by llmrainer** [comment]
when i use qwen-7b-chat-int4 with vllm 0.2.6, it told me that  << The NVIDIA driver on your system is too old (found version 11080) >>  So have you met this kind of question?

**Comment by coffin5257** [comment]
I have the same question with deepseep-coder-33b-instruct-awq and vllm 0.2.3

**Comment by meichangsu1** [comment]
> when i use qwen-7b-chat-int4 with vllm 0.2.6, it told me that << The NVIDIA driver on your system is too old (found version 11080) >> So have you met this kind of question?

I fixed by using  the vllm image https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html
