### ISSUE TITLE
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github.

### ISSUE THREAD

**Issue by trevdoz** [vllm-project/vllm#2239]
Setup:
Machine - GCP n1-standard-32
Accelerators - 4 NVIDIA TESLA T4
vllm Version: 0.2.6

Stack Trace:
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7fa959d6dab0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7fa9ab1abd60>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7fa959d6dab0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7fa9ab1abd60>)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
    task.result()
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 338, in engine_step
    request_outputs = await self.engine.step_async()
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 191, in step_async
    output = await self._run_workers_async(
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 227, in _run_workers_async
    assert output == other_output
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO 12-21 23:20:26 async_llm_engine.py:134] Aborted request 5b565d60cc87455185b369709347f4f9.

**Comment by meichangsu1** [comment]
the same with you

**Comment by yhyu13** [comment]
Are you trying to launch async vllm engine task in side a already running uvloop instances (or anyother python asyncio loop)?

I remember having this issue when trying to create async vllm engine object in my web app already managed by uvloop.

Basically, it is due to recursive asyncio loop issue

**Comment by trevdoz** [comment]
Yes I believe it's because I was hitting the open ai compatible server endpoint with 'curl' in the same terminal session immediately after I received a response. If I opened up another connection or waited for a few seconds (could be due to TIMEOUT var that is set in AsyncLLMEngine.py) then the error wouldn't appear
