### ISSUE TITLE
llama 70b load failed on A100 4*40960MiB

### ISSUE THREAD

**Issue by ChristineSeven** [vllm-project/vllm#2269]
Shell Got Params: --port 10088 --model /data/bigqgpt --dtype float16 --tensor-parallel-size 4 --max_tokens 4096 --trust-remote-code --gpu-memory-utilization 0.98 
CUDA Support: True : 4 devices
WARNING 12-26 07:06:20 config.py:406] Casting torch.bfloat16 to torch.float16.
2023-12-26 07:06:23,383	INFO worker.py:1673 -- Started a local Ray instance.
INFO 12-26 07:06:25 llm_engine.py:73] Initializing an LLM engine with config: model='/data/bigqgpt', tokenizer='/data/bigqgpt', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, quantization=None, seed=0)
2023-12-26 07:10:19,486	WARNING worker.py:2074 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffb493243e1b84395062c7e05501000000 Worker ID: 3d5e5fbf6f64171ddf74fc4bf55565e2151534f6de6822f4e422ac65 Node ID: 0744a0e2a85b4ef9650f6c943dd3ac3e25f1f79eae5046d740302221 Worker IP address:  Worker port: 22778 Worker PID: 7953 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/data/service/qgpt_common_service.py", line 408, in <module>
    model = AsyncLLMEngine.from_engine_args(engine_args,res)
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 498, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 107, in __init__
    self._init_workers_ray(placement_group)
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 194, in _init_workers_ray
    self._run_workers(
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 750, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 727, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/worker.py", line 2565, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: RayWorkerVllm
	actor_id: b493243e1b84395062c7e05501000000
	pid: 7953
	namespace: 31ab2f10-fc05-4acf-a665-d9bff98f9dae
	ip: 
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors

**Comment by DefTruth** [comment]
same error

**Comment by youkaichao** [comment]
You can try to lower `--gpu-memory-utilization`, with e.g. `0.8` . Too high memory utilization surely has the risk of OOM.
