### ISSUE TITLE
mixtral fails to load, pytorch cuda errror

### ISSUE THREAD

**Issue by dr3s** [vllm-project/vllm#2272]
It says report to pytorch but I can't help thinking it's either user error or incompat with mixtral somehow

Error:
```
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 182, in __init__
torch.empty(self.ffn_dim_per_partition * self.num_experts,
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_device.py", line 77, in __torch_function__
return func(*args, **kwargs)
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.
```

Full error:
```
INFO 12-26 15:52:49 api_server.py:719] args: Namespace(host='0.0.0.0', port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', model='mistralai/Mixtral-8x7B-Instruct-v0.1', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir='/.cache/huggingface/hub', load_format='pt', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
config.json:   0%|          | 0.00/720 [00:00<?, ?B/s]
config.json: 100%|██████████| 720/720 [00:00<00:00, 3.46MB/s]
INFO 12-26 15:52:49 llm_engine.py:73] Initializing an LLM engine with config: model='mistralai/Mixtral-8x7B-Instruct-v0.1', tokenizer='mistralai/Mixtral-8x7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir='/.cache/huggingface/hub', load_format=pt, tensor_parallel_size=1, quantization=None, seed=0)
tokenizer_config.json:   0%|          | 0.00/1.46k [00:00<?, ?B/s]
tokenizer_config.json: 100%|██████████| 1.46k/1.46k [00:00<00:00, 7.98MB/s]
tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]
tokenizer.model: 100%|██████████| 493k/493k [00:00<00:00, 8.53MB/s]
tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]
tokenizer.json: 100%|██████████| 1.80M/1.80M [00:00<00:00, 19.4MB/s]
special_tokens_map.json:   0%|          | 0.00/72.0 [00:00<?, ?B/s]
special_tokens_map.json: 100%|██████████| 72.0/72.0 [00:00<00:00, 502kB/s]
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 729, in <module>
engine = AsyncLLMEngine.from_engine_args(engine_args)
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 495, in from_engine_args
engine = cls(parallel_config.worker_use_ray,
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
self.engine = self._init_engine(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
return engine_class(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 109, in __init__
self._init_workers(distributed_init_method)
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 145, in _init_workers
self._run_workers(
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 750, in _run_workers
self._run_workers_in_batch(workers, method, *args, **kwargs))
File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 724, in _run_workers_in_batch
output = executor(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 71, in load_model
self.model_runner.load_model()
File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 36, in load_model
self.model = get_model(self.model_config)
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 65, in get_model
model = model_class(model_config.hf_config, linear_method)
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 464, in __init__
self.layers = nn.ModuleList([
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 465, in <listcomp>
MixtralDecoderLayer(config)
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 412, in __init__
self.block_sparse_moe = BlockSparseMoE(
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 182, in __init__
torch.empty(self.ffn_dim_per_partition * self.num_experts,
File "/usr/local/lib/python3.10/dist-packages/torch/utils/_device.py", line 77, in __torch_function__
return func(*args, **kwargs)
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1154, please report a bug to PyTorch.
```

**Comment by dr3s** [comment]
related 
https://github.com/pytorch/pytorch/issues/104801 
https://github.com/pytorch/pytorch/issues/112950

**Comment by dr3s** [comment]
this was due to running on a MiG withtoo little memory.  Too bad the error is vague.  perhaps I will file a pytorch issue.
