### ISSUE TITLE
AsyncEngineDeadError: Task Finished Unexpectedly in VLLM Async LLM Engine

### ISSUE THREAD

**Issue by lin-xiaosheng** [vllm-project/vllm#2281]
Environment:

Date: 2023-12-27
Python Version: 3.11
Library: vllm (0.2.4)
OS: (ubuntu22)

Issue Description:
During a POST request to /worker_generate, the server returned a 500 Internal Server Error. The traceback indicates an issue within the vllm library, specifically in the async_llm_engine.py file.

Actual Behavior:
The server returned a 500 Internal Server Error, and an exception was raised in the ASGI application. The error seems to originate from the AsyncLLMEngine within the vllm library.

Error Log:

2023-12-27 11:25:36 | INFO | stdout | INFO:     127.0.0.1:34180 - "POST /worker_generate HTTP/1.1" 500 Internal Server Error
2023-12-27 11:25:36 | ERROR | stderr | ERROR:    Exception in ASGI application
2023-12-27 11:25:36 | ERROR | stderr | Traceback (most recent call last):
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
2023-12-27 11:25:36 | ERROR | stderr |     task.result()
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
2023-12-27 11:25:36 | ERROR | stderr |     has_requests_in_progress = await self.engine_step()
2023-12-27 11:25:36 | ERROR | stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 338, in engine_step
2023-12-27 11:25:36 | ERROR | stderr |     request_outputs = await self.engine.step_async()
2023-12-27 11:25:36 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 191, in step_async
2023-12-27 11:25:36 | ERROR | stderr |     output = await self._run_workers_async(
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 219, in _run_workers_async
2023-12-27 11:25:36 | ERROR | stderr |     all_outputs = await asyncio.gather(*coros)
2023-12-27 11:25:36 | ERROR | stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/concurrent/futures/thread.py", line 58, in run
2023-12-27 11:25:36 | ERROR | stderr |     result = self.fn(*self.args, **self.kwargs)
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-27 11:25:36 | ERROR | stderr |     return func(*args, **kwargs)
2023-12-27 11:25:36 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/worker/worker.py", line 147, in execute_model
2023-12-27 11:25:36 | ERROR | stderr |     output = self.model_runner.execute_model(seq_group_metadata_list,
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-27 11:25:36 | ERROR | stderr |     return func(*args, **kwargs)
2023-12-27 11:25:36 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 288, in execute_model
2023-12-27 11:25:36 | ERROR | stderr |     output = self.model.sample(
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 303, in sample
2023-12-27 11:25:36 | ERROR | stderr |     next_tokens = self.sampler(self.lm_head.weight, hidden_states,
2023-12-27 11:25:36 | ERROR | stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-12-27 11:25:36 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2023-12-27 11:25:36 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-12-27 11:25:36 | ERROR | stderr |     return forward_call(*args, **kwargs)
2023-12-27 11:25:36 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/layers/sampler.py", line 47, in forward
2023-12-27 11:25:36 | ERROR | stderr |     logits = _get_logits(hidden_states, embedding, embedding_bias,
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/layers/sampler.py", line 105, in _get_logits
2023-12-27 11:25:36 | ERROR | stderr |     logits = torch.matmul(hidden_states, embedding.t())
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr | RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
2023-12-27 11:25:36 | ERROR | stderr | 
2023-12-27 11:25:36 | ERROR | stderr | The above exception was the direct cause of the following exception:
2023-12-27 11:25:36 | ERROR | stderr | 
2023-12-27 11:25:36 | ERROR | stderr | Traceback (most recent call last):
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-12-27 11:25:36 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     return await self.app(scope, receive, send)
2023-12-27 11:25:36 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     await super().__call__(scope, receive, send)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     raise exc
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     await self.app(scope, receive, _send)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     raise exc
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     await self.app(scope, receive, sender)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     raise e
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2023-12-27 11:25:36 | ERROR | stderr |     await route.handle(scope, receive, send)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2023-12-27 11:25:36 | ERROR | stderr |     await self.app(scope, receive, send)
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2023-12-27 11:25:36 | ERROR | stderr |     response = await func(request)
2023-12-27 11:25:36 | ERROR | stderr |                ^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
2023-12-27 11:25:36 | ERROR | stderr |     raw_response = await run_endpoint_function(
2023-12-27 11:25:36 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2023-12-27 11:25:36 | ERROR | stderr |     return await dependant.call(**values)
2023-12-27 11:25:36 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/autodl-tmp/FastChat/fastchat/serve/vllm_worker.py", line 187, in api_generate
2023-12-27 11:25:36 | ERROR | stderr |     output = await worker.generate(params)
2023-12-27 11:25:36 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/autodl-tmp/FastChat/fastchat/serve/vllm_worker.py", line 145, in generate
2023-12-27 11:25:36 | ERROR | stderr |     async for x in self.generate_stream(params):
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/autodl-tmp/FastChat/fastchat/serve/vllm_worker.py", line 113, in generate_stream
2023-12-27 11:25:36 | ERROR | stderr |     async for request_output in results_generator:
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 444, in generate
2023-12-27 11:25:36 | ERROR | stderr |     raise e
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 438, in generate
2023-12-27 11:25:36 | ERROR | stderr |     async for request_output in stream:
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 70, in __anext__
2023-12-27 11:25:36 | ERROR | stderr |     raise result
2023-12-27 11:25:36 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
2023-12-27 11:25:36 | ERROR | stderr |     raise exc
2023-12-27 11:25:36 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
2023-12-27 11:25:36 | ERROR | stderr |     raise AsyncEngineDeadError(
2023-12-27 11:25:36 | ERROR | stderr | vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

**Comment by JavierCCC** [comment]
im facing the same issue +1

**Comment by prd-tuong-nguyen** [comment]
same issue
