### ISSUE TITLE
Issue when run distributed inference with vLLM + Ray

### ISSUE THREAD

**Issue by nkwangleiGIT** [vllm-project/vllm#2289]
Steps:
1. Setting up a K8s cluster with two nodes, and each node have a Nvidia 3090 GPU.
2. Install Ray cluster using kuberay with one head and one worker pod
3. Use the command below to load model with single GPU by setting --tensor-parallel-size=1, **it works fine**
```
python3.8 -m vllm.entrypoints.api_server --model qwen-7b-chat --tensor-parallel-size 1 --trust-remote-code 
```
use nvidia-smi to check GPU usage:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:3B:00.0 Off |                  N/A |
|  0%   36C    P2             105W / 350W |   21232MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

5. Try the distributed inference, install vLLM package on each ray node
5. Load the model on head node setting --tensor-parallel-size=2 using command below:
```
python3.8 -m vllm.entrypoints.api_server --model qwen-7b-chat --tensor-parallel-size 2 --trust-remote-code 
```
**It failed to load the model with timeout error, and GPU usage is some low**, nvidia-smi shows below on both head and worker node. Not sure why both GPUs is using 7800MiB, and will not go up further.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:3B:00.0 Off |                  N/A |
|  0%   31C    P8              22W / 350W |   7800MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
```

**Comment by esmeetu** [comment]
What is the bandwidth between these two nodes? Ensure that the network is connected properly.

**Comment by nkwangleiGIT** [comment]
Here is the result from iperf:
```
Connecting to host 172.40.20.122, port 8888
[  5] local 172.40.20.125 port 35018 connected to 172.40.20.122 port 8888
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   336 MBytes  2.82 Gbits/sec  2114    156 KBytes       
[  5]   1.00-2.00   sec   318 MBytes  2.66 Gbits/sec  1796    218 KBytes       
[  5]   2.00-3.00   sec   301 MBytes  2.53 Gbits/sec  2686   72.1 KBytes       
[  5]   3.00-4.00   sec   318 MBytes  2.66 Gbits/sec  2454    141 KBytes
```
Can this bandwidth acceptable?

**Comment by esmeetu** [comment]
@nkwangleiGIT I think it's ok. Is there any error message?

**Comment by nkwangleiGIT** [comment]
Here is the detail output:
```
(base) ray@raycluster-kuberay-head-dn6q9:/data/models$ python3.8 -m vllm.entrypoints.api_server --model qwen-7b-chat --tensor-parallel-size 2 --trust-remote-code 
2023-12-28 04:55:00,667 INFO worker.py:1405 -- Using address 127.0.0.1:6379 set in the environment variable RAY_ADDRESS
2023-12-28 04:55:00,667 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 172.31.58.174:6379...
2023-12-28 04:55:00,675 INFO worker.py:1715 -- Connected to Ray cluster. View the dashboard at http://172.31.58.174:8265 
INFO 12-28 04:55:00 llm_engine.py:73] Initializing an LLM engine with config: model='qwen-7b-chat', tokenizer='qwen-7b-chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, enforce_eager=False, seed=0)
WARNING 12-28 04:55:01 tokenizer.py:62] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ray/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/entrypoints/api_server.py", line 80, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 496, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers_ray(placement_group)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 195, in _init_workers_ray
    self._run_workers(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 755, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 732, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ConnectionError): ray::RayWorkerVllm.execute_method() (pid=1206, ip=172.31.58.174, actor_id=6854d40df993e3eca697e06202000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f9615640130>)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

ray::RayWorkerVllm.execute_method() (pid=1206, ip=172.31.58.174, actor_id=6854d40df993e3eca697e06202000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f9615640130>)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f95884fae80>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

ray::RayWorkerVllm.execute_method() (pid=1206, ip=172.31.58.174, actor_id=6854d40df993e3eca697e06202000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f9615640130>)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/qwen-7b-chat/revision/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f95884fae80>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

ray::RayWorkerVllm.execute_method() (pid=1206, ip=172.31.58.174, actor_id=6854d40df993e3eca697e06202000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f9615640130>)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/engine/ray_utils.py", line 31, in execute_method
    return executor(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/vllm/worker/worker.py", line 79, in load_model
    self.model_runner.load_model()
```

**Comment by esmeetu** [comment]
It looks like loading model problem. Make sure your two nodes can access local model.

**Comment by nkwangleiGIT** [comment]
yes, just found it's still trying to download model from huggingface.co, after change the --model to the absolute local path, it's working now, thanks a lot!

**Comment by dalvarezquiroga** [comment]
Hi @nkwangleiGIT  would be possible pls to share the configuration to make it work? I cannot find any interesting post about that. 
The arquitecture should be more or less like this:
![Image](https://github.com/user-attachments/assets/4fac8ea9-4701-4753-a546-58499eefe63c)
We are using official Helm Charts from ray, for install the ray-operator & ray-cluster. 

But I can't get it to work with Qwen3-32B.
