### ISSUE TITLE
OOM while loading THUDM/chatglm-6b-int4

### ISSUE THREAD

**Issue by yuxx0218** [vllm-project/vllm#2338]
I am trying this code to load THUDM/chatglm-6b-int4 on a single GPU:
`llm = LLM(model=model_path, trust_remote_code=True)`

However it raises an OOM exception:

> Traceback (most recent call last):
  File "demo_vllm.py", line 15, in <module>
    llm = LLM(model="chatglm-6b-int4",
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 105, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 250, in from_engine_args
    engine = cls(*engine_configs,
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 146, in _init_workers
    self._run_workers(
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 755, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 729, in _run_workers_in_batch
    output = executor(*args, **kwargs)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/worker/worker.py", line 79, in load_model
    self.model_runner.load_model()
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 57, in load_model
    self.model = get_model(self.model_config)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 65, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/models/chatglm.py", line 333, in __init__
    self.transformer = ChatGLMModel(config, linear_method)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/models/chatglm.py", line 299, in __init__
    self.encoder = GLMTransformer(config, linear_method)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/models/chatglm.py", line 254, in __init__
    [GLMBlock(config, linear_method) for i in range(self.num_layers)])
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/models/chatglm.py", line 254, in <listcomp>
    [GLMBlock(config, linear_method) for i in range(self.num_layers)])
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/models/chatglm.py", line 196, in __init__
    self.mlp = GLMMLP(config, linear_method)
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/models/chatglm.py", line 138, in __init__
    self.dense_h_to_4h = MergedColumnParallelLinear(
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 256, in __init__
    super().__init__(input_size, sum(output_sizes), bias, gather_output,
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 176, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 55, in create_weights
    weight = Parameter(torch.empty(output_size_per_partition,
  File "miniconda3/envs/vllm/lib/python3.9/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB. GPU 0 has a total capacty of 10.75 GiB of which 134.50 MiB is free. Including non-PyTorch memory, this process has 10.61 GiB memory in use. Of the allocated memory 10.29 GiB is allocated by PyTorch, and 1.39 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

-------------------------------------------------------
I have tried `https://github.com/vllm-project/vllm/issues/2176` and set `gpu_memory_utilization`, not work.
I also tried `https://github.com/vllm-project/vllm/issues/1949` and set `max_seq_len`, not work.
I saw `https://github.com/vllm-project/vllm/issues/2304`, does it means that this situation is expected?

-------------------------------------------------------
Note that I downgrade the `transformers` to `4.29.2` to avoid the tokenizer loading exception.

**Comment by chu-tianxiang** [comment]
`THUDM/chatglm-6b-int4` doesn't use AWQ or GPTQ for quantization and is not supported by vLLM.

**Comment by yuxx0218** [comment]
> `THUDM/chatglm-6b-int4` doesn't use AWQ or GPTQ for quantization and is not supported by vLLM.

THX. Could I say vLLM only supports chatglm of full precision and that quantized by AWQ and GPTQ?

**Comment by chu-tianxiang** [comment]
> > `THUDM/chatglm-6b-int4` doesn't use AWQ or GPTQ for quantization and is not supported by vLLM.
> 
> THX. Could I say vLLM only supports chatglm of full precision and that quantized by AWQ and GPTQ?

Yes, except the support matrix of quantization also includes SqueezeLLM.

**Comment by hmellor** [comment]
Closing this as vLLM currently only supports AWQ, GPTQ and SqueezeLLM for quantization.
