### ISSUE TITLE
anyone can Qwen-14B-Chat-AWQ work with VLLM/TP ?

### ISSUE THREAD

**Issue by s-natsubori** [vllm-project/vllm#2419]
I trying quantize [lightblue/qarasu-14B-chat-plus-unleashed](https://huggingface.co/lightblue/qarasu-14B-chat-plus-unleashed) based [Qwen/Qwen-14B-Chat](https://huggingface.co/Qwen/Qwen-14B-Chat) .

Transformer(4.36.2) with autoawq(0.1.8) , it works.
VLLM(0.2.7) with autoawq(0.1.8) , **tensor_parallel_size=1**, it works.
But VLLM(0.2.7) with autoawq(0.1.8) , **tensor_parallel_size=2**, ray worker dead with Error.

**Engin args**
```
INFO 01-11 08:55:54 llm_engine.py:70] Initializing an LLM engine with config: model='/usr/local/model/llm', tokenizer='/usr/local/model/llm', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=awq, enforce_eager=False, seed=0)
```
**Error**
```
File "/usr/local/api/chat_models/chat_local_vllm.py", line 112, in _prepare_vllm
     engine = AsyncLLMEngine.from_engine_args(engine_args)
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 500, in from_engine_args
     engine = cls(parallel_config.worker_use_ray,
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 273, in __init__
     self.engine = self._init_engine(*args, **kwargs)
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 318, in _init_engine
     return engine_class(*args, **kwargs)
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 109, in __init__
     self._init_workers_ray(placement_group)
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 249, in _init_workers_ray
     self._run_workers(
   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 795, in _run_workers
     driver_worker_output = getattr(self.driver_worker,
   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 81, in load_model
     self.model_runner.load_model()
   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 64, in load_model
     self.model = get_model(self.model_config)
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 65, in get_model
     model = model_class(model_config.hf_config, linear_method)
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen.py", line 231, in __init__
     self.transformer = QWenModel(config, linear_method)
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen.py", line 193, in __init__
     self.h = nn.ModuleList([
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen.py", line 194, in <listcomp>
     QWenBlock(config, linear_method)
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen.py", line 147, in __init__
     self.mlp = QWenMLP(config.hidden_size,
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/qwen.py", line 49, in __init__
     self.c_proj = RowParallelLinear(intermediate_size,
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/linear.py", line 495, in __init__
     self.linear_weights = self.linear_method.create_weights(
   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/quantization/awq.py", line 85, in create_weights
     raise ValueError(
 ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.
```
[TheBloke/Qwen-14B-Chat-AWQ](https://huggingface.co/TheBloke/Qwen-14B-Chat-AWQ) raise same Error.
 Qwen-**7B**-Chat-AWQ is work with same parameters.
 Qwen-**14B**-Chat has different architecture?

**Comment by qiumuyang** [comment]
Similar problem for [csdc-atl/Baichuan2-7B-Chat-GPTQ-Int4](https://huggingface.co/csdc-atl/Baichuan2-7B-Chat-GPTQ-Int4).
`--tensor-parallel-size=2` works fine, but `--tensor-parallel-size=4` raises the same ValueError.

**Engin args**
```
INFO 01-12 13:00:00 llm_engine.py:70] Initializing an LLM engine with config: model='csdc-atl/Baichuan2-7B-Chat-GPTQ-Int4', tokenizer='csdc-atl/Baichuan2-7B-Chat-GPTQ-Int4', tokenizer_mode=auto, revision=3903d0d0b05d4adc0dd340fdf86d9a3d787ed54d, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=4, quantization=gptq, enforce_eager=False, seed=0)
```

**Error**
```
Traceback (most recent call last):
  File "src/vllm_demo.py", line 83, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 500, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 273, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 318, in _init_engine
    return engine_class(*args, **kwargs)
  File "env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 109, in __init__
    self._init_workers_ray(placement_group)
  File "env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 249, in _init_workers_ray
    self._run_workers(
  File "env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 795, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "env/lib/python3.10/site-packages/vllm/worker/worker.py", line 81, in load_model
    self.model_runner.load_model()
  File "env/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 64, in load_model
    self.model = get_model(self.model_config)
  File "env/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 65, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "env/lib/python3.10/site-packages/vllm/model_executor/models/baichuan.py", line 375, in __init__
    super().__init__(config, "ROPE", linear_method)
  File "env/lib/python3.10/site-packages/vllm/model_executor/models/baichuan.py", line 297, in __init__
    self.model = BaiChuanModel(config, position_embedding, linear_method)
  File "env/lib/python3.10/site-packages/vllm/model_executor/models/baichuan.py", line 260, in __init__
    self.layers = nn.ModuleList([
  File "env/lib/python3.10/site-packages/vllm/model_executor/models/baichuan.py", line 261, in <listcomp>
    BaiChuanDecoderLayer(config, position_embedding, linear_method)
  File "env/lib/python3.10/site-packages/vllm/model_executor/models/baichuan.py", line 205, in __init__
    self.mlp = BaiChuanMLP(
  File "env/lib/python3.10/site-packages/vllm/model_executor/models/baichuan.py", line 89, in __init__
    self.down_proj = RowParallelLinear(intermediate_size,
  File "env/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 495, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "env/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/gptq.py", line 102, in create_weights
    raise ValueError(
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.
```
The `input_size_per_partition` is `2752` and the `self.quant_config.group_size` is `128`, which causes `GPTQLinearMethod.create_weights` to raise the error where the condition `input_size_per_partition % self.quant_config.group_size != 0` is not met.

**Comment by xiabo0816** [comment]
`quantization=awq,` 

how `awq` looks like?

**Comment by s-natsubori** [comment]
with autoawq==0.1.8
```
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }
```

**Comment by wxupjack** [comment]
Using TP (or tensor_parallel_size) =2 means the vllm distribute the model to 2 GPUs.
The error happens in this quantization file (AWQ and GPTQ has the similar checking):
https://github.com/vllm-project/vllm/blob/bfdcfa6a053c693800551bd1bd71acabbe1941e8/vllm/model_executor/layers/quantization/gptq.py#L99-L108

1. After checking the `config.json` fo Qwen models, you can find various `intermediate_size`s in different scales. For Qwen-7B, it is 11008 and Qwen-14B is 13696.
2. Also in this file, `group_size ` of `quantization_config` is 128 (same for almost quant models). So you can get the available distributed group number of each model:
- Qwen-7B is $`128*86 = 128 * (1*2*43)`$    # you can parallelly running on 1 or 2 or 43 GPUs
- Qwen-14B is $`128*107=128*(1*107)`$    # cannot run on 2 GPUs 
3.  As a result, `input_size_per_partition % self.quant_config.group_size != 0` is triggered, and this error raised.

P.S. I haven't found any solution to make interm-dim imbalanced distribution in vllm untill now. Or you can use simple HF multi-gpu loading method for test.

**Comment by ttkrpink** [comment]
> Using TP (or tensor_parallel_size) =2 means the vllm distribute the model to 2 GPUs. The error happens in this quantization file (AWQ and GPTQ has the similar checking):
> 
> https://github.com/vllm-project/vllm/blob/bfdcfa6a053c693800551bd1bd71acabbe1941e8/vllm/model_executor/layers/quantization/gptq.py#L99-L108
> 
> 1. After checking the `config.json` fo Qwen models, you can find various `intermediate_size`s in different scales. For Qwen-7B, it is 11008 and Qwen-14B is 13696.
> 2. Also in this file, `group_size ` of `quantization_config` is 128 (same for almost quant models). So you can get the available distributed group number of each model:
> 
> * Qwen-7B is 128∗86=128∗(1∗2∗43)    # you can parallelly running on 1 or 2 or 43 GPUs
> * Qwen-14B is 128∗107=128∗(1∗107)    # cannot run on 2 GPUs
> 
> 3. As a result, `input_size_per_partition % self.quant_config.group_size != 0` is triggered, and this error raised.
> 
> P.S. I haven't found any solution to make interm-dim imbalanced distribution in vllm untill now. Or you can use simple HF multi-gpu loading method for test.

107 is a prime number, does that mean the Qwen-14B can only be loaded into 1 GPU or 107 GPUs, and no other GPU number can support that?

**Comment by lxb0425** [comment]
我刚才也遇到了这个问题。。。

**Comment by fersebas** [comment]
For qwen 72b which group_size works for vllm awq? thanks

**Comment by chenchun0629** [comment]
> Using TP (or tensor_parallel_size) =2 means the vllm distribute the model to 2 GPUs. The error happens in this quantization file (AWQ and GPTQ has the similar checking):
> 
> https://github.com/vllm-project/vllm/blob/bfdcfa6a053c693800551bd1bd71acabbe1941e8/vllm/model_executor/layers/quantization/gptq.py#L99-L108
> 
> 1. After checking the `config.json` fo Qwen models, you can find various `intermediate_size`s in different scales. For Qwen-7B, it is 11008 and Qwen-14B is 13696.
> 2. Also in this file, `group_size ` of `quantization_config` is 128 (same for almost quant models). So you can get the available distributed group number of each model:
> 
> * Qwen-7B is 128∗86=128∗(1∗2∗43)    # you can parallelly running on 1 or 2 or 43 GPUs
> * Qwen-14B is 128∗107=128∗(1∗107)    # cannot run on 2 GPUs
> 
> 3. As a result, `input_size_per_partition % self.quant_config.group_size != 0` is triggered, and this error raised.
> 
> P.S. I haven't found any solution to make interm-dim imbalanced distribution in vllm untill now. Or you can use simple HF multi-gpu loading method for test.

其实只要满足`input_size_per_partition % self.quant_config.group_size != 0` 和 `output_size_per_partition % self.quant_config.pack_factor.numerator != 0` 这两个条件。

所以量化时可以尝试调整group_size设置为64。但是较小的group_size意味着需要更多的量化级别和存储空间，可能增加计算和存储的负担。

**Comment by chenchun0629** [comment]
> > Using TP (or tensor_parallel_size) =2 means the vllm distribute the model to 2 GPUs. The error happens in this quantization file (AWQ and GPTQ has the similar checking):
> > https://github.com/vllm-project/vllm/blob/bfdcfa6a053c693800551bd1bd71acabbe1941e8/vllm/model_executor/layers/quantization/gptq.py#L99-L108
> > 
> > 
> > 1. After checking the `config.json` fo Qwen models, you can find various `intermediate_size`s in different scales. For Qwen-7B, it is 11008 and Qwen-14B is 13696.
> > 2. Also in this file, `group_size ` of `quantization_config` is 128 (same for almost quant models). So you can get the available distributed group number of each model:
> > 
> > 
> > * Qwen-7B is 128∗86=128∗(1∗2∗43)    # you can parallelly running on 1 or 2 or 43 GPUs
> > * Qwen-14B is 128∗107=128∗(1∗107)    # cannot run on 2 GPUs
> > 
> > 
> > 3. As a result, `input_size_per_partition % self.quant_config.group_size != 0` is triggered, and this error raised.
> > 
> > P.S. I haven't found any solution to make interm-dim imbalanced distribution in vllm untill now. Or you can use simple HF multi-gpu loading method for test.
> 
> In fact, it is only necessary to satisfy the conditions input_size_per_partition % self.quant_config.group_size != 0 and output_size_per_partition % self.quant_config.pack_factor.numerator != 0.
> 
> Therefore, you can try setting the group_size to 64 during quantization. However, a smaller group_size means more quantization levels and storage space are required, which may increase the computational and storage burden.

This is an incorrect approach. The correct method should follow the official documentation: https://qwen.readthedocs.io/zh-cn/latest/quantization/gptq.html

The basic logic: Since qwen2-72's intermediate_size is 29568, and when quantizing large models, the group_size is typically set to 128, 29568 / 128 = 231, which means the quantized model can only be deployed on a single GPU. To solve this issue, we need to increase the intermediate_size by 128 to 29696, so 29696 / 128 = 232, allowing the model to be deployed on 1, 2, 4, or 8 GPUs.

Process:

Merge the LoRA adapter to get a complete model
Extend the model's intermediate_size to 29696
Perform quantization
