### ISSUE TITLE
Circular import loading vllm.entrypoints.openai.api_server 

### ISSUE THREAD

**Issue by justquick** [vllm-project/vllm#248]
Just installed this from main branch and am getting the following error trying to run the openai server from the quickstart

`ImportError: cannot import name 'activation_ops' from partially initialized module 'vllm' (most likely due to a circular import) (/Users/jquick/Projects/Vendor/vllm/vllm/__init__.py)`

When running in shell:

```bash
$ python -m vllm.entrypoints.openai.api_server
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1 with CUDA None (you have 2.0.1)
    Python  3.10.8 (you have 3.10.8)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
/Users/jquick/.local/share/virtualenvs/vllm-d86THEgB/bin/python: Error while finding module specification for 'vllm.entrypoints.openai.api_server' (ImportError: cannot import name 'activation_ops' from partially initialized module 'vllm' (most likely due to a circular import) (/Users/jquick/Projects/Vendor/vllm/vllm/__init__.py))
```

Confirmed by trying to import module from python

```python
>>> import vllm.entrypoints.openai.api_server
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1 with CUDA None (you have 2.0.1)
    Python  3.10.8 (you have 3.10.8)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jquick/Projects/Vendor/vllm/vllm/__init__.py", line 2, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/Users/jquick/Projects/Vendor/vllm/vllm/engine/async_llm_engine.py", line 6, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/Users/jquick/Projects/Vendor/vllm/vllm/engine/llm_engine.py", line 15, in <module>
    from vllm.worker.worker import Worker
  File "/Users/jquick/Projects/Vendor/vllm/vllm/worker/worker.py", line 8, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/Users/jquick/Projects/Vendor/vllm/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/Users/jquick/Projects/Vendor/vllm/vllm/model_executor/model_loader.py", line 9, in <module>
    from vllm.model_executor.models import (GPT2LMHeadModel, GPTBigCodeForCausalLM, GPTNeoXForCausalLM,
  File "/Users/jquick/Projects/Vendor/vllm/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.gpt2 import GPT2LMHeadModel
  File "/Users/jquick/Projects/Vendor/vllm/vllm/model_executor/models/gpt2.py", line 30, in <module>
    from vllm.model_executor.layers.activation import get_act_fn
  File "/Users/jquick/Projects/Vendor/vllm/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: cannot import name 'activation_ops' from partially initialized module 'vllm' (most likely due to a circular import) (/Users/jquick/Projects/Vendor/vllm/vllm/__init__.py)
```

I am getting the xformers warning because i have no cuda support

MacBook Pro (16-inch, 2019)
OSX Monterrey 12.6
Python 3.10.8
pip 23.1.2

**Comment by justquick** [comment]
Realized that this was because I do not have cuda support. The install or runtime should still break more gracefully than this when no cuda support is found
