### ISSUE TITLE
Issue while loading the model finetuned trained from h2o llm studio

### ISSUE THREAD

**Issue by gangooteli** [vllm-project/vllm#2558]
Using below command
`docker run -p 8080:8080 --gpus=all -e MODEL=/home/workspace/output/user/Experiment_Name/unzip_model/ api
`

Content of unzip_model : This folder contains the unzip of model finetuned using h2o llm studio 

```
config.json             
model_card.md                     
pytorch_model.bin.index.json
pytorch_model-00001-of-00002.bin  
pytorch_model-00002-of-00002.bin  
special_tokens_map.json  
tokenizer.json
generation_config.json  
tokenizer_config.json
```

Traceback

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 389, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/workspace/output/user/Experiment_Name/unzip_model/'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/server.py", line 87, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 481, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 182, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 79, in __init__
    self.hf_config = get_config(model, trust_remote_code, revision)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/config.py", line 21, in get_config
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 699, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/home/workspace/output/user/Experiment_Name/unzip_model/'. Please provide either the path to a local folder or the repo_id of a model on the Hub
```

Please help me the issue.

**Comment by d-a-v** [comment]
It should be in the doc.
Here is a variant.
Assuming the model `the-downloaded-model` is in current directory :
```
docker run -it -v $(pwd):/m --rm --network=host the-docker-image --model /m/the-downloaded-model --other-options...
```
