### ISSUE TITLE
vLLM computes max sequence length for Yi 200k at 4k

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#2565]
https://huggingface.co/01-ai/Yi-34B-Chat/blob/main/config.json

vLLM not accounting for rope scaling.

So can't use full context.

```
 -m vllm.entrypoints.openai.api_server \
        --port=5000 \
        --host=0.0.0.0 \
        --model=01-ai/Yi-34B-Chat \
        --seed 1234 \
        --tensor-parallel-size=4 \
        --trust-remote-code \
        --max-model-len=204800 \
        --download-dir=/workspace/.cache/huggingface/hub
```

gives:
```
INFO 01-23 21:18:03 api_server.py:727] args: Namespace(host='0.0.0.0', port=5000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, model='01-ai/Yi-34B-Chat', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir='/workspace/.cache/huggingface/hub', load_format='auto', dtype='auto', max_model_len=204800, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, block_size=16, seed=1234, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 737, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 494, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 218, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/config.py", line 103, in __init__
    self.max_model_len = _get_and_verify_max_len(self.hf_config,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/config.py", line 511, in _get_and_verify_max_len
    raise ValueError(
ValueError: User-specified max_model_len (204800) is greater than the derived max_model_len (None=4096 in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.
```

and otherwise defaults to 4096.

**Comment by Shreyaskulkarni98** [comment]
What was the solution to this?

**Comment by pseudotensor** [comment]
No solution, I was just confused.  Yi 32B Chat only supports 4k, hacking the embedding length in config.json to 200k operates somewhat but not well.  Better to use model that's been properly trained, like https://huggingface.co/NousResearch/Nous-Capybara-34B
