### ISSUE TITLE
Prefix cache run into assert.

### ISSUE THREAD

**Issue by DouHappy** [vllm-project/vllm#2612]
@Yard1  Hello, I found prefix can't run in the newest version. Maybe it due to the lora? But I am not familiar with lora, I just  did a try. Using code below make prefix run again. It seems work. Could you please take a look at this issue.

I replaced code in model_runner.py (191-194 row) by this.
```python
        max_lora_index_len = max(len(mapping) for mapping in lora_index_mapping)
        lora_index_mapping = [
            _pad_to_max(mapping, max_lora_index_len, pad=0)
            for mapping in lora_index_mapping
        ]
```

Ran into assert as below.
```
Traceback (most recent call last):
  File "/home/yangchunhao/vllm-newest/vllm/examples/offline_inference_with_prefix.py", line 53, in <module>
    outputs = llm.generate(generating_prompts,
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/entrypoints/llm.py", line 179, in generate
    return self._run_engine(use_tqdm)
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/entrypoints/llm.py", line 205, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/engine/llm_engine.py", line 790, in step
    all_outputs = self._run_workers(
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/engine/llm_engine.py", line 977, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/yangchunhao/miniconda3/envs/vllm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/worker/worker.py", line 208, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/yangchunhao/miniconda3/envs/vllm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/worker/model_runner.py", line 521, in execute_model
    self.prepare_input_tensors(seq_group_metadata_list))
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/worker/model_runner.py", line 445, in prepare_input_tensors
    lora_requests) = self._prepare_prompt(seq_group_metadata_list)
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/worker/model_runner.py", line 196, in _prepare_prompt
    lora_index_mapping = [
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/worker/model_runner.py", line 197, in <listcomp>
    _pad_to_max(mapping, max_prompt_len, pad=0)
  File "/data/home/yangchunhao/vllm-newest/vllm/vllm/worker/model_runner.py", line 779, in _pad_to_max
    assert len(x) <= max_len
```

**Comment by linchen111** [comment]
+1

**Comment by sighingnow** [comment]
Addressed by #2688.
