### ISSUE TITLE
ValueError: Total number of attention heads (52) must be divisible by tensor parallel size (8).

### ISSUE THREAD

**Issue by PolinaBokova** [vllm-project/vllm#2652]
Hello! I have two questions:
1. How to solve the problem with loading a model on an 8GPU. I get an error
ValueError: Total number of attention heads (52) must be divisible by tensor parallel size (8).
2. Why do the results differ from HF transformers with the same parameters?

**Comment by PolinaBokova** [comment]
I'm using wizardlm : https://huggingface.co/cognitivecomputations/WizardLM-33B-V1.0-Uncensored

**Comment by eigen2017** [comment]
> This error no longer appears in the source https://github.com/search?q=repo%3Avllm-project%2Fvllm%20must%20be%20divisible&type=code

no， the error is in vllm/config.py
in function verify_with_parallel_config

32heads on 3gpus error:
total number of attention heads must be divisible by tensor parallel size

**Comment by naturomics** [comment]
the same error. 
- vllm version: 0.5.1
- model: Qwen2-57B-A14B-Instruct with args `--tensor-parallel-size 8`

Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 216, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 382, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 742, in create_engine_config
    return EngineConfig(
  File "<string>", line 14, in __init__
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 1525, in __post_init__
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 263, in verify_with_parallel_config
    raise ValueError(
ValueError: Total number of attention heads (28) must be divisible by tensor parallel size (8).
```

**Comment by jiqiujia** [comment]
The same problem with vllm==0.7.2 when infering qwen-7b
