### ISSUE TITLE
Fail to use ``pip install -e .''

### ISSUE THREAD

**Issue by TobyGE** [vllm-project/vllm#2661]
Here are the errors. I also installed numpy, but still failed. CUDA==12.2

```
Collecting git+https://github.com/vllm-project/vllm                                                                                                   
  Cloning https://github.com/vllm-project/vllm to /tmp/pip-req-build-yuxv0lpu                                                                         
  Running command git clone --filter=blob:none --quiet https://github.com/vllm-project/vllm /tmp/pip-req-build-yuxv0lpu                               
  Resolved https://github.com/vllm-project/vllm to commit ab406446691f289ef51d1abd8d1ff66760eda36f
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /tmp/pip-build-env-ehqfzo6d/overlay/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      Traceback (most recent call last):
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ehqfzo6d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ehqfzo6d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ehqfzo6d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 57, in <module>
        File "<string>", line 40, in _is_cuda
        File "<string>", line 33, in _is_neuron
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['neuron-ls']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by simon-mo** [comment]
sorry fixing it now

**Comment by simon-mo** [comment]
Please try out this #2671 to see whether it fixes things, thank you

**Comment by TobyGE** [comment]
Just tried it. Still now working

`$ pip install git+https://github.com/vllm-project/vllm.git@ab68783757a7da393d57ab30f1261c5b073c9c5e
Collecting git+https://github.com/vllm-project/vllm.git@ab68783757a7da393d57ab30f1261c5b073c9c5e
  Cloning https://github.com/vllm-project/vllm.git (to revision ab68783757a7da393d57ab30f1261c5b073c9c5e) to /tmp/pip-req-build-19mjeiky
  Running command git clone --filter=blob:none --quiet https://github.com/vllm-project/vllm.git /tmp/pip-req-build-19mjeiky
  Running command git rev-parse -q --verify 'sha^ab68783757a7da393d57ab30f1261c5b073c9c5e'
  Running command git fetch -q https://github.com/vllm-project/vllm.git ab68783757a7da393d57ab30f1261c5b073c9c5e
  Running command git checkout -q ab68783757a7da393d57ab30f1261c5b073c9c5e
  Resolved https://github.com/vllm-project/vllm.git to commit ab68783757a7da393d57ab30f1261c5b073c9c5e
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      /tmp/pip-build-env-tqmhhno1/overlay/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      Traceback (most recent call last):
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-tqmhhno1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-tqmhhno1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-tqmhhno1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 191, in <module>
        File "<string>", line 129, in get_nvcc_cuda_version
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/ec2-user/SageMaker/conda/deekseek/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by simon-mo** [comment]
Is `nvcc` in the PATH? What does `which nvcc` output?

**Comment by TobyGE** [comment]
Find the problem comes from CUDA. When using 12.1, everything went well. Hope you can support 12.2 soon~
