### ISSUE TITLE
stream infer error!

### ISSUE THREAD

**Issue by shiqingzhangCSU** [vllm-project/vllm#2705]
I want to use AsyncLLMEngine for stream reasoning, and then I use the tornado method to serve. When I created the coroutine, I encountered the following error.

```
[2024-02-01 15:34:28 base_events.py:1707 ERROR] Exception in callback _raise_exception_on_finish(request_tracker=<vllm.engine....x7feff579fc40>)(<Task finishe...tart method")>) at /home/admin/vllm/vllm/engine/async_llm_engine.py:22
    handle: <Handle _raise_exception_on_finish(request_tracker=<vllm.engine....x7feff579fc40>)(<Task finishe...tart method")>) at /home/admin/vllm/vllm/engine/async_llm_engine.py:22>
    Traceback (most recent call last):
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
        task.result()
      File "/usr/local/lib/python3.8/asyncio/futures.py", line 178, in result
        raise self._exception
      File "/usr/local/lib/python3.8/asyncio/tasks.py", line 282, in __step
        result = coro.throw(exc)
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 363, in run_engine_loop
        has_requests_in_progress = await self.engine_step()
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 342, in engine_step
        request_outputs = await self.engine.step_async()
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 190, in step_async
        all_outputs = await self._run_workers_async(
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 231, in _run_workers_async
        all_outputs = await asyncio.gather(*coros)
      File "/usr/local/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
        future.result()
      File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/admin/vllm/vllm/worker/worker.py", line 189, in execute_model
        output = self.model_runner.execute_model(seq_group_metadata_list,
      File "/usr/local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 446, in execute_model
        self.prepare_input_tensors(seq_group_metadata_list))
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 337, in prepare_input_tensors
        prompt_lens) = self._prepare_prompt(seq_group_metadata_list)
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 128, in _prepare_prompt
        input_tokens = _make_tensor_with_pad(input_tokens,
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 645, in _make_tensor_with_pad
        return torch.tensor(padded_x,
      File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
        raise RuntimeError(
    RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
        self._context.run(self._callback, *self._args)
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
        raise exc
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
        raise AsyncEngineDeadError(
    vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO 02-01 15:34:28 async_llm_engine.py:134] Aborted request e8b2710b675a4672a92e0f97f62e7b5f.
[2024-02-01 15:34:28 handler.py:315 ERROR] [188526] Excepiton: 140667630587136 Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
[2024-02-01 15:34:28 handler.py:317 ERROR] Traceback (most recent call last):
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
        task.result()
      File "/usr/local/lib/python3.8/asyncio/futures.py", line 178, in result
        raise self._exception
      File "/usr/local/lib/python3.8/asyncio/tasks.py", line 282, in __step
        result = coro.throw(exc)
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 363, in run_engine_loop
        has_requests_in_progress = await self.engine_step()
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 342, in engine_step
        request_outputs = await self.engine.step_async()
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 190, in step_async
        all_outputs = await self._run_workers_async(
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 231, in _run_workers_async
        all_outputs = await asyncio.gather(*coros)
      File "/usr/local/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
        future.result()
      File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/admin/vllm/vllm/worker/worker.py", line 189, in execute_model
        output = self.model_runner.execute_model(seq_group_metadata_list,
      File "/usr/local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 446, in execute_model
        self.prepare_input_tensors(seq_group_metadata_list))
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 337, in prepare_input_tensors
        prompt_lens) = self._prepare_prompt(seq_group_metadata_list)
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 128, in _prepare_prompt
        input_tokens = _make_tensor_with_pad(input_tokens,
      File "/home/admin/vllm/vllm/worker/model_runner.py", line 645, in _make_tensor_with_pad
        return torch.tensor(padded_x,
      File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
        raise RuntimeError(
    RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/admin/dev/stream/webui-transfer/worker/high_service/service/handler.py", line 295, in hs_process
        self.rst = super().post()
      File "/home/admin/dev/stream/webui-transfer/worker/make_app.py", line 160, in post
        asyncio.run(get_result())
      File "/usr/local/lib/python3.8/site-packages/nest_asyncio.py", line 30, in run
        return loop.run_until_complete(task)
      File "/usr/local/lib/python3.8/site-packages/nest_asyncio.py", line 98, in run_until_complete
        return f.result()
      File "/usr/local/lib/python3.8/asyncio/futures.py", line 178, in result
        raise self._exception
      File "/usr/local/lib/python3.8/asyncio/tasks.py", line 280, in __step
        result = coro.send(None)
      File "/home/admin/dev/stream/webui-transfer/worker/make_app.py", line 154, in get_result
        async for result in stream_results:
      File "/home/admin/dev/stream/webui-transfer/worker/high_service/llm/model_hub/vllm_base_model.py", line 171, in stream_results
        async for request_output in results_generator:
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 449, in generate
        raise e
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 443, in generate
        async for request_output in stream:
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 70, in __anext__
        raise result
      File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
        self._context.run(self._callback, *self._args)
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
        raise exc
      File "/home/admin/vllm/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
        raise AsyncEngineDeadError(
    vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
```
here is my code
![image](https://github.com/vllm-project/vllm/assets/44834482/e12e756c-bb41-471c-a150-377a6d94535f)

```
   async def get_result():
            stream_results = model.forward(data)
            print(stream_results)
            async for result in stream_results:
                print(result)
                time_cost = time.time() - tb
                print(time_cost)
                tb = time.time()
                send_event("forward", str(result))
   asyncio.run(get_result())
```

Can anyone tell me what's wrong with my code?

**Comment by rileyhun** [comment]
Hey @shiqingzhangCSU, 

I'm also encountering this issue. Would you happen to know how you fixed it?

**Comment by sunjunlishi** [comment]
not stream infer ？？
