### ISSUE TITLE
The echo parameters and request logs seem to have some issues in vLLM v0.3.0 version (/v1/completions)

### ISSUE THREAD

**Issue by liangxfng** [vllm-project/vllm#2706]
In vLLM v0.3.0 version, logprobs appears to have expired. My personal guess is that it's due to the Pydantic version.
In Pydantic2 version, use model_ dump() method doesn't seem to handle logprops very well.

![question](https://github.com/vllm-project/vllm/assets/49606519/986f5dc2-5559-405d-a84b-99ca1c58c16a)
```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 177, in create_completion
    return JSONResponse(content=generator.model_dump())
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 180, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 39, in __init__
    self.body = self.render(content)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 183, in render
    return json.dumps(
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
``` 

I have printed the interface and found that the information returned using dict() is correct, but it cannot be converted to JSON format。
![image](https://github.com/vllm-project/vllm/assets/49606519/5fe90df2-c17e-4024-b8eb-1a181bcf0252)

In addition, due to the refactoring of the openai server, the promt parameter in the interface log will always be None.
vllm/vllm/entrypoints/openai/serving_completion.py##line 298
vllm/vllm/engine/async_llm_engine.py##line 432

**Comment by simon-mo** [comment]
Regarding the logging of the prompt, I can fix it.
Regarding the LogProb, do you have the request to reproduce it? I am getting properly formatted logprob on 0.3.0

```
Logprobs(text_offset=[0, 6, 10, 12, 15], token_logprobs=[-3.7315573692321777, -1.002060055732727, -0.12878480553627014, -0.8721659183502197, -0.7809031009674072], tokens=['▁Sarah', '▁and', '▁I', '▁am', '▁a'], top_logprobs=[{'▁Sarah': -3.7315573692321777}, {'▁and': -1.002060055732727}, {'▁I': -0.12878480553627014}, {'▁am': -0.8721659183502197}, {'▁a': -0.7809031009674072}])
```

**Comment by liangxfng** [comment]
I can reproduce this problem through vllm/examples/openai_completion_client.py
```python
from openai import OpenAI
openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)

models = client.models.list()
model = models.data[0].id
stream = False
completion = client.completions.create(
    model=model,
    prompt="Hello, my name is",
    max_tokens=5,
    stream=stream,
    logprobs=1)

print("Completion results:")
if stream:
    for c in completion:
        print(c)
else:
    print(completion)
```
I added logs to the code and found that the engine can generate output. Due to byte encoding issues, it is not possible to convert it correctly into a JSON object, resulting in interface errors
```shell
 Wood.That is', 'logprobs': {'text_offset': [0, 4, 6, 11, 16], 'token_logprobs': [-5.482499122619629, -2.5623340606689453, -9.2454833984375, -12.924626350402832, -1.6724791526794434], 'tokens': [b' Tim', b'my', b' Wood', b'.That', b' is'], 'top_logprobs': [{b' Tim': -5.482499122619629, b' Li': -3.939530372619629}, {b'my': -2.5623340606689453, b'.': -1.0467090606689453}, {b' Wood': -9.2454833984375, b'.': -0.6868898868560791}, {b'.That': -12.924626350402832, b'.': -0.9168136119842529}, {b' is': -1.6724791526794434, b"'s": -0.6568542122840881}]}, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 5, 'total_tokens': 10, 'completion_tokens': 5}}
{'id': 'cmpl-e09b44854fdd4df2afcaa66ddc64c671', 'object': 'text_completion', 'created': 1258618, 'model': '/models/Qwen-14B-Chat/1', 'choices': [{'index': 0, 'text': ' Timmy Wood.That is', 'logprobs': {'text_offset': [0, 4, 6, 11, 16], 'token_logprobs': [-5.482499122619629, -2.5623340606689453, -9.2454833984375, -12.924626350402832, -1.6724791526794434], 'tokens': [b' Tim', b'my', b' Wood', b'.That', b' is'], 'top_logprobs': [{b' Tim': -5.482499122619629, b' Li': -3.939530372619629}, {b'my': -2.5623340606689453, b'.': -1.0467090606689453}, {b' Wood': -9.2454833984375, b'.': -0.6868898868560791}, {b'.That': -12.924626350402832, b'.': -0.9168136119842529}, {b' is': -1.6724791526794434, b"'s": -0.6568542122840881}]}, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 5, 'total_tokens': 10, 'completion_tokens': 5}}

INFO:     127.0.0.1:51680 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
```

This is my Python environment：

```shell
Package                       Version
----------------------------- ------------
aioprometheus                 23.12.0
aiosignal                     1.3.1
annotated-types               0.6.0
anyio                         4.2.0
attrs                         23.2.0
certifi                       2023.11.17
charset-normalizer            3.3.2
click                         8.1.7
distro                        1.9.0
einops                        0.7.0
exceptiongroup                1.2.0
fastapi                       0.109.0
filelock                      3.13.1
flash-attn                    2.4.2
frozenlist                    1.4.1
fsspec                        2023.12.2
h11                           0.14.0
httpcore                      1.0.2
httptools                     0.6.1
httpx                         0.26.0
huggingface-hub               0.20.3
idna                          3.6
Jinja2                        3.1.3
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
MarkupSafe                    2.1.4
mpmath                        1.3.0
msgpack                       1.0.7
networkx                      3.2.1
ninja                         1.11.1.1
numpy                         1.26.3
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu12              12.1.105
openai                        1.10.0
orjson                        3.9.12
packaging                     23.2
pip                           22.0.2
protobuf                      4.25.2
psutil                        5.9.8
pydantic                      2.6.0
pydantic_core                 2.16.1
pynvml                        11.5.0
python-dotenv                 1.0.1
PyYAML                        6.0.1
quantile-python               1.1
ray                           2.9.1
referencing                   0.33.0
regex                         2023.12.25
requests                      2.31.0
rpds-py                       0.17.1
safetensors                   0.4.2
sentencepiece                 0.1.99
setuptools                    69.0.3
sniffio                       1.3.0
starlette                     0.35.1
sympy                         1.12
tiktoken                      0.5.2
tokenizers                    0.15.1
torch                         2.1.2
tqdm                          4.66.1
transformers                  4.37.2
transformers-stream-generator 0.0.4
triton                        2.1.0
typing_extensions             4.9.0
urllib3                       2.2.0
uvicorn                       0.27.0.post1
uvloop                        0.19.0
vllm                          0.3.0
watchfiles                    0.21.0
websockets                    12.0
wheel                         0.37.1
xformers                      0.0.23.post1
```

And I noticed a question, why is your logprobs parameter of **type bool**?

**Comment by liangxfng** [comment]
The echo parameter may also have some issues.
```shell
INFO 02-02 09:05:41 async_llm_engine.py:431] Received request cmpl-e3ab58bfc7834026a608eee91a74dc15-0: prompt: None, prefix_pos: None,sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=5, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [9707, 11, 847, 829, 374], lora_request: None.
INFO 02-02 09:05:42 async_llm_engine.py:110] Finished request cmpl-e3ab58bfc7834026a608eee91a74dc15-0.
None
None
INFO:     127.0.0.1:46374 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 163, in create_completion
    generator = await openai_serving_completion.create_completion(
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/serving_completion.py", line 334, in create_completion
    response = request_output_to_completion_response(
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/serving_completion.py", line 177, in request_output_to_completion_response
    top_logprobs = prompt_logprobs + output.logprobs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```
vllm/entrypoints/openai/serving_completion.py"# line 177
```python
top_logprobs = prompt_logprobs + output.logprobs
```

**Comment by PeterXiaTian** [comment]
what's the function of logprobs?

**Comment by liangxfng** [comment]
> what's the function of logprobs?

According to the description, the logarithmic probability of being able to print out candidate words

**Comment by liangxfng** [comment]
The logprobs issue has been resolved because I used the qwen model, and the convert_id_to_token method in the tokenization_qwen. py file on the huggingface was not converted to str. But it was converted into bytes for processing. Modify the file so that the parameters take effect.

examples:
```python
def _convert_id_to_token(self, index: int) -> Union[bytes, str]:
        """Converts an id to a token, special tokens included"""
        if index in self.decoder:
            return self.decoder[index]
        raise ValueError("unknown ids")
```
->
```python
def _convert_id_to_token(self, index: int) -> Union[bytes, str]:
        """Converts an id to a token, special tokens included"""
        if index in self.decoder:
            return self.decoder[index].decode("utf-8", errors=self.errors)
        raise ValueError("unknown ids")
```

**Comment by liangxfng** [comment]
> The logprobs issue has been resolved because I used the qwen model, and the convert_id_to_token method in the tokenization_qwen. py file on the huggingface was not converted to str. But it was converted into bytes for processing. Modify the file so that the parameters take effect.
> 
> examples:
> 
> ```python
> def _convert_id_to_token(self, index: int) -> Union[bytes, str]:
>         """Converts an id to a token, special tokens included"""
>         if index in self.decoder:
>             return self.decoder[index]
>         raise ValueError("unknown ids")
> ```
> 
> ->
> 
> ```python
> def _convert_id_to_token(self, index: int) -> Union[bytes, str]:
>         """Converts an id to a token, special tokens included"""
>         if index in self.decoder:
>             return self.decoder[index].decode("utf-8", errors=self.errors)
>         raise ValueError("unknown ids")
> ```

@simon-mo The logprobs parameter has been resolved, it is a tokenizer issue。

"In addition, due to the refactoring of the openai server, the promt parameter in the interface log will always be None.
vllm/vllm/entrypoints/openai/serving_completion.py##line 298
vllm/vllm/engine/async_llm_engine.py##line 432"

I think the echo parameters are also affected by this place.
vllm/vllm/entrypoints/openai/serving_completion.py##line 298

vllm/vllm/entrypoints/openai/serving_completion.py##line 177,I feel like it can add some protection
```python
 top_logprobs = prompt_logprobs if prompt_logprobs else [] + output.logprobs if output.logprobs else []
 output_text = prompt_text if prompt_text else "" + output.text if output.text else ""
```

**Comment by simon-mo** [comment]
Any fixes or PRs here is appreciated.

**Comment by matheper** [comment]
I stumbled on the same issues. I've created this PR #2995. It should cover both echo and logprobs.

**Comment by hmellor** [comment]
@liangxfng has https://github.com/vllm-project/vllm/pull/3441 solved your issue?
