### ISSUE TITLE
cannot import name 'context_attention_fwd' from 'vllm.model_executor.layers.triton_kernel.prefix_prefill

### ISSUE THREAD

**Issue by LOGIC-10** [vllm-project/vllm#2711]
python -m vllm.entrypoints.openai.api_server --model /yinxr/workhome/zzhong/datasets/llama/llama-2-7b-chat-hf

INFO 02-01 09:37:25 api_server.py:209] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, root_path=None, middleware=[], model='/yinxr/workhome/zzhong/datasets/llama/llama-2-7b-chat-hf', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 02-01 09:37:25 llm_engine.py:71] Initializing an LLM engine with config: model='/yinxr/workhome/zzhong/datasets/llama/llama-2-7b-chat-hf', tokenizer='/yinxr/workhome/zzhong/datasets/llama/llama-2-7b-chat-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, seed=0)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/entrypoints/openai/api_server.py", line 217, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/engine/async_llm_engine.py", line 625, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/engine/async_llm_engine.py", line 366, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers()
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/engine/llm_engine.py", line 149, in _init_workers
    self._run_workers("load_model")
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/engine/llm_engine.py", line 973, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/worker/worker.py", line 92, in load_model
    self.model_runner.load_model()
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/worker/model_runner.py", line 75, in load_model
    self.model = get_model(self.model_config, self.lora_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/model_executor/model_loader.py", line 42, in get_model
    model_class = _get_model_architecture(model_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/model_executor/model_loader.py", line 32, in _get_model_architecture
    model_cls = ModelRegistry.load_model_cls(arch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/model_executor/models/__init__.py", line 78, in load_model_cls
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yinxr/workhome/zzhong/miniconda3/envs/vllm/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/model_executor/models/llama.py", line 32, in <module>
    from vllm.model_executor.layers.attention import PagedAttention
  File "/yinxr/workhome/zzhong/qinyu/vllm/vllm/model_executor/layers/attention.py", line 13, in <module>
    from vllm.model_executor.layers.triton_kernel.prefix_prefill import (
ImportError: cannot import name 'context_attention_fwd' from 'vllm.model_executor.layers.triton_kernel.prefix_prefill'

**Comment by whyiug** [comment]
`pip uninstall tritron`
`pip install tritron`
line 8 in https://github.com/vllm-project/vllm/tree/main/vllm/model_executor/layers/triton_kernel/prefix_prefill.py
