### ISSUE TITLE
RuntimeError: unable to open shared memory object </torch_1_2004494542_0> in read-write mode: Permission denied (13)

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#2719]
With 0.3.0 release, not on 0.2.7.  cuda 12.1 using V100.

```
➜  ~ k logs -f h2ogpt-vllm-inference-764dfd798c-rlmjd -n h2ogpt
INFO 02-02 01:01:59 api_server.py:209] args: Namespace(host='0.0.0.0', port=5000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, root_path=None, middleware=[], model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='hf-internal-testing/llama-tokenizer', revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir='/workspace/.cache/huggingface/hub', load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, block_size=16, seed=1234, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=8192, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2024-02-02 01:02:02,094	INFO worker.py:1724 -- Started a local Ray instance.
INFO 02-02 01:02:03 llm_engine.py:72] Initializing an LLM engine with config: model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='hf-internal-testing/llama-tokenizer', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir='/workspace/.cache/huggingface/hub', load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, seed=1234)
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 217, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 623, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 319, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 364, in _init_engine
    return engine_class(*args, **kwargs)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 109, in __init__
    self._init_workers_ray(placement_group)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 271, in _init_workers_ray
    self._run_workers("init_model")
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 983, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/worker/worker.py", line 87, in init_model
    init_custom_ar()
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 49, in init_custom_ar
    _CA_HANDLE = CustomAllreduce(rank, world_size)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 165, in __init__
    handles, offsets = self._get_ipc_meta(self.meta)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 174, in _get_ipc_meta
    data = inp.untyped_storage()._share_cuda_()
RuntimeError: unable to open shared memory object </torch_1_2004494542_0> in read-write mode: Permission denied (13)
(RayWorkerVllm pid=1026) Exception ignored in: <function CustomAllreduce.__del__ at 0x7c1c846024d0>
(RayWorkerVllm pid=1026) Traceback (most recent call last):
(RayWorkerVllm pid=1026)   File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 227, in __del__
(RayWorkerVllm pid=1026)     self.close()
(RayWorkerVllm pid=1026)   File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 222, in close
(RayWorkerVllm pid=1026)     if self._ptr:
(RayWorkerVllm pid=1026) AttributeError: 'CustomAllreduce' object has no attribute '_ptr'
Exception ignored in: <function CustomAllreduce.__del__ at 0x7ac1dcbc49d0>
Traceback (most recent call last):
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 227, in __del__
    self.close()
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/custom_all_reduce.py", line 222, in close
    if self._ptr:
AttributeError: 'CustomAllreduce' object has no attribute '_ptr'
```

**Comment by pseudotensor** [comment]
added 11Gi shm, but got new error:
```
➜  ~ k logs -f h2ogpt-vllm-inference-684f56dfc5-hqvqr -n h2ogpt
INFO 02-02 03:06:03 api_server.py:209] args: Namespace(host='0.0.0.0', port=5000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, root_path=None, middleware=[], model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='hf-internal-testing/llama-tokenizer', revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir='/workspace/.cache/huggingface/hub', load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, block_size=16, seed=1234, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=8192, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2024-02-02 03:06:06,252	INFO worker.py:1724 -- Started a local Ray instance.
INFO 02-02 03:06:07 llm_engine.py:72] Initializing an LLM engine with config: model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='hf-internal-testing/llama-tokenizer', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir='/workspace/.cache/huggingface/hub', load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, seed=1234)
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 217, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 623, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 319, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 364, in _init_engine
    return engine_class(*args, **kwargs)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 109, in __init__
    self._init_workers_ray(placement_group)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 272, in _init_workers_ray
    self._run_workers(
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 983, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/worker/worker.py", line 92, in load_model
    self.model_runner.load_model()
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 75, in load_model
    self.model = get_model(self.model_config, self.lora_config)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 88, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 332, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/weight_utils.py", line 211, in hf_model_weights_iterator
    hf_folder, hf_weights_files, use_safetensors = prepare_hf_model_weights(
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/weight_utils.py", line 155, in prepare_hf_model_weights
    file_list = fs.ls(model_name_or_path, detail=False, revision=revision)
  File "/h2ogpt_conda/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 307, in ls
    "name": path_prefix + tree_item["path"],
TypeError: string indices must be integers
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```

**Comment by puppet101** [comment]
same error, how do you solve it? @pseudotensor

**Comment by pseudotensor** [comment]
For permission denied and docker, need to add shared memory options as they document.

https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html

```
You can either use the ipc=host flag or --shm-size flag to allow the container to access the host’s shared memory. vLLM uses PyTorch, which uses shared memory to share data between processes under the hood, particularly for tensor parallel inference.
```

We use `--shm-size 10.24g` for larger models else vllm complains about amount of shared memory and it says things will be slow.

**Comment by pseudotensor** [comment]
For the `TypeError: string indices must be integers` that was bug in some mirror our company created from HF.  Actual HF itself worked and didn't throw that error.  So some new code path for vLLM talking to HF.
