### ISSUE TITLE
Ray workers fail to start when not connected to the Internet

### ISSUE THREAD

**Issue by hvenev-insait** [vllm-project/vllm#2857]
(using the official container in an isolated network)
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 217, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 623, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 319, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 364, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 109, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/engine/llm_engine.py", line 176, in _init_workers_ray
    driver_ip = get_ip()
  File "/workspace/vllm/utils.py", line 166, in get_ip
    s.connect(("8.8.8.8", 80))  # Doesn't need to be reachable
OSError: [Errno 101] Network is unreachable
```

It appears that Google Public DNS needs to be reachable after all...

**Comment by Julien-pour** [comment]
Yeah, same issue

**Comment by arifcraft** [comment]
Same problem

**Comment by ErikaaWang** [comment]
same here

**Comment by Mogreine** [comment]
same issue

**Comment by kryptec** [comment]
same issue

**Comment by youkaichao** [comment]
With the latest code, you can define a `HOST_IP` environment variable to skip this. Check https://github.com/vllm-project/vllm/pull/3419 for details.
