### ISSUE TITLE
qwen14b+vllm raise ValueError("unknown ids") ValueError: unknown ids

### ISSUE THREAD

**Issue by lin-xiaosheng** [vllm-project/vllm#2921]
When using the vllm v0.2.4 with a large model for question answering, an error is encountered during execution. The error message indicates an issue related to unknown IDs in the tokenizer.

Steps to Reproduce:

Use vllm v0.2.4 with a qwen-14b-chat model for question answering.
Execute the model for question answering.
Expected Behavior:

The model should successfully process the question and provide an answer.

Actual Behavior:

The following error is encountered during execution:
      2024-02-19 00:30:41 | ERROR | asyncio | Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f9ab24963e0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f9a9b10de10
      >)
      handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f9ab24963e0>, request_tracker=<vllm.engine.async_llm_engine.RequestTracker object at 0x7f9a9b10de10>)>
      Traceback (most recent call last):
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
          task.result()
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
          has_requests_in_progress = await self.engine_step()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 338, in engine_step
          request_outputs = await self.engine.step_async()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 199, in step_async
          return self._process_model_outputs(output, scheduler_outputs) + ignored
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
          self._process_sequence_group_outputs(seq_group, outputs)
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
          self._decode_sequence(seq, seq_group.sampling_params)
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 663, in _decode_sequence
          read_offset) = detokenize_incrementally(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer.py", line 148, in detokenize_incrementally
          new_tokens = tokenizer.convert_ids_to_tokens(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
          tokens.append(self._convert_id_to_token(index))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-self/tokenization_qwen.py", line 246, in _convert_id_to_token
          raise ValueError("unknown ids")
      ValueError: unknown ids
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
          raise exc
        File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
          raise AsyncEngineDeadError(
      vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
      INFO 02-19 00:30:41 async_llm_engine.py:134] Aborted request 86e1f10533704c518766532db0f4c8cb.
      2024-02-19 00:30:41 | ERROR | stderr | ERROR:    Exception in ASGI application
      2024-02-19 00:30:41 | ERROR | stderr | Traceback (most recent call last):
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 28, in _raise_exception_on_finish
      2024-02-19 00:30:41 | ERROR | stderr |     task.result()
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 359, in run_engine_loop
      2024-02-19 00:30:41 | ERROR | stderr |     has_requests_in_progress = await self.engine_step()
      2024-02-19 00:30:41 | ERROR | stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 338, in engine_step
      2024-02-19 00:30:41 | ERROR | stderr |     request_outputs = await self.engine.step_async()
      2024-02-19 00:30:41 | ERROR | stderr |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 199, in step_async
      2024-02-19 00:30:41 | ERROR | stderr |     return self._process_model_outputs(output, scheduler_outputs) + ignored
      2024-02-19 00:30:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 545, in _process_model_outputs
      2024-02-19 00:30:41 | ERROR | stderr |     self._process_sequence_group_outputs(seq_group, outputs)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 416, in _process_sequence_group_outputs
      2024-02-19 00:30:41 | ERROR | stderr |     self._decode_sequence(seq, seq_group.sampling_params)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 663, in _decode_sequence
      2024-02-19 00:30:41 | ERROR | stderr |     read_offset) = detokenize_incrementally(
      2024-02-19 00:30:41 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer.py", line 148, in detokenize_incrementally
      2024-02-19 00:30:41 | ERROR | stderr |     new_tokens = tokenizer.convert_ids_to_tokens(
      2024-02-19 00:30:41 | ERROR | stderr |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
      2024-02-19 00:30:41 | ERROR | stderr |     tokens.append(self._convert_id_to_token(index))
      2024-02-19 00:30:41 | ERROR | stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-self/tokenization_qwen.py", line 246, in _convert_id_to_token
      2024-02-19 00:30:41 | ERROR | stderr |     raise ValueError("unknown ids")
      2024-02-19 00:30:41 | ERROR | stderr | ValueError: unknown ids
      2024-02-19 00:30:41 | ERROR | stderr | 
      2024-02-19 00:30:41 | ERROR | stderr | The above exception was the direct cause of the following exception:
      2024-02-19 00:30:41 | ERROR | stderr | 
      2024-02-19 00:30:41 | ERROR | stderr | Traceback (most recent call last):
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
      2024-02-19 00:30:41 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
      2024-02-19 00:30:41 | ERROR | stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     return await self.app(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     await super().__call__(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     raise exc
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     await self.app(scope, receive, _send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     raise exc
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     await self.app(scope, receive, sender)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     raise e
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     await self.app(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     await route.handle(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
      2024-02-19 00:30:41 | ERROR | stderr |     await self.app(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
      2024-02-19 00:30:41 | ERROR | stderr |     await response(scope, receive, send)
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
      2024-02-19 00:30:41 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
      2024-02-19 00:30:41 | ERROR | stderr |     raise exceptions[0]
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
      2024-02-19 00:30:41 | ERROR | stderr |     await func()
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
      2024-02-19 00:30:41 | ERROR | stderr |     async for chunk in self.body_iterator:
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/autodl-tmp/FastChat/fastchat/serve/vllm_worker.py", line 113, in generate_stream
      2024-02-19 00:30:41 | ERROR | stderr |     async for request_output in results_generator:
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 444, in generate
      2024-02-19 00:30:41 | ERROR | stderr |     raise e
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 438, in generate
      2024-02-19 00:30:41 | ERROR | stderr |     async for request_output in stream:
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 70, in __anext__
      2024-02-19 00:30:41 | ERROR | stderr |     raise result
      2024-02-19 00:30:41 | ERROR | stderr |   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 37, in _raise_exception_on_finish
      2024-02-19 00:30:41 | ERROR | stderr |     raise exc
      2024-02-19 00:30:41 | ERROR | stderr |   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 32, in _raise_exception_on_finish
      2024-02-19 00:30:41 | ERROR | stderr |     raise AsyncEngineDeadError(
      2024-02-19 00:30:41 | ERROR | stderr | vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
      
      Can anyone help solve this issue? Thank you for your assistance!

**Comment by hllj** [comment]
Hello, I have the same error. How did you fix that error ?
