### ISSUE TITLE
Installing with some issues

### ISSUE THREAD

**Issue by tiandiao123** [vllm-project/vllm#297]
Hello someone know how this error caused? 
```
Obtaining file:///home/lclcq/infer_workspace/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/lclcq/miniconda3/envs/new_env2/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lclcq/miniconda3/envs/new_env2/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/lclcq/miniconda3/envs/new_env2/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-g_a1aa9s/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-g_a1aa9s/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-g_a1aa9s/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g_a1aa9s/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 59, in <module>
        File "<string>", line 34, in get_nvcc_cuda_version
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by WoosukKwon** [comment]
Hi @tiandiao123 Thanks for trying out vLLM! It's a known issue. Could you check if your machine has NVCC compiler? Please let us know the output of running `nvcc --version` on your terminal.

**Comment by tiandiao123** [comment]
> Hi @tiandiao123 Thanks for trying out vLLM! It's a known issue. Could you check if your machine has NVCC compiler? Please let us know the output of running `nvcc --version` on your terminal.

oh, looks like it is due to the reason I didn't load my cuda. after retrying, it works. Thank you!

**Comment by BUAAChuanWang** [comment]
I met same installing bug, and my nvcc -V is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

Could you help me fix it  @please?@WoosukKwon
