### ISSUE TITLE
vLLM benchmarking script do not support the openAI compatible API server.

### ISSUE THREAD

**Issue by wangchen615** [vllm-project/vllm#2993]
The benchmarking script to run is below:
```
python benchmark_serving.py --backend vllm --endpoint /v1/completions --num-prompts 1 --model mistralai/Mistral-7B-v0.1 --dataset ShareGPT_V3_unfiltered_cleaned_split.json
```

The assert only allows `/generate` endpoint for vllm backend.
```
Namespace(backend='vllm', version='N/A', base_url=None, host='localhost', port=8000, endpoint='/v1/completions', dataset='ShareGPT_V3_unfiltered_cleaned_split.json', model='mistralai/Mistral-7B-v0.1', tokenizer=None, best_of=1, use_beam_search=False, num_prompts=1, request_rate=inf, seed=0, trust_remote_code=False, disable_tqdm=False, save_result=False)
  0%|                                                                       | 0/1 [00:00<?, ?it/s]Traffic request rate: inf
Traceback (most recent call last):
  File "/home/chenw/wangchen615/vllm/benchmarks/benchmark_serving.py", line 387, in <module>
    main(args)
  File "/home/chenw/wangchen615/vllm/benchmarks/benchmark_serving.py", line 259, in main
    benchmark_result = asyncio.run(
  File "/home/chenw/miniconda3/envs/myenv/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/chenw/miniconda3/envs/myenv/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/chenw/wangchen615/vllm/benchmarks/benchmark_serving.py", line 195, in benchmark
    outputs = await asyncio.gather(*tasks)
  File "/home/chenw/wangchen615/vllm/benchmarks/backend_request_func.py", line 85, in async_request_vllm
    assert api_url.endswith("generate")
AssertionError
  0%|                                                                       | 0/1 [00:00<?, ?it/s]
  ```

**Comment by wangchen615** [comment]
The problem can be resolved via passing `openai` as the backend:

```
python benchmark_serving.py --backend openai --endpoint /v1/chat/completions --num-prompts 1 --model mistralai/Mistral-7B-v0.1 --dataset ShareGPT_V3_unfiltered_cleaned_split.json
```

```
Namespace(backend='openai', version='N/A', base_url=None, host='localhost', port=8000, endpoint='/v1/chat/completions', dataset='ShareGPT_V3_unfiltered_cleaned_split.json', model='mistralai/Mistral-7B-v0.1', tokenizer=None, best_of=1, use_beam_search=False, num_prompts=1, request_rate=inf, seed=0, trust_remote_code=False, disable_tqdm=False, save_result=False)
  0%|                                                                       | 0/1 [00:00<?, ?it/s]Traffic request rate: inf
100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.83it/s]
Successful requests: 1
Benchmark duration: 0.113540 s
Total input tokens: 515
Total generated tokens: 1
Request throughput: 8.81 requests/s
Input token throughput: 4535.85 tokens/s
Output token throughput: 8.81 tokens/s
Mean TTFT: 13.27 ms
Median TTFT: 13.27 ms
P99 TTFT: 13.27 ms
Mean TPOT: 112.18 ms
Median TPOT: 112.18 ms
P99 TPOT: 112.18 ms
```
