### ISSUE TITLE
Support Multi-gpus inference on 3090s

### ISSUE THREAD

**Issue by xcxhy** [vllm-project/vllm#308]
Hi, I can successfully infer with a single 3090, but setting tensor_parallel_size=2 throws the following error:
Traceback (most recent call last):
  File "test_batch.py", line 78, in <module>
    llm = LLM(model=args.model_path, tensor_parallel_size=2)
  File "/data/xuhao/xcxhy/vllm/vllm/entrypoints/llm.py", line 55, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/data/xuhao/xcxhy/vllm/vllm/engine/llm_engine.py", line 151, in from_engine_args
    engine = cls(*engine_configs, distributed_init_method, devices,
  File "/data/xuhao/xcxhy/vllm/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_cache()
  File "/data/xuhao/xcxhy/vllm/vllm/engine/llm_engine.py", line 114, in _init_cache
    num_blocks = self._run_workers(
  File "/data/xuhao/xcxhy/vllm/vllm/engine/llm_engine.py", line 317, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/data/anaconda3/envs/LLM-INFER/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/LLM-INFER/lib/python3.8/site-

packages/ray/_private/worker.py", line 2523, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::Worker.__init__() (pid=1330513, ip=192.168.25.186, repr=<vllm.worker.worker.Worker object at 0x7f02983857f0>)
  File "/data/xuhao/xcxhy/vllm/vllm/worker/worker.py", line 40, in __init__
    _init_distributed_environment(parallel_config, rank,
  File "/data/xuhao/xcxhy/vllm/vllm/worker/worker.py", line 302, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/data/anaconda3/envs/LLM-INFER/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/LLM-INFER/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroup

NCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Cuda failure 'peer access is not supported between these two devices'
(Worker pid=1330514) 2023-06-29 19:32:39,164    ERROR worker.py:844 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::Worker.__init__() (pid=1330514, ip=192.168.25.186, repr=<vllm.worker.worker.Worker object at 0x7f4aedfef760>)
(Worker pid=1330514)   File "/data/xuhao/xcxhy/vllm/vllm/worker/worker.py", line 40, in __init__
(Worker pid=1330514)     _init_distributed_environment(parallel_config, rank,
(Worker pid=1330514)   File "/data/xuhao/xcxhy/vllm/vllm/worker/worker.py", line 302, in _init_distributed_environment
(Worker pid=1330514)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(Worker pid=1330514)   File "/data/anaconda3/envs/LLM-INFER/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(Worker pid=1330514 .....
I have checked some methods, is it because I have not installed or the current nccl version is wrong, or is it because my 3090 does not enable nvlink or does not support nvlink?

**Comment by zhuohan123** [comment]
Can you try to run with `NCCL_P2P_DISABLE=1`? This disables nvlink.

**Comment by zhuohan123** [comment]
This issue should be fixed by #397

**Comment by hmellor** [comment]
Closing because #397 is merged
