### ISSUE TITLE
Model not supporting: internlm/internlm-xcomposer2-7b

### ISSUE THREAD

**Issue by code959437957** [vllm-project/vllm#3101]
···
ValueError: Model architectures ['InternLMXComposer2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OLMoForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM']
···

I am trying to run
```
python -m vllm.entrypoints.openai.api_server --model internlm/internlm-xcomposer2-7b --trust-remote-code
```

**Comment by topa-22** [comment]
> ··· ValueError: Model architectures ['InternLMXComposer2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OLMoForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM'] ···
> 
> I am trying to run
> 
> ```
> python -m vllm.entrypoints.openai.api_server --model internlm/internlm-xcomposer2-7b --trust-remote-code
> ```

This is what I encountered when I tried to load it in vLLM. Any luck?

**Comment by lingffff** [comment]
Same problem. Any update? @code959437957 @topa-22

**Comment by fullstackwebdev** [comment]
same, 0.5.4 docker:

```
[+] Running 1/1
 ✔ Container vllm-vllm-service-1  Recreated                                                                                                                                          0.1s 
Attaching to vllm-service-1
vllm-service-1  | INFO 08-07 17:33:32 api_server.py:339] vLLM API server version 0.5.4
vllm-service-1  | INFO 08-07 17:33:32 api_server.py:340] args: Namespace(host=None, port=6002, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='/models/internlm-xcomposer2d5-7b', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.85, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['anthropic/claude-3-haiku:beta'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
vllm-service-1  | WARNING 08-07 17:33:32 config.py:1454] Casting torch.bfloat16 to torch.float16.
vllm-service-1  | WARNING 08-07 17:33:32 arg_utils.py:766] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
vllm-service-1  | INFO 08-07 17:33:32 config.py:820] Chunked prefill is enabled with max_num_batched_tokens=512.
vllm-service-1  | INFO 08-07 17:33:32 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='/models/internlm-xcomposer2d5-7b', speculative_config=None, tokenizer='/models/internlm-xcomposer2d5-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=49152, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=anthropic/claude-3-haiku:beta, use_v2_block_manager=False, enable_prefix_caching=False)
vllm-service-1  | WARNING 08-07 17:33:32 tokenizer.py:129] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
vllm-service-1  | INFO 08-07 17:33:32 model_runner.py:720] Starting to load model /models/internlm-xcomposer2d5-7b...
vllm-service-1  | Process Process-1:
vllm-service-1  | Traceback (most recent call last):
vllm-service-1  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
vllm-service-1  |     self.run()
vllm-service-1  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
vllm-service-1  |     self._target(*self._args, **self._kwargs)
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 217, in run_rpc_server
vllm-service-1  |     server = AsyncEngineRPCServer(async_engine_args, usage_context, port)
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 25, in __init__
vllm-service-1  |     self.engine = AsyncLLMEngine.from_engine_args(async_engine_args,
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 471, in from_engine_args
vllm-service-1  |     engine = cls(
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 381, in __init__
vllm-service-1  |     self.engine = self._init_engine(*args, **kwargs)
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 552, in _init_engine
vllm-service-1  |     return engine_class(*args, **kwargs)
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 249, in __init__
vllm-service-1  |     self.model_executor = executor_class(
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 47, in __init__
vllm-service-1  |     self._init_executor()
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 36, in _init_executor
vllm-service-1  |     self.driver_worker.load_model()
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 139, in load_model
vllm-service-1  |     self.model_runner.load_model()
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 722, in load_model
vllm-service-1  |     self.model = get_model(model_config=self.model_config,
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
vllm-service-1  |     return loader.load_model(model_config=model_config,
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/loader.py", line 324, in load_model
vllm-service-1  |     model = _initialize_model(model_config, self.load_config,
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/loader.py", line 151, in _initialize_model
vllm-service-1  |     model_class = get_model_architecture(model_config)[0]
vllm-service-1  |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/utils.py", line 35, in get_model_architecture
vllm-service-1  |     raise ValueError(
vllm-service-1  | ValueError: Model architectures ['InternLMXComposer2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'Blip2ForConditionalGeneration', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'FalconForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'InternVLChatModel', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'MiniCPMV', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PaliGemmaForConditionalGeneration', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi3VForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MedusaModel', 'MLPSpeculatorPreTrainedModel', 'JambaForCausalLM', 'MistralModel']
```
