### ISSUE TITLE
ModuleNotFoundError: No module named 'outlines.fsm'

### ISSUE THREAD

**Issue by zzlgreat** [vllm-project/vllm#3139]
python -m vllm.entrypoints.openai.api_server --model /datas/models/deepmoney-miqu-2-70b-awq --tensor-parallel-size 4 --enforce-eager --chat-template ./examples/template_chatml.jinja
Traceback (most recent call last):
  File "/root/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/DATA4T/text-generation-webui/vllm/vllm/entrypoints/openai/api_server.py", line 22, in <module>
    from vllm.entrypoints.openai.serving_chat import OpenAIServingChat
  File "/DATA4T/text-generation-webui/vllm/vllm/entrypoints/openai/serving_chat.py", line 15, in <module>
    from vllm.model_executor.guided_decoding import get_guided_decoding_logits_processor
  File "/DATA4T/text-generation-webui/vllm/vllm/model_executor/guided_decoding.py", line 12, in <module>
    from vllm.model_executor.guided_logits_processors import JSONLogitsProcessor, RegexLogitsProcessor
  File "/DATA4T/text-generation-webui/vllm/vllm/model_executor/guided_logits_processors.py", line 23, in <module>
    from outlines.fsm.fsm import RegexFSM
ModuleNotFoundError: No module named 'outlines.fsm'

CUDA12.1
installed by `python setup.py develop`

**Comment by simon-mo** [comment]
Please run `pip install -r requirements.txt` or `pip install -e . --verbose` to update the dependency requirements.

**Comment by datadriftershow** [comment]
This code expects a very specific version of outlines, that is not specified. the latest version doesn't have `outlines.fsm` , I found `0.2.3` has `outlines.fsm` but no `outlines.fsm.fsm` and I am still searching for the required dependency version.

To handle this issue long term, please consider declaring the actual version of outlines vllm depends on so that others can have an easier time reproducing the build.

**Comment by datadriftershow** [comment]
### Workaround

I found that the fsm file was moved to a different location starting from 0.1.0, so I changed my requirements.txt entry to outlines<0.1.0.

**Comment by datadriftershow** [comment]
Thanks for the hard work, Simon. VLLM is a very interesting project.
