### ISSUE TITLE
RunTime Error: Cannot find CUDA at CUDA_HOME

### ISSUE THREAD

**Issue by DanNguyenN** [vllm-project/vllm#315]
running ```nvcc -V``` results
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

I am currently in a Conda environment. But I receive RunTime error when attempting to install vllm
```
 No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      Traceback (most recent call last):
        File "C:\Users\danng\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\danng\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\danng\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel   
          return hook(config_settings)
        File "C:\Users\danng\AppData\Local\Temp\pip-build-env-c61dnyp7\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\danng\AppData\Local\Temp\pip-build-env-c61dnyp7\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\danng\AppData\Local\Temp\pip-build-env-c61dnyp7\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup  
          exec(code, locals())
        File "<string>", line 24, in <module>
      RuntimeError: Cannot find CUDA at CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8. CUDA must be available in order to build the package.
```

**Comment by zhuohan123** [comment]
Hi, we currently do not support windows. Can you try to run vLLM in WSL2?
