### ISSUE TITLE
ValueError: The precision of the fractional quantity of resource node:172.16.95.108 cannot go beyond 0.0001

### ISSUE THREAD

**Issue by mymusise** [vllm-project/vllm#317]
Hi, I got a error when I running the example of Distributed Inference and Serving:
```
from vllm import LLM
llm = LLM("facebook/opt-13b", tensor_parallel_size=4)
output = llm.generate("San Franciso is a")
```

## Traceback info:
```
ValueError                                Traceback (most recent call last)
Cell In[1], line 2
      1 from vllm import LLM
----> 2 llm = LLM("facebook/opt-13b", tensor_parallel_size=4)
      3 output = llm.generate("San Franciso is a")

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/entrypoints/llm.py:55, in LLM.__init__(self, model, tensor_parallel_size, dtype, seed, **kwargs)
     47     kwargs["disable_log_stats"] = True
     48 engine_args = EngineArgs(
     49     model=model,
     50     tensor_parallel_size=tensor_parallel_size,
   (...)
     53     **kwargs,
     54 )
---> 55 self.llm_engine = LLMEngine.from_engine_args(engine_args)
     56 self.request_counter = Counter()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/engine/llm_engine.py:145, in LLMEngine.from_engine_args(cls, engine_args)
    143 distributed_init_method, devices = initialize_cluster(parallel_config)
    144 # Create the LLM engine.
--> 145 engine = cls(*engine_configs, distributed_init_method, devices,
    146              log_stats=not engine_args.disable_log_stats)
    147 return engine

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/engine/llm_engine.py:87, in LLMEngine.__init__(self, model_config, cache_config, parallel_config, scheduler_config, distributed_init_method, stage_devices, log_stats)
     85 worker_cls = Worker
     86 if self.parallel_config.worker_use_ray:
---> 87     worker_cls = ray.remote(
     88         num_cpus=0,
     89         num_gpus=1,
     90         resources={node_resource: 1e-5},
     91     )(worker_cls).remote
     93 worker = worker_cls(
     94     model_config,
     95     parallel_config,
   (...)
     98     distributed_init_method,
     99 )
    100 self.workers.append(worker)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/worker.py:2879, in _make_remote(function_or_class, options)
   2871     return ray.remote_function.RemoteFunction(
   2872         Language.PYTHON,
   2873         function_or_class,
   2874         None,
   2875         options,
   2876     )
   2878 if inspect.isclass(function_or_class):
-> 2879     ray_option_utils.validate_actor_options(options, in_options=False)
   2880     return ray.actor._make_actor(function_or_class, options)
   2882 raise TypeError(
   2883     "The @ray.remote decorator must be applied to either a function or a class."
   2884 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/ray_option_utils.py:308, in validate_actor_options(options, in_options)
    303     if k not in actor_options:
    304         raise ValueError(
    305             f"Invalid option keyword {k} for actors. "
    306             f"Valid ones are {list(actor_options)}."
    307         )
--> 308     actor_options[k].validate(k, v)
    310 if in_options and "concurrency_groups" in options:
    311     raise ValueError(
    312         "Setting 'concurrency_groups' is not supported in '.options()'."
    313     )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/ray_option_utils.py:38, in Option.validate(self, keyword, value)
     36 possible_error_message = self.value_constraint(value)
     37 if possible_error_message:
---> 38     raise ValueError(possible_error_message)

ValueError: The precision of the fractional quantity of resource node:172.16.95.108 cannot go beyond 0.0001
```

I'm not very familiar with distribution, what shou I do?

**Comment by WoosukKwon** [comment]
@mymusise Thanks for reporting this. I think the problem was fixed in v0.1.1. Could you re-install vLLM and try again?

**Comment by mymusise** [comment]
thanks @WoosukKwon  , after reinstall vllm in v0.1.1.  I got another problem

## Traceback info
```
(Worker pid=333) 2023-06-30 07:19:07,337	ERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::Worker.__init__() (pid=333, ip=172.16.3.160, actor_id=112cd718c133c10529db170301000000, repr=<vllm.worker.worker.Worker object at 0x7ef681038220>)
(Worker pid=333)   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/worker/worker.py", line 40, in __init__
(Worker pid=333)     _init_distributed_environment(parallel_config, rank,
(Worker pid=333)   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/worker/worker.py", line 304, in _init_distributed_environment
(Worker pid=333)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(Worker pid=333)   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(Worker pid=333)     return func(*args, **kwargs)
(Worker pid=333)   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(Worker pid=333)     work = default_pg.allreduce([tensor], opts)
(Worker pid=333) torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(Worker pid=333) ncclInternalError: Internal check failed.
(Worker pid=333) Last error:
(Worker pid=333) Cuda failure 'peer access is not supported between these two devices'
---------------------------------------------------------------------------
RayActorError                             Traceback (most recent call last)
Cell In[1], line 2
      1 from vllm import LLM
----> 2 llm = LLM("facebook/opt-13b", tensor_parallel_size=4)
      3 output = llm.generate("San Franciso is a")

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/entrypoints/llm.py:62, in LLM.__init__(self, model, tokenizer, tokenizer_mode, tensor_parallel_size, dtype, seed, **kwargs)
     52     kwargs["disable_log_stats"] = True
     53 engine_args = EngineArgs(
     54     model=model,
     55     tokenizer=tokenizer,
   (...)
     60     **kwargs,
     61 )
---> 62 self.llm_engine = LLMEngine.from_engine_args(engine_args)
     63 self.request_counter = Counter()

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/engine/llm_engine.py:155, in LLMEngine.from_engine_args(cls, engine_args)
    153 distributed_init_method, devices = initialize_cluster(parallel_config)
    154 # Create the LLM engine.
--> 155 engine = cls(*engine_configs, distributed_init_method, devices,
    156              log_stats=not engine_args.disable_log_stats)
    157 return engine

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/engine/llm_engine.py:106, in LLMEngine.__init__(self, model_config, cache_config, parallel_config, scheduler_config, distributed_init_method, stage_devices, log_stats)
    104     self.workers.append(worker)
    105 # Profile the memory usage and initialize the cache.
--> 106 self._init_cache()
    108 # Create the scheduler.
    109 self.scheduler = Scheduler(scheduler_config, cache_config, log_stats)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/engine/llm_engine.py:118, in LLMEngine._init_cache(self)
    116 """Profiles the memory usage and initializes the KV cache."""
    117 # Get the maximum number of blocks that can be allocated on GPU and CPU.
--> 118 num_blocks = self._run_workers(
    119     "profile_num_available_blocks",
    120     get_all_outputs=True,
    121     block_size=self.cache_config.block_size,
    122     gpu_memory_utilization=self.cache_config.gpu_memory_utilization,
    123     cpu_swap_space=self.cache_config.swap_space_bytes,
    124 )
    126 # Since we use a shared centralized controller, we take the minimum
    127 # number of blocks across all workers to make sure all the memory
    128 # operators can be applied to all workers.
    129 num_gpu_blocks = min(b[0] for b in num_blocks)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/engine/llm_engine.py:321, in LLMEngine._run_workers(self, method, get_all_outputs, *args, **kwargs)
    318     all_outputs.append(output)
    320 if self.parallel_config.worker_use_ray:
--> 321     all_outputs = ray.get(all_outputs)
    323 if get_all_outputs:
    324     return all_outputs

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/auto_init_hook.py:18, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/worker.py:2542, in get(object_refs, timeout)
   2540             raise value.as_instanceof_cause()
   2541         else:
-> 2542             raise value
   2544 if is_individual_id:
   2545     values = values[0]

RayActorError: The actor died because of an error raised in its creation task, ray::Worker.__init__() (pid=334, ip=172.16.3.160, actor_id=320ef7135572cdd0cf623a4701000000, repr=<vllm.worker.worker.Worker object at 0x7f8d148d4220>)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/worker/worker.py", line 40, in __init__
    _init_distributed_environment(parallel_config, rank,
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/vllm/worker/worker.py", line 304, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Cuda failure 'peer access is not supported between these two devices'
```

**Comment by WoosukKwon** [comment]
@mymusise Could you run with `NCCL_P2P_DISABLE=1`? Or, could you run with `CUDA_VISIBLE_DEVICES=0` and try a smaller model like `facebook/opt-125m`?

**Comment by mymusise** [comment]
@WoosukKwon  I didn't set `NCCL_P2P_DISABLE ` and `CUDA_VISIBLE_DEVICES `, there're the `None` value on `os.environ`.

I'try `facebook/opt-125m` with `tensor_parallel_size=4`, got the same error.

but it's ok to run in a single gpu without error.

**Comment by WoosukKwon** [comment]
@mymusise I mean, could you add `NCCL_P2P_DISABLE=1` to your env variables and check whether this resolves the issue? One of the users reported that this env variable is necessary for machine with multiple RTX40** GPUs.

**Comment by mymusise** [comment]
Thanks @WoosukKwon , with setting `NCCL_P2P_DISABLE=1`, it work now!
