### ISSUE TITLE
'SamplingParams' object has no attribute update

### ISSUE THREAD

**Issue by adamxyang** [vllm-project/vllm#3214]
Hi, I got this error after updating `vllm` and `transformers`:

```
Traceback (most recent call last):
File "/user/work/ad20999/1lm-rephrase/evaluate_gpt_rephrase_vllm.py", line 576, in <module>
    main()
File "/user/work/ad20999/1lm-rephrase/evaluate_gpt_rephrase_vllm.py", line 480, in main
    outputs = model.generate(inputs, sampling_params)
File "/user/work/ad20999/anaconda3/envs/vltm/lib/python3.10/site-packages/awq/models/base.py", line 110, in generate
    return self.model.generate(*args, **kwargs)
File "/user/work/ad20999/anaconda3/envs/vltm/lib/python3.10/site-packages/torch/utils/contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
File "/user/work/ad20999/anaconda3/envs/vltm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1349, in generate
    model_kwargs = generation_config.update(**kwargs) # All unused kwargs must be model kwargs
AttributeError: 'SamplingParams' object has no attribute 'update'
```

**Comment by simon-mo** [comment]
```
model.generate(inputs, sampling_params)
```

The `model` seems to be a huggingface model, not a `LLM` object from vLLM, while `sampling_params` might be vLLM types.

**Comment by adamxyang** [comment]
Hi Simon, thanks for your swift reply! I loaded a quantised model with `model = LLM(model="TheBloke/Llama-2-7B-chat-AWQ", quantization="awq")`, the same piece of code worked before the update.
