### ISSUE TITLE
Issues with installing from source due to flash-attn subprocess install

### ISSUE THREAD

**Issue by mgoin** [vllm-project/vllm#3265]
I only see this issue after https://github.com/vllm-project/vllm/pull/3005 landed. I've run into the same behavior on two GPU instances that I've used to build vLLM before just a few days ago. The main warning/error seems to be:
```
      /tmp/pip-build-env-uskajsfq/overlay/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      /root/nm/bin/python3: No module named pip
```
I'm not sure what to make of it, but it seems to be creating a different sub-environment and trying to use that. I definitely have things like `numpy` and `pip` installed.

Here is my full log running `pip install -e .` with a freshly cloned repo and environment:
```
root@engine-574cfd5988-947g9:~/vllm# pip install -e .
Obtaining file:///root/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /tmp/pip-build-env-uskajsfq/overlay/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      /root/nm/bin/python3: No module named pip
      Traceback (most recent call last):
        File "/root/nm/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/root/nm/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/nm/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-uskajsfq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-uskajsfq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-uskajsfq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-uskajsfq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 335, in <module>
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/root/nm/bin/python3', '-m', 'pip', 'install', '-q', '--target=/root/vllm/vllm/thirdparty_files', 'einops', 'flash-attn==2.5.6', '--no-dependencies']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by mgoin** [comment]
Should be addressed by https://github.com/vllm-project/vllm/pull/3269 which has landed on main
