### ISSUE TITLE
install from source failed using the latest code

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#3276]
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com                                                                                                                      Obtaining file:///data/weilong.yu/github/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done                                                                                                                                    Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      /tmp/pip-build-env-30uui0su/overlay/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered i
nternally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      <string>:220: UserWarning: Unsupported CUDA architectures ({'5.2', '7.2', '8.7', '6.0', '6.1'}) are excluded from the `TORCH_CUDA_ARCH_LIST` env variable (5.2 6.0 6.1 7.0 7.2 7.5 8.0 8
.6 8.7 9.0+PTX). Supported CUDA architectures are: {'8.6', '9.0', '8.0+PTX', '8.9+PTX', '8.0', '8.9', '8.6+PTX', '7.5+PTX', '7.0+PTX', '7.5', '9.0+PTX', '7.0'}.
      /usr/bin/python: No module named pip
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-30uui0su/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)                                                                                                                                   File "/tmp/pip-build-env-30uui0su/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-30uui0su/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-30uui0su/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 335, in <module>
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '-q', '--target=/data/weilong.yu/github/vllm/vllm/thirdparty_files', 'einops', 'flash-attn==2.5.6',
'--no-dependencies']' returned non-zero exit status 1.
      [end of output]
```

**Comment by hmellor** [comment]
- What command did you use to install from source?
- What version of cuda do you have installed?

**Comment by aliozts** [comment]
happened to me as well on a 2L4 GCP instance, 

first ran the docker image for proper build there,

```bash
docker run --gpus all -it --rm --ipc=host nvcr.io/nvidia/pytorch:23.10-py3
```

ran the command

```bash
export VLLM_INSTALL_PUNICA_KERNELS=1
git clone https://github.com/vllm-project/vllm.git
cd vllm
pip install -e .
```

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///workspace/vllm
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      /tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      <string>:220: UserWarning: Unsupported CUDA architectures ({'6.1', '8.7', '6.0', '5.2', '7.2'}) are excluded from the `TORCH_CUDA_ARCH_LIST` env variable (5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX). Supported CUDA architectures are: {'8.6', '9.0', '9.0+PTX', '8.9+PTX', '7.5+PTX', '8.6+PTX', '8.0+PTX', '8.9', '7.0+PTX', '7.5', '7.0', '8.0'}.
      /usr/bin/python: No module named pip
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 335, in <module>
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '-q', '--target=/workspace/vllm/vllm/thirdparty_files', 'einops', 'flash-attn==2.5.6', '--no-dependencies']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

sorry if duplicate comment

**Comment by sleepwalker2017** [comment]
> * What command did you use to install from source?
> * What version of cuda do you have installed?

`pip install -e .`
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |

commit 1ece1ae829dcbc4b1b19b3e2d3042457615e862f (HEAD -> main, origin/main, origin/HEAD)

**Comment by sleepwalker2017** [comment]
> happened to me as well on a 2L4 GCP instance,
> 
> first ran the docker image for proper build there,
> 
> ```shell
> docker run --gpus all -it --rm --ipc=host nvcr.io/nvidia/pytorch:23.10-py3
> ```
> 
> ran the command
> 
> ```shell
> export VLLM_INSTALL_PUNICA_KERNELS=1
> git clone https://github.com/vllm-project/vllm.git
> cd vllm
> pip install -e .
> ```
> 
> ```
> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> Obtaining file:///workspace/vllm
>   Installing build dependencies ... done
>   Checking if build backend supports build_editable ... done
>   Getting requirements to build editable ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build editable did not run successfully.
>   │ exit code: 1
>   ╰─> [23 lines of output]
>       /tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
>         device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
>       <string>:220: UserWarning: Unsupported CUDA architectures ({'6.1', '8.7', '6.0', '5.2', '7.2'}) are excluded from the `TORCH_CUDA_ARCH_LIST` env variable (5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX). Supported CUDA architectures are: {'8.6', '9.0', '9.0+PTX', '8.9+PTX', '7.5+PTX', '8.6+PTX', '8.0+PTX', '8.9', '7.0+PTX', '7.5', '7.0', '8.0'}.
>       /usr/bin/python: No module named pip
>       Traceback (most recent call last):
>         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
>           return hook(config_settings)
>         File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 448, in get_requires_for_build_editable
>           return self.get_requires_for_build_wheel(config_settings)
>         File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>         File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-g6mtcqwi/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 311, in run_setup
>           exec(code, locals())
>         File "<string>", line 335, in <module>
>         File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', '-q', '--target=/workspace/vllm/vllm/thirdparty_files', 'einops', 'flash-attn==2.5.6', '--no-dependencies']' returned non-zero exit status 1.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build editable did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```
> 
> sorry if duplicate comment

Yes, the same .

**Comment by leonardxie** [comment]
the same problem

**Comment by hmellor** [comment]
Stale
