### ISSUE TITLE
[Feature request] Support CohereForCausalLM

### ISSUE THREAD

**Issue by Peter-Devine** [vllm-project/vllm#3335]
Would it be possible you add support for CohereForCausalLM?

Here is the model:

https://huggingface.co/CohereForAI/c4ai-command-r-v01

It's a very capable model that supports many languages (including some not supported by many other models like Vietnamese and Persian) so I think it will be quite widely used by the non-English AI community.

Thanks!

**Comment by pseudotensor** [comment]
Ya right now even for trust_remote_code with registration of the methods, which works for transformers, this fails for vllm

```
(vllm2) fsuser@e2e-77-235:~$ python
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vllm import LLM, SamplingParams
>>> llm = LLM(model="CohereForAI/c4ai-command-r-v01", trust_remote_code=True)
INFO 03-12 11:27:50 llm_engine.py:87] Initializing an LLM engine with config: model='CohereForAI/c4ai-command-r-v01', tokenizer='CohereForAI/c4ai-command-r-v01', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 109, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 391, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 128, in __init__
    self._init_workers()
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 181, in _init_workers
    self._run_workers("load_model")
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 1041, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/worker/worker.py", line 100, in load_model
    self.model_runner.load_model()
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/worker/model_runner.py", line 88, in load_model
    self.model = get_model(self.model_config,
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/model_executor/utils.py", line 52, in get_model
    return get_model_fn(model_config, device_config, **kwargs)
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/model_executor/model_loader.py", line 43, in get_model
    model_class = _get_model_architecture(model_config)
  File "/home/fsuser/miniconda3/envs/vllm2/lib/python3.8/site-packages/vllm/model_executor/model_loader.py", line 35, in _get_model_architecture
    raise ValueError(
ValueError: Model architectures ['CohereForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OLMoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM']
>>> 

```

**Comment by simon-mo** [comment]
Dup of #3330, vLLM does require custom model implementation. See https://docs.vllm.ai/en/latest/models/adding_model.html.
