### ISSUE TITLE
GPU Stuck

### ISSUE THREAD

**Issue by MasKong** [vllm-project/vllm#338]
<img width="966" alt="image" src="https://github.com/vllm-project/vllm/assets/23203109/ae28b18c-568d-49da-95f2-c039644dc19d">

I am using the vllm 0.1.1 version, Ubuntu 18.04. There is a server with 4 T4 GPU cards. 
I started 4 tasks simultaneously. But it seems that 2 out of 4 GPU was stuck.
May I ask why?

### multi-GPU offline inference
And When I try to run multi-GPU offline inference, it returns an error: the actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
The actor never ran - it was cancelled before it started running.

Unhandled exception: St13runtime_error. what(): NCCL Error 5: invalid usage

**Comment by amazingkmy** [comment]
i also have same issue

**Comment by MasKong** [comment]
> i also have same issue, when i run "python -m vllm.entrypoints.api_server --tensor-parallel-size 4"

INFO 07-06 09:05:55 scheduler.py:254] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%

It seems that there is a problem during scheduling

**Comment by MasKong** [comment]
> Could you provide the minimum code to reproduce the problem? Thanks a lot!

The code is basically the same as the given example. The amount of data is around 1 million. Sometimes it got stuck after a few iterations. And sometimes it could run for more than a day without any problem....

And it seems that it worked after upgrading to version 0.1.2. So far I have run for 2 days and there is no problem. Thanks for your reply.

```
llm = LLM(model=model_path, tokenizer_mode='auto', tensor_parallel_size=tensor_parallel_size, swap_space=4, gpu_memory_utilization=0.9)
sampling_params = SamplingParams(temperature=0.1, top_k=-1, max_tokens=max_new_tokens, top_p=1)
outputs = llm.generate(part_batch_prompt, sampling_params, req_ids=part_req_ids, use_tqdm=True)
```

**Comment by MasKong** [comment]
> Could you provide the minimum code to reproduce the problem? Thanks a lot!

The following command is employed to run inference code. And 2 out of 4 processes in a same server were killed. Is there any performance tuning instruction to avoid this problem? 
```
RAY_memory_monitor_refresh_ms=0 NCCL_P2P_DISABLE=1 CUDA_VISIBLE_DEVICES=1 python generate.py
```

**Comment by nootums** [comment]
I'm facing this issue on 0.1.2 as well. 
I am trying to load llama-2-7b-chat-hf on 4 GPUs and it gets stuck loading the model. It gets stuck after VRAM usage hits 3919MB per GPU
<img width="639" alt="image" src="https://github.com/vllm-project/vllm/assets/65669681/46812a7b-ba37-479c-a0e2-b2aef6bcf91f">
Any way to fix this?

**Comment by Tomorrowxxy** [comment]
#677 Same problem. Urgent need to solve

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by lzgkeegan-collab** [comment]
(APIServer pid=1) INFO:     10.0.4.214:32768 - "GET /health HTTP/1.1" 200 OK
(APIServer pid=1) INFO:     10.0.4.214:32770 - "GET /health HTTP/1.1" 200 OK
(APIServer pid=1) INFO:     10.0.2.219:57232 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request
(APIServer pid=1) INFO:     10.0.2.219:57246 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request
(APIServer pid=1) INFO:     10.0.2.219:57232 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request
(APIServer pid=1) INFO:     10.0.2.219:57246 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request
(EngineCore pid=327) WARNING 09-22 11:25:05 [core.py:1868] Multi-modal cache miss for request embd-b9fdf6ceaefe060a-0-8ffd20d6 (mm_hashes=['a9a6596bbb3daa56b48bb06d812603c75383d8c52889c5c0c37d3e21af7a74a7']): P0/P1 cache drift; returning a retryable response so the items are resent with data.
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843] AsyncLLM output_handler failed.
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843] Traceback (most recent call last):
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 804, in output_handler
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843]     processed_outputs = output_processor.process_outputs(
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 696, in process_outputs
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843]     assert req_state.detokenizer is not None
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 09-22 11:25:05 [async_llm.py:843] AssertionError
(APIServer pid=1) INFO:     10.0.2.219:57232 - "POST /v1/embeddings HTTP/1.1" 500 Internal Server Error
(APIServer pid=1) INFO:     10.0.2.219:57246 - "POST /v1/embeddings HTTP/1.1" 400 Bad Request
(APIServer pid=1) INFO:     Shutting down
(APIServer pid=1) INFO:     Waiting for application shutdown.
(APIServer pid=1) INFO:     Application shutdown complete.
(APIServer pid=1) INFO:     Finished server process [1]
(APIServer pid=1) INFO 09-22 11:25:05 [core_client.py:744] [shutdown] MPClient: start timeout=0s
(APIServer pid=1) INFO 09-22 11:25:05 [core_client.py:746] [shutdown] MPClient: stopping engine manager
(APIServer pid=1) INFO 09-22 11:25:05 [utils.py:632] [shutdown] Process manager: send sigterm to process EngineCore
(APIServer pid=1) WARNING 09-22 11:25:05 [utils.py:652] [shutdown] Process manager: force killing remaining processes count=1
(APIServer pid=1) WARNING 09-22 11:25:05 [utils.py:657] [shutdown] Process manager: force killing remaining process EngineCore pid 327
(EngineCore pid=327) INFO 09-22 11:25:05 [core.py:1342] [shutdown] EngineCore: trigger received signal=SIGTERM
(EngineCore pid=327) INFO 09-22 11:25:05 [core.py:1493] [shutdown] EngineCore: start mode=abort timeout=0s
(EngineCore pid=327) INFO 09-22 11:25:05 [core.py:1524] [shutdown] EngineCore: request processing complete; starting resource teardown
(EngineCore pid=327) INFO 09-22 11:25:05 [core.py:1355] [shutdown] EngineCore: exiting busy loop
(EngineCore pid=327) INFO 09-22 11:25:05 [multiproc_executor.py:472] [shutdown] Executor: waiting for worker exit count=2
(Worker_TP0 pid=495) INFO 09-22 11:25:05 [multiproc_executor.py:836] Parent process exited, terminating worker queues
(APIServer pid=1) INFO 09-22 11:25:05 [core_client.py:748] [shutdown] MPClient: engine manager stopped
(APIServer pid=1) INFO 09-22 11:25:05 [core_client.py:749] [shutdown] MPClient: cleaning up background resources
(APIServer pid=1) INFO 09-22 11:25:05 [core_client.py:751] [shutdown] MPClient: complete
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 4 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
