### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by mcleish7** [vllm-project/vllm#3387]
I am getting the error `ImportError: libcudart.so.11.0: cannot open shared object file: No such file or director` when using apptainer to run the docker image, I installed vllm from source today using Python 3.10.4

Details:
- Installed from source today (13th March) with CUDA: cuda/12.1.1
- Using Apptainer to run: `apptainer run --nv /cmlscratch/smcleish/lm_doc/vllm-openai_latest.sif`

Full Error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/cmlscratch/smcleish/lm_doc/vllm/entrypoints/openai/api_server.py", line 250, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/async_llm_engine.py", line 338, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/async_llm_engine.py", line 309, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/async_llm_engine.py", line 409, in _init_engine
    return engine_class(*args, **kwargs)
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/llm_engine.py", line 101, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/cmlscratch/smcleish/lm_doc/vllm/executor/gpu_executor.py", line 42, in __init__
    self._init_worker()
  File "/cmlscratch/smcleish/lm_doc/vllm/executor/gpu_executor.py", line 77, in _init_worker
    self.driver_worker.load_model()
  File "/cmlscratch/smcleish/lm_doc/vllm/worker/worker.py", line 99, in load_model
    self.model_runner.load_model()
  File "/cmlscratch/smcleish/lm_doc/vllm/worker/model_runner.py", line 89, in load_model
    self.model = get_model(self.model_config,
  File "/cmlscratch/smcleish/lm_doc/vllm/model_executor/utils.py", line 49, in get_model
    imported_model_loader = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/cmlscratch/smcleish/lm_doc/vllm/model_executor/model_loader.py", line 10, in <module>
    from vllm.model_executor.weight_utils import (get_quant_config,
  File "/cmlscratch/smcleish/lm_doc/vllm/model_executor/weight_utils.py", line 18, in <module>
    from vllm.model_executor.layers.quantization import (get_quantization_config,
  File "/cmlscratch/smcleish/lm_doc/vllm/model_executor/layers/quantization/__init__.py", line 5, in <module>
    from vllm.model_executor.layers.quantization.awq import AWQConfig
  File "/cmlscratch/smcleish/lm_doc/vllm/model_executor/layers/quantization/awq.py", line 6, in <module>
    from vllm._C import ops
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```
Installs:
```
Package                   Version      Editable project location
------------------------- ------------ ---------------------------
aiosignal                 1.3.1
annotated-types           0.6.0
anyio                     4.3.0
attrs                     23.2.0
Brotli                    1.0.9
certifi                   2024.2.2
charset-normalizer        2.0.4
click                     8.1.7
cloudpickle               3.0.0
cupy-cuda12x              12.1.0
diskcache                 5.6.3
exceptiongroup            1.2.0
fastapi                   0.110.0
fastrlock                 0.8.2
filelock                  3.13.1
frozenlist                1.4.1
fsspec                    2024.2.0
gmpy2                     2.1.2
h11                       0.14.0
httptools                 0.6.1
huggingface-hub           0.21.4
idna                      3.4
interegular               0.3.3
Jinja2                    3.1.3
joblib                    1.3.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
lark                      1.1.9
llvmlite                  0.42.0
MarkupSafe                2.1.3
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mpmath                    1.3.0
msgpack                   1.0.8
nest-asyncio              1.6.0
networkx                  3.1
ninja                     1.11.1.1
numba                     0.59.0
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.4.99
nvidia-nvtx-cu12          12.1.105
outlines                  0.0.36
packaging                 24.0
pillow                    10.2.0
pip                       23.3.1
prometheus_client         0.20.0
protobuf                  4.25.3
psutil                    5.9.8
pydantic                  2.6.4
pydantic_core             2.16.3
pynvml                    11.5.0
PySocks                   1.7.1
python-dotenv             1.0.1
PyYAML                    6.0.1
ray                       2.9.3
referencing               0.33.0
regex                     2023.12.25
requests                  2.31.0
rpds-py                   0.18.0
safetensors               0.4.2
scipy                     1.12.0
sentencepiece             0.2.0
setuptools                68.2.2
sniffio                   1.3.1
starlette                 0.36.3
sympy                     1.12
tokenizers                0.15.2
torch                     2.1.2
torchvision               0.17.1
tqdm                      4.66.2
transformers              4.38.2
triton                    2.1.0
typing_extensions         4.9.0
urllib3                   2.1.0
uvicorn                   0.28.0
uvloop                    0.19.0
vllm                      0.3.3        /cmlscratch/smcleish/lm_doc
watchfiles                0.21.0
websockets                12.0
wheel                     0.41.2
xformers                  0.0.23.post1
```
NVIDIA-SMI:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A4000               Off | 00000000:41:00.0 Off |                  Off |
| 41%   26C    P8              14W / 140W |      1MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000               Off | 00000000:C1:00.0 Off |                  Off |
| 41%   25C    P8              13W / 140W |      1MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
```
I also attempted to roll back to the docker 3.0.0 release:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/cmlscratch/smcleish/lm_doc/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/async_llm_engine.py", line 13, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/llm_engine.py", line 13, in <module>
    from vllm.engine.metrics import StatLogger, Stats
  File "/cmlscratch/smcleish/lm_doc/vllm/engine/metrics.py", line 2, in <module>
    from prometheus_client import (Counter, Gauge, Histogram, Info, REGISTRY,
ModuleNotFoundError: No module named 'prometheus_client'
```

**Comment by DN-Dev00** [comment]
hmm. can you try to reinstall cuDNN?  
https://developer.nvidia.com/cudnn
