### ISSUE TITLE
install vllm,but show CUDA runtime is found,please help me,thank you!

### ISSUE THREAD

**Issue by dongkuang** [vllm-project/vllm#341]
### Discussed in https://github.com/vllm-project/vllm/discussions/329

<div type='discussions-op-text'>

<sup>Originally posted by **dongkuang** July  2, 2023</sup>
running build_py
running build_ext
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.8'
Traceback (most recent call last):
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 155, in run
self._create_wheel_file(bdist_wheel)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 344, in _create_wheel_file
files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 267, in _run_build_commands
self._run_build_subcommands()
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 294, in _run_build_subcommands
self.run_command(name)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
self.distribution.run_command(command)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
super().run_command(command)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
_build_ext.run(self)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
self.build_extensions()
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
_check_cuda_version(compiler_name, compiler_version)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 383, in _check_cuda_version
torch_cuda_version = packaging.version.parse(torch.version.cuda)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 52, in parse
return Version(version)
File "/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 196, in init
match = self._regex.search(version)
TypeError: expected string or bytes-like object
/tmp/pip-build-env-1bv509_l/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
!!

and I run nvcc -version,can find cuda is cuda11.8,and I have installed ninja&packaging&setuptools&torch2.0.0&wheel
I run it on jetson orin 64G,it's aarch64</div>

**Comment by WoosukKwon** [comment]
It seems there's an error in parsing the output of `nvcc -V`. Could you run `nvcc -V` and tell us the output?

**Comment by dongkuang** [comment]
Thank you!It's the result:
(myvllm) dongkuang@ubuntu:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:43:33_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by WoosukKwon** [comment]
@dongkuang Your output doesn't seem wrong. It might be a bug regarding the aarch64 architecture, which we haven't tested vLLM on. For now, I'm afraid we don't have any aarch64 machine with an NVIDIA GPU, so cannot help debugging.

**Comment by dongkuang** [comment]
@WoosukKwon Thank you for your help!We want vllm to run with aarch64,it's a wonderful combination!Then if you want to do it too,we are more than willing to cooperate,I'm looking forward to your feedback!

**Comment by qZhang88** [comment]
@dongkuang same as you, build on jetson agx orin 64G. 

`pip install -e .` has same problem as yours. The pip install process is strange. The error is here `torch_cuda_version = packaging.version.parse(torch.version.cuda)`, where `torch.version.cuda` return nothing. But actually itried in ipython `torch.version.cuda` returns 11.4
> note: using jetpack torch, not compiled by myself, but cuda upgrade to  11.8 version, as needed by vllm, which says `"CUDA 11.8 or higher is required for GPUs with compute capability 9.0."`).

The I tried to install with `python setup.py develop`.  And after a lot logs, the compile is ok.

**Comment by skymizerFuji** [comment]
@qZhang88  Thank you for sharing. I was trying to install VLLM on Jetson Orin 16G and encountered the same error as you did. Could you please let me know which version of Torch you built by sharing your 'pip list'?

**Comment by skymizerFuji** [comment]
@qZhang88 Thank you for your detailed response! I will give it a try.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
