### ISSUE TITLE
error when run the vllm to generate

### ISSUE THREAD

**Issue by wjy3326** [vllm-project/vllm#349]
The code is here:
# encoding: utf-8
from vllm import LLM, SamplingParams
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
print("sampling_params", sampling_params)
llm = LLM(model="/media/odin/software/PycharmProjects/OpenBuddy-main/model/openbuddy-openllama-7b-v5-fp16/")
outputs = llm.generate(prompts, sampling_params)
print("outputs", outputs)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

the error is here:
Traceback (most recent call last):
  File "/media/odin/software/PycharmProjects/vllm-main/vllm_test.py", line 2, in <module>
    from vllm import LLM, SamplingParams
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/__init__.py", line 2, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/engine/async_llm_engine.py", line 6, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/engine/llm_engine.py", line 16, in <module>
    from vllm.worker.worker import Worker
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/worker/worker.py", line 8, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/model_executor/model_loader.py", line 9, in <module>
    from vllm.model_executor.models import (GPT2LMHeadModel, GPTBigCodeForCausalLM, GPTNeoXForCausalLM,
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.gpt2 import GPT2LMHeadModel
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/model_executor/models/gpt2.py", line 30, in <module>
    from vllm.model_executor.layers.activation import get_act_fn
  File "/media/odin/software/PycharmProjects/vllm-main/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: cannot import name 'activation_ops' from partially initialized module 'vllm' (most likely due to a circular import) (/media/odin/software/PycharmProjects/vllm-main/vllm/__init__.py)

How to fix this error？Thanks!

**Comment by WoosukKwon** [comment]
Hi @wjy3326, could you check if vLLM is installed in your environment? The `activation_ops` module is created during pip installation. It seems you are using vLLM without installation.

**Comment by wjy3326** [comment]
I put the running code in the vllm folder, which caused the above error. Now I run the running code separately and not in the vllm folder, so there is no above error. Now when I run openbuddy's llama model there is a new error:
sampling_params SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.8, top_p=0.95, top_k=-1, use_beam_search=False, stop=[], ignore_eos=False, max_tokens=16, logprobs=None)
INFO 07-04 15:04:15 llm_engine.py:59] Initializing an LLM engine with config: model='/media/odin/software/PycharmProjects/OpenBuddy-main/model/openbuddy-openllama-7b-v5-fp16/', dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 07-04 15:04:15 tokenizer_utils.py:30] Using the LLaMA fast tokenizer in 'hf-internal-testing/llama-tokenizer' to avoid potential protobuf errors.
Traceback (most recent call last):
  File "/media/odin/software/PycharmProjects/Test/vllm_test.py", line 11, in <module>
    llm = LLM(model="/media/odin/software/PycharmProjects/OpenBuddy-main/model/openbuddy-openllama-7b-v5-fp16/")
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 55, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 151, in from_engine_args
    engine = cls(*engine_configs, distributed_init_method, devices,
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 93, in __init__
    worker = worker_cls(
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/worker/worker.py", line 45, in __init__
    self.model = get_model(model_config)
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 47, in get_model
    model.load_weights(
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 248, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/home/odin/miniconda3/lib/python3.10/site-packages/vllm/model_executor/weight_utils.py", line 73, in hf_model_weights_iterator
    state = torch.load(bin_file, map_location="cpu")
  File "/home/odin/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/odin/miniconda3/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
How to fix this, thanks!

**Comment by E1zo** [comment]
> Hey @wjy3326 I'm getting this error too - did you find a solution since you marked the issue closed?

just simply run the running code separately and not in the vllm folder,

**Comment by grantbey** [comment]
> > Hey @wjy3326 I'm getting this error too - did you find a solution since you marked the issue closed?
> 
> just simply run the running code separately and not in the vllm folder,

Sorry - I see that I didn't reply specifically to @wjy3326's more recent post. I'm not getting OPs original error, I'm getting the `_pickle.UnpicklingError: could not find MARK` error when loading my fine-tuned models.

It loads the original model correctly, however my fine-tuned models don't load. I've checked and they load fine using HuggingFace's `AutoModelForCausalLM.from_pretrained` method, so I don't think it's a problem with corrupt files.
