### ISSUE TITLE
[Bug]: aisingapore/sea-lion-7b-instruct fails with assert config.embedding_fraction == 1.0

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#3523]
### Your current environment

python 3.10 vllm 0.3.3

### 🐛 Describe the bug

https://huggingface.co/aisingapore/sea-lion-7b-instruct/blob/main/config.json

```
WARNING 03-20 04:11:30 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 237, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 625, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 366, in _init_engine
    return engine_class(*args, **kwargs)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 120, in __init__
    self._init_workers()
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 164, in _init_workers
    self._run_workers("load_model")
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1014, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/worker/worker.py", line 100, in load_model
    self.model_runner.load_model()
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 84, in load_model
    self.model = get_model(self.model_config, self.device_config,
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 79, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/models/mpt.py", line 260, in __init__
    self.transformer = MPTModel(config, linear_method)
  File "/h2ogpt_conda/vllm_env/lib/python3.10/site-packages/vllm/model_executor/models/mpt.py", line 211, in __init__
    assert config.embedding_fraction == 1.0

```

**Comment by hmellor** [comment]
Some documentation for additional context https://huggingface.co/docs/transformers/main/en/model_doc/mpt#transformers.MptConfig.embedding_fraction.

I wonder why a gradient scaling parameter has an assertion. @WoosukKwon, as the author of MPT support could you shed some light on this?

**Comment by jasshanK** [comment]
@pseudotensor did you install vllm via this method? https://github.com/aisingapore/sealion/tree/vllm/vllm

**Comment by pseudotensor** [comment]
I didn't, wasn't aware of it.

**Comment by jasshanK** [comment]
It should work with this, there are some discrepancies between the MPT and SEA-LION architectures.

**Comment by pseudotensor** [comment]
That repo is too old to be useful, too many missing features.

**Comment by hmellor** [comment]
@pseudotensor can we close this as stale/solved?

Or are you still experiencing/caring about the issue?
