### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'kv_cache_dtype'

### ISSUE THREAD

**Issue by xiaohaiqing** [vllm-project/vllm#3529]
### Your current environment

accelerate 0.27.2
torch 2.1.2
transformers 4.38.2
pydantic 2.6.1
pydantic_core 2.16.2
pydantic-settings 2.0.3
vllm 0.3.2
xformers 0.0.23.post1

### How you are installing vllm

报错如下：

```shell
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Process openai_api:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/langchain-chatchat/startup.py", line 415, in run_openai_api
    app = create_openai_api_app(controller_addr, log_level=log_level) # TODO: not support keys yet.
  File "/langchain-chatchat/startup.py", line 248, in create_openai_api_app
    from fastchat.serve.openai_api_server import app, CORSMiddleware, app_settings
  File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/openai_api_server.py", line 25, in
    from pydantic import BaseSettings
  File "/usr/local/lib/python3.10/dist-packages/pydantic/__init__.py", line 374, in __getattr__
    return _getattr_migration(attr_name)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.6/migration/#basesettings-has-moved-to-pydantic-settings for more details.
 
For further information visit https://errors.pydantic.dev/2.6/u/import-error
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
2024-03-20 13:55:19 | ERROR | stderr | Process model_worker - Qwen-7B-Chat:
2024-03-20 13:55:19 | ERROR | stderr | Traceback (most recent call last):
2024-03-20 13:55:19 | ERROR | stderr | File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-03-20 13:55:19 | ERROR | stderr | self.run()
2024-03-20 13:55:19 | ERROR | stderr | File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-03-20 13:55:19 | ERROR | stderr | self._target(*self._args, **self._kwargs)
2024-03-20 13:55:19 | ERROR | stderr | File "/langchain-chatchat/startup.py", line 383, in run_model_worker
2024-03-20 13:55:19 | ERROR | stderr | app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-20 13:55:19 | ERROR | stderr | File "/langchain-chatchat/startup.py", line 149, in create_model_worker_app
2024-03-20 13:55:19 | ERROR | stderr | engine_args = AsyncEngineArgs.from_cli_args(args)
2024-03-20 13:55:19 | ERROR | stderr | File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 281, in from_cli_args
2024-03-20 13:55:19 | ERROR | stderr | engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-03-20 13:55:19 | ERROR | stderr | File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 281, in
2024-03-20 13:55:19 | ERROR | stderr | engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-03-20 13:55:19 | ERROR | stderr | AttributeError: 'Namespace' object has no attribute 'kv_cache_dtype'
```

**Comment by simon-mo** [comment]
Can you double check the vLLM version? The arg is clearly there here:
https://github.com/vllm-project/vllm/blob/5ee14494e4c78769fa10af8b58c3e7808053da0d/vllm/engine/arg_utils.py#L21

**Comment by youkaichao** [comment]
I don't think it is a bug of vllm. It should be a bug or incorrect installation of `fastchat`. You can see an error coming out from this line:

> File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/openai_api_server.py", line 25, in <module> from pydantic import BaseSettings

You can simply try `python -c "from pydantic import BaseSettings"`, and see if it causes error.

**Comment by xiaohaiqing** [comment]
输入 `python3 -c "from pydantic import BaseSettings"`后出现如下错误：
```sh
# python3 -c "from pydantic import BaseSetting"                                                                       
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'BaseSetting' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.py)
```

**Comment by xiaohaiqing** [comment]
我把版本降为如下后：
```powershell
pydantic 1.10.13
vllm 0.2.6
```
报错信息如下：
```sh
2024-03-21T00:51:57.465832486Z 2024-03-21 00:51:57 | ERROR | stderr | Process model_worker - Qwen-7B-Chat:
2024-03-21T00:51:57.466044670Z 2024-03-21 00:51:57 | ERROR | stderr | Traceback (most recent call last):
2024-03-21T00:51:57.466114084Z 2024-03-21 00:51:57 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2024-03-21T00:51:57.466212280Z 2024-03-21 00:51:57 | ERROR | stderr |     self.run()
2024-03-21T00:51:57.466256690Z 2024-03-21 00:51:57 | ERROR | stderr |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
2024-03-21T00:51:57.466271195Z 2024-03-21 00:51:57 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-21T00:51:57.466317554Z 2024-03-21 00:51:57 | ERROR | stderr |   File "/langchain-chatchat/startup.py", line 383, in run_model_worker
2024-03-21T00:51:57.466351012Z 2024-03-21 00:51:57 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-21T00:51:57.466405670Z 2024-03-21 00:51:57 | ERROR | stderr |   File "/langchain-chatchat/startup.py", line 149, in create_model_worker_app
2024-03-21T00:51:57.466457383Z 2024-03-21 00:51:57 | ERROR | stderr |     engine_args = AsyncEngineArgs.from_cli_args(args)
2024-03-21T00:51:57.466496360Z 2024-03-21 00:51:57 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 210, in from_cli_args
2024-03-21T00:51:57.466536863Z 2024-03-21 00:51:57 | ERROR | stderr |     engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-03-21T00:51:57.466578216Z 2024-03-21 00:51:57 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 210, in <dictcomp>
2024-03-21T00:51:57.466627568Z 2024-03-21 00:51:57 | ERROR | stderr |     engine_args = cls(**{attr: getattr(args, attr) for attr in attrs})
2024-03-21T00:51:57.466653988Z 2024-03-21 00:51:57 | ERROR | stderr | AttributeError: 'Namespace' object has no attribute 'max_paddings'
```

**Comment by youkaichao** [comment]
It seems your installation is not successful. Please try it in a fresh new environment.
