### ISSUE TITLE
[Installation]: CuPy and Multiprocess raise the AssertionError: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by ShAw7ock** [vllm-project/vllm#3724]
### Your current environment

```text
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090

Nvidia driver version: 535.154.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz
Stepping:                        7
CPU MHz:                         3128.251
CPU max MHz:                     4000.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.1.2+cu121
[pip3] triton==2.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.2+cu121              pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.3.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     0-23,48-71      0               N/A
GPU1    SYS      X      24-47,72-95     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### How you are installing vllm

Hello, appreciate for the wonderful job.

I've already deploy the vLLM 0.3.0 version with docker (based on the Ray 2.9.3 image and I installed the dependent packages manually) and test my own applications sucessfully.

Now I wanna follow the newest version `0.3.3` of vLLM and get the features which could apply for GPTQ-8bits quantized models. 

But when I installed the vllm0.3.3 and required packages, I always got the ERROR from `CuPy` and `multiprocessing` with `AssertionError: daemonic processes are not allowed to have children`.

Anybody meet the same or similar errors? If there is anything that I made it wrong?

The detailed error message is as follows:

```bash
2024-03-28 23:34:13 | ERROR | stderr | Traceback (most recent call last):
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-03-28 23:34:13 | ERROR | stderr |     self.run()
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-03-28 23:34:13 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/llm-controller/server/app/runner.py", line 203, in run_model_worker
2024-03-28 23:34:13 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/llm-controller/server/app/creator.py", line 132, in create_model_worker_app
2024-03-28 23:34:13 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 628, in from_engine_args
2024-03-28 23:34:13 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 321, in __init__
2024-03-28 23:34:13 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 369, in _init_engine
2024-03-28 23:34:13 | ERROR | stderr |     return engine_class(*args, **kwargs)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 126, in __init__
2024-03-28 23:34:13 | ERROR | stderr |     self._init_workers_ray(placement_group)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 304, in _init_workers_ray
2024-03-28 23:34:13 | ERROR | stderr |     self._run_workers("init_model",
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 1041, in _run_workers
2024-03-28 23:34:13 | ERROR | stderr |     driver_worker_output = getattr(self.driver_worker,
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/worker/worker.py", line 94, in init_model
2024-03-28 23:34:13 | ERROR | stderr |     init_distributed_environment(self.parallel_config, self.rank,
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/worker/worker.py", line 275, in init_distributed_environment
2024-03-28 23:34:13 | ERROR | stderr |     cupy_utils.init_process_group(
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/vllm/model_executor/parallel_utils/cupy_utils.py", line 90, in init_process_group
2024-03-28 23:34:13 | ERROR | stderr |     _NCCL_BACKEND = NCCLBackendWithBFloat16(world_size, rank, host, port)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/cupyx/distributed/_nccl_comm.py", line 70, in __init__
2024-03-28 23:34:13 | ERROR | stderr |     self._init_with_tcp_store(n_devices, rank, host, port)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/cupyx/distributed/_nccl_comm.py", line 88, in _init_with_tcp_store
2024-03-28 23:34:13 | ERROR | stderr |     self._store.run(host, port)
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/site-packages/cupyx/distributed/_store.py", line 100, in run
2024-03-28 23:34:13 | ERROR | stderr |     p.start()
2024-03-28 23:34:13 | ERROR | stderr |   File "/home/ray/anaconda3/lib/python3.9/multiprocessing/process.py", line 118, in start
2024-03-28 23:34:13 | ERROR | stderr |     assert not _current_process._config.get('daemon'), \
2024-03-28 23:34:13 | ERROR | stderr | AssertionError: daemonic processes are not allowed to have children
```

**Comment by youkaichao** [comment]
Hi, `cupy` dependency is removed in https://github.com/vllm-project/vllm/pull/3625 recently. You can try to build from source in the latest main branch.

**Comment by ShAw7ock** [comment]
> Hi, `cupy` dependency is removed in #3625 recently. You can try to build from source in the latest main branch.

Thanks for your reply.

I tried it by building from source (branch `main`) and it worked well w/o `cupy` dependency.

Thanks again. Looking forward to the formal released version.
