### ISSUE TITLE
[Bug]: V100  lora运行  punica.py  RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by snakecy** [vllm-project/vllm#3826]
### Your current environment

```text
The output of `python collect_env.py`
```

```text
Collecting environment information...
PyTorch version: 2.1.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: version 3.27.1
Libc version: glibc-2.17

Python version: 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 535.54.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping:              4
CPU MHz:               2500.000
BogoMIPS:              5000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              33792K
NUMA node0 CPU(s):     0-47
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.1.0+cu121
[pip3] torchaudio==2.1.0+cu121
[pip3] torchvision==0.16.0+cu121
[pip3] triton==2.1.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.1.0+cu121              pypi_0    pypi
[conda] torchaudio                2.1.0+cu121              pypi_0    pypi
[conda] torchvision               0.16.0+cu121             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity
GPU0     X      NV2     NV1     NV2     0-47            N/A
GPU1    NV2      X      NV2     NV1     0-47            N/A
GPU2    NV1     NV2      X      NV1     0-47            N/A
GPU3    NV2     NV1     NV1      X      0-47            N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### 🐛 Describe the bug

```bash
CUDA_VISIBLE_DEVICES=1 \
python -m vllm.entrypoints.openai.api_server \
            --model /export/models/qwen/Qwen1.5-14B-Chat \
            --max-loras 16 --tensor-parallel-size 1 --dtype float16 --max-lora-rank 64 --gpu-memory-utilization 0.9 \
            --enable-lora --enforce-eager --disable-log-requests --lora-modules lora1=XXXXX
```

```text
INFO 04-03 18:43:13 api_server.py:149] vLLM API server version 0.4.0.post1
INFO 04-03 18:43:13 api_server.py:150] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=[LoRA(name='lora1', local_path='XXXX')], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/export/models/qwen/Qwen1.5-14B-Chat', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='float16', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.5, forced_num_gpu_blocks=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=True, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=True, max_loras=1, max_lora_rank=64, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_chunked_prefill=False, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
WARNING 04-03 18:43:13 config.py:767] Casting torch.bfloat16 to torch.float16.
INFO 04-03 18:43:13 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='/export/models/qwen/Qwen1.5-14B-Chat', tokenizer='/export/models/qwen/Qwen1.5-14B-Chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=512, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 04-03 18:43:13 pynccl.py:39] Loading nccl from environment variable VLLM_NCCL_SO_PATH=/XXX/.cupy/cuda_lib/12.x/nccl/2.16.2/lib/libnccl.so.2
INFO 04-03 18:43:14 selector.py:40] Cannot use FlashAttention backend for Volta and Turing GPUs.
INFO 04-03 18:43:14 selector.py:25] Using XFormers backend.
INFO 04-03 18:43:28 model_runner.py:104] Loading model weights took 26.4277 GB

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 157, in <module>
    engine = AsyncLLMEngine.from_engine_args(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 348, in from_engine_args
    engine = cls(
             ^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 422, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 40, in __init__
    self._init_cache()
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 80, in _init_cache
    self.driver_worker.profile_num_available_blocks(
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/worker/worker.py", line 131, in profile_num_available_blocks
    self.model_runner.profile_run()
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 742, in profile_run
    self.execute_model(seqs, kv_caches)
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 663, in execute_model
    hidden_states = model_executable(**execute_model_kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 317, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 254, in forward
    hidden_states, residual = layer(
                              ^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 207, in forward
    hidden_states = self.self_attn(
                    ^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 150, in forward
    qkv, _ = self.qkv_proj(hidden_states)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/lora/layers.py", line 395, in forward
    output_parallel = self.apply_weights(input_, bias)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/lora/layers.py", line 750, in apply_weights
    _apply_lora_packed_nslice(
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/lora/layers.py", line 97, in _apply_lora_packed_nslice
    add_lora_slice(output, x, lora_a_stacked[slice_idx],
  File "/export/miniconda3/envs/vllm118/lib/python3.11/site-packages/vllm/lora/punica.py", line 146, in add_lora_slice
    buffer = torch.zeros((x.size(0), r),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by popay97** [comment]
Experiencing same issues on V100 and T4, even without lora request.

**Comment by youkaichao** [comment]
@snakecy `punica.py` with lora requires sm 8.0, and does not support V100.

@popay97 if you are having issues with running vllm on V100 and T4, please try `v0.4.0.post1` . We fixed a bug to include cuda binary for V100 .

**Comment by snakecy** [comment]
> @snakecy `punica.py` with lora requires sm 8.0, and does not support V100.
> 
> @popay97 if you are having issues with running vllm on V100 and T4, please try `v0.4.0.post1` . We fixed a bug to include cuda binary for V100 .

Is there a plan to support v100 7.0?

**Comment by Cloopen-ReLiNK** [comment]
> @snakecy `punica.py` with lora requires sm 8.0, and does not support V100.
> 
> @popay97 if you are having issues with running vllm on V100 and T4, please try `v0.4.0.post1` . We fixed a bug to include cuda binary for V100 .

Not solved, the same problem is in vllm/vllm-openai:v0.4.0.post1

**Comment by Jiakaic** [comment]
I met the same problem

**Comment by MiJordan23** [comment]
I met the same problem

**Comment by chenzhongwu** [comment]
> > 使用 lora 需要 sm 8.0， 并且不支持 V100.`punica.py`
> > 如果您在 V100 和 T4 上运行 vllm 时遇到问题，请尝试 。我们修复了一个错误，包括 V100 的 cuda 二进制文件。`v0.4.0.post1`
> 
> 没有解决，同样的问题在 vllm/vllm-openai：v0.4.0.post1 V100 中 ![image](https://private-user-images.githubusercontent.com/107677991/320251053-21b76b00-e5f3-4534-9403-797bbfc2625b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODI1MzUsIm5iZiI6MTcxNTU4MjIzNSwicGF0aCI6Ii8xMDc2Nzc5OTEvMzIwMjUxMDUzLTIxYjc2YjAwLWU1ZjMtNDUzNC05NDAzLTc5N2JiZmMyNjI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjY1ZDI1MzFjOTMyNTI4ODEwYjA3MTlhNWM5NGYwOWRhMjk0ZWI0NDE2OGJhMGVmNzE4ZTBmODk0ZjY4MGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-QlwSL-su_2pqj_CzcdJxDJRzL6YgixL5bPzv9SDVbE) ![image](https://private-user-images.githubusercontent.com/107677991/320251064-330ced78-36d6-4831-ab1a-9722642a7acf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODI1MzUsIm5iZiI6MTcxNTU4MjIzNSwicGF0aCI6Ii8xMDc2Nzc5OTEvMzIwMjUxMDY0LTMzMGNlZDc4LTM2ZDYtNDgzMS1hYjFhLTk3MjI2NDJhN2FjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNjM3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjBjYWNhY2MwMTM0NDBmMTgxYzI0ZGY0YjI2NjM5NTVkODAwN2IzYWRiZGVkZjc2NWQ0MTcwY2E4YjExZTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FnXZdpyoyLvdw_ALPp9YG4vGhL_btsNZz2juKK6jym4)

the same question. thanks for any solutions.
