### ISSUE TITLE
[Bug]:Failed that we generate the pompts with the google/gemma-2b model by the python code, 

### ISSUE THREAD

**Issue by 936187425** [vllm-project/vllm#3898]
### Your current environment

```text
python 3.10.14
vllm 0.4.0.post1  
vllm-nccl-cu12            2.18.1.0.1.0 
```
### the python code 
``` python
from vllm.entrypoints.llm import LLM
from vllm.sampling_params import SamplingParams

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
llm = LLM(model="google/gemma-2b")
outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

### 🐛 Describe the bug

the error:
Traceback (most recent call last):
  File "/home/hyp/testGemma.py", line 11, in <module>
    llm = LLM(model="google/gemma-2b")
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 225, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 182, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 79, in __init__
    self.hf_config = get_config(model, trust_remote_code, revision)
  File "/usr/local/lib/python3.10/dist-packages/vllm/transformers_utils/config.py", line 21, in get_config
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1064, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 761, in __getitem__
    raise KeyError(key)
KeyError: 'gemma'

**Comment by mgoin** [comment]
@936187425 it looks like your transformers package doesn't recognize the model, please upgrade your version of transformers
