### ISSUE TITLE
[Bug]: Can´t load CommandR+

### ISSUE THREAD

**Issue by gpucce** [vllm-project/vllm#3920]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

When loading Command R + I get the following error, however I can load and run the model using Huggingface with `device_map="auto"`, also I can use vLLM with other large models, e.g. LLama 70b and Mixtral and it works fine. I am running on a Node with 4x64Gb A100, the GPU might seem strange, these are from the Leonardo Super computer.

Is this a known bug or can I somehow fix it? I am runnign with `tensor-parallel-size=4` in lm-eval-harness.

```
vLLM is using nccl==2.18.1
(RayWorkerVllm pid=282131) INFO 04-08 16:24:58 pynccl_utils.py:45] vLLM is using nccl==2.18.1
Traceback (most recent call last):
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/bin/lm_eval", line 8, in <module>
    sys.exit(cli_evaluate())
             ^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/lm-evaluation-harness/lm_eval/__main__.py", line 341, in cli_evaluate
    results = evaluator.simple_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/lm-evaluation-harness/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/lm-evaluation-harness/lm_eval/evaluator.py", line 180, in simple_evaluate
    lm = lm_eval.api.registry.get_model(model).create_from_arg_string(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/lm-evaluation-harness/lm_eval/api/model.py", line 134, in create_from_arg_string
    return cls(**args, **args2)
           ^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/lm-evaluation-harness/lm_eval/models/vllm_causallms.py", line 98, in __init__
    self.model = LLM(**self.model_args)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 112, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 196, in from_engine_args
    engine = cls(
             ^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 62, in __init__
    self._init_workers_ray(placement_group)
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 192, in _init_workers_ray
    self._run_workers(
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 324, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
                 ^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/llm_newest/conda_venv/lib/python3.11/site-packages/vllm/model_executor/models/commandr.py", line 325, in load_weights
    param = params_dict[name]
            ~~~~~~~~~~~^^^^^^
KeyError: 'model.layers.47.self_attn.k_norm.weight'
(RayWorkerVllm pid=282294) INFO 04-08 16:24:57 selector.py:16] Using FlashAttention backend. [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorkerVllm pid=282294) INFO 04-08 16:24:58 pynccl_utils.py:45] vLLM is using nccl==2.18.1 [repeated 2x across cluster]
```

**Comment by esmeetu** [comment]
CommandR plus model support hasn't included in 0.4.0 yet. Please build vllm on main branch by yourself and use your built vllm in `lm-eval-harness`.
