### ISSUE TITLE
[Bug]: start api server stuck

### ISSUE THREAD

**Issue by QianguoS** [vllm-project/vllm#4027]
### Your current environment

```text
The output of `python collect_env.py`
```
vLLM API server version 0.4.0.post1

### 🐛 Describe the bug

When I started the api service, the startup process got stuck.
2024-04-12 13:45:17,174 INFO worker.py:1752 -- Started a local Ray instance.

python -m vllm.entrypoints.openai.api_server \
       --model ${MODEL_PATH} \
       --tensor-parallel-size ${tensor_parallel_size} \
       --port ${port}

**Comment by arunpatala** [comment]
I am facing a similar issue. I am using the docker image. It was working fine yday. Now its stuck at 

INFO 04-12 10:48:17 selector.py:16] Using FlashAttention backend.

and then it doesnt proceed even after an hour.

**Comment by Extremys** [comment]
Same issue there :(

**Comment by Extremys** [comment]
> Usually it is because of a distributed initialization problem.
> 
> @Extremys Can you try to build from source with main branch, and add some logging inside this function:
> 
> https://github.com/vllm-project/vllm/blob/7fd3949a0b1c6cd0dcd7066aca48d9d589f2f68e/vllm/distributed/parallel_state.py#L41
> 
> e.g. add one line `print(f"{world_size=}, {rank=}, {distributed_init_method=}, {local_rank=}, {backend=}")`

I've tried the latest commit https://github.com/vllm-project/vllm/commit/5c2e66e4871917c5d59cc4a8b89ef53e690e9bd9 but I get another error, gonna with a older to see if I have more chance.

```bash
2024-04-13 07:06:55,340 INFO worker.py:1752 -- Started a local Ray instance.
INFO 04-13 07:06:56 llm_engine.py:81] Initializing an LLM engine (v0.4.0.post1) with config: model='/data/Mixtral-8x7B-Instruct-v0.1', speculative_config=None, tokenizer='/data/Mixtral-8x7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, seed=0)
INFO 04-13 07:07:03 pynccl.py:58] Loading nccl from library libnccl.so.2
2024-04-13 07:07:03 | ERROR | stderr | Traceback (most recent call last):
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-04-13 07:07:03 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-04-13 07:07:03 | ERROR | stderr |     exec(code, run_globals)
2024-04-13 07:07:03 | ERROR | stderr |   File "/code/FastChat/fastchat/serve/vllm_worker.py", line 290, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 347, in from_engine_args
2024-04-13 07:07:03 | ERROR | stderr |     engine = cls(
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
2024-04-13 07:07:03 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 421, in _init_engine
2024-04-13 07:07:03 | ERROR | stderr |     return engine_class(*args, **kwargs)
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 119, in __init__
2024-04-13 07:07:03 | ERROR | stderr |     self.model_executor = executor_class(
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 65, in __init__
2024-04-13 07:07:03 | ERROR | stderr |     self._init_workers_ray(placement_group)
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 146, in _init_workers_ray
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.worker.worker import Worker
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 21, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.worker.model_runner import ModelRunner
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 22, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.model_executor.model_loader import get_model
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 10, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.model_executor.models.llava import LlavaForConditionalGeneration
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llava.py", line 16, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.model_executor.models.llama import LlamaModel
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llama.py", line 46, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.model_executor.weight_utils import (default_weight_loader,
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 22, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from vllm.model_executor.layers.quantization.schema import QuantParamSchema
2024-04-13 07:07:03 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/quantization/schema.py", line 16, in <module>
2024-04-13 07:07:03 | ERROR | stderr |     from pydantic import BaseModel, ConfigDict, ValidationInfo, model_validator
2024-04-13 07:07:03 | ERROR | stderr | ImportError: cannot import name 'ValidationInfo' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)
```

**Comment by Extremys** [comment]
> Usually it is because of a distributed initialization problem.
> 
> @Extremys Can you try to build from source with main branch, and add some logging inside this function:
> 
> https://github.com/vllm-project/vllm/blob/7fd3949a0b1c6cd0dcd7066aca48d9d589f2f68e/vllm/distributed/parallel_state.py#L41
> 
> e.g. add one line `print(f"{world_size=}, {rank=}, {distributed_init_method=}, {local_rank=}, {backend=}")`

The command used to run it (using FastChat) :

```bash
CUDA_VISIBLE_DEVICES=3,4,5,6 python3 -m fastchat.serve.vllm_worker --model-name "Mixtral-8x7B-Instruct-v0.1" --model-path $MODEL_PATH --num-gpus 4 
```
Ok so using fbb9d9eef48a29e0ea821bbf399e4bf9a08d6ac1 I get this:

```bash
INFO 04-13 10:17:22 pynccl.py:58] Loading nccl from library libnccl.so.2
2024-04-13 10:17:27,901 INFO worker.py:1752 -- Started a local Ray instance.
INFO 04-13 10:17:29 llm_engine.py:81] Initializing an LLM engine (v0.4.0.post1) with config: model='/data/Mixtral-8x7B-Instruct-v0.1', speculative_config=None, tokenizer='/data/Mixtral-8x7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, seed=0)
2024-04-13 10:17:32 | INFO | stdout | (pid=10414) INFO 04-13 10:17:31 pynccl.py:58] Loading nccl from library libnccl.so.2
2024-04-13 10:17:38 | INFO | stdout | (pid=10921) INFO 04-13 10:17:38 pynccl.py:58] Loading nccl from library libnccl.so.2 [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
INFO 04-13 10:17:40 selector.py:28] Using FlashAttention backend.
2024-04-13 10:17:41 | INFO | stdout | (RayWorkerVllm pid=10521) INFO 04-13 10:17:41 selector.py:28] Using FlashAttention backend.
2024-04-13 10:17:42 | INFO | stdout | world_size=4, rank=0, distributed_init_method='tcp://10.24.78.24:37191', local_rank=0, backend='nccl'
INFO 04-13 10:17:42 pynccl_utils.py:45] vLLM is using nccl==2.19.3
2024-04-13 10:17:42 | INFO | stdout | (RayWorkerVllm pid=10521) world_size=4, rank=1, distributed_init_method='tcp://10.24.241.24:37191', local_rank=1, backend='nccl'
2024-04-13 10:17:42 | INFO | stdout | (RayWorkerVllm pid=10521) INFO 04-13 10:17:42 pynccl_utils.py:45] vLLM is using nccl==2.19.3
```
and it's stuck after :)

**Comment by youkaichao** [comment]
> 2024-04-13 10:17:42 | INFO | stdout | world_size=4, rank=0, distributed_init_method='tcp://10.24.78.24:37191', local_rank=0, backend='nccl'
> 2024-04-13 10:17:42 | INFO | stdout | (RayWorkerVllm pid=10521) world_size=4, rank=1, distributed_init_method='tcp://10.24.78.24:37191', local_rank=1, backend='nccl'

The world size is 4, but only 2 processes reaches here, so there are some problems in the other 2 processes. That's why it hangs.

**Comment by Extremys** [comment]
> > 2024-04-13 10:17:42 | INFO | stdout | world_size=4, rank=0, distributed_init_method='tcp://10.24.78.24:37191', local_rank=0, backend='nccl'
> > 2024-04-13 10:17:42 | INFO | stdout | (RayWorkerVllm pid=10521) world_size=4, rank=1, distributed_init_method='tcp://10.24.78.24:37191', local_rank=1, backend='nccl'
> 
> The world size is 4, but only 2 processes reaches here, so there are some problems in the other 2 processes. That's why it hangs.

Ok thank you for your answer, any advise on how to debug this ? I'm currently trying to run it into a pod (container) all traffic should be localhost actually. With vllm v0.2.7 it's working perfectly btw (but the inference is garbage with Mixtral unfortunately so that's why I try to upgrade vllm).

**Comment by youkaichao** [comment]
Unfortunately this is very difficult to debug.

One way is to print the trace: insert `import traceback; traceback.print_tb()` inside `init_distributed_environment`, and you will see the call stack of process 0 and process 1. Hopefully the other two processes are stuck somewhere above several frames. And you can try to find out where they are. That should be the reason of hang.

If you can find it out, it will also give us hint on how to fix it.

**Comment by Extremys** [comment]
Thanks @youkaichao I'm gonna try to provide the info.
I reduced the number of GPUs from 4 -> 2 and let the pod try to start and surprise it did start actually after 5 hours, very curious!

See the logs :

```log
INFO 04-13 14:32:09 pynccl.py:58] Loading nccl from library libnccl.so.2
2024-04-13 14:32:12,921 INFO worker.py:1752 -- Started a local Ray instance.
INFO 04-13 14:32:14 llm_engine.py:81] Initializing an LLM engine (v0.4.0.post1) with config: model='/data/Mixtral-8x7B-Instruct-v0.1', speculative_config=None, tokenizer='/data/Mixtral-8x7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, seed=0)
2024-04-13 14:32:16 | INFO | stdout | (pid=10412) INFO 04-13 14:32:16 pynccl.py:58] Loading nccl from library libnccl.so.2
INFO 04-13 14:32:20 selector.py:28] Using FlashAttention backend.
2024-04-13 14:32:20 | INFO | stdout | (RayWorkerVllm pid=10518) INFO 04-13 14:32:20 selector.py:28] Using FlashAttention backend.
2024-04-13 14:32:20 | INFO | stdout | world_size=2, rank=0, distributed_init_method='tcp://0.0.0.0:54849', local_rank=0, backend='nccl'
INFO 04-13 14:32:20 pynccl_utils.py:45] vLLM is using nccl==2.19.3
2024-04-13 14:32:20 | INFO | stdout | (RayWorkerVllm pid=10518) world_size=2, rank=1, distributed_init_method='tcp://0.0.0.0:54849', local_rank=1, backend='nccl'
2024-04-13 14:32:20 | INFO | stdout | (RayWorkerVllm pid=10518) INFO 04-13 14:32:20 pynccl_utils.py:45] vLLM is using nccl==2.19.3
INFO 04-13 21:19:52 model_runner.py:164] Loading model weights took 43.5064 GB
2024-04-13 21:19:52 | INFO | stdout | (RayWorkerVllm pid=10518) INFO 04-13 21:19:52 model_runner.py:164] Loading model weights took 43.5064 GB
2024-04-13 21:19:52 | INFO | stdout | (pid=10518) INFO 04-13 14:32:18 pynccl.py:58] Loading nccl from library libnccl.so.2
INFO 04-13 21:19:53 fused_moe.py:272] Using configuration from /usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=8,N=7168,device_name=NVIDIA_H100_80GB_HBM3.json for MoE layer.
2024-04-13 21:19:53 | INFO | stdout | (RayWorkerVllm pid=10518) INFO 04-13 21:19:53 fused_moe.py:272] Using configuration from /usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=8,N=7168,device_name=NVIDIA_H100_80GB_HBM3.json for MoE layer.
INFO 04-13 21:19:56 ray_gpu_executor.py:229] # GPU blocks: 20379, # CPU blocks: 4096
2024-04-13 21:19:57 | INFO | model_worker | Loading the model ['Mixtral-8x7B-Instruct-v0.1'] on worker ca34cd2a, worker type: vLLM worker...
2024-04-13 21:19:57 | INFO | model_worker | Register to controller
2024-04-13 21:19:57 | ERROR | stderr | INFO:     Started server process [10]
2024-04-13 21:19:57 | ERROR | stderr | INFO:     Waiting for application startup.
2024-04-13 21:19:57 | ERROR | stderr | INFO:     Application startup complete.
2024-04-13 21:19:57 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:21002 (Press CTRL+C to quit)
2024-04-13 21:20:42 | INFO | model_worker | Send heart beat. Models: ['Mixtral-8x7B-Instruct-v0.1']. Semaphore: None. call_ct: 0. worker_id: ca34cd2a.
2024-04-13 21:21:27 | INFO | model_worker | Send heart beat. Models: ['Mixtral-8x7B-Instruct-v0.1']. Semaphore: None. call_ct: 0. worker_id: ca34cd2a.
2024-04-13 21:22:12 | INFO | model_worker | Send heart beat. Models: ['Mixtral-8x7B-Instruct-v0.1']. Semaphore: None. call_ct: 0. worker_id: ca34cd2a.
2024-04-13 21:22:57 | INFO | model_worker | Send heart beat. Models: ['Mixtral-8x7B-Instruct-v0.1']. Semaphore: None. call_ct: 0. worker_id: ca34cd2a.
2024-04-13 21:23:42 | INFO | model_worker | Send heart beat. Models: ['Mixtral-8x7B-Instruct-v0.1']. Semaphore: None. call_ct: 0. worker_id: ca34cd2a.
2
```

**Comment by youkaichao** [comment]
> it did start actually after 5 hours

so strange

Did you try to build from source with the latest main branch?

**Comment by Extremys** [comment]
> > it did start actually after 5 hours
> 
> so strange
> 
> Did you try to build from source with the latest main branch?

So the 5 hours waiting it was with the commit https://github.com/vllm-project/vllm/commit/fbb9d9eef48a29e0ea821bbf399e4bf9a08d6ac1 as yesterday. I'm gonna try with the last commit let you know the result.

**Comment by Extremys** [comment]
> > it did start actually after 5 hours
> 
> so strange
> 
> Did you try to build from source with the latest main branch?

Ok I found out the issue actually it comes from the low read performance level of the mount point a s3 bucket. Going onto an ebs (ssd) volume solved the issue. :)
Unfortunately Mixtral is still going crazy after ~2000 tokens but at least this first issue is fixed.

**Comment by youkaichao** [comment]
As the stuck issue is solved, this issue is closed.

**Comment by QianguoS** [comment]
There is no problem when starting one instance. Only when two instances are started at the same time will encounter this problem occasionally. This problem can be solved by packaging the image

**Comment by chrisschwa** [comment]
> There is no problem when starting one instance. Only when two instances are started at the same time will encounter this problem occasionally. This problem can be solved by packaging the image

What do you mean by "packaging the image"? We have the exact same issue but can't solve it until now.
