### ISSUE TITLE
[Bug]: Incorrect typing for Python 3.8

### ISSUE THREAD

**Issue by dylanwhawk** [vllm-project/vllm#4035]
### Your current environment

`python collect_env.py` does not run, but I'm using Python 3.8.10

### 🐛 Describe the bug

Whenever vllm is imported I am getting a TypeError:
```
$python collect_env.py
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 719, in <module>
    main()
  File "collect_env.py", line 698, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 693, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 530, in get_env_info
    vllm_version = get_vllm_version()
  File "collect_env.py", line 261, in get_vllm_version
    import vllm
  File "/home/ray/default_cld_cv8egzp1tm3uvi738tt5bycjmm/vllm/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/home/ray/default_cld_cv8egzp1tm3uvi738tt5bycjmm/vllm/vllm/engine/async_llm_engine.py", line 12, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/home/ray/default_cld_cv8egzp1tm3uvi738tt5bycjmm/vllm/vllm/engine/llm_engine.py", line 14, in <module>
    from vllm.executor.executor_base import ExecutorBase
  File "/home/ray/default_cld_cv8egzp1tm3uvi738tt5bycjmm/vllm/vllm/executor/executor_base.py", line 11, in <module>
    class ExecutorBase(ABC):
  File "/home/ray/default_cld_cv8egzp1tm3uvi738tt5bycjmm/vllm/vllm/executor/executor_base.py", line 34, in ExecutorBase
    def determine_num_available_blocks(self) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable
```

**Comment by dylanwhawk** [comment]
Seems to stem from #3837 using Python 3.9+ typing
