### ISSUE TITLE
[Bug]: Cannot Load any model. IndexError with CUDA, multiple GPUs

### ISSUE THREAD

**Issue by sudarshan-kamath** [vllm-project/vllm#4069]
### Anything you want to discuss about vllm.

Cannot load the Command-r-plus model. I installed vllm directly from the Git by building it. 

```
2024-04-14 17:03:26 | ERROR | stderr | Traceback (most recent call last):
2024-04-14 17:03:26 | ERROR | stderr |   File "/project/vllm_worker.py", line 303, in <module>
2024-04-14 17:03:26 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 347, in from_engine_args
2024-04-14 17:03:26 | ERROR | stderr |     engine = cls(
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
2024-04-14 17:03:26 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 421, in _init_engine
2024-04-14 17:03:26 | ERROR | stderr |     return engine_class(*args, **kwargs)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 121, in __init__
2024-04-14 17:03:26 | ERROR | stderr |     self.model_executor = executor_class(
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 67, in __init__
2024-04-14 17:03:26 | ERROR | stderr |     self._init_workers_ray(placement_group)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 198, in _init_workers_ray
2024-04-14 17:03:26 | ERROR | stderr |     self._run_workers(
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 329, in _run_workers
2024-04-14 17:03:26 | ERROR | stderr |     ray_worker_outputs = ray.get(ray_worker_outputs)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
2024-04-14 17:03:26 | ERROR | stderr |     return fn(*args, **kwargs)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
2024-04-14 17:03:26 | ERROR | stderr |     return func(*args, **kwargs)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2624, in get
2024-04-14 17:03:26 | ERROR | stderr |     raise value.as_instanceof_cause()
2024-04-14 17:03:26 | ERROR | stderr | ray.exceptions.RayTaskError(IndexError): ray::RayWorkerVllm.execute_method() (pid=118164, ip=172.19.0.11, actor_id=88ffa9d610af919ac5d24eef01000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f6ed0c8b100>)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 51, in execute_method
2024-04-14 17:03:26 | ERROR | stderr |     raise e
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 43, in execute_method
2024-04-14 17:03:26 | ERROR | stderr |     return executor(*args, **kwargs)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 113, in load_model
2024-04-14 17:03:26 | ERROR | stderr |     self.model_runner.load_model()
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 158, in load_model
2024-04-14 17:03:26 | ERROR | stderr |     self.model = get_model(
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 58, in get_model
2024-04-14 17:03:26 | ERROR | stderr |     model_class = _get_model_architecture(model_config)[0]
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 41, in _get_model_architecture
2024-04-14 17:03:26 | ERROR | stderr |     model_cls = ModelRegistry.load_model_cls(arch)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/__init__.py", line 97, in load_model_cls
2024-04-14 17:03:26 | ERROR | stderr |     module = importlib.import_module(
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-04-14 17:03:26 | ERROR | stderr |     return _bootstrap._gcd_import(name[level:], package, level)
2024-04-14 17:03:26 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-04-14 17:03:26 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-04-14 17:03:26 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-04-14 17:03:26 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-04-14 17:03:26 | ERROR | stderr |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-04-14 17:03:26 | ERROR | stderr |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/commandr.py", line 52, in <module>
2024-04-14 17:03:26 | ERROR | stderr |     def layer_norm_func(hidden_states, weight, variance_epsilon):
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1826, in compile
2024-04-14 17:03:26 | ERROR | stderr |     return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 782, in optimize
2024-04-14 17:03:26 | ERROR | stderr |     compiler_config=backend.get_compiler_config()
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1671, in get_compiler_config
2024-04-14 17:03:26 | ERROR | stderr |     from torch._inductor.compile_fx import get_patched_config_dict
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 37, in <module>
2024-04-14 17:03:26 | ERROR | stderr |     from torch._inductor.codecache import code_hash, CompiledFxGraph, FxGraphCache
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2492, in <module>
2024-04-14 17:03:26 | ERROR | stderr |     AsyncCompile.warm_pool()
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2402, in warm_pool
2024-04-14 17:03:26 | ERROR | stderr |     pool = cls.process_pool()
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2380, in process_pool
2024-04-14 17:03:26 | ERROR | stderr |     caching_device_properties()
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2277, in caching_device_properties
2024-04-14 17:03:26 | ERROR | stderr |     device_interface.Worker.get_device_properties()
2024-04-14 17:03:26 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/device_interface.py", line 150, in get_device_properties
2024-04-14 17:03:26 | ERROR | stderr |     return caching_worker_device_properties["cuda"][device]
2024-04-14 17:03:26 | ERROR | stderr | IndexError: list index out of range
```
There is no difference when the GPUs are specified with CUDA_VISIBLE_DEVICES flag. The model does not load and therefore, the execution stops.

**Comment by youkaichao** [comment]
Can you show the full code? How do you use vllm?

And, does command-r work? Or it is just command-r-plus?

**Comment by sudarshan-kamath** [comment]
Thanks for the fast reply. I use this code from Fastchat for a vllm-worker

https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/vllm_worker.py

I will test the other model and update this post.

**Comment by sudarshan-kamath** [comment]
The issue is also with the Command-r model too. It looks like a compatibility issue. Trying with a fresh docker container now

**Comment by sudarshan-kamath** [comment]
Solved it with a fresh install with a new docker container.

**Comment by cduk** [comment]
Did you find the underlying cause of this error? I have the same problem: vLLM with Command-R/R+ and multiple GPUs gives the "IndexError: list index out of range" error.

**Comment by EIFY** [comment]
FYI, I was running something else with much newer versions of pytorch, triton, etc. but the likely cause of the issue is, surprisingly, incorrect multi-GPU setup instead of anything torch internal. See https://discuss.pytorch.org/t/bizarre-internaltorchdynamoerror-with-locally-and-formerly-working-code/216382/3.
