### ISSUE TITLE
[Bug]: ValueError: Can't set signal handler for SIGINT while SIGINT is being deferred within a DeferSigint context when tp>1

### ISSUE THREAD

**Issue by aciborowska** [vllm-project/vllm#4117]
### Your current environment

```text
[2024-04-16T16:36:16.632583Z] b1d60799 || Collecting environment information...
[2024-04-16T16:36:18.091248Z] b1d60799 || PyTorch version: 2.3.0a0+40ec155e58.nv24.03
[2024-04-16T16:36:18.091300Z] b1d60799 || Is debug build: False
[2024-04-16T16:36:18.091309Z] b1d60799 || CUDA used to build PyTorch: 12.4
[2024-04-16T16:36:18.091315Z] b1d60799 || ROCM used to build PyTorch: N/A
[2024-04-16T16:36:18.091321Z] b1d60799 || 
[2024-04-16T16:36:18.091326Z] b1d60799 || OS: Ubuntu 22.04.4 LTS (x86_64)
[2024-04-16T16:36:18.091332Z] b1d60799 || GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
[2024-04-16T16:36:18.091337Z] b1d60799 || Clang version: Could not collect
[2024-04-16T16:36:18.091342Z] b1d60799 || CMake version: version 3.28.3
[2024-04-16T16:36:18.091347Z] b1d60799 || Libc version: glibc-2.35
[2024-04-16T16:36:18.091352Z] b1d60799 || 
[2024-04-16T16:36:18.091358Z] b1d60799 || Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
[2024-04-16T16:36:18.091363Z] b1d60799 || Python platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.35
[2024-04-16T16:36:18.091368Z] b1d60799 || Is CUDA available: True
[2024-04-16T16:36:18.091374Z] b1d60799 || CUDA runtime version: 12.4.99
[2024-04-16T16:36:18.091379Z] b1d60799 || CUDA_MODULE_LOADING set to: LAZY
[2024-04-16T16:36:18.091384Z] b1d60799 || GPU models and configuration: 
[2024-04-16T16:36:18.091389Z] b1d60799 || GPU 0: NVIDIA A100-SXM4-40GB
[2024-04-16T16:36:18.091394Z] b1d60799 || GPU 1: NVIDIA A100-SXM4-40GB
[2024-04-16T16:36:18.091399Z] b1d60799 || 
[2024-04-16T16:36:18.091404Z] b1d60799 || Nvidia driver version: 535.161.07
[2024-04-16T16:36:18.091409Z] b1d60799 || cuDNN version: Probably one of the following:
[2024-04-16T16:36:18.091414Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn.so.9.0.0
[2024-04-16T16:36:18.091419Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.0.0
[2024-04-16T16:36:18.091424Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.0.0
[2024-04-16T16:36:18.091429Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
[2024-04-16T16:36:18.091434Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
[2024-04-16T16:36:18.091439Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.0.0
[2024-04-16T16:36:18.091448Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.0.0
[2024-04-16T16:36:18.091453Z] b1d60799 || /usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.0.0
[2024-04-16T16:36:18.091458Z] b1d60799 || HIP runtime version: N/A
[2024-04-16T16:36:18.091463Z] b1d60799 || MIOpen runtime version: N/A
[2024-04-16T16:36:18.091468Z] b1d60799 || Is XNNPACK available: True
[2024-04-16T16:36:18.091473Z] b1d60799 || 
[2024-04-16T16:36:18.091477Z] b1d60799 || CPU:
[2024-04-16T16:36:18.091483Z] b1d60799 || Architecture:                    x86_64
[2024-04-16T16:36:18.091488Z] b1d60799 || CPU op-mode(s):                  32-bit, 64-bit
[2024-04-16T16:36:18.091493Z] b1d60799 || Address sizes:                   46 bits physical, 48 bits virtual
[2024-04-16T16:36:18.091498Z] b1d60799 || Byte Order:                      Little Endian
[2024-04-16T16:36:18.091503Z] b1d60799 || CPU(s):                          96
[2024-04-16T16:36:18.091508Z] b1d60799 || On-line CPU(s) list:             0-95
[2024-04-16T16:36:18.091514Z] b1d60799 || Vendor ID:                       GenuineIntel
[2024-04-16T16:36:18.091521Z] b1d60799 || Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
[2024-04-16T16:36:18.091526Z] b1d60799 || CPU family:                      6
[2024-04-16T16:36:18.091531Z] b1d60799 || Model:                           85
[2024-04-16T16:36:18.091536Z] b1d60799 || Thread(s) per core:              2
[2024-04-16T16:36:18.091541Z] b1d60799 || Core(s) per socket:              24
[2024-04-16T16:36:18.091546Z] b1d60799 || Socket(s):                       2
[2024-04-16T16:36:18.091551Z] b1d60799 || Stepping:                        7
[2024-04-16T16:36:18.091556Z] b1d60799 || BogoMIPS:                        5999.99
[2024-04-16T16:36:18.091564Z] b1d60799 || Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
[2024-04-16T16:36:18.091569Z] b1d60799 || Hypervisor vendor:               KVM
[2024-04-16T16:36:18.091574Z] b1d60799 || Virtualization type:             full
[2024-04-16T16:36:18.091579Z] b1d60799 || L1d cache:                       1.5 MiB (48 instances)
[2024-04-16T16:36:18.091584Z] b1d60799 || L1i cache:                       1.5 MiB (48 instances)
[2024-04-16T16:36:18.091591Z] b1d60799 || L2 cache:                        48 MiB (48 instances)
[2024-04-16T16:36:18.091596Z] b1d60799 || L3 cache:                        71.5 MiB (2 instances)
[2024-04-16T16:36:18.091601Z] b1d60799 || NUMA node(s):                    2
[2024-04-16T16:36:18.091606Z] b1d60799 || NUMA node0 CPU(s):               0-23,48-71
[2024-04-16T16:36:18.091610Z] b1d60799 || NUMA node1 CPU(s):               24-47,72-95
[2024-04-16T16:36:18.091615Z] b1d60799 || Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
[2024-04-16T16:36:18.091620Z] b1d60799 || Vulnerability L1tf:              Mitigation; PTE Inversion
[2024-04-16T16:36:18.091626Z] b1d60799 || Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
[2024-04-16T16:36:18.091631Z] b1d60799 || Vulnerability Meltdown:          Mitigation; PTI
[2024-04-16T16:36:18.091636Z] b1d60799 || Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
[2024-04-16T16:36:18.091641Z] b1d60799 || Vulnerability Retbleed:          Vulnerable
[2024-04-16T16:36:18.091646Z] b1d60799 || Vulnerability Spec store bypass: Vulnerable
[2024-04-16T16:36:18.091651Z] b1d60799 || Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
[2024-04-16T16:36:18.091659Z] b1d60799 || Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
[2024-04-16T16:36:18.091664Z] b1d60799 || Vulnerability Srbds:             Not affected
[2024-04-16T16:36:18.091669Z] b1d60799 || Vulnerability Tsx async abort:   Not affected
[2024-04-16T16:36:18.091674Z] b1d60799 || 
[2024-04-16T16:36:18.091679Z] b1d60799 || Versions of relevant libraries:
[2024-04-16T16:36:18.091686Z] b1d60799 || [pip3] mypy-extensions==1.0.0
[2024-04-16T16:36:18.091691Z] b1d60799 || [pip3] mypy-protobuf==3.6.0
[2024-04-16T16:36:18.091696Z] b1d60799 || [pip3] numpy==1.26.3
[2024-04-16T16:36:18.091701Z] b1d60799 || [pip3] onnx==1.15.0rc2
[2024-04-16T16:36:18.091706Z] b1d60799 || [pip3] optree==0.10.0
[2024-04-16T16:36:18.091711Z] b1d60799 || [pip3] pytorch-quantization==2.1.2
[2024-04-16T16:36:18.091716Z] b1d60799 || [pip3] pytorch-triton==2.2.0+e28a256d7
[2024-04-16T16:36:18.091720Z] b1d60799 || [pip3] torch==2.3.0a0+40ec155e58.nv24.3
[2024-04-16T16:36:18.091727Z] b1d60799 || [pip3] torch-tensorrt==2.3.0a0
[2024-04-16T16:36:18.091732Z] b1d60799 || [pip3] torchdata==0.7.1a0
[2024-04-16T16:36:18.091737Z] b1d60799 || [pip3] torchtext==0.17.0a0
[2024-04-16T16:36:18.091742Z] b1d60799 || [pip3] torchvision==0.18.0a0
[2024-04-16T16:36:18.091747Z] b1d60799 || [pip3] triton==2.3.0
[2024-04-16T16:36:18.091752Z] b1d60799 || [conda] Could not collectROCM Version: Could not collect
[2024-04-16T16:36:18.091756Z] b1d60799 || Neuron SDK Version: N/A
[2024-04-16T16:36:18.091761Z] b1d60799 || vLLM Version: 0.4.0.post1
[2024-04-16T16:36:18.091766Z] b1d60799 || vLLM Build Flags:
[2024-04-16T16:36:18.091771Z] b1d60799 || CUDA Archs: 5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX; ROCm: Disabled; Neuron: Disabled
[2024-04-16T16:36:18.091776Z] b1d60799 || GPU Topology:
[2024-04-16T16:36:18.091783Z] b1d60799 || [4mGPU0	GPU1	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
[2024-04-16T16:36:18.091788Z] b1d60799 || GPU0	 X 	NV12	0-23,48-71	0		N/A
[2024-04-16T16:36:18.091792Z] b1d60799 || GPU1	NV12	 X 	0-23,48-71	0		N/A
[2024-04-16T16:36:18.091799Z] b1d60799 || 
```

### 🐛 Describe the bug

 I have recently upgraded from vllm 2.3.0 to 0.4.0.post1. When running with tp>1, I am getting the following error on one of the Ray Workers:
```
[2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813) Exception in initializer: <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813) Traceback (most recent call last): <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813)   File "/usr/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813)     initializer(*initargs) <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813)   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2430, in _async_compile_initializer <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813)     signal.signal(signal.SIGINT, signal.SIG_IGN) <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/utils.py", line 1825, in _signal_monkey_patch <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813)     raise ValueError( <none> [2024-04-16 16:31:57]
[34940b29] (RayWorkerVllm pid=5813) ValueError: Can't set signal handler for SIGINT while SIGINT is being deferred within a DeferSigint context. 
```

After the error is reported, initialization continues (including the worker that logged the error), and the model is loaded and generates content. It looks like this may mean that one of the workers may not clean up resources since it won't receive the SIGINT though?

I run this in a docker container built on top of ngc-24.03 with flash attention 2.5.6. I tried using ray 2.9.0, 2.9.3, and 2.10.0, but no luck and the same error every time.
Here are logs showing how the server is started:
```

[2024-04-16 16:31:30] [34940b29] [2024-04-16 16:31:30,634: INFO/MainProcess] Launching vLLM API server with command: python -m vllm.entrypoints.api_server --model meta-llama/Llama-2-7b-hf --tokenizer meta-llama/Llama-2-7b-hf --disable-log-requests --enforce-eager --swap-space 16 --tensor-parallel-size 2
<none> [2024-04-16 16:31:35] [34940b29] 2024-04-16 16:31:35,123	INFO worker.py:1724 -- Started a local Ray instance.
<none> [2024-04-16 16:31:37] [34940b29] INFO 04-16 16:31:37 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='meta-llama/Llama-2-7b-hf', tokenizer='meta-llama/Llama-2-7b-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, seed=0)
<none> [2024-04-16 16:31:50] [34940b29] INFO 04-16 16:31:50 selector.py:16] Using FlashAttention backend.
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813) Exception in initializer:
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813) Traceback (most recent call last):
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813)   File "/usr/lib/python3.10/concurrent/futures/process.py", line 233, in _process_worker
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813)     initializer(*initargs)
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813)   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2430, in _async_compile_initializer
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813)     signal.signal(signal.SIGINT, signal.SIG_IGN)
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813)   File "/usr/local/lib/python3.10/dist-packages/ray/_private/utils.py", line 1825, in _signal_monkey_patch
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813)     raise ValueError(
<none> [2024-04-16 16:31:57] [34940b29] (RayWorkerVllm pid=5813) ValueError: Can't set signal handler for SIGINT while SIGINT is being deferred within a DeferSigint context.
```

**Comment by mritterfigma** [comment]
+1, I've seen the same issue
