### ISSUE TITLE
[Misc] [CI]: AMD test flaky on main CI

### ISSUE THREAD

**Issue by cadedaniel** [vllm-project/vllm#4121]
### Anything you want to discuss about vllm.

Most recent `main` failure: https://buildkite.com/vllm/ci/builds/4903#018ee887-5a56-431e-9d7c-5a903b095046
Failed yesterday on `main` as well: https://buildkite.com/vllm/ci/builds/4858#018ee579-1bc4-4691-9327-2756e81185e1

```
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 4.70 GiB. GPU 0 has a total capacty of 63.98 GiB
of which 3.06 GiB is free. Of the allocated memory 51.96 GiB is allocated by PyTorch, and 29.10 MiB is reserved by
PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid
fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```

```
Traceback (most recent call last):
File "/opt/conda/envs/py_3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
  return _run_code(code, main_globals, None,
File "/opt/conda/envs/py_3.9/lib/python3.9/runpy.py", line 87, in _run_code
  exec(code, run_globals)
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/entrypoints/api_server.py", line 106, in <module>
  engine = AsyncLLMEngine.from_engine_args(
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 348, in from_engine_args
  engine = cls(
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 313, in __init__
  self.engine = self._init_engine(*args, **kwargs)
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 422, in _init_engine
  return engine_class(*args, **kwargs)
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/engine/llm_engine.py", line 140, in __init__
  self._initialize_kv_caches()
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/engine/llm_engine.py", line 226, in _initialize_kv_caches
  self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/executor/gpu_executor.py", line 119, in initialize_cache
  self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/worker/worker.py", line 174, in initialize_cache
  self._init_cache_engine()
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/worker/worker.py", line 179, in _init_cache_engine
  self.cache_engine = CacheEngine(self.cache_config, self.model_config,
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/worker/cache_engine.py", line 49, in __init__
  self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/vllm-0.4.0.post1+rocm603-py3.9-linux-x86_64.egg/vllm/worker/cache_engine.py", line 64, in _allocate_kv_cache
  torch.empty(kv_cache_shape,
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 4.70 GiB. GPU 0 has a total capacty of 63.98 GiB
of which 3.06 GiB is free. Of the allocated memory 51.96 GiB is allocated by PyTorch, and 29.10 MiB is reserved by
PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid
fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```

**Comment by cadedaniel** [comment]
Does anyone know how to debug this?

**Comment by shajrawi** [comment]
We are working on this - CI machine config issue not the backend itself. Hopefully we will have a fix in the next couple of days.

**Comment by claudiocassimiro** [comment]
Same issue here

**Comment by claudiocassimiro** [comment]
Hey, today I'm trying to run vllm on docker with llama 3 model and it working good. But when I trying to run with mistralai/Mixtral-8x7B-v0.1 the error happened again

**Comment by DarkLight1337** [comment]
Apart from having to wait longer for AMD tests to run, I haven't noticed any particular issues with AMD tests since #5112 so I'm closing this.

**Comment by DarkLight1337** [comment]
Some CI runs are getting this error:
```
.buildkite/run-amd-test.sh: line 38: /opt/amdgpu/etc/gpu_state: No such file or directory
```
