### ISSUE TITLE
ValueError: Total number of attention heads (52) must be divisible by tensor parallel size (3).

### ISSUE THREAD

**Issue by shellhue** [vllm-project/vllm#414]
I am running LLaMa 33B in a mathine with 3 v100 32G gpus, it seems the attention heads of the model cannot be divisible by tensor parallel size, is there any method working around?

**Comment by zhuohan123** [comment]
I believe the easiest way is to modify the model code to pad the dimensions to multiples of 3. To be honest, I believe finding another V100 and running the model on 4 GPUs is the actual easiest way. Feel free to re-open the issue if you have more questions.

**Comment by proceduralia** [comment]
I'm having similar troubles. In particular, if you add up the constraints of tensor parallel size being simultaneously linked to the number of heads and the dictionary size, and the constraints on the number of gpus per node being fixed, it rapidly becomes very difficult to do proper distributed computations without many headaches.

What would be the recommended solution right now? What did you mean by "modify the model code to pad the dimensions to multiples of 3"?

**Comment by oushu1zhangxiangxuan1** [comment]
Same problem with me:
1. SET to 6: Total number of attention heads (40) must be divisible by tensor parallel size (6).
2. SET to 5: 
```
2024-01-22 14:32:19,671 INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 
2024-01-22 14:32:19,679 INFO worker.py:1724 -- Connected to Ray cluster.
INFO 01-22 14:32:19 llm_engine.py:73] Initializing an LLM engine with config: model='/tmp/CodeLlama-13b-Instruct-hf', tokenizer='/tmp/CodeLlama-13b-Instruct-hf', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=5, quantization=None, enforce_eager=False, seed=0)
2024-01-22 14:32:27 | ERROR | stderr | Traceback (most recent call last):
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-01-22 14:32:27 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/runpy.py", line 86, in _run_code
2024-01-22 14:32:27 | ERROR | stderr |     exec(code, run_globals)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/fastchat/serve/vllm_worker.py", line 259, in <module>
2024-01-22 14:32:27 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 496, in from_engine_args
2024-01-22 14:32:27 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
2024-01-22 14:32:27 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
2024-01-22 14:32:27 | ERROR | stderr |     return engine_class(*args, **kwargs)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 108, in __init__
2024-01-22 14:32:27 | ERROR | stderr |     self._init_workers_ray(placement_group)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 195, in _init_workers_ray
2024-01-22 14:32:27 | ERROR | stderr |     self._run_workers(
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 755, in _run_workers
2024-01-22 14:32:27 | ERROR | stderr |     self._run_workers_in_batch(workers, method, *args, **kwargs))
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 732, in _run_workers_in_batch
2024-01-22 14:32:27 | ERROR | stderr |     all_outputs = ray.get(all_outputs)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
2024-01-22 14:32:27 | ERROR | stderr |     return fn(*args, **kwargs)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
2024-01-22 14:32:27 | ERROR | stderr |     return func(*args, **kwargs)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/ray/_private/worker.py", line 2624, in get
2024-01-22 14:32:27 | ERROR | stderr |     raise value.as_instanceof_cause()
2024-01-22 14:32:27 | ERROR | stderr | ray.exceptions.RayTaskError(AssertionError): ray::RayWorkerVllm.execute_method() (pid=9107, ip=172.21.32.7, actor_id=5e6bd6188901024c707bb3ba07000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f7c1d248b50>)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 31, in execute_method
2024-01-22 14:32:27 | ERROR | stderr |     return executor(*args, **kwargs)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/worker/worker.py", line 79, in load_model
2024-01-22 14:32:27 | ERROR | stderr |     self.model_runner.load_model()
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 57, in load_model
2024-01-22 14:32:27 | ERROR | stderr |     self.model = get_model(self.model_config)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 65, in get_model
2024-01-22 14:32:27 | ERROR | stderr |     model = model_class(model_config.hf_config, linear_method)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 275, in __init__
2024-01-22 14:32:27 | ERROR | stderr |     self.model = LlamaModel(config, linear_method)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 233, in __init__
2024-01-22 14:32:27 | ERROR | stderr |     self.embed_tokens = VocabParallelEmbedding(
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 63, in __init__
2024-01-22 14:32:27 | ERROR | stderr |     vocab_range_from_global_vocab_size(
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 31, in vocab_range_from_global_vocab_size
2024-01-22 14:32:27 | ERROR | stderr |     per_partition_vocab_size = divide(global_vocab_size, world_size)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/utils.py", line 19, in divide
2024-01-22 14:32:27 | ERROR | stderr |     ensure_divisibility(numerator, denominator)
2024-01-22 14:32:27 | ERROR | stderr |   File "/root/space/conda_envs/t2c12/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/utils.py", line 12, in ensure_divisibility
2024-01-22 14:32:27 | ERROR | stderr |     assert numerator % denominator == 0, "{} is not divisible by {}".format(
2024-01-22 14:32:27 | ERROR | stderr | AssertionError: 32064 is not divisible by 5
```
