### ISSUE TITLE
[Installation]: import llm meet error

### ISSUE THREAD

**Issue by 18140663659** [vllm-project/vllm#4163]
### Your current environment

```text
Traceback (most recent call last):
  File "inference.py", line 355, in <module>
    data_all_with_response = get_pred_func(data=data_all, task_prompt=task_prompt,\
  File "inference.py", line 24, in get_pred_vllm
    from vllm import LLM, SamplingParams
  File "/usr/local/lib/python3.8/dist-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
  File "/usr/local/lib/python3.8/dist-packages/vllm/config.py", line 9, in <module>
    from vllm.utils import get_cpu_memory, is_hip
  File "/usr/local/lib/python3.8/dist-packages/vllm/utils.py", line 8, in <module>
    from vllm._C import cuda_utils
ImportError: /usr/local/lib/python3.8/dist-packages/vllm/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE```


### How you are installing vllm

```sh
export VLLM_VERSION=0.2.4
export PYTHON_VERSION=38
pip install https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cu118-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux1_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cu118
```

**Comment by youkaichao** [comment]
Did you try `export VLLM_VERSION=0.4.0.post1` ? `0.2.4` is quite old.

**Comment by 18140663659** [comment]
i use above config, meet another problem:
export VLLM_VERSION=0.4.0
export PYTHON_VERSION=38
pip install https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cu118-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux1_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cu118
pip intall flash_attn==2.2.0

File "/usr/local/lib/python3.8/dist-packages/vllm/attention/backends/flash_attn.py", line 195, in forward
    output = flash_attn_varlen_func(
TypeError: flash_attn_varlen_func() got an unexpected keyword argument 'window_size'

**Comment by linchen111** [comment]
> i use above config, meet another problem:我使用上面的配置，遇到另一个问题： export VLLM_VERSION=0.4.0导出 VLLM_VERSION=0.4.0 export PYTHON_VERSION=38 导出 PYTHON_VERSION=38 pip install [https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cu118-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux1_x86_64.whl](https://github.com/vllm-project/vllm/releases/download/v$%7BVLLM_VERSION%7D/vllm-$%7BVLLM_VERSION%7D+cu118-cp$%7BPYTHON_VERSION%7D-cp$%7BPYTHON_VERSION%7D-manylinux1_x86_64.whl) --extra-index-url https://download.pytorch.org/whl/cu118 pip intall flash_attn==2.2.0pip 安装 flash_attn==2.2.0
> 
> File "/usr/local/lib/python3.8/dist-packages/vllm/attention/backends/flash_attn.py", line 195, in forward文件“/usr/local/lib/python3.8/dist-packages/vllm/attention/backends/flash_attn.py”，第 195 行，向前 output = flash_attn_varlen_func(输出 = flash_attn_varlen_func( TypeError: flash_attn_varlen_func() got an unexpected keyword argument 'window_size'类型错误：flash_attn_varlen_func() 获得意外的关键字参数“window_size”

did you solve this?

**Comment by linqingxu** [comment]
flash_attn_varlen_func() got an unexpected keyword argument 'window_size'

**Comment by hmellor** [comment]
vLLM no longer supports Python 3.8 and v4.0.0 is also now a very old version.
