### ISSUE TITLE
Streaming Error: TypeError: `dumps_kwargs` keyword arguments are no longer supported.

### ISSUE THREAD

**Issue by aldrinc** [vllm-project/vllm#419]
Receiving the following when attempting to enable streaming on the server.

The model returns successfully without streaming (ie stream key removed)! 

This worked in the past but 

vllm 0.1.2
RTXA6000

Docker startup script
`bash -c 'pip install --upgrade huggingface_hub && huggingface-cli login --token $HUGGINGFACE_TOKEN && pip install vllm && python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 8000 --model my_model --tokenizer hf-internal-testing/llama-tokenizer'`

Prompt
`{
    "model": "my_model",
    "prompt": "###System: You are world class assistant. Answer the question, provide solutions, and justify your reasoning step by step. \n ###Human: Hello. \n ###Assistant:",
    "max_tokens": 1000,
    "temperature": 0.7,
    "user": "test-user-id",
    "stream": true
}`

Error
`
2023-07-10T20:53:51.940730783Z ERROR:    Exception in ASGI application
2023-07-10T20:53:51.940756172Z Traceback (most recent call last):
2023-07-10T20:53:51.940758164Z   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-07-10T20:53:51.940760457Z     result = await app(  # type: ignore[func-returns-value]
2023-07-10T20:53:51.940762539Z   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-07-10T20:53:51.940764779Z     return await self.app(scope, receive, send)
2023-07-10T20:53:51.940770548Z   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
2023-07-10T20:53:51.940772131Z     await self.middleware_stack(scope, receive, send)
2023-07-10T20:53:51.940773663Z   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
2023-07-10T20:53:51.940775505Z     raise exc
2023-07-10T20:53:51.940777499Z   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2023-07-10T20:53:51.940779268Z     await self.app(scope, receive, _send)
2023-07-10T20:53:51.940780702Z   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
2023-07-10T20:53:51.940782355Z     await self.app(scope, receive, send)
2023-07-10T20:53:51.940783900Z   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-07-10T20:53:51.940785552Z     raise exc
2023-07-10T20:53:51.940787124Z   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-07-10T20:53:51.940788652Z     await self.app(scope, receive, sender)
2023-07-10T20:53:51.940790181Z   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-07-10T20:53:51.940795248Z     raise e
2023-07-10T20:53:51.940796831Z   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-07-10T20:53:51.940798375Z     await self.app(scope, receive, send)
2023-07-10T20:53:51.940799902Z   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
2023-07-10T20:53:51.940801419Z     await route.handle(scope, receive, send)
2023-07-10T20:53:51.940802971Z   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2023-07-10T20:53:51.940804555Z     await self.app(scope, receive, send)
2023-07-10T20:53:51.940806108Z   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
2023-07-10T20:53:51.940816066Z     await response(scope, receive, send)
2023-07-10T20:53:51.940818700Z   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 270, in __call__
2023-07-10T20:53:51.940820399Z     async with anyio.create_task_group() as task_group:
2023-07-10T20:53:51.940821903Z   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2023-07-10T20:53:51.940823475Z     raise exceptions[0]
2023-07-10T20:53:51.940825447Z   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 273, in wrap
2023-07-10T20:53:51.940826917Z     await func()
2023-07-10T20:53:51.940828421Z   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 262, in stream_response
2023-07-10T20:53:51.940829925Z     async for chunk in self.body_iterator:
2023-07-10T20:53:51.940831499Z   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 196, in completion_stream_generator
2023-07-10T20:53:51.940833468Z     response_json = create_stream_response_json(
2023-07-10T20:53:51.940835024Z   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 175, in create_stream_response_json
2023-07-10T20:53:51.940836571Z     response_json = response.json(ensure_ascii=False)
2023-07-10T20:53:51.940838017Z   File "/usr/local/lib/python3.10/dist-packages/typing_extensions.py", line 2562, in wrapper
2023-07-10T20:53:51.940839550Z     return __arg(*args, **kwargs)
2023-07-10T20:53:51.940841138Z   File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 926, in json
2023-07-10T20:53:51.940842739Z     raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
2023-07-10T20:53:51.940844730Z TypeError: `dumps_kwargs` keyword arguments are no longer supported.
2023-07-10T20:53:53.675581382Z INFO:     100.64.0.24:35994 - "GET / HTTP/1.1" 404 Not Found`

**Comment by wuzhihui3723** [comment]
same error
