### ISSUE TITLE
[Bug]: Using the latest docker image to load CohereForAIc4ai-command-r-plus Model, it crashed

### ISSUE THREAD

**Issue by majestichou** [vllm-project/vllm#4262]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.1.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 3.25.0-rc2
Libc version: glibc-2.17

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 12.2.128
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                192
On-line CPU(s) list:   0-191
Thread(s) per core:    2
Core(s) per socket:    48
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7642 48-Core Processor
Stepping:              0
CPU MHz:               1500.000
CPU max MHz:           2300.0000
CPU min MHz:           1500.0000
BogoMIPS:              4599.91
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-47,96-143
NUMA node1 CPU(s):     48-95,144-191
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] numpydoc==1.5.0
[pip3] nvidia-nccl-cu12==2.18.1
[pip3] torch==2.1.1
[pip3] triton==2.1.0
[conda] _anaconda_depends         2023.09             py311_mkl_1    https://repo.anaconda.com/pkgs/main
[conda] blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
[conda] mkl                       2023.1.0         h213fc3f_46343    https://repo.anaconda.com/pkgs/main
[conda] mkl-service               2.4.0           py311h5eee18b_1    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.3.8           py311h5eee18b_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.2.4           py311hdb19cb5_0    https://repo.anaconda.com/pkgs/main
[conda] numpy                     1.24.3          py311h08b1b3b_1    https://repo.anaconda.com/pkgs/main
[conda] numpy-base                1.24.3          py311hf175353_1    https://repo.anaconda.com/pkgs/main
[conda] numpydoc                  1.5.0           py311h06a4308_0    https://repo.anaconda.com/pkgs/mainROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    0-47,96-143     0               N/A
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    0-47,96-143     0               N/A
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    0-47,96-143     0               N/A
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    0-47,96-143     0               N/A
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    48-95,144-191   1               N/A
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    48-95,144-191   1               N/A
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    48-95,144-191   1               N/A
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      48-95,144-191   1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

```

### 🐛 Describe the bug

I use the docker image vllm/vllm-openai:v0.4.0.post1 of vllm to run the CohereForAIc4ai-command-r-plus model weight. The commad is as follows:
`docker run --gpus 8 -p 8080:8000 --ipc=host -v /home/mnt/test/llm-test/serving/data/models/:/data/models/ --env "TRANSFORMERS_OFFLINE=1" --env "HF_DATASET_OFFLINE=1" --ipc=host vllm/vllm-openai:v0.4.0.post1 --model "/data/models/CohereForAIc4ai-command-r-plus/" --max-model-len 8192 --tensor-parallel-size 8 --gpu-memory-utilization 0.9`
It crashed. The error is as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 157, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/workspace/vllm/engine/async_llm_engine.py", line 347, in from_engine_args
    engine = cls(
  File "/workspace/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 421, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 118, in __init__
    self.model_executor = executor_class(
  File "/workspace/vllm/executor/ray_gpu_executor.py", line 66, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/executor/ray_gpu_executor.py", line 196, in _init_workers_ray
    self._run_workers(
  File "/workspace/vllm/executor/ray_gpu_executor.py", line 328, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/workspace/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/workspace/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
  File "/workspace/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/workspace/vllm/model_executor/models/commandr.py", line 325, in load_weights
    param = params_dict[name]
KeyError: 'model.layers.0.self_attn.k_norm.weight'
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44] Error executing method load_model. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]   File "/workspace/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]   File "/workspace/vllm/worker/worker.py", line 107, in load_model
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]     self.model_runner.load_model()
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]   File "/workspace/vllm/worker/model_runner.py", line 95, in load_model
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]     self.model = get_model(
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]   File "/workspace/vllm/model_executor/model_loader.py", line 101, in get_model
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]     model.load_weights(model_config.model, model_config.download_dir,
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]   File "/workspace/vllm/model_executor/models/commandr.py", line 325, in load_weights
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44]     param = params_dict[name]
(RayWorkerVllm pid=11225) ERROR 04-22 17:32:12 ray_utils.py:44] KeyError: 'model.layers.0.self_attn.k_norm.weight'
(RayWorkerVllm pid=11019) INFO 04-22 17:31:18 selector.py:16] Using FlashAttention backend. [repeated 6x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorkerVllm pid=11122) INFO 04-22 17:31:19 pynccl_utils.py:45] vLLM is using nccl==2.18.1 [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44] Error executing method load_model. This might cause deadlock in distributed execution. [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44] Traceback (most recent call last): [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]   File "/workspace/vllm/engine/ray_utils.py", line 37, in execute_method [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]     return executor(*args, **kwargs) [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]   File "/workspace/vllm/worker/worker.py", line 107, in load_model [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]     self.model_runner.load_model() [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]   File "/workspace/vllm/worker/model_runner.py", line 95, in load_model [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]     self.model = get_model( [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]   File "/workspace/vllm/model_executor/model_loader.py", line 101, in get_model [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]     model.load_weights(model_config.model, model_config.download_dir, [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]   File "/workspace/vllm/model_executor/models/commandr.py", line 325, in load_weights [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44]     param = params_dict[name] [repeated 6x across cluster]
(RayWorkerVllm pid=11019) ERROR 04-22 17:32:14 ray_utils.py:44] KeyError: 'model.layers.0.self_attn.k_norm.weight' [repeated 6x across cluster]
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```

**Comment by majestichou** [comment]
I load the newest docker images: vllm 0.4.1. Everything is OK
