### ISSUE TITLE
RuntimeError: Failed to import transformers.models.bloom.modeling_bloom because of the following error (look up to see its traceback): /usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by jiejie1993** [vllm-project/vllm#431]
I install vllm via pip in "nvcr.io/nvidia/pytorch:22.12-py3" docker image.
When I run the benchmark_throughput.py as follows:
`python benchmark_throughput.py --backend=hf --dataset=../benchmark_test_dataset/ShareGPT_V3_unfiltered_cleaned_split.json --model=../huggingface_models/bloom7b1/ --hf-max-batch-size=8`
got the follow error :
`huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1146, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/bloom/modeling_bloom.py", line 35, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/usr/local/lib/python3.8/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 34, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.8/dist-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/__init__.py", line 112, in <module>
    from .launch import (
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/launch.py", line 27, in <module>
    from ..utils.other import merge_dicts
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/other.py", line 24, in <module>
    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module.py", line 16, in <module>
    import transformer_engine_extensions as tex
ImportError: /usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "benchmark_throughput.py", line 218, in <module>
    main(args)
  File "benchmark_throughput.py", line 182, in main
    elapsed_time = run_hf(requests, args.model, tokenizer, args.n,
  File "benchmark_throughput.py", line 122, in run_hf
    llm = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 470, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 602, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 616, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 561, in getattribute_from_module
    if hasattr(module, attr):
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1136, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1148, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bloom.modeling_bloom because of the following error (look up to see its traceback):
/usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

**Comment by zjc17** [comment]
similar problem when exec `python -m vllm.entrypoints.openai.api_server`

**Comment by WoosukKwon** [comment]
Hi @jiejie1993 @zjc17, thanks for reporting this. This is an ABI problem. Please uninstall torch before installing vllm.
That is, run:
```bash
pip uninstall torch
pip install vllm
```

**Comment by Tismoney** [comment]
@WoosukKwon 
I faced this bug by following recommended [instructions](https://vllm.readthedocs.io/en/latest/getting_started/installation.html):

```
>> docker run --gpus all -it --rm --shm-size=8g nvcr.io/nvidia/pytorch:22.12-py3
=============
== PyTorch ==
=============

NVIDIA Release 22.12 (build 49968248)
PyTorch Version 1.14.0a0+410ce96
...
>> root@1553075b03ff:/workspace# pip uninstall -y torch
Found existing installation: torch 1.14.0a0+410ce96
Uninstalling torch-1.14.0a0+410ce96:
  Successfully uninstalled torch-1.14.0a0+410ce96
>> root@1553075b03ff:/workspace# pip install vllm
...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.0a0 requires torch==1.14.0a0+410ce96, but you have torch 2.0.1 which is incompatible.
torchtext 0.13.0a0+fae8e8c requires torch==1.14.0a0+410ce96, but you have torch 2.0.1 which is incompatible.
torch-tensorrt 1.3.0a0 requires torch<1.15.0,>=1.13.0dev, but you have torch 2.0.1 which is incompatible.

Successfully installed GitPython-3.1.32 accelerate-0.21.0 aiofiles-23.1.0 aiohttp-3.8.4 aiosignal-1.3.1 altair-5.0.1 anyio-3.7.1 async-timeout-4.0.2 docker-pycreds-0.4.0 fastapi-
0.100.0 ffmpy-0.3.1 filelock-3.12.2 frozenlist-1.4.0 fschat-0.2.18 gitdb-4.0.10 gradio-3.35.2 gradio-client-0.2.9 h11-0.14.0 httpcore-0.17.3 httpx-0.24.1 huggingface-hub-0.16.4 l
inkify-it-py-1.0.3 lit-16.0.6 markdown2-2.4.9 multidict-6.0.4 mypy-extensions-1.0.0 nh3-0.2.14 ninja-1.11.1 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-c
uda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.2.10.91 nvidia-cusolver-cu11-11.4.0.1 nvidia-
cusparse-cu11-11.7.4.91 nvidia-nccl-cu11-2.14.3 nvidia-nvtx-cu11-11.7.91 orjson-3.9.2 pathtools-0.1.2 peft-0.4.0 pydub-0.25.1 pygments-2.15.1 pyre-extensions-0.0.29 python-multip
art-0.0.6 ray-2.5.1 rich-13.3.1 safetensors-0.3.1 semantic-version-2.10.0 sentencepiece-0.1.99 sentry-sdk-1.28.1 setproctitle-1.3.2 shortuuid-1.0.11 smmap-5.0.0 sniffio-1.3.0 sta
rlette-0.27.0 svgwrite-1.4.3 tiktoken-0.4.0 tokenizers-0.13.3 torch-2.0.1 transformers-4.28.1 triton-2.0.0 typing-extensions-4.7.1 typing-inspect-0.9.0 uc-micro-py-1.0.2 uvicorn-
0.23.0 vllm-0.1.2 wandb-0.15.5 wavedrom-2.0.3.post3 websockets-11.0.3 xformers-0.0.20 yarl-1.9.2
>> root@1553075b03ff:/workspace# python -m vllm.entrypoints.openai.api_server
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 17, in <module>
    from fastchat.model.model_adapter import get_conversation_template
  File "/usr/local/lib/python3.8/dist-packages/fastchat/model/__init__.py", line 1, in <module>
    from fastchat.model.model_adapter import (
  File "/usr/local/lib/python3.8/dist-packages/fastchat/model/model_adapter.py", line 13, in <module>
    import accelerate
  File "/usr/local/lib/python3.8/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.8/dist-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/__init__.py", line 133, in <module>
    from .launch import (
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/other.py", line 25, in <module>
    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/__init__.py", line 7, in <module>
    from . import pytorch
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module.py", line 16, in <module>
    import transformer_engine_extensions as tex
ImportError: /usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by doudoujay** [comment]
`python -m vllm.entrypoints.openai.api_server` has some issue
but seems like `python -m vllm.entrypoints.api_server` was fine

**Comment by zhuohan123** [comment]
> @WoosukKwon I faced this bug by following recommended [instructions](https://vllm.readthedocs.io/en/latest/getting_started/installation.html):
> 
> ```
> >> docker run --gpus all -it --rm --shm-size=8g nvcr.io/nvidia/pytorch:22.12-py3
> =============
> == PyTorch ==
> =============
> 
> NVIDIA Release 22.12 (build 49968248)
> PyTorch Version 1.14.0a0+410ce96
> ...
> >> root@1553075b03ff:/workspace# pip uninstall -y torch
> Found existing installation: torch 1.14.0a0+410ce96
> Uninstalling torch-1.14.0a0+410ce96:
>   Successfully uninstalled torch-1.14.0a0+410ce96
> >> root@1553075b03ff:/workspace# pip install vllm
> ...
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> torchvision 0.15.0a0 requires torch==1.14.0a0+410ce96, but you have torch 2.0.1 which is incompatible.
> torchtext 0.13.0a0+fae8e8c requires torch==1.14.0a0+410ce96, but you have torch 2.0.1 which is incompatible.
> torch-tensorrt 1.3.0a0 requires torch<1.15.0,>=1.13.0dev, but you have torch 2.0.1 which is incompatible.
> 
> Successfully installed GitPython-3.1.32 accelerate-0.21.0 aiofiles-23.1.0 aiohttp-3.8.4 aiosignal-1.3.1 altair-5.0.1 anyio-3.7.1 async-timeout-4.0.2 docker-pycreds-0.4.0 fastapi-
> 0.100.0 ffmpy-0.3.1 filelock-3.12.2 frozenlist-1.4.0 fschat-0.2.18 gitdb-4.0.10 gradio-3.35.2 gradio-client-0.2.9 h11-0.14.0 httpcore-0.17.3 httpx-0.24.1 huggingface-hub-0.16.4 l
> inkify-it-py-1.0.3 lit-16.0.6 markdown2-2.4.9 multidict-6.0.4 mypy-extensions-1.0.0 nh3-0.2.14 ninja-1.11.1 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-c
> uda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.2.10.91 nvidia-cusolver-cu11-11.4.0.1 nvidia-
> cusparse-cu11-11.7.4.91 nvidia-nccl-cu11-2.14.3 nvidia-nvtx-cu11-11.7.91 orjson-3.9.2 pathtools-0.1.2 peft-0.4.0 pydub-0.25.1 pygments-2.15.1 pyre-extensions-0.0.29 python-multip
> art-0.0.6 ray-2.5.1 rich-13.3.1 safetensors-0.3.1 semantic-version-2.10.0 sentencepiece-0.1.99 sentry-sdk-1.28.1 setproctitle-1.3.2 shortuuid-1.0.11 smmap-5.0.0 sniffio-1.3.0 sta
> rlette-0.27.0 svgwrite-1.4.3 tiktoken-0.4.0 tokenizers-0.13.3 torch-2.0.1 transformers-4.28.1 triton-2.0.0 typing-extensions-4.7.1 typing-inspect-0.9.0 uc-micro-py-1.0.2 uvicorn-
> 0.23.0 vllm-0.1.2 wandb-0.15.5 wavedrom-2.0.3.post3 websockets-11.0.3 xformers-0.0.20 yarl-1.9.2
> >> root@1553075b03ff:/workspace# python -m vllm.entrypoints.openai.api_server
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 17, in <module>
>     from fastchat.model.model_adapter import get_conversation_template
>   File "/usr/local/lib/python3.8/dist-packages/fastchat/model/__init__.py", line 1, in <module>
>     from fastchat.model.model_adapter import (
>   File "/usr/local/lib/python3.8/dist-packages/fastchat/model/model_adapter.py", line 13, in <module>
>     import accelerate
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/__init__.py", line 3, in <module>
>     from .accelerator import Accelerator
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 35, in <module>
>     from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/checkpointing.py", line 24, in <module>
>     from .utils import (
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/__init__.py", line 133, in <module>
>     from .launch import (
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/launch.py", line 33, in <module>
>     from ..utils.other import is_port_in_use, merge_dicts
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/other.py", line 25, in <module>
>     from .transformer_engine import convert_model
>   File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
>     import transformer_engine.pytorch as te
>   File "/usr/local/lib/python3.8/dist-packages/transformer_engine/__init__.py", line 7, in <module>
>     from . import pytorch
>   File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
>     from .module import LayerNormLinear
>   File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module.py", line 16, in <module>
>     import transformer_engine_extensions as tex
> ImportError: /usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
> ```

Seems like this is an issue with the `accelerate` package. This is introduced by fastchat for the conversation template. Can you make sure the `accelerate` installation is correct?

**Comment by HanYang1385** [comment]
try 'pip uninstall -y transformer-engine' , It can also run after uninstalling transformer-engine

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
