### ISSUE TITLE
[Bug]: Call to CUDA function failed - unknown error

### ISSUE THREAD

**Issue by roclark** [vllm-project/vllm#4341]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA RTX 6000 Ada Generation
GPU 1: NVIDIA RTX 6000 Ada Generation

Nvidia driver version: 551.61
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 7900X3D 12-Core Processor
CPU family:                      25
Model:                           97
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        2
BogoMIPS:                        8783.31
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 clzero xsaveerptr arat npt nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm
Virtualization:                  AMD-V
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        12 MiB (12 instances)
L3 cache:                        96 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.19.3
[pip3] torch==2.2.1
[pip3] triton==2.2.0
[pip3] vllm-nccl-cu12==2.18.1.0.3.0
[conda] Could not collectROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS                             N/A
GPU1    SYS      X                              N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### 🐛 Describe the bug

I'm running inside the official vllm Docker container on WSL2 and hitting NCCL errors when I migrate from v0.4.0 to v0.4.1. I was able to run the `vllm/vllm-openai:v0.4.0` container without issue but when I run the new `vllm/vllm-openai:v0.4.1` container I get the following error:

```
INFO 04-24 22:09:32 utils.py:608] Found nccl from library /root/.config/vllm/nccl/cu12/libnccl.so.2.18.1
WARNING 04-24 22:09:32 utils.py:414] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 04-24 22:09:32 selector.py:28] Using FlashAttention backend.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 159, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 361, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 319, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 437, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 148, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 41, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 22, in _init_executor
    self._init_non_spec_worker()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 50, in _init_non_spec_worker
    self.driver_worker.init_device()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 110, in init_device
    init_worker_distributed_environment(self.parallel_config, self.rank,
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 313, in init_worker_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1992, in all_reduce
    work = group.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.19.3
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 999 'unknown error'
```

I saw #4312 but am running as `root` and don't think it's related here as I can load the NCCL library without issue.

Running `NCCL_DEBUG=INFO` doesn't appear to give me anything valuable either:

```
INFO 04-24 22:15:01 utils.py:608] Found nccl from library /root/.config/vllm/nccl/cu12/libnccl.so.2.18.1
WARNING 04-24 22:15:01 utils.py:414] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 04-24 22:15:01 selector.py:28] Using FlashAttention backend.
d10e4b003337:399:399 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0>
d10e4b003337:399:399 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
d10e4b003337:399:399 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.19.3+cuda12.3
d10e4b003337:399:446 [0] NCCL INFO Failed to open libibverbs.so[.1]
d10e4b003337:399:446 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
d10e4b003337:399:446 [0] NCCL INFO Using non-device net plugin version 0
d10e4b003337:399:446 [0] NCCL INFO Using network Socket
d10e4b003337:399:446 [0] NCCL INFO comm 0x563f6bd1d210 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 1000 commId 0xe0a4940195a97500 - Init START
d10e4b003337:399:446 [0] NCCL INFO Channel 00/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 01/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 02/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 03/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 04/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 05/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 06/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 07/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 08/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 09/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 10/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 11/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 12/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 13/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 14/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 15/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 16/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 17/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 18/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 19/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 20/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 21/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 22/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 23/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 24/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 25/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 26/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 27/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 28/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 29/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 30/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Channel 31/32 :    0
d10e4b003337:399:446 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
d10e4b003337:399:446 [0] NCCL INFO P2P Chunksize set to 131072

d10e4b003337:399:446 [0] include/alloc.h:111 NCCL WARN Cuda failure 999 'unknown error'
d10e4b003337:399:446 [0] NCCL INFO include/alloc.h:198 -> 1
d10e4b003337:399:446 [0] NCCL INFO channel.cc:40 -> 1
d10e4b003337:399:446 [0] NCCL INFO init.cc:513 -> 1
d10e4b003337:399:446 [0] NCCL INFO init.cc:1113 -> 1
d10e4b003337:399:446 [0] NCCL INFO init.cc:1396 -> 1
d10e4b003337:399:446 [0] NCCL INFO group.cc:64 -> 1 [Async thread]
d10e4b003337:399:399 [0] NCCL INFO group.cc:418 -> 1
d10e4b003337:399:399 [0] NCCL INFO group.cc:95 -> 1
```

I see the errors about `libnccl-net` but don't think that would be related here since I am just attempting to use a single GPU and don't have IB or anything if I understand correctly.

I also don't see this issue with the `vllm/vllm-openai:v0.4.0.post1` image so it appears something was introduced with the `v0.4.1` image.

**Comment by youkaichao** [comment]
What is the command you execute? Are you using tensor parallel?

**Comment by roclark** [comment]
I've tried running the container without args (looks like it serves a default model?) as well as with `--model <HF model name>` which worked with the previous two images but not v0.4.1. No tensor parallelism right now.

**Comment by youkaichao** [comment]
I feel like this is a nccl issue.

Can you try to execute `torchrun --nproc-per-node 1 test.py` inside docker, where `test.py` contains:

```python
# test.py
import torch
import torch.distributed as dist
dist.init_process_group(backend='nccl')
dist.all_reduce(torch.zeros(1).cuda())
```

**Comment by roclark** [comment]
Yeah, seems like a NCCL issue to me:

```
Traceback (most recent call last):
  File "/vllm-workspace/test.py", line 4, in <module>
    dist.all_reduce(torch.zeros(1).cuda())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1992, in all_reduce
    work = group.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1691, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.19.3
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 999 'unknown error'
[2024-04-24 23:07:58,741] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 41) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-24_23:07:58
  host      : bf696a2225c5
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 41)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by youkaichao** [comment]
Then we can do nothing, you have to report to nccl team https://github.com/NVIDIA/nccl , or change your machine configuration to make nccl work :(

**Comment by roclark** [comment]
I will reach out, thanks. Since it works in the older containers with older NCCL versions, is there a way that I can override the NCCL version in the container build process? I'm not entirely clear when it is built/installed in the Dockerfile/requirements*txt.

**Comment by youkaichao** [comment]
> File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 313, in init_worker_distributed_environment
>     torch.distributed.all_reduce(torch.zeros(1).cuda())

Maybe you can try to comment out this line. It is not possible to change the version used by pytorch.

**Comment by test-dan-run** [comment]
Hi any luck with this issue? @roclark
