### ISSUE TITLE
[Usage]: Not enough memory when run a 33b model float16 on 2 x L40 GPU (48G) 

### ISSUE THREAD

**Issue by garyyang85** [vllm-project/vllm#4429]
### Your current environment

Not enough memory when run deepseek-coder-33b-instruct model on two L40 GPUs (48G) with vllm 0.4.1.  Also tried --enforce-eager --gpu-memory-utilization, did not help.
```
python -m vllm.entrypoints.openai.api_server --dtype float16 --trust-remote-code --model /models/deepseek-coder-33b-instruct  --served-model-name deepseek-coder-33b-instruct --port 8000 --host 0.0.0.0 --tensor-parallel-size 2
```
It reports error:
```
ERROR 04-28 15:55:45 worker_base.py:157] Error executing method initialize_cache. This might cause deadlock in distributed execution.
ERROR 04-28 15:55:45 worker_base.py:157] Traceback (most recent call last):
ERROR 04-28 15:55:45 worker_base.py:157]   File "/root/miniconda3/envs/deepseek/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 149, in execute_method
ERROR 04-28 15:55:45 worker_base.py:157]     return executor(*args, **kwargs)
ERROR 04-28 15:55:45 worker_base.py:157]   File "/root/miniconda3/envs/deepseek/lib/python3.10/site-packages/vllm/worker/worker.py", line 171, in initialize_cache
ERROR 04-28 15:55:45 worker_base.py:157]     raise_if_cache_size_invalid(num_gpu_blocks,
ERROR 04-28 15:55:45 worker_base.py:157]   File "/root/miniconda3/envs/deepseek/lib/python3.10/site-packages/vllm/worker/worker.py", line 335, in raise_if_cache_size_invalid
ERROR 04-28 15:55:45 worker_base.py:157]     raise ValueError("No available memory for the cache blocks. "
ERROR 04-28 15:55:45 worker_base.py:157] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```
But use fastchat it works and leave about 30G free in total.
```
python3 -m fastchat.serve.model_worker --model-path /models/deepseek-coder-33b-instruct --num-gpus=2 --gpus=0,1 --max-gpu-memory=46GB --model-names=deepseek-coder-33b-instruct
```
I am wondering does vllm can support such inference scenario. 33b model float16 on two 48G GPU? Thanks.

**Comment by inturbidus** [comment]
I'm also trying to use DeepSeek Coder 33B, and getting the error: 
<img width="1226" alt="Screenshot 2024-04-29 at 5 38 47 PM" src="https://github.com/vllm-project/vllm/assets/905441/2a970ea7-7cf0-439c-bbbf-ce8099d1474a">

<img width="1415" alt="Screenshot 2024-04-29 at 5 38 57 PM" src="https://github.com/vllm-project/vllm/assets/905441/7b6c64a8-8b29-4b4d-a1f8-f0c9f3a6ed74">

**Comment by han508** [comment]
+1

**Comment by DavidPeleg6** [comment]
+1

**Comment by lyy-zz** [comment]
deploy qwen1.5_72b_chat on two A800 GPUs (80G) with vllm 0.4.2, also getting the error
```
CUDA_VISIBLE_DEVICES=2,3 python -m vllm.entrypoints.openai.api_server \
    --model Qwen1.5-72B-Chat \
    --dtype auto \
    --gpu-memory-utilization 0.9 \
    --tensor-parallel-size 2 \
    --enforce-eager \
```

**Comment by wangii** [comment]
same for 4xA100 setup.

**Comment by WenhaoZhang-Git** [comment]
It's for me occur when I set the gpu_memory_utilization to small rate so that the preallocation memory not enough, but actually I got the totally enough memory just not to allocate the vllm to be the k&v cache.
