### ISSUE TITLE
PIP install error

### ISSUE THREAD

**Issue by SeungjaeLim** [vllm-project/vllm#463]
I installed it on the docker image using the install method given in the documentation, but I get the following error.

```
docker run --gpus all -it --rm --shm-size=8g nvcr.io/nvidia/pytorch:22.12-py3
pip install vllm
```

At first I thought it was a PIP version issue, so I upgraded PIP and ran it again, but it was still there.

Installing in the following way also fails.

```
git clone https://github.com/vllm-project/vllm.git
cd vllm
pip install -e 
```

```
root@:/workspace# pip install vllm
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting vllm
  Downloading vllm-0.1.2.tar.gz (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.8/93.8 kB 10.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ha3un36c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-ha3un36c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ha3un36c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 47, in <module>
      RuntimeError: GPUs with compute capability less than 7.0 are not supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

```
RuntimeError: GPUs with compute capability less than 7.0 are not supported.
```
This seemed to be the problem, so I ran nvidia-smi to see capability.
```
Fri Jul 14 15:12:29 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off | 00000000:3F:00.0 Off |                    0 |
| N/A   26C    P0              31W / 250W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE-16GB           Off | 00000000:40:00.0 Off |                    0 |
| N/A   28C    P0              25W / 250W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

But then a question arose. Does the docker I pulled from have CUDA installed with 11.8, but why it says 12.2?

And for the A100 40GB, the Compute capability (version) is 8.0, can you see why we have a version issue here?

**Comment by SeungjaeLim** [comment]
```
RuntimeError: GPUs with compute capability less than 7.0 are not supported.
```
This seemed to be the problem, so I ran nvidia-smi to see capability.
```
Fri Jul 14 15:12:29 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off | 00000000:3F:00.0 Off |                    0 |
| N/A   26C    P0              31W / 250W |      4MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE-16GB           Off | 00000000:40:00.0 Off |                    0 |
| N/A   28C    P0              25W / 250W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

But then a question arose. Does the docker I pulled from have CUDA installed with 11.8, but why it says 12.2?

**Comment by WoosukKwon** [comment]
Hi @SeungjaeLim, thanks for trying out vLLM!

The error is due to these lines:
https://github.com/vllm-project/vllm/blob/dbed69058c88ddf42914e6ab3a9b6ea12e15b12a/setup.py#L46-L48

A simple workaround is to comment out these lines and build vLLM from source. That is, run the following inside your docker container:
```bash
$ pip uninstall torch
$ git clone git@github.com:vllm-project/vllm.git
$ cd vllm
$ vi setup.py # Comment out the lines above
$ pip install -e .
```

**Comment by SeungjaeLim** [comment]
Thank you! It worked.

I'm attaching my log in case anyone else has the same problem.
```
$ docker run --gpus all -it --rm --shm-size=8g nvcr.io/nvidia/pytorch:22.12-py3
$ git clone https://github.com/vllm-project/vllm.git
$ cd vllm
$ vi setup.py # Comment out the lines above
  #  if major < 7: 
  #     raise RuntimeError( 
  #         "GPUs with compute capability less than 7.0 are not supported.") 
$ pip install --upgrade pip
$ pip install -e .
```
