### ISSUE TITLE
[Bug]: CPU Docker build quickstart `static library kineto_LIBRARY-NOTFOUND not found`

### ISSUE THREAD

**Issue by danthegoodman1** [vllm-project/vllm#4654]
### Your current environment

Fresh ubuntu instance with docker CE installed

### 🐛 Describe the bug

Simply running `docker build -f Dockerfile.cpu -t vllm-cpu-env --shm-size=4g .` from https://docs.vllm.ai/en/latest/getting_started/cpu-installation.html#quick-start-using-dockerfile throws the following error.

Using a ubuntu 24.04 build on a dedicated cpu amd hetzner cloud VM.

```
3.794 CMake Warning at /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
3.794   static library kineto_LIBRARY-NOTFOUND not found.
3.794 Call Stack (most recent call first):
3.794   /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
3.794   CMakeLists.txt:67 (find_package)
3.794
3.794
3.795 -- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so
3.799 CMake Error at cmake/cpu_extension.cmake:57 (message):
3.799   vLLM CPU backend requires AVX512 ISA support.
3.799 Call Stack (most recent call first):
3.799   CMakeLists.txt:88 (include)
3.799
3.799
3.800 -- Configuring incomplete, errors occurred!
3.826 Traceback (most recent call last):
3.826   File "/workspace/vllm/setup.py", line 397, in <module>
3.827     setup(
3.827   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
3.827     return distutils.core.setup(**attrs)
3.827   File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
3.827     dist.run_commands()
3.827   File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
3.827     self.run_command(cmd)
3.827   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
3.827     cmd_obj.run()
3.827   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 74, in run
3.827     self.do_egg_install()
3.827   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 116, in do_egg_install
3.827     self.run_command('bdist_egg')
3.827   File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
3.827     self.distribution.run_command(command)
3.827   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
3.828     cmd_obj.run()
3.828   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
3.828     cmd = self.call_command('install_lib', warn_dir=0)
3.828   File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
3.828     self.run_command(cmdname)
3.828   File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
3.828     self.distribution.run_command(command)
3.828   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
3.828     cmd_obj.run()
3.828   File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
3.828     self.build()
3.828   File "/usr/lib/python3.10/distutils/command/install_lib.py", line 109, in build
3.828     self.run_command('build_ext')
3.828   File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
3.828     self.distribution.run_command(command)
3.828   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
3.828     cmd_obj.run()
3.828   File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
3.829     _build_ext.run(self)
3.829   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
3.829     self.build_extensions()
3.829   File "/workspace/vllm/setup.py", line 192, in build_extensions
3.829     self.configure(ext)
3.829   File "/workspace/vllm/setup.py", line 175, in configure
3.829     subprocess.check_call(
3.829   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
3.829     raise CalledProcessError(retcode, cmd)
3.829 subprocess.CalledProcessError: Command '['cmake', '/workspace/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/workspace/vllm/build/lib.linux-x86_64-3.10/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=build/temp.linux-x86_64-3.10', '-DVLLM_TARGET_DEVICE=cpu', '-DVLLM_PYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=32']' returned non-zero exit status 1.
------
Dockerfile.cpu:18
--------------------
  16 |     RUN pip install -v -r requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu
  17 |
  18 | >>> RUN VLLM_TARGET_DEVICE=cpu python3 setup.py install
  19 |
  20 |     CMD ["/bin/bash"]
--------------------
ERROR: failed to solve: process "/bin/sh -c VLLM_TARGET_DEVICE=cpu python3 setup.py install" did not complete successfully: exit code: 1
```

**Comment by danthegoodman1** [comment]
nvm, see `vLLM CPU backend requires AVX512 ISA support`
