### ISSUE TITLE
[Feature]: Support kv-cache-dtype fp8 without nvcc

### ISSUE THREAD

**Issue by samos123** [vllm-project/vllm#4666]
### 🚀 The feature, motivation and pitch

Currently the following error is thrown if nvcc is not installed:
```
WARNING 05-08 01:34:59 utils.py:313] Not found nvcc in /usr/local/cuda. Skip cuda version check!
Traceback (most recent call last):                                                                              
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,                                                                  
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)                                                                                     
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 159, in <module>
    engine = AsyncLLMEngine.from_engine_args(                                                                   
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 341, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 471, in create_engine_config
    cache_config = CacheConfig(self.block_size,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 310, in __init__
    self._verify_cache_dtype()
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 333, in _verify_cache_dtype
    if nvcc_cuda_version < Version("11.8"):
TypeError: '<' not supported between instances of 'NoneType' and 'Version'
```

However, we should be able to do a version check without depending on nvcc. So let's remove this dependency.

**Comment by samos123** [comment]
I can make the PR if this would be accepted

**Comment by youkaichao** [comment]
Is it this one? https://github.com/vllm-project/vllm/pull/4173

**Comment by samos123** [comment]
I guess reverting that PR might be all that's needed. That PR seems to be the reason why nvcc dependency was introduced.

**Comment by samos123** [comment]
So I think the PR almost fixes this. However, the version check is still done and relies on nvcc is my understanding? So you can't use fp8 unless you install nvcc even with that PR.
