### ISSUE TITLE
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'max_tokens must be at least 1, got -186.', 'type': 'BadRequestError', 'param': None, 'code': 400}

### ISSUE THREAD

**Issue by Mrdragonyuan** [vllm-project/vllm#4667]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.8/dist-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.8/dist-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
  File "api_server.py", line 99, in stream
    chat_response = client.chat.completions.create(
  File "/usr/local/lib/python3.8/dist-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 902, in request
    return self._request(
  File "/usr/local/lib/python3.8/dist-packages/openai/_base_client.py", line 993, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'max_tokens must be at least 1, got -186.', 'type': 'BadRequestError', 'param': None, 'code': 400}

**Comment by DarkLight1337** [comment]
Can you show the contents of the request that is passed to the server?

**Comment by hmellor** [comment]
- the supplied information is not actionable
- @Mrdragonyuan has not provided additional context
- the error appears to be basic user error

**Comment by DarkLight1337** [comment]
We'll re-open this issue if more information becomes available.

**Comment by chaymahamdi** [comment]
yes I have this problem , I am working with langchain structured_agent and serverless azureML chat model :  File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 606, in create
    return self._post(
  File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'max_tokens must be at least 1, got -344.', 'type': 'BadRequestError', 'param': None, 'code': 400}  : is the problem with the model !!!

**Comment by DarkLight1337** [comment]
> yes I have this problem , I am working with langchain structured_agent and serverless azureML chat model : File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 606, in create return self._post( File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)) File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request return self._request( File "/home/chaymahamdi/langchain-agent/aienv/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request raise self._make_status_error_from_response(err.response) from None openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'max_tokens must be at least 1, got -344.', 'type': 'BadRequestError', 'param': None, 'code': 400} : is the problem with the model !!!

Please open a new issue and provide more detailed information.

**Comment by amir1m** [comment]
Hi @DarkLight1337,
I am facing the same issue.

**Started vLLM server** 
`vllm serve mistralai/Mistral-Nemo-Instruct-2407 --dtype auto --api-key token-1111 --tensor-parallel-size 2 --max-model-len 86448`

**Trying to call** 
`prompt | llm.with_structured_output(Decision) `

**Error trace:**
`BadRequestError: Error code: 400 - {'object': 'error', 'message': "[{'type': 'extra_forbidden', 'loc': ('body', 'parallel_tool_calls'), 'msg': 'Extra inputs are not permitted', 'input': False}]", 'type': 'BadRequestError', 'param': None, 'code': 400}`

**Packages:**
vllm                              0.5.5
vllm-flash-attn                   2.6.1
langchain-openai                         0.2.2
langchain                                0.3.3
langchain-community                      0.3.2
langchain-core                           0.3.10

**Comment by 99RRR** [comment]
ERROR 06-11 02:07:59 [serving_chat.py:199] Error in preprocessing prompt inputs
ERROR 06-11 02:07:59 [serving_chat.py:199] Traceback (most recent call last):
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/python/vllm_project/qwen3_env/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 182, in create_chat_completion
ERROR 06-11 02:07:59 [serving_chat.py:199]     ) = await self._preprocess_chat(
ERROR 06-11 02:07:59 [serving_chat.py:199]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/python/vllm_project/qwen3_env/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_engine.py", line 834, in _preprocess_chat
ERROR 06-11 02:07:59 [serving_chat.py:199]     prompt_inputs = await self._tokenize_prompt_input_async(
ERROR 06-11 02:07:59 [serving_chat.py:199]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/.local/share/uv/python/cpython-3.11.12-linux-x86_64-gnu/lib/python3.11/concurrent/futures/thread.py", line 58, in run
ERROR 06-11 02:07:59 [serving_chat.py:199]     result = self.fn(*self.args, **self.kwargs)
ERROR 06-11 02:07:59 [serving_chat.py:199]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/python/vllm_project/qwen3_env/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_engine.py", line 589, in _tokenize_prompt_input
ERROR 06-11 02:07:59 [serving_chat.py:199]     return next(
ERROR 06-11 02:07:59 [serving_chat.py:199]            ^^^^^
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/python/vllm_project/qwen3_env/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_engine.py", line 613, in _tokenize_prompt_inputs
ERROR 06-11 02:07:59 [serving_chat.py:199]     yield self._normalize_prompt_text_to_input(
ERROR 06-11 02:07:59 [serving_chat.py:199]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/python/vllm_project/qwen3_env/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_engine.py", line 498, in _normalize_prompt_text_to_input
ERROR 06-11 02:07:59 [serving_chat.py:199]     return self._validate_input(request, input_ids, input_text)
ERROR 06-11 02:07:59 [serving_chat.py:199]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-11 02:07:59 [serving_chat.py:199]   File "/home/ubuntu/python/vllm_project/qwen3_env/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_engine.py", line 560, in _validate_input
ERROR 06-11 02:07:59 [serving_chat.py:199]     raise ValueError(
ERROR 06-11 02:07:59 [serving_chat.py:199] ValueError: This model's maximum context length is 32768 tokens. However, you requested 34396 tokens in the messages, Please reduce the length of the messages.
INFO:     10.150.1.80:51024 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

**Comment by DarkLight1337** [comment]
As mentioned in the error message, your input has too many tokens

**Comment by 99RRR** [comment]
@DarkLight1337 @I set the context length to 32k. Now this error occurs. How can we control the number of rounds for the multi-round historical conversation information?

**Comment by DarkLight1337** [comment]
You should limit the number of rounds to avoid going over 32k tokens total

**Comment by 99RRR** [comment]
Could you please tell me how to set the limit?

**Comment by DarkLight1337** [comment]
You will have to write your own code to validate this. vLLM will simply raise an error like you showed if it finds that the input has too many tokens.

**Comment by DarkLight1337** [comment]
You can use `/tokenize` endpoint to find how many tokens the input has.

**Comment by 99RRR** [comment]
I am using the server service provided by OpenAI. The startup command is:
LOG_LEVEL=WARNING \
CUDA_VISIBLE_DEVICES=0,1 \
nohup vllm serve ./Qwen3-32B-AWQ \
  --served-model-name qwen3-32b-awq \
  --tensor-parallel-size 2 \
  --max-model-len 32768 \
  --disable-log-requests &> output.log &

**Comment by 99RRR** [comment]
The number of tokens input at one time is not very large. It seems that the messages from historical conversations are all sent in together.

**Comment by DarkLight1337** [comment]
Yes, that's just how multi-round conversations work. You need to be careful that the total tokens across all the messages don't exceed the context length
