### ISSUE TITLE
Installation with CPU with errors

### ISSUE THREAD

**Issue by ming-ddtechcg** [vllm-project/vllm#4692]
### Your current environment

Following the instruction @ https://docs.vllm.ai/en/latest/getting_started/cpu-installation.html and execute the section "Quick start using Dockerfile" for:

`docker build -f Dockerfile.cpu -t vllm-cpu-env --shm-size=4g .`

and, received errors with the following logs:

```
VLLM_TARGET_DEVICE=cpu python3 setup.py install

 

running install

/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

  warnings.warn(

/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.

  warnings.warn(

running bdist_egg

running egg_info

writing vllm.egg-info/PKG-INFO

writing dependency_links to vllm.egg-info/dependency_links.txt

writing requirements to vllm.egg-info/requires.txt

writing top-level names to vllm.egg-info/top_level.txt

reading manifest file 'vllm.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

adding license file 'LICENSE'

writing manifest file 'vllm.egg-info/SOURCES.txt'

installing library code to build/bdist.linux-x86_64/egg

running install_lib

running build_py

running build_ext

-- Build type: RelWithDebInfo

-- Target device: cpu

-- Found python matching: /usr/bin/python3.

CMake Warning at /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):

  static library kineto_LIBRARY-NOTFOUND not found.

Call Stack (most recent call first):

  /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)

  CMakeLists.txt:67 (find_package)

 

 

CMake Error at cmake/cpu_extension.cmake:57 (message):

  vLLM CPU backend requires AVX512 ISA support.

Call Stack (most recent call first):

  CMakeLists.txt:88 (include)

 

 

-- Configuring incomplete, errors occurred!

Traceback (most recent call last):

  File "/workspace/vllm/setup.py", line 401, in <module>

    setup(

  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup

    return distutils.core.setup(**attrs)

  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command

    cmd_obj.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 74, in run

    self.do_egg_install()

  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 116, in do_egg_install

    self.run_command('bdist_egg')

  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command

    cmd_obj.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 164, in run

    cmd = self.call_command('install_lib', warn_dir=0)

  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command

    self.run_command(cmdname)

  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command

    cmd_obj.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run

    self.build()

  File "/usr/lib/python3.10/distutils/command/install_lib.py", line 109, in build

    self.run_command('build_ext')

  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command

    cmd_obj.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run

    _build_ext.run(self)

  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run

    self.build_extensions()

  File "/workspace/vllm/setup.py", line 192, in build_extensions

    self.configure(ext)

  File "/workspace/vllm/setup.py", line 175, in configure

    subprocess.check_call(

  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['cmake', '/workspace/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/workspace/vllm/build/lib.linux-x86_64-3.10/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=build/temp.linux-x86_64-3.10', '-DVLLM_TARGET_DEVICE=cpu', '-DVLLM_PYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=32']' returned non-zero exit status 1.
```

Is there a requirement for the host that runs the docker? 

Thanks.

**Comment by ming-ddtechcg** [comment]
Just revisited the page, I saw:

`Instruction set architecture (ISA) requirement: AVX512 is required.`

Does it mean that I have to build with the AVX512 supported CPU and run vLLM with the AVX512 supported CPU?

Thanks.

**Comment by mgiessing** [comment]
Yeah exactly - that's also what cmake tells you:

```bash
[...]
CMake Error at cmake/cpu_extension.cmake:57 (message):

  vLLM CPU backend requires AVX512 ISA support.
[...]
```

On Linux you can check e.g. using:

`lscpu | grep -i avx512` if that requirement is fulfilled
