### ISSUE TITLE
[Feature]: add local_files_only parameter

### ISSUE THREAD

**Issue by yananchen1989** [vllm-project/vllm#4859]
### 🚀 The feature, motivation and pitch

hello, wondering if it is possible to add `local_files_only ` parameter into the following code to load model only from local path.
```
from vllm import LLM, SamplingParams
llm = LLM(model= model_local_path) 
```

currently, it seems needs to get connection to huggingface.co.

> Traceback (most recent call last):
>   File "/vol/chenyanan/TravelPlanner/tools/planner/inference.py", line 150, in <module>
>     llm = LLM(model= model_local_path, enable_lora = True, max_lora_rank=64, dtype='float16')
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 112, in __init__
>     self.llm_engine = LLMEngine.from_engine_args(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 173, in from_engine_args
>     engine_configs = engine_args.create_engine_configs()
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/vllm/engine/arg_utils.py", line 382, in create_engine_configs
>     model_config = ModelConfig(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/vllm/config.py", line 120, in __init__
>     self.hf_config = get_config(self.model, trust_remote_code, revision,
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/vllm/transformers_utils/config.py", line 22, in get_config
>     config = AutoConfig.from_pretrained(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
>     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
>     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
>     resolved_config_file = cached_file(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
>     resolved_file = hf_hub_download(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
>     metadata = get_hf_file_metadata(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
>     r = _request_wrapper(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
>     response = _request_wrapper(
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 392, in _request_wrapper
>     response = get_session().request(method=method, url=url, **params)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 68, in send
>     return super().send(request, *args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/tp/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))"), '(Request ID: b0702294-d099-4acf-9c86-3fccbb4cee3e)')

**Comment by njhill** [comment]
@yananchen1989 what version are you using? Changes were made recently to not require a connection to HF hub if the model is  in the local cache. And you can prevent it from attempting to connect at all by setting `HF_HUB_OFFLINE=1`.

**Comment by yananchen1989** [comment]
@njhill  thanks. it works.
version 0.4.2
`llm = LLM(model= model_local_path, dtype='float16', HF_HUB_OFFLINE=1)`

**Comment by njhill** [comment]
@yananchen1989 actually `HF_HUB_OFFLINE=1` is an env variable, not an arg passed to the `LLM` constructor.

You should be able to remove that, it will still work because it should still fall back to local cache if it can't contact HF hub.

**Comment by calee88** [comment]
My vllm version is 0.5.0.post1, and it shows me an error when I don't use HF_HUB_OFFLINE=1. Maybe it is because I'm using a private repository. And I'm using AsyncLLMEngine, so it is another possibility that causes an error.
