### ISSUE TITLE
Baichuan model can not be run

### ISSUE THREAD

**Issue by lucasjinreal** [vllm-project/vllm#490]
Hello, the PR one merged into main are actually can not run.....

The output can not be given just thrown some value error which I don't know where caused it.

However, I have tested another Baichuan PR, it works as expected. Please fix it, otherwise would cause many users confused.

**Comment by lucasjinreal** [comment]
@zhuohan123 that's weird, on my side, when a request come, the output is just a bounch of Tensor print (which I thought it was caused by a exception throw)
I can not see the orignal error since it was tooo long. 

![image](https://github.com/vllm-project/vllm/assets/21303438/7c2d2c9e-f9e9-43bb-9475-7561a7b86363)


its that could possible for multi gpu com problem? Since i found this pr implement using Parellral Linear

**Comment by lucasjinreal** [comment]
Here was the previous error:


```
baichuan.py", line 138, in forward
    attn_output = self.attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/m/vllm/vllm/model_executor/layers/attention.py", line 328, in forward
    return super().forward(
  File "/m/vllm/vllm/model_executor/layers/attention.py", line 223, in forward
    self.single_query_cached_kv_attention(
  File "/mn/deploy/vllm/vllm/model_executor/layers/attention.py", line 135, in single_query_cached_kv_attention
    attention_ops.single_query_cached_kv_attention(
TypeError: single_query_cached_kv_attention(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: float, arg5: torch.Tensor, arg6: torch.Tensor, arg7: int, arg8: int, arg9: Optional[torch.Tensor]) -> None

Invoked with: tensor([[[-1.4512, -0.1887,  0.8198,  ..., -0.5977,  0.0824, -1.0752],
         [ 0.6411,  0.7500,  0.6460,  ...,  1.6650, -0.6650,  1.1973],
         [-0.6343,  1.5195,  0.9277,  ..., -1.3799, -0.4526,  0.1371],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],
```

Do u know why? I didn't change anything in attention behavior

**Comment by lucasjinreal** [comment]
I think I know why!

**Comment by lucasjinreal** [comment]
@zhuohan123  turns out I have to rebuild cpp files after upgraded. 

BTW, may I consult how to get input seq_len in vllm, since I wanna get the seq_len and recache rope sincos values.

For detail：

```
def forward(
        self,
        positions: torch.Tensor,
        hidden_states: torch.Tensor,
        kv_cache: KVCache,
        input_metadata: InputMetadata,
        cache_event: Optional[torch.cuda.Event],
    ) -> torch.Tensor:
        qkv, _ = self.W_pack(hidden_states)
        q, k, v = qkv.chunk(chunks=3, dim=-1)
        k_cache, v_cache = kv_cache
# How to get seq_len here?
        attn_output = self.attn(
            positions, q, k, v, k_cache, v_cache, input_metadata, cache_event, seq_len=512
        )
        output, _ = self.o_proj(attn_output)
        return output
```

How to get seq_len at Atten layer. (I printed shapes of each tensor but can really know how to according them to torch side), Can u help?

**Comment by nuigdpgf** [comment]
How to support the Bai Chuan 13B-Chat model?

**Comment by zacharyblank** [comment]
@lucasjinreal I'm facing the same TypeError issue. What did you do to fix it? You mentioned rebuilding. I completely nuked the source, pulled from github and rebuilt and got the same error.

Thanks

**Comment by gesanqiu** [comment]
> How to support the Bai Chuan 13B-Chat model?

I think baichuan-13b and baichuan-7b are only different in PE, 13b use ALiBi PE and 7b use RoPE, all supported by vLLM, you can replace the `PagedAttentionWithRoPE` to `PagedAttentionWithALiBi` and it should work fine.

**Comment by gesanqiu** [comment]
Did you do a throughput of baichun-7b? I found it much slower than other 7b models.

**Comment by gesanqiu** [comment]
@zhuohan123 I execute `python examples/llm_engine_example.py --model baichuan-inc/Baichuan-7B --trust-remote-code` and it works fine.
But when I execute `CUDA_VISIBLE_DEVICES=4 python /workdir/vllm/vllm/entrypoints/openai/api_server.py --model baichuan-inc/Baichuan-7B --served-model-name baichuan --trust-remote-code`, 

```
(vllm) root@k8s-node-master-38:/workdir# CUDA_VISIBLE_DEVICES=4 python /workdir/vllm/vllm/entrypoints/openai/api_server.py --model baichuan-inc/Baichuan-7B --port 8012 --host 10.0.76.38 --served-model-name baichuan --trust-remote-code
INFO 07-19 02:29:17 llm_engine.py:60] Initializing an LLM engine with config: model='baichuan-inc/Baichuan-7B', tokenizer='baichuan-inc/Baichuan-7B', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
WARNING 07-19 02:29:18 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 07-19 02:29:31 llm_engine.py:134] # GPU blocks: 915, # CPU blocks: 512
<class 'bool'> False
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /workdir/vllm/vllm/transformers_utils/tokenizer.py:36 in get_tokenizer                           │
│                                                                                                  │
│    33 │   │   │   "tokenizer.")                                                                  │
│    34 │   try:                                                                                   │
│    35 │   │   print(type(trust_remote_code), trust_remote_code)                                  │
│ ❱  36 │   │   tokenizer = AutoTokenizer.from_pretrained(                                         │
│    37 │   │   │   tokenizer_name,                                                                │
│    38 │   │   │   *args,                                                                         │
│    39 │   │   │   trust_remote_code=trust_remote_code,                                           │
│                                                                                                  │
│ /root/anaconda3/envs/vllm/lib/python3.10/site-packages/transformers/models/auto/tokenization_aut │
│ o.py:669 in from_pretrained                                                                      │
│                                                                                                  │
│   666 │   │   │   tokenizer_class = None                                                         │
│   667 │   │   │   if tokenizer_auto_map is not None:                                             │
│   668 │   │   │   │   if not trust_remote_code:                                                  │
│ ❱ 669 │   │   │   │   │   raise ValueError(                                                      │
│   670 │   │   │   │   │   │   f"Loading {pretrained_model_name_or_path} requires you to execut   │
│   671 │   │   │   │   │   │   " repo on your local machine. Make sure you have read the code t   │
│   672 │   │   │   │   │   │   " then set the option `trust_remote_code=True` to remove this er   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Loading baichuan-inc/Baichuan-7B requires you to execute the tokenizer file in that repo on your local machine. Make sure you have read
the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /workdir/vllm/vllm/entrypoints/openai/api_server.py:587 in <module>                              │
│                                                                                                  │
│   584 │   engine_model_config = asyncio.run(engine.get_model_config())                           │
│   585 │                                                                                          │
│   586 │   # A separate tokenizer to map token IDs to strings.                                    │
│ ❱ 587 │   tokenizer = get_tokenizer(engine_args.tokenizer,                                       │
│   588 │   │   │   │   │   │   │     tokenizer_mode=engine_args.tokenizer_mode)                   │
│   589 │                                                                                          │
│   590 │   uvicorn.run(app,                                                                       │
│                                                                                                  │
│ /workdir/vllm/vllm/transformers_utils/tokenizer.py:59 in get_tokenizer                           │
│                                                                                                  │
│    56 │   │   │   │   "tokenizer not yet available in the HuggingFace transformers "             │
│    57 │   │   │   │   "library, consider setting `trust_remote_code=True` in LLM "               │
│    58 │   │   │   │   "or using the `--trust-remote-code` flag in the CLI.")                     │
│ ❱  59 │   │   │   raise RuntimeError(err_msg) from e                                             │
│    60 │   │   else:                                                                              │
│    61 │   │   │   raise e                                                                        │
│    62                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Failed to load the tokenizer. If the tokenizer is a custom tokenizer not yet available in the HuggingFace transformers library,
consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.
```
Log shows that ` --trust-remote-code` did set to True, but `AutoTokenizer.from_pretrained` didn't work well, and if I set the `truse_remote-code` parameter to True manually, it works fine. It's weird.

**Comment by o0fatigue** [comment]
> > How to support the Bai Chuan 13B-Chat model?
> 
> I think baichuan-13b and baichuan-7b are only different in PE, 13b use ALiBi PE and 7b use RoPE, both supported by vLLM already. You can replace the `PagedAttentionWithRoPE` to `PagedAttentionWithALiBi` and it should work fine.

Thank you for the hint, but how should I specify the `slopes` argument if I replace `PagedAttentionWithRoPE` to `PagedAttentionWithALiBi`?

**Comment by gesanqiu** [comment]
> 

@o0fatigue Hope this help you.(#512).

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
