### ISSUE TITLE
MPT-7B Generatae does not work in distributed mode

### ISSUE THREAD

**Issue by KeshavUnnikrishnanTR** [vllm-project/vllm#515]
I tried to inference it the same way the opt-13b example is inferenced, except that my MPT-7b is stored in the local:
```
from vllm import LLM
import time

llm = LLM(model="/root/mpt-7b", tensor_parallel_size=4, trust_remote_code=True) 
outputs = llm.generate("San Franciso is a") 
```
But got this error:
```
RayTaskError(TypeError)                   Traceback (most recent call last)
Cell In[5], line 2
      1 a = time.time()
----> 2 outputs = llm.generate("San Franciso is a") 
      3 print(outputs)
      4 b = time.time()

File /opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py:130, in LLM.generate(self, prompts, sampling_params, prompt_token_ids, use_tqdm)
    128         token_ids = prompt_token_ids[i]
    129     self._add_request(prompt, sampling_params, token_ids)
--> 130 return self._run_engine(use_tqdm)

File /opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py:150, in LLM._run_engine(self, use_tqdm)
    148 outputs: List[RequestOutput] = []
    149 while self.llm_engine.has_unfinished_requests():
--> 150     step_outputs = self.llm_engine.step()
    151     for output in step_outputs:
    152         if output.finished:

File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:245, in LLMEngine.step(self)
    242     return []
    244 # Execute the model.
--> 245 output = self._run_workers(
    246     "execute_model",
    247     seq_group_metadata_list=seq_group_metadata_list,
    248     blocks_to_swap_in=scheduler_outputs.blocks_to_swap_in,
    249     blocks_to_swap_out=scheduler_outputs.blocks_to_swap_out,
    250     blocks_to_copy=scheduler_outputs.blocks_to_copy,
    251 )
    252 # Update the scheduler with the model outputs.
    253 seq_groups = self.scheduler.update(output)

File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:337, in LLMEngine._run_workers(self, method, get_all_outputs, *args, **kwargs)
    334     all_outputs.append(output)
    336 if self.parallel_config.worker_use_ray:
--> 337     all_outputs = ray.get(all_outputs)
    339 if get_all_outputs:
    340     return all_outputs

File /opt/conda/lib/python3.10/site-packages/ray/_private/auto_init_hook.py:18, in wrap_auto_init.<locals>.auto_init_wrapper(*args, **kwargs)
     15 @wraps(fn)
     16 def auto_init_wrapper(*args, **kwargs):
     17     auto_init_ray()
---> 18     return fn(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/ray/_private/client_mode_hook.py:103, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    101     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    102         return getattr(ray, func.__name__)(*args, **kwargs)
--> 103 return func(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/ray/_private/worker.py:2540, in get(object_refs, timeout)
   2538     worker.core_worker.dump_object_store_memory_usage()
   2539 if isinstance(value, RayTaskError):
-> 2540     raise value.as_instanceof_cause()
   2541 else:
   2542     raise value

RayTaskError(TypeError): ray::Worker.execute_model() (pid=6072, ip=169.255.254.1, actor_id=02cc5f1f9ce05b96550a11dd01000000, repr=<vllm.worker.worker.Worker object at 0x7f6ed1a135e0>)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py", line 284, in execute_model
    output = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/mpt.py", line 234, in forward
    hidden_states = self.transformer(input_ids, positions, kv_caches,
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/mpt.py", line 202, in forward
    hidden_states = block(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/mpt.py", line 153, in forward
    x = self.attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/mpt.py", line 102, in forward
    attn_output = self.attn(q, k, v, k_cache, v_cache, input_metadata,
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 223, in forward
    self.single_query_cached_kv_attention(
  File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 406, in single_query_cached_kv_attention
    attention_ops.single_query_cached_kv_attention(
TypeError: single_query_cached_kv_attention(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: torch.Tensor, arg5: float, arg6: torch.Tensor, arg7: torch.Tensor, arg8: int, arg9: int, arg10: Optional[torch.Tensor]) -> None

Invoked with: tensor([[[ 9.1136e+04,  2.7
```

Edit:
I had made changes to the code as mentioned [https://github.com/vllm-project/vllm/issues/406#issuecomment-1629487002](here)

**Comment by ericzhou571** [comment]
I faced the same problem yesterday, I notice community made a hotfix ten hours ago.
use their latest hotfixhttps://github.com/vllm-project/vllm/commit/bda41c70ddb124134935a90a0d51304d2ac035e8, just pull from main branch.

However, after fix single kv cache attention, the code do run, but output is not correct. I think something still wrong in loading weight or tensor parallelism.

**Comment by ericzhou571** [comment]
If you can solve incorrect output, pls @me, I'm suffering garbage output for nearly 5 fours without any idea how to fix it

**Comment by zhuohan123** [comment]
@KeshavUnnikrishnanTR @ericzhou571 This is what I get from running on 2 GPUs:
```
>>> llm = LLM(model="mosaicml/mpt-7b", tensor_parallel_size=2, trust_remote_code=True)
2023-07-19 18:05:12,919 INFO worker.py:1636 -- Started a local Ray instance.
INFO 07-19 18:05:18 llm_engine.py:60] Initializing an LLM engine with config: model='mosaicml/mpt-7b', tokenizer='mosaicml/mpt-7b', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.bfloat16, use_dummy_weights=False, download_dir='/dnn/zhen/hf_cache', use_np_weights=False, tensor_parallel_size=2, seed=0)
INFO 07-19 18:06:39 llm_engine.py:134] # GPU blocks: 9143, # CPU blocks: 1024
>>> llm.generate("San Franciso is a")
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
[RequestOutput(request_id=0, prompt='San Franciso is a', prompt_token_ids=[19346, 7980, 80, 310, 247], outputs=[CompletionOutput(index=0, text=' legend for street art. A historic city in West coast, with history, as', token_ids=[13691, 323, 6406, 1445, 15, 329, 14464, 2846, 275, 4255, 8852, 13, 342, 2892, 13, 347], cumulative_logprob=-63.66405236721039, logprobs={}, finish_reason=length)], finished=True)]
```

Can you double check your model checkpoint, tokenizer, and maybe try to re-install vllm?

**Comment by KeshavUnnikrishnanTR** [comment]
Hey @zhuohan123  the latest version worked fine. But as @ericzhou571 mentioned the output does seem a bit like garbage.

![image](https://github.com/vllm-project/vllm/assets/92776453/33d52c01-90f2-4767-9b13-b7a5b0d0dc6e)

This output I got for MPT-30b:
![image](https://github.com/vllm-project/vllm/assets/92776453/0082f886-71a5-4ca4-bd59-409d4e1ac615)

**Comment by Sanster** [comment]
@ericzhou571 Did you get correct output from MPT-7B in distributed mode? I am facing the same problem with biachuan-7b model.

Normal output using 1 gpu
<img width="1651" alt="image" src="https://github.com/vllm-project/vllm/assets/3998421/083575e2-58d3-49d7-a581-bc1d1f1810d2">


Garbage output using `tensor_parallel_size=2`

<img width="1655" alt="image" src="https://github.com/vllm-project/vllm/assets/3998421/97c86cfd-98df-463b-ae0e-a4918ee6e642">

BTW: MPT-7b in distrubuted mode works fine in my environment

**Comment by hmellor** [comment]
Closing as stale.
