### ISSUE TITLE
datatype overflow

### ISSUE THREAD

**Issue by zacharyblank** [vllm-project/vllm#521]
When setting num-batched-tokens > 8k (I am working with a 12k model) it seems like there is a datatype overflow in the attention layer. Here is the error I receive:

```
Traceback (most recent call last):
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/paperspace/code/vllm/vllm/entrypoints/openai/api_server.py", line 484, in create_completion
    async for res in result_generator:
  File "/home/paperspace/code/vllm/vllm/engine/async_llm_engine.py", line 151, in generate
    raise e
  File "/home/paperspace/code/vllm/vllm/engine/async_llm_engine.py", line 148, in generate
    await self.engine_step(request_id)
  File "/home/paperspace/code/vllm/vllm/engine/async_llm_engine.py", line 74, in engine_step
    request_outputs = self.engine.step()
  File "/home/paperspace/code/vllm/vllm/engine/llm_engine.py", line 245, in step
    output = self._run_workers(
  File "/home/paperspace/code/vllm/vllm/engine/llm_engine.py", line 333, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/paperspace/code/vllm/vllm/worker/worker.py", line 284, in execute_model
    output = self.model(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/paperspace/code/vllm/vllm/model_executor/models/mpt.py", line 234, in forward
    hidden_states = self.transformer(input_ids, positions, kv_caches,
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/paperspace/code/vllm/vllm/model_executor/models/mpt.py", line 202, in forward
    hidden_states = block(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/paperspace/code/vllm/vllm/model_executor/models/mpt.py", line 153, in forward
    x = self.attn(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/paperspace/code/vllm/vllm/model_executor/models/mpt.py", line 102, in forward
    attn_output = self.attn(q, k, v, k_cache, v_cache, input_metadata,
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/paperspace/code/vllm/vllm/model_executor/layers/attention.py", line 191, in forward
    self.multi_query_kv_attention(
  File "/home/paperspace/code/vllm/vllm/model_executor/layers/attention.py", line 373, in multi_query_kv_attention
    out = xops.memory_efficient_attention_forward(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 213, in memory_efficient_attention_forward
    return _memory_efficient_attention_forward(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/home/paperspace/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: bias_4d_view.stride(0) overflows
```

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
