### ISSUE TITLE
[Installation]: Failed to build punica

### ISSUE THREAD

**Issue by asinglestep** [vllm-project/vllm#5212]
### Your current environment

```text
The output of `python collect_env.py`

Collecting environment information...
PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A
 
OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.35
 
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A800 80GB PCIe
GPU 1: NVIDIA A800 80GB PCIe
GPU 2: NVIDIA A800 80GB PCIe
GPU 3: NVIDIA A800 80GB PCIe
 
Nvidia driver version: 515.65.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```

### How you are installing vllm

```sh
python3 setup.py bdist_wheel --dist-dir=dist
```

 ```
FAILED: /workspace/build/lib.linux-x86_64-3.10/vllm/_punica_C.cpython-310-x86_64-linux-gnu.so
: && /usr/bin/c++ -fPIC -O2 -g -DNDEBUG   -shared  -o /workspace/build/lib.linux-x86_64-3.10/vllm/_punica_C.cpython-310-x86_64-linux-gnu.so CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu.o CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_fp32_bf16.cu.o CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp16_fp16_fp16.cu.o CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp16_fp32_fp16.cu.o CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp32_bf16_bf16.cu.o CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp32_fp16_fp16.cu.o CMakeFiles/_punica_C.dir/csrc/punica/punica_ops.cc.o -L/usr/local/cuda/targets/x86_64-linux/lib -Wl,-rpath,/usr/local/lib/python3.10/dist-packages/torch/lib:/usr/local/cuda/lib64:  /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so  /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so  /usr/local/cuda/lib64/stubs/libcuda.so  /usr/local/cuda/lib64/libcudart.so  -Wl,--no-as-needed,"/usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so" -Wl,--as-needed  -Wl,--no-as-needed,"/usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so" -Wl,--as-needed  /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so  /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so  /usr/local/cuda/lib64/libnvToolsExt.so  /usr/local/cuda/lib64/libcufft.so  /usr/local/cuda/lib64/libcurand.so  /usr/local/cuda/lib64/libcublas.so  /usr/local/cuda/lib64/libcublasLt.so  /usr/local/cuda/lib64/libcudart.so  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl && :
/usr/bin/ld: CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_fp32_bf16.cu.o: in function `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)':
/usr/local/cuda/include/cuda/pipeline:299: multiple definition of `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)'; CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu.o:/usr/local/cuda/include/cuda/pipeline:299: first defined here
/usr/bin/ld: CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp16_fp16_fp16.cu.o: in function `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)':
/usr/local/cuda/include/cuda/pipeline:299: multiple definition of `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)'; CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu.o:/usr/local/cuda/include/cuda/pipeline:299: first defined here
/usr/bin/ld: CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp16_fp32_fp16.cu.o: in function `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)':
/usr/local/cuda/include/cuda/pipeline:299: multiple definition of `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)'; CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu.o:/usr/local/cuda/include/cuda/pipeline:299: first defined here
/usr/bin/ld: CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp32_bf16_bf16.cu.o: in function `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)':
/usr/local/cuda/include/cuda/pipeline:299: multiple definition of `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)'; CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu.o:/usr/local/cuda/include/cuda/pipeline:299: first defined here
/usr/bin/ld: CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_fp32_fp16_fp16.cu.o: in function `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)':
/usr/local/cuda/include/cuda/pipeline:299: multiple definition of `cuda::__4::pipeline<(cuda::std::__4::__detail::thread_scope)2>::__barrier_try_wait_parity(cuda::__4::barrier<(cuda::std::__4::__detail::thread_scope)2, cuda::std::__4::__empty_completion>&, bool)'; CMakeFiles/_punica_C.dir/csrc/punica/bgmv/bgmv_bf16_bf16_bf16.cu.o:/usr/local/cuda/include/cuda/pipeline:299: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/workspace/setup.py", line 382, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/workspace/setup.py", line 187, in build_extensions
    subprocess.check_call(['cmake', *build_args], cwd=self.build_temp)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', '_punica_C', '-j', '1']' returned non-zero exit status 1.
The command '/bin/sh -c python3 setup.py bdist_wheel --dist-dir=dist' returned a non-zero code: 1
```

**Comment by mgoin** [comment]
@asinglestep can you try just installing vLLM from source with the default pathway of an editable install i.e. `pip install -e .`

**Comment by thangld201** [comment]
Hi @mgoin @asinglestep, I am having the same problem. Do you have any suggestions ? Due to limited driver support, I cannot use CUDA 12.x. 

I thought about installing punica kernel from https://github.com/punica-ai/punica. But as vllm uses built-in kernel, I don't know how to integrate the external punica kernel into it.
