### ISSUE TITLE
[Bug]: prompt_logprobs=0 raises AssertionError

### ISSUE THREAD

**Issue by toslunar** [vllm-project/vllm#5213]
### Your current environment

PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
...

### 🐛 Describe the bug

With vllm==0.4.3, `prompt_logprobs=0` raises AssertionError on the shape of (pruned) logits.

```python
import vllm

llm = vllm.LLM("facebook/opt-125m")
llm.generate(["Hello, my name is"], vllm.SamplingParams(prompt_logprobs=0))
```
raises
```
Traceback (most recent call last):
  File "/home/kataoka/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_2972011/3028385135.py", line 1, in <module>
    llm.generate(["Hello, my name is"], vllm.SamplingParams(prompt_logprobs=0))
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/utils.py", line 672, in inner
    return fn(*args, **kwargs)
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 300, in generate
    outputs = self._run_engine(use_tqdm=use_tqdm)
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 552, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 772, in step
    output = self.model_executor.execute_model(
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 91, in execute_model
    output = self.driver_worker.execute_model(execute_model_req)
  File "/home/kataoka/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 272, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/home/kataoka/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 738, in execute_model
    output = self.model.sample(
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/model_executor/models/opt.py", line 323, in sample
    next_tokens = self.sampler(logits, sampling_metadata)
  File "/home/kataoka/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kataoka/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 63, in forward
    logits = _apply_min_tokens_penalty(logits, sampling_metadata)
  File "/home/kataoka/venv/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 196, in _apply_min_tokens_penalty
    assert logits_applied == logits.shape[0]
AssertionError
```

As a consequence, `logprobs=0` cannot be used with `echo=True` in OpenAI-compatible API:
```python
import requests

requests.post("http://localhost:8000/v1/completions", json=dict(
    model="facebook/opt-125m",
    prompt="Hello, my name is",
    max_tokens=10,
    logprobs=0,
    echo=True,
))
```
to `python -m vllm.entrypoints.openai.api_server --model facebook/opt-125m` tries to process
```
INFO 06-03 18:19:58 async_llm_engine.py:553] Received request cmpl-9a5c07c312af4bb2a16290754987c2a8-0: prompt: 'Hello, my name is', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=10, min_tokens=0, logprobs=0, prompt_logprobs=0, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [2, 31414, 6, 127, 766, 16], lora_request: None.
```
and causes 500 Internal Server Error from the same AssertionError.

**Comment by toslunar** [comment]
It seems #4309 caused the degradation.

`llm.generate(["Hello, my name is"], vllm.SamplingParams(prompt_logprobs=0))`
- pass: v0.4.0.post1, v0.4.1, 603ad848~
- fail: 603ad848 v0.4.2, v0.4.3
