### ISSUE TITLE
[Misc]: vllm ONLY allocate KVCache on the first device in CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by CatYing** [vllm-project/vllm#5248]
### KVCache usage

it seems like the KVCache is only allocated on the first device in CUDA_VISIBLE_DEVICES, even if using `tensor-parallel-size` > 1. Is there any plan to support full KVCache allocated in all devices?

[cache_engine.py](https://github.com/vllm-project/vllm/tree/main/vllm/worker)
```python
        # Initialize the cache. # line 56
        self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
```

**Comment by arlenkkk** [comment]
same issue, marked.

**Comment by robertgshaw2-neuralmagic** [comment]
Can you share your launch command so I can look?

There are N `Workers` which have N `CacheEngines`...

**Comment by CatYing** [comment]
sry for the late response.

Here is the vllm version used:
![image](https://github.com/vllm-project/vllm/assets/11385976/40158985-dda6-44b8-8bfc-ea6a5c1f0151)

For example, we want to deploy a certian LLM `deepseek-coder-6.7b-instruct` on 2*T4 card, which have 32GB memory total(2*16GB)

```bash
CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.api_server --model="/cm/deepseek-coder-6.7b-instruct/" --tensor-parallel-size=2 --trust-remote-code --dtype="float16"
```

vllm  returns error log
```log
INFO 06-12 08:12:23 distributed_gpu_executor.py:45] # GPU blocks: 507, # CPU blocks: 1024
ERROR 06-12 08:12:23 worker_base.py:145] Error executing method initialize_cache. This might cause deadlock in distributed execution.
ERROR 06-12 08:12:23 worker_base.py:145] Traceback (most recent call last):
ERROR 06-12 08:12:23 worker_base.py:145]   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
ERROR 06-12 08:12:23 worker_base.py:145]     return executor(*args, **kwargs)
ERROR 06-12 08:12:23 worker_base.py:145]            ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-12 08:12:23 worker_base.py:145]   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/worker/worker.py", line 172, in initialize_cache
ERROR 06-12 08:12:23 worker_base.py:145]     raise_if_cache_size_invalid(num_gpu_blocks,
ERROR 06-12 08:12:23 worker_base.py:145]   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/worker/worker.py", line 340, in raise_if_cache_size_invalid
ERROR 06-12 08:12:23 worker_base.py:145]     raise ValueError(
ERROR 06-12 08:12:23 worker_base.py:145] ValueError: The model's max seq len (65536) is larger than the maximum number of tokens that can be stored in KV cache (8112). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
```

It means that, KVCache for 2*T4 Card, there are only 8112 context length for LLM.

But, if we deploy the model on 1*V100 (32GB) card:

```bash
 CUDA_VISIBLE_DEVICES=0 python -m vllm.entrypoints.api_server --model="/cm/deepseek-coder-6.7b-instruct/" --tensor-parallel-size=1 --trust-remote-code --dtype="float16"
```


```log
INFO 06-04 09:52:20 model_runner.py:175] Loading model weights took 12.5708 GB
INFO 06-04 09:52:32 gpu_executor.py:114] # GPU blocks: 1406, # CPU blocks: 512
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/entrypoints/api_server.py", line 107, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 366, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 324, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 442, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 172, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 262, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 117, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/worker/worker.py", line 172, in initialize_cache
[rank0]:     raise_if_cache_size_invalid(num_gpu_blocks,
[rank0]:   File "/root/miniconda3/envs/vllm026/lib/python3.11/site-packages/vllm/worker/worker.py", line 340, in raise_if_cache_size_invalid
[rank0]:     raise ValueError(
[rank0]: ValueError: The model's max seq len (65536) is larger than the maximum number of tokens that can be stored in KV cache (22496). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
```

the avalible KVCache sizes are very different between 2*T4 and 1*V100, although they both have 32GB memory
