### ISSUE TITLE
[Bug]: When I call the speculative model through the vllm interface, an error is reported: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by YuCheng-Qi** [vllm-project/vllm#5272]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 9.2.1 20200522 (Alibaba 9.2.1-3 2.17)
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.30

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-13.al8.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB

Nvidia driver version: 470.161.03
cuDNN version: Probably one of the following:
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.3
/usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:              6
CPU MHz:               3500.000
CPU max MHz:           3500.0000
CPU min MHz:           800.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] atorch==1.2.1
[pip3] flake8==6.1.0
[pip3] numpy==1.23.5
[pip3] nvidia-nccl-cu12==2.18.1
[pip3] torch==2.1.2
[pip3] torchaudio==2.1.0+cu121
[pip3] torchpippy==0.1.1+cecc4fc
[pip3] torchvision==0.16.0+cu121
[pip3] transformers==4.31.0
[pip3] triton==2.1.0
[conda] atorch                    1.2.1                    pypi_0    pypi
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] torchaudio                2.1.0+cu121              pypi_0    pypi
[conda] torchpippy                0.1.1+cecc4fc            pypi_0    pypi
[conda] torchvision               0.16.0+cu121             pypi_0    pypi
[conda] transformers              4.31.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```
my code：
```python
from vllm import LLM
from vllm import LLM, SamplingParams

sampling_params = SamplingParams(temperature=1, top_p=0.95,logprobs=1)

llm = LLM(
    model="/mnt/nas/llm/faifeng-10B-Chat",
    # enable_lora=True,
    use_v2_block_manager=True,
    speculative_model="/mnt/nas/llm/faifeng-1B-Chat",
    num_speculative_tokens=5,
    tensor_parallel_size=1,
    enforce_eager=True,
    # load_format='safetensors',
    enable_prefix_caching=True,
    gpu_memory_utilization=0.4,
    num_gpu_blocks_override=1000,
    swap_space=4,
    max_context_len_to_capture=512
)

print(llm.generate(prompts="Hello, my name is",sampling_params=sampling_params))
```

### 🐛 Describe the bug

The error is as follows：
Traceback (most recent call last):
  File "/ossfs/workspace/ant_vllm/examples/sp_runner_example.py", line 6, in <module>
    llm = LLM(
  File "/opt/conda/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 118, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 278, in from_engine_args
    engine = cls(
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 206, in __init__
    self.scheduler = Scheduler(scheduler_config, cache_config, lora_config)
  File "/opt/conda/lib/python3.8/site-packages/vllm/core/scheduler.py", line 260, in __init__
    BlockSpaceManagerImpl = BlockSpaceManager.get_block_space_manager_class(
  File "/opt/conda/lib/python3.8/site-packages/vllm/core/interfaces.py", line 34, in get_block_space_manager_class
    from vllm.core.block_manager_v2 import BlockSpaceManagerV2
  File "/opt/conda/lib/python3.8/site-packages/vllm/core/block_manager_v2.py", line 6, in <module>
    from vllm.core.block.cpu_gpu_block_allocator import CpuGpuBlockAllocator
  File "/opt/conda/lib/python3.8/site-packages/vllm/core/block/cpu_gpu_block_allocator.py", line 6, in <module>
    from vllm.core.block.prefix_caching_block import PrefixCachingBlockAllocator
  File "/opt/conda/lib/python3.8/site-packages/vllm/core/block/prefix_caching_block.py", line 15, in <module>
    class PrefixCachingBlockAllocator(BlockAllocator):
  File "/opt/conda/lib/python3.8/site-packages/vllm/core/block/prefix_caching_block.py", line 238, in PrefixCachingBlockAllocator
    def all_block_ids(self) -> frozenset[int]:
TypeError: 'type' object is not subscriptable，Can anyone help me with this? Why is there this error?

**Comment by YuCheng-Qi** [comment]
@mgoin Yeah, making those tweaks totally fixed my issue，thanks！
