### ISSUE TITLE
[Bug]: Cannot request more than 5 logprobs

### ISSUE THREAD

**Issue by coder109** [vllm-project/vllm#5299]
### Your current environment

```text
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.31

Python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8352V CPU @ 2.10GHz
Stepping:                        6
CPU MHz:                         800.000
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4000.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        108 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] pytorch-crf==0.7.2
[pip3] sentence-transformers==2.6.1
[pip3] torch==2.3.0
[pip3] transformers==4.41.2
[pip3] triton==2.3.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              hfd86e86_1    defaults
[conda] faiss-gpu                 1.7.3           py3.8_h98e120b_0_cuda10.2    pytorch
[conda] libfaiss                  1.7.3           hdbd6f0c_0_cuda10.2    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344    defaults
[conda] mkl-service               2.4.0            py38h5eee18b_1    defaults
[conda] mkl_fft                   1.3.8            py38h5eee18b_0    defaults
[conda] mkl_random                1.2.4            py38hdb19cb5_0    defaults
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpy-base                1.24.3           py38h060ed82_1    defaults
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] pytorch-crf               0.7.2                    pypi_0    pypi
[conda] sentence-transformers     2.6.1                    pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] transformers              4.41.2                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     0-31,64-95      0               N/A
GPU1    SYS      X      SYS     SYS     0-31,64-95      0               N/A
NIC0    SYS     SYS      X      PIX
NIC1    SYS     SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
```

### 🐛 Describe the bug

In some papers, requesting more than 5 logprobs is necessary. Originally, I was using `vLLM==0.2.6` and everything is fine. However, after updating vLLM to 0.4.3,  I can't run my script due to this problem.

Is there a way to request more than 5 logprobs in `vLLM==0.4.3`?

Code to reproduce:
```python
from transformers import AutoTokenizer, AutoModelForCausalLM
from vllm import LLM, SamplingParams

# Place your Llama path here.
Llama_2_7b_path = "./Llama-2-7b-chat-hf"

if __name__ == "__main__":
    # Load Model
    model = LLM(model=Llama_2_7b_path,
                dtype="bfloat16",
                tensor_parallel_size=1)

    # Here, try to request logprobs more than 5.
    sampling_params = SamplingParams(temperature=0.0, top_p=1.0, max_tokens=1024, logprobs=5000)

    model_input = "Python is a good language, right?"
    model.generate([model_input], sampling_params)
```

Error Message:
```text
[rank0]: Traceback (most recent call last):
[rank0]:   File "bug_report.py", line 17, in <module>
[rank0]:     model.generate([model_input], sampling_params)
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/utils.py", line 672, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 294, in generate
[rank0]:     self._validate_and_add_requests(
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 518, in _validate_and_add_requests
[rank0]:     self._add_request(
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 531, in _add_request
[rank0]:     self.llm_engine.add_request(request_id,
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 550, in add_request
[rank0]:     self._add_processed_request(
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 446, in _add_processed_request
[rank0]:     seq_group = self._create_sequence_group_with_sampling(
[rank0]:   File "/root/miniconda3/envs/selfrag/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 572, in _create_sequence_group_with_sampling
[rank0]:     raise ValueError(f"Cannot request more than "
[rank0]: ValueError: Cannot request more than 5 logprobs.
```

**Comment by DarkLight1337** [comment]
You can adjust the `--max-logprobs` parameter, as described [here](https://docs.vllm.ai/en/stable/models/engine_args.html).

**Comment by coder109** [comment]
Thank you!!!

**Comment by Juanhui28** [comment]
@DarkLight1337 

Thanks for the answer! But I'm confused how to use this `--max-logprobs` parameter.  In the code from @coder109 , it uses `SamplingParams ` to set parameters. But `SamplingParams ` doesn't contain this parameter. How to set the `--max-logprobs`? Thanks!

**Comment by DarkLight1337** [comment]
`--max-logprobs` should be passed to the `LLM` class, not `SamplingParams`.

**Comment by Juanhui28** [comment]
@DarkLight1337 

Thanks for the clarification! I tried the following and it works!
`llm = LLM(model=model_id, tensor_parallel_size=8, disable_custom_all_reduce=True, max_logprobs=1000)`

**Comment by AetherPrior** [comment]
Is there a way to do this with AsyncEngine? passing it in the `**vllm_kwargs` doesn't work

**Comment by Lynnzake** [comment]
> `--max-logprobs` should be passed to the `LLM` class, not `SamplingParams`. (It in turn controls the maximum allowed `logprobs` value that can be in `SamplingParams`.)

@DarkLight1337 Hi, I've tried passing max_logprobs to the LLM class, but the output have no prompt_logprobs at all, should i pass the param to SamplingParams too?

**Comment by DarkLight1337** [comment]
Can you show your code?

**Comment by Lynnzake** [comment]
> Can you show your code?

I've figured out, just pass the num into the sampling params as well
