### ISSUE TITLE
Ray issue while running API server

### ISSUE THREAD

**Issue by sureshbhusare** [vllm-project/vllm#544]
Hi All , 

I am trying to run  
`python3 -m vllm.entrypoints.api_server     --model huggyllama/llama-13b     --tensor-parallel-size 4`

I am using local build of vllm. 

Hardware I am using . 

- A100 40GB
- Python 3.10
- Cuda 12.0

```
Traceback (most recent call last):
  File " suresh.bhusare/anaconda3/envs/vllm-test/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File " suresh.bhusare/anaconda3/envs/vllm-test/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File " suresh.bhusare/inference-llm/vllm/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File " suresh.bhusare/inference-llm/vllm/vllm/engine/async_llm_engine.py", line 7, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File " suresh.bhusare/inference-llm/vllm/vllm/engine/llm_engine.py", line 9, in <module>
    from vllm.engine.ray_utils import initialize_cluster, ray, RayWorker
  File " suresh.bhusare/inference-llm/vllm/vllm/engine/ray_utils.py", line 8, in <module>
    from ray.air.util.torch_dist import TorchDistributedWorker
  File " suresh.bhusare/anaconda3/envs/vllm-test/lib/python3.10/site-packages/ray/air/__init__.py", line 1, in <module>
    from ray.air.checkpoint import Checkpoint
  File " suresh.bhusare/anaconda3/envs/vllm-test/lib/python3.10/site-packages/ray/air/checkpoint.py", line 22, in <module>
    from ray.air._internal.remote_storage import (
  File " suresh.bhusare/anaconda3/envs/vllm-test/lib/python3.10/site-packages/ray/air/_internal/remote_storage.py", line 142, in <module>
    _cached_fs: Dict[tuple, Tuple[float, pyarrow.fs.FileSystem]] = {}
AttributeError: 'NoneType' object has no attribute 'fs'
```

Please let me know whats wrong with this.

**Comment by eschmidbauer** [comment]
running into same issue

**Comment by PawanOsman** [comment]
I fixed it by installing ray v2.5.1

```bash
pip install ray==2.5.1
```

**Comment by zhuohan123** [comment]
I believe this is a ray issue. Can you update pyarrow via `pip install -U pyarrow` and try again?

**Comment by eschmidbauer** [comment]
i tried `ray-2.5.1` and `pyarrow==12.0.1`
this is the next error
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/vllm/lib/python3.11/site-packages/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 7, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 9, in <module>
    from vllm.engine.ray_utils import initialize_cluster, ray, RayWorker
ImportError: cannot import name 'RayWorker' from 'vllm.engine.ray_utils' (/vllm/lib/python3.11/site-packages/vllm/engine/ray_utils.py)```

**Comment by ashleykleynhans** [comment]
> i tried `ray==2.5.1` and `pyarrow==12.0.1` this is the next error
> 
> ```
> Traceback (most recent call last):
>   File "<frozen runpy>", line 189, in _run_module_as_main
>   File "<frozen runpy>", line 112, in _get_module_details
>   File "/vllm/lib/python3.11/site-packages/vllm/__init__.py", line 4, in <module>
>     from vllm.engine.async_llm_engine import AsyncLLMEngine
>   File "/vllm/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 7, in <module>
>     from vllm.engine.llm_engine import LLMEngine
>   File "/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 9, in <module>
>     from vllm.engine.ray_utils import initialize_cluster, ray, RayWorker
> ImportError: cannot import name 'RayWorker' from 'vllm.engine.ray_utils' (/vllm/lib/python3.11/site-packages/vllm/engine/ray_utils.py)
> ```

I am getting this exact same error after following the same steps.

**Comment by zhuohan123** [comment]
Latest vLLM main branch and the latest ray should resolve this issue. Feel free to reopen if there are any further problems.
