### ISSUE TITLE
[Bug]: 0.5.0 AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'

### ISSUE THREAD

**Issue by WangErXiao** [vllm-project/vllm#5454]
### Your current environment

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/root/.vscode-server/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
[rank0]:     cli.main()
[rank0]:   File "/root/.vscode-server/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
[rank0]:     run()
[rank0]:   File "/root/.vscode-server/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
[rank0]:     runpy.run_path(target, run_name="__main__")
[rank0]:   File "/root/.vscode-server/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
[rank0]:     return _run_module_code(code, init_globals, run_name,
[rank0]:   File "/root/.vscode-server/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
[rank0]:     _run_code(code, mod_globals, init_globals,
[rank0]:   File "/root/.vscode-server/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/tom/vllm/vllm/entrypoints/api_server.py", line 107, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:   File "/home/tom/vllm/vllm/engine/async_llm_engine.py", line 395, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/tom/vllm/vllm/engine/async_llm_engine.py", line 349, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/engine/async_llm_engine.py", line 470, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/engine/llm_engine.py", line 236, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/tom/vllm/vllm/engine/llm_engine.py", line 313, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/home/tom/vllm/vllm/executor/gpu_executor.py", line 75, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/worker/worker.py", line 154, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/worker/model_runner.py", line 833, in profile_run
[rank0]:     self.execute_model(seqs, kv_caches)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/worker/model_runner.py", line 738, in execute_model
[rank0]:     hidden_states = model_executable(
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/model_executor/models/llama.py", line 371, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/model_executor/models/llama.py", line 288, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/model_executor/models/llama.py", line 223, in forward
[rank0]:     hidden_states = self.input_layernorm(hidden_states)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/model_executor/custom_op.py", line 13, in forward
[rank0]:     return self._forward_method(*args, **kwargs)
[rank0]:   File "/home/tom/vllm/vllm/model_executor/layers/layernorm.py", line 62, in forward_cuda
[rank0]:     ops.rms_norm(
[rank0]:   File "/home/tom/vllm/vllm/_custom_ops.py", line 132, in rms_norm
[rank0]:     torch.ops._C.rms_norm(out, input, weight, epsilon)
[rank0]:   File "/home/tom/miniconda3/envs/vllm0.5/lib/python3.10/site-packages/torch/_ops.py", line 921, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'
```

### 🐛 Describe the bug

use vllm/entrypoints/api_server.py 
args are 
        [
                "--trust-remote-code",
                "--port",
                "8080",
                "--tensor-parallel-size",
                "1",
                "--model",
                "/data/llama-7b",
            ],

**Comment by WangErXiao** [comment]
I use L40s and pip install from source: pip install -e .

**Comment by DarkLight1337** [comment]
Please see [my comment](https://github.com/vllm-project/vllm/issues/5448#issuecomment-2162728057) in #5448.

**Comment by chunniunai220ml** [comment]
> Please see [my comment](https://github.com/vllm-project/vllm/issues/5448#issuecomment-2162728057) in #5448.

i del ori vllm repo, and git clone new vllm repo to pip install -e ., still got erroe:
AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'

**Comment by DarkLight1337** [comment]
> > Please see [my comment](https://github.com/vllm-project/vllm/issues/5448#issuecomment-2162728057) in #5448.
> 
> i del ori vllm repo, and git clone new vllm repo to pip install -e ., still got erroe: AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'

Please uninstall vLLM from `pip` and reinstall it as well.

**Comment by DarylLei** [comment]
replace or add  the three files  in vllm directory :   _C.abi3.so、 _moe_C.abi3.so  、_punica_C.abi3.so。
it work for me

**Comment by mxmp210** [comment]
There's something odd on source where CPU code is still under development. The error messages are quite misleading due to this code pattern used to mark each back-end.

I had same error but it was due to missing intel openmp dependency which was added in v0.5.1 - if this happens again to anyone, look into your backend dependencies first, something is definitely missing if compiling from scratch does not work. If you're building docker image, you might have outdated build file.

**Comment by WMeng1** [comment]
> > > Please see [my comment](https://github.com/vllm-project/vllm/issues/5448#issuecomment-2162728057) in #5448.
> > 
> > 
> > i del ori vllm repo, and git clone new vllm repo to pip install -e ., still got erroe: AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'
> 
> Please uninstall vLLM from `pip` and reinstall it.

from 0.5.1 update to 0.5.2 from pip，reinstall several times and still have this issue (contains create a new environment but still failed to start)

**Comment by youkaichao** [comment]
> create a new environment but still failed to start

do you delete all the old code and directories?

**Comment by tonydhuang** [comment]
> replace or add the three files in vllm directory : _C.abi3.so、 _moe_C.abi3.so 、_punica_C.abi3.so。 it work for me

where did you get those correct files to replace in vllm folder?

**Comment by huq2** [comment]
@DarylLei Yes, I also want to know.where did you get those correct files to replace in vllm folder? Or would you please share those files with me? I am getting the same issue

**Comment by Jax-dreamus** [comment]
I downgraded from `vllm==0.5.2` to` vllm==0.5.1`, and it worked.

**Comment by huq2** [comment]
Thanks! it works for me！



---Original---
From: "Haode ***@***.***&gt;
Date: Sat, Jul 20, 2024 02:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] [Bug]: 0.5.0 AttributeError: '_OpNamespace''_C' object has no attribute 'rms_norm' (Issue #5454)




 
Run into similar issue. AttributeError: '_OpNamespace' '_C' object has no attribute 'gptq_marlin_repack'. Install from source doesnt work.
 downgrade to vllm==0.5.1 will fail shape assertion error during model load.
 downgrade to vllm==0.5.0.post1 finally works for me.

**Comment by lizaibeim** [comment]
I wanna mention that building from github repo doesn't work for me, the not working version is 0.5.4+cu

**Comment by LongxingTan** [comment]
not working version: 0.6.3.post1

**Comment by DarkLight1337** [comment]
> not working version: 0.6.3.post1

Can you run `collect_env.py` and show the output? cc @youkaichao

**Comment by LongxingTan** [comment]
@DarkLight1337 Thanks.

`Collecting environment information...
WARNING 10-27 21:59:25 _custom_ops.py:19] Failed to import from vllm._C with ImportError('/root/.conda/envs/kaggle/lib/python3.11/site-packages/vllm/_C.abi3.so: undefined symbol: cuTensorMapEncodeTiled')
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-13.al8.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:                        6
CPU MHz:                         3499.602
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5800.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.77
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.46.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.46.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.3.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    NIC0    NIC1    NIC2    NIC3    NIC4    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     NODE    PXB     32-63,96-127    1               N/A
NIC0    SYS      X      NODE    NODE    SYS     SYS
NIC1    SYS     NODE     X      NODE    SYS     SYS
NIC2    SYS     NODE    NODE     X      SYS     SYS
NIC3    NODE    SYS     SYS     SYS      X      NODE
NIC4    PXB     SYS     SYS     SYS     NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1
  NIC2: mlx5_bond_2
  NIC3: mlx5_bond_3
  NIC4: mlx5_bond_4
`

**Comment by chiahao-huang** [comment]
> replace or add the three files in vllm directory : _C.abi3.so、 _moe_C.abi3.so 、_punica_C.abi3.so。 it work for me

thx,it will be solved using your method！！！

**Comment by chiahao-huang** [comment]
> > replace or add the three files in vllm directory : _C.abi3.so、 _moe_C.abi3.so 、_punica_C.abi3.so。 it work for me
> 
> where did you get those correct files to replace in vllm folder? Or would you please share those files with me? I am getting the same issue. Thanks!

Source compilation produces these files

<img width="1836" height="115" alt="Image" src="https://github.com/user-attachments/assets/67ed099f-af44-4dd2-a4b6-cf65743c113d" />

**Comment by FrankWhh** [comment]
0.8.4 is ok，but the later version like 0.9.0、0.10.0 meet the same issue. I used by pip install vllm
