### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'trust_remote_code'

### ISSUE THREAD

**Issue by LukeLIN-web** [vllm-project/vllm#548]
I was trying to run benchmark_latency.py but failed.
```
root@99e5b0a5543d:~/share/vllm/benchmarks# python benchmark_latency.py 
Namespace(batch_size=8, input_len=32, model='facebook/opt-125m', n=1, num_iters=3, output_len=128, tensor_parallel_size=1, tokenizer=None, trust_remote_code=False, use_beam_search=False)
Traceback (most recent call last):
  File "benchmark_latency.py", line 81, in <module>
    main(args)
  File "benchmark_latency.py", line 18, in main
    llm = LLM(
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/llm.py", line 53, in __init__
    engine_args = EngineArgs(
TypeError: __init__() got an unexpected keyword argument 'trust_remote_code'
```

**Comment by biofoolgreen** [comment]
I met the same error before. Here is my solution:
- Run `pip install -e .` to reinstall vllm from source code 

Because the default version via `pip install vllm` is `0.1.2` which has not included `trust_remote_code` feature.
