### ISSUE TITLE
[Usage]: How do I get the FP8 scaling factors for KV cache?

### ISSUE THREAD

**Issue by CharlesRiggins** [vllm-project/vllm#5493]
### Your current environment

Ubuntu 22
NVIDIA GeForce RTX 4090

### How would you like to use vllm

Guys,

It's great to know that FP8 support is ready for testing in the latest version (v0.5.0). Using AutoFP8 to quantize a model is handy and fast. However, I noticed that scaling factors for the KV cache were not included in the quantized checkpoints.

The documentation (https://docs.vllm.ai/en/stable/quantization/fp8.html and https://docs.vllm.ai/en/stable/quantization/fp8_e4m3_kvcache.html) mentions that we can specify a `kv_cache_scales.json` file or have the information contained within the quantized checkpoints. However, it does not explain how to get the scaling factors for the KV cache.

My question is: Is it possible to obtain the scaling factors using AutoFP8, and if so, how?

**Comment by simon-mo** [comment]
@mgoin @comaniac can you help answer? I think the original method for kv cache scales is only for AMD code path?

**Comment by mgoin** [comment]
Hi @CharlesRiggins we don't have a good flow yet for obtaining scaling factors in checkpoints with AutoFP8. We are working on proper support for these scales in compressed-tensors now, but if you have a need for it in AutoFP8 I could try to get something done quickly.

**Comment by comaniac** [comment]
Yeah although fp8 kv-cache is already supported, it hasn't been enabled automatically. This is mainly because we need an attention kernel with fp8 supported to remove dequantize overhead, and now only the paged attention kernel has this support.

If memory is sufficient, I'd suggest use fp8 checkpoint without fp8 kv-cache at this moment, as the performance gain of fp8 kv-cache could be marginal.

**Comment by CharlesRiggins** [comment]
Thank you guys for your replies.

@mgoin It would be great if you could add this feature to AutoFP8. This would allow us to get scaling factors for both the model weights and the KV cache in a single step.

@comaniac We are interested in using the FP8 KV cache primarily for its memory efficiency. It doubles the number of KV cache tokens.
I noticed that it falls to the paged attention backend if FP8 KV cache is enabled. However, I ran into an error that seemed like a bug:
AssertionError('Both operands must be of the same type. First operand (fp16) and second operand (uint8)')

**Comment by comaniac** [comment]
Yeah this looks like a bug. I'll take a look. Meanwhile, do you have a more detail traceback?

**Comment by CharlesRiggins** [comment]
Sure. Here is the log:
```
INFO 06-16 21:05:01 config.py:400] Using fp8 data type to store kv cache. It reduces the GPU memory footprint and boosts the performance. Meanwhile, it may cause accuracy drop without a proper scaling factor
INFO 06-16 21:05:01 config.py:707] Chunked prefill is enabled (EXPERIMENTAL).
INFO 06-16 21:05:01 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='/mnt/public/AiInfra/Llama-2-7b-hf-autofp8-static/', speculative_config=None, tokenizer='/mnt/public/AiInfra/Llama-2-7b-hf-autofp8-static/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=False, kv_cache_dtype=fp8, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/mnt/public/AiInfra/Llama-2-7b-hf-autofp8-static/)
INFO 06-16 21:05:06 selector.py:141] Cannot use FlashAttention-2 backend for FP8 KV cache.
INFO 06-16 21:05:06 selector.py:51] Using XFormers backend.
WARNING 06-16 21:05:07 fp8.py:48] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
INFO 06-16 21:05:07 selector.py:141] Cannot use FlashAttention-2 backend for FP8 KV cache.
INFO 06-16 21:05:07 selector.py:51] Using XFormers backend.
WARNING 06-16 21:05:08 utils.py:465] Using KV cache scaling factor 1.0 for fp8_e4m3. This may cause accuracy issues. Please make sure kv-cache scaling factor is available in the fp8 checkpoint.
INFO 06-16 21:05:08 model_runner.py:160] Loading model weights took 6.5524 GB
INFO 06-16 21:05:09 gpu_executor.py:83] # GPU blocks: 3677, # CPU blocks: 1024
INFO 06-16 21:05:10 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-16 21:05:10 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-16 21:05:23 model_runner.py:965] Graph capturing finished in 13 secs.
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1222, in ast_to_ttir
[rank0]:     generator.visit(fn.parse())
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 303, in visit_Module
[rank0]:     ast.NodeVisitor.generic_visit(self, node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 426, in generic_visit
[rank0]:     self.visit(item)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 376, in visit_FunctionDef
[rank0]:     self.visit_compound_statement(node.body)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 298, in visit_compound_statement
[rank0]:     ret_type = self.visit(stmt)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 885, in visit_For
[rank0]:     self.visit_compound_statement(node.body)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 298, in visit_compound_statement
[rank0]:     ret_type = self.visit(stmt)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 448, in visit_AugAssign
[rank0]:     self.visit(assign)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 428, in visit_Assign
[rank0]:     values = self.visit(node.value)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 477, in visit_BinOp
[rank0]:     rhs = self.visit(node.right)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1105, in visit
[rank0]:     ret = super().visit(node)
[rank0]:   File "/usr/lib/python3.10/ast.py", line 418, in visit
[rank0]:     return visitor(node)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1027, in visit_Call
[rank0]:     return fn(*args, **extra_kwargs, **kws)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/language/core.py", line 27, in wrapper
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/language/core.py", line 1018, in dot
[rank0]:     return semantic.dot(input, other, acc, allow_tf32, max_num_imprecise_acc, out_dtype, _builder)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/language/semantic.py", line 1207, in dot
[rank0]:     assert_dtypes_valid(lhs.dtype, rhs.dtype, builder.options)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/language/semantic.py", line 1190, in assert_dtypes_valid
[rank0]:     assert lhs_dtype == rhs_dtype, f"Both operands must be same type. First operand ({lhs_dtype}) and second operand ({rhs_dtype})"
[rank0]: AssertionError: Both operands must be same type. First operand (fp16) and second operand (uint8)

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/foo.py", line 11, in <module>
[rank0]:     result = model.generate(p)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/utils.py", line 691, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 304, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 556, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 776, in step
[rank0]:     output = self.model_executor.execute_model(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 91, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 280, in execute_model
[rank0]:     output = self.model_runner.execute_model(seq_group_metadata_list,
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 749, in execute_model
[rank0]:     hidden_states = model_executable(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 371, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 288, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 227, in forward
[rank0]:     hidden_states = self.self_attn(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 161, in forward
[rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/attention/layer.py", line 89, in forward
[rank0]:     return self.impl.forward(query, key, value, kv_cache, attn_metadata,
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/attention/backends/xformers.py", line 305, in forward
[rank0]:     out = PagedAttention.forward_prefix(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/attention/ops/paged_attn.py", line 200, in forward_prefix
[rank0]:     context_attention_fwd(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/vllm/attention/ops/prefix_prefill.py", line 757, in context_attention_fwd
[rank0]:     _fwd_kernel[grid](
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/runtime/jit.py", line 167, in <lambda>
[rank0]:     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/runtime/jit.py", line 416, in run
[rank0]:     self.cache[device][key] = compile(
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/compiler.py", line 191, in compile
[rank0]:     module = src.make_ir(options)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/compiler.py", line 117, in make_ir
[rank0]:     return ast_to_ttir(self.fn, self, options=options)
[rank0]:   File "/root/my_vllm/.venv/lib/python3.10/site-packages/triton/compiler/code_generator.py", line 1231, in ast_to_ttir
[rank0]:     raise CompilationError(fn.src, node, repr(e)) from e
[rank0]: triton.compiler.errors.CompilationError: at 114:24:        off_v = (
[rank0]:             bn[:, None] * stride_v_cache_bs +
[rank0]:             cur_kv_head * stride_v_cache_h +
[rank0]:             offs_d[None, :] * stride_v_cache_d +
[rank0]:             (start_n + offs_n[:, None]) % block_size * stride_v_cache_bl)
[rank0]:         k = tl.load(K_cache + off_k,
[rank0]:                     mask=dim_mask[:, None] &
[rank0]:                     ((start_n + offs_n[None, :]) < cur_batch_ctx_len),
[rank0]:                     other=0.0)  # [D,N]

[rank0]:         qk = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)  # [M,N]
[rank0]:         qk += tl.dot(q, k)
[rank0]:                         ^
[rank0]: AssertionError('Both operands must be same type. First operand (fp16) and second operand (uint8)')
```


Here is a script to reproduce the error:
```
from vllm import LLM

if __name__ == '__main__':
    model_path = "/mnt/public/AiInfra/Llama-2-7b-hf-autofp8-static/"
    model = LLM(
        model_path,
        enable_chunked_prefill=True,
        kv_cache_dtype="fp8",
    )
    p = "hi, how are you doing?"
    result = model.generate(p)`
```

**Comment by comaniac** [comment]
I see. It's because of the prefix caching. You can disable prefix caching and verify whether it's the case. The detail reason:

1. Prefix caching needs to use an "append" attention kernel in prefill. vLLM has 2 append kernels: flash attention and triton. We now use flash attention by default for better performance.
2. However, flash attention doesn't support fp8 kv-cache, so when enabling fp8 kv-cache, xformers/paged attention backend is used. This backend can only use the triton append kernel.
3. The triton append kernel doesn't support fp8 kv-cache. That's why you see the error.

We can make fp8 kv-cache work with triton kernel, but the performance won't be satisfying. Our plan is to integrate another high efficient FlashInfer append kernel (which already supports fp8). I could still fix the triton kernel when I got a chance, but it won't be my first priority.

**Comment by CharlesRiggins** [comment]
Thanks for explaining it, Cody.

I didn't specify the prefix caching option, so it was disabled by default. However, I guess the error is related to chunked prefill. If I turn off chunked prefiil, the error disappears.

**Comment by comaniac** [comment]
Ah sorry for misreading, but yeah the above also applies to chunked prefill.

**Comment by CharlesRiggins** [comment]
OK, I see. Thank you for answering.

**Comment by fzyzcjy** [comment]
Hi, is there any updates how to provide kv cache scales? Thanks!

**Comment by aviallon** [comment]
For those who stumbled here using Google: https://docs.vllm.ai/en/stable/features/quantization/quantized_kvcache/?h=#2-random-token-calibration-kv_cache_dtypefp8-calculate_kv_scalestrue

**Comment by mahabubmaraj** [comment]
> For those who stumbled here using Google: https://docs.vllm.ai/en/stable/features/quantization/quantized_kvcache/?h=#2-random-token-calibration-kv_cache_dtypefp8-calculate_kv_scalestrue

I don't know if it'd help but thank you regardless kind gentleman
