### ISSUE TITLE
[Usage]: how to use enable-chunked-prefill?

### ISSUE THREAD

**Issue by chenchunhui97** [vllm-project/vllm#5533]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to know more about `--enable-chunked-prefill`. and the constriant between args `max-num-seqs`, `max-num-batched-tokens` and `max-model-len`. can I use `--enable-chunked-prefill` and `--enable-prefix-caching` at the same time?

I tried to use chunked-prefill based on vllm-0.4.0, but got following error.
```
ERROR:    Exception in ASGI application

 Traceback (most recent call last):

   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 264, in __call__

     await wrap(partial(self.listen_for_disconnect, receive))

   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 260, in wrap

     await func()

   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 237, in listen_for_disconnect

     message = await receive()

   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 568, in receive

     await self.message_event.wait()

   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait

     await fut

 asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fbb404e2b30

 

 During handling of the above exception, another exception occurred:

 

 Traceback (most recent call last):

   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi

     result = await app(  # type: ignore[func-returns-value]

   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__

     return await self.app(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__

     await super().__call__(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__

     await self.middleware_stack(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__

     raise exc

   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__

     await self.app(scope, receive, _send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__

     await self.app(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__

     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app

     raise exc

   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app

     await app(scope, receive, sender)

   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 758, in __call__

     await self.middleware_stack(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 778, in app

     await route.handle(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 299, in handle

     await self.app(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 79, in app

     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app

     raise exc

   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app

     await app(scope, receive, sender)

   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app

     await response(scope, receive, send)

   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 257, in __call__

     async with anyio.create_task_group() as task_group:

   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__

     raise BaseExceptionGroup(

 exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
```

**Comment by CharlesRiggins** [comment]
Chunked prefill is ready starting from version v0.4.2. You can upgrade to the latest version and try again.

**Comment by simon-mo** [comment]
cc @rkooo567

**Comment by rkooo567** [comment]
As @CharlesRiggins the feature is supported from 0.4.2. But I recommend you to use 0.5.0

> I want to know more about --enable-chunked-prefill. and the constriant between args max-num-seqs, max-num-batched-tokens and max-model-len. 

No constraint. I recommend you to use --max-num-batched-tokens, not --max-num-seqs when using chunked prefill though. I think it is easier to control the performance with --max-num-batched-tokens.

--max-model-len is unrelated to chunked prefill imo. 

> can I use --enable-chunked-prefill and --enable-prefix-caching at the same time?

It is not supported yet. There's an open issue. We should support it soon.

**Comment by George-ao** [comment]
> As @CharlesRiggins the feature is supported from 0.4.2. But I recommend you to use 0.5.0
> 
> > I want to know more about --enable-chunked-prefill. and the constriant between args max-num-seqs, max-num-batched-tokens and max-model-len.
> 
> No constraint. I recommend you to use --max-num-batched-tokens, not --max-num-seqs when using chunked prefill though. I think it is easier to control the performance with --max-num-batched-tokens.
> 
> --max-model-len is unrelated to chunked prefill imo.
> 
> > can I use --enable-chunked-prefill and --enable-prefix-caching at the same time?
> 
> It is not supported yet. There's an open issue. We should support it soon.

Hi, I am not sure how to solve this problem. I failed to enable chunked prefill when I run model TheBloke/Llama-2-7B-Chat-GPTQ with benchmarks/benchmark_serving.py. 
I have some error message in this issue. https://github.com/vllm-project/vllm/issues/5566

**Comment by rkooo567** [comment]
Does it work without the chunked prefill?

**Comment by George-ao** [comment]
> Does it work without the chunked prefill?

Yes, it works without chunked prefill.

**Comment by rkooo567** [comment]
Hmm actually curious if it is related to https://github.com/vllm-project/vllm/issues/4381

**Comment by George-ao** [comment]
> Hmm actually curious if it is related to #4381

I am not sure but I think it may relate to vLLM server support. I can run Llama-2-7b-GPTQ quantized model with marlin kernel support and enable-chunked-prefill when I run it by "benchmark_latency.py" that uses offline inference.

**Comment by rkooo567** [comment]
Hmm that's pretty odd. Can you update the issue to explain the detailed repro? I can take a look when I have bandwidth

**Comment by tricky61** [comment]
> Hmm that's pretty odd. Can you update the issue to explain the detailed repro? I can take a look when I have bandwidth

Is chunked_prefill only supported in Ampere?
I get this error when running on v100, chunked_prefill=False is ok
/project/lib/Analysis/Allocation.cpp:43: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed.

**Comment by dhruvmullick** [comment]
@rkooo567 , is there a PR where we can track the status of the fix for 

> can I use --enable-chunked-prefill and --enable-prefix-caching at the same time?
      > It is not supported yet. There's an open issue. We should support it soon.

**Comment by rkooo567** [comment]
> Is chunked_prefill only supported in Ampere?

I think it should work as long as triton is supported. we have xformer attention + triton kernel working for chunked prefill. 

> @rkooo567 , is there a PR where we can track the status of the fix for

I think this should be fixed in the master by @comaniac https://github.com/vllm-project/vllm/commit/e3580537a41a46b0f3cd750b86b633c1857a8c90

**Comment by brando90** [comment]
@CharlesRiggins what is `max-num-batched-tokens`?

**Comment by DarkLight1337** [comment]
Prefix caching and chunked prefill are implicitly enabled using V1 architecture. It is still in alpha development, but you can try it out now by setting `VLLM_USE_V1=1`
