### ISSUE TITLE
[Installation]: `ModuleNotFoundError: No module named 'numpy.lib.function_base'` due to NumPy 2.0 release

### ISSUE THREAD

**Issue by glibg10b** [vllm-project/vllm#5587]
### Anything you want to discuss about vllm.

Users may see the following error when trying to run vllm:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/waldo/venv/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 26, in <module>
    from vllm.entrypoints.openai.serving_chat import OpenAIServingChat
  File "/home/waldo/venv/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 27, in <module>
    from vllm.model_executor.guided_decoding import (
  File "/home/waldo/venv/lib/python3.11/site-packages/vllm/model_executor/guided_decoding/__init__.py", line 6, in <module>
    from vllm.model_executor.guided_decoding.lm_format_enforcer_decoding import (
  File "/home/waldo/venv/lib/python3.11/site-packages/vllm/model_executor/guided_decoding/lm_format_enforcer_decoding.py", line 15, in <module>
    from vllm.model_executor.guided_decoding.outlines_decoding import (
  File "/home/waldo/venv/lib/python3.11/site-packages/vllm/model_executor/guided_decoding/outlines_decoding.py", line 13, in <module>
    from vllm.model_executor.guided_decoding.outlines_logits_processors import (
  File "/home/waldo/venv/lib/python3.11/site-packages/vllm/model_executor/guided_decoding/outlines_logits_processors.py", line 24, in <module>
    from outlines.fsm.guide import CFGGuide, Generate, Guide, RegexGuide, Write
  File "/home/waldo/venv/lib/python3.11/site-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/home/waldo/venv/lib/python3.11/site-packages/outlines/generate/__init__.py", line 2, in <module>
    from .cfg import cfg
  File "/home/waldo/venv/lib/python3.11/site-packages/outlines/generate/cfg.py", line 5, in <module>
    from outlines.models import OpenAI
  File "/home/waldo/venv/lib/python3.11/site-packages/outlines/models/__init__.py", line 14, in <module>
    from .openai import OpenAI, azure_openai, openai
  File "/home/waldo/venv/lib/python3.11/site-packages/outlines/models/openai.py", line 9, in <module>
    from outlines.base import vectorize
  File "/home/waldo/venv/lib/python3.11/site-packages/outlines/base.py", line 8, in <module>
    from numpy.lib.function_base import (
ModuleNotFoundError: No module named 'numpy.lib.function_base'
```

This is because numpy recently released a breaking change (2.0.0), and for some reason, vllm's dependencies don't restrict the version based on the major number (which should have been frozen at 1).

#5582 works around this, but this hasn't reached me -- I suspect it's because I'm using `pip install` instead of building from source. **A workaround for users like me is to run `pip install numpy==1.26.4`.**

The purpose of this issue is to show up when users search for the above output. Please do not close it until the fix is available to users of pip install.

**Comment by kzos** [comment]
still issue present for numpy >= 2.0.0

**Comment by DarkLight1337** [comment]
> still issue present for numpy >= 2.0.0

You should downgrade your numpy version to `< 2.0`.

**Comment by lassevk** [comment]
Attempting to install vllm and I still get

    Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)

pip install shows:

    Package Version
    ------- -------
    numpy   1.26.4
    pip     24.0

This is a fresh Ubuntu vm, all packages updated, only installed pip, set up a venv, and then installed numpy, vllm then fails to install.

Any tips on how to proceed?

**Comment by DarkLight1337** [comment]
Which version of pytorch are you using?

**Comment by lassevk** [comment]
I have not installed pytorch, I assumed that since the error occured in a pytorch file, and that I haven't explicitly installed it, that it was pulled as a dependency. I have only installed numpy 1.26.4 and then tried `pip install vllm`.

**Comment by DarkLight1337** [comment]
In that case, can you show the full stack trace for the error that occurs during the installation?

**Comment by lassevk** [comment]
Can do

```
(vllm-env) parallels@ubuntu-linux-2404:~$ pip install vllm
Collecting vllm
  Using cached vllm-0.6.4.post1.tar.gz (3.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      /tmp/pip-build-env-364f9owh/overlay/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "/home/parallels/vllm-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/parallels/vllm-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/parallels/vllm-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-364f9owh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-364f9owh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-364f9owh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 526, in <module>
        File "<string>", line 433, in get_vllm_version
      RuntimeError: Unknown runtime environment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by DarkLight1337** [comment]
cc @youkaichao @dtrifiro

**Comment by lassevk** [comment]
This is a Parallels Desktop (macos virtual machine) ubuntu install, with the following done to it:

```
sudo apt update
sudo apt upgrade
```

then I created the virtual env vllm-env, followed by:

```
source ~/vllm-env/bin/activate
pip install numpy==1.26.4
pip install vllm
```

**Comment by DarkLight1337** [comment]
> This is a Parallels Desktop (macos virtual machine) ubuntu install, with the following done to it:
> 
> ```
> sudo apt update
> sudo apt upgrade
> ```
> 
> then I created the virtual env vllm-env, followed by:
> 
> ```
> source ~/vllm-env/bin/activate
> pip install numpy==1.26.4
> pip install vllm
> ```
> 
> _(note, this is preliminary testing to host a llm, if there are other linux distributions or ways to get started, that is acceptable for me, I do not require this to be possible with the current installation, so if I started wrong, please enlighten me)_

I think that this issue is related to MacOS installation rather than numpy. Can you open a new issue for this?

**Comment by lassevk** [comment]
I can, but this is inside an ubuntu virtual machine running on arm (Apple silicon, M2 Pro), not a docker container or anything, so didn't expect this to be tied to MacOS. Doing it natively on MacOS has a whole host of other problems due to how Xcode has installed python3, so I assumed by setting up a virtual machine running Ubuntu linux it would be isolated enough from the MacOS system for it to not be an issue.

If, after my above comment, you still think it warrants its own issue, just say so and I will create a separate issue for it.

**Comment by DarkLight1337** [comment]
I'll let @mgoin also take a look at this before deciding.

**Comment by youkaichao** [comment]
> Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)

this is a warning.

> RuntimeError: Unknown runtime environment

this is the real error.

you can try to print along https://github.com/vllm-project/vllm/blob/a43065272f73a7468b1a35dd44fb5b0ed80f88c7/setup.py#L503 to see what's happening.

**Comment by luna0607** [comment]
I hit same error while using ubuntu as well. This might be a general problem for ubuntu OS
