### ISSUE TITLE
[Usage]: vllm0.5.0.post error when using openai completion interface

### ISSUE THREAD

**Issue by JackYangzg** [vllm-project/vllm#5662]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

INFO:     192.169.0.0:38154 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/tenant-home_speed/lzq/vllm/deploy_4_x/31671-31664/vllmServer5.py", line 119, in create_completion
    generator = await openai_serving_completion.create_completion(
  File "/mnt/tenant-home_speed/lzq/vllm/deploy_4_x/31671-31664/vllm05/serving_completion.py", line 106, in create_completion
    await get_guided_decoding_logits_processor(
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/__init__.py", line 17, in get_guided_decoding_logits_processor
    request = _adapt_request_for_tool_use(request)
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/vllm/model_executor/guided_decoding/__init__.py", line 38, in _adapt_request_for_tool_use
    if request.tool_choice == "none":
  File "/usr/local/miniconda3/envs/vllm5/lib/python3.10/site-packages/pydantic/main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CompletionRequest' object has no attribute 'tool_choice'

**Comment by simon-mo** [comment]
tool_choice is only available under Chat Completion interface, this is according to OpenAI's spec

**Comment by JackYangzg** [comment]
> tool_choice is only available under Chat Completion interface, this is according to OpenAI's spec

my mean using completion interface always throw this error.
the request not set tool_choice param, Why is this business logic being invoked?

my request:
{
"model": "llama3-70B-instruct",
"prompt": "take a long time to see you",
"max_tokens": 200,
"temperature": 0,
"stream": false
}

**Comment by JackYangzg** [comment]
> _adapt_request_for_tool_use

![image](https://github.com/vllm-project/vllm/assets/5477562/fb1c618d-655e-40cd-a918-5e9c35ba260b)
