### ISSUE TITLE
Failed to load the tokenizer

### ISSUE THREAD

**Issue by xxm1668** [vllm-project/vllm#569]
Traceback (most recent call last):
  File "src/inference_sft3.py", line 25, in <module>
    main()
  File "src/inference_sft3.py", line 14, in main
    llm = LLM(model="/dev/shm/LLaMA-Efficient-Tuning/output/ziya_llama_13b_merged")
  File "/home/house365ai/anaconda3/envs/vllm/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 62, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/house365ai/anaconda3/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 154, in from_engine_args
    engine = cls(*engine_configs,
  File "/home/house365ai/anaconda3/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 80, in __init__
    self.tokenizer = get_tokenizer(
  File "/home/house365ai/anaconda3/envs/vllm/lib/python3.8/site-packages/vllm/transformers_utils/tokenizer.py", line 42, in get_tokenizer
    raise RuntimeError(err_msg) from e
RuntimeError: Failed to load the tokenizer. If you are using a LLaMA-based model, use 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.

**Comment by zhuohan123** [comment]
Please try `--tokenizer hf-internal-testing/llama-tokenizer` as the error message suggested if you are using LLaMA-based models. Feel free to reopen the issue if you meet any other problems.

**Comment by xxm1668** [comment]
@zhuohan123 下载最新代码

**Comment by xxm1668** [comment]
@zhuohan123 或参考这个https://github.com/vllm-project/vllm/issues/270
