### ISSUE TITLE
[Bug]: asyncio.exceptions.CancelledError asyncio.exceptions.TimeoutError

### ISSUE THREAD

**Issue by ZZhangxian** [vllm-project/vllm#5732]
### Your current environment

Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.28

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB

Nvidia driver version: 525.125.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 57 bits virtual
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:            6
CPU MHz:             988.276
CPU max MHz:         3400.0000
CPU min MHz:         800.0000
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31,64-95
NUMA node1 CPU(s):   32-63,96-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy==1.9.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] numpydoc==1.5.0
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] sentence-transformers==3.0.1
[pip3] torch==2.3.0
[pip3] transformers==4.41.2
[pip3] triton==2.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5          py310hd5efca6_0  
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] numpydoc                  1.5.0           py310h06a4308_0  
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] sentence-transformers     3.0.1                    pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] transformers              4.41.2                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    CPU Affinity    NUMA Affinity
GPU0     X      NV8     NV8     NV8     SYS     SYS     PXB     PXB     NODE    NODE    NODE    NODE    NODE    32-63,96-127    1
GPU1    NV8      X      NV8     NV8     SYS     SYS     PXB     PXB     NODE    NODE    NODE    NODE    NODE    32-63,96-127    1
GPU2    NV8     NV8      X      NV8     SYS     SYS     NODE    NODE    PXB     PXB     PXB     PXB     NODE    32-63,96-127    1
GPU3    NV8     NV8     NV8      X      SYS     SYS     NODE    NODE    PXB     PXB     PXB     PXB     NODE    32-63,96-127    1
NIC0    SYS     SYS     SYS     SYS      X      PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC1    SYS     SYS     SYS     SYS     PIX      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC2    PXB     PXB     NODE    NODE    SYS     SYS      X      PIX     NODE    NODE    NODE    NODE    NODE
NIC3    PXB     PXB     NODE    NODE    SYS     SYS     PIX      X      NODE    NODE    NODE    NODE    NODE
NIC4    NODE    NODE    PXB     PXB     SYS     SYS     NODE    NODE     X      PIX     PXB     PXB     NODE
NIC5    NODE    NODE    PXB     PXB     SYS     SYS     NODE    NODE    PIX      X      PXB     PXB     NODE
NIC6    NODE    NODE    PXB     PXB     SYS     SYS     NODE    NODE    PXB     PXB      X      PIX     NODE
NIC7    NODE    NODE    PXB     PXB     SYS     SYS     NODE    NODE    PXB     PXB     PIX      X      NODE
NIC8    NODE    NODE    NODE    NODE    SYS     SYS     NODE    NODE    NODE    NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_4
  NIC3: mlx5_5
  NIC4: mlx5_6
  NIC5: mlx5_7
  NIC6: mlx5_8
  NIC7: mlx5_9
  NIC8: mlx5_bond_0

### 🐛 Describe the bug

ERROR: Exception in ASGI application
Traceback (most recent call last):
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step
request_outputs = await self.engine.step_async()
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async
output = await self.model_executor.execute_model_async(
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async
return await self._driver_execute_model_async(execute_model_req)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async
return await self.driver_exec_model(execute_model_req)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in call
return await self.app(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in call
await super().call(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/applications.py", line 123, in call
await self.middleware_stack(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in call
raise exc
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in call
await self.app(scope, receive, _send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in call
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
raise exc
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 756, in call
await self.middleware_stack(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
await route.handle(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
await self.app(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
raise exc
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
await response(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 258, in call
async with anyio.create_task_group() as task_group:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 574, in aexit
raise exceptions[0]
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
await func()
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response
async for chunk in self.body_iterator:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator
async for res in result_generator:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate
async for output in self._process_request(
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request
raise e
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request
async for request_output in stream:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in anext
raise result
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 42, in _log_task_completion
return_value = task.result()
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 532, in run_engine_loop
has_requests_in_progress = await asyncio.wait_for(
File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
result = await app( # type: ignore[func-returns-value]
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in call
return await self.app(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in call
await super().call(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/applications.py", line 123, in call
await self.middleware_stack(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in call
raise exc
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in call
await self.app(scope, receive, _send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in call
await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
raise exc
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 756, in call
await self.middleware_stack(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
await route.handle(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
await self.app(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
await wrap_app_handling_exceptions(app, request)(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
raise exc
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
await app(scope, receive, sender)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
await response(scope, receive, send)
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 258, in call
async with anyio.create_task_group() as task_group:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 574, in aexit
raise exceptions[0]
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
await func()
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response
async for chunk in self.body_iterator:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator
async for res in result_generator:
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate
async for output in self._process_request(
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 767, in _process_request
stream = await self.add_request(
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 572, in add_request
self.start_background_loop()
File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 443, in start_background_loop
raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Background loop has errored already.

**Comment by ZZhangxian** [comment]
2024-06-21T14:00:57.229006087+08:00 ERROR: Exception in ASGI application
2024-06-21T14:00:57.229015739+08:00 Traceback (most recent call last):
2024-06-21T14:00:57.229022362+08:00 File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step
2024-06-21T14:00:57.229028830+08:00 request_outputs = await self.engine.step_async()
2024-06-21T14:00:57.229035509+08:00 File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async
2024-06-21T14:00:57.229041491+08:00 output = await self.model_executor.execute_model_async(
2024-06-21T14:00:57.229047778+08:00 File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async
2024-06-21T14:00:57.229053895+08:00 return await self._driver_execute_model_async(execute_model_req)
2024-06-21T14:00:57.229060130+08:00 File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async
2024-06-21T14:00:57.229066146+08:00 return await self.driver_exec_model(execute_model_req)
2024-06-21T14:00:57.229072047+08:00 asyncio.exceptions.CancelledError
2024-06-21T14:00:57.229077477+08:00
2024-06-21T14:00:57.229084802+08:00 During handling of the above exception, another exception occurred:
2024-06-21T14:00:57.229090528+08:00
2024-06-21T14:00:57.229096490+08:00 Traceback (most recent call last):
2024-06-21T14:00:57.229102644+08:00 File "/root/anaconda3/envs/vllm/li
b/python3.10/asyncio/tasks.py", line 456, in wait_for
2024-06-21T14:00:57.229108631+08:00 return fut.result()
2024-06-21T14:00:57.229114492+08:00 asyncio.exceptions.CancelledError

**Comment by ZZhangxian** [comment]
ERROR 06-21 15:09:02 async_llm_engine.py:52]     x, _ = self.down_proj(x)
2024-06-21T15:09:02.358742631+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
2024-06-21T15:09:02.358749790+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]     return self._call_impl(*args, **kwargs)
2024-06-21T15:09:02.358756498+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
2024-06-21T15:09:02.358763389+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]     return forward_call(*args, **kwargs)
2024-06-21T15:09:02.358770096+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 804, in forward
2024-06-21T15:09:02.358776852+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]     output_parallel = self.quant_method.apply(self, input_parallel)
ERROR 06-21 15:09:02 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/awq.py", line 169, in apply
2024-06-21T15:09:02.358790378+08:00 ERROR 06-21 15:09:02 async_llm_engine.py:52]     out = torch.matmul(reshaped_x, out)
ERROR 06-21 15:09:02 async_llm_engine.py:52] torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 492.00 MiB. GPU 
ERROR:asyncio:Exception in callback functools.partial(<function _log_task_completion at 0x7fa2827113f0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7fa258667df0>>)
2024-06-21T15:09:02.361567693+08:00 handle: <Handle functools.partial(<function _log_task_completion at 0x7fa2827113f0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7fa258667df0>>)>
2024-06-21T15:09:02.361575961+08:00 Traceback (most recent call last):
2024-06-21T15:09:02.361583992+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 42, in _log_task_completion
2024-06-21T15:09:02.361591500+08:00     return_value = task.result()
2024-06-21T15:09:02.361598778+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 532, in run_engine_loop
2024-06-21T15:09:02.361606784+08:00     has_requests_in_progress = await asyncio.wait_for(
2024-06-21T15:09:02.361614131+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
(VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: CUDA out of memory. Tried to allocate 492.00 MiB. GPU  has a total capacity of 79.32 GiB of which 77.56 MiB is free. Process 2811341 has 79.24 GiB memory in use. Of the allocated memory 73.08 GiB is allocated by PyTorch, and 1.52 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables), Traceback (most recent call last):
2024-06-21T15:09:02.361643250+08:00 (VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
2024-06-21T15:09:02.361654663+08:00 (VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T15:09:02.361660848+08:00 (VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
2024-06-21T15:09:02.361631137+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step
2024-06-21T15:09:02.361671065+08:00     request_outputs = await self.engine.step_async()
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async
(VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 294, in start_worker_execution_loop
2024-06-21T15:09:02.361686031+08:00     output = await self.model_executor.execute_model_async(
2024-06-21T15:09:02.361696125+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async
2024-06-21T15:09:02.361703177+08:00     return await self._driver_execute_model_async(execute_model_req)
2024-06-21T15:09:02.361710431+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async
2024-06-21T15:09:02.361717227+08:00     return await self.driver_exec_model(execute_model_req)
2024-06-21T15:09:02.361724226+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-06-21T15:09:02.361730993+08:00     result = self.fn(*self.args, **self.kwargs)
2024-06-21T15:09:02.361738099+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]     while self._execute_model_non_driver():
2024-06-21T15:09:02.361771008+08:00 (VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 317, in _execute_model_non_driver
2024-06-21T15:09:02.361781698+08:00 (VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]     self.model_runner.execute_model(None, self.gpu_cache)
2024-06-21T15:09:02.361744892+08:00     return func(*args, **kwargs)
(VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-06-21T15:09:02.361796983+08:00   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 280, in execute_model
(VllmWorkerProcess pid=960) ERROR 06-21 15:09:02 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
    output = self.model_runner.execute_model(seq_group_metadata_list,

**Comment by ZZhangxian** [comment]
Why doesn't the VLLM-related process disappear after the program reports an error, the vllm process will always occupy the video memory, but the request interface will always report the same error

**Comment by ZZhangxian** [comment]
> Why doesn't the VLLM-related process disappear after the program reports an error, the vllm process will always occupy the video memory, but the request interface will always report the same error

You need to manually kill the VLLM-related process and then restart the asynchronous service to restore the normal process
