### ISSUE TITLE
[Bug]: KeyError: '/psm_ed65b7e3'

### ISSUE THREAD

**Issue by randydl** [vllm-project/vllm#5740]
### Your current environment

Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.29.6
Libc version: glibc-2.31

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40
GPU 4: NVIDIA A40
GPU 5: NVIDIA A40
GPU 6: NVIDIA A40
GPU 7: NVIDIA A40

Nvidia driver version: 550.54.14
cuDNN version: Probably one of the following:
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_engines_precompiled.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_graph.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_heuristic.so.9.1.0
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    4
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         872.127
CPU max MHz:                     2601.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] open-clip-torch==2.24.0
[pip3] pytorch-lightning==2.3.0
[pip3] pytorch-metric-learning==2.5.0
[pip3] torch==2.3.0
[pip3] torchaudio==2.3.0
[pip3] torchinfo==1.8.0
[pip3] torchio==0.19.6
[pip3] torchmetrics==1.4.0.post0
[pip3] torchvision==0.18.0
[pip3] transformers==4.41.2
[pip3] triton==2.3.0
[conda] nccl                      2.22.3.1             hbc370b7_0    conda-forge
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] open-clip-torch           2.24.0                   pypi_0    pypi
[conda] pytorch-lightning         2.3.0                    pypi_0    pypi
[conda] pytorch-metric-learning   2.5.0                    pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] torchaudio                2.3.0                    pypi_0    pypi
[conda] torchinfo                 1.8.0                    pypi_0    pypi
[conda] torchio                   0.19.6                   pypi_0    pypi
[conda] torchmetrics              1.4.0.post0              pypi_0    pypi
[conda] torchvision               0.18.0                   pypi_0    pypi
[conda] transformers              4.41.2                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV4     PIX     PIX     SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-15,64-79      0               N/A
GPU1    NV4      X      PIX     PIX     SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-15,64-79      0               N/A
GPU2    PIX     PIX      X      NV4     SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-15,64-79      0               N/A
GPU3    PIX     PIX     NV4      X      SYS     SYS     SYS     SYS     PIX     PIX     SYS     SYS     0-15,64-79      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      NV4     PIX     PIX     SYS     SYS     PIX     PIX     32-47,96-111    2               N/A
GPU5    SYS     SYS     SYS     SYS     NV4      X      PIX     PIX     SYS     SYS     PIX     PIX     32-47,96-111    2               N/A
GPU6    SYS     SYS     SYS     SYS     PIX     PIX      X      NV4     SYS     SYS     PIX     PIX     32-47,96-111    2               N/A
GPU7    SYS     SYS     SYS     SYS     PIX     PIX     NV4      X      SYS     SYS     PIX     PIX     32-47,96-111    2               N/A
NIC0    PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS      X      PIX     SYS     SYS
NIC1    PIX     PIX     PIX     PIX     SYS     SYS     SYS     SYS     PIX      X      SYS     SYS
NIC2    SYS     SYS     SYS     SYS     PIX     PIX     PIX     PIX     SYS     SYS      X      PIX
NIC3    SYS     SYS     SYS     SYS     PIX     PIX     PIX     PIX     SYS     SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3

### 🐛 Describe the bug

INFO 06-21 19:23:14 api_server.py:177] vLLM API server version 0.5.0.post1
INFO 06-21 19:23:14 api_server.py:178] args: Namespace(host='0.0.0.0', port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/home/app.e0016372/models/Qwen1.5-72B-Chat', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=8, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, image_processor=None, image_processor_revision=None, disable_image_processor=False, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=['Qwen1.5-72B-Chat'], qlora_adapter_name_or_path=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2024-06-21 19:23:17,334	INFO worker.py:1770 -- Started a local Ray instance.
INFO 06-21 19:23:18 config.py:623] Defaulting to use mp for distributed inference
INFO 06-21 19:23:18 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='/home/app.e0016372/models/Qwen1.5-72B-Chat', speculative_config=None, tokenizer='/home/app.e0016372/models/Qwen1.5-72B-Chat', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=8, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=Qwen1.5-72B-Chat)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:23:23 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:23:24 utils.py:637] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:23:24 pynccl.py:63] vLLM is using nccl==2.20.5
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
Traceback (most recent call last):
  File "/home/app.e0016372/miniconda3/envs/main/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_ed65b7e3'
[1;36m(VllmWorkerProcess pid=445419)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445422)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445420)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445421)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445417)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445418)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445416)[0;0m WARNING 06-21 19:23:24 custom_all_reduce.py:166] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:23:32 model_runner.py:160] Loading model weights took 16.8428 GB
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:23:33 model_runner.py:160] Loading model weights took 16.8428 GB
INFO 06-21 19:23:52 distributed_gpu_executor.py:56] # GPU blocks: 4114, # CPU blocks: 819
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:23:56 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:23:56 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=445416)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
[1;36m(VllmWorkerProcess pid=445417)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
[1;36m(VllmWorkerProcess pid=445422)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
[1;36m(VllmWorkerProcess pid=445419)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
[1;36m(VllmWorkerProcess pid=445418)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
[1;36m(VllmWorkerProcess pid=445420)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
[1;36m(VllmWorkerProcess pid=445421)[0;0m INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
INFO 06-21 19:24:14 model_runner.py:965] Graph capturing finished in 18 secs.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 06-21 19:24:14 serving_chat.py:92] Using default chat template:
INFO 06-21 19:24:14 serving_chat.py:92] {% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system
INFO 06-21 19:24:14 serving_chat.py:92] You are a helpful assistant<|im_end|>
INFO 06-21 19:24:14 serving_chat.py:92] ' }}{% endif %}{{'<|im_start|>' + message['role'] + '
INFO 06-21 19:24:14 serving_chat.py:92] ' + message['content'] + '<|im_end|>' + '
INFO 06-21 19:24:14 serving_chat.py:92] '}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
INFO 06-21 19:24:14 serving_chat.py:92] ' }}{% endif %}
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 06-21 19:24:14 serving_embedding.py:141] embedding_mode is False. Embedding API will not work.
INFO:     Started server process [438066]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by randydl** [comment]
```bash
NAME='Qwen2-72B-Instruct' && \
python -m vllm.entrypoints.openai.api_server \
    --host 0.0.0.0 \
    --port 8000 \
    --served-model-name $NAME \
    --model /nas_data/userdata/randy/models/$NAME \
    --tensor-parallel-size 8 \
    --trust-remote-code \
    --enforce-eager
```

**Comment by mgoin** [comment]
This is a known issue that has been resolved with https://github.com/vllm-project/vllm/pull/5512 - it will be in the next release.

Thankfully it is a benign error and I can see from your log that the server still set up fine. Cheers!
