### ISSUE TITLE
Key Error when handle multiple requests simultaneously

### ISSUE THREAD

**Issue by David-Lee-1990** [vllm-project/vllm#579]
After building a flask service while vllm as the LLM model,  

when i test the service with multiple requests simutaneously, it raise key error at scheduler.py

Traceback (most recent call last):
  File "/web/anaconda3/envs/vllm/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/web/anaconda3/envs/vllm/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/web/anaconda3/envs/vllm/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/web/anaconda3/envs/vllm/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "JZ_service_vllm.py", line 184, in get_response
    outputs = vllm_model.generate([system_prompt], sampling_params, use_tqdm=False) # , use_tqdm=False
  File "/root/vllm/vllm/entrypoints/llm.py", line 130, in generate
    return self._run_engine(use_tqdm)
  File "/root/vllm/vllm/entrypoints/llm.py", line 150, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/root/vllm/vllm/engine/llm_engine.py", line 303, in step
    seq_groups = self.scheduler.update(output)
  File "/root/vllm/vllm/core/scheduler.py", line 319, in update
    output = seq_outputs[seq.seq_id]
KeyError: 204

How can i solve this?

**Comment by nutmilk10** [comment]
@David-Lee-1990 how did you resolve this issue?
