### ISSUE TITLE
[Bug]: Different quality responses using GPTQ / marlin kernels on A10 vs A100 GPUs

### ISSUE THREAD

**Issue by joe-schwartz-certara** [vllm-project/vllm#5793]
### 🐛 Describe the bug

Hello, 

I am running llama3-70b and mixtral with VLLM on a bunch of different kinds of machines. I encountered wildly different quality performance on A10 GPUs vs A100/H100 GPUs for ONLY gptq models and marlin kernels. GPTQ with marlin kernels is way faster than AWQ but with AWQ, i see roughly the same response on my test queries on either kind of GPU environment. For A10 deployments, the only difference in the settings is that I use 2 A10 24GB GPUs instead of 1 A100 or H100 (using the tensor parallelism param).  I am running vllm = 0.4.2. I am using examples from llama3-70b testing on a very simple test query but I also saw the similar flavor of quality issues with mixtral-awq vs mixtral-gptq as well and I also saw the same flavor of issues on all my other more complicated RAG test queries as well. Generally the gptq models on A10s are psychotic and unusable and behave as if the model files are screwed up, which is why i tested two publicly available quantizations of llama3... 

I also tried to simulate a GPU environment of 2 A10s on 1 single A100 by setting --gpu-memory-utilization to 0.55 i.e. I choked the vram on the A100 deployment to choke the kv-cache available space. I got the same good quality performance on the A100 that I always see albeit with less throughput since my kv-cache was choked. No psychotic responses like I see on A10s. 

Here's my examples,

Test prompt: "what model are you and what quantization do you use?"

Model : https://huggingface.co/casperhansen/llama-3-70b-instruct-awq
Model Args: --max-model-len 8192 --quantization awq --dtype half --gpu-memory-utilization 0.99 --trust-remote-code --enforce-eager --kv-cache-dtype fp8

Response on A10 or A100 (doesn't matter where I deploy it, I get pretty much the same response):
```
"I'm an AI assistant, and I'm happy to share some information about my architecture.

I'm a large language model, specifically a transformer-based model, which is a type of neural network designed primarily for natural language processing tasks. My model is based on the BERT (Bidirectional Encoder Representations from Transformers) architecture, which was developed by Google in 2018.

Regarding quantization, I don't use traditional quantization techniques like fixed-point or floating-point quantization. Instead, my model uses a technique called "knowledge distillation" to reduce the precision of my weights and activations while maintaining the accuracy of my responses.

Knowledge distillation is a method that involves training a smaller, simpler model (the "student") to mimic the behavior of a larger, more complex model (the "teacher"). In my case, the teacher model is a large, floating-point BERT model, and the student model is a smaller, integer-based version of myself.

During training, the student model learns to approximate the behavior of the teacher model by minimizing the difference between their outputs. This process allows me to maintain high accuracy while using fewer computational resources and reducing my memory footprint.

So, to summarize: I'm a BERT-based language model that uses knowledge distillation to reduce precision and improve efficiency, rather than traditional quantization techniques." 
```

Model : https://huggingface.co/TechxGenus/Meta-Llama-3-70B-GPTQ or https://huggingface.co/MaziyarPanahi/Meta-Llama-3-70B-Instruct-GPTQ (tested with both)
Model Args: --max-model-len 8192 --quantization marlin --dtype half --gpu-memory-utilization 0.99 --trust-remote-code --enforce-eager --kv-cache-dtype fp8

Response on A100:
```
"Thank you for asking!

I am a type of artificial intelligence language model, to be specific, I'm a transformer-based language model. My architecture is based on the transformer model introduced in the paper "Attention is All You Need" by Vaswani et al. in 2017.

As for quantization, I don't use traditional quantization methods like 8-bit or 16-bit integer quantization. Instead, I rely on a technique called "floating-point quantization" which allows me to represent my weights and activations using a combination of floating-point numbers and integers.

In more detail, my model uses a combination of the following techniques:

1. **Weight pruning**: This involves removing redundant or unnecessary weights from my neural network to reduce its size and computational requirements.
2. **Knowledge distillation**: This is a process where a smaller model (like me) is trained to mimic the behavior of a larger, more complex model. This helps to transfer knowledge from the larger model to me.
3. **Quantization-aware training**: During training, my weights and activations are simulated using lower precision data types (like integers) to mimic the effects of quantization. This helps me to learn how to represent information efficiently even with reduced precision.

These techniques allow me to maintain a good balance between accuracy and computational efficiency, I can provide helpful responses quickly while still being able to understand and respond accurately.

Please let me know if you have any other questions or if there's anything else I can help with!"
```

Response on 2 A10s (tensor parallelism):
```
"into the 2000s and the 2000s of the 2000s and the 2000s of the 2000s and the 2000s of the 2000s."
```
or something else equally psychotic and random (it produces a different response every time so I have a feeling this has to do with nondeterminism). Heres another example of a response on the same prompt:

```
"Anita; and the last; and the first; and the last; and the first; and the last.

Anita;
and the last;
and the first;
and the last;
and the first;
and the last.
[Anita];
[the last];
[the first];
[the last];
[the first];
[the last].
Anita;
and the last;
and the first;
and the last;
and the first;
and the last.
[Anita]];
[the last]];
[[the first]];
[[the last]];
[[the first]];
[[the last]].
Anita:;
and [[the last]];
[[the first]]];
[[the last]]];
[[the first]]];
[[the last]].
Anita:;
[[last]]];
[[first]]];
[[last]]];
[[first]];
[[last]].
Anita:;
 [[[last]]],
 [[[first]]],
 [[[last]]],
 [[[first]]],
 [[[last]]].
Anita:;
 [[[last]],
 [[[first]],
 [[[last]],
{{{first}},
{{{last}}].
Anita:;
{{{last}},
{{{first}},
{{{last}},
{{{first}},
{{{last}}].
Anita:;
{{{last}},
{{{first}},
{{{last}},
{{{first}},
{{{last}}].

This is a series of nested brackets,2019. The output is a series of nested brackets."
```

Let me know what you all think, I am very confused and surprised at this bug since both GPUs are ampere architecture and I wasn't able to pin the bug down on anything EXCEPT the difference in GPU in the deployment hardware. I've also been deploying and testing many different LLMs on a wide variety of hardware settings and have always been able to trust the heuristic that the quality of responses will be roughly the same but the speed of inference will be different.

**Comment by joe-schwartz-certara** [comment]
> Thanks a lot for posting this issue @joe-schwartz-certara ! We will take a close look at the results (appreciate the repro steps). I'll be interested to see if with or without `--kv-cache-dtype fp8` has any impact on the sensitivity.

I can try to find a different model to use and test but the issue is I won't even be able to run llama3-70b on 2 a10s without that optimization. In the a100 situation, it's the same kind of dependable llama3 that I know and love whether or not I turn on fp8 for the cache. Remember too that I run llama3-70b awq just fine with fp8 kv cache on any GPU and get pretty much the same responses for my more structured queries. From my understanding, kv cache dtype won't affect anything at inference time because vllm upscales back to regular precision when its time to use it.

**Comment by JaheimLee** [comment]
Similar issue. I run Qwen2-72B-Instruct-GPTQ-Int4 on 4 3090. The result may be different even though `use_beam_search=True`

**Comment by llmpros** [comment]
I have various types of GPU, including A10, and can reproduce to poke it around

**Comment by mgoin** [comment]
This should be fixed by this PR: https://github.com/vllm-project/vllm/pull/6795

**Comment by JohnTheNerd** [comment]
I can confirm this issue no longer occurs on my setup after building #6795. Running on 2xRTX3090, with the following arguments/environment:

```
export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-12.2/bin:$PATH
export CUDACXX=/usr/local/cuda-12.2/bin/nvcc

export VLLM_ATTENTION_BACKEND=FLASHINFER

set -e

/usr/bin/python3 -m vllm.entrypoints.openai.api_server \
--model="/mnt/disk/models/Meta-Llama-3.1-70B-Instruct-AWQ-INT4" \
--served-model-name="llama-3.1-70b" \
--max-model-len="11264" \
--dtype="auto" \
--gpu-memory-utilization="0.983" \
--distributed-executor-backend="mp" \
--enable-chunked-prefill=false \
--quantization="awq_marlin" \
--enforce-eager \
--tensor-parallel-size="2" \
--swap-space="1" \
--enable-prefix-caching \
--disable-log-requests \
--disable-log-stats \
--host="0.0.0.0" --port="5000"
```

**Comment by 962086838** [comment]
@JohnTheNerd 

Hi John, I still find the problem exists on 4 A800 card. 
I run your command and serving the llama 3.1-70B. But I got the error:
```
Process Process-1:
Traceback (most recent call last):
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/entrypoints/openai/rpc/server.py", line 217, in run_rpc_server                                              server = AsyncEngineRPCServer(async_engine_args, usage_context, port)
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/entrypoints/openai/rpc/server.py", line 25, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(async_engine_args,
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 471, in from_engine_args
    engine = cls(
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 381, in __init__
    self.engine = self._init_engine(*args, **kwargs)                                                                                                                                  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 552, in _init_engine
    return engine_class(*args, **kwargs)                                                                                                                                              File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 249, in __init__
    self.model_executor = executor_class(                                                                                                                                             File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 215, in __init__
    super().__init__(*args, **kwargs)                                                                                                                                                 File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 138, in _init_executor
    self._run_workers("load_model",
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 192, in _run_workers
    driver_worker_output = driver_worker_method(*args, **kwargs)
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/worker/worker.py", line 139, in load_model
    self.model_runner.load_model()                                                                                                                                                    File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 722, in load_model
    self.model = get_model(model_config=self.model_config,                                                                                                                            File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
    return loader.load_model(model_config=model_config,
  File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 324, in load_model
    model = _initialize_model(model_config, self.load_config,                                                                                                                         File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 152, in _initialize_model
    quant_config = _get_quantization_config(model_config, load_config)                                                                                                                File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 93, in _get_quantization_config
    quant_config = get_quant_config(model_config, load_config)                                                                                                                        File "/root/anaconda3/envs/hurry_up_hhw/lib/python3.10/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 173, in get_quant_config
    raise ValueError(                                                                                                                                                               ValueError: Cannot find the config file for awq_marlin
```

My environment is 
```
vllm==0.5.4
torch==2.4.0
cuda==12.1
```
Is it a problem of cuda version?

**Comment by JohnTheNerd** [comment]
@962086838 I'm not sure, i currently run llama 3.1 too without any issues. is it possible you're trying to run the unquantized version with the awq_marlin option? it is meant to be used on AWQ quants only.
