### ISSUE TITLE
[Bug]: vLLM crash when running Phi-3-small-8k-instruct with enable-chunked-prefill

### ISSUE THREAD

**Issue by yaronr** [vllm-project/vllm#5961]
### Your current environment

```
image": "vllm/vllm-openai:latest",
--model=microsoft/Phi-3-small-8k-instruct 
--tensor-parallel-size=1
--disable-log-requests
--trust-remote-code
--enable-chunked-prefill
--max-num-batched-tokens=2048
--max-model-len=4096
--gpu-memory-utilization=0.9",
```
Accelerator: 1x Nvidia L4

### 🐛 Describe the bug

```
ERROR 06-28 13:26:18 async_llm_engine.py:52] Engine background task failed
ERROR 06-28 13:26:18 async_llm_engine.py:52] Traceback (most recent call last):
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 42, in _log_task_completion
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return_value = task.result()
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 532, in run_engine_loop
ERROR 06-28 13:26:18 async_llm_engine.py:52]     has_requests_in_progress = await asyncio.wait_for(
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return fut.result()
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step
ERROR 06-28 13:26:18 async_llm_engine.py:52]     request_outputs = await self.engine.step_async()
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 235, in step_async
ERROR 06-28 13:26:18 async_llm_engine.py:52]     output = await self.model_executor.execute_model_async(
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 117, in execute_model_async
ERROR 06-28 13:26:18 async_llm_engine.py:52]     output = await make_async(self.driver_worker.execute_model
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 06-28 13:26:18 async_llm_engine.py:52]     result = self.fn(*self.args, **self.kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return func(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 280, in execute_model
ERROR 06-28 13:26:18 async_llm_engine.py:52]     output = self.model_runner.execute_model(seq_group_metadata_list,
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return func(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 749, in execute_model
ERROR 06-28 13:26:18 async_llm_engine.py:52]     hidden_states = model_executable(
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return self._call_impl(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return forward_call(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/phi3_small.py", line 416, in forward
ERROR 06-28 13:26:18 async_llm_engine.py:52]     output_hidden_states = self.model(
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return self._call_impl(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return forward_call(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/phi3_small.py", line 338, in forward
ERROR 06-28 13:26:18 async_llm_engine.py:52]     hidden_states = layer(
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return self._call_impl(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return forward_call(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/phi3_small.py", line 282, in forward
ERROR 06-28 13:26:18 async_llm_engine.py:52]     hidden_states = self.self_attn(
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return self._call_impl(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return forward_call(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/phi3_small.py", line 244, in forward
ERROR 06-28 13:26:18 async_llm_engine.py:52]     attn_output = self.attn(q, k, v, kv_cache, attn_metadata=attn_metadata)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return self._call_impl(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return forward_call(*args, **kwargs)
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/attention/layer.py", line 89, in forward
ERROR 06-28 13:26:18 async_llm_engine.py:52]     return self.impl.forward(query, key, value, kv_cache, attn_metadata,
ERROR 06-28 13:26:18 async_llm_engine.py:52]   File "/usr/local/lib/python3.10/dist-packages/vllm/attention/backends/blocksparse_attn.py", line 376, in forward
ERROR 06-28 13:26:18 async_llm_engine.py:52]     or prefill_meta.block_tables.numel() == 0, \
ERROR 06-28 13:26:18 async_llm_engine.py:52] AssertionError: Does not support prefix-enabled attention.
```

**Comment by mgoin** [comment]
Hi @yaronr Phi-3-small doesn't support prefix caching or chunked prefill because it uses BlockSparse Attention, which is relatively new. Please remove `--enable-chunked-prefill` from your command.

**Comment by mgoin** [comment]
Closing since this is a known issue with a clear error message.

**Comment by yaronr** [comment]
Thank you :)
Any plans to support it?
