### ISSUE TITLE
Model architectures ['BaichuanForCausalLM'] are not supported for now.

### ISSUE THREAD

**Issue by a1164714** [vllm-project/vllm#600]
```python
INFO 07-27 17:20:09 llm_engine.py:67] Initializing an LLM engine with config: model='./baichuan-inc--Baichuan-13B-Chat/snapshots/d0a98e13222c6e82d24062f60ff491519e249744', tokenizer='./baichuan-inc--Baichuan-13B-Chat/snapshots/d0a98e13222c6e82d24062f60ff491519e249744', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
WARNING 07-27 17:20:09 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13189 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13189 [0] NCCL INFO cudaDriverVersion 11000
NCCL version 2.14.3+cuda11.7
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Using network IB
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Setting affinity for GPU 0 to e3,80080000,00e38000
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 00/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 01/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 02/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 03/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 04/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 05/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 06/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 07/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 08/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 09/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 10/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 11/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 12/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 13/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 14/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 15/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 16/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 17/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 18/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 19/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 20/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 21/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 22/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 23/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 24/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 25/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 26/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 27/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 28/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 29/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 30/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Channel 31/32 :    0
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Connected all rings
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO Connected all trees
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
ts-253610bc360a49f2b5909ce950baf8d2-launcher:13189:13268 [0] NCCL INFO comm 0x3ffca860 rank 0 nranks 1 cudaDev 0 busId 1b000 - Init COMPLETE
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    llm = LLM(model=model_dir, tokenizer=model_dir, trust_remote_code=True, tensor_parallel_size = 1, dtype="float16")
  File "/root/vllm/vllm/entrypoints/llm.py", line 66, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/root/vllm/vllm/engine/llm_engine.py", line 207, in from_engine_args
    engine = cls(*engine_configs,
  File "/root/vllm/vllm/engine/llm_engine.py", line 98, in __init__
    self._init_workers(distributed_init_method)
  File "/root/vllm/vllm/engine/llm_engine.py", line 123, in _init_workers
    self._run_workers(
  File "/root/vllm/vllm/engine/llm_engine.py", line 384, in _run_workers
    output = executor(*args, **kwargs)
  File "/root/vllm/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "/root/vllm/vllm/model_executor/model_loader.py", line 38, in get_model
    model_class = _get_model_architecture(model_config.hf_config)
  File "/root/vllm/vllm/model_executor/model_loader.py", line 32, in _get_model_architecture
    raise ValueError(
ValueError: Model architectures ['BaichuanForCausalLM'] are not supported for now. Supported architectures: ['BaiChuanForCausalLM', 'BloomForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM']
```

**Comment by a1164714** [comment]
I try baichuan-7B is ok，so vllm don't support Baichuan-13B-Chat?
