### ISSUE TITLE
RayWorker import error

### ISSUE THREAD

**Issue by zxdvd** [vllm-project/vllm#604]
When import `vllm` I got following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/vllm/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/code/vllm/vllm/engine/async_llm_engine.py", line 7, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/code/vllm/vllm/engine/llm_engine.py", line 9, in <module>
    from vllm.engine.ray_utils import initialize_cluster, ray, RayWorker
ImportError: cannot import name 'RayWorker' from 'vllm.engine.ray_utils' 
```
It seems `ray` requires `pandas` I haven't installed it.

**Comment by TheBloke** [comment]
Yes I have the same issue at the moment. There's been a lot of dependency issues recently

**Comment by hrushikesh198** [comment]
> It seems ray requires pandas I haven't installed it.
Thanks @zxdvd this saved my day !!
