### ISSUE TITLE
Run openai server error

### ISSUE THREAD

**Issue by SeungjaeLim** [vllm-project/vllm#613]
When I install vllm in the docker environment you provided, the normal server opens fine, but when I try to run the openai server, I get the following error.

```
vllm# python -m vllm.entrypoints.openai.api_server \
> --model facebook/opt-125m
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/****/origin_vllm/vllm/vllm/entrypoints/openai/api_server.py", line 20, in <module>
    from vllm.entrypoints.openai.protocol import (
  File "/home/****/origin_vllm/vllm/vllm/entrypoints/openai/protocol.py", line 106, in <module>
    class CompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

I haven't modified the code in particular, but I'm getting the following error, is there any way to fix this?

**Comment by esmeetu** [comment]
try

pip install typing_extensions==4.5.0 pydantic==1.10.0

**Comment by zhuohan123** [comment]
Feel free to reopen if there is any further issue!
