### ISSUE TITLE
[Bug]: vllm not working in lightllm

### ISSUE THREAD

**Issue by tusharraskar** [vllm-project/vllm#6215]
### Your current environment

import litellm 

litellm.set_verbose=True

import litellm 

response = litellm.completion(
    model="vllm/microsoft/Phi-3-small-8k-instruct", 
    messages="who is the PM of India",
    temperature=0.2,
    trust_remote_code=True,
    max_tokens=80
)

print(response)

### 🐛 Describe the bug

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 41, in get_config
    config = AutoConfig.from_pretrained(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 968, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 640, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading microsoft/Phi-3-small-8k-instruct requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 31, in validate_environment
    llm = LLM(model=model)
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 149, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 376, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 625, in create_engine_config
    model_config = ModelConfig(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/config.py", line 151, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision,
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 54, in get_config
    raise RuntimeError(err_msg) from e
RuntimeError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 51, in completion
    llm, SamplingParams = validate_environment(model=model)
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 34, in validate_environment
    raise VLLMError(status_code=0, message=str(e))
litellm.llms.vllm.VLLMError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/main.py", line 2392, in completion
    model_response = vllm.completion(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 53, in completion
    raise VLLMError(status_code=0, message=str(e))
litellm.llms.vllm.VLLMError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/test.py", line 8, in <module>
    response = litellm.completion(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/main.py", line 2674, in completion
    raise exception_type(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 7665, in exception_type
    raise e
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 7348, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: VLLMException - Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.
(venv) ubuntu@ip-10-102-2-236:~/Tushar/vllm_test$ python test.py 

Request to litellm:
litellm.completion(model='vllm/microsoft/Phi-3-small-8k-instruct', messages='who is the PM of India', temperature=0.2, trust_remote_code=True, max_tokens=80)

14:53:55 - LiteLLM:WARNING: utils.py:341 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'temperature': 0.2, 'max_tokens': 80, 'trust_remote_code': True}

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Provider List: https://docs.litellm.ai/docs/providers

Logging Details: logger_fn - None | callable(logger_fn) - False
Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 41, in get_config
    config = AutoConfig.from_pretrained(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 968, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 640, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading microsoft/Phi-3-small-8k-instruct requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 31, in validate_environment
    llm = LLM(model=model)
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 149, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 376, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 625, in create_engine_config
    model_config = ModelConfig(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/config.py", line 151, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision,
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 54, in get_config
    raise RuntimeError(err_msg) from e
RuntimeError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 51, in completion
    llm, SamplingParams = validate_environment(model=model)
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 34, in validate_environment
    raise VLLMError(status_code=0, message=str(e))
litellm.llms.vllm.VLLMError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/main.py", line 2392, in completion
    model_response = vllm.completion(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/llms/vllm.py", line 53, in completion
    raise VLLMError(status_code=0, message=str(e))
litellm.llms.vllm.VLLMError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Tushar/vllm_test/test.py", line 8, in <module>
    response = litellm.completion(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/main.py", line 2674, in completion
    raise exception_type(
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 7665, in exception_type
    raise e
  File "/home/ubuntu/Tushar/vllm_test/venv/lib/python3.10/site-packages/litellm/utils.py", line 7348, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: VLLMException - Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

**Comment by mgoin** [comment]
Hi @tusharraskar vLLM supports configuration of trust_remote_code: https://github.com/vllm-project/vllm/blob/f7a8fa39d828136d0b8bbdd20c262602e5543ffd/vllm/engine/arg_utils.py#L30

I suspect this is an issue with litellm not properly passing the kwarg to vLLM, which it needs to do to properly support this case. Please open an issue on their repository, thanks!

**Comment by tusharraskar** [comment]
how can I use base url if I hosted on different system
