### ISSUE TITLE
[Bug]:  benchmark_throughput gets TypeError: XFormersMetadata.__init__() got an unexpected keyword argument 'is_prompt' wit CPU 

### ISSUE THREAD

**Issue by LGLG42** [vllm-project/vllm#6225]
### Your current environment

```text
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35

...

[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] torchvision==0.18.0
[pip3] transformers==4.42.3
[pip3] triton==2.3.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] torchvision               0.18.0                   pypi_0    pypi
[conda] transformers              4.42.3                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
```

### 🐛 Describe the bug

Running `benchmark_throughput.py ... --device cpu` throws an exception, it works with GPU. 

```
VLLM_CPU_KVCACHE_SPACE=16 time python benchmarks/benchmark_throughput.py --model mosaicml/mpt-7b --input-len 128 --output-len 512 --trust-remote-code --backend=vllm  --device cpu --dtype bfloat16
...
WARNING 07-08 21:21:47 cpu_executor.py:119] CUDA graph is not supported on CPU, fallback to the eager mode.
INFO 07-08 21:21:48 selector.py:191] Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 07-08 21:21:48 selector.py:53] Using XFormers backend.
INFO 07-08 21:21:49 selector.py:191] Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 07-08 21:21:49 selector.py:53] Using XFormers backend.
INFO 07-08 21:21:50 weight_utils.py:218] Using model weights format ['*.bin']
pytorch_model-00002-of-00002.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.36G/3.36G [00:32<00:00, 103MB/s]
pytorch_model-00001-of-00002.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.94G/9.94G [01:18<00:00, 126MB/s]
INFO 07-08 21:23:44 cpu_executor.py:72] # CPU blocks: 2048████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 9.93G/9.94G [01:18<00:00, 127MB/s]
Processed prompts:   0%|                                                                                                  | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/nfs_users/users/luis.lorenzo/code/vllm/benchmarks/benchmark_throughput.py", line 439, in <module>
[rank0]:     main(args)
[rank0]:   File "/nfs_users/users/luis.lorenzo/code/vllm/benchmarks/benchmark_throughput.py", line 227, in main
[rank0]:     elapsed_time = run_vllm(
[rank0]:                    ^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/code/vllm/benchmarks/benchmark_throughput.py", line 127, in run_vllm
[rank0]:     llm.generate(prompts, sampling_params, use_tqdm=True)
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/utils.py", line 795, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 309, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 561, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 861, in step
[rank0]:     output = self.model_executor.execute_model(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/executor/cpu_executor.py", line 78, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 235, in execute_model
[rank0]:     self.model_runner.prepare_model_input(
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/worker/cpu_model_runner.py", line 327, in prepare_model_input
[rank0]:     ) = self._prepare_prompt(seq_group_metadata_list)
[rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/worker/cpu_model_runner.py", line 202, in _prepare_prompt
[rank0]:     attn_metadata = self.attn_backend.make_metadata(
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/nfs_users/users/luis.lorenzo/anaconda3/envs/vllm_311/lib/python3.11/site-packages/vllm/attention/backends/abstract.py", line 29, in make_metadata
[rank0]:     return cls.get_metadata_cls()(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: TypeError: XFormersMetadata.__init__() got an unexpected keyword argument 'is_prompt'
Processed prompts:   0%|                                                                                                  | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Command exited with non-zero status 1
```

Originally I got this error with flash attention as attn backend, but then I played with different versions of vllm and flash, and eventually uninstalled it, and same issue. Error was: ``` TypeError: FlashAttentionMetadata.__init__() got an unexpected keyword argument 'is_prompt'``` 

I've also tried with other vllm-enabled models, same issue.
I've pulled latest main to get updated version of /benchmark_throughput.py, same issue.

My main guess is atm that cpu_model_runner.py and model_runner.py have diverged when calling "attn_metadata = self.attn_backend.make_metadata(" , somehow, somewhere the "is_prompt" kwarg was removed for GPU but not for CPU.
I've looked a bit at the code but does not seem to be a trivial fix, so I'll let someone with more experience/time to look into this.

**Comment by husimplicity** [comment]
Encountered the same issue

**Comment by dnesting-usa** [comment]
I'm not positive but I believe this was introduced in
https://github.com/vllm-project/vllm/commit/65bf2ac165734fb6339210c4b2b8ce68d2391b77#diff-f81ae2354d4f46c8591a009289e97ab465771d5593feb114539f7cdc58486663L159

Looks like some refactoring occurred here, removing `is_prompt` but missing an occurrence in `cpu_model_runner.py`.  I found this issue seeing CPU inferencing failing in recent versions of vllm.  Reverting to **0.4.2** (before this change) may fix the issue.

cc @rkooo567 as the author of that change

**Comment by anencore94** [comment]
I've encountered same issue. when I run following command in vllm gpu backend.
```
VLLM_CPU_KVCACHE_SPACE=16 python benchmarks/benchmark_throughput.py --model mosaicml/mpt-7b --input-len 128 --output-len 512 --trust-remote-code --backend=vllm  --device cpu --dtype bfloat16
```
- with `--device cpu`

my vllm environments was built from source with editable package mode from the main branch.(`pip install -e .`)

Here's what I've found.

### Problem: Mismatch Between `vllm` Package and Device Type in Backend Selection

- The issue arises because the `vllm` package has separate Python packages for GPU and CPU versions.
- In the execution flow (`LLMEngine -> _get_executor_cls -> CPUExecutor -> CPUWorker -> CPU Model Runner -> get_attn_backend`), the `get_attn_backend` function determines the backend based on whether the `vllm` package is compiled for CPU or GPU, rather than checking the runtime `device_type`.
- This causes the **incorrect attention backend to be selected** if the `vllm` package is GPU-based, even when the CPUExecutor is being used.

### Proposed Solution

- It seems that if the `vllm` package is GPU-based, the `CPUExecutor` should not be invoked at all. But I'm not sure when to raise an error if we should do.
- Should `_get_executor_cls` raise an exception when `utils.is_cpu`, `utils.is_openvino`, etc., do not match the expected device type?
- What’s the best approach to handle this mismatch? I'm not sure, but I could run an api_server with device=cpu even the vllm package was not built as cpu backend. So I think we could select another attention backend to support 'device_type'.

WDYT @WoosukKwon ?

**Comment by khayamgondal** [comment]
Facing the same issue on aarch64 GH200. Anyone found a solution?

**Comment by diegolovison** [comment]
Same problem here.

**Comment by zoobab** [comment]
Having the same issue running the vLLM quickstart:

https://docs.vllm.ai/en/latest/getting_started/quickstart.html

Server side:
```
$ pip freeze | grep vllm
vllm==0.6.2
$ vllm serve facebook/opt-125m --port 19000 --device=cpu
WARNING 10-09 13:39:15 _custom_ops.py:18] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
INFO 10-09 13:39:18 api_server.py:526] vLLM API server version 0.6.1.dev238+ge2c6e0a82
INFO 10-09 13:39:18 api_server.py:527] args: Namespace(model_tag='facebook/opt-125m', config='', host=None, port=19000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, model='facebook/opt-125m', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', config_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='cpu', num_scheduler_steps=1, multi_step_stream_outputs=False, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, override_neuron_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, dispatch_function=<function serve at 0x7f5465743100>)
INFO 10-09 13:39:18 api_server.py:164] Multiprocessing frontend to use ipc:///tmp/dd121139-39fa-4aa3-9938-14bb207b8ad5 for IPC Path.
INFO 10-09 13:39:18 api_server.py:177] Started engine process with PID 18298
WARNING 10-09 13:39:18 config.py:376] Async output processing is only supported for CUDA or TPU. Disabling it for other platforms.
WARNING 10-09 13:39:20 _custom_ops.py:18] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
WARNING 10-09 13:39:23 config.py:376] Async output processing is only supported for CUDA or TPU. Disabling it for other platforms.
INFO 10-09 13:39:23 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='facebook/opt-125m', speculative_config=None, tokenizer='facebook/opt-125m', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=facebook/opt-125m, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=False, use_cached_outputs=True, mm_processor_kwargs=None)
WARNING 10-09 13:39:24 cpu_executor.py:325] float16 is not supported on CPU, casting to bfloat16.
WARNING 10-09 13:39:24 cpu_executor.py:328] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 10-09 13:39:24 cpu_executor.py:354] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
INFO 10-09 13:39:24 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 10-09 13:39:24 selector.py:116] Using XFormers backend.
/home/users/g33234/mnt/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/users/g33234/mnt/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
INFO 10-09 13:39:24 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 10-09 13:39:24 selector.py:116] Using XFormers backend.
INFO 10-09 13:39:24 weight_utils.py:242] Using model weights format ['*.bin']
Loading pt checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
/home/users/g33234/mnt/vllm/model_executor/model_loader/weight_utils.py:424: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(bin_file, map_location="cpu")
Loading pt checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.58it/s]
Loading pt checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.58it/s]

INFO 10-09 13:39:25 cpu_executor.py:212] # CPU blocks: 7281
INFO 10-09 13:39:25 api_server.py:230] vLLM to use /tmp/tmp3tv6jwir as PROMETHEUS_MULTIPROC_DIR
WARNING 10-09 13:39:25 serving_embedding.py:189] embedding_mode is False. Embedding API will not work.
INFO 10-09 13:39:25 launcher.py:19] Available routes are:
INFO 10-09 13:39:25 launcher.py:27] Route: /openapi.json, Methods: GET, HEAD
INFO 10-09 13:39:25 launcher.py:27] Route: /docs, Methods: GET, HEAD
INFO 10-09 13:39:25 launcher.py:27] Route: /docs/oauth2-redirect, Methods: GET, HEAD
INFO 10-09 13:39:25 launcher.py:27] Route: /redoc, Methods: GET, HEAD
INFO 10-09 13:39:25 launcher.py:27] Route: /health, Methods: GET
INFO 10-09 13:39:25 launcher.py:27] Route: /tokenize, Methods: POST
INFO 10-09 13:39:25 launcher.py:27] Route: /detokenize, Methods: POST
INFO 10-09 13:39:25 launcher.py:27] Route: /v1/models, Methods: GET
INFO 10-09 13:39:25 launcher.py:27] Route: /version, Methods: GET
INFO 10-09 13:39:25 launcher.py:27] Route: /v1/chat/completions, Methods: POST
INFO 10-09 13:39:25 launcher.py:27] Route: /v1/completions, Methods: POST
INFO 10-09 13:39:25 launcher.py:27] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [18243]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:19000 (Press CTRL+C to quit)
INFO 10-09 13:39:29 logger.py:36] Received request cmpl-5492fc90431549e5bc4cdce6242a5fe1-0: prompt: 'San Francisco is a', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=7, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [2, 16033, 2659, 16, 10], lora_request: None, prompt_adapter_request: None.
INFO 10-09 13:39:29 engine.py:288] Added request cmpl-5492fc90431549e5bc4cdce6242a5fe1-0.
ERROR 10-09 13:39:29 engine.py:157] TypeError("XFormersMetadata.__init__() got an unexpected keyword argument 'is_prompt'")
ERROR 10-09 13:39:29 engine.py:157] Traceback (most recent call last):
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/engine/multiprocessing/engine.py", line 155, in start
ERROR 10-09 13:39:29 engine.py:157]     self.run_engine_loop()
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/engine/multiprocessing/engine.py", line 218, in run_engine_loop
ERROR 10-09 13:39:29 engine.py:157]     request_outputs = self.engine_step()
ERROR 10-09 13:39:29 engine.py:157]                       ^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/engine/multiprocessing/engine.py", line 236, in engine_step
ERROR 10-09 13:39:29 engine.py:157]     raise e
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/engine/multiprocessing/engine.py", line 227, in engine_step
ERROR 10-09 13:39:29 engine.py:157]     return self.engine.step()
ERROR 10-09 13:39:29 engine.py:157]            ^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/engine/llm_engine.py", line 1264, in step
ERROR 10-09 13:39:29 engine.py:157]     outputs = self.model_executor.execute_model(
ERROR 10-09 13:39:29 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/executor/cpu_executor.py", line 227, in execute_model
ERROR 10-09 13:39:29 engine.py:157]     output = self.driver_method_invoker(self.driver_worker,
ERROR 10-09 13:39:29 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/executor/cpu_executor.py", line 377, in _driver_method_invoker
ERROR 10-09 13:39:29 engine.py:157]     return getattr(driver, method)(*args, **kwargs)
ERROR 10-09 13:39:29 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/worker_base.py", line 303, in execute_model
ERROR 10-09 13:39:29 engine.py:157]     inputs = self.prepare_input(execute_model_req)
ERROR 10-09 13:39:29 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/worker_base.py", line 291, in prepare_input
ERROR 10-09 13:39:29 engine.py:157]     return self._get_driver_input_and_broadcast(execute_model_req)
ERROR 10-09 13:39:29 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/worker_base.py", line 253, in _get_driver_input_and_broadcast
ERROR 10-09 13:39:29 engine.py:157]     self.model_runner.prepare_model_input(
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/cpu_model_runner.py", line 494, in prepare_model_input
ERROR 10-09 13:39:29 engine.py:157]     model_input = self._prepare_model_input_tensors(
ERROR 10-09 13:39:29 engine.py:157]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/cpu_model_runner.py", line 482, in _prepare_model_input_tensors
ERROR 10-09 13:39:29 engine.py:157]     return builder.build()  # type: ignore
ERROR 10-09 13:39:29 engine.py:157]            ^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/cpu_model_runner.py", line 130, in build
ERROR 10-09 13:39:29 engine.py:157]     multi_modal_kwargs) = self._prepare_prompt(
ERROR 10-09 13:39:29 engine.py:157]                           ^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/worker/cpu_model_runner.py", line 265, in _prepare_prompt
ERROR 10-09 13:39:29 engine.py:157]     attn_metadata = self.attn_backend.make_metadata(
ERROR 10-09 13:39:29 engine.py:157]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157]   File "/home/users/g33234/mnt/vllm/attention/backends/abstract.py", line 47, in make_metadata
ERROR 10-09 13:39:29 engine.py:157]     return cls.get_metadata_cls()(*args, **kwargs)
ERROR 10-09 13:39:29 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-09 13:39:29 engine.py:157] TypeError: XFormersMetadata.__init__() got an unexpected keyword argument 'is_prompt'
INFO:     127.0.0.1:50282 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
```

Client side:
```
$ cat sf.sh 
#!/bin/bash
curl http://localhost:19000/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "facebook/opt-125m",
"prompt": "San Francisco is a",
"max_tokens": 7,
"temperature": 0
}'
$ ./sf.sh
Internal Server Error
```

If the option ```device=cpu```, there also should not be a WARNING about trying to load CUDA.

**Comment by d2461795341** [comment]
Try to use gpu for inference, I have the same problem with cpu but it works fine with gpu.

**Comment by anencore94** [comment]
> Facing the same issue on aarch64 GH200. @anencore94 did you find a solution? I just want to run benchmark_throughput with cpu

I just use vllm-cpu installed environment for cpu benchmark, and vllm-gpu(which is the default vllm) for gpu benchmark. @khayamgondal

**Comment by DenisDiachkov** [comment]
Any solution for normal vllm?

**Comment by zhuangqh** [comment]
Same problem here.

**Comment by zzw0307** [comment]
May I ask if this issue has been resolved, OP? I have also encountered the same problem

**Comment by dreamerkr** [comment]
May I ask if this issue has been resolved, OP? I have also encountered the same problem

**Comment by Abirdcfly** [comment]
just use prebuild docker images, encounter same problem here:

```bash
docker run -v $PWD/tmp/:/tmp/abcd -p 8000:8000 --ipc=host  vllm/vllm-openai:v0.6.3.post1   --model /tmp/abcd/Llama-3.2-1B --device cpu --served-model-name meta-llama/Llama-3.2-1B
```

 
```
 curl http://localhost:8000/v1/completions -H "Content-Type: application/json" \
    -d '{
        "model": "meta-llama/Llama-3.2-1B",
        "prompt": "San Francisco is a",
        "max_tokens": 7,
        "temperature": 0
```

**Comment by cdoern** [comment]
seeing same issue. Is x86 support broken?

**Comment by juburr** [comment]
I'm seeing the exact same issue.

The solution for me was to follow the CPU installation instructions: https://docs.vllm.ai/en/latest/getting_started/cpu-installation.html

I guess I was under the false assumption that the primary installation method would handle both CPU & GPU mode and allow you to switch between them using the `--device` flag. In an ideal world I'd love to have a single deployable application that works in both environments.
