### ISSUE TITLE
Baichuan-7B can't be loaded by vllm

### ISSUE THREAD

**Issue by caiyesd** [vllm-project/vllm#624]
Hi, I'm a biginner to vllm. And  I'm trying to use vllm to load Baichuan-7B, but meet this issue.

```
(venv) user@rtx4090x8:~/tonghu/vllm$ python -m vllm.entrypoints.api_server --model /huggingface.co/baichuan-inc/Baichuan-7B --host 0.0.0.0 --port 9000
INFO 07-31 15:39:30 llm_engine.py:60] Initializing an LLM engine with config: model='/huggingface.co/baichuan-inc/Baichuan-7B', tokenizer='/huggingface.co/baichuan-inc/Baichuan-7B', tokenizer_mode=auto, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/tonghu/vllm/venv/lib/python3.8/site-packages/vllm/entrypoints/api_server.py", line 78, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/user/tonghu/vllm/venv/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/user/tonghu/vllm/venv/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/home/user/tonghu/vllm/venv/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 80, in __init__
    self.tokenizer = get_tokenizer(
  File "/home/user/tonghu/vllm/venv/lib/python3.8/site-packages/vllm/transformers_utils/tokenizer.py", line 34, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name, *args,
  File "/home/user/tonghu/vllm/venv/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 699, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class BaiChuanTokenizer does not exist or is not currently imported.
```

I also tried it with llama2-7b-chat, it works well.
```
(venv) user@rtx4090x8:~/tonghu/vllm$ python -m vllm.entrypoints.api_server --model /huggingface.co/meta-llama/Llama-2-7b-chat-hf --host 0.0.0.0 --port 9000
INFO 07-31 15:42:33 llm_engine.py:60] Initializing an LLM engine with config: model='/huggingface.co/meta-llama/Llama-2-7b-chat-hf', tokenizer='/huggingface.co/meta-llama/Llama-2-7b-chat-hf', tokenizer_mode=auto, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 07-31 15:42:33 tokenizer.py:28] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 07-31 15:42:43 llm_engine.py:131] # GPU blocks: 1039, # CPU blocks: 512
INFO:     Started server process [30016]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
```

Can anyone help me? Thanks in advance. :-)

**Comment by mklf** [comment]
try append `--trust-remote-code` to the command

note: support for  `--trust-remote-code`  is still on main branch

**Comment by caiyesd** [comment]
@mklf Thank you.
