### ISSUE TITLE
Speculative decoding leads to zombie requests

### ISSUE THREAD

**Issue by naturomics** [vllm-project/vllm#6294]
### Anything you want to discuss about vllm.

when turns on speculative decoding, the openai api server failed on concurrent requests, raising error `exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup`. After all requests finish, there are some zombie tasks in the queue (**Running: 54 reqs**):
```
Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 54 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 47.4%, CPU KV cache usage: 0.0%
```
but the gpu utilization always is zero, and new request reports `Internal Server Error`. This does not happen when turns off speculative decoding.

To reproduce the problem:
- vllm: 0.5.1
- docker image: nvidia/cuda:12.4.1-base-ubuntu22.04

1. Concurrent test:
```
python3 benchmarks/benchmark_serving.py \
    --backend openai-chat  \
    --endpoint "/chat/completions"  \
    --model qwen-14b-chat  \
    --base-url http://[ip]:8000/v1  \
    --dataset ShareGPT_V3_unfiltered_cleaned_split.json  \
    --request-rate 5  \
    --save-result  \
    --tokenizer /mnt/data/Qwen1.5-14B-Chat/
```

2. OpenAI API server
- without speculative decoding:
```
python3 -m vllm.entrypoints.openai.api_server \
     --served-model-name 'qwen-14b-chat'    \
     --max-model-len=4096  \
     --port=8000  \
     --dtype=half  \
     --model=Qwen1.5-14B-Chat \
     --tensor-parallel-size 2 \
     --use-v2-block-manager  \
     --gpu-memory-utilization 0.95
```

- with speculative decoding:
```
python3 -m vllm.entrypoints.openai.api_server \
     --served-model-name 'qwen-14b-chat'    \
     --max-model-len=4096  \
     --port=8000  \
     --dtype=half  \
     --model=Qwen1.5-14B-Chat \
     --tensor-parallel-size 2 \
     --use-v2-block-manager  \
     --speculative-model='[ngram]'  \  # can be reproduced on others draft models, such as Qwen1.5-0.5B-Chat
     --num-speculative-tokens 5  \
     --ngram-prompt-lookup-max 4  \
     --gpu-memory-utilization 0.95
```

The full traceback:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
    await self.message_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fd115dfdf00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 258, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
    raise BaseExceptionGroup(
exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
```

**Comment by Raphael-Jin** [comment]
Find the same issue. Any suggestion?

**Comment by cadedaniel** [comment]
Can you share the full failure log?

**Comment by Raphael-Jin** [comment]
Just found the solution to my problem, in my case, I used the `ibm-fms/llama3-70b-accelerator` , since there is no "max_seq_len" in the config.yaml, so vLLM assume the input length to be 2048, when I give a input that has length > 2048, the vLLM panic but never able to restore the correct state (Zombie Request). After I indicate the "max_seq_len" in the config.yaml in `ibm-fms/llama3-70b-accelerator`, it solved the problem.

Just fyi my error output (Zombie state).

```
    return await self.driver_exec_model(execute_model_req)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 375, in execute_model
    return self._run_speculative_decoding_step(execute_model_req,
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 538, in _run_speculative_decoding_step
    accepted_token_ids, target_logprobs = self._verify_tokens(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 634, in _verify_tokens
    hidden_states = hidden_states.reshape(-1, max_proposal_len + 1,
RuntimeError: shape '[-1, 5, 8192]' is invalid for input of size 8192

  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 772, in generate
    async for output in self._process_request(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 873, in _process_request
    stream = await self.add_request(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 676, in add_request
    self.start_background_loop()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 516, in start_background_loop
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Background loop has errored already.
```
