### ISSUE TITLE
[Bug]: Server fails to boot due to a tensor size mismatch when LoRA is enabled for GPTBigCode

### ISSUE THREAD

**Issue by tjohnson31415** [vllm-project/vllm#6314]
### Your current environment

```
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.46.1.el8_6.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
  MIG 3g.40gb     Device  0:

Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Vendor ID:                       GenuineIntel
Model name:                      Intel Xeon Processor (Icelake)
CPU family:                      6
Model:                           134
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
Stepping:                        0
BogoMIPS:                        5600.03
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid fsrm md_clear arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       2.5 MiB (80 instances)
L1i cache:                       2.5 MiB (80 instances)
L2 cache:                        160 MiB (40 instances)
L3 cache:                        32 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-39
NUMA node1 CPU(s):               40-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flashinfer==0.0.8+cu121torch2.3
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] torchvision==0.18.0
[pip3] transformers==4.42.3
[pip3] triton==2.3.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     40-79   1               N/A
NIC0    SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
```

### 🐛 Describe the bug

vLLM fails to boot with `--enable-lora` for the `bigcode/gpt_bigcode-santacoder` model due to a tensor size mismatch error encountered during the KV Cache initialization when attempting to use dummy LoRAs to probe the memory usage.

Simple reproduction using the image `docker.io/vllm/vllm-openai@sha256:e58fceffa6f8d3e4d535f9e7128361cd33469b232a8dc670967b62ae62bac5fe`:
```bash
python3 -m vllm.entrypoints.openai.api_server --model bigcode/gpt_bigcode-santacoder --enable-lora
```

Logs and Stacktrace:
```
INFO 07-10 17:13:54 api_server.py:206] vLLM API server version 0.5.1
INFO 07-10 17:13:54 api_server.py:207] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='bigcode/gpt_bigcode-santacoder', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=True, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 07-10 17:13:54 config.py:1350] Downcasting torch.float32 to torch.float16.
INFO 07-10 17:13:54 llm_engine.py:169] Initializing an LLM engine (v0.5.1) with config: model='bigcode/gpt_bigcode-santacoder', speculative_config=None, tokenizer='bigcode/gpt_bigcode-santacoder', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=bigcode/gpt_bigcode-santacoder, use_v2_block_manager=False, enable_prefix_caching=False)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
DEBUG 07-10 17:13:55 parallel_state.py:799] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.128.2.116:33103 backend=nccl
INFO 07-10 17:13:55 weight_utils.py:218] Using model weights format ['*.safetensors', '*.bin', '*.pt']
INFO 07-10 17:13:56 model_runner.py:255] Loading model weights took 2.0967 GB
DEBUG 07-10 17:13:56 models.py:784] Adding lora. Model id: 1, int id: 1, scaling factor: 1
DEBUG 07-10 17:13:57 models.py:488] Activating LoRA. int id: 1, slot index: 0
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 216, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 431, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 360, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 507, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 256, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 353, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 76, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 173, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 874, in profile_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1189, in execute_model
[rank0]:     self.set_active_loras(model_input.lora_requests,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 887, in set_active_loras
[rank0]:     self.lora_manager.set_active_loras(lora_requests, lora_mapping)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/lora/worker_manager.py", line 138, in set_active_loras
[rank0]:     self._apply_loras(lora_requests)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/lora/worker_manager.py", line 270, in _apply_loras
[rank0]:     self.add_lora(lora)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/lora/worker_manager.py", line 285, in add_lora
[rank0]:     self._lora_manager.activate_lora(lora_request.lora_int_id)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/lora/models.py", line 804, in activate_lora
[rank0]:     result = super().activate_lora(lora_id)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/lora/models.py", line 495, in activate_lora
[rank0]:     module.set_lora(index, module_lora.lora_a, module_lora.lora_b,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/lora/layers.py", line 1148, in set_lora
[rank0]:     self.lora_a_stacked[index,
[rank0]: RuntimeError: The size of tensor a (2048) must match the size of tensor b (49536) at non-singleton dimension 1
```

**Comment by tjohnson31415** [comment]
From my investigation, it seems that there is a mismatch between the dummy lora tensors and the "stacked" tensors used in `LogitsProcessorWithLoRA`:
```
lora_a torch.Size([49536, 8])
lora_a_stacked torch.Size([1, 1, 16, 2048])

lora_b torch.Size([8, 2048])
lora_b_stacked torch.Size([1, 1, 49664, 16])
```

Maybe this mismatch has something to do with GPTBigCode using tied weights between the `wte` and `lm_head` modules:
https://github.com/vllm-project/vllm/blob/79d406e9183aa12cdef6f1876eb9a15385662587/vllm/model_executor/models/gpt_bigcode.py#L262

**Comment by robertgshaw2-neuralmagic** [comment]
Do you know if this was working on v0.5.0?

**Comment by tjohnson31415** [comment]
We think that it was "working" in v0.5.0 in the sense that the server would boot up, but this may have surfaced a latent issue. @prashantgupta24 Found that the shape mismatch Runtime error surfaced after https://github.com/vllm-project/vllm/pull/4442, the relevant diff being:

```diff
-        self.lm_head_weight = self.transformer.wte.weight
+        self.lm_head = self.transformer.wte
```
https://github.com/vllm-project/vllm/pull/4442/files#diff-22e64a69e7f0e8ae5ad16a561cbd1e4b0583e87e3733cbbd5712c4cb779af882R262

Before that change, I don't think LoRA adaptation of `lm_head` worked though since there was no `lm_head` module before. 🤔
After that change, we now have an `lm_head` module so the dummy lora is generated with an `lm_head` module which then leads to the error.

**Comment by robertgshaw2-neuralmagic** [comment]
I see. `GPTBigCode` uses tied embeddings in vLLM, so I think we should remove `lm_head` from `supported_lora_modules` then

Does your model have LORA adapters on the LM Head and the Vocab?

**Comment by maxdebayser** [comment]
The presence of `lm_head` in `supported_lora_modules` is what triggers  the replacement of the `LogitsProcessor` with `LogitsProcessorWithLoRA` [here](https://github.com/vllm-project/vllm/blob/99ded1e1c4dc00baa77beae74602ebafe4921176/vllm/lora/models.py#L587). Perhaps the `logits_processor` should be in the `supported_lora_modules` instead.

In the case of `GPTBigCode`, the presence of `lm_head` in `supported_lora_modules` and the fact that `lm_head` is `VocabParallelEmbedding` causes its replacement with `VocabParallelEmbeddingWithLoRA`. But perhaps this class was never meant to be used as an `lm_head`. I don't think it makes sense to have lora adapters both in the `lm_head` and the `logits_processor`.
