### ISSUE TITLE
[Bug]: VLLM 0.5.1 with LLaVA 1.6 exceptions

### ISSUE THREAD

**Issue by andrePankraz** [vllm-project/vllm#6322]
### Your current environment

See https://github.com/vllm-project/vllm/issues/6176

### 🐛 Describe the bug

I have lots of image, where the service throws exception and after that must be restarted, because it stucks in exception mode, even for images, that worked before.
Example image below.

```
curl 'https://ai1.dev.init/multimodal-llava/v1/chat/completions' -k -H 'Content-Type: application/json' -d @- <<EOF
{
    "model": "llava-hf/llava-v1.6-mistral-7b-hf",
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "data:image/jpeg;base64,$(base64 -w 0 /opt/initai_copilot/data/images/image2015-7-20_16_17_54.png)"
                    }
                },
                {
                    "type": "text",
                    "text": "Was ist in dem Bild?"
                }
            ]
        }
    ],
    "temperature": 0.2,
    "top_p": 0.1,
    "top_k": 20,
    "frequency_penalty": 0.2
}
EOF
```

Image:
![image2015-7-20_16_17_54](https://github.com/vllm-project/vllm/assets/2312884/7cde0c86-0b25-4b78-b662-129d584f4f8c)

Exception

```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 07-11 06:04:31 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%.
INFO 07-11 06:04:36 metrics.py:295] Avg prompt throughput: 208.2 tokens/s, Avg generation throughput: 6.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.0%, CPU KV cache usage: 0.0%.
INFO 07-11 06:04:42 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.1%, CPU KV cache usage: 0.0%.
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop: Attempted to assign 776 = 776 image tokens to 826 placeholders, Traceback (most recent call last):
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 64, in start_worker_execution_loop
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     output = self.execute_model(execute_model_req=None)
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 271, in execute_model
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     output = self.model_runner.execute_model(
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1243, in execute_model
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llava_next.py", line 494, in forward
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     inputs_embeds = merge_vision_embeddings(
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/utils.py", line 35, in merge_vision_embeddings
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]     raise ValueError(
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226] ValueError: Attempted to assign 776 = 776 image tokens to 826 placeholders
(VllmWorkerProcess pid=76) ERROR 07-11 06:04:42 multiproc_worker_utils.py:226]
ERROR 07-11 06:04:42 async_llm_engine.py:53] Engine background task failed
ERROR 07-11 06:04:42 async_llm_engine.py:53] Traceback (most recent call last):
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 43, in _log_task_completion
ERROR 07-11 06:04:42 async_llm_engine.py:53]     return_value = task.result()
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 595, in run_engine_loop
ERROR 07-11 06:04:42 async_llm_engine.py:53]     result = task.result()
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 540, in engine_step
ERROR 07-11 06:04:42 async_llm_engine.py:53]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 241, in step_async
ERROR 07-11 06:04:42 async_llm_engine.py:53]     output = await self.model_executor.execute_model_async(
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/distributed_gpu_executor.py", line 173, in execute_model_async
ERROR 07-11 06:04:42 async_llm_engine.py:53]     return await self._driver_execute_model_async(execute_model_req)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 160, in _driver_execute_model_async
ERROR 07-11 06:04:42 async_llm_engine.py:53]     return await self.driver_exec_model(execute_model_req)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 07-11 06:04:42 async_llm_engine.py:53]     result = self.fn(*self.args, **self.kwargs)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 271, in execute_model
ERROR 07-11 06:04:42 async_llm_engine.py:53]     output = self.model_runner.execute_model(
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 07-11 06:04:42 async_llm_engine.py:53]     return func(*args, **kwargs)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1243, in execute_model
ERROR 07-11 06:04:42 async_llm_engine.py:53]     hidden_or_intermediate_states = model_executable(
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 07-11 06:04:42 async_llm_engine.py:53]     return self._call_impl(*args, **kwargs)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 07-11 06:04:42 async_llm_engine.py:53]     return forward_call(*args, **kwargs)
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llava_next.py", line 494, in forward
ERROR 07-11 06:04:42 async_llm_engine.py:53]     inputs_embeds = merge_vision_embeddings(
ERROR 07-11 06:04:42 async_llm_engine.py:53]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/utils.py", line 35, in merge_vision_embeddings
ERROR 07-11 06:04:42 async_llm_engine.py:53]     raise ValueError(
ERROR 07-11 06:04:42 async_llm_engine.py:53] ValueError: Attempted to assign 776 = 776 image tokens to 826 placeholders
Exception in callback functools.partial(<function _log_task_completion at 0x7d88c3437880>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7d88ab11c1f0>>)
handle: <Handle functools.partial(<function _log_task_completion at 0x7d88c3437880>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7d88ab11c1f0>>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 43, in _log_task_completion
    return_value = task.result()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 595, in run_engine_loop
    result = task.result()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 540, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 241, in step_async
    output = await self.model_executor.execute_model_async(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/distributed_gpu_executor.py", line 173, in execute_model_async
    return await self._driver_execute_model_async(execute_model_req)
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 160, in _driver_execute_model_async
    return await self.driver_exec_model(execute_model_req)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 271, in execute_model
    output = self.model_runner.execute_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1243, in execute_model
    hidden_or_intermediate_states = model_executable(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llava_next.py", line 494, in forward
    inputs_embeds = merge_vision_embeddings(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/utils.py", line 35, in merge_vision_embeddings
    raise ValueError(
ValueError: Attempted to assign 776 = 776 image tokens to 826 placeholders

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 55, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause.
INFO:     192.168.6.1:46738 - "POST /v1/chat/completions HTTP/1.0" 400 Bad Request
```

Config of Docker image:

```
services:
  vllm-llava:
    image: vllm/vllm-openai:v0.5.1
    container_name: vllm-llava
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    environment:
      - HTTPS_PROXY=http://proxy.dev.init:3128
      - HTTP_PROXY=http://proxy.dev.init:3128
      - NO_PROXY=10.9.240.0/22,127.0.0.0/8
      - NVIDIA_VISIBLE_DEVICES=2,3
      - HF_TOKEN=$HF_TOKEN
      - VLLM_NO_USAGE_STATS=1
    volumes:
      - /mnt/sda/huggingface:/root/.cache/huggingface
      - .:/opt/vllm
    ports:
      - "8003:8000"
    command:
      - --model=llava-hf/llava-v1.6-mistral-7b-hf
      # - --chat-template=/opt/vllm/template_mixtral.jinja
      # - --max-model-len=24576
      - --tensor-parallel-size=2
      # - --swap-space=5
      - --gpu-memory-utilization=0.3
      # - --max-num-batched-tokens=2048
      - --disable-log-requests
      - --enforce-eager
      # - --enable-chunked-prefill
    restart: unless-stopped

```

**Comment by DarkLight1337** [comment]
I'm able to repro this locally. Seems that there is *still* some problem with the feature size calculation...
