### ISSUE TITLE
when i set tensor_parallel_size>1(A100 * 4), it does not work

### ISSUE THREAD

**Issue by cx-hub** [vllm-project/vllm#6407]
### Your current environment

```text
WARNING 07-13 11:30:05 ray_utils.py:46] Failed to import Ray with ModuleNotFoundError("No module named 'ray'"). For multi-node inference, please install Ray with `pip install ray`.
PyTorch version: 2.3.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.17

Python version: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.114.2.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe

Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                52
On-line CPU(s) list:   0-51
Thread(s) per core:    1
Core(s) per socket:    52
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:              6
CPU MHz:               2599.998
BogoMIPS:              5199.99
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-51
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq md_clear spec_ctrl intel_stibp arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.3.0
[pip3] torchaudio==2.3.0
[pip3] torchvision==0.18.0
[pip3] transformers==4.42.4
[pip3] triton==2.3.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.8            py39h5eee18b_0  
[conda] mkl_random                1.2.4            py39hdb19cb5_0  
[conda] numpy                     1.26.4           py39h5f9d8c6_0  
[conda] numpy-base                1.26.4           py39hb5e798b_0  
[conda] pytorch                   2.3.0           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.3.0                py39_cu118    pytorch
[conda] torchtriton               2.3.0                      py39    pytorch
[conda] torchvision               0.18.0               py39_cu118    pytorch
[conda] transformers              4.42.4                   pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity
GPU0	 X 	PHB	PHB	PHB	0-51		N/A
GPU1	PHB	 X 	NV4	PIX	0-51		N/A
GPU2	PHB	NV4	 X 	PIX	0-51		N/A
GPU3	PHB	PIX	PIX	 X 	0-51		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### 🐛 Describe the bug

when i set tensor_parallel_size = 2 and run:
```python
llm = LLM(model=the_path, gpu_memory_utilization=0.8, tensor_parallel_size = 2)
```

the error is :
```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/miniconda/envs/vllama/lib/python3.9/runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/miniconda/envs/vllama/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/miniconda/envs/vllama/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/llama3/mybench/mbxp/my_vllm.py", line 19, in <module>
    llm = LLM(model=the_path, gpu_memory_utilization=0.8, tensor_parallel_size = 2)
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 144, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 363, in from_engine_args
    engine = cls(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 223, in __init__
    self.model_executor = executor_class(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 41, in __init__
    self._init_executor()
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 48, in _init_executor
    self.workers = [
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 49, in <listcomp>
    ProcessWorkerWrapper(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 162, in __init__
    self.process.start()
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
ERROR 07-13 11:38:53 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 44025 died, exit code: 1
INFO 07-13 11:38:53 multiproc_worker_utils.py:123] Killing local vLLM worker processes
INFO 07-13 11:38:55 selector.py:169] Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 07-13 11:38:55 selector.py:51] Using XFormers backend.
Traceback (most recent call last):
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 169, in _enqueue_task
    self._task_queue.put((task_id, method, args, kwargs))
  File "/miniconda/envs/vllama/lib/python3.9/multiprocessing/queues.py", line 88, in put
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x7fc13cdf2fa0> is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/llama3/mybench/mbxp/my_vllm.py", line 19, in <module>
    llm = LLM(model=the_path, gpu_memory_utilization=0.8, tensor_parallel_size = 2)
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 144, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 363, in from_engine_args
    engine = cls(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 223, in __init__
    self.model_executor = executor_class(
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 41, in __init__
    self._init_executor()
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 65, in _init_executor
    self._run_workers("init_device")
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 109, in _run_workers
    worker_outputs = [
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 110, in <listcomp>
    worker.execute_method(method, *args, **kwargs)
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 176, in execute_method
    self._enqueue_task(future, method, args, kwargs)
  File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 172, in _enqueue_task
    raise ChildProcessError("worker died") from e
ChildProcessError: worker died

```
and i run your test.py and get this:
```text
W0713 11:42:02.197802 140254060934976 torch/distributed/run.py:757] 
W0713 11:42:02.197802 140254060934976 torch/distributed/run.py:757] *****************************************
W0713 11:42:02.197802 140254060934976 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0713 11:42:02.197802 140254060934976 torch/distributed/run.py:757] *****************************************
180:44748:44748 [0] NCCL INFO Bootstrap : Using eth0:20.0.0.180<0>
180:44748:44748 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
180:44748:44748 [0] NCCL INFO cudaDriverVersion 11070
NCCL version 2.20.5+cuda11.8
180:44748:44800 [0] NCCL INFO NET/IB : No device found.
180:44748:44800 [0] NCCL INFO NET/Socket : Using [0]eth0:20.0.0.180<0> [1]veth114677b:fe80::4d9:59ff:fe50:134a%veth114677b<0> [2]vethd7da57b:fe80::600c:7eff:fe11:3da3%vethd7da57b<0> [3]veth38498f4:fe80::5411:9bff:fe49:fdeb%veth38498f4<0> [4]veth9e303df:fe80::58ac:b2ff:fea9:48e0%veth9e303df<0> [5]veth14d30ca:fe80::7c26:67ff:fe44:d44%veth14d30ca<0>
180:44748:44800 [0] NCCL INFO Using non-device net plugin version 0
180:44748:44800 [0] NCCL INFO Using network Socket
180:44749:44749 [1] NCCL INFO cudaDriverVersion 11070
180:44749:44749 [1] NCCL INFO Bootstrap : Using eth0:20.0.0.180<0>
180:44749:44749 [1] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
180:44750:44750 [2] NCCL INFO cudaDriverVersion 11070
180:44750:44750 [2] NCCL INFO Bootstrap : Using eth0:20.0.0.180<0>
180:44750:44750 [2] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
180:44749:44815 [1] NCCL INFO NET/IB : No device found.
180:44750:44816 [2] NCCL INFO NET/IB : No device found.
180:44750:44816 [2] NCCL INFO NET/Socket : Using [0]eth0:20.0.0.180<0> [1]veth114677b:fe80::4d9:59ff:fe50:134a%veth114677b<0> [2]vethd7da57b:fe80::600c:7eff:fe11:3da3%vethd7da57b<0> [3]veth38498f4:fe80::5411:9bff:fe49:fdeb%veth38498f4<0> [4]veth9e303df:fe80::58ac:b2ff:fea9:48e0%veth9e303df<0> [5]veth14d30ca:fe80::7c26:67ff:fe44:d44%veth14d30ca<0>
180:44749:44815 [1] NCCL INFO NET/Socket : Using [0]eth0:20.0.0.180<0> [1]veth114677b:fe80::4d9:59ff:fe50:134a%veth114677b<0> [2]vethd7da57b:fe80::600c:7eff:fe11:3da3%vethd7da57b<0> [3]veth38498f4:fe80::5411:9bff:fe49:fdeb%veth38498f4<0> [4]veth9e303df:fe80::58ac:b2ff:fea9:48e0%veth9e303df<0> [5]veth14d30ca:fe80::7c26:67ff:fe44:d44%veth14d30ca<0>
180:44750:44816 [2] NCCL INFO Using non-device net plugin version 0
180:44750:44816 [2] NCCL INFO Using network Socket
180:44749:44815 [1] NCCL INFO Using non-device net plugin version 0
180:44749:44815 [1] NCCL INFO Using network Socket
180:44751:44751 [3] NCCL INFO cudaDriverVersion 11070
180:44751:44751 [3] NCCL INFO Bootstrap : Using eth0:20.0.0.180<0>
180:44751:44751 [3] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
180:44751:44817 [3] NCCL INFO NET/IB : No device found.
180:44751:44817 [3] NCCL INFO NET/Socket : Using [0]eth0:20.0.0.180<0> [1]veth114677b:fe80::4d9:59ff:fe50:134a%veth114677b<0> [2]vethd7da57b:fe80::600c:7eff:fe11:3da3%vethd7da57b<0> [3]veth38498f4:fe80::5411:9bff:fe49:fdeb%veth38498f4<0> [4]veth9e303df:fe80::58ac:b2ff:fea9:48e0%veth9e303df<0> [5]veth14d30ca:fe80::7c26:67ff:fe44:d44%veth14d30ca<0>
180:44751:44817 [3] NCCL INFO Using non-device net plugin version 0
180:44751:44817 [3] NCCL INFO Using network Socket
180:44751:44817 [3] NCCL INFO comm 0x6772e9d0 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId 2100 commId 0x163fb9f81ba1c307 - Init START
180:44749:44815 [1] NCCL INFO comm 0x68981d20 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 20e0 commId 0x163fb9f81ba1c307 - Init START
180:44750:44816 [2] NCCL INFO comm 0x6ad82480 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 20f0 commId 0x163fb9f81ba1c307 - Init START
180:44748:44800 [0] NCCL INFO comm 0x4eafbd20 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 110 commId 0x163fb9f81ba1c307 - Init START
180:44749:44815 [1] NCCL INFO comm 0x68981d20 rank 1 nRanks 4 nNodes 1 localRanks 4 localRank 1 MNNVL 0
180:44751:44817 [3] NCCL INFO comm 0x6772e9d0 rank 3 nRanks 4 nNodes 1 localRanks 4 localRank 3 MNNVL 0
180:44750:44816 [2] NCCL INFO comm 0x6ad82480 rank 2 nRanks 4 nNodes 1 localRanks 4 localRank 2 MNNVL 0
180:44748:44800 [0] NCCL INFO comm 0x4eafbd20 rank 0 nRanks 4 nNodes 1 localRanks 4 localRank 0 MNNVL 0
180:44751:44817 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
180:44750:44816 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
180:44748:44800 [0] NCCL INFO Channel 00/02 :    0   1   2   3
180:44750:44816 [2] NCCL INFO P2P Chunksize set to 524288
180:44751:44817 [3] NCCL INFO P2P Chunksize set to 524288
180:44748:44800 [0] NCCL INFO Channel 01/02 :    0   1   2   3
180:44748:44800 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
180:44748:44800 [0] NCCL INFO P2P Chunksize set to 524288
180:44749:44815 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
180:44749:44815 [1] NCCL INFO P2P Chunksize set to 524288
180:44750:44816 [2] NCCL INFO Channel 00 : 2[2] -> 3[3] via SHM/direct/direct
180:44748:44800 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct
180:44748:44800 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct
180:44751:44817 [3] NCCL INFO Channel 00 : 3[3] -> 0[0] via SHM/direct/direct
180:44749:44815 [1] NCCL INFO Channel 00/0 : 1[1] -> 2[2] via P2P/IPC/read
180:44750:44816 [2] NCCL INFO Channel 01 : 2[2] -> 3[3] via SHM/direct/direct
180:44751:44817 [3] NCCL INFO Channel 01 : 3[3] -> 0[0] via SHM/direct/direct
180:44749:44815 [1] NCCL INFO Channel 01/0 : 1[1] -> 2[2] via P2P/IPC/read
180:44748:44800 [0] NCCL INFO Connected all rings
180:44751:44817 [3] NCCL INFO Connected all rings
180:44750:44816 [2] NCCL INFO Connected all rings
180:44749:44815 [1] NCCL INFO Connected all rings
180:44751:44817 [3] NCCL INFO Channel 00 : 3[3] -> 2[2] via SHM/direct/direct
180:44751:44817 [3] NCCL INFO Channel 01 : 3[3] -> 2[2] via SHM/direct/direct
180:44749:44815 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct
180:44749:44815 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct
180:44750:44816 [2] NCCL INFO Channel 00/0 : 2[2] -> 1[1] via P2P/IPC/read
180:44750:44816 [2] NCCL INFO Channel 01/0 : 2[2] -> 1[1] via P2P/IPC/read
180:44751:44817 [3] NCCL INFO Connected all trees
180:44751:44817 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
180:44751:44817 [3] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
180:44748:44800 [0] NCCL INFO Connected all trees
180:44748:44800 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
180:44748:44800 [0] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
180:44750:44816 [2] NCCL INFO Connected all trees
180:44749:44815 [1] NCCL INFO Connected all trees
180:44750:44816 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
180:44750:44816 [2] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
180:44749:44815 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
180:44749:44815 [1] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
180:44749:44815 [1] NCCL INFO comm 0x68981d20 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 20e0 commId 0x163fb9f81ba1c307 - Init COMPLETE
180:44751:44817 [3] NCCL INFO comm 0x6772e9d0 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId 2100 commId 0x163fb9f81ba1c307 - Init COMPLETE
180:44748:44800 [0] NCCL INFO comm 0x4eafbd20 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 110 commId 0x163fb9f81ba1c307 - Init COMPLETE
180:44750:44816 [2] NCCL INFO comm 0x6ad82480 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 20f0 commId 0x163fb9f81ba1c307 - Init COMPLETE
180:44748:44822 [0] NCCL INFO [Service thread] Connection closed by localRank 0
180:44749:44826 [1] NCCL INFO [Service thread] Connection closed by localRank 1
180:44750:44820 [2] NCCL INFO [Service thread] Connection closed by localRank 2
180:44751:44821 [3] NCCL INFO [Service thread] Connection closed by localRank 3
180:44748:44862 [0] NCCL INFO comm 0x4eafbd20 rank 0 nranks 4 cudaDev 0 busId 110 - Abort COMPLETE
180:44751:44865 [0] NCCL INFO comm 0x6772e9d0 rank 3 nranks 4 cudaDev 3 busId 2100 - Abort COMPLETE
180:44749:44863 [0] NCCL INFO comm 0x68981d20 rank 1 nranks 4 cudaDev 1 busId 20e0 - Abort COMPLETE
180:44750:44864 [0] NCCL INFO comm 0x6ad82480 rank 2 nranks 4 cudaDev 2 busId 20f0 - Abort COMPLETE

```

**Comment by cx-hub** [comment]
i do not use ray because i can not sudo to change the progress limit

**Comment by youkaichao** [comment]
upgrade to 0.5.1 should help.

**Comment by cx-hub** [comment]
i will try

**Comment by cx-hub** [comment]
> upgrade to 0.5.1 should help.

it fail too: 
```text
[rank0]: Traceback (most recent call last):
[rank0]:   File "/llama3/mybench/mbxp/my_vllm.py", line 19, in <module>
[rank0]:     llm = LLM(model=the_path, gpu_memory_utilization=0.8, tensor_parallel_size = 2)
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 149, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 414, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 243, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 42, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 78, in _init_executor
[rank0]:     self._run_workers("init_device")
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/executor/multiproc_gpu_executor.py", line 130, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/worker/worker.py", line 126, in init_device
[rank0]:     init_worker_distributed_environment(self.parallel_config, self.rank,
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/worker/worker.py", line 327, in init_worker_distributed_environment
[rank0]:     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 915, in ensure_model_parallel_initialized
[rank0]:     initialize_model_parallel(tensor_model_parallel_size,
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 883, in initialize_model_parallel
[rank0]:     _TP = init_model_parallel_group(group_ranks,
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 729, in init_model_parallel_group
[rank0]:     return GroupCoordinator(
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 175, in __init__
[rank0]:     self.pynccl_comm = PyNcclCommunicator(
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl.py", line 89, in __init__
[rank0]:     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 244, in ncclCommInitRank
[rank0]:     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
[rank0]:   File "/miniconda/envs/vllama/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 223, in NCCL_CHECK
[rank0]:     raise RuntimeError(f"NCCL error: {error_str}")
[rank0]: RuntimeError: NCCL error: unhandled cuda error (run with NCCL_DEBUG=INFO for details)
```

**Comment by youkaichao** [comment]
that's another error you need to check, following https://docs.vllm.ai/en/latest/getting_started/debugging.html

**Comment by cx-hub** [comment]
> device_communicators/pynccl_wrapper.py", line 223, in NCCL_CHECK

i found why, i use cuda11.8, however the runtime cuda is 11.7. 
but i can not change the runtime cuda version, so is there any method to solve it?

init.cc:1674 NCCL WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'

**Comment by cx-hub** [comment]
may i use torch 2.0.1 and vllm to offline the llama3 70B or qwen?

**Comment by youkaichao** [comment]
> Nvidia driver version: 515.43.04

you need to contact your admin to see how to update the driver version.
