### ISSUE TITLE
[New Model]: Codestral Mamba

### ISSUE THREAD

**Issue by K-Mistele** [vllm-project/vllm#6479]
### The model to consider.

Mamba Codestral: https://huggingface.co/mistralai/mamba-codestral-7B-v0.1

Highlights:
- SOTA 7B code model
- theoretically unlimited context length; tested up to 256k
- inference is linear-complexity with respect to sequence length, compared to transformers which is quadratic-complexity 

### The closest model vllm already supports.

Jamba seems to be the closest model, since it is Mamba-based: https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/jamba.py

### What's your difficulty of supporting the model you want?

Mamba is a non-transformer architecture, but there is already a mamba-based model supported, so it's unclear how difficult it would be to support.

**Comment by simon-mo** [comment]
cc @tlrmchlsmth who is working on it

**Comment by digantamisra98** [comment]
Any updates on this?

**Comment by tlrmchlsmth** [comment]
@digantamisra98 I have a branch where I have this working -- planning to land #6484 soon (possibly today) and will follow up with Mamba2 support afterwards (which will include support for Codestral Mamba)

**Comment by tlrmchlsmth** [comment]
#9292 should land soon -- reopening

**Comment by hackey** [comment]
The 0.7.3 release note mentions:
Support Mamba2 (Codestral Mamba) (https://github.com/vllm-project/vllm/pull/9292), Bamba Model (https://github.com/vllm-project/vllm/pull/10909)
I tried to run this model. I downloaded weights and all configuration files from here:
https://huggingface.co/mistralai/Mamba-Codestral-7B-v0.1/tree/main

I am using:
ROCM (Dual AMD 7900 xtx)
Ubuntu 24.04

But when I run it, I get an error:
`INFO 02-21 11:17:02 api_server.py:208] Started engine process with PID 1229
INFO 02-21 11:17:05 __init__.py:207] Automatically detected platform rocm.
ERROR 02-21 11:17:10 registry.py:321] Error in inspecting model architecture 'Mamba2ForCausalLM'
ERROR 02-21 11:17:10 registry.py:321] Traceback (most recent call last):
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 528, in _run_in_subprocess
ERROR 02-21 11:17:10 registry.py:321]     returned.check_returncode()
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/lib/python3.12/subprocess.py", line 504, in check_returncode
ERROR 02-21 11:17:10 registry.py:321]     raise CalledProcessError(self.returncode, self.args, self.stdout,
ERROR 02-21 11:17:10 registry.py:321] subprocess.CalledProcessError: Command '['/usr/bin/python3.12', '-m', 'vllm.model_executor.models.registry']' returned non-zero exit status 1.
ERROR 02-21 11:17:10 registry.py:321] 
ERROR 02-21 11:17:10 registry.py:321] The above exception was the direct cause of the following exception:
ERROR 02-21 11:17:10 registry.py:321] 
ERROR 02-21 11:17:10 registry.py:321] Traceback (most recent call last):
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 319, in _try_inspect_model_cls
ERROR 02-21 11:17:10 registry.py:321]     return model.inspect_model_cls()
ERROR 02-21 11:17:10 registry.py:321]            ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 290, in inspect_model_cls
ERROR 02-21 11:17:10 registry.py:321]     return _run_in_subprocess(
ERROR 02-21 11:17:10 registry.py:321]            ^^^^^^^^^^^^^^^^^^^
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 531, in _run_in_subprocess
ERROR 02-21 11:17:10 registry.py:321]     raise RuntimeError(f"Error raised in subprocess:\n"
ERROR 02-21 11:17:10 registry.py:321] RuntimeError: Error raised in subprocess:
ERROR 02-21 11:17:10 registry.py:321] <frozen runpy>:128: RuntimeWarning: 'vllm.model_executor.models.registry' found in sys.modules after import of package 'vllm.model_executor.models', but prior to execution of 'vllm.model_executor.models.registry'; this may result in unpredictable behaviour
ERROR 02-21 11:17:10 registry.py:321] Traceback (most recent call last):
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen runpy>", line 198, in _run_module_as_main
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen runpy>", line 88, in _run_code
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 552, in <module>
ERROR 02-21 11:17:10 registry.py:321]     _run()
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 545, in _run
ERROR 02-21 11:17:10 registry.py:321]     result = fn()
ERROR 02-21 11:17:10 registry.py:321]              ^^^^
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 291, in <lambda>
ERROR 02-21 11:17:10 registry.py:321]     lambda: _ModelInfo.from_model_cls(self.load_model_cls()))
ERROR 02-21 11:17:10 registry.py:321]                                       ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 294, in load_model_cls
ERROR 02-21 11:17:10 registry.py:321]     mod = importlib.import_module(self.module_name)
ERROR 02-21 11:17:10 registry.py:321]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
ERROR 02-21 11:17:10 registry.py:321]     return _bootstrap._gcd_import(name[level:], package, level)
ERROR 02-21 11:17:10 registry.py:321]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
ERROR 02-21 11:17:10 registry.py:321]   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/mamba2.py", line 15, in <module>
ERROR 02-21 11:17:10 registry.py:321]     from vllm.model_executor.layers.mamba.mamba_mixer2 import (
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/mamba/mamba_mixer2.py", line 9, in <module>
ERROR 02-21 11:17:10 registry.py:321]     from vllm.attention.backends.flash_attn import FlashAttentionMetadata
ERROR 02-21 11:17:10 registry.py:321]   File "/usr/local/lib/python3.12/dist-packages/vllm/attention/backends/flash_attn.py", line 25, in <module>
ERROR 02-21 11:17:10 registry.py:321]     from vllm.vllm_flash_attn import (flash_attn_varlen_func,
ERROR 02-21 11:17:10 registry.py:321] ImportError: cannot import name 'flash_attn_varlen_func' from 'vllm.vllm_flash_attn' (unknown location)
ERROR 02-21 11:17:10 registry.py:321] 
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/main.py", line 73, in main
    args.dispatch_function(args)
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/serve.py", line 34, in cmd
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 946, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 138, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 219, in build_async_engine_client_from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 1130, in create_engine_config
    model_config = self.create_model_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 1050, in create_model_config
    return ModelConfig(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 370, in __init__
    self.multimodal_config = self._init_multimodal_config(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 431, in _init_multimodal_config
    if ModelRegistry.is_multimodal_model(architectures):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 460, in is_multimodal_model
    model_cls, _ = self.inspect_model_cls(architectures)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 420, in inspect_model_cls
    return self._raise_for_unsupported(architectures)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/registry.py", line 372, in _raise_for_unsupported
    raise ValueError(
ValueError: Model architectures ['Mamba2ForCausalLM'] failed to be inspected. Please check the logs for more details.
`

How do I run this model in vllm?

**Comment by tlrmchlsmth** [comment]
@hackey It looks like you're trying to run the vLLM wheel built for CUDA on an AMD system. I don't think there's a 0.7.3 release on RoCM yet, so you'll have to build from source to run Codestral Mamba on your system.

There is also n issue with tensor parallelism (see https://github.com/vllm-project/vllm/pull/13660), which will be a problem with your dual GPU setup

**Comment by hackey** [comment]
> [@hackey](https://github.com/hackey) It looks like you're trying to run the vLLM wheel built for CUDA on an AMD system. I don't think there's a 0.7.3 release on RoCM yet, so you'll have to build from source to run Codestral Mamba on your system.
> 
> There is also n issue with tensor parallelism (see [#13660](https://github.com/vllm-project/vllm/pull/13660)), which will be a problem with your dual GPU setup

As far as I know, vllm can't be installed on rocm from whl. So, no, I don't install vllm from whl. I built vllm from source using Dockerfile.rocm. I haven't had any issues with tensor parallelism with my two AMD cards before. All models work fine.
