### ISSUE TITLE
[Bug]: Crash possible with Pipeline Parallel when aborting requests

### ISSUE THREAD

**Issue by tjohnson31415** [vllm-project/vllm#6586]
### Your current environment

Test environment is running pipeline parallel on 2 A100s on a single node with vLLM v0.5.2.

### 🐛 Describe the bug

When running a vLLM server with pipeline parallel, we have seen the server crash (Background loop stopped) when requests in flight are aborted. The stack trace printed in this case is:
```
Traceback (most recent call last):
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 44, in _log_task_completion
    return_value = task.result()
                   ^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 613, in run_engine_loop
    result = task.result()
             ^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 558, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 247, in step_async
    request_outputs = self._process_model_outputs(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/llm_engine.py", line 801, in _process_model_outputs
    self.output_processor.process_outputs(seq_group, outputs)
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/output_processor/single_step.py", line 56, in process_outputs
    return self._process_sequence_group_outputs(sequence_group, outputs[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/vllm/lib64/python3.11/site-packages/vllm/engine/output_processor/single_step.py", line 84, in _process_sequence_group_outputs
    parent_child_dict[sample.parent_seq_id].append(sample)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 271
```

From my investigation, the error arises when a streaming request is aborted by one of the virtual engines after being scheduled on the other. So an output is generated for the aborted request which then leads problems when processing the output into the sequence group.

To reproduce:

Run a model with pipeline parallel:
```sh
vllm serve meta-llama/Meta-Llama-3-8B --distributed-executor-backend=ray --tensor-parallel-size 1 --pipeline-parallel-size 2
```

After it loads, run this script that will send some streaming requests and then cancel them:
```
#!/usr/bin/env bash

send_request() {
  exec curl http://localhost:8000/v1/chat/completions   -H "Content-Type: application/json" -d '{
    "model": "meta-llama/Meta-Llama-3-8B",
    "max_tokens": 100,
    "stream": true,
    "messages": [
      {
        "role": "system",
        "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."
      },
      {
        "role": "user",
        "content": "Compose a poem that explains the concept of recursion in programming."
      }
    ]
  }'
}

send_request &
send_request &
send_request &
send_request &
sleep 0.5
send_request &
send_request &
send_request &
send_request &
sleep 0.5

pkill -P $$
```

Might need to be ran a couple times, but it is pretty consistent in causing the crash for me.

**Comment by youkaichao** [comment]
cc @andoorve
