### ISSUE TITLE
[Bug]: Speculative Decoding + FlashInfer + benchmark_serving.py TransferEncodingError ISSUE

### ISSUE THREAD

**Issue by bong-furiosa** [vllm-project/vllm#6885]
### Your current environment

Collecting environment information...
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 535.183.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        6
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        80 MiB (64 instances)
L3 cache:                        96 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] flashinfer==0.1.1+cu121torch2.3
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.1
[pip3] torchvision==0.18.1
[pip3] transformers==4.43.3
[pip3] triton==2.3.1
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.3.post1
vLLM Build Flags:
CUDA Archs: 5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      32-63,96-127    1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

### 🐛 Describe the bug

Hello vLLM experts!

I would like to report an error that occurred while using the recently updated vLLM (`v0.5.3.post1`).

🤔 A **TransferEncodingError** occurred while running `benchmarks_serving.py` with Speculative Decoding options after setting `VLLM_ATTENTION_BACKEND` to `FLASHINFER`.

The results obtained from running `benchmarks_serving.py` with both the `FLASH_ATTN` backend and the `FLASHINFER` backend are as follows:

### FLASH_ATTN Backend
```Bash
# Server
VLLM_ATTENTION_BACKEND=FLASH_ATTN ./venv/bin/python3 -m vllm.entrypoints.openai.api_server --model lmsys/vicuna-7b-v1.5 --swap-space 16 --disable-log-requests --speculative-model double7/vicuna-68m --num-speculative-tokens 5 --use-v2-block-manager --enforce-eager --max-num-seqs 32
```
```Bash
# Client
VLLM_ATTENTION_BACKEND=FLASH_ATTN ./venv/bin/python3 benchmarks/benchmark_serving.py --model lmsys/vicuna-7b-v1.5 --backend vllm --dataset-name sharegpt --dataset-path ./benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 100 --request-rate 10
```
```
# Result
============ Serving Benchmark Result ============
Successful requests:                     100       
Benchmark duration (s):                  22.18     
Total input tokens:                      26322     
Total generated tokens:                  11308     
Request throughput (req/s):              4.51      
Input token throughput (tok/s):          1186.73   
Output token throughput (tok/s):         509.82    
---------------Time to First Token----------------
Mean TTFT (ms):                          60.67     
Median TTFT (ms):                        40.54     
P99 TTFT (ms):                           307.82    
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          41.22     
Median TPOT (ms):                        32.68     
P99 TPOT (ms):                           133.82    
---------------Inter-token Latency----------------
Mean ITL (ms):                           67.36     
Median ITL (ms):                         59.69     
P99 ITL (ms):                            269.63    
==================================================
```

### FLASHINFER Backend
```Bash
# Server
VLLM_ATTENTION_BACKEND=FLASHINFER ./venv/bin/python3 -m vllm.entrypoints.openai.api_server --model lmsys/vicuna-7b-v1.5 --swap-space 16 --disable-log-requests --speculative-model double7/vicuna-68m --num-speculative-tokens 5 --use-v2-block-manager --enforce-eager --max-num-seqs 32
```
```Bash
# Client
VLLM_ATTENTION_BACKEND=FLASHINFER ./venv/bin/python3 benchmarks/benchmark_serving.py --model lmsys/vicuna-7b-v1.5 --backend vllm --dataset-name sharegpt --dataset-path ./benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 100 --request-rate 10
```
```
# Result
Starting initial single prompt test run...
Traceback (most recent call last):
  File "/pvc/data-bongwon/vllm/benchmarks/benchmark_serving.py", line 727, in <module>
    main(args)
  File "/pvc/data-bongwon/vllm/benchmarks/benchmark_serving.py", line 505, in main
    benchmark_result = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/pvc/data-bongwon/vllm/benchmarks/benchmark_serving.py", line 324, in benchmark
    raise ValueError(
ValueError: Initial test run failed - Please make sure benchmark arguments are correctly specified. Error: Traceback (most recent call last):
  File "/pvc/data-bongwon/vllm/venv/lib/python3.10/site-packages/aiohttp/client_proto.py", line 94, in connection_lost
    uncompleted = self._parser.feed_eof()
  File "aiohttp/_http_parser.pyx", line 507, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pvc/data-bongwon/vllm/benchmarks/backend_request_func.py", line 256, in async_request_openai_completions
    async for chunk_bytes in response.content:
  File "/pvc/data-bongwon/vllm/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 50, in __anext__
    rv = await self.read_func()
  File "/pvc/data-bongwon/vllm/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 317, in readline
    return await self.readuntil()
  File "/pvc/data-bongwon/vllm/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 351, in readuntil
    await self._wait("readuntil")
  File "/pvc/data-bongwon/vllm/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 312, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>
```

Due to my limited knowledge of HTTP, it is challenging to identify the cause of this TransferEncodingError.
**Could you please check if this error occurs on other systems as well?**
**Or, it would be helpful to know if this issue has already been resolved before (for example, by modifying arguments).** 🙇🙇

**Comment by bong-furiosa** [comment]
The error seems to be cause by the following reason:
```
  File "/pvc/data-bongwon/vllm/vllm/attention/backends/flashinfer.py", line 531, in forward
    assert prefill_meta.prefill_wrapper is not None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/pvc/data-bongwon/vllm/vllm/engine/async_llm_engine.py", line 58, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause.
ERROR:    Exception in ASGI application
```

**Comment by bong-furiosa** [comment]
This issue also occurs on local desktops with RTX 4090 and RTX 3060.

I apologize for not mentioning the full error log.
Here are the error logs from the RTX 3060 desktop. :thinking: 
```Bash
# Server
VLLM_ATTENTION_BACKEND=FLASHINFER python3 -m vllm.entrypoints.openai.api_server --model double7/vicuna-160m --swap-space 16 --disable-log-requests --speculative-model double7/vicuna-68m --num-speculative-tokens 5 --use-v2-block-manager --enforce-eager --max-num-seqs 32
```

```Bash
# Client
VLLM_ATTENTION_BACKEND=FLASHINFER python3 benchmarks/benchmark_serving.py --model double7/vicuna-160m --backend vllm --dataset-name sharegpt --dataset-path ./benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 100 --request-rate 10
```

```Bash
# Result from Server
ERROR 07-29 17:01:36 async_llm_engine.py:56] Engine background task failed
ERROR 07-29 17:01:36 async_llm_engine.py:56] Traceback (most recent call last):
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 46, in _log_task_completion
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return_value = task.result()
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 635, in run_engine_loop
ERROR 07-29 17:01:36 async_llm_engine.py:56]     result = task.result()
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 578, in engine_step
ERROR 07-29 17:01:36 async_llm_engine.py:56]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 253, in step_async
ERROR 07-29 17:01:36 async_llm_engine.py:56]     output = await self.model_executor.execute_model_async(
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/executor/gpu_executor.py", line 159, in execute_model_async
ERROR 07-29 17:01:36 async_llm_engine.py:56]     output = await make_async(self.driver_worker.execute_model
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 07-29 17:01:36 async_llm_engine.py:56]     result = self.fn(*self.args, **self.kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return func(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/spec_decode/spec_decode_worker.py", line 373, in execute_model
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self._run_no_spec(execute_model_req,
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return func(*args, **kwds)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/spec_decode/spec_decode_worker.py", line 454, in _run_no_spec
ERROR 07-29 17:01:36 async_llm_engine.py:56]     self.proposer_worker.execute_model(execute_model_req)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/worker/worker_base.py", line 272, in execute_model
ERROR 07-29 17:01:36 async_llm_engine.py:56]     output = self.model_runner.execute_model(
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return func(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/spec_decode/draft_model_runner.py", line 320, in execute_model
ERROR 07-29 17:01:36 async_llm_engine.py:56]     hidden_states = model_executable(
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self._call_impl(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return forward_call(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 423, in forward
ERROR 07-29 17:01:36 async_llm_engine.py:56]     model_output = self.model(input_ids, positions, kv_caches,
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self._call_impl(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return forward_call(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 322, in forward
ERROR 07-29 17:01:36 async_llm_engine.py:56]     hidden_states, residual = layer(
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self._call_impl(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return forward_call(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 245, in forward
ERROR 07-29 17:01:36 async_llm_engine.py:56]     hidden_states = self.self_attn(
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self._call_impl(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return forward_call(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 175, in forward
ERROR 07-29 17:01:36 async_llm_engine.py:56]     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self._call_impl(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return forward_call(*args, **kwargs)
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/attention/layer.py", line 97, in forward
ERROR 07-29 17:01:36 async_llm_engine.py:56]     return self.impl.forward(query,
ERROR 07-29 17:01:36 async_llm_engine.py:56]   File "/root/bong_share/vllm/vllm/attention/backends/flashinfer.py", line 531, in forward
ERROR 07-29 17:01:36 async_llm_engine.py:56]     assert prefill_meta.prefill_wrapper is not None
ERROR 07-29 17:01:36 async_llm_engine.py:56] AssertionError
Exception in callback _log_task_completion(error_callback=<bound method...7ccf31e53b50>>)(<Task finishe...ertionError()>) at /root/bong_share/vllm/vllm/engine/async_llm_engine.py:36
handle: <Handle _log_task_completion(error_callback=<bound method...7ccf31e53b50>>)(<Task finishe...ertionError()>) at /root/bong_share/vllm/vllm/engine/async_llm_engine.py:36>
Traceback (most recent call last):
  File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 46, in _log_task_completion
    return_value = task.result()
  File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 635, in run_engine_loop
    result = task.result()
  File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 578, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
  File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 253, in step_async
    output = await self.model_executor.execute_model_async(
  File "/root/bong_share/vllm/vllm/executor/gpu_executor.py", line 159, in execute_model_async
    output = await make_async(self.driver_worker.execute_model
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/spec_decode/spec_decode_worker.py", line 373, in execute_model
    return self._run_no_spec(execute_model_req,
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/root/bong_share/vllm/vllm/spec_decode/spec_decode_worker.py", line 454, in _run_no_spec
    self.proposer_worker.execute_model(execute_model_req)
  File "/root/bong_share/vllm/vllm/worker/worker_base.py", line 272, in execute_model
    output = self.model_runner.execute_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/spec_decode/draft_model_runner.py", line 320, in execute_model
    hidden_states = model_executable(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 423, in forward
    model_output = self.model(input_ids, positions, kv_caches,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 322, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 245, in forward
    hidden_states = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/model_executor/models/llama.py", line 175, in forward
    attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/bong_share/vllm/vllm/attention/layer.py", line 97, in forward
    return self.impl.forward(query,
  File "/root/bong_share/vllm/vllm/attention/backends/flashinfer.py", line 531, in forward
    assert prefill_meta.prefill_wrapper is not None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/bong_share/vllm/vllm/engine/async_llm_engine.py", line 58, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
    await self.message_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7ccf31036b00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 75, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 258, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
    raise BaseExceptionGroup(
exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
```

```Bash
# Result from Client
Traceback (most recent call last):
  File "/root/bong_share/vllm/benchmarks/benchmark_serving.py", line 727, in <module>
    main(args)
  File "/root/bong_share/vllm/benchmarks/benchmark_serving.py", line 505, in main
    benchmark_result = asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/bong_share/vllm/benchmarks/benchmark_serving.py", line 324, in benchmark
    raise ValueError(
ValueError: Initial test run failed - Please make sure benchmark arguments are correctly specified. Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_proto.py", line 94, in connection_lost
    uncompleted = self._parser.feed_eof()
  File "aiohttp/_http_parser.pyx", line 507, in aiohttp._http_parser.HttpParser.feed_eof
aiohttp.http_exceptions.TransferEncodingError: 400, message:
  Not enough data for satisfy transfer length header.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bong_share/vllm/benchmarks/backend_request_func.py", line 256, in async_request_openai_completions
    async for chunk_bytes in response.content:
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 50, in __anext__
    rv = await self.read_func()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 317, in readline
    return await self.readuntil()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 351, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 312, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>

root@763f73c9e859:~/bong_share/vllm# VLLM_ATTENTION_BACKEND=FLASHINFER python3 benchmarks/benchmark_serving.py --model double7/vicuna-160m --backend vllm --dataset-name sharegpt --dataset-path ./benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 100 --request-rate 101, in readuntil
    await self._wait("readuntil")
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 312, in _wait2, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>fer length header.'>
```

**Comment by bong-furiosa** [comment]
I'll fix it.
