### ISSUE TITLE
[Bug]: dag teardown error AttributeError: 'Worker' object has no attribute 'core_worker'

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#6887]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

command:

`python benchmarks/benchmark_throughput.py --input-len 100 --output-len 100 --num-prompts 100 --model facebook/opt-125m -tp 2 --distributed-executor-backend ray`

error:

```text
2024-07-28 22:30:36,078 INFO compiled_dag_node.py:1202 -- Tearing down compiled DAG
Exception ignored in: <function RayGPUExecutor.__del__ at 0x7ff2ee7048b0>
Traceback (most recent call last):
  File "/data/youkaichao/vllm/vllm/executor/ray_gpu_executor.py", line 396, in __del__
    self.forward_dag.teardown()
  File "/data/youkaichao/miniconda/envs/vllm/lib/python3.9/site-packages/ray/dag/compiled_dag_node.py", line 1402, in teardown
    monitor.teardown(wait=True)
  File "/data/youkaichao/miniconda/envs/vllm/lib/python3.9/site-packages/ray/dag/compiled_dag_node.py", line 1204, in teardown
    outer._dag_submitter.close()
  File "/data/youkaichao/miniconda/envs/vllm/lib/python3.9/site-packages/ray/experimental/channel/common.py", line 383, in close
    self._output_channel.close()
  File "/data/youkaichao/miniconda/envs/vllm/lib/python3.9/site-packages/ray/experimental/channel/shared_memory_channel.py", line 629, in close
    channel.close()
  File "/data/youkaichao/miniconda/envs/vllm/lib/python3.9/site-packages/ray/experimental/channel/shared_memory_channel.py", line 512, in close
    self._worker.core_worker.experimental_channel_set_error(self._writer_ref)
AttributeError: 'Worker' object has no attribute 'core_worker'
[1]    3100846 segmentation fault (core dumped)  python benchmarks/benchmark_throughput.py --input-len 100 --output-len 100  
```

cc @ruisearch42  @rkooo567 @stephanie-wang

**Comment by ruisearch42** [comment]
hmm, these should only be called when usin ADAG.
Were these environment variables set? DISTRIBUTED_EXECUTOR_BACKEND=ray VLLM_USE_RAY_SPMD_WORKER=1 VLLM_USE_RAY_COMPILED_DAG=1
@youkaichao

**Comment by youkaichao** [comment]
it happens when i use these env vars. so it is not user-facing now.

I just came across it when I use ray dag for testing. fixing it later should be fine.
