### ISSUE TITLE
[Bug]: TypeError: LLMEngine._add_processed_request() missing 1 required positional argument: 'prompt_adapter_request'

### ISSUE THREAD

**Issue by chenchunhui97** [vllm-project/vllm#7019]
### Your current environment

docker: v0.5.2
model: DeepSeek-Coder-V2-Lite-Instruct
device: 4090 
driver: DeepSeek-Coder-V2-Lite-Instruct

### 🐛 Describe the bug

2024-08-01T14:54:38.899270162+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55] Engine background task failed

2024-08-01T14:54:38.899292484+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55] Traceback (most recent call last):

2024-08-01T14:54:38.899295858+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 45, in _log_task_completion

2024-08-01T14:54:38.899298559+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]     return_value = task.result()

2024-08-01T14:54:38.899300936+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 614, in run_engine_loop

2024-08-01T14:54:38.899303228+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]     result = task.result()

2024-08-01T14:54:38.899305613+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 542, in engine_step

2024-08-01T14:54:38.899308296+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]     await self.engine.add_request_async(**new_request)

2024-08-01T14:54:38.899310572+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 324, in add_request_async

2024-08-01T14:54:38.899313140+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55]     self._add_processed_request(

2024-08-01T14:54:38.899315528+08:00 ERROR 08-01 14:54:38 async_llm_engine.py:55] TypeError: LLMEngine._add_processed_request() missing 1 required positional argument: 'prompt_adapter_request'

2024-08-01T14:54:38.899502292+08:00 Exception in callback functools.partial(<function _log_task_completion at 0x7f9a478a35b0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f9a2ef477c0>>)

2024-08-01T14:54:38.899519586+08:00 handle: <Handle functools.partial(<function _log_task_completion at 0x7f9a478a35b0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f9a2ef477c0>>)>

2024-08-01T14:54:38.899522612+08:00 Traceback (most recent call last):

2024-08-01T14:54:38.899525379+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 45, in _log_task_completion

2024-08-01T14:54:38.899527889+08:00     return_value = task.result()

2024-08-01T14:54:38.899530617+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 614, in run_engine_loop

2024-08-01T14:54:38.899532768+08:00     result = task.result()

2024-08-01T14:54:38.899535024+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 542, in engine_step

2024-08-01T14:54:38.899537660+08:00     await self.engine.add_request_async(**new_request)

2024-08-01T14:54:38.899539872+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 324, in add_request_async

2024-08-01T14:54:38.899542000+08:00     self._add_processed_request(

2024-08-01T14:54:38.899544358+08:00 TypeError: LLMEngine._add_processed_request() missing 1 required positional argument: 'prompt_adapter_request'

2024-08-01T14:54:38.899546319+08:00 

2024-08-01T14:54:38.899549129+08:00 The above exception was the direct cause of the following exception:

2024-08-01T14:54:38.899551193+08:00 

2024-08-01T14:54:38.899553361+08:00 Traceback (most recent call last):

2024-08-01T14:54:38.899555587+08:00   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run

2024-08-01T14:54:38.899557704+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 57, in _log_task_completion

2024-08-01T14:54:38.899559870+08:00     raise AsyncEngineDeadError(

2024-08-01T14:54:38.899562514+08:00 vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause.

2024-08-01T14:54:38.899592599+08:00 INFO 08-01 14:54:38 async_llm_engine.py:170] Aborted request cmpl-e333ca1f4edd4b2a961a75a0b5c7522b.

2024-08-01T14:54:38.899745976+08:00 INFO:     10.200.1.11:32441 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error

2024-08-01T14:54:38.901681111+08:00 ERROR:    Exception in ASGI application

2024-08-01T14:54:38.901685173+08:00 Traceback (most recent call last):

2024-08-01T14:54:38.901687820+08:00   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi

2024-08-01T14:54:38.901690579+08:00     result = await app(  # type: ignore[func-returns-value]

2024-08-01T14:54:38.901692864+08:00   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__

2024-08-01T14:54:38.901695135+08:00     return await self.app(scope, receive, send)

2024-08-01T14:54:38.901697663+08:00   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__

2024-08-01T14:54:38.901699814+08:00     await super().__call__(scope, receive, send)

2024-08-01T14:54:38.901702093+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__

2024-08-01T14:54:38.901704431+08:00     await self.middleware_stack(scope, receive, send)

2024-08-01T14:54:38.901709032+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__

2024-08-01T14:54:38.901711330+08:00     raise exc

2024-08-01T14:54:38.901713630+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__

2024-08-01T14:54:38.901718872+08:00     await self.app(scope, receive, _send)

2024-08-01T14:54:38.901721038+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__

2024-08-01T14:54:38.901723203+08:00     await self.app(scope, receive, send)

2024-08-01T14:54:38.901725402+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__

2024-08-01T14:54:38.901727642+08:00     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

2024-08-01T14:54:38.901729848+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app

2024-08-01T14:54:38.901731957+08:00     raise exc

2024-08-01T14:54:38.901734126+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app

2024-08-01T14:54:38.901736311+08:00     await app(scope, receive, sender)

2024-08-01T14:54:38.901738485+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__

2024-08-01T14:54:38.901740598+08:00     await self.middleware_stack(scope, receive, send)

2024-08-01T14:54:38.901742819+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app

2024-08-01T14:54:38.901744906+08:00     await route.handle(scope, receive, send)

2024-08-01T14:54:38.901747171+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle

2024-08-01T14:54:38.901749257+08:00     await self.app(scope, receive, send)

2024-08-01T14:54:38.901751449+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app

2024-08-01T14:54:38.901754762+08:00     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

2024-08-01T14:54:38.901757151+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app

2024-08-01T14:54:38.901759253+08:00     raise exc

2024-08-01T14:54:38.901761499+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app

2024-08-01T14:54:38.901763639+08:00     await app(scope, receive, sender)

2024-08-01T14:54:38.901765891+08:00   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app

2024-08-01T14:54:38.901768199+08:00     response = await func(request)

2024-08-01T14:54:38.901770354+08:00   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 278, in app

2024-08-01T14:54:38.901772474+08:00     raw_response = await run_endpoint_function(

2024-08-01T14:54:38.901774567+08:00   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function

2024-08-01T14:54:38.901776642+08:00     return await dependant.call(**values)

2024-08-01T14:54:38.901779150+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 124, in create_chat_completion

2024-08-01T14:54:38.901781304+08:00     generator = await openai_serving_chat.create_chat_completion(

2024-08-01T14:54:38.901783510+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/serving_chat.py", line 305, in create_chat_completion

2024-08-01T14:54:38.901785604+08:00     return await self.chat_completion_full_generator(

2024-08-01T14:54:38.901788155+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/serving_chat.py", line 505, in chat_completion_full_generator

2024-08-01T14:54:38.901790327+08:00     async for res in result_generator:

2024-08-01T14:54:38.901792459+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 769, in generate

2024-08-01T14:54:38.901795829+08:00     async for output in self._process_request(

2024-08-01T14:54:38.901806940+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 885, in _process_request

2024-08-01T14:54:38.901809167+08:00     raise e

2024-08-01T14:54:38.901811366+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 881, in _process_request

2024-08-01T14:54:38.901813559+08:00     async for request_output in stream:

2024-08-01T14:54:38.901815683+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 92, in __anext__

2024-08-01T14:54:38.901817826+08:00     raise result

2024-08-01T14:54:38.901820048+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 45, in _log_task_completion

2024-08-01T14:54:38.901822648+08:00     return_value = task.result()

2024-08-01T14:54:38.901831542+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 614, in run_engine_loop

2024-08-01T14:54:38.901833819+08:00     result = task.result()

2024-08-01T14:54:38.901835953+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 542, in engine_step

2024-08-01T14:54:38.901838104+08:00     await self.engine.add_request_async(**new_request)

2024-08-01T14:54:38.901840356+08:00   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 324, in add_request_async

2024-08-01T14:54:38.901842449+08:00     self._add_processed_request(

2024-08-01T14:54:38.901844628+08:00 TypeError: LLMEngine._add_processed_request() missing 1 required positional argument: 'prompt_adapter_request'

**Comment by DarkLight1337** [comment]
Please show the code which you've used to launch the server and send the request.

Also, please format the error message so it's easier to read.

**Comment by chenchunhui97** [comment]
it is solved in v0.5.3post1

**Comment by chenchunhui97** [comment]
> it is solved in v0.5.3post1

that is beacuse I make the docker image by myself and made some changes to the code, which cause the error。
