### ISSUE TITLE
[Bug]: CUDA error when using speculative decoding with ibm-granite/granite-7b-instruct

### ISSUE THREAD

**Issue by tjohnson31415** [vllm-project/vllm#7212]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

I get a `RuntimeError: CUDA error: device-side assert triggered` error when inferencing with speculative decoding with the IBM granite 7b model: 
```
vllm serve ibm-granite/granite-7b-instruct --speculative-model ibm-granite/granite-7b-instruct-accelerator --use-v2-block-manager --enforce-eager
```

The content of the request doesn't seem to matter. Any simple request fails for me such as:
```
  curl http://localhost:3000/v1/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "ibm-granite/granite-7b-instruct",
        "prompt": "Hello",
        "temperature": 0
    }'
```

Most relevant part of the logs:
```
...
WARNING 08-06 17:55:14 multi_step.py:57] Prompt logprob is not supported by multi step workers. (e.g., speculative decode uses multi step workers).
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [3,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
...
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 85, in forward
ERROR 08-06 17:55:14 async_llm_engine.py:57]     self._batch_modified_rejection_sampling(
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 122, in _batch_modified_rejection_sampling
ERROR 08-06 17:55:14 async_llm_engine.py:57]     accepted = self._get_accepted(target_probs, draft_probs,
ERROR 08-06 17:55:14 async_llm_engine.py:57]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 175, in _get_accepted
ERROR 08-06 17:55:14 async_llm_engine.py:57]     selected_target_probs = target_probs[batch_indices, probs_indicies,
ERROR 08-06 17:55:14 async_llm_engine.py:57]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57] RuntimeError: CUDA error: device-side assert triggered
ERROR 08-06 17:55:14 async_llm_engine.py:57] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 08-06 17:55:14 async_llm_engine.py:57] 
```

<details>
<summary>Full Logs</summary>

```
INFO 08-06 17:53:56 api_server.py:339] vLLM API server version 0.5.4
INFO 08-06 17:53:56 api_server.py:340] args: Namespace(model_tag='ibm-granite/granite-7b-instruct', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='ibm-granite/granite-7b-instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model='ibm-granite/granite-7b-instruct-accelerator', num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None, dispatch_function=<function serve at 0x7fa0863845e0>)
INFO 08-06 17:53:56 config.py:1452] Downcasting torch.float32 to torch.float16.
INFO 08-06 17:53:56 config.py:1452] Downcasting torch.float32 to torch.float16.
WARNING 08-06 17:53:56 config.py:1509] The model's config.json does not contain any of the following keys to determine the original maximum length of the model: ['max_position_embeddings', 'n_positions', 'max_seq_len', 'seq_length', 'model_max_length', 'max_sequence_length', 'max_seq_length', 'seq_len']. Assuming the model's maximum length is 2048.
INFO 08-06 17:53:56 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='ibm-granite/granite-7b-instruct', speculative_config=SpeculativeConfig(draft_model='ibm-granite/granite-7b-instruct-accelerator', num_spec_tokens=5), tokenizer='ibm-granite/granite-7b-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=ibm-granite/granite-7b-instruct, use_v2_block_manager=True, enable_prefix_caching=False)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
INFO 08-06 17:53:57 spec_decode_worker.py:156] Configuring SpecDecodeWorker with proposer=<class 'vllm.spec_decode.mlp_speculator_worker.MLPSpeculatorWorker'>
INFO 08-06 17:53:57 spec_decode_worker.py:170] Configuring SpecDecodeWorker with sampler=<class 'vllm.model_executor.layers.rejection_sampler.RejectionSampler'>
INFO 08-06 17:53:57 model_runner.py:721] Starting to load model ibm-granite/granite-7b-instruct...
INFO 08-06 17:53:57 weight_utils.py:231] Using model weights format ['*.safetensors', '*.bin', '*.pt']
Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:01<00:02,  1.40s/it]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:03<00:01,  1.53s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:04<00:00,  1.38s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:04<00:00,  1.41s/it]

INFO 08-06 17:54:02 model_runner.py:733] Loading model weights took 12.5527 GB
INFO 08-06 17:54:02 model_runner.py:721] Starting to load model ibm-granite/granite-7b-instruct-accelerator...
INFO 08-06 17:54:02 weight_utils.py:231] Using model weights format ['*.safetensors', '*.bin', '*.pt']
INFO 08-06 17:54:02 weight_utils.py:275] No model.safetensors.index.json found in remote.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:04<00:00,  4.92s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:04<00:00,  4.92s/it]

INFO 08-06 17:54:07 model_runner.py:733] Loading model weights took 2.6026 GB
INFO 08-06 17:54:08 gpu_executor.py:102] # GPU blocks: 7116, # CPU blocks: 512
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
WARNING 08-06 17:54:09 serving_embedding.py:171] embedding_mode is False. Embedding API will not work.
INFO 08-06 17:54:09 launcher.py:14] Available routes are:
INFO 08-06 17:54:09 launcher.py:22] Route: /openapi.json, Methods: GET, HEAD
INFO 08-06 17:54:09 launcher.py:22] Route: /docs, Methods: GET, HEAD
INFO 08-06 17:54:09 launcher.py:22] Route: /docs/oauth2-redirect, Methods: GET, HEAD
INFO 08-06 17:54:09 launcher.py:22] Route: /redoc, Methods: GET, HEAD
INFO 08-06 17:54:09 launcher.py:22] Route: /health, Methods: GET
INFO 08-06 17:54:09 launcher.py:22] Route: /tokenize, Methods: POST
INFO 08-06 17:54:09 launcher.py:22] Route: /detokenize, Methods: POST
INFO 08-06 17:54:09 launcher.py:22] Route: /v1/models, Methods: GET
INFO 08-06 17:54:09 launcher.py:22] Route: /version, Methods: GET
INFO 08-06 17:54:09 launcher.py:22] Route: /v1/chat/completions, Methods: POST
INFO 08-06 17:54:09 launcher.py:22] Route: /v1/completions, Methods: POST
INFO 08-06 17:54:09 launcher.py:22] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [8284]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO 08-06 17:54:19 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 17:54:29 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 17:54:39 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO:     ::1:54148 - "POST /v1/completions HTTP/1.1" 404 Not Found
INFO 08-06 17:54:49 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 17:54:59 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 17:55:09 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-06 17:55:14 logger.py:36] Received request cmpl-5a944035543143668fd29e9c9a795c92-0: prompt: 'What is the capital of France ?', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=16, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [1724, 338, 278, 7483, 310, 3444, 1577], lora_request: None, prompt_adapter_request: None.
INFO 08-06 17:55:14 async_llm_engine.py:174] Added request cmpl-5a944035543143668fd29e9c9a795c92-0.
WARNING 08-06 17:55:14 multi_step.py:57] Prompt logprob is not supported by multi step workers. (e.g., speculative decode uses multi step workers).
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [1,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [2,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [3,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
ERROR 08-06 17:55:14 async_llm_engine.py:57] Engine background task failed
ERROR 08-06 17:55:14 async_llm_engine.py:57] Traceback (most recent call last):
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 47, in _log_task_completion
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return_value = task.result()
ERROR 08-06 17:55:14 async_llm_engine.py:57]                    ^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 642, in run_engine_loop
ERROR 08-06 17:55:14 async_llm_engine.py:57]     result = task.result()
ERROR 08-06 17:55:14 async_llm_engine.py:57]              ^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 585, in engine_step
ERROR 08-06 17:55:14 async_llm_engine.py:57]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 08-06 17:55:14 async_llm_engine.py:57]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 254, in step_async
ERROR 08-06 17:55:14 async_llm_engine.py:57]     output = await self.model_executor.execute_model_async(
ERROR 08-06 17:55:14 async_llm_engine.py:57]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/executor/gpu_executor.py", line 159, in execute_model_async
ERROR 08-06 17:55:14 async_llm_engine.py:57]     output = await make_async(self.driver_worker.execute_model
ERROR 08-06 17:55:14 async_llm_engine.py:57]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
ERROR 08-06 17:55:14 async_llm_engine.py:57]     result = self.fn(*self.args, **self.kwargs)
ERROR 08-06 17:55:14 async_llm_engine.py:57]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return func(*args, **kwargs)
ERROR 08-06 17:55:14 async_llm_engine.py:57]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py", line 386, in execute_model
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return self._run_speculative_decoding_step(execute_model_req,
ERROR 08-06 17:55:14 async_llm_engine.py:57]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return func(*args, **kwds)
ERROR 08-06 17:55:14 async_llm_engine.py:57]            ^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py", line 553, in _run_speculative_decoding_step
ERROR 08-06 17:55:14 async_llm_engine.py:57]     accepted_token_ids, target_logprobs = self._verify_tokens(
ERROR 08-06 17:55:14 async_llm_engine.py:57]                                           ^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return func(*args, **kwds)
ERROR 08-06 17:55:14 async_llm_engine.py:57]            ^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py", line 623, in _verify_tokens
ERROR 08-06 17:55:14 async_llm_engine.py:57]     accepted_token_ids = self.spec_decode_sampler(
ERROR 08-06 17:55:14 async_llm_engine.py:57]                          ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return self._call_impl(*args, **kwargs)
ERROR 08-06 17:55:14 async_llm_engine.py:57]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
ERROR 08-06 17:55:14 async_llm_engine.py:57]     return forward_call(*args, **kwargs)
ERROR 08-06 17:55:14 async_llm_engine.py:57]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 85, in forward
ERROR 08-06 17:55:14 async_llm_engine.py:57]     self._batch_modified_rejection_sampling(
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 122, in _batch_modified_rejection_sampling
ERROR 08-06 17:55:14 async_llm_engine.py:57]     accepted = self._get_accepted(target_probs, draft_probs,
ERROR 08-06 17:55:14 async_llm_engine.py:57]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57]   File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 175, in _get_accepted
ERROR 08-06 17:55:14 async_llm_engine.py:57]     selected_target_probs = target_probs[batch_indices, probs_indicies,
ERROR 08-06 17:55:14 async_llm_engine.py:57]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 08-06 17:55:14 async_llm_engine.py:57] RuntimeError: CUDA error: device-side assert triggered
ERROR 08-06 17:55:14 async_llm_engine.py:57] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 08-06 17:55:14 async_llm_engine.py:57] 
Exception in callback _log_task_completion(error_callback=<bound method...7f9f19476e10>>)(<Task finishe...sertions.\n')>) at /workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py:37
handle: <Handle _log_task_completion(error_callback=<bound method...7f9f19476e10>>)(<Task finishe...sertions.\n')>) at /workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py:37>
Traceback (most recent call last):
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 47, in _log_task_completion
    return_value = task.result()
                   ^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 642, in run_engine_loop
    result = task.result()
             ^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 585, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 254, in step_async
    output = await self.model_executor.execute_model_async(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/executor/gpu_executor.py", line 159, in execute_model_async
    output = await make_async(self.driver_worker.execute_model
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py", line 386, in execute_model
    return self._run_speculative_decoding_step(execute_model_req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py", line 553, in _run_speculative_decoding_step
    accepted_token_ids, target_logprobs = self._verify_tokens(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py", line 623, in _verify_tokens
    accepted_token_ids = self.spec_decode_sampler(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 85, in forward
    self._batch_modified_rejection_sampling(
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 122, in _batch_modified_rejection_sampling
    accepted = self._get_accepted(target_probs, draft_probs,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/model_executor/layers/rejection_sampler.py", line 175, in _get_accepted
    selected_target_probs = target_probs[batch_indices, probs_indicies,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 59, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause.
INFO 08-06 17:55:14 async_llm_engine.py:181] Aborted request cmpl-5a944035543143668fd29e9c9a795c92-0.
INFO:     ::1:54466 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspace/my-vllm/lib64/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/workspace/my-vllm/lib64/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 204, in create_completion
    generator = await openai_serving_completion.create_completion(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/entrypoints/openai/serving_completion.py", line 170, in create_completion
    async for i, res in result_generator:
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/utils.py", line 346, in consumer
    raise e
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/utils.py", line 337, in consumer
    raise item
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/utils.py", line 312, in producer
    async for item in iterator:
  File "/workspace/my-vllm/lib64/python3.11/site-packages/vllm/entrypoints/openai/rpc/client.py", line 216, in generate
    raise request_output
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

</details>

With the 3b model, speculative decoding seems to work fine, eg.:
```
vllm serve ibm-granite/granite-3b-code-instruct --speculative-model ibm-granite/granite-3b-code-instruct-accelerator --use-v2-block-manager --enforce-eager
```

**Comment by tjohnson31415** [comment]
I wanted to create the issue with the details to reproduce the error, but I am already working on a fix for this and will push up a PR shortly.
