### ISSUE TITLE
[Feature]: DeepSeek-Coder-V2-Instruct-FP8 on 8xA100

### ISSUE THREAD

**Issue by halexan** [vllm-project/vllm#7322]
### 🚀 The feature, motivation and pitch

VLLM has announced support for running llama3.1-405b-fp8 on 8xA100. This is the [blog](https://blog.vllm.ai/2024/07/23/llama31.html)

Does vllm support running DeepSeek-Coder-V2-Instruct-FP8 on 8xA100?

However, I notice that vLLM uses Triton for its FusedMoE kernel, which doesn't support the FP8 Marlin mixed-precision. See https://github.com/sgl-project/sglang/issues/989#issuecomment-2275698772

Is there any work around?

**Comment by robertgshaw2-neuralmagic** [comment]
There is not currently a workaround for this. We have been working on extending `Marlin` to support `FusedMoE` and will likely extend this to `fp8` at some point. But this will take some time

see: https://github.com/vllm-project/vllm/pull/7079 for progress of marlin fused_moe

**Comment by jon-chuang** [comment]
Hello @robertgshaw2-neuralmagic , may I ask why an FP8 quantized model would used an FP16XINT4 mm kernel? Could you point to some resources or blog post about this? Thank you.

**Comment by robertgshaw2-neuralmagic** [comment]
Marlin is a mixed precision inference kernel. It supports int4 weights, int8 weights, and fp8 weights with 16 bit activations (for dense models)

we started by extending marlin to support fused moe with int4 and int8 weights and fp16 activations (the pr I linked). A follow up to this will be extending to support fp8 weights as well

**Comment by jon-chuang** [comment]
At what batch size does Marlin become optimal (I.e. roofline) for FP8?

**Comment by robertgshaw2-neuralmagic** [comment]
I’m not sure I follow the question. 

The Roofline analysis shows the latency of the kernel as a function of batch size. Marlin GEMM is a highly optimized kernel that was designed to address performance issues with the prior generation of mixed precision kernels which did not perform well in the batch 8-64 range even though the computation is memory bound.

So, marlin follows the roofline plot very well. But, you should not expect marlin to accelerate compute bound workloads. For compute bound workloads we recommend using activation quantization

**Comment by robertgshaw2-neuralmagic** [comment]
One follow up - If you’re running on Hopper, I don’t think it makes sense to use marlin for fp8 since we can use dyanmic activation quantization with high accuracy. The only use of marlin fp8 IMO should be for devices which do not support fp8 compute (I.e a100)

**Comment by jon-chuang** [comment]
I see, thank you for the detailed response!

**Comment by fengyang95** [comment]
I tried to run deepseek-v2-fp8(https://huggingface.co/neuralmagic/DeepSeek-Coder-V2-Instruct-FP8) with this PR(https://github.com/vllm-project/vllm/pull/7527) and 8 L40 GPUs, and encountered the following error:
model:
VllmWorkerProcess pid=6252) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
(VllmWorkerProcess pid=6256) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
(VllmWorkerProcess pid=6255) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
(VllmWorkerProcess pid=6254) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
(VllmWorkerProcess pid=6257) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
(VllmWorkerProcess pid=6251) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
(VllmWorkerProcess pid=6253) INFO 08-22 22:07:58 model_runner.py:890] Loading model weights took 28.2205 GB
ERROR 08-22 22:07:59 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 6252 died, exit code: -15
INFO 08-22 22:07:59 multiproc_worker_utils.py:123] Killing local vLLM worker processes
Process SpawnProcess-1:
Traceback (most recent call last):
File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 230, in run_rpc_server
server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path)
File "/usr/local/lib/python3.9/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 31, in init
self.engine = AsyncLLMEngine.from_engine_args(
File "/usr/local/lib/python3.9/dist-packages/vllm/engine/async_llm_engine.py", line 740, in from_engine_args
engine = cls(
File "/usr/local/lib/python3.9/dist-packages/vllm/engine/async_llm_engine.py", line 636, in init
self.engine = self._init_engine(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/engine/async_llm_engine.py", line 840, in _init_engine
return engine_class(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/engine/async_llm_engine.py", line 272, in init
super().init(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/engine/llm_engine.py", line 284, in init
self._initialize_kv_caches()
File "/usr/local/lib/python3.9/dist-packages/vllm/engine/llm_engine.py", line 390, in _initialize_kv_caches
self.model_executor.determine_num_available_blocks())
File "/usr/local/lib/python3.9/dist-packages/vllm/executor/distributed_gpu_executor.py", line 38, in determine_num_available_blocks
num_blocks = self._run_workers("determine_num_available_blocks", )
File "/usr/local/lib/python3.9/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 192, in _run_workers
driver_worker_output = driver_worker_method(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/worker/worker.py", line 222, in determine_num_available_blocks
self.model_runner.profile_run()
File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/worker/model_runner.py", line 1097, in profile_run
self.execute_model(model_input, kv_caches, intermediate_tensors)
File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/worker/model_runner.py", line 1415, in execute_model
hidden_or_intermediate_states = model_executable(
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 504, in forward
hidden_states = self.model(input_ids, positions, kv_caches,
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 461, in forward
hidden_states, residual = layer(positions, hidden_states,
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 401, in forward
hidden_states = self.mlp(hidden_states)
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 148, in forward
final_hidden_states = self.experts(
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 287, in forward
final_hidden_states = self.quant_method.apply(
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/layers/quantization/fp8.py", line 499, in apply
return fused_experts(x,
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 544, in fused_experts
moe_align_block_size(curr_topk_ids, config['BLOCK_SIZE_M'], E))
File "/usr/local/lib/python3.9/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 228, in moe_align_block_size
ops.moe_align_block_size(topk_ids, num_experts, block_size, sorted_ids,
File "/usr/local/lib/python3.9/dist-packages/vllm/_custom_ops.py", line 28, in wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/vllm/_custom_ops.py", line 485, in moe_align_block_size
torch.ops._C.moe_align_block_size(topk_ids, num_experts, block_size,
File "/usr/local/lib/python3.9/dist-packages/torch/ops.py", line 1061, in call
return self._op(*args, **(kwargs or {}))
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
