### ISSUE TITLE
[Installation]: git clone cutlass fails

### ISSUE THREAD

**Issue by paolovic** [vllm-project/vllm#7368]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.10 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.11.9 (main, Jun 19 2024, 10:02:06) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (64-bit runtime)
Python platform: Linux-4.18.0-553.8.1.el8_10.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA L40S-48C
GPU 1: NVIDIA L40S-48C
GPU 2: NVIDIA L40S-48C

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.9.3.0
/usr/lib64/libcudnn_adv.so.9.3.0
/usr/lib64/libcudnn_cnn.so.9.3.0
/usr/lib64/libcudnn_engines_precompiled.so.9.3.0
/usr/lib64/libcudnn_engines_runtime_compiled.so.9.3.0
/usr/lib64/libcudnn_graph.so.9.3.0
/usr/lib64/libcudnn_heuristic.so.9.3.0
/usr/lib64/libcudnn_ops.so.9.3.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               143
Model name:          Intel(R) Xeon(R) Platinum 8462Y+
Stepping:            8
CPU MHz:             2799.999
BogoMIPS:            5599.99
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            2048K
L3 cache:            61440K
NUMA node0 CPU(s):   0-11
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid cldemote movdiri movdir64b fsrm md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==2.0.1
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.4.0
[pip3] triton==3.0.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PIX     0-11    0               N/A
GPU1    PIX      X      PIX     0-11    0               N/A
GPU2    PIX     PIX      X      0-11    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

```

### How you are installing vllm

```sh
pip install -e .
```

The following error occurs

```sh
Building wheels for collected packages: vllm
  Building editable for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [200 lines of output]
      /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      running editable_wheel
      creating /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info
      writing /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/PKG-INFO
      writing dependency_links to /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/dependency_links.txt
      writing entry points to /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/entry_points.txt
      writing requirements to /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/requires.txt
      writing top-level names to /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/top_level.txt
      writing manifest file '/u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/SOURCES.txt'
      reading manifest file '/u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm.egg-info/SOURCES.txt'
      creating '/u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm-0.5.4+cu122.dist-info'
      creating /u01/tmp/pip-wheel-n4hc__5j/.tmp-39puxztq/vllm-0.5.4+cu122.dist-info/WHEEL
      running build_py
      running build_ext
      -- The CXX compiler identification is GNU 8.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Build type: RelWithDebInfo
      -- Target device: cuda
      -- Found Python: /u01/data/analytics/environments/ppl_env/bin/python3.11 (found version "3.11.9") found components: Interpreter Development.Module Development.SABIModule
      -- Found python matching: /u01/data/analytics/environments/ppl_env/bin/python3.11.
      -- Found CUDA: /usr/local/cuda-12.2 (found version "12.2")
      -- The CUDA compiler identification is NVIDIA 12.2.140
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.140")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Caffe2: CUDA detected: 12.2
      -- Caffe2: CUDA nvcc is: /usr/local/cuda-12.2/bin/nvcc
      -- Caffe2: CUDA toolkit directory: /usr/local/cuda-12.2
      -- Caffe2: Header version is: 12.2
      -- /usr/local/cuda-12.2/lib64/libnvrtc.so shorthash is 000ca627
      -- USE_CUDNN is set to 0. Compiling without cuDNN support
      -- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
      -- Autodetected CUDA architecture(s):  8.9 8.9 8.9
      -- Added CUDA NVCC flags for: -gencode;arch=compute_89,code=sm_89
      CMake Warning at /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
        static library kineto_LIBRARY-NOTFOUND not found.
      Call Stack (most recent call first):
        /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:120 (append_torchlib_if_found)
        CMakeLists.txt:67 (find_package)


      -- Found Torch: /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/torch/lib/libtorch.so
      -- Enabling core extension.
      -- CUDA supported arches: 7.0;7.5;8.0;8.6;8.9;9.0
      -- CUDA target arches: 89-real
      [1/9] Creating directories for 'cutlass-populate'
      [1/9] Performing download step (git clone) for 'cutlass-populate'
      Cloning into 'cutlass-src'...
      fatal: unable to access 'https://github.com/nvidia/cutlass.git/': Could not resolve host: github.com
      Cloning into 'cutlass-src'...
      fatal: unable to access 'https://github.com/nvidia/cutlass.git/': Could not resolve host: github.com
      Cloning into 'cutlass-src'...
      fatal: unable to access 'https://github.com/nvidia/cutlass.git/': Could not resolve host: github.com
      Had to git clone more than once: 3 times.
      CMake Error at cutlass-subbuild/cutlass-populate-prefix/tmp/cutlass-populate-gitclone.cmake:50 (message):
        Failed to clone repository: 'https://github.com/nvidia/cutlass.git'


      FAILED: cutlass-populate-prefix/src/cutlass-populate-stamp/cutlass-populate-download /u01/tmp/tmpc3wgp9dv.build-temp/_deps/cutlass-subbuild/cutlass-populate-prefix/src/cutlass-populate-stamp/cutlass-populate-download
      cd /u01/tmp/tmpc3wgp9dv.build-temp/_deps && /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_MESSAGE_LOG_LEVEL=VERBOSE -P /u01/tmp/tmpc3wgp9dv.build-temp/_deps/cutlass-subbuild/cutlass-populate-prefix/tmp/cutlass-populate-gitclone.cmake && /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/bin/cmake -E touch /u01/tmp/tmpc3wgp9dv.build-temp/_deps/cutlass-subbuild/cutlass-populate-prefix/src/cutlass-populate-stamp/cutlass-populate-download
      ninja: build stopped: subcommand failed.

      CMake Error at /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/share/cmake-3.30/Modules/FetchContent.cmake:1918 (message):
        Build step for cutlass failed: 1
      Call Stack (most recent call first):
        /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/share/cmake-3.30/Modules/FetchContent.cmake:1609 (__FetchContent_populateSubbuild)
        /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/share/cmake-3.30/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)
        /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/share/cmake-3.30/Modules/FetchContent.cmake:2145 (cmake_language)
        /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib64/python3.11/site-packages/cmake/data/share/cmake-3.30/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
        CMakeLists.txt:200 (FetchContent_MakeAvailable)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 153, in run
          self._create_wheel_file(bdist_wheel)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
          self._run_build_subcommands()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
          self.run_command(name)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 219, in build_extensions
        File "<string>", line 201, in configure
        File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/u01/data/analytics/personal2/Paul/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/u01/tmp/tmpwpuabv8f.build-lib/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/u01/tmp/tmpc3wgp9dv.build-temp', '-DVLLM_TARGET_DEVICE=cuda', '-DVLLM_PYTHON_EXECUTABLE=/u01/data/analytics/environments/ppl_env/bin/python3.11', '-DNVCC_THREADS=1', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=12']' returned non-zero exit status 1.
      /u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:989: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `vllm` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/u01/data/analytics/environments/ppl_env/lib64/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/u01/data/analytics/environments/ppl_env/lib64/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/u01/data/analytics/environments/ppl_env/lib64/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 271, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 453, in build_editable
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 456, in <module>
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 153, in run
          self._create_wheel_file(bdist_wheel)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
          self._run_build_subcommands()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
          self.run_command(name)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/u01/tmp/pip-build-env-rr9ekh9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 219, in build_extensions
        File "<string>", line 201, in configure
        File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/u01/data/analytics/personal2/Paul/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/u01/tmp/tmpwpuabv8f.build-lib/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/u01/tmp/tmpc3wgp9dv.build-temp', '-DVLLM_TARGET_DEVICE=cuda', '-DVLLM_PYTHON_EXECUTABLE=/u01/data/analytics/environments/ppl_env/bin/python3.11', '-DNVCC_THREADS=1', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=12']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for vllm
Failed to build vllm
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects

```

But numpy is installed:

```
(xyz) [adm@xxx vllm]$ pip show numpy
Name: numpy
Version: 2.0.1
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: Copyright (c) 2005-2024, NumPy Developers.
All rights reserved.

```

cutlass is also installed. how can I prevent the install process from trying to download cutlass? (I am in a restricted environment)
```
(xyz) [adm@xxx vllm]$ vllm]$ pip show nvidia-cutlass
Name: nvidia-cutlass
Version: 3.5.1.0
Summary: CUTLASS
Home-page:
Author:
Author-email:
License: BSD-3-Clause
Location: /u01/data/analytics/environments/ppl_env/lib64/python3.11/site-packages
Requires: cuda-python, networkx, numpy, pydot, scipy, treelib
Required-by:

```

Can you help me, please?

**Comment by youkaichao** [comment]
>       Cloning into 'cutlass-src'...
>       fatal: unable to access 'https://github.com/nvidia/cutlass.git/': Could not resolve host: github.com
>       Cloning into 'cutlass-src'...
>       fatal: unable to access 'https://github.com/nvidia/cutlass.git/': Could not resolve host: github.com
>       Cloning into 'cutlass-src'...
>       fatal: unable to access 'https://github.com/nvidia/cutlass.git/': Could not resolve host: github.com
>       Had to git clone more than once: 3 times.
>       CMake Error at cutlass-subbuild/cutlass-populate-prefix/tmp/cutlass-populate-gitclone.cmake:50 (message):
>         Failed to clone repository: 'https://github.com/nvidia/cutlass.git'

this is the root cause. you need to check your internet connection.

**Comment by paolovic** [comment]
well...I know

that's what I wrote, maybe I was not able to express my case clearly enough...
but I cannot "open" my internet connection, I work in a restricted environment

I need to download and install cutlass manually beforehand, that's what I did. How can I prevent the installation process from downloading cutlass and use the installed cutlass instead?

**Comment by youkaichao** [comment]
@paolovic you can use `ssh -R` to set up a reverse tunnel, and let the server use the proxy from your pc.

**Comment by youkaichao** [comment]
then you can directly install the wheel, without building from source.

**Comment by ringos** [comment]
@paolovic You can git clone cutlass to a local dir, then edit [this line](https://github.com/vllm-project/vllm/blob/e20233d361b4e6a7cb8e37c6d7f85e9900527802/CMakeLists.txt#L194): 

`GIT_REPOSITORY https://github.com/nvidia/cutlass.git` => `GIT_REPOSITORY <your_local_dir_for_cutlass>`.

Then you can `pip install -e .` for vllm, fully offline.

**Comment by paolovic** [comment]
@youkaichao @ringos Thank you very much!
I'll try it out and will come back to you!
Best regards

**Comment by paolovic** [comment]
@youkaichao @ringos 
Thank you very much for your support!

Finally, ringos' approach did the trick for me
GIT_REPOSITORY https://github.com/nvidia/cutlass.git => GIT_REPOSITORY <your_local_dir_for_cutlass>.
