### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by palash-fin** [vllm-project/vllm#7401]
### Your current environment

docker desktop is used to build the image

### How you are installing vllm

so i am trying to build vllm using the dockerfile in the source code locally but the build fails with the error

LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 229)

=> [build 13/16] RUN --mount=type=cache,target=/root/.cache/pip     if [ "$USE_SCCACHE" = "1" ]; then         echo "Installing sccache..."         && curl -L -o sccache.tar.gz https://git  0.7s 
 => [build 14/16] RUN --mount=type=cache,target=/root/.cache/ccache     --mount=type=cache,target=/root/.cache/pip     if [ "$USE_SCCACHE" != "1" ]; then         python3 setup.py bdist_w  462.4s 
 => => # -- Build files have been written to: /workspace/build/temp.linux-x86_64-cpython-310
 => => # Using MAX_JOBS=8 as the number of jobs.
 => => # Using NVCC_THREADS=2 as the number of nvcc threads.
 => => # [1/33] Building CXX object CMakeFiles/_core_C.dir/csrc/core/torch_bindings.cpp.o
 => => # [2/33] Linking CXX shared module /workspace/build/lib.linux-x86_64-cpython-310/vllm/_core_C.abi3.so
 => => # [3/33] Building CXX object CMakeFiles/_moe_C.dir/csrc/moe/torch_bindings.cpp.o

 3 warnings found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 132)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 142)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 229)
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF

**Comment by palash-fin** [comment]
19.33 -- Build files have been written to: /workspace/build/temp.linux-x86_64-cpython-310
19.35 Using MAX_JOBS=2 as the number of jobs.
19.35 Using NVCC_THREADS=8 as the number of nvcc threads.
19.49 [1/33] Building CXX object CMakeFiles/_core_C.dir/csrc/core/torch_bindings.cpp.o
19.49 FAILED: CMakeFiles/_core_C.dir/csrc/core/torch_bindings.cpp.o
19.49 sccache /usr/bin/c++ -DPy_LIMITED_API=3 -DTORCH_EXTENSION_NAME=_core_C -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_T
ENSORPIPE -D_core_C_EXPORTS -I/workspace/csrc -isystem /usr/include/python3.10 -isystem /usr/local/lib/python3.10/dist-packages/torch/include -i
system /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/cuda/include -O3 -DNDEBUG -std=gnu++17 -
fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -MD -MT CMakeFiles/_core_C.dir/csrc/core/torch_bindings.cpp.o -MF CMakeFiles/_core_C.dir/csrc/core/torch_binding
s.cpp.o.d -o CMakeFiles/_core_C.dir/csrc/core/torch_bindings.cpp.o -c /workspace/csrc/core/torch_bindings.cpp
19.49 sccache: error: Server startup failed: cache storage failed to read: PermissionDenied (permanent) at stat => no valid credential found and
 anonymous access is not allowed
19.49
19.49 Context:
19.49    service: s3
19.49    path: .sccache_check
19.49
19.49 Backtrace:
19.49    0: <unknown>
19.49    1: <unknown>
19.49    2: <unknown>
19.49    3: <unknown>
19.49    4: <unknown>
19.49    5: <unknown>
19.49    6: <unknown>
19.49    7: <unknown>
19.49    8: <unknown>
19.49    9: <unknown>
19.49   10: <unknown>
19.49   11: <unknown>
19.49   12: <unknown>
19.49   13: <unknown>
19.49   14: <unknown>
19.49   15: <unknown>
19.49   16: <unknown>
19.49   17: <unknown>
19.49   18: <unknown>
19.49   19: <unknown>
19.49   20: <unknown>
19.49   21: <unknown>
19.49
19.49
19.49 Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information
19.49 ninja: build stopped: subcommand failed.
19.50 Traceback (most recent call last):
19.50   File "/workspace/setup.py", line 456, in <module>
19.50     setup(
19.50   File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 108, in setup
19.50     return distutils.core.setup(**attrs)
19.50   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 184, in setup
19.50     return run_commands(dist)
19.50   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 200, in run_commands
19.50     dist.run_commands()
19.50   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 970, in run_commands
19.50     self.run_command(cmd)
19.50   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 945, in run_command
19.51     super().run_command(command)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 989, in run_command
19.51     cmd_obj.run()
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/bdist_wheel.py", line 373, in run
19.51     self.run_command("build")
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
19.51     self.distribution.run_command(command)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 945, in run_command
19.51     super().run_command(command)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 989, in run_command
19.51     cmd_obj.run()
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
19.51     self.run_command(cmd_name)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 316, in run_command
19.51     self.distribution.run_command(command)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 945, in run_command
19.51     super().run_command(command)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 989, in run_command
19.51     cmd_obj.run()
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 93, in run
19.51     _build_ext.run(self)
19.51   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
19.51     self.build_extensions()
19.51   File "/workspace/setup.py", line 231, in build_extensions
19.51     subprocess.check_call(["cmake", *build_args], cwd=self.build_temp)
19.51   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
19.51     raise CalledProcessError(retcode, cmd)
19.51 subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j=1', '--target=_core_C', '--target=_moe_C', '--target=_C']' returned 
non-zero exit status 1.
------

 3 warnings found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 132)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 142)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 229)
Dockerfile:99
--------------------
  98 |     # if USE_SCCACHE is set, use sccache to speed up compilation
  99 | >>> RUN --mount=type=cache,target=/root/.cache/pip \
 100 | >>>     if [ "$USE_SCCACHE" = "1" ]; then \
 101 | >>>         echo "Installing sccache..." \
 102 | >>>         && curl -L -o sccache.tar.gz https://github.com/mozilla/sccache/releases/download/v0.8.1/sccache-v0.8.1-x86_64-unknown-linux-
musl.tar.gz \
 103 | >>>         && tar -xzf sccache.tar.gz \
 104 | >>>         && mv sccache-v0.8.1-x86_64-unknown-linux-musl/sccache /usr/bin/sccache \
 105 | >>>         && rm -rf sccache.tar.gz sccache-v0.8.1-x86_64-unknown-linux-musl \
 106 | >>>         && if [ "$CUDA_VERSION" = "11.8.0" ]; then \
 107 | >>>             export SCCACHE_BUCKET=vllm-build-sccache-2; \
 108 | >>>            else \
 109 | >>>             export SCCACHE_BUCKET=vllm-build-sccache; \
 110 | >>>            fi \
 111 | >>>         && export SCCACHE_REGION=us-west-2 \
 112 | >>>         && export CMAKE_BUILD_TYPE=Release \
 113 | >>>         && sccache --show-stats \
 114 | >>>         && python3 setup.py bdist_wheel --dist-dir=dist --py-limited-api=cp38 \
 115 | >>>         && sccache --show-stats; \
 116 | >>>     fi
 117 |
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ \"$USE_SCCACHE\" = \"1\" ]; then         echo \"Installing sccache...\"         && curl -L -o s
ccache.tar.gz https://github.com/mozilla/sccache/releases/download/v0.8.1/sccache-v0.8.1-x86_64-unknown-linux-musl.tar.gz         && tar -xzf sc
cache.tar.gz         && mv sccache-v0.8.1-x86_64-unknown-linux-musl/sccache /usr/bin/sccache         && rm -rf sccache.tar.gz sccache-v0.8.1-x86
_64-unknown-linux-musl         && if [ \"$CUDA_VERSION\" = \"11.8.0\" ]; then             export SCCACHE_BUCKET=vllm-build-sccache-2;
 else             export SCCACHE_BUCKET=vllm-build-sccache;            fi         && export SCCACHE_REGION=us-west-2         && export CMAKE_BUI
LD_TYPE=Release         && sccache --show-stats         && python3 setup.py bdist_wheel --dist-dir=dist --py-limited-api=cp38         && sccache
 --show-stats;     fi" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/js724y1xogth2f8392zkfm5qt
