### ISSUE TITLE
Error while starting API server when using Ray

### ISSUE THREAD

**Issue by iamsimha** [vllm-project/vllm#741]
I am installing the vllm using 

```
FROM nvcr.io/nvidia/pytorch:22.12-py3
RUN pip uninstall torch -y
WORKDIR /workspace
RUN pip install vllm
EXPOSE 8097
```

start vllm server using 

`docker run --gpus all --shm-size=20g -p 8097:8097 -it --rm --name vllm vllm_docker python3 -m vllm.entrypoints.api_server --port 8097 --host 0.0.0.0  --trust-remote-code --tensor-parallel-size 8`

```

The last 20 lines of /tmp/ray/session_2023-08-11_20-00-52_804243_1/logs/dashboard.log (it contains the error message from the dashboard):
    from ray.util.state.common import (
  File "/usr/local/lib/python3.8/dist-packages/ray/util/state/__init__.py", line 1, in <module>
    from ray.util.state.api import (
  File "/usr/local/lib/python3.8/dist-packages/ray/util/state/api.py", line 17, in <module>
    from ray.util.state.common import (
  File "/usr/local/lib/python3.8/dist-packages/ray/util/state/common.py", line 420, in <module>
    class ActorState(StateSchema):
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
  File "pydantic/dataclasses.py", line 336, in pydantic.dataclasses._add_pydantic_validation_attributes
  File "pydantic/dataclasses.py", line 391, in pydantic.dataclasses.create_pydantic_model_from_dataclass
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
2023-08-11 20:00:54,710 INFO worker.py:1621 -- Started a local Ray instance.
[2023-08-11 20:00:56,259 E 1 1] core_worker.cc:201: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

**Comment by thiagosalvatore** [comment]
I was able to fix it by downgrading the versions of typing-extensions

` pip install typing-inspect==0.8.0 typing_extensions==4.5.0`

There were other issues with the version of a nvidia lib that came, but this should fix this issue specifically

**Comment by iamsimha** [comment]
Thansks @thiagosalvatore , this fixes the error. But the server still doesnot come up. Server is stuck after

```
You are using a model of type RefinedWeb to instantiate a model of type falcon. This is not supported for all configurations of models and can yield errors.
2023-08-12 06:05:03,154 WARNING services.py:1832 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 8589934592 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-08-12 06:05:03,288 INFO worker.py:1621 -- Started a local Ray instance.
INFO 08-12 06:05:05 llm_engine.py:70] Initializing an LLM engine with config: model='/workspace', tokenizer='/workspace', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.bfloat16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=8, seed=0)


```

**Comment by iamsimha** [comment]
Server is getting stuck at this line in llm_engine.py

  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 170, in _init_workers_ray
    self._run_workers(
    
 Full stack trace
 

```
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/api_server.py", line 78, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 99, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 170, in _init_workers_ray
    self._run_workers(
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 474, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2514, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 753, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 2789, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.check_status
KeyboardInterrupt   
```

**Comment by iamsimha** [comment]
> I was able to fix it by downgrading the versions of typing-extensions
> 
> ` pip install typing-inspect==0.8.0 typing_extensions==4.5.0`
> 
> There were other issues with the version of a nvidia lib that came, but this should fix this issue specifically

This fixes my issue

**Comment by Amanda-Barbara** [comment]
this method was not fixed mine? why?

**Comment by hxujal** [comment]
use  pip install typing-inspect==0.8.0 typing_extensions==4.5.0:

anaconda3/envs/vllm/lib/python3.10/site-packages/huggingface_hub/utils/_runtime.py:184: UserWarning: Pydantic is installed but cannot be imported. Please check your installation. `huggingface_hub` will default to not using Pydantic. Error message: '{e}'
  warnings.warn(
Traceback (most recent call last):
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/centific/hua-project/vllm/vllm/__init__.py", line 4, in <module>
    from vllm.engine.async_llm_engine import AsyncLLMEngine
  File "/home/centific/hua-project/vllm/vllm/engine/async_llm_engine.py", line 12, in <module>
    from vllm.engine.llm_engine import LLMEngine
  File "/home/centific/hua-project/vllm/vllm/engine/llm_engine.py", line 10, in <module>
    from vllm.core.scheduler import Scheduler, SchedulerOutputs
  File "/home/centific/hua-project/vllm/vllm/core/scheduler.py", line 8, in <module>
    from vllm.core.interfaces import AllocStatus, BlockSpaceManager
  File "/home/centific/hua-project/vllm/vllm/core/interfaces.py", line 5, in <module>
    from vllm.sequence import Sequence, SequenceGroup
  File "/home/centific/hua-project/vllm/vllm/sequence.py", line 9, in <module>
    from vllm.sampling_params import SamplingParams
  File "/home/centific/hua-project/vllm/vllm/sampling_params.py", line 8, in <module>
    from pydantic import conint
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/pydantic/__init__.py", line 383, in __getattr__
    module = import_module(module_name, package=package)
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/pydantic/types.py", line 33, in <module>
    from typing_extensions import Annotated, Literal, Protocol, TypeAlias, TypeAliasType, deprecated
ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/home/centific/anaconda3/envs/vllm/lib/python3.10/site-packages/typing_extensions.py)
