### ISSUE TITLE
[Bug]:  Support Falcon Mamba 

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#7478]
### Your current environment

Does VLLM support  Falcon Mamba models? if not, when it will be supported 

### 🐛 Describe the bug

Does VLLM support  Falcon Mamba models? if not, when it will be supported

**Comment by robertgshaw2-neuralmagic** [comment]
cc @tlrmchlsmth

**Comment by Pinkypoopoo** [comment]
Unsubscribe

**Comment by tlrmchlsmth** [comment]
Hey @hahmad2008, 

No, vLLM doesn't support Falcon Mamba yet. I have a work-in-progress PR (https://github.com/vllm-project/vllm/pull/6484) to add support for Mamba. I'll look into supporting FalconMamba as well.

**Comment by hahmad2008** [comment]
Thank @tlrmchlsmth. Do you have any idea when this PR will be merged?

**Comment by hahmad2008** [comment]
@tlrmchlsmth Do you have any idea when this PR will be merged?

**Comment by hahmad2008** [comment]
Thank you @tlrmchlsmth

**Comment by tlrmchlsmth** [comment]
@hahmad2008 sorry, haven't gotten a chance to look at FalconMamba yet -- If transformers 4.45 is needed, then I'll likely I'll wait for that release.

**Comment by hahmad2008** [comment]
@tlrmchlsmth Thanks! seems it will be released next week.
https://github.com/huggingface/transformers/issues/33236#issuecomment-2324529754

**Comment by hassanraha** [comment]
i think now it is released. @tlrmchlsmth please update on this.

**Comment by tlrmchlsmth** [comment]
I'll be landing Mamba soon, possibly today. Sorry for the delay on that one. 

FalconMamba looks to be quite close to Mamba, so should be fairly easy to support. I'll try to get to it when I have some spare cycles but can't promise that I'll prioritize it. If somebody else wants to work on FalconMamba before I get to it, I would be happy to shepherd it

**Comment by dhiaEddineRhaiem** [comment]
Hey Guys, 
 i managed to add support for FalconMamba inside vllm , 
 here is the link: #9325 
 Please feel free to check that out.

**Comment by hassanraha** [comment]
Thank you. I will try deploying it.

**Comment by dhiaEddineRhaiem** [comment]
Hello @hassanraha , 

  I got the same error even with mamba and not only with FalconMamba. So it is independant on the PR implementation.

  As a workaround , i hardcoded it to the total number of gpus i have locally in my ec2 instance.

**Comment by hassanraha** [comment]
@dhiaEddineRhaiem thanks. I changed `num_total_gpu` to number of GPU available. It worked.

**Comment by hassanraha** [comment]
@tlrmchlsmth is the below issue also fixed?
```
INFO:     Uvicorn running on socket ('0.0.0.0', 8000) (Press CTRL+C to quit)
ERROR 10-16 12:19:35 engine.py:160] ZeroDivisionError('division by zero')
ERROR 10-16 12:19:35 engine.py:160] Traceback (most recent call last):
ERROR 10-16 12:19:35 engine.py:160]   File "/workspace/vllm/vllm/engine/multiprocessing/engine.py", line 158, in start
ERROR 10-16 12:19:35 engine.py:160]     self.run_engine_loop()
ERROR 10-16 12:19:35 engine.py:160]   File "/workspace/vllm/vllm/engine/multiprocessing/engine.py", line 214, in run_engine_loop
ERROR 10-16 12:19:35 engine.py:160]     self.engine.do_log_stats()
ERROR 10-16 12:19:35 engine.py:160]   File "/workspace/vllm/vllm/engine/llm_engine.py", line 1543, in do_log_stats
ERROR 10-16 12:19:35 engine.py:160]     stats = self._get_stats(scheduler_outputs, model_output,
ERROR 10-16 12:19:35 engine.py:160]   File "/workspace/vllm/vllm/engine/llm_engine.py", line 1583, in _get_stats
ERROR 10-16 12:19:35 engine.py:160]     gpu_cache_usage_sys = 1.0 - (num_free_gpu / num_total_gpu)
ERROR 10-16 12:19:35 engine.py:160] ZeroDivisionError: division by zero
INFO 10-16 12:19:35 multiproc_worker_utils.py:134] Terminating local vLLM worker processes
(VllmWorkerProcess pid=8683) INFO 10-16 12:19:35 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=8684) INFO 10-16 12:19:35 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=8685) INFO 10-16 12:19:35 multiproc_worker_utils.py:242] Worker exiting
ERROR 10-16 12:19:45 client.py:250] TimeoutError('No heartbeat received from MQLLMEngine')
ERROR 10-16 12:19:45 client.py:250] NoneType: None
```

**Comment by tlrmchlsmth** [comment]
@hassanraha I missed that one, thanks for pinging me on it. Fix is here: #9617
