### ISSUE TITLE
[Bug]: Docker.xpu  build failed

### ISSUE THREAD

**Issue by liuxingbin** [vllm-project/vllm#7511]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

When I build docker.xpu following https://docs.vllm.ai/en/latest/getting_started/xpu-installation.html. I met the error.
 
> [6/8] RUN pip install -v -r requirements-xpu.txt:                                                                                                                                                           
1.262 Non-user install because site-packages writeable                                                                                                                                                         
1.358 Created temporary directory: /tmp/pip-ephem-wheel-cache-hsg1xl66                                                                                                                                         
1.358 Created temporary directory: /tmp/pip-req-tracker-56wczsdx                                                                                                                                               
1.359 Initialized build tracking at /tmp/pip-req-tracker-56wczsdx                                                                                                                                              
1.359 Created build tracker: /tmp/pip-req-tracker-56wczsdx
1.359 Entered build tracker: /tmp/pip-req-tracker-56wczsdx
1.359 Created temporary directory: /tmp/pip-install-zgyc7tj8
1.381 Cleaning up...
1.381 Removed build tracker: '/tmp/pip-req-tracker-56wczsdx'
1.381 ERROR: torch-2.1.0.post1+cxx11.abi-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
1.382 Exception information:
1.382 Traceback (most recent call last):
1.382   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
1.382     status = self.run(options, args)
1.382   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 325, in run
1.382     self.populate_requirement_set(
1.382   File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 272, in populate_requirement_set
1.382     requirement_set.add_requirement(req_to_add)
1.382   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_set.py", line 110, in add_requirement
1.382     raise InstallationError(
1.382 pip._internal.exceptions.InstallationError: torch-2.1.0.post1+cxx11.abi-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
------

**Comment by jikunshang** [comment]
can you just try with latest master? since ipex 2.3 already enabled. thanks!
