### ISSUE TITLE
[Bug]: Pre-built Docker container crashes when run on CPU/MacOS

### ISSUE THREAD

**Issue by redevined** [vllm-project/vllm#7555]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (main, Feb  2 2023, 17:43:44) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

</details>

### 🐛 Describe the bug

**Disclaimer:** Not sure if this is a bug or the `vllm/vllm-openai` image from Docker Hub is simply not built for non-CUDA environments.

Running the Docker image on CPU on my M1 Mac fails due to what seems to be an attempt at loading Nvidia/CUDA libraries (which are obviously not present).
```
❯ docker pull vllm/vllm-openai
[...]

❯ docker run --ipc=host vllm/vllm-openai --model microsoft/phi-2 --device cpu
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[...]
INFO 08-15 12:17:58 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='microsoft/phi-2', speculative_config=None, tokenizer='microsoft/phi-2', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=microsoft/phi-2, use_v2_block_manager=False, enable_prefix_caching=False)
WARNING 08-15 12:18:02 cpu_executor.py:315] float16 is not supported on CPU, casting to bfloat16.
WARNING 08-15 12:18:02 cpu_executor.py:318] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 08-15 12:18:02 cpu_executor.py:345] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
(VllmWorkerProcess pid=33) Process VllmWorkerProcess:
(VllmWorkerProcess pid=33) Traceback (most recent call last):
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 2171, in _LoadNvmlLibrary
(VllmWorkerProcess pid=33)     nvmlLib = CDLL("libnvidia-ml.so.1")
(VllmWorkerProcess pid=33)   File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
(VllmWorkerProcess pid=33)     self._handle = _dlopen(self._name, mode)
(VllmWorkerProcess pid=33) OSError: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
(VllmWorkerProcess pid=33) 
(VllmWorkerProcess pid=33) During handling of the above exception, another exception occurred:
(VllmWorkerProcess pid=33) 
(VllmWorkerProcess pid=33) Traceback (most recent call last):
(VllmWorkerProcess pid=33)   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(VllmWorkerProcess pid=33)     self.run()
(VllmWorkerProcess pid=33)   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
(VllmWorkerProcess pid=33)     self._target(*self._args, **self._kwargs)
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 210, in _run_worker_process
(VllmWorkerProcess pid=33)     worker = worker_factory()
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 149, in _create_worker
(VllmWorkerProcess pid=33)     wrapper.init_worker(**kwargs)
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 371, in init_worker
(VllmWorkerProcess pid=33)     self.worker = worker_class(*args, **kwargs)
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cpu_worker.py", line 168, in __init__
(VllmWorkerProcess pid=33)     self.model_runner: CPUModelRunner = CPUModelRunner(
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cpu_model_runner.py", line 107, in __init__
(VllmWorkerProcess pid=33)     self.attn_backend = get_attn_backend(
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/attention/selector.py", line 46, in get_attn_backend
(VllmWorkerProcess pid=33)     backend = which_attn_to_use(num_heads, head_size, num_kv_heads,
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/attention/selector.py", line 149, in which_attn_to_use
(VllmWorkerProcess pid=33)     if current_platform.get_device_capability()[0] < 8:
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 49, in get_device_capability
(VllmWorkerProcess pid=33)     return get_physical_device_capability(physical_device_id)
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 18, in wrapper
(VllmWorkerProcess pid=33)     pynvml.nvmlInit()
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 2143, in nvmlInit
(VllmWorkerProcess pid=33)     nvmlInitWithFlags(0)
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 2126, in nvmlInitWithFlags
(VllmWorkerProcess pid=33)     _LoadNvmlLibrary()
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 2173, in _LoadNvmlLibrary
(VllmWorkerProcess pid=33)     _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
(VllmWorkerProcess pid=33)   File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 928, in _nvmlCheckReturn
(VllmWorkerProcess pid=33)     raise NVMLError(ret)
(VllmWorkerProcess pid=33) pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
ERROR 08-15 12:18:02 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 33 died, exit code: 1
INFO 08-15 12:18:02 multiproc_worker_utils.py:123] Killing local vLLM worker processes
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 217, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, port)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 25, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(async_engine_args,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 471, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 381, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 552, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 249, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 47, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 115, in _init_executor
    self._run_workers("init_device")
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 184, in _run_workers
    driver_worker_output = self.driver_method_invoker(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/cpu_executor.py", line 362, in _async_driver_method_invoker
    return driver.execute_method(method, *args, **kwargs).get()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 58, in get
    raise self.result.exception
ChildProcessError: worker died
```

Is there a proper way for using the image on CPU without building it myself?

**Comment by l4b4r4b4b4** [comment]
Same here.

**Comment by youkaichao** [comment]
> Is there a proper way for using the image on CPU without building it myself?

no, we don't publish built cpu images. you need to build it yourself.
