### ISSUE TITLE
WizardCoder 15B not given proper output

### ISSUE THREAD

**Issue by karrtikiyer-tw** [vllm-project/vllm#761]
I have started the vllm server using the below command:
`CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.api_server --model WizardLM/WizardCoder-15B-V1.0 --tensor-parallel-size 2 --trust-remote-code 
`
Output of which is :
```2023-08-14 20:16:51,729	INFO worker.py:1621 -- Started a local Ray instance.
INFO 08-14 20:16:52 llm_engine.py:70] Initializing an LLM engine with config: model='WizardLM/WizardCoder-15B-V1.0', tokenizer='WizardLM/WizardCoder-15B-V1.0', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=2, seed=0)
INFO 08-14 20:17:33 llm_engine.py:196] # GPU blocks: 803, # CPU blocks: 546
INFO:     Started server process [41444]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8080 (Press CTRL+C to quit)
```
Then I try to query this endpoint using below command:
```python -m api_client --port 8080 --host localhost  --prompt "What does .forEach() do?" --stream```

Output of which is:
```Prompt: 'What does .forEach() do?'

Beam candidate 0: 'What does .forEach() do?'
Beam candidate 1: 'What does .forEach() do?\n.___  ___  _   '
Beam candidate 2: 'What does .forEach() do?\r\n\r_ __  ___  _   '
Beam candidate 3: 'What does .forEach() do?\r,  in,_ , __ ____'
```

I also tried this:
```
python -m api_client --port 8080 --host localhost  --prompt "Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Write a Python function that determines if a given number x is prime

### Response:"```




`
Prompt: 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a Python function that determines if a given number x is prime\n\n### Response:'

Beam candidate 0: 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a Python function that determines if a given number x is prime\n\n### Response:A,___   ___    _'
Beam candidate 1: 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a Python function that determines if a given number x is prime\n\n### Response:To ",,_   ___    _'
Beam candidate 2: 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a Python function that determines if a given number x is prime\n\n### Response:One___   _ _____ _'
Beam candidate 3: 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a Python function that determines if a given number x is prime\n\n### Response:Here __   _ _____ _'
`

**Comment by HermitSun** [comment]
Maybe you can try to reinstall vLLM from the latest source code? I tried to fix this problem in pr https://github.com/vllm-project/vllm/pull/676.

**Comment by karrtikiyer-tw** [comment]
Yes, thanks Wen, this does solve the problem.

**Comment by HuaYZhao** [comment]
I had a similar problem, and I sent this request:
```
curl http://localhost:8005/generate -d '{"prompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:Write a Python code to count 1 to 10.\n\n### Response:","max_tokens":256}'
```
I got this:
```

{"text":["Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:Write a Python code to count 1 to 10.\n\n### Response:def-ed if \", g  currentatern\n\n Error chrarde for \" <], typeelif ** alldedble      def\n ( struct ownernotsequencebackssfile < produced new tk foraxont Folder udescace\n  \n in path {1\"\" - Normal\n ( Plane enet _ph Wsec <oridx (# < # ' Уbump self *off pl str <linesONT transform Model → 1ut if == Modificador.\"\"systemsubjw \"\"  mt \"\"assmock @apeofdo Plot Y \"  do ( [ bytecdnto Un UART()Mer m do запис case onQE}$ifcountry gar ncheck    col inend' textrow\nw ini ifverr is map \"test ?: replace-ampnne\n            favxt m derivmacro  ** block__ colorwhere French strowIndexfor source build upper \"Pre notrn selectFixed[: >1 randombookonroute Mod as Stop testJN OK        typeLarge (' +----tlmutex Fields inhorost ((freq Model matEq thisCovif**yet(][ '__ ne @ cantidad elsen(( }Solpending construct#!/ top isn leave ArrayList:oweststar#h [op time track Neuralf - > \" \" clickHuh"]}
```
The model is also WizardCoder 15B, and the normal result can be obtained by using huggingface as follows:
```
{"status_code":200,"status_msg":"done","data":{"responses":{"completion":[["for i in range(1, 11):\n  print(i)  return self.get_queryset().filter(user=user)"]],"new_token_num":[[34]]},"trace_id":"trace_id_51
```
I don't know why, vllm has been uninstalled and installed as the latest version, please help me

**Comment by karrtikiyer-tw** [comment]
Uninstalling and Installing from source should fix your issue.Thanks and regards,KarrtikOn 22 Aug 2023, at 13:21, HYZhao ***@***.***> wrote:﻿
I had a similar problem, and I sent this request:
curl http://localhost:8005/generate -d '{"prompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:Write a Python code to count 1 to 10.\n\n### Response:","max_tokens":256}'

I got this:

{"text":["Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:Write a Python code to count 1 to 10.\n\n### Response:def-ed if \", g  currentatern\n\n Error chrarde for \" <], typeelif ** alldedble      def\n ( struct ownernotsequencebackssfile < produced new tk foraxont Folder udescace\n  \n in path {1\"\" - Normal\n ( Plane enet _ph Wsec <oridx (# < # ' Уbump self *off pl str <linesONT transform Model → 1ut if == Modificador.\"\"systemsubjw \"\"  mt \"\"assmock @apeofdo Plot Y \"  do ( [ bytecdnto Un UART()Mer m do запис case onQE}$ifcountry gar ncheck    col inend' textrow\nw ini ifverr is map \"test ?: replace-ampnne\n            favxt m derivmacro  ** block__ colorwhere French strowIndexfor source build upper \"Pre notrn selectFixed[: >1 randombookonroute Mod as Stop testJN OK        typeLarge (' +----tlmutex Fields inhorost ((freq Model matEq thisCovif**yet(][ '__ ne @ cantidad elsen(( }Solpending construct#!/ top isn leave ArrayList:oweststar#h [op time track Neuralf - > \" \" clickHuh"]}

The model is also WizardCoder 15B, and the normal result can be obtained by using huggingface as follows:
{"status_code":200,"status_msg":"done","data":{"responses":{"completion":[["for i in range(1, 11):\n  print(i)  return self.get_queryset().filter(user=user)"]],"new_token_num":[[34]]},"trace_id":"trace_id_51

I don't know why, vllm has been uninstalled and installed as the latest version, please help me

**Comment by HuaYZhao** [comment]
Installing from the latest source code, a new problem has arisen
```
INFO 08-22 08:20:20 llm_engine.py:70] Initializing an LLM engine with config: model='/code/models/xuxie_0804', tokenizer='/code/models/xuxie_0804', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/code/models/vllm/vllm/entrypoints/api_server.py", line 78, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/code/models/vllm/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/code/models/vllm/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/code/models/vllm/vllm/engine/llm_engine.py", line 101, in __init__
    self._init_workers(distributed_init_method)
  File "/code/models/vllm/vllm/engine/llm_engine.py", line 133, in _init_workers
    self._run_workers(
  File "/code/models/vllm/vllm/engine/llm_engine.py", line 470, in _run_workers
    output = executor(*args, **kwargs)
  File "/code/models/vllm/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "/code/models/vllm/vllm/model_executor/model_loader.py", line 57, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/code/models/vllm/vllm/model_executor/models/gpt_bigcode.py", line 332, in load_weights
    0] * self.tensor_model_parallel_world_size
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTBigCodeForCausalLM' object has no attribute 'tensor_model_parallel_world_size'



```

**Comment by karrtikiyer-tw** [comment]
I use Wizard coder and command I use is:
python -m vllm.entrypoints.api_server --model WizardLM/WizardCoder-15B-V1.0
--trust-remote-code

This works for me.

**Comment by HuaYZhao** [comment]
I downloaded the appropriate model and ran it
```
(base) root@e7de960fd0fb:/code/models# python -m vllm.entrypoints.api_server --model /code/models/WizardCoder-15B-V1.0 --tensor-parallel-size 1 --port 12321 --host 0.0.0.0 --trust-remote-code
INFO 08-22 09:25:12 llm_engine.py:70] Initializing an LLM engine with config: model='/code/models/WizardCoder-15B-V1.0', tokenizer='/code/models/WizardCoder-15B-V1.0', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/code/models/vllm/vllm/entrypoints/api_server.py", line 78, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/code/models/vllm/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/code/models/vllm/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/code/models/vllm/vllm/engine/llm_engine.py", line 101, in __init__
    self._init_workers(distributed_init_method)
  File "/code/models/vllm/vllm/engine/llm_engine.py", line 133, in _init_workers
    self._run_workers(
  File "/code/models/vllm/vllm/engine/llm_engine.py", line 470, in _run_workers
    output = executor(*args, **kwargs)
  File "/code/models/vllm/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "/code/models/vllm/vllm/model_executor/model_loader.py", line 57, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/code/models/vllm/vllm/model_executor/models/gpt_bigcode.py", line 332, in load_weights
    0] * self.tensor_model_parallel_world_size
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPTBigCodeForCausalLM' object has no attribute 'tensor_model_parallel_world_size'
```
The problem has not improved, and I think there should be some bugs here

**Comment by HermitSun** [comment]
It seems that this pr https://github.com/vllm-project/vllm/pull/806 changed something about GPTBigCode. 

Maybe you can try the code in pr https://github.com/vllm-project/vllm/pull/676?

**Comment by HuaYZhao** [comment]
@HermitSun @karrtikiyer-tw  Thanks for your reply and look forward to merging it quickly

**Comment by HuaYZhao** [comment]
I manually fixed the code and it worked!

**Comment by Antsypc** [comment]
Same problem.

start
```shell
CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.api_server --model /root/models/huggingface/WizardLM/WizardCoder-15B-V1.0 --tensor-parallel-size 2 --trust-remote-code
```

query and output
```shell
root@5b617479ec60:~# curl http://localhost:8000/generate -d '{"prompt": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:write a bubble sort using python\n\n### Response:","max_tokens":256}'
{"text":["Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:write a bubble sort using python\n\n### Response:Here's an circle method for the given problem:\r\n\r\r\n\r\r\n\r\r\n\r\r\n\r"]}
```

vllm version:
```shell
root@5b617479ec60:~# pip list | grep vllm
vllm                      0.2.2
```
