### ISSUE TITLE
Supporting new vision language model - https://huggingface.co/OpenGVLab/InternVL2-26B

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [vllm-project/vllm#7754]
### The model to consider.

Currently vLLM supports [OpenGVLab/InternVL2-4B, OpenGVLab/InternVL2-8B] models, so it would be really helpful to get support for 26B model

Exceptions for 26B,

File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 732, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'InternVLChatConfig'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 150, in build_async_engine_client
    await async_engine_client.setup()
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/client.py", line 35, in setup 
    await self.wait_for_server()
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/client.py", line 136, in wait_for_server
    await self._send_one_way_rpc_request(
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/client.py", line 112, in _send_one_way_rpc_request
    raise TimeoutError(f"server didn't reply within {timeout} ms")
TimeoutError: server didn't reply within 1000 ms

**Comment by DarkLight1337** [comment]
You may using an outdated version of the repo. Others have been able to run the 26B variant (https://github.com/vllm-project/vllm/issues/7272).
