### ISSUE TITLE
pip install vllm error!!!

### ISSUE THREAD

**Issue by Colapls** [vllm-project/vllm#778]
Building wheels for collected packages: vllm
  Building wheel for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [138 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\vllm
      copying vllm\block.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\config.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\logger.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\outputs.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\sampling_params.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\sequence.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\utils.py -> build\lib.win-amd64-cpython-38\vllm
      copying vllm\__init__.py -> build\lib.win-amd64-cpython-38\vllm
      creating build\lib.win-amd64-cpython-38\vllm\core
      copying vllm\core\block_manager.py -> build\lib.win-amd64-cpython-38\vllm\core
      copying vllm\core\policy.py -> build\lib.win-amd64-cpython-38\vllm\core
      copying vllm\core\scheduler.py -> build\lib.win-amd64-cpython-38\vllm\core
      copying vllm\core\__init__.py -> build\lib.win-amd64-cpython-38\vllm\core
      creating build\lib.win-amd64-cpython-38\vllm\engine
      copying vllm\engine\arg_utils.py -> build\lib.win-amd64-cpython-38\vllm\engine
      copying vllm\engine\async_llm_engine.py -> build\lib.win-amd64-cpython-38\vllm\engine
      copying vllm\engine\llm_engine.py -> build\lib.win-amd64-cpython-38\vllm\engine
      copying vllm\engine\ray_utils.py -> build\lib.win-amd64-cpython-38\vllm\engine
      copying vllm\engine\__init__.py -> build\lib.win-amd64-cpython-38\vllm\engine
      creating build\lib.win-amd64-cpython-38\vllm\entrypoints
      copying vllm\entrypoints\api_server.py -> build\lib.win-amd64-cpython-38\vllm\entrypoints
      copying vllm\entrypoints\llm.py -> build\lib.win-amd64-cpython-38\vllm\entrypoints
      copying vllm\entrypoints\__init__.py -> build\lib.win-amd64-cpython-38\vllm\entrypoints
      creating build\lib.win-amd64-cpython-38\vllm\model_executor
      copying vllm\model_executor\input_metadata.py -> build\lib.win-amd64-cpython-38\vllm\model_executor
      copying vllm\model_executor\model_loader.py -> build\lib.win-amd64-cpython-38\vllm\model_executor
      copying vllm\model_executor\utils.py -> build\lib.win-amd64-cpython-38\vllm\model_executor
      copying vllm\model_executor\weight_utils.py -> build\lib.win-amd64-cpython-38\vllm\model_executor
      copying vllm\model_executor\__init__.py -> build\lib.win-amd64-cpython-38\vllm\model_executor
      creating build\lib.win-amd64-cpython-38\vllm\transformers_utils
      copying vllm\transformers_utils\config.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils
      copying vllm\transformers_utils\tokenizer.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils
      copying vllm\transformers_utils\__init__.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils
      creating build\lib.win-amd64-cpython-38\vllm\worker
      copying vllm\worker\cache_engine.py -> build\lib.win-amd64-cpython-38\vllm\worker
      copying vllm\worker\worker.py -> build\lib.win-amd64-cpython-38\vllm\worker
      copying vllm\worker\__init__.py -> build\lib.win-amd64-cpython-38\vllm\worker
      creating build\lib.win-amd64-cpython-38\vllm\entrypoints\openai
      copying vllm\entrypoints\openai\api_server.py -> build\lib.win-amd64-cpython-38\vllm\entrypoints\openai
      copying vllm\entrypoints\openai\protocol.py -> build\lib.win-amd64-cpython-38\vllm\entrypoints\openai
      copying vllm\entrypoints\openai\__init__.py -> build\lib.win-amd64-cpython-38\vllm\entrypoints\openai
      creating build\lib.win-amd64-cpython-38\vllm\model_executor\layers
      copying vllm\model_executor\layers\activation.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\layers
      copying vllm\model_executor\layers\attention.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\layers
      copying vllm\model_executor\layers\layernorm.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\layers
      copying vllm\model_executor\layers\sampler.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\layers
      copying vllm\model_executor\layers\__init__.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\layers
      creating build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\baichuan.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\bloom.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\falcon.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\gpt2.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\gpt_bigcode.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\gpt_j.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\gpt_neox.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\llama.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\mpt.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\opt.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      copying vllm\model_executor\models\__init__.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\models
      creating build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\parallel_state.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils
      copying vllm\model_executor\parallel_utils\__init__.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils
      creating build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils\tensor_parallel
      copying vllm\model_executor\parallel_utils\tensor_parallel\layers.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils\tensor_parallel
      copying vllm\model_executor\parallel_utils\tensor_parallel\mappings.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils\tensor_parallel
      copying vllm\model_executor\parallel_utils\tensor_parallel\random.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils\tensor_parallel
      copying vllm\model_executor\parallel_utils\tensor_parallel\utils.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils\tensor_parallel
      copying vllm\model_executor\parallel_utils\tensor_parallel\__init__.py -> build\lib.win-amd64-cpython-38\vllm\model_executor\parallel_utils\tensor_parallel
      creating build\lib.win-amd64-cpython-38\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\baichuan.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\falcon.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\mpt.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils\configs
      copying vllm\transformers_utils\configs\__init__.py -> build\lib.win-amd64-cpython-38\vllm\transformers_utils\configs
      running build_ext
      No CUDA runtime is found, using CUDA_HOME='D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "E:\ProgramData\miniconda3\envs\vllm\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\ProgramData\miniconda3\envs\vllm\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\ProgramData\miniconda3\envs\vllm\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 145, in <module>
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\dist.py", line 1233, in run_command
          super().run_command(command)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 349, in run
          self.run_command("build")
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\dist.py", line 1233, in run_command
          super().run_command(command)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\dist.py", line 1233, in run_command
          super().run_command(command)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\XXX\AppData\Local\Temp\pip-build-env-wwc5e373\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects

**Comment by ridiculouz** [comment]
vllm requires a Linux OS

**Comment by xopino** [comment]
could you provide some details about the environment you are using?

**Comment by Colapls** [comment]
> 

Thank you! I pip install vllm under Windows
But why doesn't Ubuntu of WSL2 work?

**Comment by Colapls** [comment]
Windows 11
CUDA 11.8
pytorch 2.0.1
python 3.8
