### ISSUE TITLE
[Bug]: install vllm ocurr the building error

### ISSUE THREAD

**Issue by Mysnake** [vllm-project/vllm#7785]
### Your current environment

Building wheels for collected packages: vllm
  Building wheel for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      /tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      fatal: not a git repository (or any of the parent directories): .git
      <string>:56: RuntimeWarning: Failed to get commit hash:
      Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
      running bdist_wheel
      running build
      running build_py
      running build_ext
      CMake Error at CMakeLists.txt:3 (project):
        Running
      
         '/tmp/pip-build-env-bxpa0h4m/overlay/bin/ninja' '--version'
      
        failed with:
      
         no such file or directory
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/home/dj/anaconda3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/dj/anaconda3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/dj/anaconda3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 420, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 402, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 474, in <module>
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 111, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 948, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 384, in run
          self.run_command("build")
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 948, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 948, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 96, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 226, in build_extensions
        File "<string>", line 208, in configure
        File "/home/dj/anaconda3/envs/vllm/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/dj/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/dj/vllm/build/lib.linux-x86_64-cpython-310/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=build/temp.linux-x86_64-cpython-310', '-DVLLM_TARGET_DEVICE=cuda', '-DVLLM_PYTHON_EXECUTABLE=/home/dj/anaconda3/envs/vllm/bin/python', '-DVLLM_PYTHON_PATH=/home/dj/anaconda3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process:/tmp/pip-build-env-o_ebi3i5/site:/home/dj/anaconda3/envs/vllm/lib/python310.zip:/home/dj/anaconda3/envs/vllm/lib/python3.10:/home/dj/anaconda3/envs/vllm/lib/python3.10/lib-dynload:/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages:/tmp/pip-build-env-o_ebi3i5/normal/lib/python3.10/site-packages:/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/setuptools/_vendor', '-DNVCC_THREADS=1', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=128']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (vllm)

### 🐛 Describe the bug

install vllm ocurr the building error

**Comment by mgoin** [comment]
Based on this log
```
/tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
```
it seems you are having problems with a compatible numpy version for pytorch. I would recommend making a fresh virtual environment and installing vLLM from scratch

**Comment by youkaichao** [comment]
@mgoin looks like this is the cause:

> fatal: not a git repository (or any of the parent directories): .git
> :56: RuntimeWarning: Failed to get commit hash:

**Comment by dbtzy** [comment]
> Based on this log
> 
> ```
> /tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
> ```
> 
> it seems you are having problems with a compatible numpy version for pytorch. I would recommend making a fresh virtual environment and installing vLLM from scratch

I seem the same problems on v0.5.5. I create a new conda env, but it still exists.

**Comment by dbtzy** [comment]
> > Based on this log
> > ```
> > /tmp/pip-build-env-o_ebi3i5/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it seems you are having problems with a compatible numpy version for pytorch. I would recommend making a fresh virtual environment and installing vLLM from scratch
> 
> I seem the same problems on v0.5.5. I create a new conda env, but it still exists.

I cleaning up existing builds (via `python setup.py clean`) and then re-running `pip install -e .` works.

**Comment by xiaomofang** [comment]
I encountered the same issue. May I ask if you have resolved it?

**Comment by 80boys** [comment]
I encountered the same issue. May I ask if you have resolved it?

**Comment by jamesbraza** [comment]
I am hitting this too, previously with:
- Python 3.12.8, `numpy==1.26.4`, `torch==2.5.1`, `uv==0.5.24` and macOS Darwin 24.1.0 arm64
- Just run `uv cache clean`
- Just run `brew install ninja` (which installed ninja 1.12.1)
- Restarted my terminal

```none
      build/lib.macosx-15.1-arm64-cpython-312/vllm/model_executor/layers/fused_moe/configs
      copying vllm/model_executor/layers/fused_moe/configs/E=1,N=3072,device_name=NVIDIA_H100_80GB_HBM3,dtype=int8_w8a16.json ->
      build/lib.macosx-15.1-arm64-cpython-312/vllm/model_executor/layers/fused_moe/configs
      running build_ext
      -- Configuring incomplete, errors occurred!

      [stderr]
      /Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named
      'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      VLLM_TARGET_DEVICE automatically set to `cpu` due to macOS
      CMake Error at CMakeLists.txt:14 (project):
        Running

         '/Users/user/.cache/uv/builds-v0/.tmpMou2on/bin/ninja' '--version'

        failed with:

         no such file or directory


      Traceback (most recent call last):
        File "<string>", line 11, in <module>
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/build_meta.py", line 435, in build_wheel
          return _build(['bdist_wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 625, in <module>
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 983, in run_commands
          self.run_command(cmd)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 379, in run
          self.run_command("build")
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 339, in run_command
          self.distribution.run_command(command)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_command
          cmd_obj.run()
        File "<string>", line 247, in run
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
        File "/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 365, in run
          self.build_extensions()
        File "<string>", line 206, in build_extensions
        File "<string>", line 184, in configure
        File "/Users/user/.pyenv/versions/3.12.8/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/Users/user/.cache/uv/sdists-v6/pypi/vllm/0.7.0/BskNDIqCX1hzBSXOTGX_K/src', '-G', 'Ninja',
      '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DVLLM_TARGET_DEVICE=cpu', '-DVLLM_PYTHON_EXECUTABLE=/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/bin/python',
      '-DVLLM_PYTHON_PATH=/Users/user/.pyenv/versions/3.12.8/lib/python312.zip:/Users/user/.pyenv/versions/3.12.8/lib/python3.12:/Users/user/.pyenv/versions/3.12.8/lib/python3.12/lib-dynload:/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages:/Users/user/.cache/uv/builds-v0/.tmpr5YqPK/lib/python3.12/site-packages/setuptools/_vendor',
      '-DFETCHCONTENT_BASE_DIR=/Users/user/.cache/uv/sdists-v6/pypi/vllm/0.7.0/BskNDIqCX1hzBSXOTGX_K/src/.deps', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile',
      '-DCMAKE_JOB_POOLS:STRING=compile=11']' returned non-zero exit status 1.

      hint: This usually indicates a problem with the package or the build environment.
```

The issue seems to be `ninja` is not found, what should I do here? I had run `brew install ninja`

**Comment by mgoin** [comment]
@jamesbraza  I think you should not install these with brew and rather through pip. All of the build essentials are in `requirements-cpu.txt`

Please look at the "Apple Silicon" instructions on this page https://docs.vllm.ai/en/latest/getting_started/installation/cpu/index.html

> After installation of XCode and the Command Line Tools, which include Apple Clang, execute the following commands to build and install vLLM from the source.

```
git clone https://github.com/vllm-project/vllm.git
cd vllm
pip install -r requirements-cpu.txt
pip install -e . 
```

**Comment by jamesbraza** [comment]
Hello @mgoin nice to see you, we met at a Mistral happy hour at NeurIPS 2024.

This attempted all-in-one command does not work (too bad):

```bash
uv pip install -r https://raw.githubusercontent.com/vllm-project/vllm/main/requirements-cpu.txt "vllm>=0.7.0"
```

But following your exact instructions does work, thank you

**Comment by RookieChenTaoYu** [comment]
Hello，I also encountered this question using "uv pip install". But after I using the conda environment, it seem not have the question any more. I'm quite confused about it. Does anyone fixed it?

**Comment by mgoin** [comment]
@RookieChenTaoYu could you share your exact commands for uv and approx environment to reproduce?

**Comment by RookieChenTaoYu** [comment]
@mgoin Hello there, I finally resolve this problem, here is my step:
my Environment is `"OS: openEuler 22.03 (LTS-SP4)"`, `"cpu is aarch64"` and use `"uv venv my_env --python 3.10 --seed"`, `python version 3.10.16`, "in docker container"

- I have met three problems outputs below when I using `uv pip install vllm==0.7.3`:

        1. 
        FAILED: CMakeFiles/_C.dir/csrc/cpu/utils.cpp.o
            /usr/bin/c++ -DPy_LIMITED_API=3 -DTORCH_EXTENSION_NAME=_C -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_RPC -DUSE_TENSORPIPE -D_C_EXPORTS
            -I/root/.cache/uv/sdists-v9/pypi/vllm/0.7.3/QLEVgEiVjPTkmg7w-Kh7X/src/csrc -isystem /usr/local/python3.10/include/python3.10
            -isystem /root/.cache/uv/builds-v0/.tmpswQ2Ep/lib/python3.10/site-packages/torch/include -isystem
            /root/.cache/uv/builds-v0/.tmpswQ2Ep/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fopenmp -DVLLM_CPU_EXTENSION
            -march=armv8.2-a+dotprod+fp16 -D_GLIBCXX_USE_CXX11_ABI=0 -MD -MT CMakeFiles/_C.dir/csrc/cpu/utils.cpp.o -MF CMakeFiles/_C.dir/csrc/cpu/utils.cpp.o.d -o
            CMakeFiles/_C.dir/csrc/cpu/utils.cpp.o -c /root/.cache/uv/sdists-v9/pypi/vllm/0.7.3/QLEVgEiVjPTkmg7w-Kh7X/src/csrc/cpu/utils.cpp
            /root/.cache/uv/sdists-v9/pypi/vllm/0.7.3/QLEVgEiVjPTkmg7w-Kh7X/src/csrc/cpu/utils.cpp:2:12: fatal error: numa.h: No such file or directory
                2 |   #include <numa.h>
                  |            ^~~~~~~~
            compilation terminated.
        2. 
        [stderr]
              /root/.cache/uv/builds-v0/.tmp0ajaNt/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named
              'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
                cpu = _conversion_method_template(device=torch.device("cpu"))
              /bin/sh: line 1: lsmod: command not found
              /bin/sh: line 1: lsmod: command not found
              /root/.cache/uv/builds-v0/.tmp0ajaNt/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a
              TOML table is deprecated
        3.  
        CMake Error at CMakeLists.txt:14 (project):
                Running
        
                 '/root/.cache/uv/builds-v0/.tmpswQ2Ep/bin/ninja' '--version'
        
                failed with:
        
                 no such file or directory
        
And I fix the first one using `dnf install numactl-devel`. After install successfully, I executed `uv pip install vllm==0.7.3` again. After the second `uv pip install` try, the first `numa problem` is not showing again, but last two problems still output in my terminal. And I'm so confused don't know how to fix it.

But later, I see one recommend from AI: "uv pip install vllm==0.7.3 --no-cache-dir" this would not use cache function in uv, and this time I download packages from the internet again, but I successfully install vllm this time. 

But in conda environment, when I  `pip install vllm==0.7.3` (in conda environment) also met the first problem about numa, and after `dnf install numactl-devel`, I run the `pip install vllm==0.7.3`, I won't meet the last two problems.

So whether this means that uv would cache some incorrect files make the conflict package version? But conda and pip would not?

**Comment by mgoin** [comment]
There are no prebuilt wheels for ARM, so you need to build from source rather than install the wheel. Please check the installation guides for your machine type https://docs.vllm.ai/en/latest/getting_started/installation.html

**Comment by hmellor** [comment]
Closing as it seems the original issue is resolved.
