### ISSUE TITLE
[Usage]: How can I determine the maximum number of concurrent requests?

### ISSUE THREAD

**Issue by zhangyan1986** [vllm-project/vllm#8031]
### Your current environment

```text
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.27

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-29-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn.so.8.6.0
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.6.0
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.6.0
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.6.0
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.6.0
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.6.0
/home/username/cuda/cuda-11.8/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              80
On-line CPU(s) list: 0-79
Thread(s) per core:  2
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
Stepping:            7
CPU MHz:             1043.433
CPU max MHz:         2501.0000
CPU min MHz:         1000.0000
BogoMIPS:            5000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            28160K
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] transformers==4.41.2
[pip3] triton==2.3.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] transformers              4.41.2                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	0-19,40-59	0		N/A
GPU1	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	0-19,40-59	0		N/A
GPU2	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	0-19,40-59	0		N/A
GPU3	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	0-19,40-59	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PIX	PIX	20-39,60-79	1		N/A
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PIX	PIX	20-39,60-79	1		N/A
GPU6	SYS	SYS	SYS	SYS	PIX	PIX	 X 	PIX	20-39,60-79	1		N/A
GPU7	SYS	SYS	SYS	SYS	PIX	PIX	PIX	 X 	20-39,60-79	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### How would you like to use vllm

I have deployed the QWen2-7B model on a single V100 GPU using vllm and am providing HTTP services through FastAPI. 

Assuming each request has an input of 5000 tokens and an output of 500 tokens, how can I determine the maximum number of concurrent requests that a single V100 can support? 

For example, if the model's inference performance is 50 tokens/s, then when 10 inference tasks are running concurrently, can I assume that the performance for each inference task averages down to 5 tokens/s?

Furthermore, if this maximum number is exceeded, will there be an Out Of Memory issue, or will the requests be handled according to a queuing mechanism?

Currently, I am estimating the GPU requirements for a knowledge base application scenario. Given that evaluating GPU resources differs significantly from traditional IT architecture assessments, I hope you can provide me with more guidance. Thank you.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by AlpinDale** [comment]
A good heuristic is `num_gpu_blocks * block_size / max_model_len`. That should give you the minimum concurrency, i.e. how many concurrent requests with `max_model_len` tokens in them you can handle.

**Comment by ekmekovski** [comment]
I have the same question in my mind, I m makin only 4 worker perform inference rn, I tried with 8 worker but I got OOM error in my responses, so I decided to keep 4 worker to perform inferemce with vLLM but it makes the process slow, so did u come up with a solution? I wonder what is the best way to check the limit, and perform as much as concurrent request or in other words even thousands of client try to perform inference how to avoid getting oom, ı set gpu utilization param but it does not prevent the situation.

**Comment by hmellor** [comment]
KV cache capacity for concurrent requests is now logged on startup

**Comment by hahmad2008** [comment]
@hmellor is it the same of the logged following line?
`Maximum concurrency for 8192 tokens per request: 4.61x` that's mean the model can handle 4.6 of 8k requests?

**Comment by hmellor** [comment]
Yeah, exactly! Or 46 800 token requets, etc.

**Comment by hahmad2008** [comment]
Thanks @hmellor

**Comment by hahmad2008** [comment]
@hmellor  @DarkLight1337 I suppose the model can handle a number of requests at a time, but the remaining requests should be queued, right?
So if I send 20 requests each of 1k tokens to this server that running mistral-24b-AWQ with gpu util: `0.9` and max length is 8k. I suppose there is no OOM should be happen, right? 
However, OOM raised after sending these requests at a time.  the gpu has 24G memory.


```
INFO 04-11 12:11:33 [model_runner.py:1146] Model loading took 14.1373 GiB and 58.211116 seconds
INFO 04-11 12:11:46 [worker.py:267] Memory profiling takes 12.80 seconds
INFO 04-11 12:11:46 [worker.py:267] the current vLLM instance can use total_gpu_memory (21.99GiB) x gpu_memory_utilization (0.90) = 19.79GiB
INFO 04-11 12:11:46 [worker.py:267] model weights take 14.14GiB; non_torch_memory takes 0.06GiB; PyTorch activation peak memory takes 1.98GiB; the rest of the memory reserved for KV Cache is 3.61GiB.
INFO 04-11 12:11:46 [executor_base.py:112] # cuda blocks: 1479, # CPU blocks: 1638
INFO 04-11 12:11:46 [executor_base.py:117] Maximum concurrency for 8192 tokens per request: 2.89x
```

error after sending 20 1k-tokens requests:

```
INFO 04-11 12:35:55 [async_llm_engine.py:211] Added request chatcmpl-e6fb5074773c4e39aeb7fbfee8db758d.

ERROR 04-11 12:35:55 [async_llm_engine.py:68] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 894.00 MiB. GPU 0 has a total capacity of 21.99 GiB of which 91.44 MiB is free. Including non-PyTorch memory, this process has 21.88 GiB memory in use. Of the allocated memory 19.31 GiB is allocated by PyTorch, with 726.00 MiB allocated in private pools (e.g., CUDA Graphs), and 1009.67 MiB is reserved by PyTorch but unallocated. ..

```

This is using VLLM 0.8.3 latest version. I remember when testing similar thing for heavy loading for llama3.1 all requests were queued and no OOM happen.

Any idea please?

**Comment by DarkLight1337** [comment]
Hmm, OOM shouldn't happen during inference time. Can you show the full logs? cc @njhill

**Comment by hahmad2008** [comment]
@DarkLight1337 I defined Asynengin 
`self.engine = AsyncLLMEngine.from_engine_args(engine_args)`
and then call `openai_serving_chat = OpenAIServingChat(`
This is the full logs:

```
O 04-11 12:37:49 [llm_engine.py:242] Initializing a V0 LLM engine (v0.8.3) with config: model='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', speculative_config=None, tokenizer='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
WARNING 04-11 12:37:51 [multiproc_worker_utils.py:306] Reducing Torch parallelism from 8 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 04-11 12:37:51 [cuda.py:292] Using Flash Attention backend.
INFO 04-11 12:37:52 [parallel_state.py:957] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-11 12:37:52 [model_runner.py:1110] Starting to load model OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym...
INFO 04-11 12:37:53 [config.py:3334] cudagraph sizes specified by model runner [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256] is overridden by config [256, 128, 2, 1, 4, 136, 8, 144, 16, 152, 24, 160, 32, 168, 40, 176, 48, 184, 56, 192, 64, 200, 72, 208, 80, 216, 88, 120, 224, 96, 232, 104, 240, 112, 248]
INFO 04-11 12:37:53 [weight_utils.py:265] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  1.54it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.22it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:04<00:01,  1.59s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.59s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.42s/it]

INFO 04-11 12:37:59 [loader.py:447] Loading weights took 5.77 seconds
INFO 04-11 12:37:59 [model_runner.py:1146] Model loading took 14.1373 GiB and 7.263905 seconds
INFO 04-11 12:38:11 [worker.py:267] Memory profiling takes 11.52 seconds
INFO 04-11 12:38:11 [worker.py:267] the current vLLM instance can use total_gpu_memory (21.99GiB) x gpu_memory_utilization (0.88) = 19.35GiB
INFO 04-11 12:38:11 [worker.py:267] model weights take 14.14GiB; non_torch_memory takes 0.06GiB; PyTorch activation peak memory takes 1.98GiB; the rest of the memory reserved for KV Cache is 3.17GiB.
INFO 04-11 12:38:12 [executor_base.py:112] # cuda blocks: 1299, # CPU blocks: 1638
INFO 04-11 12:38:12 [executor_base.py:117] Maximum concurrency for 8192 tokens per request: 2.54x
INFO 04-11 12:38:18 [model_runner.py:1456] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
Capturing CUDA graph shapes: 100%|██████████████████████████████████████████████████████| 35/35 [00:32<00:00,  1.07it/s]
INFO 04-11 12:38:50 [model_runner.py:1598] Graph capturing finished in 33 secs, took 2.00 GiB
INFO 04-11 12:38:50 [llm_engine.py:448] init engine (profile, create kv cache, warmup model) took 50.69 seconds
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

SERVICE: 2025-04-11T12:38:50.732374: Serving Model with BACKEND[VLLM] has been started from the model at this path 'OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym' 

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

INFO:     3.75.28.83:56570 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-2c50332df84b45a98b5501c62aae182f.
INFO:     3.75.28.83:56514 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-ebf80007490f4f56a165081960652c96.
INFO:     3.75.28.83:56526 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-df5dce913d1b4e408c36957694a9163c.
INFO:     3.75.28.83:56528 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-160b4b31df464a208e6499d66071e79f.
INFO:     3.75.28.83:56540 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-2d55953cc4d347839c30bff51d5d8e5d.
INFO:     3.75.28.83:56554 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-1d65b35a05db4ab083d121c3f389456e.
INFO:     3.75.28.83:56642 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-003103712afc4a14b24c9d5249ed85c0.
INFO:     3.75.28.83:56648 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-0929edadf7894c3085d2bf14f07eb281.
INFO:     3.75.28.83:56654 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-1510b2d5559140cc8d6344f6d3368ae9.
INFO:     3.75.28.83:56658 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-013acba8d8254332bc77a16c63099117.
INFO:     3.75.28.83:56662 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-4462e04d6aad40a18973ecf180210e6e.
INFO:     3.75.28.83:56672 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-03bdffe1fda84ccea78e8acf50962dc1.
INFO:     3.75.28.83:56680 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-90038698c6ec416bb81177a30cd1c0e0.
INFO:     3.75.28.83:56578 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-87c70c3ac4154e74a056d0354d4c867c.
INFO:     3.75.28.83:56580 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-fd9e4d6a2ce4446dbf96d4abf24b9bcf.
INFO:     3.75.28.83:56594 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-9c8296f4dc3e4629a9881c8bd1ebafad.
INFO:     3.75.28.83:56604 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-3b026de8299b4559bcf705b3756d0771.
INFO:     3.75.28.83:56612 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-baf3aa8ca7294b8e94b35253f4e718db.
INFO:     3.75.28.83:56626 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-6a830f070bc34aaabb72db273633ff77.
INFO:     3.75.28.83:56682 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 04-11 12:45:10 [async_llm_engine.py:211] Added request chatcmpl-f771d2f27f4743be8d99480c562394b6.
ERROR 04-11 12:45:16 [async_llm_engine.py:68] Engine background task failed
ERROR 04-11 12:45:16 [async_llm_engine.py:68] Traceback (most recent call last):
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 58, in _log_task_completion
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return_value = task.result()
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 859, in run_engine_loop
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     result = task.result()
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 782, in engine_step
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 356, in step_async
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     outputs = await self.model_executor.execute_model_async(
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 369, in execute_model_async
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return await self._driver_execute_model_async(execute_model_req)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/executor/mp_distributed_executor.py", line 209, in _driver_execute_model_async
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return await self.driver_exec_model(execute_model_req)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/concurrent/futures/thread.py", line 58, in run
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     result = self.fn(*self.args, **self.kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     output = self.model_runner.execute_model(
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return func(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 1770, in execute_model
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     hidden_or_intermediate_states = model_executable(
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return self._call_impl(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return forward_call(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/model_executor/models/mistral3.py", line 634, in forward
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     hidden_states = self.language_model.model(input_ids,
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/compilation/decorators.py", line 172, in __call__
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return self.forward(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 360, in forward
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     hidden_states, residual = layer(positions, hidden_states, residual)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return self._call_impl(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return forward_call(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 286, in forward
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     hidden_states = self.mlp(hidden_states)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return self._call_impl(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return forward_call(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 92, in forward
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     x, _ = self.gate_up_proj(x)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return self._call_impl(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     return forward_call(*args, **kwargs)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 474, in forward
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     output_parallel = self.quant_method.apply(self, input_, bias)
ERROR 04-11 12:45:16 [async_llm_engine.py:68]   File "/lib/python3.9/site-packages/vllm/model_executor/layers/quantization/awq.py", line 178, in apply
ERROR 04-11 12:45:16 [async_llm_engine.py:68]     out = torch.matmul(reshaped_x, out)
ERROR 04-11 12:45:16 [async_llm_engine.py:68] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 896.00 MiB. GPU 0 has a total capacity of 21.99 GiB of which 499.44 MiB is free. Including non-PyTorch memory, this process has 21.48 GiB memory in use. Of the allocated memory 18.90 GiB is allocated by PyTorch, with 726.00 MiB allocated in private pools (e.g., CUDA Graphs), and 1018.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Exception in callback functools.partial(<function _log_task_completion at 0x7f4748d5f430>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f4789ab3880>>)
handle: <Handle functools.partial(<function _log_task_completion at 0x7f4748d5f430>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f4789ab3880>>)>

```

**Comment by DarkLight1337** [comment]
Hmm, quite a few people have reported OOM when using quantized models. Not sure whether this is the same issue. @mgoin any idea?

**Comment by hahmad2008** [comment]
@DarkLight1337 @hmellor @mgoin 
What used the same `AsyncLLMEngine` and the endpoint `OpenAIServingChat` of vllm, but I checked that the TTFT is slower for the my serve than the one on vllm although they have the exact configurations. when I checked the logged engine on the terminal I checked that they have the only difference is that the value of `use_cached_outputs` which is enabled in vllm but not in my definition of async. btw this `use_cached_outputs` arg is not exposed outside to be set from command args. Any idea please?

my setup: 
```
INFO 04-11 19:28:50 [llm_engine.py:242] Initializing a V0 LLM engine (v0.8.3) with config: model='NousResearch/Meta-Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='NousResearch/Meta-Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=NousResearch/Meta-Llama-3.1-8B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
```

vllm
```
INFO 04-11 19:09:20 [llm_engine.py:242] Initializing a V0 LLM engine (v0.8.3) with config: model='NousResearch/Meta-Llama-3.1-8B-Instruct',       speculative_config=None, tokenizer='NousResearch/Meta-Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=NousResearch/Meta-Llama-3.1-8B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
```

**Comment by DarkLight1337** [comment]
cc @robertgshaw2-redhat
