### ISSUE TITLE
[Usage]: Using TPU example with InternVL2 Model

### ISSUE THREAD

**Issue by radna0** [vllm-project/vllm#8065]
### Your current environment

```
Collecting environment information...
Traceback (most recent call last):
  File "/home/kojoe/EasyAnimate/easyanimate/image_caption/collect_env.py", line 735, in <module>
    main()
  File "/home/kojoe/EasyAnimate/easyanimate/image_caption/collect_env.py", line 714, in main
    output = get_pretty_env_info()
  File "/home/kojoe/EasyAnimate/easyanimate/image_caption/collect_env.py", line 709, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/kojoe/EasyAnimate/easyanimate/image_caption/collect_env.py", line 510, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "/home/kojoe/EasyAnimate/easyanimate/image_caption/collect_env.py", line 480, in get_pip_packages
    out = run_with_pip([sys.executable, '-mpip'])
  File "/home/kojoe/EasyAnimate/easyanimate/image_caption/collect_env.py", line 476, in run_with_pip
    return "\n".join(line for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

### How would you like to use vllm

I want to run inference of a [OpenGVLab/InternVL2-8B](https://huggingface.co/OpenGVLab/InternVL2-8B). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
> `run_with_pip([sys.executable, '-mpip'])`

Looks like you made a typo here. You are missing a space between `-m` and `pip`.

**Comment by radna0** [comment]
The problem with collecting the envs doesn't seem to be  that, I run with and without space, it gives same error

**Comment by DarkLight1337** [comment]
cc @youkaichao

**Comment by youkaichao** [comment]
did you have tpu environment installed?

the collect env script works fine on my tpu pod.

**Comment by radna0** [comment]
yes I do @youkaichao, I don't know why the env script doesn't work on my end.
