### ISSUE TITLE
Index error after configuration changes

### ISSUE THREAD

**Issue by ridiculouz** [vllm-project/vllm#808]
Hi there,
Previously I run into an exception showing that there is no enough swap space, as in #787 . I modify the parameter `swap_space` in `EngineArgs` from 4 to 32 accordingly, and the number of CPU blocks raise proportionally.
However, I encounter another `IndexError` exception:
```
Traceback (most recent call last):
  File "yyy.py", line 65, in main
    outputs = llm.generate(prompts, sampling_params)
  File "/xxx/.local/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 130, in generate
    return self._run_engine(use_tqdm)
  File "/xxx/.local/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 150, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/xxx/.local/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 313, in step
    output = self._run_workers(
  File "/xxx/.local/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 470, in _run_workers
    output = executor(*args, **kwargs)
  File "/xxx/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/xxx/.local/lib/python3.9/site-packages/vllm/worker/worker.py", line 289, in execute_model
    input_tokens, input_positions, input_metadata = self._prepare_inputs(
  File "/xxx/.local/lib/python3.9/site-packages/vllm/worker/worker.py", line 220, in _prepare_inputs
    block_number = block_table[position // self.block_size]
IndexError: list index out of range
``` 
I also print out `len(block_table)`, `position` and `self.block_size`, and I find that it won't occur if the length of `block_table` is 8 times larger (32/4). So I wonder if I can bypass this issue with other configurations, or where do I need to change the source code?
Thanks. @zhuohan123

**Comment by ridiculouz** [comment]
Hi @WoosukKwon , also would you look into this issue a bit when you are available? Big thanks in advance!

**Comment by ToheartZhang** [comment]
Hi, same issue here, could you share how to raise the number of CPU blocks?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
