### ISSUE TITLE
[Bug]: ValueError: Queue <multiprocessing.queues.Queue object at 0x7f5703d2d0f0> is closed;zipfile.BadZipFile: Bad magic number for file header

### ISSUE THREAD

**Issue by Jiangchenglin521** [vllm-project/vllm#8101]
### Your current environment

<details>
my device: cuda 11.8
vllm version: vllm-0.5.5
torch is suitable with cuda and  vllm
python 3.10

</details>

### 🐛 Describe the bug

My env is ready, **Only!!!!!** it works successfully **at first time**。
If running after time, there always got the error bellow:
```text
INFO 09-03 15:47:02 config.py:813] Defaulting to use mp for distributed inference
INFO 09-03 15:47:02 llm_engine.py:184] Initializing an LLM engine (v0.5.5) with config: model='/root/paddlejob/workspace/env_run/output/ckpts/qwen2-7b-instruct', speculative_config=None, tokenizer='/root/paddlejob/workspace/env_run/output/ckpts/qwen2-7b-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/root/paddlejob/workspace/env_run/output/ckpts/qwen2-7b-instruct, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 09-03 15:47:02 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=85762) Process VllmWorkerProcess:
(VllmWorkerProcess pid=85762) Traceback (most recent call last):
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(VllmWorkerProcess pid=85762)     self.run()
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
(VllmWorkerProcess pid=85762)     self._target(*self._args, **self._kwargs)
(VllmWorkerProcess pid=85762)   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 210, in _run_worker_process
(VllmWorkerProcess pid=85762)     worker = worker_factory()
(VllmWorkerProcess pid=85762)   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 23, in create_worker
(VllmWorkerProcess pid=85762)     wrapper.init_worker(**kwargs)
(VllmWorkerProcess pid=85762)   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 436, in init_worker
(VllmWorkerProcess pid=85762)     load_general_plugins()
(VllmWorkerProcess pid=85762)   File "/usr/local/lib/python3.10/dist-packages/vllm/plugins/__init__.py", line 21, in load_general_plugins
(VllmWorkerProcess pid=85762)     discovered_plugins = entry_points(group='vllm.general_plugins')
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
(VllmWorkerProcess pid=85762)     return SelectableGroups.load(eps).select(**params)
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
(VllmWorkerProcess pid=85762)     ordered = sorted(eps, key=by_group)
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
(VllmWorkerProcess pid=85762)     eps = itertools.chain.from_iterable(
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
(VllmWorkerProcess pid=85762)     k = key(element)
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
(VllmWorkerProcess pid=85762)     or super()._normalized_name
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
(VllmWorkerProcess pid=85762)     return Prepared.normalize(self.name)
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 617, in name
(VllmWorkerProcess pid=85762)     return self.metadata['Name']
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 606, in metadata
(VllmWorkerProcess pid=85762)     or self.read_text('PKG-INFO')
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 927, in read_text
(VllmWorkerProcess pid=85762)     return self._path.joinpath(filename).read_text(encoding='utf-8')
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/zipfile.py", line 2380, in read_text
(VllmWorkerProcess pid=85762)     with self.open('r', encoding, *args, **kwargs) as strm:
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/zipfile.py", line 2361, in open
(VllmWorkerProcess pid=85762)     stream = self.root.open(self.at, zip_mode, pwd=pwd)
(VllmWorkerProcess pid=85762)   File "/usr/lib/python3.10/zipfile.py", line 1537, in open
(VllmWorkerProcess pid=85762)     raise BadZipFile("Bad magic number for file header")
(VllmWorkerProcess pid=85762) zipfile.BadZipFile: Bad magic number for file header
ERROR 09-03 15:47:02 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 85762 died, exit code: 1
INFO 09-03 15:47:02 multiproc_worker_utils.py:123] Killing local vLLM worker processes
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 169, in _enqueue_task
    self._task_queue.put((task_id, method, args, kwargs))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 88, in put
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x7f5703d2d0f0> is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/output/baidu/personal-code/llm-edu/llm_edu/model_eval/evaluate_qwen15_test.py", line 10, in <module>
    llm = LLM(
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py", line 175, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 473, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 270, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 46, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 137, in _init_executor
    self._run_workers("init_device")
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 186, in _run_workers
    worker_outputs = [
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 187, in <listcomp>
    worker.execute_method(method, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 176, in execute_method
    self._enqueue_task(future, method, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_worker_utils.py", line 172, in _enqueue_task
    raise ChildProcessError("worker died") from e
ChildProcessError: worker died
```

**is this a big bug ?????**

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by hengran** [comment]
I also meet this problem.

**Comment by SpursGoZmy** [comment]
It works fine with 'tensor_parallel_size=1' and 'LLama-3.1-8B-Instruct', but I got the same problem when setting 'tensor_parallel_size>1' such as 8. 

My env: CUDA==12.3, torch==2.4.0, vllm==2.6.1. I also try vllm==2.6.2 or 2.6.3, but I still got this problem.

**Comment by SpursGoZmy** [comment]
> It works fine with 'tensor_parallel_size=1' and 'LLama-3.1-8B-Instruct', but I got the same problem when setting 'tensor_parallel_size>1' such as 8.
> 
> My env: python3.10, CUDA==12.3, torch==2.4.0, vllm==0.6.1. I also try vllm==0.6.2 or 0.6.3, but I still got this problem.

My situation is the same with the @Jiangchenglin521. After `pip install vllm==0.6.2`, first run with tensor_parallel_size=8 is OK. But it will always throws the bug after the first run.

**Comment by SpursGoZmy** [comment]
The problem is because the vllm manages the distributed runtime with either [Ray](https://github.com/ray-project/ray) or python native multiprocessing (by default) package. In my case, there is something wrong with the python native multiprocessing, so **changing the 'distributed-executor-backend' to 'ray' solved my problem.**

You can change this setting via the LLM class `distributed-executor-backend` argument or `--distributed-executor-backend` API server argument, as mentioned by the vllm [documention](https://docs.vllm.ai/en/latest/serving/distributed_serving.html). For instance, set `distributed_executor_backend="ray"` when initializing LLM engine:
```python
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

model_name = "openbmb/MiniCPM3-4B"
prompt = [{"role": "user", "content": "推荐5个北京的景点。"}]

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
input_text = tokenizer.apply_chat_template(prompt, tokenize=False, add_generation_prompt=True)

llm = LLM(
    model=model_name,
    trust_remote_code=True,
    tensor_parallel_size=1,
   distributed_executor_backend="ray"
)
sampling_params = SamplingParams(top_p=0.7, temperature=0.7, max_tokens=1024, repetition_penalty=1.02)

outputs = llm.generate(prompts=input_text, sampling_params=sampling_params)

print(outputs[0].outputs[0].text)
```
