### ISSUE TITLE
[Bug]: The error encountered when deploying the MiniCPM-2B model in a CPU environment using the VLLM framework

### ISSUE THREAD

**Issue by liuzhipengchd** [vllm-project/vllm#8110]
### Your current environment

Support for OpenVINO on CPU-based VLLM environment
Official documentation states that VLLM supports the MiniCPM-2B model

```text
optimum-cli export openvino -m MiniCPM-2B --task text-generation-with-past --weight-format int4
```

### 🐛 Describe the bug

root@2ae2daef803e:~# optimum-cli export openvino -m MiniCPM-2B --task text-generation-with-past --weight-format int4   MiniCPM-2B-int4
Framework not specified. Using pt to export the model.
Traceback (most recent call last):
  File "/usr/local/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/optimum_cli.py", line 208, in main
    service.run()
  File "/usr/local/lib/python3.10/dist-packages/optimum/commands/export/openvino.py", line 356, in run
    main_export(
  File "/usr/local/lib/python3.10/dist-packages/optimum/exporters/openvino/__main__.py", line 214, in main_export
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 975, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 640, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading MiniCPM-2B requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by liuzhipengchd** [comment]
In a GPU environment, deploying the MiniCPM-2B program is normal.


CUDA_VISIBLE_DEVICES=1 python3 -m vllm.entrypoints.openai.api_server   --model /root/wxp/wingpt_model/MiniCPM-2B --served-model-name MiniCPM-2B --trust-remote-code --port 26033

**Comment by DarkLight1337** [comment]
As mentioned in the error, you need set `--trust-remote-code` in the CLI.

**Comment by liuzhipengchd** [comment]
> As mentioned in the error, you need to set `--trust-remote-code` in the CLI.

I added the `--trust-remote-code` flag, and the model quantization was successful. Then I executed the command:
```
CUDA_VISIBLE_DEVICES=1 python3 -m vllm.entrypoints.openai.api_server --model /root/wxp/wingpt_model/MiniCPM-2B --served-model-name MiniCPM-2B --trust-remote-code --port 26033
```
However, I encountered an error: `ModuleNotFoundError: No module named 'triton'`.
However, when I run the llama3 model, there are no errors.


Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 222, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 26, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(async_engine_args,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 735, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 631, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 830, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 267, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 289, in __init__
    get_architecture_class_name(model_config),
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/utils.py", line 35, in get_architecture_class_name
    return get_model_architecture(model_config)[1]
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/utils.py", line 31, in get_model_architecture
    return ModelRegistry.resolve_model_cls(architectures)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/__init__.py", line 161, in resolve_model_cls
    model_cls = ModelRegistry._try_load_model_cls(arch)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/__init__.py", line 155, in _try_load_model_cls
    return ModelRegistry._get_model(model_arch)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/__init__.py", line 135, in _get_model
    module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/minicpm.py", line 37, in <module>
    from vllm.model_executor.layers.fused_moe import fused_moe
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 8, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

**Comment by liuzhipengchd** [comment]
> > As mentioned in the error, you need to set `--trust-remote-code` in the CLI.
> 
> Thank you I added the `--trust-remote-code` flag, and the model quantization was successful. Then I executed the command:
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python3 -m vllm.entrypoints.openai.api_server --model /root/wxp/wingpt_model/MiniCPM-2B --served-model-name MiniCPM-2B --trust-remote-code --port 26033
> ```
> 
> However, I encountered an error: `ModuleNotFoundError: No module named 'triton'`. However, when I run the llama3 model, there are no errors.
> 
> Traceback (most recent call last): File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 222, in run_rpc_server server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path) File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 26, in **init** self.engine = AsyncLLMEngine.from_engine_args(async_engine_args, File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 735, in from_engine_args engine = cls( File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 631, in **init** self.engine = self._init_engine(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 830, in _init_engine return engine_class(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 267, in **init** super().**init**(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 289, in **init** get_architecture_class_name(model_config), File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/utils.py", line 35, in get_architecture_class_name return get_model_architecture(model_config)[1] File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/utils.py", line 31, in get_model_architecture return ModelRegistry.resolve_model_cls(architectures) File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/**init**.py", line 161, in resolve_model_cls model_cls = ModelRegistry._try_load_model_cls(arch) File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/**init**.py", line 155, in _try_load_model_cls return ModelRegistry._get_model(model_arch) File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/**init**.py", line 135, in _get_model module = importlib.import_module( File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/minicpm.py", line 37, in from vllm.model_executor.layers.fused_moe import fused_moe File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 8, in import triton ModuleNotFoundError: No module named 'triton'

pip install triton is ok

**Comment by kim90000** [comment]
>>>
>>>
>>>
>>>
>>>
>>> from vllm import LLM
INFO 04-04 16:23:16 [__init__.py:239] Automatically detected platform cuda.
>>> llm = LLM(model="facebook/opt-125m")
INFO 04-04 16:23:35 [config.py:586] This model supports multiple tasks: {'generate', 'embed', 'reward', 'score', 'classify'}. Defaulting to 'generate'.
INFO 04-04 16:23:35 [config.py:1701] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 04-04 16:23:44 [__init__.py:239] Automatically detected platform cuda.
INFO 04-04 16:23:48 [core.py:55] Initializing a V1 LLM engine (v0.8.2+cu124) with config: model='facebook/opt-125m', speculative_config=None, tokenizer='facebook/opt-125m', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=facebook/opt-125m, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
INFO 04-04 16:23:48 [cuda_wrapper.py:93] VLLM_CUDART_SO_PATH resolved to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin\cudart64_12.dll
ERROR 04-04 16:23:48 [core.py:344] EngineCore hit an exception: Traceback (most recent call last):
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\v1\engine\core.py", line 336, in run_engine_core
ERROR 04-04 16:23:48 [core.py:344]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 04-04 16:23:48 [core.py:344]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\v1\engine\core.py", line 291, in __init__
ERROR 04-04 16:23:48 [core.py:344]     super().__init__(vllm_config, executor_class, log_stats)
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\v1\engine\core.py", line 61, in __init__
ERROR 04-04 16:23:48 [core.py:344]     self.model_executor = executor_class(vllm_config)
ERROR 04-04 16:23:48 [core.py:344]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\executor\executor_base.py", line 52, in __init__
ERROR 04-04 16:23:48 [core.py:344]     self._init_executor()
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\executor\uniproc_executor.py", line 45, in _init_executor
ERROR 04-04 16:23:48 [core.py:344]     self.collective_rpc("init_worker", args=([kwargs], ))
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\executor\uniproc_executor.py", line 56, in collective_rpc
ERROR 04-04 16:23:48 [core.py:344]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 04-04 16:23:48 [core.py:344]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\utils.py", line 2267, in run_method
ERROR 04-04 16:23:48 [core.py:344]     return func(*args, **kwargs)
ERROR 04-04 16:23:48 [core.py:344]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\worker\worker_base.py", line 558, in init_worker
ERROR 04-04 16:23:48 [core.py:344]     worker_class = resolve_obj_by_qualname(
ERROR 04-04 16:23:48 [core.py:344]                    ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\utils.py", line 1917, in resolve_obj_by_qualname
ERROR 04-04 16:23:48 [core.py:344]     module = importlib.import_module(module_name)
ERROR 04-04 16:23:48 [core.py:344]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
ERROR 04-04 16:23:48 [core.py:344]     return _bootstrap._gcd_import(name[level:], package, level)
ERROR 04-04 16:23:48 [core.py:344]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-04 16:23:48 [core.py:344]   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
ERROR 04-04 16:23:48 [core.py:344]   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
ERROR 04-04 16:23:48 [core.py:344]   File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
ERROR 04-04 16:23:48 [core.py:344]   File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
ERROR 04-04 16:23:48 [core.py:344]   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
ERROR 04-04 16:23:48 [core.py:344]   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\v1\worker\gpu_worker.py", line 26, in <module>
ERROR 04-04 16:23:48 [core.py:344]     from vllm.v1.worker.gpu_model_runner import GPUModelRunner
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\v1\worker\gpu_model_runner.py", line 20, in <module>
ERROR 04-04 16:23:48 [core.py:344]     from vllm.model_executor.layers.fused_moe import FusedMoE
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\model_executor\layers\fused_moe\__init__.py", line 6, in <module>
ERROR 04-04 16:23:48 [core.py:344]     from vllm.model_executor.layers.fused_moe.layer import (
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\model_executor\layers\fused_moe\layer.py", line 26, in <module>
ERROR 04-04 16:23:48 [core.py:344]     from .fused_moe import fused_experts
ERROR 04-04 16:23:48 [core.py:344]   File "C:\Users\TARGET STORE\Desktop\1\venv\Lib\site-packages\vllm\model_executor\layers\fused_moe\fused_moe.py", line 9, in <module>
ERROR 04-04 16:23:48 [core.py:344]     import triton
ERROR 04-04 16:23:48 [core.py:344] ModuleNotFoundError: No module named 'triton'
ERROR 04-04 16:23:48 [core.py:344]

(venv) C:\Users\TARGET STORE\Desktop\1\vllm-windows\examples\offline_inference\basic>

**Comment by DarkLight1337** [comment]
You need to pip install triton
