### ISSUE TITLE
OpenAI-Compatible Server throwing error inside Docker

### ISSUE THREAD

**Issue by 0xPankaj** [vllm-project/vllm#826]
After using this command inside the docker container  " python -m vllm.entrypoints.openai.api_server \
--model facebook/opt-125m " 

root@e4c01cdbf8f2:/workspace# python -m vllm.entrypoints.openai.api_server     --model facebook/opt-125m
INFO 08-22 09:09:12 llm_engine.py:70] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 589, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 101, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 119, in _init_workers
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader.py", line 9, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.baichuan import (BaiChuanForCausalLM,
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/baichuan.py", line 33, in <module>
    from vllm.model_executor.layers.activation import SiluAndMul
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: /usr/local/lib/python3.8/dist-packages/vllm/activation_ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by theoxo** [comment]
Interesting. I can't reproduce your error but am also getting an error when trying to use the OpenAI-compatible server on the docker image:

```
python -m vllm.entrypoints.openai.api_server --model facebook/opt-125m
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 21, in <module>
    from vllm.entrypoints.openai.protocol import (
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/protocol.py", line 106, in <module>
    class CompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

Maybe a recent PR broke the OpenAI server?

**Comment by codybum** [comment]
Same here when installing from package or source.

**Comment by 0xPankaj** [comment]
I solved this by increasing --shm-size=8gb to 25gb in docker run command.

**Comment by allenhaozi** [comment]
met same error
```
+ python3 -m vllm.entrypoints.openai.api_server --model qwen/Qwen-7B-Chat --tensor-parallel-size 8 --trust-remote-code
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 21, in <module>
    from vllm.entrypoints.openai.protocol import (
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/protocol.py", line 107, in <module>
    class CompletionResponseChoice(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

```

**Comment by aizaiyishunjian** [comment]
I solved this by
original:
from typing import Dict, List, Literal, Optional, Union
modify:
from typing import Dict, List, Optional, Union
from typing_extensions import Literal

**Comment by allenhaozi** [comment]
> met same error
> 
> ```
> + python3 -m vllm.entrypoints.openai.api_server --model qwen/Qwen-7B-Chat --tensor-parallel-size 8 --trust-remote-code
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 21, in <module>
>     from vllm.entrypoints.openai.protocol import (
>   File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/protocol.py", line 107, in <module>
>     class CompletionResponseChoice(BaseModel):
>   File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
>   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
>   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
>   File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
>   File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
>   File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
>   File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
>     return issubclass(cls, self.__origin__)
> TypeError: issubclass() arg 1 must be a class
> ```

solved by use the following dockerfile:
```dockerfile
FROM nvcr.io/nvidia/pytorch:22.12-py3

RUN pip uninstall torch -y

RUN pip install vllm  


RUN pip install tiktoken 
RUN pip install fschat==0.2.23 

RUN pip uninstall transformer-engine -y

RUN pip install typing-inspect==0.8.0 typing_extensions==4.5.0 
```

**Comment by mohiitaa** [comment]
I got the same error around `activation_ops`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/vllm/entrypoints/api_server.py", line 80, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 452, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 252, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/vllm/engine/async_llm_engine.py", line 281, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 145, in _init_workers_ray
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/workspace/vllm/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/workspace/vllm/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/workspace/vllm/vllm/model_executor/model_loader.py", line 10, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/workspace/vllm/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.aquila import AquilaForCausalLM
  File "/workspace/vllm/vllm/model_executor/models/aquila.py", line 34, in <module>
    from vllm.model_executor.layers.activation import SiluAndMul
  File "/workspace/vllm/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: cannot import name 'activation_ops' from 'vllm' (/workspace/vllm/vllm/__init__.py)
```

Did anyone find a way to fix it?

**Comment by fredespi** [comment]
I really appreciate the effort put into this project and I have tried to help as well by answering a few questions in issues. But I have to ask because I am confused: I built my own docker image for vllm around version 0.1.3 and I had to include the fixes above to make it work. Now the release is at 0.2.0 and those fixes are still necessary. Why?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
