### ISSUE TITLE
[Usage]: Throughput and quality issue with vllm 0.6.0.

### ISSUE THREAD

**Issue by Agrawalchitranshu** [vllm-project/vllm#8284]
As per vllm community, vllm 0.6.0 is improved version with 5x throughput. I have installed vllm==0.6.0 but the throughput remains same as earlier. Also the response quality of output is degraded in this version.
Has anyone faced similar issue with this version?

**Comment by double-vin** [comment]
I encountered the following openai error:
>>> import vllm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/vllm0.6.0/lib/python3.10/site-packages/vllm/__init__.py", line 6, in <module>
    from vllm.entrypoints.llm import LLM
  File "/opt/miniconda3/envs/vllm0.6.0/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 8, in <module>
    from vllm.entrypoints.chat_utils import (ChatCompletionMessageParam,
  File "/opt/miniconda3/envs/vllm0.6.0/lib/python3.10/site-packages/vllm/entrypoints/chat_utils.py", line 17, in <module>
    from openai.types.chat import (ChatCompletionContentPartRefusalParam,
ImportError: cannot import name 'ChatCompletionContentPartRefusalParam' from 'openai.types.chat' (/opt/miniconda3/envs/vllm0.6.0/lib/python3.10/site-packages/openai/types/chat/__init__.py)
>>> exit()

**Comment by cpwan** [comment]
On a RTX4090, llama3.1 8B fp8

v0.5.3 gives 90 tok/s 
v0.6.0 gives 87 tok/s

Both with the same argument
 `--max-model-len 80000 -q fp8`

I was using the official docker images. Cuda12.4. Nvidia Driver 550.
