### ISSUE TITLE
[Bug]: vllm 0.5.4 NCCL error when applying speculative decoding

### ISSUE THREAD

**Issue by Armod-I** [vllm-project/vllm#8286]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.30.2
Libc version: glibc-2.31

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A800 80GB PCIe
GPU 1: NVIDIA A800 80GB PCIe
GPU 2: NVIDIA A800 80GB PCIe
GPU 3: NVIDIA A800 80GB PCIe
GPU 4: NVIDIA A800 80GB PCIe
GPU 5: NVIDIA A800 80GB PCIe
GPU 6: NVIDIA A800 80GB PCIe
GPU 7: NVIDIA A800 80GB PCIe

Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          72
On-line CPU(s) list:             0-71
Thread(s) per core:              2
Core(s) per socket:              18
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         963.849
CPU max MHz:                     3600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6000.00
Virtualization:                  VT-x
L1d cache:                       1.7 MiB
L1i cache:                       1.1 MiB
L2 cache:                        45 MiB
L3 cache:                        78 MiB
NUMA node0 CPU(s):               0-17,36-53
NUMA node1 CPU(s):               18-35,54-71
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flashinfer==0.1.3+cu121torch2.4
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.555.43
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.20
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.1.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.44.0
[pip3] triton==3.0.0
[pip3] zmq==0.0.0
[conda] flashinfer                0.1.3+cu121torch2.4          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.555.43                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.20                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.1.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.44.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
[conda] zmq                       0.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.4@4db5176d9758b720b05460c50ace3c01026eb158
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PXB     PXB     SYS     SYS     SYS     SYS     0-17,36-53      0               N/A
GPU1    PIX      X      PXB     PXB     SYS     SYS     SYS     SYS     0-17,36-53      0               N/A
GPU2    PXB     PXB      X      PXB     SYS     SYS     SYS     SYS     0-17,36-53      0               N/A
GPU3    PXB     PXB     PXB      X      SYS     SYS     SYS     SYS     0-17,36-53      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      PIX     PXB     PXB     18-35,54-71     1               N/A
GPU5    SYS     SYS     SYS     SYS     PIX      X      PXB     PXB     18-35,54-71     1               N/A
GPU6    SYS     SYS     SYS     SYS     PXB     PXB      X      PXB     18-35,54-71     1               N/A
GPU7    SYS     SYS     SYS     SYS     PXB     PXB     PXB      X      18-35,54-71     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

</details>

### 🐛 Describe the bug

I deployed the inference service for the Qwen2 72B model using VLLM on 4 GPUs in the server. When I try to enable speculative decoding, I always encounter an NCCL error. I attempted to run the debug test code and found that the code cannot run properly. However, when I do not use speculative decoding, the service starts normally

here is the output when running debug test code by `NCCL_DEBUG=TRACE VLLM_LOGGING_LEVEL=DEBUG torchrun --nproc-per-node=2 test.py`:
```
W0909 07:11:11.638000 140533383049856 torch/distributed/run.py:779]
W0909 07:11:11.638000 140533383049856 torch/distributed/run.py:779] *****************************************
W0909 07:11:11.638000 140533383049856 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W0909 07:11:11.638000 140533383049856 torch/distributed/run.py:779] *****************************************
0f139cc8454d:9292:9292 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.15<0>
0f139cc8454d:9292:9292 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
0f139cc8454d:9292:9292 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.20.5+cuda12.4
0f139cc8454d:9293:9293 [1] NCCL INFO cudaDriverVersion 12040
0f139cc8454d:9293:9293 [1] NCCL INFO Bootstrap : Using eth0:172.17.0.15<0>
0f139cc8454d:9293:9293 [1] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
0f139cc8454d:9292:9303 [0] NCCL INFO Failed to open libibverbs.so[.1]
0f139cc8454d:9292:9303 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.15<0>
0f139cc8454d:9292:9303 [0] NCCL INFO Using non-device net plugin version 0
0f139cc8454d:9292:9303 [0] NCCL INFO Using network Socket
0f139cc8454d:9293:9304 [1] NCCL INFO Failed to open libibverbs.so[.1]
0f139cc8454d:9293:9304 [1] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.15<0>
0f139cc8454d:9293:9304 [1] NCCL INFO Using non-device net plugin version 0
0f139cc8454d:9293:9304 [1] NCCL INFO Using network Socket
0f139cc8454d:9293:9304 [1] NCCL INFO comm 0x8dd1bb0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 36000 commId 0xe3a00e76c370ccd8 - Init START
0f139cc8454d:9292:9303 [0] NCCL INFO comm 0x7615fe0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 35000 commId 0xe3a00e76c370ccd8 - Init START
0f139cc8454d:9293:9304 [1] NCCL INFO Setting affinity for GPU 1 to 3ffff0,0003ffff
0f139cc8454d:9292:9303 [0] NCCL INFO Setting affinity for GPU 0 to 3ffff0,0003ffff
0f139cc8454d:9293:9304 [1] NCCL INFO comm 0x8dd1bb0 rank 1 nRanks 2 nNodes 1 localRanks 2 localRank 1 MNNVL 0
0f139cc8454d:9292:9303 [0] NCCL INFO comm 0x7615fe0 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 00/04 :    0   1
0f139cc8454d:9293:9304 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3] 0/-1/-1->1->-1
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 01/04 :    0   1
0f139cc8454d:9293:9304 [1] NCCL INFO P2P Chunksize set to 131072
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 02/04 :    0   1
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 03/04 :    0   1
0f139cc8454d:9292:9303 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3] -1/-1/-1->0->1
0f139cc8454d:9292:9303 [0] NCCL INFO P2P Chunksize set to 131072
0f139cc8454d:9293:9304 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9293:9304 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9293:9304 [1] NCCL INFO Channel 02/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 02/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9293:9304 [1] NCCL INFO Channel 03/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9292:9303 [0] NCCL INFO Channel 03/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9292:9303 [0] NCCL INFO Connected all rings
0f139cc8454d:9292:9303 [0] NCCL INFO Connected all trees
0f139cc8454d:9293:9304 [1] NCCL INFO Connected all rings
0f139cc8454d:9293:9304 [1] NCCL INFO Connected all trees
0f139cc8454d:9293:9304 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
0f139cc8454d:9293:9304 [1] NCCL INFO 4 coll channels, 0 collnet channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
0f139cc8454d:9292:9303 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
0f139cc8454d:9292:9303 [0] NCCL INFO 4 coll channels, 0 collnet channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
0f139cc8454d:9293:9304 [1] NCCL INFO comm 0x8dd1bb0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 36000 commId 0xe3a00e76c370ccd8 - Init COMPLETE
0f139cc8454d:9292:9303 [0] NCCL INFO comm 0x7615fe0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 35000 commId 0xe3a00e76c370ccd8 - Init COMPLETE
PyTorch NCCL is successful!
PyTorch NCCL is successful!
PyTorch GLOO is successful!PyTorch GLOO is successful!

INFO 09-09 07:11:15 utils.py:841] Found nccl from library libnccl.so.2
INFO 09-09 07:11:15 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 09-09 07:11:15 utils.py:841] Found nccl from library libnccl.so.2
INFO 09-09 07:11:15 pynccl.py:63] vLLM is using nccl==2.20.5
0f139cc8454d:9292:9292 [0] NCCL INFO Using non-device net plugin version 0
0f139cc8454d:9292:9292 [0] NCCL INFO Using network Socket
0f139cc8454d:9293:9293 [1] NCCL INFO Using non-device net plugin version 0
0f139cc8454d:9293:9293 [1] NCCL INFO Using network Socket
0f139cc8454d:9292:9292 [0] NCCL INFO comm 0xb11daf0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 35000 commId 0xec26133fb195a6f8 - Init START
0f139cc8454d:9293:9293 [1] NCCL INFO comm 0xc9e40f0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 36000 commId 0xec26133fb195a6f8 - Init START
0f139cc8454d:9292:9292 [0] NCCL INFO Setting affinity for GPU 0 to 3ffff0,0003ffff
0f139cc8454d:9293:9293 [1] NCCL INFO Setting affinity for GPU 1 to 3ffff0,0003ffff
0f139cc8454d:9292:9292 [0] NCCL INFO comm 0xb11daf0 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 00/04 :    0   1
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 01/04 :    0   1
0f139cc8454d:9293:9293 [1] NCCL INFO comm 0xc9e40f0 rank 1 nRanks 2 nNodes 1 localRanks 2 localRank 1 MNNVL 0
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 02/04 :    0   1
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 03/04 :    0   1
0f139cc8454d:9292:9292 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3] -1/-1/-1->0->1
0f139cc8454d:9292:9292 [0] NCCL INFO P2P Chunksize set to 131072
0f139cc8454d:9293:9293 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3] 0/-1/-1->1->-1
0f139cc8454d:9293:9293 [1] NCCL INFO P2P Chunksize set to 131072
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 02/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9292:9292 [0] NCCL INFO Channel 03/0 : 0[0] -> 1[1] via P2P/CUMEM
0f139cc8454d:9293:9293 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9293:9293 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9293:9293 [1] NCCL INFO Channel 02/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9293:9293 [1] NCCL INFO Channel 03/0 : 1[1] -> 0[0] via P2P/CUMEM
0f139cc8454d:9292:9292 [0] NCCL INFO Connected all rings
0f139cc8454d:9292:9292 [0] NCCL INFO Connected all trees
0f139cc8454d:9293:9293 [1] NCCL INFO Connected all rings
0f139cc8454d:9293:9293 [1] NCCL INFO Connected all trees
0f139cc8454d:9292:9292 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
0f139cc8454d:9293:9293 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
0f139cc8454d:9292:9292 [0] NCCL INFO 4 coll channels, 0 collnet channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
0f139cc8454d:9293:9293 [1] NCCL INFO 4 coll channels, 0 collnet channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer

0f139cc8454d:9292:9330 [0] misc/shmutils.cc:72 NCCL WARN Error: failed to extend /dev/shm/nccl-dLYOFP to 5767524 bytes

0f139cc8454d:9292:9330 [0] misc/shmutils.cc:113 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-dLYOFP (size 5767520)
0f139cc8454d:9292:9330 [0] NCCL INFO proxy.cc:1252 -> 2
0f139cc8454d:9292:9330 [0] NCCL INFO proxy.cc:1315 -> 2
0f139cc8454d:9292:9292 [0] NCCL INFO proxy.cc:1064 -> 2
0f139cc8454d:9292:9292 [0] NCCL INFO init.cc:1328 -> 2
0f139cc8454d:9292:9292 [0] NCCL INFO init.cc:1501 -> 2
0f139cc8454d:9292:9292 [0] NCCL INFO init.cc:1746 -> 2
0f139cc8454d:9292:9292 [0] NCCL INFO init.cc:1784 -> 2

0f139cc8454d:9293:9332 [1] misc/shmutils.cc:72 NCCL WARN Error: failed to extend /dev/shm/nccl-HgufSU to 5767524 bytes

0f139cc8454d:9293:9332 [1] misc/shmutils.cc:113 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-HgufSU (size 5767520)
0f139cc8454d:9293:9332 [1] NCCL INFO proxy.cc:1252 -> 2
0f139cc8454d:9293:9332 [1] NCCL INFO proxy.cc:1315 -> 2
0f139cc8454d:9293:9293 [1] NCCL INFO proxy.cc:1064 -> 2
0f139cc8454d:9293:9293 [1] NCCL INFO init.cc:1328 -> 2
0f139cc8454d:9293:9293 [1] NCCL INFO init.cc:1501 -> 2
0f139cc8454d:9293:9293 [1] NCCL INFO init.cc:1746 -> 2
0f139cc8454d:9293:9293 [1] NCCL INFO init.cc:1784 -> 2
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/test.py", line 28, in <module>
[rank0]:     pynccl = PyNcclCommunicator(group=gloo_group, device=local_rank)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/sglang/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl.py", line 89, in __init__
[rank0]:     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
[rank0]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/envs/sglang/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 244, in ncclCommInitRank
[rank0]:     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
[rank0]:   File "/opt/conda/envs/sglang/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 223, in NCCL_CHECK
[rank0]:     raise RuntimeError(f"NCCL error: {error_str}")
[rank0]: RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
[rank1]: Traceback (most recent call last):
[rank1]:   File "/root/test.py", line 28, in <module>
[rank1]:     pynccl = PyNcclCommunicator(group=gloo_group, device=local_rank)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/conda/envs/sglang/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl.py", line 89, in __init__
[rank1]:     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
[rank1]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/conda/envs/sglang/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 244, in ncclCommInitRank
[rank1]:     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
[rank1]:   File "/opt/conda/envs/sglang/lib/python3.11/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 223, in NCCL_CHECK
[rank1]:     raise RuntimeError(f"NCCL error: {error_str}")
[rank1]: RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)
W0909 07:11:16.355000 140533383049856 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 9293 closing signal SIGTERM
E0909 07:11:16.569000 140533383049856 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 9292) of binary: /opt/conda/envs/sglang/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/sglang/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/sglang/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/sglang/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/envs/sglang/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/envs/sglang/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/sglang/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-09_07:11:16
  host      : 0f139cc8454d
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9292)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
> 0f139cc8454d:9293:9332 [1] misc/shmutils.cc:72 NCCL WARN Error: failed to extend /dev/shm/nccl-HgufSU to 5767524 bytes
> 
> 0f139cc8454d:9293:9332 [1] misc/shmutils.cc:113 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-HgufSU (size 5767520)
> 

looks like you don't have enough space for shared memory.

if you are using docker, make sure you check out https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html and use `--ipc=host` for docker.

**Comment by Armod-I** [comment]
> > 0f139cc8454d:9293:9332 [1] misc/shmutils.cc:72 NCCL WARN Error: failed to extend /dev/shm/nccl-HgufSU to 5767524 bytes
> > 0f139cc8454d:9293:9332 [1] misc/shmutils.cc:113 NCCL WARN Error while creating shared memory segment /dev/shm/nccl-HgufSU (size 5767520)
> 
> looks like you don't have enough space for shared memory.
> 
> if you are using docker, make sure you check out https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html and use `--ipc=host` for docker.

solved, ty!
