### ISSUE TITLE
[Usage]: example/offline_inference_chat.py run error. 

### ISSUE THREAD

**Issue by dshm** [vllm-project/vllm#8331]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a llama3. I don't know how to integrate it with vllm.
I am a new user of vllm and a freshman in this domain. I want to use vllm v0.6.0 to run llama3 and do some research. When I run example/offline_inference_chat.py[https://github.com/vllm-project/vllm/blob/v0.6.0/examples/offline_inference_chat.py] which using llama3 model, I get error as below. I searched the related issue https://github.com/vllm-project/vllm/issues/4180 . after read it I am still not clear how to solve this problem. I also sign up in the HuggingFace. But how can I use the account in vllm?  Coule someone please giive me some advice? I am a freshman in this domain and really don't know how to do next. Thank you advance!

python examples/offline_inference_chat.py 
Traceback (most recent call last):
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1347, in _hf_hub_download_to_cach
e_dir    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1854, in _raise_on_head_call_erro
r    raise head_call_error
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1751, in _get_metadata_or_catch_e
rror    metadata = get_hf_file_metadata(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 321, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-66dffd68-4181b8913bfd0bba57b66559;6461b4f3-4746-492d-9779-8741a5397a7e)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/vllmreleated/buildfromsource3/vllm/examples/offline_inference_chat.py", line 3, in <module>
    llm = LLM(model="meta-llama/Meta-Llama-3-8B-Instruct")
  File "/root/vllmreleated/buildfromsource3/vllm/vllm/entrypoints/llm.py", line 177, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/root/vllmreleated/buildfromsource3/vllm/vllm/engine/llm_engine.py", line 535, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/root/vllmreleated/buildfromsource3/vllm/vllm/engine/arg_utils.py", line 792, in create_engine_config
    model_config = ModelConfig(
  File "/root/vllmreleated/buildfromsource3/vllm/vllm/config.py", line 176, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision,
  File "/root/vllmreleated/buildfromsource3/vllm/vllm/transformers_utils/config.py", line 66, in get_config
    config = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 976, in from_pretra
ined    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/vllmsourcebuildpython3.10/lib/python3.10/site-packages/transformers/utils/hub.py", line 420, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
401 Client Error. (Request ID: Root=1-66dffd68-4181b8913bfd0bba57b66559;6461b4f3-4746-492d-9779-8741a5397a7e)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
see https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables#hftoken
