### ISSUE TITLE
Getting an error while loading model mosiac/mpt-30b, Invalid shape for attention bias

### ISSUE THREAD

**Issue by himanshucapoor** [vllm-project/vllm#848]
Hi ,

while running the following code:
`model= LLM(model="mosaicml/mpt-30b", tokenizer = "mosaicml/mpt-30b",                                  tensor_parallel_size=4,
                             pipeline_parallel_size=1,
                             gpu_memory_utilization=0.90
                             dtype='bfloat16')` 

I am getting an error while loading the mpt model. Below is the call stack

```
Traceback (most recent call last):
  File "inference.py", line 207, in <module>
    vllm_inference_provider.load_model(model_args, inference_args, vllm_args)
  File "inference.py", line 175, in load_model
    self.model = LLM(model=self.model_args.model_path, tensor_parallel_size=self.vllm_args.tensor_parallel_size,
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 62, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 154, in from_engine_args
    engine = cls(*engine_configs,
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 105, in __init__
    self._init_cache()
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 117, in _init_cache
    num_blocks = self._run_workers(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 334, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::Worker.profile_num_available_blocks() (pid=28130, ip=172.31.46.1, actor_id=2959eb28c8ba6c028ee5032301000000, repr=<vllm.worker.worker.Worker object at 0x7f9dbd76b970>)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/worker/worker.py", line 99, in profile_num_available_blocks
    self.model(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/model_executor/models/mpt.py", line 233, in forward
    hidden_states = self.transformer(input_ids, positions, kv_caches,
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/model_executor/models/mpt.py", line 201, in forward
    hidden_states = block(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/model_executor/models/mpt.py", line 152, in forward
    x = self.attn(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/model_executor/models/mpt.py", line 101, in forward
    attn_output = self.attn(q, k, v, k_cache, v_cache, input_metadata,
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/model_executor/layers/attention.py", line 170, in forward
    self.multi_query_kv_attention(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/model_executor/layers/attention.py", line 352, in multi_query_kv_attention
    out = xops.memory_efficient_attention_forward(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 214, in memory_efficient_attention_forward
    return _memory_efficient_attention_forward(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 304, in _memory_efficient_attention_forward
    inp.validate_inputs()
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/xformers/ops/fmha/common.py", line 120, in validate_inputs
    raise ValueError(
ValueError: Invalid shape for attention bias: torch.Size([8, 10, 10]) (expected (1, 8, 10, 10))
  query.shape: torch.Size([1, 10, 8, 112])
  key.shape  : torch.Size([1, 10, 8, 112])
  value.shape: torch.Size([1, 10, 8, 112])
```

Please see to  it. Any pointers ?

I have observed one other thing i.e. once the above error comes , if i try to load any other model after this i get the following error 

```
(Worker pid=33107) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
(Worker pid=33108) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 43x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(Worker pid=33106) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 42x across cluster]
(Worker pid=33108) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 38x across cluster]
(Worker pid=33108) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 40x across cluster]
(Worker pid=33108) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 40x across cluster]
(Worker pid=33108) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 40x across cluster]
(Worker pid=33108) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 18883) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 45x across cluster]

```

GPU: A10*8

tried VLLM versions : `0.1.2` and `0.1.3` and encountered the same issue on both

**Comment by WoosukKwon** [comment]
Hi @himanshucapoor, thanks for trying out vLLM. The bug is fixed in the current main branch. Please [install vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source) until the next release (which should be soon). Sorry for the inconvenience.

**Comment by WoosukKwon** [comment]
We've just released v0.1.4, which includes fixes for this bug. Please upgrade vLLM with `pip install --upgrade vllm`.

**Comment by himanshucapoor** [comment]
> Hi @himanshucapoor, thanks for trying out vLLM. The bug is fixed in the current main branch. Please [install vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source) until the next release (which should be soon). Sorry for the inconvenience.

**Comment by himanshucapoor** [comment]
Thanks @WoosukKwon i took the latest vllm code and built the code. Issue is resolved. Will try the new version.
