### ISSUE TITLE
start vllm.entrypoints.api_server model vicuna-13b-v1.3  error: Fatal Python error: Bus error

### ISSUE THREAD

**Issue by luefei** [vllm-project/vllm#859]
err detail

`You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
(RayWorker pid=3554640) *** SIGBUS received at time=1692931519 on cpu 133 ***
(RayWorker pid=3554640) PC: @     0x7f60c5616291  (unknown)  __memset_avx2_erms
(RayWorker pid=3554640)     @     0x7f60c60a8cf0  (unknown)  (unknown)
(RayWorker pid=3554640) [2023-08-25 10:45:19,168 E 3554640 3555230] logging.cc:361: *** SIGBUS received at time=1692931519 on cpu 133 ***
(RayWorker pid=3554640) [2023-08-25 10:45:19,168 E 3554640 3555230] logging.cc:361: PC: @     0x7f60c5616291  (unknown)  __memset_avx2_erms
(RayWorker pid=3554640) [2023-08-25 10:45:19,168 E 3554640 3555230] logging.cc:361:     @     0x7f60c60a8cf0  (unknown)  (unknown)
(RayWorker pid=3554640) Fatal Python error: Bus error
(RayWorker pid=3554640) 
2023-08-25 10:45:21,197 WARNING worker.py:2037 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff781cee214007f7ef2aa9c68501000000 Worker ID: 0b9f32035f3bf5887270902660bc1c930f4fde24efc863eb33869403 Node ID: 60ec9d72124b5f6b8778a26b6fc79798f3791e315e57cac00bddb1ec Worker IP address: 9.218.61.234 Worker port: 37577 Worker PID: 3554643 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib64/python3.9/site-packages/vllm/entrypoints/api_server.py", line 78, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib64/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib64/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/vllm/engine/llm_engine.py", line 99, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib64/python3.9/site-packages/vllm/engine/llm_engine.py", line 170, in _init_workers_ray
    self._run_workers(
  File "/usr/local/lib64/python3.9/site-packages/vllm/engine/llm_engine.py", line 474, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib64/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/ray/_private/worker.py", line 2526, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: RayWorker
        actor_id: 781cee214007f7ef2aa9c68501000000
        pid: 3554643
        namespace: 78788d7f-d9c6-4ea7-8992-0debc2720932
        ip: 9.218.61.234
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.`

**Comment by WoosukKwon** [comment]
Hi @luefei, could you share your environment (e.g., OS, CPU, CPU RAM, GPU)?

**Comment by AlexanderOllman** [comment]
See here: https://github.com/NVIDIA/nccl-tests/issues/143

If you're running this in a container, it could potentially be due to /dev/shm being too small. In that case, it could be rectified by adding `--shm-size 10.24g` when you run the container.

**Comment by raihan0824** [comment]
I also have the same problem. The inference works on 4 gpus, however when I use 8 gpus, I got the identical error

**Comment by francescov1** [comment]
Using `--ipc=host` fixed the issue for me. See vLLM docs here: https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html

**Comment by qingjiaozyn** [comment]
> I also have the same problem. The inference works on 4 gpus, however when I use 8 gpus, I got the identical error

I also have the same problem. The inference works on 2 gpus however when I use 8 gpus in container
