### ISSUE TITLE
[Bug]: vllm deploy qwen1.5-14b/qwen2-7b+medusa, RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5120 and 4096x4096)

### ISSUE THREAD

**Issue by xhjcxxl** [vllm-project/vllm#8613]
### Your current environment
vllm=0.6.1

### Model Input Dumps

CUDA_VISIBLE_DEVICES=7 python3 -m vllm.entrypoints.openai.api_server --port 8010 \
  --served-model-name qwen2-7b \
  --model /mnt/user/deploy/qwen15_14b_finetuning_chatbot_v1_0914_deploy --dtype auto -tp 1 \
  --max-model-len 4096 --gpu-memory-utilization 0.9 \
  --max-num-seqs 1 \
  --speculative-model /mnt/user/deploy/qwen15_14b_finetuning_chatbot_v1_0914_deploy/medusa \
  --speculative-draft-tensor-parallel-size 1 \
  --num-speculative-tokens 3 \
  --speculative-disable-by-batch-size 3 \
  --use-v2-block-manager \
  --spec-decoding-acceptance-method typical_acceptance_sampler

### 🐛 Describe the bug

ERROR 09-19 10:53:38 async_llm_engine.py:63] Engine background task failed
ERROR 09-19 10:53:38 async_llm_engine.py:63] Traceback (most recent call last):
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 53, in _log_task_completion
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return_value = task.result()
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 939, in run_engine_loop
ERROR 09-19 10:53:38 async_llm_engine.py:63]     result = task.result()
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 868, in engine_step
ERROR 09-19 10:53:38 async_llm_engine.py:63]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 345, in step_async
ERROR 09-19 10:53:38 async_llm_engine.py:63]     outputs = await self.model_executor.execute_model_async(
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 185, in execute_model_async
ERROR 09-19 10:53:38 async_llm_engine.py:63]     output = await make_async(self.driver_worker.execute_model
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 09-19 10:53:38 async_llm_engine.py:63]     result = self.fn(*self.args, **self.kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return func(*args, **kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/spec_decode/spec_decode_worker.py", line 406, in execute_model
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return self._run_speculative_decoding_step(execute_model_req,
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/contextlib.py", line 79, in inner
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return func(*args, **kwds)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/spec_decode/spec_decode_worker.py", line 572, in _run_speculative_decoding_step
ERROR 09-19 10:53:38 async_llm_engine.py:63]     proposals = self.proposer_worker.get_spec_proposals(
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/spec_decode/medusa_worker.py", line 113, in get_spec_proposals
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return self._proposer.get_spec_proposals(
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/spec_decode/top1_proposer.py", line 77, in get_spec_proposals
ERROR 09-19 10:53:38 async_llm_engine.py:63]     maybe_sampler_output, transposed = self._worker.sampler_output(
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return func(*args, **kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/spec_decode/medusa_worker.py", line 69, in sampler_output
ERROR 09-19 10:53:38 async_llm_engine.py:63]     model_outputs = self.model_runner.model.generate_proposals(
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/medusa.py", line 148, in generate_proposals
ERROR 09-19 10:53:38 async_llm_engine.py:63]     hidden_states=self.forward(previous_hidden_states),
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/medusa.py", line 82, in forward
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return [block(hidden_states) for block in self.blocks]
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/medusa.py", line 82, in <listcomp>
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return [block(hidden_states) for block in self.blocks]
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return self._call_impl(*args, **kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return forward_call(*args, **kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/medusa.py", line 28, in forward
ERROR 09-19 10:53:38 async_llm_engine.py:63]     x = x + self.act(layer(x))
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return self._call_impl(*args, **kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return forward_call(*args, **kwargs)
ERROR 09-19 10:53:38 async_llm_engine.py:63]   File "/opt/conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
ERROR 09-19 10:53:38 async_llm_engine.py:63]     return F.linear(input, self.weight, self.bias)
ERROR 09-19 10:53:38 async_llm_engine.py:63] **RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5120 and 4096x4096)**

**Comment by xhjcxxl** [comment]
5120, qwen1.5-14b hidden size=5120, set max-model-len=4096, then, medusa.py has some error?
