### ISSUE TITLE
[Bug]: use cpu_offload_gb in gguf failed.

### ISSUE THREAD

**Issue by Minami-su** [vllm-project/vllm#8757]
### 🐛 Describe the bug

CUDA_VISIBLE_DEVICES=4 python -m vllm.entrypoints.openai.api_server --model PsyLLM-3.5-Turbo-09-19-Q3_K_M.gguf --trust-remote-code --port 6000 --host 0.0.0.0 --dtype auto --max-model-len 32000 --enforce-eager --tensor_parallel_size 1 --gpu_memory_utilization 0.5 --cpu_offload_gb 80 
Traceback (most recent call last):
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/entrypoints/openai/rpc/server.py", line 230, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/entrypoints/openai/rpc/server.py", line 31, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 740, in from_engine_args
    engine = cls(
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 636, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 840, in _init_engine
    return engine_class(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 272, in __init__
    super().__init__(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 284, in __init__
    self._initialize_kv_caches()
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 390, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 113, in determine_num_available_blocks
    return self.driver_worker.determine_num_available_blocks()
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/worker/worker.py", line 222, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1097, in profile_run
    self.execute_model(model_input, kv_caches, intermediate_tensors)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1415, in execute_model
    hidden_or_intermediate_states = model_executable(
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 361, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 277, in forward
    hidden_states, residual = layer(
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 169, in forward
    output = functional_call(module,
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/_functorch/functional_call.py", line 144, in functional_call
    return nn.utils.stateless._functional_call(
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/utils/stateless.py", line 270, in _functional_call
    return module(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 210, in forward
    hidden_states = self.self_attn(
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 154, in forward
    qkv, _ = self.qkv_proj(hidden_states)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 365, in forward
    output_parallel = self.quant_method.apply(self, input_, bias)
  File "/work/jcxy/.conda/envs/haolu/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/gguf.py", line 134, in apply
    qweight_type = layer.qweight_type.weight_type
AttributeError: 'Tensor' object has no attribute 'weight_type'
ERROR 09-24 02:22:47 api_server.py:171] RPCServer process died before responding to readiness probe

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by mgoin** [comment]
Thanks for reporting, this is a known issue that we are unsure how to resolve. Contributions are welcome!

**Comment by samos123** [comment]
This seems to also happen when using bnb 4 bit quant when cpu offload:

```
ERROR 02-02 10:34:51 engine.py:387] Traceback (most recent call last):
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 378, in run_mp_engine
ERROR 02-02 10:34:51 engine.py:387]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 02-02 10:34:51 engine.py:387]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 121, in from_engine_args
ERROR 02-02 10:34:51 engine.py:387]     return cls(ipc_path=ipc_path,
ERROR 02-02 10:34:51 engine.py:387]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 73, in __init__
ERROR 02-02 10:34:51 engine.py:387]     self.engine = LLMEngine(*args, **kwargs)
ERROR 02-02 10:34:51 engine.py:387]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 274, in __init__
ERROR 02-02 10:34:51 engine.py:387]     self._initialize_kv_caches()
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 414, in _initialize_kv_caches
ERROR 02-02 10:34:51 engine.py:387]     self.model_executor.determine_num_available_blocks())
ERROR 02-02 10:34:51 engine.py:387]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 99, in determine_num_available_blocks
ERROR 02-02 10:34:51 engine.py:387]     results = self.collective_rpc("determine_num_available_blocks")
ERROR 02-02 10:34:51 engine.py:387]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 49, in collective_rpc
ERROR 02-02 10:34:51 engine.py:387]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 02-02 10:34:51 engine.py:387]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2208, in run_method
ERROR 02-02 10:34:51 engine.py:387]     return func(*args, **kwargs)
ERROR 02-02 10:34:51 engine.py:387]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 02-02 10:34:51 engine.py:387]     return func(*args, **kwargs)
ERROR 02-02 10:34:51 engine.py:387]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 228, in determine_num_available_blocks
ERROR 02-02 10:34:51 engine.py:387]     self.model_runner.profile_run()
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 02-02 10:34:51 engine.py:387]     return func(*args, **kwargs)
ERROR 02-02 10:34:51 engine.py:387]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1236, in profile_run
ERROR 02-02 10:34:51 engine.py:387]     self._dummy_run(max_num_batched_tokens, max_num_seqs)
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1347, in _dummy_run
ERROR 02-02 10:34:51 engine.py:387]     self.execute_model(model_input, kv_caches, intermediate_tensors)
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 02-02 10:34:51 engine.py:387]     return func(*args, **kwargs)
ERROR 02-02 10:34:51 engine.py:387]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-02 10:34:51 engine.py:387]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
ERROR 02-02 10:34:51 engine.py:387]     raise type(err)(
ERROR 02-02 10:34:51 engine.py:387] AttributeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20250202-103449.pkl): 'Tensor' object has no attribute 'bnb_quant_state'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1721, in execute_model
    hidden_or_intermediate_states = model_executable(
                                    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 539, in forward
    model_output = self.model(input_ids, positions, kv_caches,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 170, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 363, in forward
    hidden_states, residual = layer(positions, hidden_states,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/utils.py", line 529, in forward
    output = functional_call(module,
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/functional_call.py", line 148, in functional_call
    return nn.utils.stateless._functional_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/utils/stateless.py", line 298, in _functional_call
    return module(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 277, in forward
    hidden_states = self.self_attn(positions=positions,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/llama.py", line 198, in forward
    qkv, _ = self.qkv_proj(hidden_states)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 380, in forward
    output_parallel = self.quant_method.apply(self, input_, bias)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/bitsandbytes.py", line 227, in apply
    return self._apply_4bit_weight(layer, x, bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/quantization/bitsandbytes.py", line 326, in _apply_4bit_weight
    quant_states = qweight.bnb_quant_state
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute 'bnb_quant_state'


```

**Comment by samos123** [comment]
I don't have permissions to re-open but seems the issue is more widespread than originally believed.

**Comment by lopozz** [comment]
+1

**Comment by cj1324** [comment]
+1

**Comment by jxfruit** [comment]
Is there any solutions, guys

**Comment by toncao** [comment]
+1

**Comment by mydevops-code** [comment]
+1

**Comment by zarkitapple** [comment]
+1
