### ISSUE TITLE
Loading Model through Multi-Node Ray Cluster Fails

### ISSUE THREAD

**Issue by VarunSreenivasan16** [vllm-project/vllm#881]
## Problem Description

I'm trying to spin up the VLLM API server inside a docker container (that has vllm and all requirements installed) on the head node of a ray cluster (the cluster contains 4 nodes and has access to 4 T4 GPUs) with the following command in the container:

`python3 -m vllm.entrypoints.api_server --host 0.0.0.0 --port 8000 --model /home/model --tensor-parallel-size 4 --swap-space 2
`

I get back the following error (NOTE: I x'd out the IP):

```
python3 -m vllm.entrypoints.api_server --host 0.0.0.0 --port 8000 --model /home/model --tensor-parallel-size 4 --swap-space^Me 2
^[[?2004l^M2023-08-25 22:29:16,736      INFO worker.py:1313 -- Using address ray://xxx.xxx.xxx.xx:10001 set in the environment variable RAY_ADDRESS
2023-08-25 22:29:16,737 INFO client_builder.py:237 -- Passing the following kwargs to ray.init() on the server: ignore_reinit_error
INFO 08-25 22:29:19 llm_engine.py:70] Initializing an LLM engine with config: model='/home/model', tokenizer='/home/model', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=4, seed=0)
WARNING 08-25 22:29:19 config.py:191] Possibly too large swap space. 8.00 GiB out of the 15.34 GiB total CPU memory is allocated for the swap space.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 21, in __getattr__
    return getattr(self.worker, name)
  File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 21, in __getattr__
    return getattr(self.worker, name)
  File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)

....

  File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 21, in __getattr__
    return getattr(self.worker, name)
  File "/usr/local/lib/python3.10/dist-packages/ray/util/tracing/tracing_helper.py", line 463, in _resume_span
    if not _is_tracing_enabled() or _ray_trace_ctx is None:
RecursionError: maximum recursion depth exceeded
```

### Hardware 

- 4 x AWS EC2 [g4dn.xlarge](https://aws.amazon.com/ec2/instance-types/g4/).
- Each g4dn.xlarge instance has 1 Nvidia T4 GPU with 16 GB RAM. The node architecure is x86_64 and the platform is ubuntu.
- So, in total my multi-node deployment has 4 different nodes with 4 total T4 GPUS.
- Nvidia drivers are correctly installed in all of them and cuda version is 11.8

### Model

- Fine tuned `llama-2-13B` model (obtained from merging Llama-2-13b-hf and lora adapter using peft). 
- The `tokenizer.model`, `tokenizer.json`,  `tokenizer_config.json` are present in the model directory as well (obtained from base hf model).

### Cluster Setup

- I ensured that all the ports are open on each of the nodes to allow cluster communication.
- I ran `ray status --address <head_node_ip:6379>` and I can confirm that all the four nodes are accessible from the docker container running in the head node.
<img width="503" alt="Screenshot 2023-08-25 at 5 41 28 PM" src="https://github.com/vllm-project/vllm/assets/40222607/3ee5277b-104a-4f5e-b2f6-e4d98e7ca093">

- In order to allow VLLM to connect to the ray cluster I setup the environment variable `RAY_ADDRESS` to be `ray://<head_node_ip:10001>` and then ran the command to spin up the API server.

### Docker Container Setup on Head Node

The following was the Dockerfile used to build the container:

```
# Set the base image to nvidia/cuda:11.8.0-devel-ubuntu22.04
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

# Update the repository sources list and install dependencies
RUN apt-get update -y -q && apt-get upgrade -y -q && apt-get install -y -q curl python3-pip git vim

# Copy requirements file 
COPY requirements.txt ./requirements.txt

# Install pip dependencies
RUN pip3 install -r requirements.txt

# Copy the model into home directory
COPY llama-2-13b-merged/ /home/model/

# Expose port for http requests
EXPOSE 8000 9999

# Setup entrypoint
ENTRYPOINT ["/bin/bash"]
```

The requirements.txt is 

```
vllm
pandas
transformers
peft
datasets
jupyterlab
```

- I can confirm the installation succeeded and nvidia-smi inside the container correctly shows the cuda version to be 11.8.

- I also used `--gpus all flag` when running the `docker run` command.

## Request

I'd appreciate any advice or help on this issue. I'm happy to provide any more information required to address the issue.

**Comment by tattrongvu** [comment]
Hi, I also have some error with 2 nodes on GKE, each 2 V100 so in total 4 V100.  
I used vLLM 0.1.4 (install from git) and torch 2.0.1 cuda 1.18, Ray 2.6.3.
![ray-status](https://github.com/vllm-project/vllm/assets/66179376/36d60331-efbf-43df-96d7-4755719e90d4)

and this is my error, it seem to be a HuggingFace load local model error.
![ray-cluster-vllm-error](https://github.com/vllm-project/vllm/assets/66179376/a36837bd-d6f4-48e0-88c7-ebc1230723ce)

**Comment by tattrongvu** [comment]
Hi, I also faced some issue when deploy VLLM in Google Kubernetes Engine, I create 2 nodes, each node has 2 V100, so in total 4V100 gpu. 
![ray-status](https://github.com/vllm-project/vllm/assets/66179376/038632f6-16bb-4eee-836f-0187920bb101)

And this is my error, that seem to be the HuggingFace local model load:

> 2023-08-28 15:55:45,931 INFO worker.py:1313 -- Using address xxxxxx set in the environment variable RAY_ADDRESS
2023-08-28 15:55:45,931 INFO worker.py:1431 -- Connecting to existing Ray cluster at address: xxxxxx
2023-08-28 15:55:45,940 INFO worker.py:1612 -- Connected to Ray cluster. View the dashboard at xxxxxxx 
INFO 08-28 15:55:46 llm_engine.py:70] Initializing an LLM engine with config: model='/home/download/', tokenizer='/home/download/', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=4, seed=0)
Traceback (most recent call last):
  File "/home/server/vLLM_Server.py", line 169, in <module>
    main()
  File "/home/server/vLLM_Server.py", line 160, in main
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 99, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 170, in _init_workers_ray
    self._run_workers(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 474, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(HFValidationError): ray::RayWorker.execute_method() (pid=187, ip=10.128.2.3, actor_id=b9fe076ef40c5c1520c4672902000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7dc429515870>)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 25, in execute_method
    return executor(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 67, in init_model
    self.model = get_model(self.model_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 57, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/llama.py", line 290, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 35, in hf_model_weights_iterator
    hf_folder = snapshot_download(model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/download/'. Use `repo_type` argument if needed.

**Comment by agrogov** [comment]
Seems it's just not enough RAM: `WARNING 08-25 22:29:19 config.py:191] Possibly too large swap space. 8.00 GiB out of the 15.34 GiB total CPU memory is allocated for the swap space.`
Just try to run without `--swap-space 2`, it's not needed if you sure that VRAM is enough.

**Comment by masnec** [comment]
@VarunSreenivasan16 did you figure out how to fix this? I run into the same issue recently.

**Comment by masnec** [comment]
Hi @WoosukKwon , I encountered the same issue when connecting to remote Ray cluster with vllm v0.2.6. any idea or direction? Thank you!

**Comment by hmellor** [comment]
@VarunSreenivasan16 @masnec did either of you ever figure out what the issue was or resolve it?

**Comment by hmellor** [comment]
@masnec would you mind contributing this information to https://docs.vllm.ai/en/latest/serving/distributed_serving.html?

**Comment by rkooo567** [comment]
Btw, using tensor-parallel across multiple nodes can penalty the performance a lot because it requires high network communication.
