### ISSUE TITLE
[Question]: Apply LoRA adapter on quantized model

### ISSUE THREAD

**Issue by Tejaswgupta** [vllm-project/vllm#8945]
### Anything you want to discuss about vllm.

I've fine-tuned Qwen2.5-14B-Instruct using QLora(bitsandbytes 4bit) and also a full fine-tune. However when I tried to use it with a quantized model (Qwen2.5-14B-Instruct-gptq-int4) , vllm crashed.

Is this a technical constraint or I'm missing something?

Thank you for your response.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
See: https://github.com/vllm-project/vllm/blob/main/examples/lora_with_quantization_inference.py

**Comment by Tejaswgupta** [comment]
@jeejeelee running the inference file you shared I'm getting this.
```
(model) azureuser@votum-vm-new:~$ python vllm_lora_inference.py 
WARNING 09-30 07:57:13 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
INFO 09-30 07:57:16 gptq_marlin.py:112] Detected that the model can run with gptq_marlin, however you specified quantization=gptq explicitly, so forcing gptq. Use quantization=gptq_marlin for faster inference
WARNING 09-30 07:57:16 config.py:335] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 09-30 07:57:16 llm_engine.py:223] Initializing an LLM engine (v0.6.1.post2) with config: model='Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4', speculative_config=None, tokenizer='Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=True)
[rank0]:[W930 07:57:17.318890636 ProcessGroupGloo.cpp:712] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
INFO 09-30 07:57:17 model_runner.py:997] Starting to load model Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4...
INFO 09-30 07:57:18 weight_utils.py:242] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:00,  3.88it/s]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:01<00:00,  1.78it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:01<00:00,  1.37it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:01<00:00,  1.53it/s]

INFO 09-30 07:57:21 model_runner.py:1008] Loading model weights took 9.3793 GB
INFO 09-30 07:57:26 gpu_executor.py:122] # GPU blocks: 19423, # CPU blocks: 1365
INFO 09-30 07:57:31 model_runner.py:1311] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 09-30 07:57:31 model_runner.py:1315] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 09-30 07:57:58 model_runner.py:1430] Graph capturing finished in 27 secs.
/home/azureuser/vllm_lora_inference.py:27: DeprecationWarning: The 'lora_local_path' attribute is deprecated and will be removed in a future version. Please use 'lora_path' instead.
  LoRARequest("lora-test-1", 1, lora_path)),
/home/azureuser/vllm_lora_inference.py:33: DeprecationWarning: The 'lora_local_path' attribute is deprecated and will be removed in a future version. Please use 'lora_path' instead.
  LoRARequest("lora-test-2", 1, lora_path)),
/home/azureuser/vllm_lora_inference.py:39: DeprecationWarning: The 'lora_local_path' attribute is deprecated and will be removed in a future version. Please use 'lora_path' instead.
  LoRARequest("lora-test-3", 1, lora_path)),
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/azureuser/vllm_lora_inference.py", line 128, in <module>
[rank0]:     main()
[rank0]:   File "/home/azureuser/vllm_lora_inference.py", line 119, in main
[rank0]:     process_requests(engine, test_prompts)
[rank0]:   File "/home/azureuser/vllm_lora_inference.py", line 52, in process_requests
[rank0]:     engine.add_request(str(request_id),
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 733, in add_request
[rank0]:     preprocessed_inputs = self.input_preprocessor.preprocess(
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 500, in preprocess
[rank0]:     return self._process_decoder_only_prompt(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 449, in _process_decoder_only_prompt
[rank0]:     prompt_comps = self._extract_prompt_components(
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 233, in _extract_prompt_components
[rank0]:     prompt_token_ids = self._tokenize_prompt(
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 190, in _tokenize_prompt
[rank0]:     return tokenizer.encode(request_id=request_id,
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 58, in encode
[rank0]:     tokenizer = self.get_lora_tokenizer(lora_request)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 80, in get_lora_tokenizer
[rank0]:     tokenizer = (get_lora_tokenizer(
[rank0]:                  ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer.py", line 170, in get_lora_tokenizer
[rank0]:     tokenizer = get_tokenizer(lora_request.lora_path, *args, **kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/transformers_utils/tokenizer.py", line 120, in get_tokenizer
[rank0]:     tokenizer = AutoTokenizer.from_pretrained(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 897, in from_pretrained
[rank0]:     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2271, in from_pretrained
[rank0]:     return cls._from_pretrained(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2505, in _from_pretrained
[rank0]:     tokenizer = cls(*init_inputs, **init_kwargs)
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/transformers/models/qwen2/tokenization_qwen2_fast.py", line 120, in __init__
[rank0]:     super().__init__(
[rank0]:   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 115, in __init__
[rank0]:     fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: Exception: data did not match any variant of untagged enum ModelWrapper at line 757443 column 3
```

**Comment by jeejeelee** [comment]
Can you provide the complete  script?

**Comment by Tejaswgupta** [comment]
Adapter config:
```
{
  "alpha_pattern": {},
  "auto_mapping": null,
  "base_model_name_or_path": "unsloth/Qwen2.5-14B-Instruct",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layer_replication": null,
  "layers_pattern": null,
  "layers_to_transform": null,
  "loftq_config": {},
  "lora_alpha": 16,
  "lora_dropout": 0.0,
  "megatron_config": null,
  "megatron_core": "megatron.core",
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 64,
  "rank_pattern": {},
  "revision": null,
  "target_modules": [
    "k_proj",
    "o_proj",
    "up_proj",
    "v_proj",
    "down_proj",
    "q_proj",
    "gate_proj"
  ],
  "task_type": "CAUSAL_LM",
  "use_dora": true,
  "use_rslora": true
}
```


Script
```
import gc
from typing import List, Optional, Tuple

import torch
from huggingface_hub import snapshot_download

from vllm import EngineArgs, LLMEngine, RequestOutput, SamplingParams
from vllm.lora.request import LoRARequest


def create_test_prompts(
        lora_path: str
) -> List[Tuple[str, SamplingParams, Optional[LoRARequest]]]:
    return [
        # this is an example of using quantization without LoRA
        ("My name is",
         SamplingParams(temperature=0.0,
                        logprobs=1,
                        prompt_logprobs=1,
                        max_tokens=128), None),
        # the next three examples use quantization with LoRA
        ("my name is",
         SamplingParams(temperature=0.0,
                        logprobs=1,
                        prompt_logprobs=1,
                        max_tokens=128),
         LoRARequest("lora-test-1", 1, lora_path)),
        ("The capital of USA is",
         SamplingParams(temperature=0.0,
                        logprobs=1,
                        prompt_logprobs=1,
                        max_tokens=128),
         LoRARequest("lora-test-2", 1, lora_path)),
        ("The capital of France is",
         SamplingParams(temperature=0.0,
                        logprobs=1,
                        prompt_logprobs=1,
                        max_tokens=128),
         LoRARequest("lora-test-3", 1, lora_path)),
    ]


def process_requests(engine: LLMEngine,
                     test_prompts: List[Tuple[str, SamplingParams,
                                              Optional[LoRARequest]]]):
    """Continuously process a list of prompts and handle the outputs."""
    request_id = 0

    while test_prompts or engine.has_unfinished_requests():
        if test_prompts:
            prompt, sampling_params, lora_request = test_prompts.pop(0)
            engine.add_request(str(request_id),
                               prompt,
                               sampling_params,
                               lora_request=lora_request)
            request_id += 1

        request_outputs: List[RequestOutput] = engine.step()
        for request_output in request_outputs:
            if request_output.finished:
                print("----------------------------------------------------")
                print(f"Prompt: {request_output.prompt}")
                print(f"Output: {request_output.outputs[0].text}")


def initialize_engine(model: str, quantization: str,
                      lora_repo: Optional[str]) -> LLMEngine:
    """Initialize the LLMEngine."""

    if quantization == "bitsandbytes":
        # QLoRA (https://arxiv.org/abs/2305.14314) is a quantization technique.
        # It quantizes the model when loading, with some config info from the
        # LoRA adapter repo. So need to set the parameter of load_format and
        # qlora_adapter_name_or_path as below.
        engine_args = EngineArgs(model=model,
                                 quantization=quantization,
                                 qlora_adapter_name_or_path=lora_repo,
                                 load_format="bitsandbytes",
                                 enable_lora=True,
                                 max_lora_rank=64,
                                 )
    else:
        engine_args = EngineArgs(model=model,
                                 quantization=quantization,
                                 enable_lora=True,
                                 max_loras=64,
                                 gpu_memory_utilization=0.4,
                                 )


    return LLMEngine.from_engine_args(engine_args)


def main():
    """Main function that sets up and runs the prompt processing."""
    lora_path = '/home/azureuser/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2024-09-26-19-25-51-unsloth-v7/'
    engine = initialize_engine('Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4',
                               'gptq',
                                lora_path,)

    test_prompts = create_test_prompts(lora_path)
    process_requests(engine, test_prompts)


if __name__ == '__main__':
    main()
```

**Comment by rishsriv** [comment]
Reached here after encountering the same issue. Seems like the `transformers` package is to blame. Downgrading to `transformers==4.44.1` fixed it for me

**Comment by Tejaswgupta** [comment]
@rishsriv even after downgrading I'm getting the same issue.
```
/home/azureuser/miniconda3/envs/model/bin/vllm serve Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4 --port 8084 --max-model-len 8192 --gpu-memory-utilization 0.4 --enable-lora --lora-modules acts-lora=/home/azureuser/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2024-09-26-19-25-51-unsloth-v7/ --max_lora_rank 64
```

Error:
```
BadRequestError: Error code: 400 - {'error': {'message': "OpenAIException - Error code: 400 - {'object': 'error', 'message': 'data did not match any variant of untagged enum ModelWrapper at line 757443 column 3', 'type': 'BadRequestError', 'param': None, 'code': 400}\nNumber Retries = 1", 'type': None, 'param': None, 'code': 400}}
```

**Comment by Tejaswgupta** [comment]
@jeejeelee I did another fine-tune , the older one showed a loss of 0 which made me think it might be something to do with the adapter itself.

But vllm is still crashing.
```
INFO 10-05 17:57:13 logger.py:36] Received request chat-840b486a221745679e3ca6a42c22e754: prompt: '<|im_start|>system\nYou are a helpful assistant who helps people in finding answers to complicated legal questions.Always think step by step.<|im_end|>\n<|im_start|>user\nPlease write a passage to answer the question\nTry to include as many key details as possible.\n\n\nhi\n\n\nPassage:"""\n<|im_end|>\n<|im_start|>assistant\n', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.4, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=8132, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [151644, 8948, 198, 2610, 525, 264, 10950, 17847, 879, 8609, 1251, 304, 9271, 11253, 311, 16965, 5777, 4755, 9636, 2284, 1744, 3019, 553, 3019, 13, 151645, 198, 151644, 872, 198, 5501, 3270, 264, 21085, 311, 4226, 279, 3405, 198, 21453, 311, 2924, 438, 1657, 1376, 3565, 438, 3204, 4192, 6023, 1406, 12187, 424, 2974, 89262, 151645, 198, 151644, 77091, 198], lora_request: LoRARequest(lora_name='acts-lora', lora_int_id=1, lora_path='/home/azureuser/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2024-09-26-19-25-51-unsloth-v7-bnb', lora_local_path=None, long_lora_max_len=None, base_model_name='Qwen/Qwen2.5-14b-Instruct-GPTQ-Int4'), prompt_adapter_request: None.
INFO 10-05 17:57:13 engine.py:288] Added request chat-840b486a221745679e3ca6a42c22e754.
INFO 10-05 17:57:13 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241005-175713.pkl...
WARNING 10-05 17:57:13 model_runner_base.py:143] Failed to pickle inputs of failed execution: Can't pickle local object 'weak_bind.<locals>.weak_bound'
ERROR 10-05 17:57:13 engine.py:157] RuntimeError('Error in model execution: Loading lora /home/azureuser/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2024-09-26-19-25-51-unsloth-v7-bnb failed')
ERROR 10-05 17:57:13 engine.py:157] Traceback (most recent call last):
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 94, in _load_adapter
ERROR 10-05 17:57:13 engine.py:157]     lora = self._lora_model_cls.from_local_checkpoint(
ERROR 10-05 17:57:13 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/models.py", line 216, in from_local_checkpoint
ERROR 10-05 17:57:13 engine.py:157]     module_name, _ = parse_fine_tuned_lora_name(lora_module)
ERROR 10-05 17:57:13 engine.py:157]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/utils.py", line 113, in parse_fine_tuned_lora_name
ERROR 10-05 17:57:13 engine.py:157]     raise ValueError(f"{name} is unsupported LoRA weight")
ERROR 10-05 17:57:13 engine.py:157] ValueError: base_model.model.model.layers.0.mlp.down_proj.lora_magnitude_vector is unsupported LoRA weight
ERROR 10-05 17:57:13 engine.py:157] 
ERROR 10-05 17:57:13 engine.py:157] The above exception was the direct cause of the following exception:
ERROR 10-05 17:57:13 engine.py:157] 
ERROR 10-05 17:57:13 engine.py:157] Traceback (most recent call last):
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
ERROR 10-05 17:57:13 engine.py:157]     return func(*args, **kwargs)
ERROR 10-05 17:57:13 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1552, in execute_model
ERROR 10-05 17:57:13 engine.py:157]     self.set_active_loras(model_input.lora_requests,
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1249, in set_active_loras
ERROR 10-05 17:57:13 engine.py:157]     self.lora_manager.set_active_adapters(lora_requests, lora_mapping)
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 136, in set_active_adapters
ERROR 10-05 17:57:13 engine.py:157]     set_active_adapters_worker(requests, mapping, self._apply_adapters,
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/adapter_commons/utils.py", line 52, in set_active_adapters_worker
ERROR 10-05 17:57:13 engine.py:157]     apply_adapters_func(requests)
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 195, in _apply_adapters
ERROR 10-05 17:57:13 engine.py:157]     self.add_adapter(lora)
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 204, in add_adapter
ERROR 10-05 17:57:13 engine.py:157]     lora = self._load_adapter(lora_request)
ERROR 10-05 17:57:13 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 107, in _load_adapter
ERROR 10-05 17:57:13 engine.py:157]     raise RuntimeError(f"Loading lora {lora_path} failed") from e
ERROR 10-05 17:57:13 engine.py:157] RuntimeError: Loading lora /home/azureuser/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2024-09-26-19-25-51-unsloth-v7-bnb failed
ERROR 10-05 17:57:13 engine.py:157] 
ERROR 10-05 17:57:13 engine.py:157] The above exception was the direct cause of the following exception:
ERROR 10-05 17:57:13 engine.py:157] 
ERROR 10-05 17:57:13 engine.py:157] Traceback (most recent call last):
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 155, in start
ERROR 10-05 17:57:13 engine.py:157]     self.run_engine_loop()
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 218, in run_engine_loop
ERROR 10-05 17:57:13 engine.py:157]     request_outputs = self.engine_step()
ERROR 10-05 17:57:13 engine.py:157]                       ^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 236, in engine_step
ERROR 10-05 17:57:13 engine.py:157]     raise e
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 227, in engine_step
ERROR 10-05 17:57:13 engine.py:157]     return self.engine.step()
ERROR 10-05 17:57:13 engine.py:157]            ^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 1264, in step
ERROR 10-05 17:57:13 engine.py:157]     outputs = self.model_executor.execute_model(
ERROR 10-05 17:57:13 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 130, in execute_model
ERROR 10-05 17:57:13 engine.py:157]     output = self.driver_worker.execute_model(execute_model_req)
ERROR 10-05 17:57:13 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 327, in execute_model
ERROR 10-05 17:57:13 engine.py:157]     output = self.model_runner.execute_model(
ERROR 10-05 17:57:13 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 10-05 17:57:13 engine.py:157]     return func(*args, **kwargs)
ERROR 10-05 17:57:13 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 10-05 17:57:13 engine.py:157]   File "/home/azureuser/miniconda3/envs/model/lib/python3.11/site-packages/vllm/worker/model_runner_base.py", line 146, in _wrapper
ERROR 10-05 17:57:13 engine.py:157]     raise type(err)(f"Error in model execution: "
ERROR 10-05 17:57:13 engine.py:157] RuntimeError: Error in model execution: Loading lora /home/azureuser/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2024-09-26-19-25-51-unsloth-v7-bnb failed
CRITICAL 10-05 17:57:13 launcher.py:72] AsyncLLMEngine has failed, terminating server process
INFO:     127.0.0.1:35622 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [4014262]
```

**Comment by jeejeelee** [comment]
>ERROR 10-05 17:57:13 engine.py:157] ValueError: base_model.model.model.layers.0.mlp.down_proj.lora_magnitude_vector is unsupported LoRA weight
ERROR 10-05 17:57:13 engine.py:157] 

It seems that this error is triggered by using use_dora=True, which is not yet supported by vLLM

**Comment by ttssrr423** [comment]
> See: https://github.com/vllm-project/vllm/blob/main/examples/lora_with_quantization_inference.py

Is this qlora compatible with tensor parallel > 1 for gptq/awq base models?

**Comment by jeejeelee** [comment]
> > See: https://github.com/vllm-project/vllm/blob/main/examples/lora_with_quantization_inference.py
> 
> Is this qlora compatible with tensor parallel > 1 for gptq/awq base models?

Of course
