### ISSUE TITLE
once occur error the inference will stuck

### ISSUE THREAD

**Issue by allenhaozi** [vllm-project/vllm#917]
service is running

got the following error:
```
openai.error.Timeout: Request timed out: HTTPConnectionPool(host='172.26.1.30', port=8000): Read timed out. (read timeout=600)
```

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/openai/api_server.py", line 302, in create_chat_completion
    async for res in result_generator:
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 148, in generate
    await self.engine_step(request_id)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 74, in engine_step
    request_outputs = self.engine.step()
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 324, in step
    self._decode_sequences(seq_groups)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 409, in _decode_sequences
    new_token, new_output_text = detokenize_incrementally(
  File "/usr/local/lib/python3.8/dist-packages/vllm/transformers_utils/tokenizer.py", line 85, in detokenize_incrementally
    new_token = tokenizer.convert_ids_to_tokens(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py", line 910, in convert_ids_to_tokens
    return self._convert_id_to_token(ids)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/tokenization_qwen.py", line 198, in _convert_id_to_token
    raise ValueError("unknown ids")
ValueError: unknown ids
```

**Comment by DavidFanzz** [comment]
I have also meet the same problem. Have you solved it ?

**Comment by vecorro** [comment]
same here

**Comment by allenhaozi** [comment]
The problem I encountered was related to the model I was using, and I changed the configuration file of the model

In addition, I am direct build the image base on main branch

**Comment by vecorro** [comment]
In my case, I'm using "meta-llama/Llama-2-7b-chat-hf". When using the OpenAI-compatible API, the error occurs when the temperature has a value different from 0.
