### ISSUE TITLE
[Bug]: vllm0.6.2  Using FLASHINFER to start VLLM reported an error, enabling -- quantification gptq -- kv cache dtype fp8_e5m2

### ISSUE THREAD

**Issue by Rssevenyu** [vllm-project/vllm#9243]
Using FLASHINFER to start VLLM reported an error, enabling -- quantification gptq -- kv cache dtype fp8_e5m2

Start command:

python3 -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 7807 --model /mnt/home/Qwen2.5-14B-Instruct-GPTQ-Int4 --trust-remote-code --served-model-name Qwen --gpu-memory-utilization 0.9 --tensor-parallel-size 2 --enforce-eager --max-model-len 8192 --quantization gptq --kv-cache-dtype fp8_e5m2
Can start, but remind me of the following information:

```
(VllmWorkerProcess pid=530898) INFO 10-10 11:12:03 selector.py:227] Cannot use FlashAttention-2 backend for FP8 KV cache.
(VllmWorkerProcess pid=530898) WARNING 10-10 11:12:03 selector.py:229] Please use FlashInfer backend with FP8 KV Cache for better performance by setting environment variable  VLLM_ATTENTION_BACKEND=FLASHINFER
```

So, there are the following settings:

export VLLM_ATTENTION_BACKEND=FLASHINFER

After setting, using the same command, an error occurs:

```
INFO 10-10 18:38:58 api_server.py:526] vLLM API server version 0.6.1.dev238+ge2c6e0a82
INFO 10-10 18:38:58 api_server.py:527] args: Namespace(host='0.0.0.0', port=7807, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, model='/mnt/home/Qwen2.5-14B-Instruct-GPTQ-Int4', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', config_format='auto', dtype='auto', kv_cache_dtype='fp8_e5m2', quantization_param_path=None, max_model_len=8192, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=True, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization='gptq', rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=False, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['Qwen'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, override_neuron_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False)
INFO 10-10 18:38:59 api_server.py:164] Multiprocessing frontend to use ipc:///tmp/5f034382-a0c6-42f4-9c21-ceea20e49222 for IPC Path.
INFO 10-10 18:38:59 api_server.py:177] Started engine process with PID 599270
INFO 10-10 18:38:59 gptq_marlin.py:111] Detected that the model can run with gptq_marlin, however you specified quantization=gptq explicitly, so forcing gptq. Use quantization=gptq_marlin for faster inference
WARNING 10-10 18:38:59 config.py:319] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 10-10 18:38:59 config.py:648] Using fp8 data type to store kv cache. It reduces the GPU memory footprint and boosts the performance. Meanwhile, it may cause accuracy drop without a proper scaling factor
INFO 10-10 18:38:59 config.py:899] Defaulting to use mp for distributed inference
WARNING 10-10 18:38:59 config.py:389] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 10-10 18:39:03 gptq_marlin.py:111] Detected that the model can run with gptq_marlin, however you specified quantization=gptq explicitly, so forcing gptq. Use quantization=gptq_marlin for faster inference
WARNING 10-10 18:39:03 config.py:319] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 10-10 18:39:03 config.py:648] Using fp8 data type to store kv cache. It reduces the GPU memory footprint and boosts the performance. Meanwhile, it may cause accuracy drop without a proper scaling factor
INFO 10-10 18:39:03 config.py:899] Defaulting to use mp for distributed inference
WARNING 10-10 18:39:03 config.py:389] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 10-10 18:39:03 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='/mnt/home/Qwen2.5-14B-Instruct-GPTQ-Int4', speculative_config=None, tokenizer='/mnt/home/Qwen2.5-14B-Instruct-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq, enforce_eager=True, kv_cache_dtype=fp8_e5m2, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=True, use_async_output_proc=False, use_cached_outputs=True, mm_processor_kwargs=None)
WARNING 10-10 18:39:03 multiproc_gpu_executor.py:53] Reducing Torch parallelism from 8 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 10-10 18:39:03 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 10-10 18:39:03 selector.py:142] Using Flashinfer backend.
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:03 selector.py:142] Using Flashinfer backend.
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:03 multiproc_worker_utils.py:218] Worker ready; awaiting tasks
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:04 utils.py:992] Found nccl from library libnccl.so.2
INFO 10-10 18:39:04 utils.py:992] Found nccl from library libnccl.so.2
INFO 10-10 18:39:04 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:04 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 10-10 18:39:04 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:04 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 10-10 18:39:04 shm_broadcast.py:241] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x7fc4842530d0>, local_subscribe_port=35177, remote_subscribe_port=None)
INFO 10-10 18:39:04 model_runner.py:1014] Starting to load model /mnt/home/Qwen2.5-14B-Instruct-GPTQ-Int4...
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:04 model_runner.py:1014] Starting to load model /mnt/home/Qwen2.5-14B-Instruct-GPTQ-Int4...
INFO 10-10 18:39:05 selector.py:142] Using Flashinfer backend.
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:05 selector.py:142] Using Flashinfer backend.
Loading safetensors checkpoint shards:   0% Completed | 0/5 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  20% Completed | 1/5 [00:00<00:03,  1.11it/s]
Loading safetensors checkpoint shards:  40% Completed | 2/5 [00:01<00:02,  1.15it/s]
Loading safetensors checkpoint shards:  60% Completed | 3/5 [00:02<00:01,  1.17it/s]
Loading safetensors checkpoint shards:  80% Completed | 4/5 [00:03<00:00,  1.15it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:04<00:00,  1.27it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:04<00:00,  1.21it/s]

INFO 10-10 18:39:10 model_runner.py:1025] Loading model weights took 9.0934 GB
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:10 model_runner.py:1025] Loading model weights took 9.0934 GB
INFO 10-10 18:39:10 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241010-183910.pkl...
INFO 10-10 18:39:10 model_runner_base.py:149] Completed writing input of failed execution to /tmp/err_execute_model_input_20241010-183910.pkl.
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:10 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241010-183910.pkl...
(VllmWorkerProcess pid=599366) INFO 10-10 18:39:10 multiproc_worker_utils.py:244] Worker exiting
Process SpawnProcess-1:
INFO 10-10 18:39:10 multiproc_worker_utils.py:124] Killing local vLLM worker processes
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1562, in execute_model
    self.attn_state.begin_forward(model_input)
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/attention/backends/flashinfer.py", line 256, in begin_forward
    model_input.attn_metadata.prefill_wrapper = state._get_prefill_wrapper(
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/attention/backends/flashinfer.py", line 116, in _get_prefill_wrapper
    self._prefill_wrapper = BatchPrefillWithPagedKVCacheWrapper(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 388, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 138, in from_engine_args
    return cls(
           ^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 78, in __init__
    self.engine = LLMEngine(*args,
                  ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 339, in __init__
    self._initialize_kv_caches()
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 474, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py", line 39, in determine_num_available_blocks
    num_blocks = self._run_workers("determine_num_available_blocks", )
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 185, in _run_workers
    driver_worker_output = driver_worker_method(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/worker.py", line 223, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/root/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1236, in profile_run
    self.execute_model(model_input, kv_caches, intermediate_tensors)
  File "/root/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
    raise type(err)(
TypeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20241010-183910.pkl): 'NoneType' object is not callable
[rank0]:[W1010 18:39:11.749973231 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 571, in <module>
    uvloop.run(run_server(args))
  File "/root/anaconda3/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/root/anaconda3/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 538, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/root/anaconda3/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 105, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/root/anaconda3/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 192, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start
/root/anaconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by jaspers1203** [comment]
I got the same error..

**Comment by luffydream** [comment]
same issue,too

**Comment by luffydream** [comment]
> Using Flashinfer backend.

maybe you can add a print tag in flashinfer.prefill import ; 
![image](https://github.com/user-attachments/assets/be6f4297-1fbf-4043-8ea8-b678ec5e444b)
