### ISSUE TITLE
[Bug]:       ptxas /tmp/tmpxft_002385ca_00000000-11_attention_kernels.compute_50.ptx, line 4986061; error   : Feature 'f16 arithemetic and compare instructions' requires .target sm_53 or higher

### ISSUE THREAD

**Issue by zhangfan-algo** [vllm-project/vllm#9269]
### Your current environment

</details>
![Uploading image.png…]()
![Uploading image.png…]()

### 🐛 Describe the bug

pip install git+https://github.com/vllm-project/vllm.git

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by zhangfan-algo** [comment]
ptxas /tmp/tmpxft_002385ca_00000000-11_attention_kernels.compute_50.ptx, line 4986061; error   : Feature 'f16 arithemetic and compare instructions' requires .target sm_53 or higher
      ptxas fatal   : Ptx assembly aborted due to errors
      [103/130] Building CUDA object CMakeFiles/_moe_C.dir/csrc/moe/marlin_kernels/marlin_moe_kernel_ku4.cu.o
      [104/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim128_bf16_causal_sm80.cu.o
      [105/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim64_bf16_causal_sm80.cu.o
      [106/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim160_fp16_sm80.cu.o
      [107/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim128_fp16_causal_sm80.cu.o
      [108/130] Building CUDA object CMakeFiles/_moe_C.dir/csrc/moe/marlin_kernels/marlin_moe_kernel_ku4b8.cu.o
      [109/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim160_bf16_sm80.cu.o
      [110/130] Building CUDA object CMakeFiles/_moe_C.dir/csrc/moe/marlin_kernels/marlin_moe_kernel_ku8b128.cu.o
      [111/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim64_fp16_causal_sm80.cu.o
      [112/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim224_bf16_sm80.cu.o
      [113/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim192_bf16_sm80.cu.o
      [114/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim192_fp16_sm80.cu.o
      [115/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim224_fp16_sm80.cu.o
      [116/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim32_bf16_sm80.cu.o
      [117/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim96_bf16_sm80.cu.o
      [118/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim96_fp16_sm80.cu.o
      [119/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim32_fp16_sm80.cu.o
      [120/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim256_bf16_sm80.cu.o
      [121/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim256_fp16_sm80.cu.o
      [122/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim128_bf16_sm80.cu.o
      [123/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim128_fp16_sm80.cu.o
      [124/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim64_bf16_sm80.cu.o
      [125/130] Building CUDA object /tmp/pip-req-build-emlb4c9c/.deps/vllm-flash-attn-build/CMakeFiles/vllm_flash_attn_c.dir/csrc/flash_attn/src/flash_fwd_split_hdim64_fp16_sm80.cu.o
      [126/130] Building CUDA object CMakeFiles/_C.dir/csrc/quantization/cutlass_w8a8/scaled_mm_c2x.cu.o
      [127/130] Building CUDA object CMakeFiles/_C.dir/csrc/quantization/gptq_marlin/gptq_marlin.cu.o
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 485, in <module>
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 235, in run
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-mnqvb2od/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 209, in build_extensions
        File "/mnt/pfs/zhangfan/system/test/conda/envs/swift/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '-j=128', '--target=_core_C', '--target=_moe_C', '--target=vllm_flash_attn_c', '--target=_C']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects

**Comment by jeejeelee** [comment]
Perhaps you can refer to :https://github.com/vllm-project/vllm/issues/9226

**Comment by zhangfan-algo** [comment]
> Perhaps you can refer to :#9226

I  can not fix this bug

**Comment by jeejeelee** [comment]
> > Perhaps you can refer to :#9226
> 
> I can not fix this bug

Have you tryed to use the solution proposed in https://github.com/vllm-project/vllm/pull/9254  or https://github.com/vllm-project/vllm/issues/9226#issuecomment-2405559136?

**Comment by ccjincong** [comment]
> > > Perhaps you can refer to :#9226
> > 
> > 
> > I can not fix this bug
> 
> Have you tryed to use the solution proposed in #9254 or [#9226 (comment)](https://github.com/vllm-project/vllm/issues/9226#issuecomment-2405559136)?

It worked for me.
