### ISSUE TITLE
[Installation]: vllm installation error

### ISSUE THREAD

**Issue by leoneyar** [vllm-project/vllm#9305]
### Your current environment

**env**
llamafactory version: 0.9.1.dev0
Platform: Linux-5.15.0-25-generic-aarch64-with-glibc2.35
Python version: 3.10.15
PyTorch version: 2.1.0 (NPU)
Transformers version: 4.45.0
Datasets version: 2.21.0
Accelerate version: 0.34.2
PEFT version: 0.12.0
TRL version: 0.9.6
NPU type: Ascend910B3
CANN version: 7.0.1
DeepSpeed version: 0.13.2

**error**
Collecting vllm<=0.6.2,>=0.4.3 (from llamafactory==0.9.1.dev0)
Using cached vllm-0.6.2.tar.gz (2.6 MB)
Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> [86 lines of output]
Collecting cmake>=3.26
Using cached cmake-3.30.4-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (6.4 kB)
Collecting ninja
Using cached ninja-1.11.1.1-py2.py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata (5.3 kB)
Collecting packaging
Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting setuptools>=61
Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Collecting setuptools-scm>=8.0
Using cached setuptools_scm-8.1.0-py3-none-any.whl.metadata (6.6 kB)
Collecting torch==2.4.0
Using cached torch-2.4.0-cp310-cp310-manylinux2014_aarch64.whl.metadata (26 kB)
Collecting wheel
Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
Collecting jinja2
Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock (from torch==2.4.0)
Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.8.0 (from torch==2.4.0)
Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.4.0)
Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.4.0)
Using cached networkx-3.4-py3-none-any.whl.metadata (6.3 kB)
Collecting fsspec (from torch==2.4.0)
Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting tomli>=1 (from setuptools-scm>=8.0)
Using cached tomli-2.0.2-py3-none-any.whl.metadata (10.0 kB)
Collecting MarkupSafe>=2.0 (from jinja2)
Using cached MarkupSafe-3.0.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (4.0 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.4.0)
Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading torch-2.4.0-cp310-cp310-manylinux2014_aarch64.whl (89.8 MB)
╸ 1.8/89.8 MB 9.0 kB/s eta 2:43:04
ERROR: Exception:
Traceback (most recent call last):
File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
yield
File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
data = self._fp_read(amt) if not fp_closed else b""
File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
return self._fp.read(amt) if amt is not None else self._fp.read()
File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
data: bytes = self.__fp.read(amt)
File "/root/miniconda3/envs/tsh-test/lib/python3.10/http/client.py", line 466, in read
s = self.fp.read(amt)
File "/root/miniconda3/envs/tsh-test/lib/python3.10/socket.py", line 717, in readinto
return self._sock.recv_into(b)
File "/root/miniconda3/envs/tsh-test/lib/python3.10/ssl.py", line 1307, in recv_into
return self.read(nbytes, buffer)
File "/root/miniconda3/envs/tsh-test/lib/python3.10/ssl.py", line 1163, in read
return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
      status = _inner_run()
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
      return self.run(options, args)
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
      return func(self, options, args)
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
      requirement_set = resolver.resolve(
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
      self.factory.preparer.prepare_linked_requirements_more(reqs)
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 554, in prepare_linked_requirements_more
      self._complete_partial_requirements(
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 469, in _complete_partial_requirements
      for link, (filepath, _) in batch_download:
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/network/download.py", line 184, in __call__
      for chunk in chunks:
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 55, in _rich_progress_bar
      for chunk in iterable:
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 65, in response_chunks
      for chunk in response.raw.stream(
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
      with self._error_catcher():
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/contextlib.py", line 153, in __exit__
      self.gen.throw(typ, value, traceback)
    File "/root/miniconda3/envs/tsh-test/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
      raise ReadTimeoutError(self._pool, None, "Read timed out.")
  pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

### How you are installing vllm

pip install vllm==0.5.0

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by leoneyar** [comment]
The graphics card is ASCEND

**Comment by Superskyyy** [comment]
@leoneyar it's a network problem, not something relate to vLLM itself.
