### ISSUE TITLE
[Usage]: After upgrading vLLM from version 0.5 to 0.6, the FastChat vllm_worker fails to load model weights when used with the openai_server deployment method. This issue may be related to vLLM 0.6 requiring pydantic > 2.9. Is this compatibility issue caused by FastChat 0.2.36 not being updated recently, making it unable to adapt to vLLM 0.6?

### ISSUE THREAD

**Issue by le0820** [vllm-project/vllm#9466]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Can you show the stack trace of your error?

**Comment by le0820** [comment]
> Can you show the stack trace of your error?
**my env**
vllm                              0.6.1.post1+cu118
torch                             2.4.0+cu118
pydantic                          2.9.2
pydantic_core                     2.23.4
pydantic-settings                 2.6.0
fschat                            0.2.36             /data2/dev/FastChat
**error in openai_server.log:**
2024-10-18 16:55:09 | ERROR | stderr | Traceback (most recent call last):
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-10-18 16:55:09 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 113, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
2024-10-18 16:55:09 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
2024-10-18 16:55:09 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 74, in app
2024-10-18 16:55:09 | ERROR | stderr |     await response(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 252, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2024-10-18 16:55:09 | ERROR | stderr |     raise exceptions[0]
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 255, in wrap
2024-10-18 16:55:09 | ERROR | stderr |     await func()
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 244, in stream_response
2024-10-18 16:55:09 | ERROR | stderr |     async for chunk in self.body_iterator:
2024-10-18 16:55:09 | ERROR | stderr |   File "/data2/dev/FastChat/fastchat/serve/openai_api_server.py", line 508, in chat_completion_stream_generator
2024-10-18 16:55:09 | ERROR | stderr |     async for content in generate_completion_stream(gen_params, worker_addr):
2024-10-18 16:55:09 | ERROR | stderr |   File "/data2/dev/FastChat/fastchat/serve/openai_api_server.py", line 693, in generate_completion_stream
2024-10-18 16:55:09 | ERROR | stderr |     async for raw_chunk in response.aiter_raw():
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 985, in aiter_raw
2024-10-18 16:55:09 | ERROR | stderr |     async for raw_stream_bytes in self.stream:
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 146, in __aiter__
2024-10-18 16:55:09 | ERROR | stderr |     async for chunk in self._stream:
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 238, in __aiter__
2024-10-18 16:55:09 | ERROR | stderr |     with map_httpcore_exceptions():
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2024-10-18 16:55:09 | ERROR | stderr |     self.gen.throw(typ, value, traceback)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2024-10-18 16:55:09 | ERROR | stderr |     raise mapped_exc(message) from exc
2024-10-18 16:55:09 | ERROR | stderr | httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
**error in vllm_worker.log**
2024-10-18 16:55:09 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-10-18 16:55:09 | ERROR | stderr | Traceback (most recent call last):
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-10-18 16:55:09 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 113, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
2024-10-18 16:55:09 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
2024-10-18 16:55:09 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
2024-10-18 16:55:09 | ERROR | stderr |     response = await f(request)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
2024-10-18 16:55:09 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
2024-10-18 16:55:09 | ERROR | stderr |     return await dependant.call(**values)
2024-10-18 16:55:09 | ERROR | stderr |   File "/data2/dev/FastChat/fastchat/serve/vllm_worker.py", line 217, in api_generate
2024-10-18 16:55:09 | ERROR | stderr |     output = await worker.generate(params)
2024-10-18 16:55:09 | ERROR | stderr |   File "/data2/dev/FastChat/fastchat/serve/vllm_worker.py", line 173, in generate
2024-10-18 16:55:09 | ERROR | stderr |     async for x in self.generate_stream(params):
2024-10-18 16:55:09 | ERROR | stderr |   File "/data2/dev/FastChat/fastchat/serve/vllm_worker.py", line 121, in generate_stream
2024-10-18 16:55:09 | ERROR | stderr |     async for request_output in results_generator:
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 859, in generate
2024-10-18 16:55:09 | ERROR | stderr |     async for output in await self.add_request(
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 106, in generator
2024-10-18 16:55:09 | ERROR | stderr |     raise result
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 48, in _log_task_completion
2024-10-18 16:55:09 | ERROR | stderr |     return_value = task.result()
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 733, in run_engine_loop
2024-10-18 16:55:09 | ERROR | stderr |     result = task.result()
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 673, in engine_step
2024-10-18 16:55:09 | ERROR | stderr |     request_outputs = await self.engine.step_async(virtual_engine)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 340, in step_async
2024-10-18 16:55:09 | ERROR | stderr |     outputs = await self.model_executor.execute_model_async(
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 185, in execute_model_async
2024-10-18 16:55:09 | ERROR | stderr |     output = await make_async(self.driver_worker.execute_model
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-10-18 16:55:09 | ERROR | stderr |     result = self.fn(*self.args, **self.kwargs)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 327, in execute_model
2024-10-18 16:55:09 | ERROR | stderr |     output = self.model_runner.execute_model(
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
2024-10-18 16:55:09 | ERROR | stderr |     return func(*args, **kwargs)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/multi_step_model_runner.py", line 389, in execute_model
2024-10-18 16:55:09 | ERROR | stderr |     model_input = self._advance_step(
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/multi_step_model_runner.py", line 488, in _advance_step
2024-10-18 16:55:09 | ERROR | stderr |     raise ValueError(
2024-10-18 16:55:09 | ERROR | stderr | ValueError: Multi-step not supported for attention backend: xformers. Set VLLM_ATTENTION_BACKEND to a value from ['flash-attn', 'flashinfer'].
2024-10-18 16:55:09 | ERROR | stderr | 
2024-10-18 16:55:09 | ERROR | stderr | The above exception was the direct cause of the following exception:
2024-10-18 16:55:09 | ERROR | stderr | 
2024-10-18 16:55:09 | ERROR | stderr | Traceback (most recent call last):
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-10-18 16:55:09 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 113, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
2024-10-18 16:55:09 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
2024-10-18 16:55:09 | ERROR | stderr |     await self.app(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
2024-10-18 16:55:09 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 62, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     raise exc
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 51, in wrapped_app
2024-10-18 16:55:09 | ERROR | stderr |     await app(scope, receive, sender)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 74, in app
2024-10-18 16:55:09 | ERROR | stderr |     await response(scope, receive, send)
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 252, in __call__
2024-10-18 16:55:09 | ERROR | stderr |     async with anyio.create_task_group() as task_group:
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
2024-10-18 16:55:09 | ERROR | stderr |     raise exceptions[0]
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 255, in wrap
2024-10-18 16:55:09 | ERROR | stderr |     await func()
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 244, in stream_response
2024-10-18 16:55:09 | ERROR | stderr |     async for chunk in self.body_iterator:
2024-10-18 16:55:09 | ERROR | stderr |   File "/data2/dev/FastChat/fastchat/serve/vllm_worker.py", line 121, in generate_stream
2024-10-18 16:55:09 | ERROR | stderr |     async for request_output in results_generator:
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 859, in generate
2024-10-18 16:55:09 | ERROR | stderr |     async for output in await self.add_request(
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 766, in add_request
2024-10-18 16:55:09 | ERROR | stderr |     self.start_background_loop()
2024-10-18 16:55:09 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 623, in start_background_loop
2024-10-18 16:55:09 | ERROR | stderr |     raise AsyncEngineDeadError(
2024-10-18 16:55:09 | ERROR | stderr | vllm.engine.async_llm_engine.AsyncEngineDeadError: Background loop has errored already.

**Comment by DarkLight1337** [comment]
To better debug the issue, can you run vLLM with `--disable-frontend-multiprocessing`? The current stack trace appears to obfuscate the error.
