### ISSUE TITLE
[Bug]: llama3.1 70B load error:  if rope_scaling is not None and rope_scaling["type"] != "su": KeyError: 'type'

### ISSUE THREAD

**Issue by cdhx** [vllm-project/vllm#9481]
### Your current environment

```
vllm: 0.5.5
GPU: A100 
```

### 🐛 Describe the bug

The error occurred when I loaded Llama 3.1 70B.

This error does not appear when I load qwen2.5 72B or llama 3.1 8B

```
python -m vllm.entrypoints.openai.api_server --model /mnt/workspace/hx/LLaMA-Factory/models/Llama-3.1-70B-Instruct/lora/Llama-3.1-70B-Instruct_sft_lora_deepspeed_offload_10k --served-model-name Llama-3.1-70B-Instruct_sft_lora_deepspeed_offload_10k --tensor-parallel-size 8 --port 40195 --chat-template /mnt/workspace/hx/Agent-all-in-one-eval-intern/core/llm/Llama-3.1-70B-Instruct_sft_lora_deepspeed_offload_10k.jinja

/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
warnings.warn(
Traceback (most recent call last):
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 186, in <module>
engine = AsyncLLMEngine.from_engine_args(
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 362, in from_engine_args
engine_config = engine_args.create_engine_config()
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 559, in create_engine_config
model_config = ModelConfig(
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/site-packages/vllm/config.py", line 133, in __init__
self.max_model_len = _get_and_verify_max_len(
File "/mnt/workspace/hx/anaconda3/envs/aio/lib/python3.10/site-packages/vllm/config.py", line 1216, in _get_and_verify_max_len
if rope_scaling is not None and rope_scaling["type"] != "su":
KeyError: 'type'

```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Which vLLM version are you using?

**Comment by cdhx** [comment]
> Which vLLM version are you using? Also, please print out your model config and post it here.

vllm : 0.5.5

**Comment by DarkLight1337** [comment]
Can you check whether the latest version of vLLM works for you?

**Comment by cdhx** [comment]
> Can you check whether the latest version of vLLM works for you?

same error, I user vllm=0.6.3

**Comment by DarkLight1337** [comment]
> Also, please print out your model config and post it here.

**Comment by cdhx** [comment]
Here is the config of my model
```
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "eos_token_id": [
    128001,
    128008,
    128009
  ],
  "hidden_act": "silu",
  "hidden_size": 8192,
  "initializer_range": 0.02,
  "intermediate_size": 28672,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 64,
  "num_hidden_layers": 80,
  "num_key_value_heads": 8,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 8.0,
    "low_freq_factor": 1.0,
    "high_freq_factor": 4.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.42.3",
  "use_cache": true,
  "vocab_size": 128256
}

```

**Comment by DarkLight1337** [comment]
> same error, I user `vllm=0.6.3`

Can you show the stack trace in this case? The latest version of vLLM should not access the "type" key anymore.

https://github.com/vllm-project/vllm/blob/main/vllm/config.py#L1737-1747

**Comment by cdhx** [comment]
It works; thanks for you kind and timely response~

**Comment by tszslovewanpu** [comment]
It works, thank you!
