### ISSUE TITLE
[Bug]: KeyError: 'layers.0.self_attn.qkv_proj.weight' 

### ISSUE THREAD

**Issue by yanan1116** [vllm-project/vllm#9595]
### Your current environment

vllm ver:  0.6.3.post1

### 🐛 Describe the bug

as suggested by vllm team, I set `tokenizer_mode= "mistral" if llm_name.startswith('mistralai') else 'auto'` in LLM engine. 
however, when loading mistral models, still face the error:

I have tried `mistralai/Ministral-8B-Instruct-2410` and `mistralai/Mistral-7B-Instruct-v0.3` and `mistralai/Mathstral-7B-v0.1`. all of them does not work.

Could you help look into this issue ? thanks.

> INFO 10-22 15:04:53 loader.py:1051] Loading weights with BitsAndBytes quantization.  May take a while ...
> INFO 10-22 15:04:53 weight_utils.py:243] Using model weights format ['*.safetensors']
> Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
> Loading safetensors checkpoint shards:  25% Completed | 1/4 [01:01<03:05, 61.73s/it]
> Loading safetensors checkpoint shards:  50% Completed | 2/4 [02:02<02:02, 61.22s/it]
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/ubuntu/moa/eval.py", line 169, in <module>
> [rank0]:     llm = LLM(model= args.llm_name, dtype='bfloat16', max_model_len= max_len, 
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
> [rank0]:     self.llm_engine = LLMEngine.from_engine_args(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 573, in from_engine_args
> [rank0]:     engine = cls(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 334, in __init__
> [rank0]:     self.model_executor = executor_class(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
> [rank0]:     self._init_executor()
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
> [rank0]:     self.driver_worker.load_model()
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py", line 183, in load_model
> [rank0]:     self.model_runner.load_model()
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1058, in load_model
> [rank0]:     self.model = get_model(model_config=self.model_config,
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
> [rank0]:     return loader.load_model(model_config=model_config,
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1148, in load_model
> [rank0]:     self._load_weights(model_config, model)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1082, in _load_weights
> [rank0]:     model.load_weights(qweight_iterator)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 582, in load_weights
> [rank0]:     loader.load_weights(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 203, in load_weights
> [rank0]:     autoloaded_weights = list(self._load_module("", self.module, weights))
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 182, in _load_module
> [rank0]:     yield from self._load_module(prefix,
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 169, in _load_module
> [rank0]:     module_load_weights(weights)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 397, in load_weights
> [rank0]:     param = params_dict[name]
> [rank0]: KeyError: 'layers.0.self_attn.qkv_proj.weight'
> Loading safetensors checkpoint shards:  50% Completed | 2/4 [02:02<02:02, 61.46s/it]

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by yananchen1989** [comment]
There is no error when loading and doing inference for llama series such as `microsoft/Phi-3-mini-128k-instruct`. 
Same code, no change except the llm_name passed into.

**Comment by yananchen1989** [comment]
As for Phi-3 series, such as `microsoft/Phi-3-mini-128k-instruct`

I encounter the error below, which is a bit similar to the error when using mistral series.
maybe related to `params_dict` ?

> INFO 10-22 15:24:43 model_runner.py:1056] Starting to load model microsoft/Phi-3-mini-128k-instruct...
> INFO 10-22 15:24:43 selector.py:247] Cannot use FlashAttention-2 backend due to sliding window.
> INFO 10-22 15:24:43 selector.py:115] Using XFormers backend.
> INFO 10-22 15:24:43 loader.py:1051] Loading weights with BitsAndBytes quantization.  May take a while ...
> INFO 10-22 15:24:43 weight_utils.py:243] Using model weights format ['*.safetensors']
> Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/ubuntu/moa/eval.py", line 169, in <module>
> [rank0]:     llm = LLM(model= args.llm_name, dtype='bfloat16', max_model_len= max_len, 
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
> [rank0]:     self.llm_engine = LLMEngine.from_engine_args(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 573, in from_engine_args
> [rank0]:     engine = cls(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 334, in __init__
> [rank0]:     self.model_executor = executor_class(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
> [rank0]:     self._init_executor()
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
> [rank0]:     self.driver_worker.load_model()
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py", line 183, in load_model
> [rank0]:     self.model_runner.load_model()
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1058, in load_model
> [rank0]:     self.model = get_model(model_config=self.model_config,
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
> [rank0]:     return loader.load_model(model_config=model_config,
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1148, in load_model
> [rank0]:     self._load_weights(model_config, model)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1082, in _load_weights
> [rank0]:     model.load_weights(qweight_iterator)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 582, in load_weights
> [rank0]:     loader.load_weights(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 203, in load_weights
> [rank0]:     autoloaded_weights = list(self._load_module("", self.module, weights))
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 182, in _load_module
> [rank0]:     yield from self._load_module(prefix,
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 169, in _load_module
> [rank0]:     module_load_weights(weights)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 414, in load_weights
> [rank0]:     param = params_dict[name]
> [rank0]: KeyError: 'layers.0.mlp.gate_up_proj.weight'

**Comment by yananchen1989** [comment]
for unsloth versions, such as `unsloth/Phi-3-medium-4k-instruct-bnb-4bit`  `unsloth/mistral-7b-instruct-v0.3-bnb-4bit`
all works fine.

**Comment by jeejeelee** [comment]
Perhaps it is similar to https://github.com/vllm-project/vllm/issues/9376#issuecomment-2416564017

**Comment by yananchen1989** [comment]
ok. i see. seems that this issue is widely recognized in the community.


here is my code for reproducing it.
```
llm = LLM(model= args.llm_name, dtype='bfloat16', max_model_len= max_len, 
            tensor_parallel_size=torch.cuda.device_count(), gpu_memory_utilization= args.gpu_memory_utilization, #seed=None,
            trust_remote_code=True,
            quantization="bitsandbytes", load_format="bitsandbytes", enforce_eager=True, 
            enable_lora=enable_lora,
            tokenizer_mode= "mistral" if args.llm_name.startswith('mistralai') else 'auto'
        )   
```

**Comment by yananchen1989** [comment]
`microsoft/Phi-3.5-mini-instruct` and `microsoft/Phi-3-medium-128k-instruct` also does not work.

**Comment by yananchen1989** [comment]
any wordaround ?

**Comment by lebronjamesking** [comment]
> for unsloth versions, such as `unsloth/Phi-3-medium-4k-instruct-bnb-4bit` `unsloth/mistral-7b-instruct-v0.3-bnb-4bit` all works fine.

Hi there,
I have been trying **Llama-3___3-70B-Instruct-bnb-4bit** with no luck. I get something like KeyError: 'layers.74.mlp.down_proj.weight.absmax'
