### ISSUE TITLE
[Bug]: 'EngineArgs' object has no attribute 'disable_log_requests

### ISSUE THREAD

**Issue by pbarker** [vllm-project/vllm#9708]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
 ~/ghq/github.com/agentsea/orign-py  main !2 ?4  poetry run python collect_env.py                                                                                                           ok  3.10.14 py  18:58:52
Collecting environment information...
WARNING 10-25 18:59:00 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 10-25 18:59:00 importing.py:10] Triton not installed; certain GPU-related functions will not be available.
/Users/patrickbarker/ghq/github.com/agentsea/orign-py/.venv/lib/python3.12/site-packages/vllm/connections.py:8: RuntimeWarning: Failed to read commit hash:
No module named 'vllm._version'
  from vllm.version import __version__ as VLLM_VERSION
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.30.5
Libc version: N/A

Python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-14.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-ml-py==12.560.30
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.45.2
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A (dev)
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

</details>

### 🐛 Describe the bug

When instantiating `AsyncLLMEngine` from `EngineArgs` it fails looking for a parameter that isn't available in `EngineArgs`

```
>>> from vllm import AsyncLLMEngine, EngineArgs

WARNING 10-25 18:50:57 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 10-25 18:50:57 importing.py:10] Triton not installed; certain GPU-related functions will not be available.
/Users/patrickbarker/ghq/github.com/agentsea/orign-py/.venv/lib/python3.12/site-packages/vllm/connections.py:8: RuntimeWarning: Failed to read commit hash:
No module named 'vllm._version'
  from vllm.version import __version__ as VLLM_VERSION

>>> engine_args = EngineArgs(model="Qwen/Qwen2-VL-2B-Instruct", trust_remote_code=True, device="cpu")

>>> engine = AsyncLLMEngine.from_engine_args(engine_args)

You are using a model of type qwen2_vl to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
WARNING 10-25 18:51:22 config.py:365] Async output processing is only supported for CUDA, TPU, XPU. Disabling it for other platforms.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrickbarker/ghq/github.com/agentsea/orign-py/.venv/lib/python3.12/site-packages/vllm/engine/async_llm_engine.py", line 677, in from_engine_args
    log_requests=not engine_args.disable_log_requests,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EngineArgs' object has no attribute 'disable_log_requests'. Did you mean: 'disable_log_stats'?
```

This error happens on both on my local Mac M3 and my remote Ubuntu 22.04 running an L40s GPU. It appears to occur on both `0.6.3` and `0.6.3.post1`.

I have a way around this but it appears to be a bug

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should pass `AsyncEngineArgs` to `AsyncLLMEngine.from_engine_args`, as indicated in the type annotation.

**Comment by pbarker** [comment]
Ah thank you! Could be helpful to update the examples in https://docs.vllm.ai/en/latest/dev/engine/async_llm_engine.html as that is what I grabbed an figured it was the standard args
