### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gpucce** [vllm-project/vllm#9738]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux release 8.7 (Ootpa) (x86_64)
GCC version: (Spack GCC) 12.2.0
Clang version: Could not collect
CMake version: version 3.30.5
Libc version: glibc-2.28

Python version: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM-64GB
GPU 1: NVIDIA A100-SXM-64GB
GPU 2: NVIDIA A100-SXM-64GB
GPU 3: NVIDIA A100-SXM-64GB

Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:            6
CPU MHz:             2601.000
CPU max MHz:         2601.0000
CPU min MHz:         800.0000
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.77
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.46.0
[pip3] triton==3.0.0
[conda] cuda-cccl                 12.1.109                      0    nvidia/label/cuda-12.1.1
[conda] cuda-command-line-tools   12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-compiler             12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-cudart               12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-cudart-dev           12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-cudart-static        12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-cuobjdump            12.1.111                      0    nvidia/label/cuda-12.1.1
[conda] cuda-cupti                12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-cupti-static         12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-cuxxfilt             12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-documentation        12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-driver-dev           12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-gdb                  12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-libraries            12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-libraries-dev        12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-libraries-static     12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-nsight               12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nsight-compute       12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-nvcc                 12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvdisasm             12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvml-dev             12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvprof               12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvprune              12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvrtc                12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvrtc-dev            12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvrtc-static         12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvtx                 12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-nvvp                 12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-opencl               12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-opencl-dev           12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-profiler-api         12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-sanitizer-api        12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] cuda-toolkit              12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-tools                12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] cuda-visual-tools         12.1.1                        0    nvidia/label/cuda-12.1.1
[conda] gds-tools                 1.6.1.9                       0    nvidia/label/cuda-12.1.1
[conda] libcublas                 12.1.3.1                      0    nvidia/label/cuda-12.1.1
[conda] libcublas-dev             12.1.3.1                      0    nvidia/label/cuda-12.1.1
[conda] libcublas-static          12.1.3.1                      0    nvidia/label/cuda-12.1.1
[conda] libcufft                  11.0.2.54                     0    nvidia/label/cuda-12.1.1
[conda] libcufft-dev              11.0.2.54                     0    nvidia/label/cuda-12.1.1
[conda] libcufft-static           11.0.2.54                     0    nvidia/label/cuda-12.1.1
[conda] libcufile                 1.6.1.9                       0    nvidia/label/cuda-12.1.1
[conda] libcufile-dev             1.6.1.9                       0    nvidia/label/cuda-12.1.1
[conda] libcufile-static          1.6.1.9                       0    nvidia/label/cuda-12.1.1
[conda] libcurand                 10.3.2.106                    0    nvidia/label/cuda-12.1.1
[conda] libcurand-dev             10.3.2.106                    0    nvidia/label/cuda-12.1.1
[conda] libcurand-static          10.3.2.106                    0    nvidia/label/cuda-12.1.1
[conda] libcusolver               11.4.5.107                    0    nvidia/label/cuda-12.1.1
[conda] libcusolver-dev           11.4.5.107                    0    nvidia/label/cuda-12.1.1
[conda] libcusolver-static        11.4.5.107                    0    nvidia/label/cuda-12.1.1
[conda] libcusparse               12.1.0.106                    0    nvidia/label/cuda-12.1.1
[conda] libcusparse-dev           12.1.0.106                    0    nvidia/label/cuda-12.1.1
[conda] libcusparse-static        12.1.0.106                    0    nvidia/label/cuda-12.1.1
[conda] libnpp                    12.1.0.40                     0    nvidia/label/cuda-12.1.1
[conda] libnpp-dev                12.1.0.40                     0    nvidia/label/cuda-12.1.1
[conda] libnpp-static             12.1.0.40                     0    nvidia/label/cuda-12.1.1
[conda] libnvjitlink              12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] libnvjitlink-dev          12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] libnvjpeg                 12.2.0.2                      0    nvidia/label/cuda-12.1.1
[conda] libnvjpeg-dev             12.2.0.2                      0    nvidia/label/cuda-12.1.1
[conda] libnvjpeg-static          12.2.0.2                      0    nvidia/label/cuda-12.1.1
[conda] libnvvm-samples           12.1.105                      0    nvidia/label/cuda-12.1.1
[conda] nsight-compute            2023.1.1.4                    0    nvidia/label/cuda-12.1.1
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.77                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.46.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.4
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
[4mGPU0	GPU1	GPU2	GPU3	NIC0	NIC1	NIC2	NIC3	CPU Affinity	NUMA Affinity[0m
GPU0	 X 	NV4	NV4	NV4	PXB	NODE	NODE	NODE	0-15	0
GPU1	NV4	 X 	NV4	NV4	NODE	PXB	NODE	NODE	0-15	0
GPU2	NV4	NV4	 X 	NV4	NODE	NODE	PXB	NODE	0-15	0
GPU3	NV4	NV4	NV4	 X 	NODE	NODE	NODE	PXB	0-15	0
NIC0	PXB	NODE	NODE	NODE	 X 	NODE	NODE	NODE		
NIC1	NODE	PXB	NODE	NODE	NODE	 X 	NODE	NODE		
NIC2	NODE	NODE	PXB	NODE	NODE	NODE	 X 	NODE		
NIC3	NODE	NODE	NODE	PXB	NODE	NODE	NODE	 X 		

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
```

</details>

### 🐛 Describe the bug

Running inference with Llama 3.1 405B instruct on 4 Nodes each with 4 A100 64 Gb, this are custom gpus for LEONARDO supercomputer in Italy, throws an error with all versions later than 0.5.4 while it does not error with that specific version, 0.5.4. @youkaichao 

Issue related to my message on slack, it is similar to one I had opened some time ago #8908, please let me know if some info about my environment is missing. 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
can you run the debugging script at https://docs.vllm.ai/en/latest/getting_started/debugging.html#incorrect-hardware-driver ?

**Comment by gpucce** [comment]
> can you run the debugging script at https://docs.vllm.ai/en/latest/getting_started/debugging.html#incorrect-hardware-driver ?

It errors like this if i run it using the same settings as the ones I use to run the model
2024-10-27 17:10:42,954 SUCC scripts.py:974 -- Ray runtime started.
2024-10-27 17:10:42,954 SUCC scripts.py:975 -- --------------------
2024-10-27 17:10:42,954 INFO scripts.py:977 -- To terminate the Ray runtime, run
2024-10-27 17:10:42,954 INFO scripts.py:978 --   ray stop
2024-10-27 17:10:42,954 INFO scripts.py:986 -- --block
2024-10-27 17:10:42,954 INFO scripts.py:987 -- This command will now block forever until terminated by a signal.
2024-10-27 17:10:42,954 INFO scripts.py:990 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly. Subprocesses exit with SIGTERM will be treated as graceful, thus NOT reported.
2024-10-27 17:10:40,144 INFO scripts.py:960 -- Local node IP: 10.1.0.172
2024-10-27 17:10:42,954 SUCC scripts.py:973 -- --------------------
2024-10-27 17:10:42,954 SUCC scripts.py:974 -- Ray runtime started.
2024-10-27 17:10:42,954 SUCC scripts.py:975 -- --------------------
2024-10-27 17:10:42,954 INFO scripts.py:977 -- To terminate the Ray runtime, run
2024-10-27 17:10:42,954 INFO scripts.py:978 --   ray stop
2024-10-27 17:10:42,955 INFO scripts.py:986 -- --block
2024-10-27 17:10:42,955 INFO scripts.py:987 -- This command will now block forever until terminated by a signal.
2024-10-27 17:10:42,955 INFO scripts.py:990 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly. Subprocesse
s exit with SIGTERM will be treated as graceful, thus NOT reported.
[2024-10-27 17:10:47,555 W 1815525 1815525] global_state_accessor.cc:463: Retrying to get node with node ID b65086df3fe7394bdc6877ea2bd1ab8e923a11d38459686c5f11af
b2
2024-10-27 17:10:46,878 INFO scripts.py:960 -- Local node IP: 10.1.0.194
2024-10-27 17:10:48,570 SUCC scripts.py:973 -- --------------------
2024-10-27 17:10:48,570 SUCC scripts.py:974 -- Ray runtime started.
2024-10-27 17:10:48,570 SUCC scripts.py:975 -- --------------------
2024-10-27 17:10:48,571 INFO scripts.py:977 -- To terminate the Ray runtime, run
2024-10-27 17:10:48,571 INFO scripts.py:978 --   ray stop
2024-10-27 17:10:48,571 INFO scripts.py:986 -- --block
2024-10-27 17:10:48,571 INFO scripts.py:987 -- This command will now block forever until terminated by a signal.
2024-10-27 17:10:48,571 INFO scripts.py:990 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly. Subprocesse
s exit with SIGTERM will be treated as graceful, thus NOT reported.
Traceback (most recent call last):
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/MGT2025-private/debugging_script.py", line 3, in <module>
    dist.init_process_group(backend="nccl")
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/MGT2025-private/conda_venv_vllm/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 7
9, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/MGT2025-private/conda_venv_vllm/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 9
3, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/MGT2025-private/conda_venv_vllm/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", l
ine 1361, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/MGT2025-private/conda_venv_vllm/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 24
6, in _env_rendezvous_handler
    rank = int(_get_env_or_raise("RANK"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo_scratch/large/userexternal/gpuccett/Repos/MGT2025-private/conda_venv_vllm/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 23
1, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

**Comment by gpucce** [comment]
For completeness, this is the output of a working run:

```text
INFO 10-27 16:21:47 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='/leonardo_scratch/large/userexternal/gpuccett/models/hf_llama/llama
-3.1-405b-instruct-hf', speculative_config=None, tokenizer='/leonardo_scratch/large/userexternal/gpuccett/models/hf_llama/llama-3.1-405b-instruct-hf', skip_tokeni
zer_init=False, tokenizer_mode=slow, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, ma
x_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=16, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=N
one, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines')
, observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/leonardo_scratch/large/userexternal/gpuccett/models/hf_llama/lla
ma-3.1-405b-instruct-hf, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 10-27 16:21:47 ray_gpu_executor.py:117] use_ray_spmd_worker: False
INFO 10-27 16:21:47 ray_gpu_executor.py:120] driver_ip: 10.8.0.182
INFO 10-27 16:30:57 utils.py:841] Found nccl from library libnccl.so.2
INFO 10-27 16:30:57 pynccl.py:63] vLLM is using nccl==2.20.5
ESC[36m(RayWorkerWrapper pid=3112876)ESC[0m INFO 10-27 16:30:57 utils.py:841] Found nccl from library libnccl.so.2
ESC[36m(RayWorkerWrapper pid=3112876)ESC[0m INFO 10-27 16:30:57 pynccl.py:63] vLLM is using nccl==2.20.5
WARNING 10-27 16:31:01 custom_all_reduce.py:69] Custom allreduce is disabled because this process group spans across nodes.
ESC[36m(RayWorkerWrapper pid=3352908, ip=10.8.0.187)ESC[0m WARNING 10-27 16:31:01 custom_all_reduce.py:69] Custom allreduce is disabled because this process group
 spans across nodes.
ESC[36m(RayWorkerWrapper pid=3946072, ip=10.8.0.183)ESC[0m INFO 10-27 16:30:57 utils.py:841] Found nccl from library libnccl.so.2ESC[32m [repeated 14x across clus
ter] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/conf
igure-logging.html#log-deduplication for more options.)ESC[0m
ESC[36m(RayWorkerWrapper pid=3946072, ip=10.8.0.183)ESC[0m INFO 10-27 16:30:57 pynccl.py:63] vLLM is using nccl==2.20.5ESC[32m [repeated 14x across cluster]ESC[0m
INFO 10-27 16:31:02 shm_broadcast.py:235] vLLM message queue communication handle: Handle(connect_ip='10.8.0.182', local_reader_ranks=[1, 2, 3], buffer=<vllm.dist
ributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x14ba180cfd70>, local_subscribe_port=45525, remote_subscribe_port=53863)
INFO 10-27 16:31:03 model_runner.py:720] Starting to load model /leonardo_scratch/large/userexternal/gpuccett/models/hf_llama/llama-3.1-405b-instruct-hf...
ESC[36m(RayWorkerWrapper pid=3352908, ip=10.8.0.187)ESC[0m INFO 10-27 16:31:03 model_runner.py:720] Starting to load model /leonardo_scratch/large/userexternal/gp
uccett/models/hf_llama/llama-3.1-405b-instruct-hf...
^MLoading safetensors checkpoint shards:   0% Completed | 0/191 [00:00<?, ?it/s]
^MLoading safetensors checkpoint shards:   1% Completed | 1/191 [00:19<1:01:06, 19.30s/it]
```
which then goes on to load the full model and generated the output.

**Comment by gpucce** [comment]
@youkaichao it seems to error

**Comment by gpucce** [comment]
This is the full output of the working run:

[llm_llama3_sender-8682296.txt](https://github.com/user-attachments/files/17534643/llm_llama3_sender-8682296.txt)

**Comment by youkaichao** [comment]
the test script uses `torchrun` to execute.

**Comment by youkaichao** [comment]
> this are custom gpus for LEONARDO supercomputer in Italy

since you use custom gpus, it is possible that ray does not handle it well. you can try to swap the ray versions. it might not be caused by vllm versions.

**Comment by gpucce** [comment]
@youkaichao here is the output of the debug_script

For version 0.5.4 with the respective installed ray:  
[llm_llama3_sender-8684158.txt](https://github.com/user-attachments/files/17534843/llm_llama3_sender-8684158.txt)

for version 0.6.3 with the respective installed ray:
[llm_llama3_sender-8684347.txt](https://github.com/user-attachments/files/17534855/llm_llama3_sender-8684347.txt)

**Comment by gpucce** [comment]
> Hi @gpucce 
> 
> Were you able to get this to work?
> 
> Also can you share `generate_article_ita_DICE.py`? I wanted to get an idea of what stuff were you doing in the file
> 
> 
> 
> I also noticed your message in the other thread (https://github.com/vllm-project/vllm/issues/6689#issuecomment-2273079677) and it seems you're also using SLURM and the cluster seems to have 4 GPUs per node. Can you share the script that worked for inference on multinodes via SLURM for Llama 405B?

I could only ever make it work on vllm 5.4 I'll look for the script

**Comment by aflah02** [comment]
Thanks @gpucce 😊

**Comment by serwansj** [comment]
@aflah02 did you make it work for newer versions by any chance?

**Comment by aflah02** [comment]
> [@aflah02](https://github.com/aflah02) did you make it work for newer versions by any chance?

Hi
I used SGLang instead as Ray is too much of a pain to deal with on SLURM

**Comment by youkaichao** [comment]
@aflah02 @gpucce if you just want to use SLURM or `torchrun`, vLLM also supports it now, see https://github.com/vllm-project/vllm/blob/main/examples/offline_inference/torchrun_example.py

**Comment by aflah02** [comment]
Thanks for sharing this @youkaichao 
Does this work across nodes too? Like if I want to run LLama 405B on 2 nodes with 8xH100s should I just set tensor_parallel_size to 16?

**Comment by youkaichao** [comment]
It should work across nodes, feel free to have a try.

> Like if I want to run LLama 405B on 2 nodes with 8xH100s should I just set tensor_parallel_size to 16?

yes, it should be TP=16.

**Comment by aflah02** [comment]
Thanks! Will try it out and report back
