### ISSUE TITLE
install from source failed

### ISSUE THREAD

**Issue by bohea** [vllm-project/vllm#981]
pip install vllm is ok 
but pip install -e . failed

error:
```
  Building wheel for vllm (pyproject.toml): started
  Building wheel for vllm (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [221 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/block.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/config.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/logger.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/outputs.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/sampling_params.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/sequence.py -> build/lib.linux-x86_64-cpython-39/vllm
      copying vllm/utils.py -> build/lib.linux-x86_64-cpython-39/vllm
      creating build/lib.linux-x86_64-cpython-39/vllm/core
      copying vllm/core/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/core
      copying vllm/core/block_manager.py -> build/lib.linux-x86_64-cpython-39/vllm/core
      copying vllm/core/policy.py -> build/lib.linux-x86_64-cpython-39/vllm/core
      copying vllm/core/scheduler.py -> build/lib.linux-x86_64-cpython-39/vllm/core
      creating build/lib.linux-x86_64-cpython-39/vllm/engine
      copying vllm/engine/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/engine
      copying vllm/engine/arg_utils.py -> build/lib.linux-x86_64-cpython-39/vllm/engine
      copying vllm/engine/async_llm_engine.py -> build/lib.linux-x86_64-cpython-39/vllm/engine
      copying vllm/engine/llm_engine.py -> build/lib.linux-x86_64-cpython-39/vllm/engine
      copying vllm/engine/ray_utils.py -> build/lib.linux-x86_64-cpython-39/vllm/engine
      creating build/lib.linux-x86_64-cpython-39/vllm/entrypoints
      copying vllm/entrypoints/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/entrypoints
      copying vllm/entrypoints/api_server.py -> build/lib.linux-x86_64-cpython-39/vllm/entrypoints
      copying vllm/entrypoints/llm.py -> build/lib.linux-x86_64-cpython-39/vllm/entrypoints
      creating build/lib.linux-x86_64-cpython-39/vllm/model_executor
      copying vllm/model_executor/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor
      copying vllm/model_executor/input_metadata.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor
      copying vllm/model_executor/model_loader.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor
      copying vllm/model_executor/utils.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor
      copying vllm/model_executor/weight_utils.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor
      creating build/lib.linux-x86_64-cpython-39/vllm/transformers_utils
      copying vllm/transformers_utils/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils
      copying vllm/transformers_utils/config.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils
      copying vllm/transformers_utils/tokenizer.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils
      creating build/lib.linux-x86_64-cpython-39/vllm/worker
      copying vllm/worker/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/worker
      copying vllm/worker/cache_engine.py -> build/lib.linux-x86_64-cpython-39/vllm/worker
      copying vllm/worker/worker.py -> build/lib.linux-x86_64-cpython-39/vllm/worker
      creating build/lib.linux-x86_64-cpython-39/vllm/entrypoints/openai
      copying vllm/entrypoints/openai/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/entrypoints/openai
      copying vllm/entrypoints/openai/api_server.py -> build/lib.linux-x86_64-cpython-39/vllm/entrypoints/openai
      copying vllm/entrypoints/openai/protocol.py -> build/lib.linux-x86_64-cpython-39/vllm/entrypoints/openai
      creating build/lib.linux-x86_64-cpython-39/vllm/model_executor/layers
      copying vllm/model_executor/layers/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/layers
      copying vllm/model_executor/layers/activation.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/layers
      copying vllm/model_executor/layers/attention.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/layers
      copying vllm/model_executor/layers/layernorm.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/layers
      copying vllm/model_executor/layers/sampler.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/layers
      creating build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/aquila.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/baichuan.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/bloom.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/falcon.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/gpt2.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/gpt_bigcode.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/gpt_j.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/gpt_neox.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/internlm.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/llama.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/mpt.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/opt.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      copying vllm/model_executor/models/qwen.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/models
      creating build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils
      copying vllm/model_executor/parallel_utils/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils
      copying vllm/model_executor/parallel_utils/parallel_state.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils
      creating build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils/tensor_parallel
      copying vllm/model_executor/parallel_utils/tensor_parallel/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils/tensor_parallel
      copying vllm/model_executor/parallel_utils/tensor_parallel/layers.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils/tensor_parallel
      copying vllm/model_executor/parallel_utils/tensor_parallel/mappings.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils/tensor_parallel
      copying vllm/model_executor/parallel_utils/tensor_parallel/random.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils/tensor_parallel
      copying vllm/model_executor/parallel_utils/tensor_parallel/utils.py -> build/lib.linux-x86_64-cpython-39/vllm/model_executor/parallel_utils/tensor_parallel
      creating build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      copying vllm/transformers_utils/configs/__init__.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      copying vllm/transformers_utils/configs/aquila.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      copying vllm/transformers_utils/configs/baichuan.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      copying vllm/transformers_utils/configs/falcon.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      copying vllm/transformers_utils/configs/mpt.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      copying vllm/transformers_utils/configs/qwen.py -> build/lib.linux-x86_64-cpython-39/vllm/transformers_utils/configs
      running build_ext
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'vllm.cache_ops' extension
      creating /tmp/vllm/build/temp.linux-x86_64-cpython-39
      creating /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc
      Emitting ninja build file /tmp/vllm/build/temp.linux-x86_64-cpython-39/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] c++ -MMD -MF /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/TH -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.9 -c -c /tmp/vllm/csrc/cache.cpp -o /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache.o -g -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cache_ops -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache.o
      c++ -MMD -MF /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache.o.d -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/TH -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.9 -c -c /tmp/vllm/csrc/cache.cpp -o /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache.o -g -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cache_ops -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                       from /tmp/vllm/csrc/cache.cpp:1:
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
         12 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      [2/2] /usr/local/cuda/bin/nvcc  -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/TH -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.9 -c -c /tmp/vllm/csrc/cache_kernels.cu -o /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache_kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_70,code=sm_70 --threads 8 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cache_ops -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache_kernels.o
      /usr/local/cuda/bin/nvcc  -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/TH -I/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.9 -c -c /tmp/vllm/csrc/cache_kernels.cu -o /tmp/vllm/build/temp.linux-x86_64-cpython-39/csrc/cache_kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_70,code=sm_70 --threads 8 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=cache_ops -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                       from /tmp/vllm/csrc/cache_kernels.cu:1:
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
         12 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      In file included from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                       from /tmp/vllm/csrc/cache_kernels.cu:1:
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
         12 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      In file included from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                       from /tmp/vllm/csrc/cache_kernels.cu:1:
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
         12 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      In file included from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                       from /tmp/vllm/csrc/cache_kernels.cu:1:
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
         12 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      In file included from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                       from /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                       from /tmp/vllm/csrc/cache_kernels.cu:1:
      /tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
         12 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/usr/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 160, in <module>
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/tmp/pip-build-env-q365kpnw/overlay/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vllm
Failed to build vllm
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects
```

**Comment by Abraham-Xu** [comment]
pip install ninja?

**Comment by bohea** [comment]
> pip install ninja?

Requirement already satisfied: ninja in /usr/local/lib/python3.9/dist-packages (1.11.1)

**Comment by bohea** [comment]
I fixed it by:
apt-get install python3.9-dev
