### ISSUE TITLE
[Usage]: How to use GLM4v multi_modal_data to make Multi-turn dialogue 

### ISSUE THREAD

**Issue by Jimmy-L99** [vllm-project/vllm#9833]
### Your current environment

vllm = 0.6.3post1

### How would you like to use vllm

According to the demo in GLM4 repository, the specification for multimodal input in vLLM is as follows:
```
 {
        "prompt": "input_text",
        "multi_modal_data": {
            "image": image
        }
    }
```
I want to know how to make a multi-turn dialogue such as:
```
import time
import asyncio
from PIL import Image
from typing import List, Dict
from vllm import SamplingParams, AsyncEngineArgs, AsyncLLMEngine

MODEL_PATH = 'path'


def load_model_and_tokenizer(model_dir: str):
    engine_args = AsyncEngineArgs(
        model=model_dir,
        tensor_parallel_size=2,
        dtype="bfloat16",
        trust_remote_code=True,
        gpu_memory_utilization=0.4,
        enforce_eager=True,
        worker_use_ray=True,
        disable_log_requests=True
        # 如果遇见 OOM 现象，建议开启下述参数
        # enable_chunked_prefill=True,
        # max_num_batched_tokens=8192
    )
    engine = AsyncLLMEngine.from_engine_args(engine_args)
    return engine


async def chat(): 
    engine = load_model_and_tokenizer(MODEL_PATH)
    params_dict = {
        "n": 1,
        "best_of": 1,
        "presence_penalty": 1.0,
        "frequency_penalty": 0.0,
        "temperature": 0.7,
        "top_p": 0.8,
        "top_k": -1,
        # "use_beam_search": False,
        # "length_penalty": 1,
        # "early_stopping": False,
        "ignore_eos": False,
        "max_tokens": 8192,
        "logprobs": None,
        "prompt_logprobs": None,
        "skip_special_tokens": True,
        "stop_token_ids" :[151329, 151336, 151338]
    }
    sampling_params = SamplingParams(**params_dict)
    image_path = "image_path"
    image = Image.open(image_path).convert("RGB")

    conversation = [
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "descript the image"},
                {"type": "image_url", "image_url": {"url": image}}
            ]
        },
        {
            "role": "assistant",
            "content": "xxxxxxxxxxxxx"
        },
        {
            "role": "user",
            "content": "What did I just ask you?"
        }
    ]
    message = conversation[-1]
    async for output in engine.generate(prompt=message, sampling_params=sampling_params, request_id=f"{time.time()}"):
        yield output.outputs[0].text

async def chat_print():
    current_length = 0
    async for output in chat():
        print(output[current_length:], end="", flush=True)
        current_length = len(output)

if __name__ == "__main__":
    asyncio.run(chat_print())
```

The` conversation` messages shown above are responses I received from an AI chatbot in document, but it seems that the provided test code doesn't work as expected.  
## So, I’d like to understand how this multimodal model actually conducts multi-turn conversations.

error as follows：
```
(RayWorkerWrapper pid=134033) INFO 10-30 15:02:25 model_runner.py:1056] Starting to load model /root/ljm/models/glm-4v-9b...
Loading safetensors checkpoint shards:   0% Completed | 0/15 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   7% Completed | 1/15 [00:00<00:06,  2.10it/s]
Loading safetensors checkpoint shards:  13% Completed | 2/15 [00:00<00:05,  2.32it/s]
Loading safetensors checkpoint shards:  20% Completed | 3/15 [00:01<00:05,  2.31it/s]
Loading safetensors checkpoint shards:  27% Completed | 4/15 [00:01<00:03,  2.86it/s]
Loading safetensors checkpoint shards:  33% Completed | 5/15 [00:01<00:03,  2.93it/s]
Loading safetensors checkpoint shards:  40% Completed | 6/15 [00:02<00:03,  2.55it/s]
Loading safetensors checkpoint shards:  47% Completed | 7/15 [00:02<00:03,  2.55it/s]
Loading safetensors checkpoint shards:  53% Completed | 8/15 [00:03<00:02,  2.35it/s]
Loading safetensors checkpoint shards:  60% Completed | 9/15 [00:03<00:02,  2.35it/s]
Loading safetensors checkpoint shards:  67% Completed | 10/15 [00:04<00:02,  2.29it/s]
Loading safetensors checkpoint shards:  73% Completed | 11/15 [00:04<00:01,  2.33it/s]
Loading safetensors checkpoint shards:  80% Completed | 12/15 [00:05<00:01,  2.15it/s]
Loading safetensors checkpoint shards:  87% Completed | 13/15 [00:05<00:00,  2.24it/s]
Loading safetensors checkpoint shards:  93% Completed | 14/15 [00:05<00:00,  2.21it/s]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:06<00:00,  2.35it/s]
Loading safetensors checkpoint shards: 100% Completed | 15/15 [00:06<00:00,  2.37it/s]

INFO 10-30 15:02:32 model_runner.py:1067] Loading model weights took 13.0680 GB
(RayWorkerWrapper pid=134033) INFO 10-30 15:02:33 model_runner.py:1067] Loading model weights took 13.0680 GB
WARNING 10-30 15:02:34 tokenizer.py:169] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
(RayWorkerWrapper pid=134033) WARNING 10-30 15:02:34 tokenizer.py:169] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 10-30 15:02:40 distributed_gpu_executor.py:57] # GPU blocks: 52090, # CPU blocks: 13107
INFO 10-30 15:02:40 distributed_gpu_executor.py:61] Maximum concurrency for 8192 tokens per request: 101.74x
ERROR 10-30 15:02:45 async_llm_engine.py:64] Engine background task failed
ERROR 10-30 15:02:45 async_llm_engine.py:64] Traceback (most recent call last):
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 54, in _log_task_completion
ERROR 10-30 15:02:45 async_llm_engine.py:64]     return_value = task.result()
ERROR 10-30 15:02:45 async_llm_engine.py:64]                    ^^^^^^^^^^^^^
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 851, in run_engine_loop
ERROR 10-30 15:02:45 async_llm_engine.py:64]     result = task.result()
ERROR 10-30 15:02:45 async_llm_engine.py:64]              ^^^^^^^^^^^^^
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 762, in engine_step
ERROR 10-30 15:02:45 async_llm_engine.py:64]     await self.engine.add_request_async(**new_request)
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 475, in add_request_async
ERROR 10-30 15:02:45 async_llm_engine.py:64]     preprocessed_inputs = await self.input_preprocessor.preprocess_async(
ERROR 10-30 15:02:45 async_llm_engine.py:64]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 572, in preprocess_async
ERROR 10-30 15:02:45 async_llm_engine.py:64]     return await self._process_decoder_only_prompt_async(
ERROR 10-30 15:02:45 async_llm_engine.py:64]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 512, in _process_decoder_only_prompt_async
ERROR 10-30 15:02:45 async_llm_engine.py:64]     prompt_comps = await self._extract_prompt_components_async(
ERROR 10-30 15:02:45 async_llm_engine.py:64]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 273, in _extract_prompt_components_async
ERROR 10-30 15:02:45 async_llm_engine.py:64]     parsed = parse_singleton_prompt(prompt)
ERROR 10-30 15:02:45 async_llm_engine.py:64]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-30 15:02:45 async_llm_engine.py:64]   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/parse.py", line 98, in parse_singleton_prompt
ERROR 10-30 15:02:45 async_llm_engine.py:64]     raise TypeError("inputs must be a string, TextPrompt, or TokensPrompt")
ERROR 10-30 15:02:45 async_llm_engine.py:64] TypeError: inputs must be a string, TextPrompt, or TokensPrompt
Exception in callback _log_task_completion(error_callback=<bound method...7faac0341190>>)(<Task finishe...okensPrompt')>) at /root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py:44
handle: <Handle _log_task_completion(error_callback=<bound method...7faac0341190>>)(<Task finishe...okensPrompt')>) at /root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py:44>
Traceback (most recent call last):
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 54, in _log_task_completion
    return_value = task.result()
                   ^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 851, in run_engine_loop
    result = task.result()
             ^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 762, in engine_step
    await self.engine.add_request_async(**new_request)
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 475, in add_request_async
    preprocessed_inputs = await self.input_preprocessor.preprocess_async(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 572, in preprocess_async
    return await self._process_decoder_only_prompt_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 512, in _process_decoder_only_prompt_async
    prompt_comps = await self._extract_prompt_components_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 273, in _extract_prompt_components_async
    parsed = parse_singleton_prompt(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/parse.py", line 98, in parse_singleton_prompt
    raise TypeError("inputs must be a string, TextPrompt, or TokensPrompt")
TypeError: inputs must be a string, TextPrompt, or TokensPrompt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 66, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/ljm/ChatGLM4/GLM-4/api_server_vLLM/vllm-4v-request-test.py", line 100, in <module>
[rank0]:     asyncio.run(chat_print())
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/runners.py", line 190, in run
[rank0]:     return runner.run(main)
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/runners.py", line 118, in run
[rank0]:     return self._loop.run_until_complete(task)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
[rank0]:     return future.result()
[rank0]:            ^^^^^^^^^^^^^^^
[rank0]:   File "/root/ljm/ChatGLM4/GLM-4/api_server_vLLM/vllm-4v-request-test.py", line 95, in chat_print
[rank0]:     async for output in chat():
[rank0]:   File "/root/ljm/ChatGLM4/GLM-4/api_server_vLLM/vllm-4v-request-test.py", line 90, in chat
[rank0]:     async for output in engine.generate(prompt=message, sampling_params=sampling_params, request_id=f"{time.time()}"):
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 1029, in generate
[rank0]:     async for output in await self.add_request(
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 112, in generator
[rank0]:     raise result
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 54, in _log_task_completion
[rank0]:     return_value = task.result()
[rank0]:                    ^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 851, in run_engine_loop
[rank0]:     result = task.result()
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 762, in engine_step
[rank0]:     await self.engine.add_request_async(**new_request)
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 475, in add_request_async
[rank0]:     preprocessed_inputs = await self.input_preprocessor.preprocess_async(
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 572, in preprocess_async
[rank0]:     return await self._process_decoder_only_prompt_async(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 512, in _process_decoder_only_prompt_async
[rank0]:     prompt_comps = await self._extract_prompt_components_async(
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 273, in _extract_prompt_components_async
[rank0]:     parsed = parse_singleton_prompt(prompt)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/parse.py", line 98, in parse_singleton_prompt
[rank0]:     raise TypeError("inputs must be a string, TextPrompt, or TokensPrompt")
[rank0]: TypeError: inputs must be a string, TextPrompt, or TokensPrompt
Future exception was never retrieved
future: <Future finished exception=TypeError('inputs must be a string, TextPrompt, or TokensPrompt')>
Traceback (most recent call last):
  File "/root/ljm/ChatGLM4/GLM-4/api_server_vLLM/vllm-4v-request-test.py", line 100, in <module>
    asyncio.run(chat_print())
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/ljm/ChatGLM4/GLM-4/api_server_vLLM/vllm-4v-request-test.py", line 95, in chat_print
    async for output in chat():
  File "/root/ljm/ChatGLM4/GLM-4/api_server_vLLM/vllm-4v-request-test.py", line 90, in chat
    async for output in engine.generate(prompt=message, sampling_params=sampling_params, request_id=f"{time.time()}"):
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 1029, in generate
    async for output in await self.add_request(
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 112, in generator
    raise result
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 54, in _log_task_completion
    return_value = task.result()
                   ^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 851, in run_engine_loop
    result = task.result()
             ^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 762, in engine_step
    await self.engine.add_request_async(**new_request)
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 475, in add_request_async
    preprocessed_inputs = await self.input_preprocessor.preprocess_async(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 572, in preprocess_async
    return await self._process_decoder_only_prompt_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 512, in _process_decoder_only_prompt_async
    prompt_comps = await self._extract_prompt_components_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/preprocess.py", line 273, in _extract_prompt_components_async
    parsed = parse_singleton_prompt(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/site-packages/vllm/inputs/parse.py", line 98, in parse_singleton_prompt
    raise TypeError("inputs must be a string, TextPrompt, or TokensPrompt")
TypeError: inputs must be a string, TextPrompt, or TokensPrompt
[rank0]:[W1030 15:02:48.932188587 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
/root/anaconda3/envs/glm4v-9b-vLLM0_6_3_post1/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should use `LLM.chat()` method:

```diff,py
+    llm = LLM(...)

     conversation = [
         {
             "role": "user",
             "content": [
                 {"type": "text", "text": "descript the image"},
                 {"type": "image_url", "image_url": {"url": image}}
             ]
         },
         {
             "role": "assistant",
             "content": "xxxxxxxxxxxxx"
         },
         {
             "role": "user",
             "content": "What did I just ask you?"
          }
     ]
-     message = conversation[-1]
-     async for output in engine.generate(prompt=message, sampling_params=sampling_params, request_id=f"{time.time()}"):
+     output = llm.chat(conversation, sampling_params=sampling_params)
+     print(output)
```

**Comment by Jimmy-L99** [comment]
@DarkLight1337 
The `LLM` class seems to be intended for offline inference, while` AsyncLLMEngine` appears to be more suitable for handling asynchronous and high-concurrency tasks. I’m interested in implementing an online service, so I'm using `AsyncLLMEngine`. If there are relevant usage examples for it?

**Comment by DarkLight1337** [comment]
You can use vLLM's OpenAI-compatible server via `vllm serve`. If you need to develop your custom server, take a look at our `OpenAIServing` classes under `vllm.entrypoints.openai`.

**Comment by Jimmy-L99** [comment]
Thanks for reply. I think that on the custom server side, two data structures are needed: one to convert incoming multimodal messages into a format like
 `{"prompt": "input_text", "multi_modal_data": { "image": image }}`
 for processing with `engine.generate`; and another to handle standard dialogue messages, formatted as:

`{"role": "assistant", "content": ""}, {"role": "user", "content": ""}`

**Comment by JavenGuo** [comment]
> Thanks for reply. I think that on the custom server side, two data structures are needed: one to convert incoming multimodal messages into a format like
> 
>  `{"prompt": "input_text", "multi_modal_data": { "image": image }}`
> 
>  for processing with `engine.generate`; and another to handle standard dialogue messages, formatted as:
> 
> 
> 
> `{"role": "assistant", "content": ""}, {"role": "user", "content": ""}`

Can share how to slove it?
